### ISSUE TITLE
Missing legalities in AtomicCards.json

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#1002]
#### Version(s) tested against
v5

#### Description of Bug
A bunch of cards have incorrectly had their legalities set to empty. No obvious pattern: Sylvan Library, Tahngarth, Taiga, Teferi's Response, etc.

**Comment by KingSupernova31** [comment]
Are you sure it's fixed? I just downloaded https://mtgjson.com/api/v5/AtomicCards.json and Sylvan Library still has `legalities: {}`. (Or does it just take a while for changes to propagate to the live API?)

**Comment by ZeldaZach** [comment]
It repopulated 9am EST daily
