### ISSUE TITLE
Arena cards have "A-" appended to the beginning of their name.

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#1005]
#### Version(s) tested against
v5

#### Description of Bug
The Arena version of Armory Veteran has a `name` field of `A-Armory Veteran`, which is incorrect. The card's name does not begin with "A-".

![image](https://user-images.githubusercontent.com/27539004/211225430-a33f723a-d2c9-4da4-b3ff-82f143f6ca15.png)

I believe all Arena cards have the same error.

**Comment by ZeldaZach** [comment]
This indication is for Alchemy rebalanced cards, as they have the same name but different text boxes and can become easily confusing. This was an intentional choice, as well as handled by Arena with the "A" symbol to indicate this.
