### ISSUE TITLE
Two card typos in YBRO

### ISSUE THREAD

**Issue by DJCatBlitz** [mtgjson/mtgjson#1006]
v5.2.0+20230109

Because the YBRO set is already is already released (?), I thought maybe two card typos were missed.

Melt Through
  form -> from

Legion of Clay
  'perpetually' missing
  I think it should have two seperate abilities instead of one with two effects

**Comment by ZeldaZach** [comment]
Fixed!

**Comment by DJCatBlitz** [comment]
Just to be sure that it's not missed. The multipurpose ability of Legion of Clay is really one ability? Or is it impossible to decide?
