### ISSUE TITLE
DMR baseSetSize seems incorrect

### ISSUE THREAD

**Issue by lyngbach** [mtgjson/mtgjson#1007]
#### Version(s) tested against
v5.2.0+20230110

#### Description of Bug
Looking at the Dominaria Remastered baseSetSize I noticed it got changed in an earlier mtgjson version from a more correct number to the now almost full set size of `456`, but shouldn't it instead be `261` as indicated on the cards maximum number?

![image](https://user-images.githubusercontent.com/3426543/211691650-292c4958-c83d-4be8-b72f-0ca05e656b35.png)

**Comment by ZeldaZach** [comment]
Thanks for catching this. The alt frames really messed things up heh. Will fix shortly :)
