### ISSUE TITLE
Some PHED cards missing

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#1009]
According to decklist from the wiki ( https://mtg.fandom.com/wiki/Secret_Lair_Drop_Series:_Secretversary_2021/Commander_deck ) PHED should have 5 more cards, which are not in mtgjson (or scryfall): "Krark's Thumb", "Okaun, Eye of Chaos", "Propaganda", "Stitch in Time", "Zndrsplt, Eye of Wisdom"

The original Wizards article https://magic.wizards.com/en/news/news/heads-i-win-tails-you-lose-commander-decklist-2021-11-18 seems to be 404ing now.

The moved one https://magic.wizards.com/en/news/announcements/heads-i-win-tails-you-lose-commander-decklist-2021-11-18 crashes with `Cannot read property '0' of undefined` most of the time, but it loads sometimes and it shows the same cards there.

**Comment by ZeldaZach** [comment]
So the 5 cards you're referring to are in the SLD since they have that set code. Will see what upstream thinks, but it's probably correct as-is unfortunately

**Comment by ZeldaZach** [comment]
@taw Confirmed this is correct as expected. The deck list should pull from SLD for those 5 cards, as appropriate.

**Comment by taw** [comment]
Weird but it works now https://mtg.wtf/deck/phed/heads-i-win-tails-you-lose
