### ISSUE TITLE
Add block to SetList

### ISSUE THREAD

**Issue by Garbee** [mtgjson/mtgjson#101]
Would it be accepted if the `block` property was added to the extra `SetList.json` file?

It would make setting up new instances which rely on the block sets belong to much easier to scaffold out. Especially since we then aren't pulling all the extra MB to get `AllSets.json` for testing a part of a system that only needs the set names and block association.

**Comment by ZeldaZach** [comment]
Do we still want to do this? Since blocks will be removed starting next set?

**Comment by fenhl** [comment]
They will still be relevant for various historical purposes.

**Comment by ZeldaZach** [comment]
Added in v4
