### ISSUE TITLE
Update PyPI release

### ISSUE THREAD

**Issue by dconathan** [mtgjson/mtgjson#1011]
The package on PyPI is `v0.4.0` and hasn't been updated since 2015 (assuming these two projects are the same / still connected)... any plans to have the latest versions on PyPI again?

https://pypi.org/project/mtgjson/

**Comment by ZeldaZach** [comment]
Hey there @dconathan! That package is unaffiliated with the official MTGJSON brand, and is linked back to https://github.com/mbr/pymtgjson.

We don't have an official SDK at the moment, but that could be something we look into for the future. Thanks for being a user of MTGJSON :)
