### ISSUE TITLE
DMR borderless cards are marked as alternative

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#1017]
the `IsAlternative` flag is set for all the borderless cards, while it should be not the case since there is a differing property (borderColor)

**Comment by ZeldaZach** [comment]
In some sense, IsAlternative was a precursor to what borderColor = borderless now achieves. I don't think this is an issue as-is currently.

**Comment by kodawah** [comment]
it is because isAlternative is reserved for otherwise indistinguishable card such as release launch

**Comment by ZeldaZach** [comment]
Should the IsAlternative field be marked for deprecation/removal? I know we have #679 in regards to this confusion that I seem to be having myself here heh

**Comment by kodawah** [comment]
that's orthogonal to the problem reported

to answer your question, you'd still need some sort of flag/identifier for in-set duplicates such as the CMR set/deck cards (example: Return to Dust)
