### ISSUE TITLE
modal dfcs have "isAlternative" marked on all back sides when present

### ISSUE THREAD

**Issue by ebbit1q** [mtgjson/mtgjson#1030]
#### Version(s) tested against

MTGJSON 5.2.0+20230128 AllPrintings.json

#### Description of Bug
all modal dfc cards in a set will have the "isAlternative" key present and set to True on the back side of the card only when any of the cards in that set should have this key set.
sets without alternatives are unaffected.
note that the front of the card will never have isAlternative set.

examples:
- Blightstep Pathway // Searstep Pathway KHM
- Shatterskull Smashing // Shatterskull, the Hammer Pass ZNR

instead these should have isAlternative removed on the first printing and have isAlternative set on both sides of the extra printing.

**Comment by ebbit1q** [comment]
I'd also like to mention this is a regression, it was not present in 5.1.0

**Comment by ZeldaZach** [comment]
Correct, this is indeed a regression. Will look into this soon.
