### ISSUE TITLE
JSON files crash Notepad++

### ISSUE THREAD

**Issue by G-e-n-e-v-e-n-s-i-S** [mtgjson/mtgjson#1035]
Opening a JSON file of more than 30 or 40 megabytes crashes Notepad++, very likely because all the data is written on a single line.

By contrast, Notepad++ can open gigabytes large JSON files from Scryfall without problem, because these files have one card per line.

Is there a way to get JSON files with one card per line?

Thanks for all your hard work!

**Comment by ZeldaZach** [comment]
We intentionally look to compress our data streams to be less bandwidth intensive. If you run the `jsonlint` program fr locally (which is what I do myself, when I need to debug a deployed file!), it will prettify the contents and make it viewable in other programs.

Here's a copy of mine if you need a boost:

```
#!/usr/bin/env python

import json
import pathlib
import sys


def main():
    files = pathlib.Path(sys.argv[1]).expanduser()

    if files.is_dir():
        for json_file in files.glob("**/*.json"):
            fix_file(json_file)
    elif files.is_file():
        fix_file(files)
    else:
        print(f"Unable to determine type: {files}")

def fix_file(json_file: pathlib.Path) -> None:
    with json_file.open(encoding="utf-8") as fp:
        content = json.load(fp)
    with json_file.open("w", encoding="utf-8") as fp:
        json.dump(content, fp, indent=4, sort_keys=True, ensure_ascii=False)

    print(f"Fixed {json_file}")

if __name__ == "__main__":
    main()
```
