### ISSUE TITLE
Duplicate multiverseIds for different frame printings in recent sets

### ISSUE THREAD

**Issue by guldfisk** [mtgjson/mtgjson#1037]
#### Version(s) tested against:
MTGJSON 5.2.0+20230211

In some recent sets (ONE, ONC and JJ2 as far as i can see), the different frame versions of the same card in the same set share the same multiverseId, even though they have different ones on gatherer.

Example:
the json lists Cankerbloom as printed twice in ONE with the multiverseId 602691, but on gatherer, it has two different ids:
https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=602691
https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=605007

**Comment by ZeldaZach** [comment]
Hey again! Just looking through, and I believe this issue has been addressed. If you're still seeing issues, please feel free to let me know!!
