### ISSUE TITLE
Printings from MB1 share multiverseIds with other cards from CMB1 and CMB2

### ISSUE THREAD

**Issue by guldfisk** [mtgjson/mtgjson#1038]
#### Version(s) tested against:
5.2.0+20230211

Cards from MB1 seems to have multiverseIds overlapping with the "test cards" (CMB1 + CMB2) (to be fair, the non test cards from MB1 does not seem to be listed on gatherer, so i am not sure what it should actually be, but i would rather it be nothing than overlap with another card.)

Example:
Eldrazi Devastator is listed as having a printing in MB1 in the json with multiverseId 476135, which is actually Five Kids in a Trench Coat, see: https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=476135

**Comment by ZeldaZach** [comment]
Hey there @guldfisk I believe this issue has been fixed. I see Eldrazi Devastator having an MID of 401867, which correctly links back on [Gatherer](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401867). Let me know if you spot any other issues, and thanks for your report!!
