### ISSUE TITLE
Zendikar Land Art Issues

### ISSUE THREAD

**Issue by ebmusicman84** [mtgjson/mtgjson#104]
The multiverse IDs for the following cards (collector's numbers) are flipped with their corresponding "a" sub variant: 230, 231, 232, 234, 237, 239, 240, 244, 248, 249.

So for example the multiverse id recorded for 230 is actually 230a and vice versa.  This is most likely an error on Gatherer's part.

**Comment by lsmoura** [comment]
Bummer...

I'll check and fix it!

**Comment by KingSupernova31** [comment]
Is this fixed in v4?

**Comment by ZeldaZach** [comment]
Should be, with the new data source.
