### ISSUE TITLE
duplicate TCGSKUs for the same productId when foil nonfoil finishes are separate

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#1045]
```json
    "9954df08-0479-5921-ac9d-dbe08360924c": [
      {
        "condition": "NEAR MINT",
        "language": "ENGLISH",
        "printing": "NON FOIL",
        "productId": 37828,
        "skuId": 396912
      },
      {
        "condition": "NEAR MINT",
        "language": "ENGLISH",
        "printing": "FOIL",
        "productId": 37828,
        "skuId": 399322
      },
```

9954df08-0479-5921-ac9d-dbe08360924c is the ID for Blast from the Past UNH FOIL, there is no NON FOIL printing for this uuid (the counterpart would be f1857a68-aec8-5a33-9d2f-969151456e5b - which has the same problem)

**Comment by ZeldaZach** [comment]
I'm looking further into this, and this appears to be a TCGPlayer issue. When we query for the SKUs associated with Blast from the Past, they return the following list:

<img width="648" alt="Screenshot 2023-04-01 at 11 43 30 PM" src="https://user-images.githubusercontent.com/7460172/229330105-1a06656a-94d2-41e3-843c-797ecf5cc719.png">

Which appears to show both foil and non-foil support. On TCGPlayer's website, we can see https://www.tcgplayer.com/product/37828?Language=English has both foil and non-foil linkages. 

I do understand it's a bit awkward. Maybe it makes sense to do some internal filtering to check the MTGJSON card's attributes for premium status and filter out these "extra" fields... but according to their API, the SKUs/ProductIds are correct as-is.

**Comment by kodawah** [comment]
hmm that doesn't seem to happen for 10E, 9ED, 8ED or 7ED where there are separate uuid (and tcg has a single listing page), are you suggesting it's a unique bug for this card?

**Comment by ZeldaZach** [comment]
Not necessarily just for this card, but I believe this holds true for the entire set itself
