### ISSUE TITLE
[EnumValues.json] Add new field, legalities enum

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgjson#1046]
Id like the enumeration for values available to a play format legality. I do not need them for every upper level format, just all the possible values for any legality, however based on the current structure of the EnumValues.json we need to nest at least once. Example:

```json
"data": {
  "legalities": {
    "legality": [
      "Legal",
      "Banned",
      "Restricted"
    ]
  }
}
```

I think those are the only values returned.

**Comment by ZeldaZach** [comment]
I don't have a great way of doing this unfortunately. That file is very finicky to begin with. Is this a necessity?
