### ISSUE TITLE
Support Serialized as another card variation.

### ISSUE THREAD

**Issue by t102** [mtgjson/mtgjson#1048]
Can MTGJSON be extended to support serialized variations of cards?  More and more of these are being added into the new sets.

For example, for Bone Saw, the serial variation is:

TCGPlayer: https://www.tcgplayer.com/product/452442/magic-the-brothers-war-retro-frame-artifacts-bone-saw-schematic-serial-numbered
StarCity: https://starcitygames.com/bone-saw-sgl-mtg-brr3-070-enf/?sku=SGL-MTG-BRR3-070-ENF1
Cardmarket: https://www.cardmarket.com/en/Magic/Products/Singles/Retro-Frame-Artifacts/Bone-Saw-V3

**Comment by ZeldaZach** [comment]
I like the idea, as we already have separate printings for these serialized cards. I'll see if upstreams are interested in supporting this, and if not I'll look into a homebrew solution!

**Comment by kodawah** [comment]
this is supported upstream, via the `serialized` promo type

**Comment by ZeldaZach** [comment]
Neat, then it should be auto pulled in for card types. I still want to support the number of serialized versions, but that will come soon.
