### ISSUE TITLE
mtgArenaID missing for some Explorer Anthology 2 cards

### ISSUE THREAD

**Issue by cwintermute** [mtgjson/mtgjson#1049]
#### Version(s) tested against

Tested with the latest AllPrintings.sqlite as of 03/20/23.

#### Description of Bug

Was attempting to parse Magic Arena logs and came across cards that are missing their mtgArenaId value in the cards table.

Shaman of the Pack - 61505
Nykthos, Shrine to Nyx - 54769

Please let me know if there is any other information you need

**Comment by ZeldaZach** [comment]
Hey there! I've gone through and it appears almost all cards are missing arena IDs. Will look into getting this addressed!

**Comment by ZeldaZach** [comment]
This has been fixed :)
