### ISSUE TITLE
Translations property of every Set is empty

### ISSUE THREAD

**Issue by sobriarczero** [mtgjson/mtgjson#1056]
#### Version(s) tested against
MTGJSON 5.2.1+20230409

#### Description of Bug
All Sets have an empty "translations" field, it is shown like empty object "{}".

I have tried several times over the last month with this file: https://mtgjson.com/api/v5/SetList.json
But it happens in all files that the definition of "Set" is included.

**Comment by ZeldaZach** [comment]
I have noticed this broke a bit ago, and I do want to investigate further into this.

**Comment by ZeldaZach** [comment]
Reason is due to better bot protection by MKM. I have downloaded a copy of everything and will look to compile a manual set for this soon.
