### ISSUE TITLE
null-able json items are not null'ed

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#1057]
the following fields

set.sealedProduct.subtype
set.sealedProduct.releaseDate
set.tokens
set.translations
card.colors
card.colorIdentity
card.foreignData
card.supertypes
card.rulings

are always exported in the allprintings file, even when they're empty
it would be nice if they got removed during marshaling

**Comment by ZeldaZach** [comment]
I've [intentionally marked these fields](https://github.com/mtgjson/mtgjson/blob/master/mtgjson5/classes/mtgjson_card.py#L120) to be included, and they're not marked optional: https://mtgjson.com/data-models/card-set/#colors

**Comment by kodawah** [comment]
@ZeldaZach the only reason to keep them non-nullable is to make the file human readable but it has been stated that the json file is not supposed to be readable - so what gives?

assuming readability is the goal, i can see why fields like `colors` are non-nullable, but a "null" releaseDate is not any informative
