### ISSUE TITLE
IKO Collector Booster lists an arena-only card in Godzilla

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#1058]
there is a Void Beckoner 373A (UUID 15c513ba-f3be-56b0-b991-bbde1ecf5b01) listed in the godzilla sheet, but this is incorrect, since it never got printed into paper

i don't know if it's an upstream data issue (cc @taw), or if it's something wrong during import - is there any validation for only-only cards (ie by looking at `card.IsOnlineOnly`)?

**Comment by taw** [comment]
@axxroytovu Do you want to take a look at it?

@kodabb There's no specific validation for is:paper and is:arena, such issues come up extremely rarely. All queries are filtered by is:foil and is:nonfoil, as that's more common.

**Comment by axxroytovu** [comment]
I've been collecting known issues here: https://github.com/taw/magic-sealed-data/issues/32#issuecomment-1507705885

I added this one. I already brought up to Scryfall that their tagging is wrong for that variant.

**Comment by axxroytovu** [comment]
Fixed with https://github.com/taw/magic-search-engine/pull/215

**Comment by taw** [comment]
Is this done now?

**Comment by axxroytovu** [comment]
Is complete. You can verify https://mtg.wtf/pack/iko-collector

**Comment by kodawah** [comment]
all good, thank you
