### ISSUE TITLE
ONE baseSetSize seems incorrect

### ISSUE THREAD

**Issue by davidmartos96** [mtgjson/mtgjson#1060]
#### Version(s) tested against
5.2.1+20230420

#### Description of Bug

It calculated 284, when in reality it should be 271.
Maybe the promotypes "promopack" and/or "bundle" should be included when checking "boosterfun" in the `set_builder.py`.

The 284 comes from including the following blocks of cards.

272-276: Basic lands not counted towards the main set https://scryfall.com/card/one/272/plains
They have the promotype "bundle"

277-283: Promo packs: https://scryfall.com/card/one/277/ossification

**Comment by kodawah** [comment]
I sent a PR to override the number for now, up to @ZeldaZach to decide if there needs to be more work in `set_builder.py`

**Comment by davidmartos96** [comment]
On a similar note, ONC size shows up as 30, but it should be 28.

The problem is that the display commanders are being considered:

Card 28 https://scryfall.com/card/onc/28/urtet-remnant-of-memnarch

Display commanders
Card 29 https://scryfall.com/card/onc/29/ixhel-scion-of-atraxa
Card 30 https://scryfall.com/card/onc/30/neyali-suns-vanguard

They have the promo_type as "thick"

Maybe some additional exclusions improve the current inferred sizes for future sets :smile: @ZeldaZach

**Comment by kodawah** [comment]
@davidmartos96 any chance you could make a PR about that? It'd be just like the one I sent
