### ISSUE TITLE
Wrong CardMarket prices in AllPrices.json?

### ISSUE THREAD

**Issue by figiel** [mtgjson/mtgjson#1062]
#### Version(s) tested against
5.2.1+20230422 (public)

#### Description of Bug

The prices in AllPrices.json don't seem to match prices shown on the CardMarket website and therefore aren't very useful. I noticed this on a couple of cards, but consider this example where there's exactly one version of the card:

```
$ cat AllIdentifiers.json | jq '.data[]|select(.name=="Shell of the Last Kappa")|(.name,.identifiers["mcmId"],.uuid)'
"Shell of the Last Kappa"
"12182"
"cad67ee8-2d44-5eb6-8f08-0e876240a137"
```

```
$ cat AllPrices.json | jq '.data["cad67ee8-2d44-5eb6-8f08-0e876240a137"]["paper"]["cardmarket"]["retail"]["normal"]'
{
  "2023-01-22": 0.19,
  "2023-01-23": 0.29,
// cut
  "2023-04-10": 0.18,
  "2023-04-11": 0.18,
  "2023-04-12": 0.18,
  "2023-04-13": 0.18,
  "2023-04-15": 0.14,
  "2023-04-16": 0.24,
  "2023-04-17": 0.24,
  "2023-04-18": 0.24,
  "2023-04-19": 0.24,
  "2023-04-20": 0.24,
  "2023-04-21": 0.2,
  "2023-04-22": 0.2
}
```

When I look at the CardMarket's [page](https://www.cardmarket.com/en/Magic/Products/Singles/Champions-of-Kamigawa/Shell-of-the-Last-Kappa) for this card on 2023-04-23 I can see that:

- There is no price for 2023-04-22 on the graph,
- For 2023-04-21 the actual price on the chart on the website is 0.15 EUR (25% lower than 0.20 EUR shown in AllPrices.json),
- Dates 2023-04-15, 2023-04-16, 2023-04-17, 2023-04-18 and 2023-04-20 don't have a price on the chart, but are present in AllPrices.json,
- 2023-04-14 is present on the website but it's missing from the AllPrices.json,
- 2023-04-13 is present in both places but there's again a relevant difference: 0.14 EUR on the web page and 0.18 in the AllPrices.json
- There are differences of values on other days, and they are not just shifted by a day or two, they are completely different.

I don't understand where does this disparity come from but I guess it maybe because of "AVG1" and "Foil AVG1" values [are taken](https://github.com/mtgjson/mtgjson/blob/799c81f5448b137f1041930f8bb3c74b383b3d34/mtgjson5/providers/cardmarket/monolith.py#L105-L106) from the export from MCM. While MCM documents that "Avg. Sell Price" and "Foil Sell" have the values as visible on the website. But I can't really say as I don't have access to MCM API and the documentation they provide doesn't seem clear enough.

For comparison Scryfall on their website and API shows the same value as visible on MCM website (however without historical data).

**Comment by kodawah** [comment]
> But I can't really say as I don't have access to MCM API and the documentation they provide doesn't seem clear enough.

this would be better forwarded to cardmarket support, as end user their API are a pain to use and should really modernize their whole system

**Comment by ZeldaZach** [comment]
Unfortunately this feels a bit out of scope for what we can support on our side, as we have to have a source of truth somewhere.
