### ISSUE TITLE
Feature request: comprehensive rules dataset

### ISSUE THREAD

**Issue by JayDi85** [mtgjson/mtgjson#1064]
It's can be useful to have actual comprehensive rules in json format, indexed by numbers so third party apps can use it in chats or other services. Example: write `!302.2` to show all related rules.

**Comment by ZeldaZach** [comment]
This is something I'd be interesting in supporting. Might be tricky, but I'm open to it. Gimme some time :)

**Comment by KingSupernova31** [comment]
https://api.academyruins.com/cr

**Comment by ZeldaZach** [comment]
Since there's already a 3rd party service that supports this (Thanks for pointing this out) I don't feel reinventing the wheel benefits us here. However, I will reach out and see if they want to collaborate on this functionality to be incorporated into MTGJSON
