### ISSUE TITLE
Add sets with no associated cards

### ISSUE THREAD

**Issue by axxroytovu** [mtgjson/mtgjson#1070]
Is there a way to forcibly build sets that don't have any cards associated with them? There are products with set codes that are entirely reprints. Sets in question:
- Q01-Q05: [Challenger deck sets 1-5](https://www.tcgplayer.com/search/magic/challenger-decks?productLineName=magic&setName=challenger-decks&view=grid)
- DD3: [Duel Decks Anthology](https://www.tcgplayer.com/search/magic/duel-decks-anthology?productLineName=magic&setName=duel-decks-anthology&view=grid&ProductTypeName=Magic+Deck+Pack&page=1)
- GK1 & GK2: [Guild Kits](https://www.tcgplayer.com/search/magic/ravnica-allegiance-guild-kits?productLineName=magic&setName=ravnica-allegiance-guild-kits&view=grid&ProductTypeName=Sealed+Products&page=1)

Other products that don't have associated sets and need a home:
- [Arena Starter Kits](https://www.tcgplayer.com/search/magic/arena-starter-kit?productLineName=magic&setName=arena-starter-kit&view=grid)
- [Holiday Gift Boxes](https://www.tcgplayer.com/search/magic/gift-boxes-and-promos?productLineName=magic&setName=gift-boxes-and-promos&view=grid&ProductTypeName=Sealed+Products|Booster+Box&page=1)

**Comment by ZeldaZach** [comment]
We could add a basic override to the system for something like this, but I'm not sure how much value these type of sets will fit into the main system, as we don't have a default source of truth. We can make our own, sure, but what value do these sets provide to most folks who scan the full card database? Is this just a placeholder to hold purchasable entities?

**Comment by axxroytovu** [comment]
To me it's a matter of completeness, useful or otherwise. These sets have decks, packs, and sealed product that are currently not associated with anything or are wrongly associated with a different set. For people who are scanning for any of those things, they will be incomplete or incorrect.

**Comment by axxroytovu** [comment]
I just noticed that this issue is a subset of @kodabb 's list here: https://github.com/mtgjson/mtgjson/issues/799

**Comment by ZeldaZach** [comment]
Kinda a dupe of #786 ?

**Comment by axxroytovu** [comment]
True, I didn't notice that issue. Do you want me to consolidate these into one issue (close this one and move to #786) or just leave both open?

**Comment by kodawah** [comment]
> Kinda a dupe of https://github.com/mtgjson/mtgjson/issues/786 ?

I dont think this is a dupe - the set FWB is missing and it's a whole edition, the Q01-Q05 sets are reprints containing cards with the same edition symbol, so they are not "editions" but rather sealed product that should appear *somewhere* (I'm actually unclear where, maybe we could match year they came out?)

GK1 and GK2 are existing editions, do they just miss product information?

**Comment by axxroytovu** [comment]
Work should be done with https://github.com/mtgjson/mtgjson/pull/1098

**Comment by ZeldaZach** [comment]
Fixed in #1098
