### ISSUE TITLE
Multiple sets map to the same TCGplayer ID and duplicates sealed products

### ISSUE THREAD

**Issue by mallardduck** [mtgjson/mtgjson#1075]
#### Version(s) tested against
Verseion: `5.2.1+20230515`

#### Description of Bug
After I ingest the `SetList.json` file into my database I'm seeing that some of my `SealedProducts` entries are duplicates. Specifically I see lots of duplicates of "Judge Promo Pack 2014 Full Art Land Set" all with different Set IDs.

Looking into the Sets table I quickly noticed that all but 5 of the `Judge Gift Card {YEAR}` are set to the same `tcgplayer_id`. Looking at TCGplayer they currently only have a sealed product for the 2014 year. So it seems likely that all the duplicates not matching year 2014 are errant.

Digging further I realized that Scryfall is showing incorrect data for this too. So that may play a factor here to explain the source of the errors, tho I'm not sure.

Here's an example of the issue in question, showing the 2014 sealed pack as a product on the 2018 promo set.

```
→ cat ./blobs/SetList.json |jq '.data[] | select(.code=="J18")'
{
  "baseSetSize": 8,
  "block": "Judge Gift Cards",
  "code": "J18",
  "isFoilOnly": true,
  "isOnlineOnly": false,
  "keyruneCode": "PMEI",
  "languages": [
    "English"
  ],
  "name": "Judge Gift Cards 2018",
  "releaseDate": "2018-01-01",
  "sealedProduct": [
    {
      "category": "booster_pack",
      "identifiers": {
        "tcgplayerProductId": "448319"
      },
      "name": "Judge Promo Pack 2014 Full Art Land Set",
      "purchaseUrls": {
        "tcgplayer": "https://mtgjson.com/links/d12d78a807d20473"
      },
      "releaseDate": null,
      "subtype": "set",
      "uuid": "a0b85d64-0b22-5d96-b8fb-f1656e9940b5"
    }
  ],
  "tcgplayerGroupId": 62,
  "totalSetSize": 8,
  "translations": {},
  "type": "promo"
}
```

**Comment by axxroytovu** [comment]
I think this maps to a bigger want, where TCGplayer is particularly bad at categorizing its sealed products into the correct set. E.g. [The Brothers' War Jumpstart Box Case](https://www.tcgplayer.com/product/449721/magic-dominaria-united-the-brothers-war-jumpstart-booster-box-case?xid=pi1b12b274-a00f-4ec6-a9a8-fbbf5c2a8032&page=1&Language=English) is in the DMU products for some reason.

**Comment by mallardduck** [comment]
@axxroytovu - I'm unclear on what relationship (if any) the MTGjson data and that of Scryfall have. I think I've seen code that implies this project pulls in data from Scryfall. But I've also seen Scryfall listed as an "MTGJSON powered app". So maybe it's a bit of "it goes both ways".

That said I was confused if the issue (within MTGJSON context) came from Scryfall, or if potentially scryfall was encountering the same issue I was. However you can compare these 3 sets JSON on scryfall to see what I mean:

- [Correct, (i think) TCGplayer ID on year 2014](https://api.scryfall.com/sets/J14)
- [Incorrect, duplicate TCGplayer ID on 2018](https://api.scryfall.com/sets/J18)
- [Correct, excluded TCGplayer ID on 2020](https://api.scryfall.com/sets/J20)

**Comment by axxroytovu** [comment]
Linking to this, the TCGPlayer ID for the 30a set is wrong, at least for the sealed products.

**Comment by axxroytovu** [comment]
Should be resolved with https://github.com/mtgjson/mtg-sealed-content/pull/92

**Comment by kodawah** [comment]
i think this can be closed right?
