### ISSUE TITLE
Support Decks inside of Set Files & AllPrintings

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#1076]
It would be nice to have decklists embedded in the main AllPrintings data model for ease of access when determining ev and other properties. I see a couple of ways to do this

1. add the current decklists in the set data
2. add a fixed sheet in Booster, with custom Contents
3. add a separate data format for decks with just a (fixed) sheet

I'm favoring #2 because it would allow to reuse parsing format used for normal products, but I'd like to hear more thoughts - cc @ZeldaZach @taw @axxroytovu

**Comment by ZeldaZach** [comment]
I've been thinking about this for a bit, and have some rough ideas that could be feasible

The first idea is to follow a very similar model to the booster model, and have "sheets" of cards that help discern the types around for the main and sideboard of each deck. This would be tricky to manage without an external resource, as I'd have to compile the main set, compile the deck file, then retroactively go back and re-compile the main set. This entity would be added along side "booster" instead of adding to booster itself.
```
"decks": [
{
  "name": "Deck Name 1",
  "contents": {
    "mainDeckNonFoil": {
      "cards": {
        "01b9cc89-6e90-5dbc-8daf-530d9bb23be0": 2,
        "031e3c5a-bf28-5f69-9568-ac2b09622764": 2,
        "1647a4e3-119f-54fa-9c34-4e47f6b46be4": 2,
        "1967ceae-7733-5eea-bd4b-a479deee287b": 3
      },
      "foil": false,
      "totalWeight": 1,
      "isMainBoard": true
    },
    "mainDeckFoil": {
      "cards": {
        "01b9cc89-6e90-5dbc-8daf-530d9bb23be0": 1
      },
      "foil": true,
      "totalWeight": 1,
      "isMainBoard":  true
    }
  }
}
],
```

The other ideas I have aren't as fledged out yet, so I want to see what folks think of this and allow them to propose their own ideas for this update

**Comment by taw** [comment]
Do you need any support from me, or is the data in the current export format enough?

**Comment by kodawah** [comment]
example structure from c20 (with random data)

```json
    "C20": {
      "baseSetSize": 322,
      "block": "Commander",
      "booster":
        "commander deck 1": {
          "boosters": [
            {
              "contents": {
                "list_of_nonfoil_cards": 17,
                "list_of_foil_cards": 2,
                "list_of_random_cards": 1
              },
              "weight": 1
            }
          ],
          "boostersTotalWeight": 10,
          "name": "commander 2020 commander deck 1",
          "sheets": {
            "list_of_nonfoil_cards": {
              "cards": {
                "2758d906-f551-5c62-8069-fc7f9ced5914": 1,
                ...
             },
              "fixed": true,
              "foil": false,
              "totalWeight": 17
            },
            "list_of_foil_cards": {
              "cards": {
                "db2b0bb2-19ec-565f-992b-4380a22e25d4": 2
              },
              "fixed": true,
              "foil": true,
              "totalWeight": 2
            }
         }
      },
```

maybe the name is the confusing part? like it's reusing something that is not a booster to represent a deck, but i think it adds nice properties such as having a list of cards with fixed weights instead of repeated ids for repeated cards.


@taw i think the data in the current export is enough, but i'd value your opinion on how you'd structure this in mtgjson

**Comment by taw** [comment]
Are you trying to make one data structure that's both for decklists and boosters?

Hybrid slightly randomized products (like jumpstart-19 decks, some SLD boxes) don't fit current model too great.

I guess technically you could represent a deck as a series of boosters, but that would be a bit annoying, as you'd need main, mainFoil, side, sideFoil, commmander, and commanderFoil (and if we ever get to implementing tokens, tokens and tokensFoil). Ugh.

**Comment by ZeldaZach** [comment]
@taw Koda wants a way to easily parse Deck lists for EV and doesn't want to reinvent the wheel to do so. I'm not overly happy with the approach provided and would consider a deviation here, but I wanted to hear what you/axxel thought before making any final decisions

**Comment by taw** [comment]
I think we're happy with keeping fully random and fully fixed products separate in their own formats. Other than maybe adding tokens support, they do everything we want.

I don't really see that much value in creating custom format for fixed decks pretending to be boosters, isn't it like a few lines of jq to transform existing formats for EV calculations?

For hybrid products, it's a bit messy. For various Jumpstarts we provide them twice in both formats:

* [as individual decks with human-readable field for additional contents](https://mtg.wtf/deck/bro/infantry-1)
* [as boosters](https://mtg.wtf/pack/bro-jumpstart)

Right now that extra content field isn't included in the export. I could add it, but it's not machine readable. We could make it machine readable, as we have all necessary information (or at least a good guess), but it would complicate the export format.

SLD boxes also have semi-random content. It is only provided in human readable format [example](https://mtg.wtf/deck/sld/imaginary-friends), [example](https://mtg.wtf/deck/sld/hope-you-like-squirrels-foil). We'll probably add boosters for every such semi-randomized SLD box for completeness.

Also arguably none of these (Jumpstart half-decks or SLD boxes) are "decks".

Do you have any opinion on how extra content information could best be exported?

**Comment by ZeldaZach** [comment]
I do agree that fitting the data to the booster format is a bit awkward, and had another idea of just setting up a "decks" list

```
"decks": [
{
   "name": "Deck 1",
   "cards": [
      {
         "uuid": "UUID-1-1-1-1-1",
         "foiling": None|Foil|Etched,
         "count": 2
      },
      ...
   ]
},
...
]
```

**Comment by kodawah** [comment]
so sets like commander will have `decks` and sets with intro or starter decks will have both `decks` and `booster`?

**Comment by axxroytovu** [comment]
I don't have any issues with Zach's proposal. Including a simpler version of the existing Deck format just as a `decks` tag should fulfill the desired outcome.

At this point pretty much every set will have both `decks` and `boosters`. Between welcome packs (fixed decks), arena starter decks, jumpstart packs, collector booster samples, etc. most sets have both decks and packs.

**Comment by kodawah** [comment]
cool I'm ok with #3 too then. To further nitpick the idea:
* ~~maybe `deck` instead of "decks" and dictionary instead of array to keep it consistent with "booster"?~~
* ~~`count` could be skipped in favor of repeat the card in the array~~
* `foiling`->`finish`

example

```json
"deck": {
  "reference_deck_1": {
    "name": "Deck 1",
    "cards": [
    {
      "uuid": "UUID-1-1-1-1-1",
      "finish": Nonfoil|Foil|Etched
    },
    ...
   ]
  },
...
}
```

edit: updated dropping suggestions for simplicity's sake

**Comment by axxroytovu** [comment]
The current implementation doesn't separate the sideboard/commander cards from the mainboard. Is this OK, or do we want to update with an additional flag for the card's location?
