### ISSUE TITLE
Identifier additions for Tokens

### ISSUE THREAD

**Issue by Boomstamtak** [mtgjson/mtgjson#1081]
Currently there are no external identifiers (cardkingdom, cardmarket, tcg...) provided for Tokens other than the mtgjson ID ofcourse. Is there a reason for this?

**Comment by ZeldaZach** [comment]
I've gone ahead and added support for MCM details, but CardKingdom will take a bit more work. Will involve my upstream (@kodabb) for this one. If he's unable to help at this time, I have alternatives when CK updates their API in the next few months
