### ISSUE TITLE
Prototype layout doesn't exist

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#1085]
Prototype cards have layout "normal" rather than layout "prototype".

**Comment by ZeldaZach** [comment]
For further clarification, would you consider Mutate and cards in need of a different frame layout? Because those are are also declared normal.

**Comment by KingSupernova31** [comment]
Hmm, good question. They do have a different frame, but it's just aesthetic, and doesn't contain any actual information past that of a regular card. I'd say that's a judgement call, I don't have a strong opinion either way.

Prototype cards have their own alternative characteristics, very similar to leveler cards, which do have their own layout.

**Comment by ZeldaZach** [comment]
Prototype is now a supported layout!
