### ISSUE TITLE
Treats to Share has keyword "food"

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#1087]
In atomicCards, v5. I didn't check if anything else is subject to the same bug.

**Comment by ZeldaZach** [comment]
Can you further clarify what the issue is here? Food is somewhat a keyword nowadays, like Treasure and Clue.

**Comment by KingSupernova31** [comment]
The issue is that Food is not a keyword.

https://media.wizards.com/2023/downloads/MagicCompRules%2020230414.pdf
https://mtg.fandom.com/wiki/Keyword_ability
https://en.wikipedia.org/wiki/List_of_Magic:_The_Gathering_keywords

**Comment by ZeldaZach** [comment]
I'm gonna close this as a dupe of #757 because the keywords array, which is populated upstream, seems to be a bit unreliable. I'll consider my own implementation through that ticket.
