### ISSUE TITLE
No identifiers column in cards table?

### ISSUE THREAD

**Issue by Nimrod-666** [mtgjson/mtgjson#1089]
#### Version(s) tested against
Current https://mtgjson.com/api/v5/AllPrintings.sqlite

#### Description of Bug

Hi, i'm using the api the first time since a few months and i've seen that "scryfallId" has been removed and moved to the new "cardIdentifiers" table. Now i'm wondering how to join both tables because i don't see an "identifiers" column in the "cards" table. My former approach was the query "SELECT * FROM cards WHERE scryfallId = ?". Could somebody give me a hint what i'm missing? I would guess i need to join both tables somehow, but i don't see the keys that would be joinable.

Best regards

**Comment by ZeldaZach** [comment]
Hey @Nimrod-666! You should be able to take the UUID from cards and link it back to the cardIdentifiers table.

Something like this should work?
`SELECT * FROM cards c WHERE scryfallId = (SELECT scryfallId FROM cardIdentifiers WHERE uuid = c.uuid)`

**Comment by ZeldaZach** [comment]
Or maybe `SELECT c.* FROM cards c JOIN cardIdentifiers ci ON c.uuid = ci.uuid`

**Comment by ZeldaZach** [comment]
If you're still having issues, please let me know!
