### ISSUE TITLE
starterdeck promotype is missing

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#1093]
There are a handful of cards from KLD and AER that need this promotype since they have a different collector number

example https://scryfall.com/card/kld/70%E2%80%A0/wind-drake

no idea why that promo type is lost

**Comment by kodawah** [comment]
as @axxroytovu pointed out, these cards all have `"isStarter": true` instead of promo type entry

edit: which afaiu is a flag that is being deprecated

**Comment by ZeldaZach** [comment]
We currently filter out starterdeck promoType in favor of setting the isStarter flag. I think it's time to revert that option, since isStarter will be going away soon.
