### ISSUE TITLE
LTC / LTR data issues

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#1094]
I'm sure they're upstream.

Anyway:

* 2 sagas from LTR have layout:normal not layout:saga - Oath of the Grey Host  and There and Back Again. This one has been going for a while.
* in LTC some cards are borderColor:borderless, and others are border:black frameEffect:borderless, there's not been frameEffect:borderless before. From pics both groups have very similar non-borders. This is new from latest update. There was no frameEffect:borderless last time I did an update.

**Comment by FrankJeager** [comment]
Also ForeignData are empty in LTR/LTC.

**Comment by kodawah** [comment]
I believe these were all fixed upstream

https://scryfall.com/search?as=grid&extras=true&lang=any&order=name&q=s%3Altc+layout%3Anormal+t%3Asaga&unique=cards
https://scryfall.com/search?q=s%3Altc+border%3Aborderless&unique=cards&as=grid&order=name
