### ISSUE TITLE
[Suggestion] Make Card "availability" atomic-like

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgjson#1095]
Currently the card `Liliana, Dreadhorde General` has different values depending on its printing which I find to be confusing and not accurate to the purpose of the availability field. For example:

`Liliana, Dreadhorde General`
**In PRM**: `["mtgo"]`
**In WAR**: `["arena", "mtgo", "paper"]`

Can we make this property evergreen and stay the same amongst all printings?

**Comment by ZeldaZach** [comment]
I'm not convinced this is a correct application of atomic-keys. Specific printings of a card can be found in specific places, and this is how folks should be able to identify them. The AtomicCards should handle this correctly as-is, if that's what's wanted by the user.
