### ISSUE TITLE
Modifying Booster Data when things change

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson#1099]
This discussion post is for if we should remove the 1/1 serialized One Ring from the LOTR set Booster data field, since it's no longer publicly acquirable from packs.

**Comment by kodawah** [comment]
context from discord

> Koda — @Axxroy (and anybody interested in box contents) i haven't checked if the serialized 1/1 one ring was added to the pool of cards available in lotr cbb, but if so, now that it has been found, do you think it could be removed from the list?
> Axxroy — That's a good question. I don't really have an opinion, though it might make sense to remove it.
> Koda — it's gonna skew ev, but now that card is gone 💸
> taw — lol, are we going to edit the boosters based on which one are open already?
> that feels crazy
> Zach — I kind of agree, I'm not sure it makes sense for us to modify what the data set is just because a serialized card was pulled. It sets a bad precedent
> taw — I'd prefer to keep it
> Koda — i disagree clearly - the one ring has been opened so it's not possible to open one again
so the data currently embedded reflect a situaiton that cannot happen any more
and in particular for ev calculation, it could skew the value if it is left as is
> veyloris — FWIW, I agree with your take. Take it with a grain of salt since it's not really a part of the data model I use frequently, but I think my initial expectation is that it would be removed.
> If, tomorrow, WotC did something similar to their racial sensitivity super bans and said "Bill the Pony (LTR #0003) is offensive to horses and horsekin everywhere, and so we stopped printing it after the initial print run and no variants of it will appear in packs past the initial print run." The question basically becomes: is the data model's goal to provide a superset of all cards that could ever be pulled in a collector pack, or is it designed to give an idea on present state? I use the data operationally, so I have more of a going concern approach to it: if I can't pull it, I don't really care that at one point I could. That's definitely a different use-case from someone consuming data from a more academic approach, maybe.
> As a similar example: https://twitter.com/StarCityBen/status/1673847008107327490 I could absolutely see those cards being included within a collector pack data model initially because the assumption is that they could be present, but given that the cards literally cannot be pulled from a CB I think I'd expect them to be removed when that information "became" true. 
> Obviously trying to keep up with every individual serial of every variant is super outside the scope of this project, and I think the precedent being "this category of cards will no longer appear in boosters, and so we will remove it" seems appropriate - the one ring is a category of cards that contains a single card.
> Axxroy — I personally would lean toward the historical, archival approach. Do we take Tabernacle out of the DMU collector boosters because the supposed "3 copies" were pulled? Do we track all of the serialized cards to update how many copies still exist? By committing to a live update model we are opening up a HUGE amount of work for ourselves, and honestly not changing the actual EV of packs by that much. Because of how rare it was, the LTR collector booster EV goes down by 0.6 cents if we take out the One Ring.
> Also we've already accounted for that tweet, since those cards literally can't appear in collector boosters and it's a known thing from day 1
> Koda — i'd argue that wotc doesn't publish data on print numbers so we can do only estimates, but when things are serialized it's a different story

**Comment by kodawah** [comment]
i may understand the "historical" data need, but it seems like more applications would prefer a "practical" state of things

maybe adding a flag for both sheets/usecases is a viable compromise?

**Comment by axxroytovu** [comment]
I do want to clarify that I was incorrect about the EV change from the one ring, it's <0.6 dollars, not 0.6 cents. 

From https://magic.wizards.com/en/news/feature/collecting-the-lord-of-the-rings-tales-of-middle-earth there is a <0.00003% chance to pull the One Ring from any booster. Multiply that by the $2M bounty, and you get $0.6.

**Comment by axxroytovu** [comment]
@taw Does it make sense to flag a specific booster variant as "depleted" or similar? That's the only real version of this I can see being manageable in the long term from a workload standpoint. That leaves the data available for historical purposes and still allows people to use the "most current" data. 

We would need a very specific set of circumstances to happen though, and being able to fully deplete a booster variant may not be a common thing moving forward. It does seem like a lot of work to add an entire feature that will only affect one product.

**Comment by taw** [comment]
@axxroytovu I'd rather just take historical view, and not get into any such flagging. Hopefully this is a one-off, and WotC won't be doing this in the future.

**Comment by kodawah** [comment]
seems like we prefer to keep things as is, and hopefully these cards should not affect ev much
