### ISSUE TITLE
Identical card numbers for transform cards

### ISSUE THREAD

**Issue by antoinevanwel** [mtgjson/mtgjson#110]
Hi,

I was expecting card numbers to be different for front and back of transform cards (like in v3), but found
- Search for Azcanta / Azcanta, the Sunken Ruin, both number 74 (or 74s in different set)
- Arguel's Blood Fast / Temple of Aclazotz, both 90 (or 90s in a different set)

in v3 this is 74a / 74b and 90a / 90b

Trying to find if a card is front or backside, any advice how this should be done in v4?

thanks!

**Comment by ZeldaZach** [comment]
Cards That have split type has a names field with the other side

**Comment by ZeldaZach** [comment]
Split cards can be identified by a card having the "names" field. This field is only on split/flip/transform/meld/etc cards, so it's fairly standard.

For numbering of cards, v3 did do it as an a/b side, and it seems we currently do not with v4. Is this something that is wanted? Does it matter?

Please do let me know!

**Comment by silasary** [comment]
Yes, having a/b is preferable

**Comment by ZeldaZach** [comment]
PR #111 should address this :)

**Comment by bakert** [comment]
As long as it's possible to reconstruct the card from the data I don't think it matters *too* much what you choose. 

If mtgjson's "card" data represents "faces" ('Alive' and 'Well' as two separate things, 'Erayo' and "Erayo's Essence" as two separate things) and not as card ('Alive // Well', the Erayo flip card) then a choice has to be made about how to represent the relationships.

One option is to use related identifiers that differ ("121a" and "121b"). I think this option is somewhat poor in the abstract (you have to inspect the identifiers to make sense of them, they now all have to be strings but 99% are a string representation of an integer). BUT (and it's a big but) this is what WotC already do with the "Card Number". For that reason I'd probably just roll with it. A somewhat-redudnant "names" array that contains all parts of the card is good too. If you wanted to do something more "correct" and less similar to Gatherer I wouldn't blame you.
