### ISSUE TITLE
Spellbook for The Hourglass Coven missing

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#1100]
#### Version(s) tested against
HBG.json from 5.2.1+20230730

#### Description of Bug
[The Hourglass Coven should have related spellbook with 9 cards](https://mtg.fandom.com/wiki/Alchemy_Horizons:_Baldur%27s_Gate#List_of_cards_in_Spellbooks), it doesn't have any.

**Comment by ZeldaZach** [comment]
Found a discrepancy in upstream dependency, have filed an issue with them.
