### ISSUE TITLE
Time Lord should be a single string

### ISSUE THREAD

**Issue by theelk801** [mtgjson/mtgjson#1101]
#### Version(s) tested against
"MTGJSON 5.2.1+20230805"

#### Description of Bug

The "Time Lord" subtype should be a single string rather than two separate strings

**Comment by ZeldaZach** [comment]
This is definitely an interesting corner case. Technically, the way it's worded on the card, I see no indication that they're a combined subtype, but logically I understand they should be. Is there any official WOTC notes indicating this is one subtype?

**Comment by theelk801** [comment]
yeah, it's already been confirmed [here](https://x.com/wotc_matt/status/1682442194081431552)
