### ISSUE TITLE
sealedproduct: add a language field

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#1115]
we could be adding a language field in the sealed property to simplify parsing complicated products like

*legends italian
*the dark italian
*strixhaven japanese
*war of the spark japanese
*reinassance

maybe an optional value to be set if the product is non-English? cc @axxroytovu

**Comment by kodawah** [comment]
@axxroytovu we have the language field available in the model, but it's not getting imported in mtgjson, do you know where to touch on this side?

**Comment by axxroytovu** [comment]
Provider is here: `mtgjson5/providers/github_sealed.py`

Need to define a language property in `mtgjson5/classes/mtgjson_sealed_product.py`
