### ISSUE TITLE
All Decks as a single file

### ISSUE THREAD

**Issue by hallem** [mtgjson/mtgjson#1129]
It would be great to include a download option for the all decks files to be a single JSON file as well. It would be a lot easier to parse.

**Comment by ZeldaZach** [comment]
I've thought about this more, and I'm just not certain the redundancy over AllDeckFiles.zip is worth it. It should be trivial to iterate that directory compared to a single file, as the structs are guaranteed to be the same. Sorry to disappoint on this one.
