### ISSUE TITLE
battle royale old hash still present

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#1134]
battle royale set got renamed to remove the double Battle Royale markup here https://github.com/mtgjson/mtgjson/commit/ef562693ce029b66fea197c8c21e0d9e5ad093e5#diff-476f9d1e2d6b92aba08a82d3197642451e829b2a1f577531d25152ffb3a27496

this caused a new hash to be generated, however it seems like the old hash is still used for the sourceProduct, and it has not gone away in a few days

**Comment by axxroytovu** [comment]
Has this issue resolved over the last few builds? If not I can dig into it further. 

Edit: I just checked and it looks to be resolved. Please verify.

**Comment by kodawah** [comment]
yep it got resolved, thank you
