### ISSUE TITLE
there is a number in a dictionary of strings

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#1135]
after the sealed product source migration (cc @axxroytovu)

> json: cannot unmarshal number into Go struct field .data.sealedProduct.identifiers of type string

There is a element in a dictionary which cannot be unmarshalled easily into a map of strings. Unfortunately i cannot pinpoint it any further

Should we add a test to avoid this from happening?

**Comment by ZeldaZach** [comment]
There appears to be a manual coalesce issue -- See https://github.com/mtgjson/mtg-sealed-content/blob/main/data/products/SLD.yaml#L2148 as an example. I'll add better guards on both repos to prevent this in the future
