### ISSUE TITLE
Support JSONP or CORS

### ISSUE THREAD

**Issue by Kerrick** [mtgjson/mtgjson#115]
Hi!

MTGJSON v3 supported JSONP so a website could load the data from the browser. However, MTGJSON v4 does not, and trying to load the JSON URL directly fails because the `OPTIONS` request made by the browser doesn't get a response stating that the server supports CORS for the URL.

Can you please add back JSONP support _or_ configure the server to support CORS for the following URLs?

- `https://mtgjson.com/v4/json/AllCards.json`
- `https://mtgjson.com/v4/json/AllSets.json`

Thanks a million for all the work that goes into MTGJSON, and for how great v4 looks!

**Comment by ZeldaZach** [comment]
Thanks for the report. I'll see about adding CORS for the json folder in the near future

**Comment by ZeldaZach** [comment]
Update: This will be put into place after the new years. We'll be switching host providers at that time, so I'll have a bit more authority on the server :)

**Comment by ZeldaZach** [comment]
And supported :)
