### ISSUE TITLE
Cardkingdom retail prices include OOS cards

### ISSUE THREAD

**Issue by snowfoxsean** [mtgjson/mtgjson#1154]
#### Version(s) tested against
5.2.2

#### Description of Bug
Similar to https://github.com/mtgjson/mtgjson/issues/1142
The issue also exists with retail pricing. Cards that are OOS on CK also have a price but that price doesn't really mean anything.

**Comment by snowfoxsean** [comment]
This issue might be a little more intricate though because price history might still mean something to some people? Ideally the API serves a flag on whether the item is currently OOS or not.

**Comment by kodawah** [comment]
many vendors do not update the prices of oos cards, so I think it's safe to drop it entirely if qty is 0
