### ISSUE TITLE
A few typos/inconsistencies in ability texts

### ISSUE THREAD

**Issue by DJCatBlitz** [mtgjson/mtgjson#1156]
Version(s) tested against
MTGJSON 5.2.2+20231130"

#### Description of Bug
_I replaced some characters, but the problem is the missing space_
**Balloon Stand**
Visit - Choose one.~ Create a 1/1 red Balloon creature token with flying.~ Sacrifice a Balloon. If you do, target creature gains flying until end of turn.
->
Visit - Choose one -~ Create a 1/1 red Balloon creature token with flying.~ Sacrifice a Balloon. If you do, target creature gains flying until end of turn.

_Again some characters are replaced , but the problem is the missing dot_
**Celebr-8000**
... it also gains double strike until end of turn.~ 2 - menace~ 3 - vigilance~ 4 - lifelink~ 5 ...
->
... it also gains double strike until end of turn.~ 2 - menace.~ 3 - vigilance.~ 4 - lifelink.~ 5 ...

_I'm not sure about this one, but again there seems to be a dot missing?_
**Lord Skitter's Butcher**
When Lord Skitter's Butcher enters the battlefield, choose one -~ Create a 1/1 black Rat creature token with "This creature can't block."~ You may sacrifice another creature. If you do, scry 2, then draw a card.~ Creatures you control gain menace until end of turn.
->
When Lord Skitter's Butcher enters the battlefield, choose one -~ Create a 1/1 black Rat creature token with "This creature can't block.".~ You may sacrifice another creature. If you do, scry 2, then draw a card.~ Creatures you control gain menace until end of turn.

**The Pyramid of Mars**
When you planeswalk to The Pyramid of Mars and at beginning of your upkeep, surveil 2.
->
When you planeswalk to The Pyramid of Mars and at the beginning of your upkeep, surveil 2.

**Comment by ZeldaZach** [comment]
So unfortunately this is a "Wizards" issue and not an "us" issue. The cards were annotated within MTGJSON correctly, but Wizards was using a different style of text for their ops. You can check the physical cards at Scryfall or Gatherer and see that the wording is awkward as you pointed out.
