### ISSUE TITLE
Prices don't include Etched entities

### ISSUE THREAD

**Issue by GaryTheHutt** [mtgjson/mtgjson#1164]
The MTGJSON release includes the base version of the SLD PixelSnowLands.jpg release #325-#329 (which included both simple and foil finishes), but there was also an etched finish release. This becomes important when tracking prices since there is no UUID for the uniquely valued etched cards. 

Would appreciate if the etched versions could be added with unique UUIDs as has been done with other releases in this situation.

**Comment by ZeldaZach** [comment]
Hey @GaryTheHutt I'm not exactly sure what additional fields you're looking for / what you're referencing with this. 

I picked Snow-Covered Mountain from SLD with PixelSnowLands drop status, and I see etched IDs for all entities. Is there something here I'm missing?

<img width="586" alt="Screenshot 2023-12-17 at 1 46 56 PM" src="https://github.com/mtgjson/mtgjson/assets/7460172/565cc66c-5e26-45e9-ade9-51375164c979">

**Comment by GaryTheHutt** [comment]
There is no etched price for the uuid in the PriceList module. It only returns a normal and a foil price from sources. In other SLD releases, this was handled by adding a seperate row with a unique uuid for the etched version.

**Comment by ZeldaZach** [comment]
You're right! Let me update this ticket and work on a fix :)
