### ISSUE TITLE
Pull translations from Magiccards.info

### ISSUE THREAD

**Issue by bra1n** [mtgjson/mtgjson#117]
A lot of cards actually have translated names from reprints in auxiliary products like Duel Decks or Tempest Remastered. These translations are often not available on Gatherer, while they are listed on MCI. Example:
[Rith's Charm on MCI](http://magiccards.info/pvc/en/60.html) has 6 translations, while [the one on Gatherer](http://gatherer.wizards.com/Pages/Card/Languages.aspx?multiverseid=209152) only has 1.
[Skyshroud Elf](http://magiccards.info/tpr/en/192.html) hast 5 translations on MCI, while it [doesn't have any on Gatherer](http://gatherer.wizards.com/Pages/Card/Languages.aspx?multiverseid=397435).
Updating the translations when comparing cards to Gatherer would add a lot of useful new card names in foreign languages! :)

**Comment by ZeldaZach** [comment]
Using ScryFall, and addressed in V4
