### ISSUE TITLE
Meld cards don't have a "side" field

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#117]
Meld cards should have a "side" field just like all other multi-part cards, with the top half being "a", bottom half being "b", and melded face being "c".

**Comment by KingSupernova31** [comment]
Alternatively, both front sides could be "a" and the melded side could be "b". I'm not sure which one makes more sense from a design perspective.

**Comment by ZeldaZach** [comment]
Meld cards are a real special case... not sure what the right approach is here. I'm more inclined to leave it as is than try to make up a formatting further. 

If you have an alternative opinion, please speak up so I know what the community wants

**Comment by KingSupernova31** [comment]
The docs say that the side field is "used on cards with multiple faces", which meld cards certainly qualify for. It seems strange to omit it.

After thinking about it a bit more, I think it makes the most sense to have "a", "b", and "c". The difference between the top half and the bottom half is relevant for applications that want to display card images. The top half is also always the one that has the ability to meld the cards. And philosophically, I think there is a difference between the two front halves- arguably more than the difference between two halves of a split card.

**Comment by nhrsn** [comment]
While being a very slight corner case, I definitely think meld cards need to follow the same standard as other multi-part cards. So no matter what I think the `side` field should be added.

I'm inclined to say `a` is the front of the primary card, `b` is the front of the secondary card and `c` is the full face of the melded card. The half faces of the melded card aren't cards and shouldn't exist as such.
