### ISSUE TITLE
LCI promo pack cards price not updating

### ISSUE THREAD

**Issue by GaryTheHutt** [mtgjson/mtgjson#1172]
#### Description of Bug
For several weeks now, it appears the prices for promo pack cards from LCI are not updating. The uuids do not appear in the AllPrices nor AllPricesToday files.

**Comment by ZeldaZach** [comment]
I've confirmed these prices have been updating as expected. If you can be more specific on what you think might be a problem, feel free to comment/reopen!

**Comment by GaryTheHutt** [comment]
They finally started updated about a week and a half ago, but for more than two months there were no updates for any promo pack LCI cards.
