### ISSUE TITLE
missing leadershipSkills

### ISSUE THREAD

**Issue by GaryTheHutt** [mtgjson/mtgjson#1173]
The LeadershipSkills data module doesn't contain any data within the CardsSet module in the AllPrintings file.

**Comment by ZeldaZach** [comment]
Hey @GaryTheHutt can you be a bit more specific on this? I'm not sure what you mean, as I see leadershipSkills populated for almost 10k entries as of this moment

**Comment by GaryTheHutt** [comment]
I made an error. I extracted 'leadership' instead of 'leadershipSkills'. The data is fine. Sorry for the confusion.
