### ISSUE TITLE
Getting an error when running MTGJSON. How do I resolve this?

### ISSUE THREAD

**Issue by algonorth** [mtgjson/mtgjson#1174]
#### Version(s) tested against
MTGJSON 5.2.2+20240109

#### Description of Bug
[INFO] 2024-01-09 12:37:44,544: Loading configuration from local file
[INFO] 2024-01-09 12:37:44,546: Starting  on 2024-01-09
[WARNING] 2024-01-09 12:37:44,546: Pushover keys values missing. Skipping alerts
[WARNING] 2024-01-09 12:37:45,118: Scryfall keys values missing. Defaulting to non-authorized mode
[INFO] 2024-01-09 12:37:45,341: Building 1 Sets: NEO
[WARNING] 2024-01-09 12:37:53,543: Scryfall keys values missing. Defaulting to non-authorized mode
[WARNING] 2024-01-09 12:37:54,344: CardMarket keys values missing. Skipping requests
[CRITICAL] 2024-01-09 12:37:54,353: Exception caught: 'CardMarketProvider' object has no attribute 'set_map' Traceback (most recent call last):
  File "/mnt/d/projects/mtgjson/mtgjson-stable/mtgjson5/__main__.py", line 149, in main
    dispatcher(args)
  File "/mnt/d/projects/mtgjson/mtgjson-stable/mtgjson5/__main__.py", line 111, in dispatcher
    build_mtgjson_sets(sorted(sets_to_build), args.pretty, args.referrals)
  File "/mnt/d/projects/mtgjson/mtgjson-stable/mtgjson5/__main__.py", line 48, in build_mtgjson_sets
    mtgjson_set = build_mtgjson_set(set_to_build)
  File "/mnt/d/projects/mtgjson/mtgjson-stable/mtgjson5/set_builder.py", line 460, in build_mtgjson_set
    mtgjson_set.mcm_name = CardMarketProvider().get_set_name(mtgjson_set.name)
  File "/mnt/d/projects/mtgjson/mtgjson-stable/mtgjson5/providers/cardmarket/monolith.py", line 224, in get_set_name
    if not self.set_map:
AttributeError: 'CardMarketProvider' object has no attribute 'set_map'

[WARNING] 2024-01-09 12:37:54,357: Pushover keys values missing. Skipping alerts

**Comment by ZeldaZach** [comment]
Looks like a new feature I added has a problem with non-auth mode.

Just curious, any reason you're looking to build MTGJSON data yourself vs using our [pre-compiled biniaries](https://mtgjson.com/api/v5)?

**Comment by bit-pax** [comment]
I'd like to modify the structure of the json data so it works better with a
web app I'm building.

**Comment by algonorth** [comment]
I'd like to modify the structure of the json data so it works better with a
web app I'm building.

In the long term when I get something up and running and it starts making
money I'll definitely be donating to MTGJSON on a monthly basis because I'd
like to be listed as a supporter.
