### ISSUE TITLE
Cardsphere IDs are sometimes the foil IDs

### ISSUE THREAD

**Issue by catascopic** [mtgjson/mtgjson#1178]
#### Version(s) tested against
MTGJSON 5.2.2+20240127

#### Description of Bug
It seems to be around half the time or more, the cardsphereId field for a given card links to its foil ID on Cardsphere. For example, Army of the Damned's ID on Cardsphere is 20385 and the foil is 20384.  MTGJSON lists it as 20384 (the foil), and has no listing for 20385.

EDIT: It looks like it always links to the foil ID if it exists.

I know there's some compatibility issues since most sites don't use different IDs for foil and nonfoil cards. I guess ideally you'd list both in the ID object (cardsphereFoilId?), but if you don't want to do that, I assume it's meant to consistently list the nonfoil ID.

**Comment by pauperbattlebox** [comment]
@ZeldaZach LMK if I can provide this data differently. 

@catascopic A temporary solution could be multiversebridge.com if you aren't using it already.

cdn.multiversebridge.com/mtgjson_build.json
