### ISSUE TITLE
Card entries with the same name have duplicated "names".

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#118]
See #94. Collapsing the entries was fixed, but the names field still has the duplicates.

**Comment by ZeldaZach** [comment]
I wasn't sure what to do with this. Should I change it to Foo (A), Foo (B) or leave it as a list of Foo's. Would like further opinions.

**Comment by KingSupernova31** [comment]
A list of Foos isn't particularly helpful. "Foo (A)", "Foo (B)" makes sense, but is somewhat inconsistant with how other cards are handled. I think it's the best option though.

**Comment by ZeldaZach** [comment]
Fixed with #134
