### ISSUE TITLE
Cards without mana costs don't have 'cmc' data

### ISSUE THREAD

**Issue by vslashg** [mtgjson/mtgjson#118]
This is mostly applicable to lands, but can happen to other cards (Ancestral Vision is a non-land example).

Cards without mana costs have a converted mana cost of 0 (rule 202.3a), and it would be useful if CMC data were provided for all cards.

**Comment by Garbee** [comment]
How exactly would this be useful? You can easily program for this occurance when reading the data.

**Comment by vslashg** [comment]
Clients can work around missing data, but should they be expected to?  Ancestral Vision and Memnite are both CMC 0.  Why does one card's entry provide this data and the other not?

**Comment by bakert** [comment]
An example of how this might be useful. magidex.com uses mtgjson data and currently "cmc<1" in a search query does not find lands. If the client programmer is aware of this omission they can work around it but they have to know. Given that the CMC of a land is 0 and not NULL I think the data should reflect that. I just added some code to work around this in my own project.

**Comment by gwax** [comment]
Fixed by #413
