### ISSUE TITLE
Duplicate cards in AllPrintings.json

### ISSUE THREAD

**Issue by Rodentman87** [mtgjson/mtgjson#1184]
#### Version(s) tested against
5.2.2+20240203

#### Description of Bug
There's 43 tokens and 3481 cards with duplicated uuids in the PLST set. The full list is too long to paste here, but these are some of the tokens that are duplicated. These ids seem to be mostly duplicated from within the PLST set itself but I don't have full info on that since there's so many

| UUID | Name | Set Code |
| --- | --- | --- |
| ba22fdaf-8d82-5f14-a5f0-3e5908f04d8c | Angel | PLST |
| 3d659294-a211-5deb-b01a-f89803fe57b0 | Angel | PLST |
| 2549f082-332d-5da3-a920-fb2d0fdf3632 | Beast | PLST |
| c18f9fdc-5c27-56f9-bb63-1e68212d18a6 | Vampire | PLST |
| 86b07616-a2d8-51d5-ac8f-9dfb9af80ce5 | Cat Soldier | PLST |
| 7448081c-7411-5fed-aafe-634b8ae05a30 | Soldier | PLST |
| 3bdb268c-8791-54bc-8904-6d3245934224 | Soldier | PLST |
| fc8ca6fb-2c23-5b94-8cc0-2a458fea05bb | Cat Beast | PLST |
| ad98a0db-9d20-5b48-acae-40bd74f5137b | Vampire | PLST |
| cb53027b-e24a-51b1-a06a-130217568848 | Zombie | PLST |
| aece7d3f-d168-5b09-849e-b8895dadecb8 | Pest | PLST |
| b0a9bf0e-8389-50f0-b7d3-23d8ca0ad8de | Wolf | PLST |
| 6308f39d-f1a5-528d-97a0-200dd2e44fc5 | City's Blessing | PLST |
| ab23fbc6-93ff-5576-935d-1baf0dce8f4d | Plant | PLST |
| 32898d2b-e15e-585c-b43a-ca545bb2e933 | Ashaya, the Awoken World | PLST |
| 3a180139-efdf-56ba-937d-61617cfaf0f1 | Lukka, Wayward Bonder Emblem | PLST |
| b2967043-69b9-529e-aaf4-c2b463da9f1b | Cat | PLST |
| b7e852ac-2fca-54a0-86e6-7c5e29c4b506 | Dog | PLST |
| d717c906-b914-547e-9502-6b71dc0768e3 | Human Cleric | PLST |
| e2a31834-4fd7-5ecd-af99-11ab79ec8ed4 | Ape | PLST |
| bc2331ef-369f-5929-9a00-c32b48e89cbf | Treasure | PLST |
| c564288c-0a99-5a75-b1bf-4973b8e29834 | Jace, Telepath Unbound Emblem | PLST |
| 84ffe3c7-6ce2-5004-9839-8f9e876dfc33 | Elf Warrior | PLST |
| f8ca07e3-9212-555d-984f-2551a9c6bb34 | Citizen | PLST |
| b101956b-c0f9-5be5-9133-a39b3fd24f40 | Wolf | PLST |
| 1cda1cde-1297-519b-9b6c-dbae01790596 | Liliana, Defiant Necromancer Emblem | PLST |
| 266d4358-2f11-5e60-82ee-7d2b58a01afe | The Monarch | PLST |

**Comment by kodawah** [comment]
i think these got all sorted out, there were a lot of leftovers during the conversion
