### ISSUE TITLE
Some cards have a nonsensical "names" array

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#119]
Helm of Kaldra, Hero of Bladehold, and Herald of Anafenza for example.

**Comment by ZeldaZach** [comment]
I'll keep playing with the names array. A bit annoyed, I thought i solved it already

**Comment by rvock** [comment]
Here are some more examples in GRN Guild Kit (GK1): https://mtgjson.com/v4/json/GK1.json
`Thunderheads` has names `Weird` and `Goblin`:
`Tolsimir Wolfblood` has names `Voja` and `Saproling`

`Jiang Yanggu` in "Global Series Jiang Yanggu & Mu Yanling" (GS1)
