### ISSUE TITLE
Conspiracy (set) exclusive cards missing Commander legality

### ISSUE THREAD

**Issue by mpaulweeks** [mtgjson/mtgjson#119]
More accurately, this is a bug in gatherer. Note the differences in the examples below.

Council's Judgement, a Conspiracy card with a reprint, is fine:
http://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=382239

Stifle, a card reprinted in Conspiracy, is fine:
http://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=382377

Council Guardian, a Conspiracy card w/o a reprint, is wrong:
http://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=382238

Some more examples:
http://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=382223
http://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=382209
http://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=382219

**Comment by gwax** [comment]
This appears to have been resolved by previously committed PRs.
