### ISSUE TITLE
Database for “The List Cards”

### ISSUE THREAD

**Issue by Snacks201** [mtgjson/mtgjson#1191]
So we run a MTG league at www.draftalot.com and we use the MTGJSON database for logging our cards in decks and for trading etc.

it used to be simply cause a set was a set, now they include “Special Guest Cards” and “The List” cards, which messes up our tracking.

Is there a way to make a database file for these?

**Comment by kodawah** [comment]
are you referring to PLST and SPG?

**Comment by ZeldaZach** [comment]
Booster data can be used to re-create what's in TheList and SpecialGuestCards for each set that exists
