### ISSUE TITLE
Prices for MKM promo cards not tracking

### ISSUE THREAD

**Issue by GaryTheHutt** [mtgjson/mtgjson#1194]
Prices for pMKM cards are not updating since release (about 6 weeks at this point) in the AllPrices and AllPricesToday files. Same for Dossier, Invisible Ink, Prism, and Showcase cards in the MKM set. The uuid for these cards does not appear in the files.

**Comment by GaryTheHutt** [comment]
These prices finally started updating sometime this week. About 2 months after release and all at once.

**Comment by ZeldaZach** [comment]
Glad to hear they're coming over now! If there's another problem do lmk :)
