### ISSUE TITLE
Physical cards total in Set

### ISSUE THREAD

**Issue by nicho92** [mtgjson/mtgjson#1195]
Hi, 

i ask for an enhancement for the Set object : 

we have : 
totalSetSize = total cards of the set (with rotated, dual, adventure, etc... that are count as one)
baseSetSize = "official" set size ( but without extra cards...).

Is it possible to get another property : 

physicalSetSize  = total of physical cards of the set ( something like count as side = null or side = a)

**Comment by kodawah** [comment]
sorry what is the goal here? what would `physicalSetSize` represent?

**Comment by nicho92** [comment]
Sorry, if i'm not clear..
I would like to add a propery in sets object with value = number of existing card of the set : 

In exemple : 
MID set (Innistrad: Midnight Hunt)
totalSetSize=471
baseSetSize=277

I suggest a new attribute which would be the value of the number of cards phisicaly present in the set. In our exemple, 
physicalSetSize=400. (320 normal cards + 80 transformed cards).

**Comment by kodawah** [comment]
ok but why though?

I fear such a number would be highly misleading as there can be several printing (finishes) per each card

**Comment by nicho92** [comment]
In my case, i collect only one version of each cards of the sets... but double sided card are counted as 2 cards ( like splited, transform, etc...) .

i need to calculate card with side=null or  side=a and isRebalanced=false for each set.

**Comment by kodawah** [comment]
ah i think this might be a bit of a custom use case, but it'd be up to @ZeldaZach to decide

in the mean time have you tried using AllAtomicCards in order to track single versions of each card?

**Comment by ZeldaZach** [comment]
Based on the discussions, I'm not inclined to add such a field at this time. I think the AllAtomic would provide some good insights to your collection, or possibly polling the SF API for the sets with a custom query field.
