### ISSUE TITLE
Cardkingdom OOS prices mismatch

### ISSUE THREAD

**Issue by khalimwu** [mtgjson/mtgjson#1198]
Version 5.2.2

Comparing prices between AllPrices.json and cardkingdom site seems to not match entirely. I understand that vendors don't update their price so the price that it's shown on the site it's fake?
A good example is Mana crypt yellow neon https://www.cardkingdom.com/mtg/special-guests/mana-crypt-0017b-yellow-neon-ink-foil  where it's shown at 329.99 (out of stock)

However the last price on AllPrices.json for db458c8f-0cba-51d2-8ec3-dd4ead161494 (which is that mana crypt) is USD 279

For cards that are on stock the prices are similar.

**Comment by ZeldaZach** [comment]
This is intentional. Cards that are out of stock don't have a true "price", so we ignore it as there's no way to confirm it's accurate and not a place holder.
