### ISSUE TITLE
Keywords.json uses incorrect apostrophe character

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#120]
The Magic comp rules and therefore the Keywords.json file uses "’" as its apostrophe character (unicode: single right quote, 0x2019). However the oracle text files use "'" (unicode: apostrophe, 0x27) as their apostrophe character. This leads to false negatives when doing any sort of comparison between the two.

Keywords.json should convert all single right quotes to apostrophes.

**Comment by ZeldaZach** [comment]
That's annoying... I parse right from the document, and that's what they had selected. Why would they use the wrong one? :P

**Comment by KingSupernova31** [comment]
Yeah, it's a pain. Unfortunately there are a lot of programs that default to a single right quote as their apostrophe character- I assume that whatever they're using to build their file is one of them.
