### ISSUE TITLE
[QUESTION] Where can I find Set image ?

### ISSUE THREAD

**Issue by Horsty80** [mtgjson/mtgjson#1200]
Hello,
I'm looking for link where I can find image of the set like this 

![bwu3253ehGBU-FR](https://github.com/mtgjson/mtgjson/assets/15615569/72cd16f5-e59e-4890-9f28-def5e80105b6)

That we can find here : https://magic.wizards.com/fr/products/outlaws-of-thunder-junction

The link of imported img are :
https://images.ctfassets.net/s5n2t79q9icq/57Qte6e0EDWaL0sXjF2mE8/c26ec06260b3f64ae9c0ea3dd200ca72/bwu3253ehGBU-FR.png?w=660

I don't know what are ID used by Hasbro =/

If someone can help me thanks :)

**Comment by ZeldaZach** [comment]
Hey there! Unfortunately this is currently out of scope for MTGJSON as we don't handle any kind of imaging :( I do apologize on that.
