### ISSUE TITLE
Add scryfallId to ForeignData

### ISSUE THREAD

**Issue by khalimwu** [mtgjson/mtgjson#1202]
Add scryfallId to ForeignData

Currently ForeignData only have multiverseId. Problem is that even if we try to find the uuid from the cardForeignData table we will end up with scryfallId for english version (since the uuid is repeated for all language variations). This is troublesome when trying to use scryfall's api to get the images of foreign cards.

**Comment by ZeldaZach** [comment]
Seems reasonable, and can be easily extended to other IDs over time. Will address shortly.
