### ISSUE TITLE
sensitive data exposure

### ISSUE THREAD

**Issue by rizkitj** [mtgjson/mtgjson#1207]
hello
mtg son team

I found a directory file with information on token data, cardforeigndat, etc. which can be accessed on the internet
#### Description of Bug
Sensitive data is anything that should not be accessible to unauthorized access, known as sensitive data. Sensitive data may include [personally identifiable information (PII)](https://securiti.ai/blog/what-is-personally-identifiable-information-pii/), such as Social Security numbers, financial information, or login credentials. Sensitive Data Exposure occurs when an organization unknowingly exposes sensitive data or when a security incident leads to the accidental or unlawful destruction, loss, alteration, or unauthorized disclosure of, or access to sensitive data. Such Data exposure may occur as a result of inadequate protection of a database, misconfigurations when bringing up new instances of datastores, inappropriate usage of data systems, and more.

step by step 

1.search google 
2.inurl:"/api/v5" intext:"index of / search
3.https://mtgjson.com/api/v5/ or https://mtgjson.com/api/v5/csv
4.There is a lot of information there that may be sensitive

remeditions

grant access rights or close access to the public

thanks 
grant access rights or close access to the public

![information_disclosure](https://github.com/mtgjson/mtgjson/assets/173668300/8bf782a1-e17c-418e-83e9-1bf961071fdb)
![mtgjson dork public](https://github.com/mtgjson/mtgjson/assets/173668300/317e4bcd-552a-4efb-b684-a639e00cc8a4)

**Comment by ZeldaZach** [comment]
This information is intentionally public, as we're a free data service. There is no sensitive data found within this API.
