### ISSUE TITLE
Transform cards don't have flavorText field

### ISSUE THREAD

**Issue by CajunAvenger** [mtgjson/mtgjson#121]
All cards in the sets jsons with layout: "transform" don't have flavorText fields, regardless of if the face has ft or not. This isn't a problem on the meld layout cards. Easiest way to see this is V17.json, but they're missing from the comprehensive jsons as well.

**Comment by ZeldaZach** [comment]
That's a big problem. Thanks for bringing this up. I'll work on this hopefully next week.
