### ISSUE TITLE
missing SLD decklist - Through the Wormhole

### ISSUE THREAD

**Issue by joe-nasti** [mtgjson/mtgjson#1211]
#### Version(s) tested against
{"date": "2024-07-15", "version": "5.2.2+20240715"}

#### Description of Bug
It appears that the Secret Lair Drop 'Through the Wormhole' from 2023 Secretversary Superdrop is missing in the MTGJSON decklist files (individual deck files or DeckList.json). Haven't seen any issues with the individual cards themselves.

https://mtgjson.com/downloads/all-decks/
https://secretlair.wizards.com/us/en/product/879333/through-the-wormhole

Let me know if I could help provide any add'l data, thanks

**Comment by axxroytovu** [comment]
The secret lair decklists are hosted here, which is open source if you want to contribute any of them: https://github.com/taw/magic-preconstructed-decks

Specifically you'll want to create a new file in the data/sld/sld folder, and you can use any of the existing files as an example for formatting.

**Comment by joe-nasti** [comment]
Thanks, Axxroy...I'm now aware of the downstream process for these, I'm still working to find some additional free time to submit the pull request for this and a few other open lists.

This can be closed. Thanks!

**Comment by joe-nasti** [comment]
Didn't mean to close as completed
