### ISSUE TITLE
AllCards.json should contain reserved list information

### ISSUE THREAD

**Issue by klaffke** [mtgjson/mtgjson#122]
If a card is on the reserved list is a set-independent attribute. It would be cool if the reserved field would be included in the AllCards.json file.

**Comment by KingSupernova31** [comment]
I agree with this. Cards on the reserved list should have a "reserved: true' field.  It should probably only be in AllCards-x.json file though, not the base AllCards.json.

**Comment by ZeldaZach** [comment]
This should be preserved in V4 :)
