### ISSUE TITLE
Invalid ISO 8601 in SetList.json, AllPrintings.json and ITP.json

### ISSUE THREAD

**Issue by grim7reaper** [mtgjson/mtgjson#1220]
#### Version(s) tested against

MTGJSON 5.2.2+20240816

#### Description of Bug

From `SetList.json`:

```json
{
  "baseSetSize": 67,
  "code": "ITP",
  "sealedProduct": [
    {
      "cardCount": 120,
      "category": "multiple_decks",
      "name": "Introductory Two Player Set Gift Edition",
      "purchaseUrls": {},
      "releaseDate": "1996-12-1",
      "subtype": "two_player_starter",
      "uuid": "14fb8593-1680-57a4-8214-83018d58cee0"
    }
  ],
  "tcgplayerGroupId": 2742,
  "totalSetSize": 67,
  "translations": {},
  "type": "starter"
}
```

⚠️ Same issue in `AllPrintings.json` and `ITP.json`

According to the ISO 8601 spec:

> Each date and time value has a fixed number of digits that must be padded with leading zeros.

So, it should be:
```json
      "releaseDate": "1996-12-01",
```

**Comment by ZeldaZach** [comment]
Fixed in https://github.com/mtgjson/mtg-sealed-content/commit/b05a6d3ff619bebe8f86728df69ae84bdcb2d11e
