### ISSUE TITLE
Unexpected SealedProduct in AllIdentifiers.json

### ISSUE THREAD

**Issue by grim7reaper** [mtgjson/mtgjson#1224]
#### Version(s) tested against

MTGJSON 5.2.2+20240816

#### Description of Bug

According to the documentation, the `AllIdentifiers.json` file is supposed to contains only `CardSet`

> File containing all [Card (Set)](https://mtgjson.com/data-models/card/card-set/) cards organized by the [uuid](https://mtgjson.com/data-models/card/card-set/#uuid) property.

But I've found some `SealedProduct`.

For example this one:

```json
"001651e5-5141-5c9e-8f7c-b3bf3b23c148": {
  "cardCount": 15,
  "category": "booster_pack",
  "contents": {
    "pack": [
      {
        "code": "collector",
        "set": "cmr"
      }
    ]
  },
  "identifiers": {
    "cardKingdomId": "238689",
    "cardtraderId": "146025",
    "csiId": "302913",
    "mcmId": "492109",
    "tcgplayerProductId": "221322"
  },
  "name": "Commander Legends Collector Booster Pack",
  "purchaseUrls": {
    "cardKingdom": "https://mtgjson.com/links/b07ad300c99d3bd5",
    "tcgplayer": "https://mtgjson.com/links/99e8db98840bccd1"
  },
  "releaseDate": "2020-11-20",
  "subtype": "collector",
  "uuid": "001651e5-5141-5c9e-8f7c-b3bf3b23c148"
},
```

**Comment by ZeldaZach** [comment]
Wow that's weird, I'm not sure how this slipped in.

**Comment by ZeldaZach** [comment]
Introduced in https://github.com/mtgjson/mtgjson/commit/1619c340201f3585a7d86375595748fb2500603a, seems this was a byproduct error
