### ISSUE TITLE
Remove the reserved attribute from cards of digital or non-tournament-legal sets

### ISSUE THREAD

**Issue by klaffke** [mtgjson/mtgjson#123]
The reserved list policy only applies to tournament-legal, printed magic cards.

The reserved attribute should be removed from all gold-bordered, square-cornered and digital sets:

Collector's Edition
International Collector's Edition
Vintage Masters
Masters Edition I
Masters Edition II
Masters Edition III
Masters Edition IV

**Comment by gwax** [comment]
The cards are still, technically, on the reserved list.
