### ISSUE TITLE
Base Set Size issues

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#1230]
#### Version(s) tested against
5.2.2+20240926

#### Description of Bug
There's a bunch of base set sizes that are just wrong.

DBL:

* currently 633
* should be 534
* 534 - highest number normal card
* 535 - prerelease card

BRO:

* currently 292
* should be 287
* literally says "/287" on cards

BRR:

* currently 189
* should be 63
* there are no cards with numbers higher than 126 and 126z
* 64+ are special schematic versions (rarity 1/6)
* 64+ should probably also have some flag like promo:schematic or something

JMP:

* currently 495
* should be 78
* literally says "/78" on cards

2X2:

* currently 577
* should be  331
* literally says "/331" on cards

LTR:

* currently 289
* should be 281
* cards 282 - 289 are not in draft boosters

@axxroytovu below for DSK

That's the whole list. I had TSR override but it was wrong on my end.

**Comment by axxroytovu** [comment]
DSK is incorrect: the base set size should be 286 instead of 301. The "Lurking Evil" cards are 287-301 and are treated the same as booster fun even if they aren't marked in scryfall as such.

**Comment by ZeldaZach** [comment]
These can be corrected in **https://github.com/mtgjson/mtgjson/blob/master/mtgjson5/resources/base_set_sizes.json**
