### ISSUE TITLE
'Desolation' incorrectly associated with set 'FBB' in AllCards.json (v4.1)

### ISSUE THREAD

**Issue by ghost** [mtgjson/mtgjson#124]
'Desolation' is incorrectly associated with the set 'FBB' in AllCards.json (v4.1). This is possibly the result 
 of confusion with the card 'Badlands' in 'FBB' which has the French name 'Désolation'.

**Comment by ZeldaZach** [comment]
So i looked in FBB.json and i don't see Desolation, but it does show the FBB tag in AllCards and AllSets. Will look into this!

**Comment by ZeldaZach** [comment]
Appears to be upstream issue with SF https://api.scryfall.com/cards/3b186460-d2af-4912-ba19-95b2cb5f1639?format=json&pretty=true is the URL and if you look at printings, https://api.scryfall.com/cards/search?order=set&q=%21%E2%80%9CDesolation%E2%80%9D+include%3Aextras&unique=prints, it will show both cards.

cc: @csuhta

**Comment by csuhta** [comment]
This issue is fixed upstream, the `prints_search_uri` field now provides a URI that links to searches that don't require using the `!""` operator.

**Comment by ZeldaZach** [comment]
Perfect, appreciated!!
