### ISSUE TITLE
Futureshifted incorrectly use "special" rarity

### ISSUE THREAD

**Issue by CajunAvenger** [mtgjson/mtgjson#125]
The shifted cards from Future Sight all use the Special rarity instead of their printed rarity (which is done correctly with the Planar Chaos shifted cards.)

**Comment by ZeldaZach** [comment]
I'll look into this

Note for me: https://api.scryfall.com/cards/47e6e715-abd8-4ff9-a8aa-8f4b929b0283?format=json&pretty=true
