### ISSUE TITLE
'Khans of Tarkir block' format only appears on Negate card; similar issue with BfZ block format.

### ISSUE THREAD

**Issue by PAK90** [mtgjson/mtgjson#127]
Two separate occurrences, but same issue; the AllSets-x.json file doesn't have KTK block format for any KTK block cards except Negate, and the 'BFZ block' format cards seem to only be applied to OGW cards.

**Comment by lsmoura** [comment]
Wizards changed "Tarkir" block to "KTK" block a while back... I'll fix it when time permits.

**Comment by gwax** [comment]
This has been resolved by previously committed PRs.
