### ISSUE TITLE
CED and CEI edition cards don't have "mciNumber"

### ISSUE THREAD

**Issue by dlmorais-13** [mtgjson/mtgjson#133]
Cards on file CED-x.json and CEI-x.json don't have the attribute "mciNumber", altought edition have field "magicCardsInfoCode".

Looks like to me it's something that was forgotten or something...

**Comment by MickHardins** [comment]
Sorry to bother you, but mcinumber issue has been fixed only for CED. This problem is still present in CEI.

**Comment by dlmorais-13** [comment]
There are a lot of editions without mciNumber, actually. Most of them promotionals.

CEI, pLGM, pMEI, pARL, pCEL, ITP, pPOD, pPRE, pJGP, pALP, ATH, pWOR, pGRU, pWOS, pSUS, pFNM, pELP, pMPR, p2HG, pGTW, pWPN, p15A, pLPA, pSUM, pMGD, pGPX, pPRO, pHHO, pCMP and DPA

**Comment by lsmoura** [comment]
All non-gatherer are missing...

**Comment by MickHardins** [comment]
I did a bit of testing: i checked all sets and verified if cards in set have a card numer != null, if they have i assumed that mcinumber would be the same( most of the time it is), if they don't i checked mci number.
sets that have mci missing number on some card **( missing/total_card_in_set > 0.01%)**:

LEA,LEB,ARN,2ED,ATQ,3ED,FEM,4ED,ICE,CHR,HML,ALL,RQS,MIR,MGB,ITP,5ED,POR,VAN,WTH,TMP,STH,PO2,ATH,BRB,S00,DDQ,W16,SOI

Most of the sets above have only land Cards with mciNumber = null ( e.g LEA, LEB ATQ) 
Instead sets that have all cards without mciNumber **(missing/total_card_in_set = 100%)** are the following:

ARN,FEM,ICE,ALL,RQS,MIR,MGB,ITP,POR,VAN,WTH,STH,PO2,ATH,BRB,S00,DDQ,W16,SOI

If you need them i can send you the complete list of cards that are missing this field in each expansions!
Hope this will be helpful to further improve MTGJSON ! :+1:

**Comment by MickHardins** [comment]
i'm posting again to report that 4ED and 5ED have mciNumberField set as "5e/en/numberofcard" instead of "numberofcard"

**Comment by gwax** [comment]
This was fixed in a previous rebuild.
