### ISSUE TITLE
Mythic rarity has different names in 'boosterV3' field and in 'rarity'

### ISSUE THREAD

**Issue by ivodopyanov** [mtgjson/mtgjson#137]
Card.rarity field can have 'mythic' value.
Set.boosterV3 array can have 'mythic rare' value.

That difference causes some inconvenience. Can it be uniform?

**Comment by ZeldaZach** [comment]
Since boosterV3 is fully compatible with V3 of MTGJSON, there will be no changes to the boosterV3 field at any time.

This is something to note for if/when we re-implement as "booster" (v4 incompatible version)
