### ISSUE TITLE
Flip cards are missing their colors

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#138]
For example, "Budoka Gardener" and "Dokai, Weaver of Life" should both have color: ["G"], but they do not.

**Comment by ZeldaZach** [comment]
Doesn't `colorIdentity` serve this purpose? The "colors" of a card are usually derived from the mana cost, but the flip side of cards do not have a mana cost.

**Comment by ZeldaZach** [comment]
Note to self: Simple fix, if necessary,

```python3
    if "colors" not in mtgjson_card:
        if "colors" in face_data:
            mtgjson_card["colors"] = face_data.get("colors")
        else:
            mtgjson_card["colors"] = sf_card.get("colors")
```

**Comment by KingSupernova31** [comment]
There are a lot of things that *could* be figured out from various fields. borderColor, colorIdentity, colors, convertedManaCost, frameVersion, hasNonFoil, supertypes, types, and subtypes are all redundant on every card- their values could be derived from the other fields. That doesn't mean that they should be inconsistently omitted on some cards and not on others.

The flipped side of flip cards *does* have a mana cost, which is what determines its color. And this bug applies to both sides of flip cards, not just the flipped side.

**Comment by fenhl** [comment]
`hasNonFoil` isn't redundant. There are cards that exist as both (e.g. most cards from booster products) and there are cards that only exist as foils (e.g. Kess, Dissident Mage).

**Comment by KingSupernova31** [comment]
It is indeed redundant, there's an `isFoilOnly` field. Regardless, that's not important. Those were just examples to illustrate that redundancy is not a reason to leave this bug unfixed.

**Comment by ZeldaZach** [comment]
Thanks for pointing out this issue. A fix has been added, as the "front" side not listing color is definitely an issue. Adding it to the back _shouldnt_ cause too many problems.
