### ISSUE TITLE
Reconsidering CMC for Split Cards

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson#142]
After talking with several parties, I am rethinking how we should handle split face cards CMCs.

On one hand, I agree that a card should list its CMC based on the mana cost. On the other hand, we should help convey the information of the split card by listening the combined CMC too.

My suggestion is we have two fields:

- `convertedManaCost` = the cost of the entire object. An object is a singular card. For `Far // Away` this field would be 5.
- `faceConvertedManaCost` = the cost of this portion. For `Far // Away` the field would be 2 and 3, respectively.  This field would only be available for split cards (and possibly rotation ones?).

Looking for some feedback, as this would be a 4.1.1 change if I don't get further inputs

**Comment by ancestral** [comment]
I support this idea, as a handful of cards care about CMC of a card outside of the stack (Inquisition of Kozilek, Repeal) while others care about the CMC of a spell (Disdainful Stroke, Chalice of the Void).
