### ISSUE TITLE
Missing translations from subsequent Gatherer pages

### ISSUE THREAD

**Issue by bra1n** [mtgjson/mtgjson#144]
Hi,

I just noticed that MTGJSON doesn't seem to pull any translations from Gatherer beyond the first page.
For example, Wastes lacks translations for Spanish, Russian and Chinese Simplified, which are all shown [on the second page](http://gatherer.wizards.com/Pages/Card/Languages.aspx?page=1&multiverseid=407694) on Gatherer. This is probably also the case for a couple of other cards, though I only noticed it on Wastes so far.
Can you fix this, please? :)

Thanks,
bra1n

**Comment by galaxyoyo** [comment]
I noticed this problem a long time ago, I wanted to create an issue now, but I was too late.
Yes, there aren't all foreignNames, you can see all basic lands, there are only 25 different printings, while basic lands can be 100 times printed (5 different illustrations (BFZ) * 2 (full-art/normal; BFZ/ZEN) * 10 languages).

**Comment by galaxyoyo** [comment]
I tried to put a little fix, that works but not very optimized : #173

**Comment by bra1n** [comment]
Bump, any news on this?

**Comment by ZeldaZach** [comment]
Using scryfall's data now for translations. Look to V4 for that impl! :)
