### ISSUE TITLE
Cards without multiverseId

### ISSUE THREAD

**Issue by dbottillo** [mtgjson/mtgjson#149]
Hi,

I've recently built all the sets and I have discovered that some cards are without a multiverseId.

Sets affected:
- Anthologies - all cards are without it
- DeckMasters - all cards are without it
- Duel Decks: Elves vs Inventors - only the card `Darksteel Plate`
- Duel Decks: Zendikar vs Eldrazi - The token`plant` is in the array of cards
- Duels of the Planeswalkers - all cards are without it
- Explorers of Ixalan - The token `Saproling` is in the array of cards
- From the Vault: Lore - only the card `Marit Lage`
- Tenth edition - all cards are without it
- Ultimate Masters - all cards are without it
- Unhinged - all cards version (b), eg. `Cardpecker (a)` has it, `Cardpecker (b)` doesn't

I've checked all the pre-built json as well at version `4.1.2`. 
Let me know if you need any more info!

Thanks :)

**Comment by tooomm** [comment]
It looks like, as least for UMA, there are no url's either.

**Comment by ZeldaZach** [comment]
@tooomm UMA wasn't up on SF when this ticket came out, it's fixed now on their end so I just need a rebuild. Will be done for the next release

**Comment by ZeldaZach** [comment]
So I brought this issue up with SF (one of our upstream providers) and they gave some valid input.

The following sets aren't available on Gatherer, so there's no way to associate a multiverseId to them
- Anthologies
- DeckMasters
- Duels of the Planeswalkers
- Unhinged (The alternate artwork cards are not on Gatherer)

The following sets have been fixed based on your feedback (thank you!):
- Duel Decks: Elves vs Inventors
- Ultimate Masters 

The following sets I will look into a fix, as it's correct as-is, but the tokens should be moved to the "tokens" array:
- Duel Decks: Zendikar vs Eldrazi
- Explorers of Ixalan
- From the Vault: Lore

I have checked the outputs, but 10th Edition appears to have MultiverseIds correctly associated.

___

In other news, please make sure you are not using multiverseids as a primary key. I have provided a UUID for that purpose. Not every card has an MID, but _every_ card has a UUID :)

**Comment by dbottillo** [comment]
yes I'm not using the `multiverseId` as a primary key :) But I'm using that to fetch the card image from gatherer, I'm thinking to maybe use the `scryfall` API for images in the future so I don't need the `multiverseId` anymore. I guess I can't display images for those 4 sets if they are not on gatherer 🤷‍♂️

**Comment by lebenski** [comment]
Awesome!  When will the next update go out?  I'm looking to get Ultimate Masters up on Cube Tutor before release of the set (Saturday) if possible.  Thanks for all your hard work on this new version @ZeldaZach

**Comment by ZeldaZach** [comment]
@lebenski Didn't know CT was using MTGJSON. Glad you like!

Since you're hoping to get an update on Saturday, I'll put out a fix build today or tomorrow (4.1.3)

**Comment by lebenski** [comment]
@ZeldaZach Much appreciated!  :)

**Comment by lfgcampos** [comment]
Interested in the new release as well!! =)
