### ISSUE TITLE
Banlist not updated

### ISSUE THREAD

**Issue by MitjaHenner** [mtgjson/mtgjson#150]
The Bans/Unbans from this year are not updated in the json files.
Modern:
Banned: Splinter Twin, Summer Bloom, Eye of Ugin
Unbanned: Sword of the Meek, Ancestral Vison

Vintage:
Restricted: Lodestone Golem

**Comment by tooomm** [comment]
Is there some kind of `banlist` file in the repo that the community can easily update (-->send pr) and support you instead of opening an issue on it @lsmoura?
You would just need to double check it. It needs to be part of the build process for sure to properly update the legalities on run.

**Comment by leematos** [comment]
@tooomm, my understanding is that it happens here:

https://github.com/lsmoura/mtgjson/blob/339374988e90342b4de42678b815545c28340646/build/rip.js#L625

And that re-creating those sets would create the right ban status & re-making all-sets.json to reflect that (still not sure how all-sets is made, still diving in to that. 💃 )

**Comment by lsmoura** [comment]
@tooomm idea seems awesome. I can just "rebuild" the legalities without rebuilding the whole set. I'll try to implement this.

The current way of updating the legalities is to delete the legality cache and rebuild the set.

**Comment by MitjaHenner** [comment]
What I don't really understand is the reason the legalities are wrong, since they are updated on gatherer. Its not only modern but also the sets that rotated out of standard.

**Comment by dgant** [comment]
Prophet of Kruphix needs an update as well, for its Commander ban.

**Comment by gwax** [comment]
This has been fixed by previous PRs.
