### ISSUE TITLE
idea: customize "type" keys

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson#152]
There are a lot of different `type` keys around in all file and in different logical places.

Wouldn't it be better and more helpful for the consumer to have unique or different naming for them?
Like `setType`, `cardType`, `cardTypeForeign` etc.

E.g. in the AllCards file if you search for "type" you find oracle "card type" next to each "card type" for every language for that card.

Does this proposal makes sense at all?

**Comment by ZeldaZach** [comment]
Can you give an example with JSON? It doesn't have to be large, just with enough entries to exemplify your points

**Comment by tooomm** [comment]
For example, `originalType` better specifies what it is about. Could even be `originalCardType`.
So that just by looking at the key you know what it relates to.

Currently there is 1x `type` for cards, 1x `type` for each foreign language, 1x `type` for each token and 1x `type` for each set.
Does this better explain where my idea came from? It's only about renaming and differentiating the several type keys.

**Comment by ZeldaZach** [comment]
The keys are all within individual structs, so I don't find this necessary or really helpful.

**Comment by tooomm** [comment]
Ok. 👍
