### ISSUE TITLE
Some cards have different ability texts than on gatherer

### ISSUE THREAD

**Issue by TheOnlyDJCat** [mtgjson/mtgjson#154]
While parsing new v4 of AllCards.json I found that several cards have ability texts that differ from the current gatherer text.

For example: Arclight Phoenix
- At the beginning of combat on your turn, if you've cast three or more instant and sorcery spells this turn, return Arclight Phoenix from your graveyard to the battlefield.
- At the beginning of combat on your turn, if you've cast three or more instant and sorcery spells this turn, you may return Arclight Phoenix from your graveyard to the battlefield.

Or: Arid Mesa
- T, Pay 1 life, Sacrifice Arid Mesa: Search your library for a Mountain or Plains card, put it onto the battlefield, then shuffle your library.

- T, Pay 1 life, Sacrifice Arid Mesa: Search your library for a Mountain or Plains card and put it onto the battlefield. Then shuffle your library.

Darkblade Agent:
- As long as you've surveilled this turn, Darkblade Agent has deathtouch and "Whenever this creature deals combat damage to a player, you draw a card."
- As long as you've surveilled this turn, Darkblade Agent has deathtouch and "Whenever this creature deals combat damage to a player, draw a card."

Maybe this comes from other editions that are not correctly updated?

**Comment by ZeldaZach** [comment]
Are you referring to `text` or `originalText`? the latter should always refer to what was printed on a specific card at the time of printing. the former should be consistent across all printings and contain the latest oracle text of the card.

**Comment by TheOnlyDJCat** [comment]
I can't see originalText in the json file?
I parse the "text" key. 
If it helps I attach the comparison of the gatherer version with the V4 version
[Compare.zip](https://github.com/mtgjson/mtgjson4/files/2642883/Compare.zip)

**Comment by ZeldaZach** [comment]
Since you closed the issue I can assume you were parsing the wrong field by accident? Either way, I’ll check the zip file tomorrow.

**Comment by TheOnlyDJCat** [comment]
Sorry, I'm a Github noob and clicked the wrong button ;)

**Comment by ZeldaZach** [comment]
Just tested around with this. Seems some cards have their API and on-card mismatched with updated text.

cc: @csuhta

**Comment by csuhta** [comment]
All three fixed

**Comment by TheOnlyDJCat** [comment]
I have checked the json from 4.1.3 version and there are still the other inconsistencies. only the three examples are fixed. Now I extracted all cards with different ability texts:

Assure // Assemble (Assure)
Bad River
Blood Crypt
Breeding Pool
Demotion
Faith's Fetters
Fertilid
Flood Plain
Godless Shrine
Grasslands
Hallowed Fountain
Land Tax
Mnemonic Betrayal
Pir's Whim
Plots That Span Centuries
Skyshroud Claim
Stomping Ground
Undercity Uprising
Vigor

**Comment by ZeldaZach** [comment]
cc: @csuhta :)

**Comment by csuhta** [comment]
These are all updated upstream, except: Plots That Span Centuries is not on Gatherer, it can't have different text.

**Comment by TheOnlyDJCat** [comment]
Yes you are right with "Plots...". I always check against my current own database which also has a few non- gatherer cards. But on other sites with extracted rule text, I see "Plots..." only with the word 'would' inbetween - as it was printed. I don't see a hint, that this word was removed anywhere?
