### ISSUE TITLE
Wrong card data: Erase, Old Fogey and Grimlock

### ISSUE THREAD

**Issue by JayDi85** [mtgjson/mtgjson#158]
Version: 4.1.2 (2018-11-30)

Cards data have wrong info, please check that:
 * [Erase](https://scryfall.com/card/ktk/9/erase):
   * FIXED: **cost** `{2}{W}` must be changed to `{W}`;
 * [Old Fogey](https://scryfall.com/card/unh/106/old-fogey): 
   * **PT** `null/null` must be changed to `7/7`;
   * **Type** `Summon` must be changed to `Creature` (maybe);
   * Scryfall have same problems, maybe it's not mistake (I'd reported it too, feedback id 80c26f47-146d-41cb-9d52-f68c598fb41f);
 * [Grimlock, Dinobot Leader](https://scryfall.com/card/h17/1/grimlock-dinobot-leader-grimlock-ferocious-king):
   * **cost** `{1}{W}{R}{G}` must be `{1}{R}{G}{W}` (it's different mana order with data and card image -- but scryfall have same error, I'd reported it too, feedback id ed35597d-3ee7-42cb-b011-df96128863ea).

**Comment by ZeldaZach** [comment]
Can you point me to which file(s) have this issue? So I can better pinpoint where things went wrong?

**Comment by JayDi85** [comment]
That's all in `AllCards.json.zip`

**Comment by ZeldaZach** [comment]
Can you confirm/deny this is a problem in other compiled outputs? (i.e. AllSets.json, UNH.json, etc.)

**Comment by JayDi85** [comment]
Hmm... I've checked direct json files -- that's `Erase` is fine (it's an `allcards` problem only):
 * https://mtgjson.com/v4/json/KTK.json
 * https://mtgjson.com/v4/json/M13.json
 * https://mtgjson.com/v4/json/ULG.json

Other cards: Old Fogey and Grimlock, Dinobot Leader have same "problems".

**Comment by ZeldaZach** [comment]
Just checked myself:

- Old Fogey is indeed a problem with upstream. I have reported this to them.
- Grimlock appears to be fine on the latest rebuild (that I just ran locally) `"manaCost": "{1}{R}{G}{W}",`. Also looked on SF and it appears correct. Maybe they _just_ fixed this?
- Erase has the correct mana cost (1)
- Erase (Not the Urza's Legacy One) has the correct mana cost (3)

**Comment by ZeldaZach** [comment]
Update: Summon is correct for Old Fogey as it's apart of the joke of the dino being _olddd_

The rest of the ticket is upstream based and will be fixed shortly. I appreciate the bug report! You're what drives MTGJSON and Scryfall to be the best sources of accurate content :)

**Comment by JayDi85** [comment]
Yearh, scryfall fixed Grimlock minutes ago. Thanks for your json data.
