### ISSUE TITLE
Wrong cards/tokens in Friday Night Magic sets

### ISSUE THREAD

**Issue by JayDi85** [mtgjson/mtgjson#159]
Friday Night Magic sets have wrong cards data. All tokens stores as `cards`, but it must stores as `tokens`. I'd checked [Friday Night Magic 2017](https://mtgjson.com/v4/json/F17.json) and [Friday Night Magic 2018](https://mtgjson.com/v4/json/F18.json). It's haven't tokens at all and save it as cards.

As example: 
 * FNM 2018 ([scryfall](https://scryfall.com/sets/f18), [mtgjsonv4](https://mtgjson.com/v4/json/F18.json));
 * Set have 3 double faced tokens;
 * But mtgjson stores it as 6 cards and 0 tokens.

**Comment by ZeldaZach** [comment]
Thanks for that, I have a fix in the works

**Comment by ZeldaZach** [comment]
Addressed in #156
