### ISSUE TITLE
Keywords in keywords.json should be case insensitive

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgjson#161]
As people may be using keywords.json to compare with the card data, the keywords should all be lowercase to emphasize that the keywords don’t always have capitalization (like `flying` or `investigate`).

**Comment by ZeldaZach** [comment]
Looking for additional feedback before considering a change on this

**Comment by excention** [comment]
I would agree.. the uppercase can always be applied via CSS on the consuming app
