### ISSUE TITLE
UMA set cards have not their multiverseId property

### ISSUE THREAD

**Issue by carlol** [mtgjson/mtgjson#162]
#### MTGJSON Version: 4.X.X
4.1.2 (2018-11-30)

#### Description of Bug:
Hi,
thank you for your really appreciated work.

In UMA set cards have not their multiverseId property, is it intentional because you are waiting for the gatherer update?

Best regards.

**Comment by lfgcampos** [comment]
It is fixed in the latest version (4.1.3).

**Comment by carlol** [comment]
I don't see it on https://mtgjson.com/v4/, have I to download it directly form github?

**Comment by lfgcampos** [comment]
I have downloaded it this morning and everything was fine. But I can't see this on the website anymore.
Let's wait for any other input from the guys.

**Comment by ZeldaZach** [comment]
This has been fixed in 4.1.3 and we're getting it live currently. Give us a bit of time :)
