### ISSUE TITLE
Duplicated cards in 10th edition without multiverseID

### ISSUE THREAD

**Issue by dbottillo** [mtgjson/mtgjson#164]
#### Description of Bug:
Some cards in https://mtgjson.com/v4/json/10E.json are duplicated and the copy doesn't have a `multiverseID`. For example: the first card is `Ancestor's Chosen` which has `multiverseId = 130500` and the card right after it's a copy `Ancestor's Chosen` but without `multiverseId`.

![screenshot 2018-12-09 at 15 44 17](https://user-images.githubusercontent.com/485717/49699457-4e922900-fbc9-11e8-875d-d1d852c4f31a.png)

On `scryfall` they are also duplicated: https://scryfall.com/sets/10e so the duplication may be fine but it would be nice to have a `multiverseId` for both of them!

**Comment by ZeldaZach** [comment]
So the reason for this is some cards have alternative text (usually in the foils). You'll notice that there is no reminder text in the foil versions, so SF considers them two different cards. You can also see that the card number has a star next to the number, indicating it's a modification of the original.

My potential fixes are:
- Remove duplicates from 10E
- Manually override with a MID
- Do nothing

Looking for additional opinions before moving forward with anything

**Comment by excention** [comment]
I would think something like "alternate":"art" or "alternate":"text" or not in the JSON if not an alternate... might be a better way and remove the Star from the number.

I track the alternates.

**Comment by dbottillo** [comment]
My preferred option would be to leave there as a duplicate but retain the MID from the original card, because it would be nice to show that card with the alternative image as well (they are foil). If that's not possible then I would prefer to remove the duplicate or have an `alternate: text` in the original card (although I would not using it for anything in my own app 🤷‍♂️ )

**Comment by ZeldaZach** [comment]
So to address this well I'd have to figure out what changed between cards, so I'd probably go with an `isAlternative (bool)` option, if anything. 

Contemplating still what to do, but it's a secret print in the set so not 100% certain what the best strategy is.
