### ISSUE TITLE
Missing UUIDs for Tokens

### ISSUE THREAD

**Issue by nhrsn** [mtgjson/mtgjson#167]
#### Description of Bug:

66 tokens are missing UUIDs. These tokens exist across sets A25, F12, F17, F18, GK1, GS1, L16, L17, PEMN, PHEL, UST.

**Comment by ZeldaZach** [comment]
Can you provide some examples? Would love to see all, but a small sample would be enough to pinpoint the issue

**Comment by nhrsn** [comment]
[tokenExamples.json.txt](https://github.com/mtgjson/mtgjson4/files/2666149/tokenExamples.json.txt)

**Comment by nhrsn** [comment]
That's all of them. Just set codes and names but I thought that'd be enough...

**Comment by ZeldaZach** [comment]
Ok so after reviewing this, the issue is only with double-sided tokens. My issue is I didn't split them up with UUIDs correctly, so i'll get that fixed. In conjunction with #173
