### ISSUE TITLE
Add cards gameplay info (abilities, targets, boost effects and more)

### ISSUE THREAD

**Issue by JayDi85** [mtgjson/mtgjson#168]
Hi.

I'm one of the developer of [XMage](https://github.com/magefree/mage) -- open source MTG game with full implemented mechanics, cards, AI and auto-ruling engine. We are using mtgjson for verify inner database and other cards info.

There are many useful info inside like abilities list for each card, target types for each ability, spell modes and other real gameplay data. I can write some scripts and generate json-data for your project -- you can download it and parse into your mtg database. It's not 100% correct, but can help with 80% of the cards.

Json example:
![shot_181211_172957](https://user-images.githubusercontent.com/8344157/49803847-6d7bf100-fd6a-11e8-8640-50518ec5de8b.png)

Cards info example:
![shot_181211_170721](https://user-images.githubusercontent.com/8344157/49802750-3ce68800-fd67-11e8-9602-e89291f2620b.png)

![shot_181211_171155](https://user-images.githubusercontent.com/8344157/49802943-e0d03380-fd67-11e8-93cc-2f0e1c0ea7f8.png)

But some cards have hard logic (dynamic code) and can't be dumped to json:

![shot_181211_171514](https://user-images.githubusercontent.com/8344157/49803105-5936f480-fd68-11e8-90ae-121141cd0010.png)

**Comment by ZeldaZach** [comment]
Interesting use of our data, I like!

Is this something I want to support mass scale? I'm not too sure. It feels very niche to your project, and you guys seem to already have a decent support engine for it.

If other people want to chime in opinions, I'd love to hear if this is something everyone wants.

**Comment by ZeldaZach** [comment]
Hey @JayDi85 coming back to the ticket, I may have misunderstood what you were saying.

Are you implying that you'd like to contribute to the project with your program that parses out the abilities fields and such? If so, that would be awesome! Feel free to open a PR and we can discuss the code changes there.

If you meant something else, please let me know as I'm still a bit confused with what you were saying 😅

**Comment by JayDi85** [comment]
I have mtg app with manually added and refined game logic and cards with all abilities and data (that's app developed many years and have ~18k unique cards). So what can we do:
1. You are creates data list or json example with info (what you want get for your project -- see examples at my first post);
2. I'm creates extra java scripts in my project -- that's scripts will use game engine, process code and cards, and create new json-file (it's not a text parser -- it's a source code, see my first post);
3. You are gets that json-file (as example, by http), parse it and load data to your project;
4. Time by time I'm run scripts again and generate updated json-file for you with new data.

P.S. [XMage](https://github.com/magefree/mage) uses automatic scripts to build app from source (java - maven). If you setup java development environment then you can build that app and json-data by yourself (as example: I can create docker with dev environment and command to build that script/json).

**Comment by ZeldaZach** [comment]
@JayDi85 Can you write out a step-by-step guide to use it? I'm looking through the XMage source, but I can't find what I'm looking for

**Comment by JayDi85** [comment]
Added generated json example (see attachment):
[jsonexample1.txt](https://github.com/mtgjson/mtgjson/files/2704779/jsonexample1.txt)

Code example to generate it:
[ExportJsonGameplayDataTest.java.txt](https://github.com/mtgjson/mtgjson/files/2704961/ExportJsonGameplayDataTest.java.txt)

Sample from that file:

```
  "Barging Sergeant": {
    "abilities": [
      {
        "cost": "{4}{R}",
        "name": "Cast Barging Sergeant",
        "class": "SpellAbility"
      },
      {
        "cost": "",
        "name": "haste",
        "class": "HasteAbility"
      },
      {
        "cost": "",
        "name": "mentor \u003ci\u003e(Whenever this creature attacks, put a +1/+1 counter on target attacking creature with lesser power.)\u003c/i\u003e",
        "class": "MentorAbility",
        "modes": [
          {
            "effects": [
              {
                "class": "AddCountersTargetEffect",
                "outcome": "Benefit",
                "text": "put a +1/+1 counter on target attacking creature with lesser power"
              }
            ],
            "targets": [
              {
                "name": "attacking creature with lesser power",
                "class": "TargetCreaturePermanent",
                "min": 1,
                "max": 1
              }
            ]
          }
        ]
      }
    ]
  }
```

**Comment by ZeldaZach** [comment]
This is pretty cool, but it's a lot of bloat that I'm not sure everyone would appreciate.

I've been poked about this for a bit, but maybe going back to "extra" files compared to "stripped" files might be useful. The ideas I would have for those stripped files I will bring up in another ticket.

**Comment by ZeldaZach** [comment]
So I started playing around with the code you sent, and modified it: https://gist.github.com/ZeldaZach/10388092173753b19332b2f210baa2e4

It seems that Xmage is failing at quite a few tests when you call `mode.getTargets().get(0)` as the getTargets() is returning an empty array. This is called from `resEffect.addProperty("text", effect.getText(mode));` 

I'm not big into the XMage codebase, so me debugging this is probably a moot point. @JayDi85 Maybe you and your squad can look into this so I can get this program running for all sets? :)

**Comment by JayDi85** [comment]
I'm [fixed that errors in master](https://github.com/magefree/mage/commit/942ecc5328e4008d8039d2a5d1aa23e50b19200e). Also uploaded export code example to 
`Mage.Tests/src/test/java/org/mage/test/utils/ExportJsonGameplayDataTest.java`

**Comment by ZeldaZach** [comment]
I'm still contemplating the best way to add such data to MTGJSON. I'm close to a solution in my head, but I'm hoping to get some outside feedback too :)

**Comment by excention** [comment]
It might be interesting if you have a game mechanics side JSON that can be downloaded that references the UUIDs of this project.

**Comment by ZeldaZach** [comment]
Hmm, that's an interesting idea. Would be very different than what I'm used to, so maybe the alternative download would be `{"MTGJSON_UUID": ...}`

**Comment by ZeldaZach** [comment]
I've decided to pass on this for the time being. The script to generate isn't working as expected, and the build time for adding this seems a bit lengthy.

If you're able to generate the data as one file stored as `{"MTGJSON_UUID": [card abilities], ...}` I'd consider a pull request, but I don't feel exerting any more energy on my part would be useful. @JayDi85
