### ISSUE TITLE
Incorrect Meld Card Name Ordering ("Chittering Host" - EMN)

### ISSUE THREAD

**Issue by nhrsn** [mtgjson/mtgjson#170]
#### Description of Bug:

"Chittering Host" should be at index 1, as per documentation.

```
[12] pry(main)> j['EMN']['cards'].find { |c| c['name'] =~ /Brisela/ }['names']
=> ["Bruna, the Fading Light", "Brisela, Voice of Nightmares", "Gisela, the Broken Blade"]
[13] pry(main)> j['EMN']['cards'].find { |c| c['name'] =~ /Rats/ }['names']
=> ["Graf Rats", "Midnight Scavengers", "Chittering Host"]
[14] pry(main)> j['EMN']['cards'].find { |c| c['name'] =~ /Chittering/ }['names']
=> ["Graf Rats", "Midnight Scavengers", "Chittering Host"]
 ```

**Comment by nhrsn** [comment]
Left this as a comment on a merged PR so it may have been missed. Thank @tooomm for pinging me 😄

**Comment by ZeldaZach** [comment]
Reported as an issue upstream. Thanks for pointing this out!

**Comment by ZeldaZach** [comment]
So upstream will be adding a new way of handling the parts, and won't be fixing this on their end. I'll look into a manual override soon (temporary placeholder)

**Comment by KingSupernova31** [comment]
This is not fixed.

**Comment by ZeldaZach** [comment]
Just tested, it is for me?

<img width="358" alt="screenshot 2018-12-20 13 51 10" src="https://user-images.githubusercontent.com/7460172/50304565-528e3880-045e-11e9-922d-742598507fa1.png">
<img width="359" alt="screenshot 2018-12-20 13 51 07" src="https://user-images.githubusercontent.com/7460172/50304566-528e3880-045e-11e9-8f4a-e4c39c88b214.png">
<img width="371" alt="screenshot 2018-12-20 13 51 03" src="https://user-images.githubusercontent.com/7460172/50304567-528e3880-045e-11e9-9167-8c76bf298dc1.png">

**Comment by KingSupernova31** [comment]
That's only one of them. Hanweir and Brisela are still broken.

**Comment by ZeldaZach** [comment]
I'm very confused. They look right to me.

<img width="429" alt="screenshot 2018-12-20 13 58 19" src="https://user-images.githubusercontent.com/7460172/50304921-566e8a80-045f-11e9-8e10-d07c4501135b.png">
<img width="466" alt="screenshot 2018-12-20 13 58 15" src="https://user-images.githubusercontent.com/7460172/50304922-566e8a80-045f-11e9-837f-1222a5814a1a.png">
<img width="466" alt="screenshot 2018-12-20 13 58 12" src="https://user-images.githubusercontent.com/7460172/50304923-566e8a80-045f-11e9-8959-5c44fec33c38.png">


<img width="497" alt="screenshot 2018-12-20 14 00 36" src="https://user-images.githubusercontent.com/7460172/50305014-a64d5180-045f-11e9-99d5-90c08e17954f.png">
<img width="530" alt="screenshot 2018-12-20 14 00 28" src="https://user-images.githubusercontent.com/7460172/50305015-a64d5180-045f-11e9-9d95-0306aad3cae3.png">
<img width="494" alt="screenshot 2018-12-20 14 00 25" src="https://user-images.githubusercontent.com/7460172/50305016-a64d5180-045f-11e9-83b2-4a8ec5c07c02.png">

**Comment by KingSupernova31** [comment]
Hanweir Battlements and Gisela, the Broken Blade should be index 0, not 2. They're switched with the other half.

**Comment by tooomm** [comment]
Linking the follow up issue: https://github.com/mtgjson/mtgjson/issues/187
