### ISSUE TITLE
Ripping Set Error

### ISSUE THREAD

**Issue by carlol** [mtgjson/mtgjson#170]
I tried to update FRF but I got this error:

`Error: multiverseid [391823] cardParts length [0] does not equal printedCardParts length [1]
oracle url: http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=391823&printed=false
printed url: http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=391823&printed=true`

How can I solve it?

Thank you

**Comment by lsmoura** [comment]
Are you still having this problem? I've just re-fetched FRF on a clean repository clone and it worked just fine...

**Comment by fenhl** [comment]
I have this problem for 10E.

**Comment by gwax** [comment]
This is a problem with the download cache. It is reasonable to mark this as a duplicate to #313 

The work around is to run `node util/clearCacheForSet original <set code>` and try again.

**Comment by gwax** [comment]
This was fixed between #392 and #394
