### ISSUE TITLE
Bring back gatherer set code

### ISSUE THREAD

**Issue by ArkadesSabboth** [mtgjson/mtgjson#171]
Version 3 had multiple fields for the set code :
- code  : The code name of the set
- gathererCode : The code that Gatherer uses for the set.
- oldCode : An old style code used by some Magic software.
- magicCardsInfoCode : The code that magiccards.info uses for the set. 

version 4 have : 
- code : Set code for the set.
- mtgoCode :  Set code for the set as it appears on Magic: The Gathering Online.
	
magiccards.info is defunct and I can live without oldCode but I would like if you bring back gathererCode 
I doubt I am the only one who used it.

For exemple the code for Alpha is LEA, mtgoCode is empty and on gatherer it is 1E

**Comment by ZeldaZach** [comment]
I have no easy way to re-impl this field, and I'm not sure what information you'd need from gatherer as we have everything from them, plus more. Unfortunately this is probably a nofix on our end :(

If you'd like to provide a use case, I'm sure we can help find a way to better integrate MTGJSON usage! Feel free to reach out whenever
