### ISSUE TITLE
[UMA] Mythic Rare issue

### ISSUE THREAD

**Issue by lfgcampos** [mtgjson/mtgjson#172]
MTGJson4 is using `mythic` and not `mythic rare` for mythics card.
I have looked on gatherer and scryfall and they use `Mythic Rare`.

Example links:
- http://gatherer.wizards.com/Pages/Card/Details.aspx?printed=true&multiverseid=456785
- https://scryfall.com/card/uma/189/vengevine

ps: I've tagged as UMA but haven't checked the other jsons.

**Comment by ZeldaZach** [comment]
Interesting, as SF's API uses `mythic` but I could agree to upgrading it ourselves to mythic rare. Will tag them just in case this is an oversight on their part.

cc: @csuhta

**Comment by csuhta** [comment]
Our API always uses the value `mythic`, but we sometimes display that as “M” or “Mythic Rare” around the site in UI.

**Comment by ZeldaZach** [comment]
Sounds good. The word "mythic" should be clear enough imo, as there's no "mythic commons" etc. If that were to ever change, I would consider updating the program to include "mythic rare" but for the time being I find this appropriate.

If you disagree and can provide good reasoning, I am more than willing to reconsider this topic. Thanks for helping improve MTGJSON :)
