### ISSUE TITLE
Ultimate Masters Base Card Number 79

### ISSUE THREAD

**Issue by excention** [mtgjson/mtgjson#174]
#### Description of Bug:

the base card number in Ultimate masters is 79 instead of 254. 

`   "UMA": {
        "baseSetSize": 79,
        "cards": [`

**Comment by ZeldaZach** [comment]
That's really weird... will look into it

**Comment by ZeldaZach** [comment]
So this is fixed when I rebuilt my local program and ran it. Will be "fixed" when the next release is live. Thanks for reporting this issue!!
