### ISSUE TITLE
Offer download of all sets/cards of only "legal" (not Unglued/Unhinged) cards

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgjson#178]
It would be great if there was a way to download all cards or all sets without the Unglued and other non-legal, silly cards. Like many I am sure, I choose to completely ignore these cards when compiling, analyzing and parsing Magic cards.

Thanks!

**Comment by lsmoura** [comment]
I like this.

**Comment by fenhl** [comment]
Such a filtered download should also exclude the token cards listed for some Duel Decks.

**Comment by ancestral** [comment]
Good point.

Also, it should exclude Scheme cards, Plane cards, Conspiracies and of course, other Celebration cards.

**Comment by ZeldaZach** [comment]
I'm still not sure how I want to do this in V4. Ticket has been moved to https://github.com/mtgjson/mtgjson4/issues/47
