### ISSUE TITLE
Make flags better

### ISSUE THREAD

**Issue by PAK90** [mtgjson/mtgjson#178]
There should be a flag or some notification when the python script is run without TCGPlayer credentials, else the script will just crash on trying to retrieve a TCGPlayer url. For devs that don't have a key, maybe an option to skip the price acquisitions too might be good.

**Comment by ZeldaZach** [comment]
Gonna update this ticket: Make my flags better :)

Ask for (or give option to omit) TCGPlayer dev key

**Comment by ZeldaZach** [comment]
For most of my use cases I only need 'normal' cards, i.e. non-token, non-scheme, non-vanguard, non-funny, etc. cards. Having a flag for this would be very useful. Scryfall offers some set categorizations, which might be handy.
