### ISSUE TITLE
Have the ability to exclude 'abnormal' sets by flag.

### ISSUE THREAD

**Issue by PAK90** [mtgjson/mtgjson#179]
For most of my use cases I only need 'normal' cards, i.e. non-token, non-scheme, non-vanguard, non-funny, etc. cards. Having a flag for this would be very useful. [Scryfall offers some set categorizations](https://scryfall.com/docs/api/sets), which might be handy.

**Comment by ZeldaZach** [comment]
I'm gonna call this a dupe of #178
