### ISSUE TITLE
mciNumber Formatting in 4th and 5th Edition

### ISSUE THREAD

**Issue by ebmusicman84** [mtgjson/mtgjson#180]
The mciNumber for 4th and 5th edition is formatted strangely.  Examples: 

| Zephyr Falcon                   | 5e/en/137 |
| Zombie Master                   | 5e/en/69  |
| Zur's Weirding                  | 5e/en/138 |
| Abomination                     | 4e/en/1   |
| Air Elemental                   | 4e/en/59  |
| Alabaster Potion                | 4e/en/251 |

**Comment by MickHardins** [comment]
#133

**Comment by gwax** [comment]
This was fixed in a previous rebuild.
