### ISSUE TITLE
Add officialCode field

### ISSUE THREAD

**Issue by fenhl** [mtgjson/mtgjson#182]
As suggested [here](https://github.com/lsmoura/mtgjson/issues/156#issuecomment-215835896), a field for the official set code of a set would be useful in the cases where the `"code"` field is different. The wiki has official references for most set codes.

**Comment by lsmoura** [comment]
Which wiki?

**Comment by fenhl** [comment]
http://mtgsalvation.gamepedia.com/. Each set's article (except for a few where we couldn't find any official sources) has a reference next to the set code in its infobox.

**Comment by Garbee** [comment]
Which codes are currently incorrect?

**Comment by fenhl** [comment]
Comparing the sourced set codes on the wiki with the [set overview](http://mtgjson.com/sets.html), I notice *Nemesis* (listed as NMS, should be [NEM](http://magic.wizards.com/en/articles/archive/ask-wizards-august-2004-2004-08-02)), *Portal Second Age* (listed as PO2, should be [P02](http://magic.wizards.com/en/articles/archive/ask-wizards-august-2004-2004-08-02)), *Commander's Arsenal* (listed as CM1, should be [CMA](http://magic.wizards.com/en/game-info/products/card-set-archive/commanders-arsenal)), and *Duel Decks: Heroes vs. Monsters* (listed as DDL, should be [HVM](http://magic.wizards.com/en/game-info/products/card-set-archive/duel-decks-heroes-vs-monsters), though this might be incorrect since the card set archive also lists Theros as THR).

**Comment by ZeldaZach** [comment]
Fixed in V4, using SF data
