### ISSUE TITLE
Kyscu Drake in visions has a "side" = c attribute in error.

### ISSUE THREAD

**Issue by excention** [mtgjson/mtgjson#184]
#### Description of Bug:
Kyscu Drake in visions has a side attribute with the value of C. According to zach this is due to the multiple names in the names array being linked as "combo pieces" and not being checked correctly.

`,
            {
                "artist": "Geofrey Darrow & I. Rabarot",
                "borderColor": "black",
                "colorIdentity": [
                    "G"
                ],
                "colors": [
                    "G"
                ],
                "convertedManaCost": 4.0,
                "foreignData": [
                    {
                        "language": "German",
                        "name": "Kyscusceada",
                        "text": "Fliegend\n{G}: +0/+1 bis zum Ende des Zuges. Du kannst nicht mehr als {G} auf diese Art pro Zug ausgeben.\nOpfere den Kyscusceada und den Feuerspeienden Sceada: Durchsuche Deine Bibliothek nach dem Viashivan-Drachen und bringe ihn direkt ins Spiel, als ob er gerade gesprochen worden wäre. Mische Deine Bibliothek danach neu.",
                        "type": "Beschwörung eines Sceadas"
                    },
                    {
                        "language": "Spanish",
                        "name": "Draco de Kyscu"
                    },
                    {
                        "language": "French",
                        "name": "Drakôn du kyscû"
                    },
                    {
                        "language": "Italian",
                        "name": "Draghetto di Kyscu"
                    },
                    {
                        "language": "Portuguese (Brazil)",
                        "name": "Dragonete de Kyscu"
                    }
                ],
                "frameVersion": "1997",
                "hasFoil": false,
                "hasNonFoil": true,
                "isReserved": false,
                "layout": "normal",
                "legalities": {
                    "1v1": "Legal",
                    "commander": "Legal",
                    "duel": "Legal",
                    "legacy": "Legal",
                    "vintage": "Legal"
                },
                "manaCost": "{3}{G}",
                "multiverseId": 3668,
                "name": "Kyscu Drake",
                "names": [
                    "Spitting Drake",
                    "Kyscu Drake",
                    "Viashivan Dragon"
                ],
                "number": "111",
                "originalText": "Flying\nooG +0/+1 until end of turn. You cannot spend more than oG in this way each turn.\nSacrifice Kyscu Drake and Spitting Drake: Search your library for Viashivan Dragon and put it into play. Shuffle your library afterwards.",
                "originalType": "Summon - Drake",
                "power": "2",
                "printings": [
                    "VIS"
                ],
                "rarity": "uncommon",
                "rulings": [
                    {
                        "date": "2004-10-04",
                        "text": "Because the “search” requires you to find a card with certain characteristics, you don’t have to find the card if you don’t want to."
                    }
                ],
                "side": "c",
                "subtypes": [
                    "Drake"
                ],
                "supertypes": [],
                "tcgplayerProductId": 5876,
                "text": "Flying\n{G}: Kyscu Drake gets +0/+1 until end of turn. Activate this ability only once each turn.\nSacrifice Kyscu Drake and a creature named Spitting Drake: Search your library for a card named Viashivan Dragon and put that card onto the battlefield. Then shuffle your library.",
                "toughness": "2",
                "type": "Creature — Drake",
                "types": [
                    "Creature"
                ],
                "uuid": "b6f14bbe-2436-4a5a-8e2a-8066b740b715"
            },`

**Comment by ZeldaZach** [comment]
Fixed in 3c377417fef17c2a99dbb7d09f4048deba12cee4 <3
