### ISSUE TITLE
Many release dates are incorrect

### ISSUE THREAD

**Issue by fenhl** [mtgjson/mtgjson#184]
Looking through the [set overview](http://mtgjson.com/sets.html), I see many sets listed as released on the first of the month. [The wiki](http://mtgsalvation.gamepedia.com/) has the exact dates for most of these, so someone should go through the sets and fix them in the database.

**Comment by fenhl** [comment]
Can anyone point me to where the release dates are defined? I could fix them and send a pull request.

**Comment by lsmoura** [comment]
They are defined over here: https://github.com/lsmoura/mtgjson/blob/master/shared/C.js
