### ISSUE TITLE
Some cards are specified as legal in 'Tarkir Block', the rest in `Khans of Tarkir Block`

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#185]
2710 cards are defined as `Khans of Tarkir Block` format, 30 as `Tarkir Block` format.

Full list is:
- BRB - Arc Lightning
- FRF_UGIN - Watcher of the Roost
- FRF_UGIN - Mystic of the Hidden Way
- FRF_UGIN - Debilitating Injury
- FRF_UGIN - Grim Haruspex
- FRF_UGIN - Ruthless Ripper
- FRF_UGIN - Ainok Tracker
- FRF_UGIN - Arc Lightning
- FRF_UGIN - Jeering Instigator
- FRF_UGIN - Dragonscale Boon
- FRF_UGIN - Altar of the Brood
- FRF_UGIN - Briber's Purse
- FRF_UGIN - Ghostfire Blade
- HOP - Arc Lightning
- KTK - Watcher of the Roost
- KTK - Mystic of the Hidden Way
- KTK - Debilitating Injury
- KTK - Grim Haruspex
- KTK - Ruthless Ripper
- KTK - Ainok Tracker
- KTK - Arc Lightning
- KTK - Jeering Instigator
- KTK - Dragonscale Boon
- KTK - Altar of the Brood
- KTK - Briber's Purse
- KTK - Ghostfire Blade
- USG - Arc Lightning
- pARL - Arc Lightning
- pPRE - Grim Haruspex
- pPRE - Jeering Instigator

Presumably FRF_UGIN is mistagged.

**Comment by gwax** [comment]
This appears to have been fixed in a previous build.
