### ISSUE TITLE
Some cards have still different ability texts than on gatherer

### ISSUE THREAD

**Issue by TheOnlyDJCat** [mtgjson/mtgjson#185]
#### Description of Bug:

Following https://github.com/mtgjson/mtgjson4/issues/154
After the last update only 3.5 cards are still different than the gatherer/correct version.

- Circuitous Route

- The Savant (I know there is no gatherer entry for that, but the AllCards.json text differents also from the printed version?)

- Plots That Span Centuries (I know there is no gatherer entry for that, but the AllCards.json text differents also from the printed version?)

- Plated Crusher is a bit unclear to me, how it should be done. On gatherer the two keywords are on two lines (I think because of the reminder text). In AllCards.json they are comma-separated.

**Comment by ZeldaZach** [comment]
cc @csuhta

**Comment by csuhta** [comment]
All fixed upstream

**Comment by ZeldaZach** [comment]
Appreciate the help, as always :)
