### ISSUE TITLE
"printings" should be lowercase

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#186]
The set codes in SetList.json are lowercase, while set codes everywhere else are uppercase.

**Comment by ZeldaZach** [comment]
Documentation states this is intended behavior. If someone wants it in capitals, they can do it themselves very easily.

**Comment by KingSupernova31** [comment]
Why would this be intended? There is no benefit to requiring a case-change in order for any comparison to be made.

And the documentation only states that most set codes are uppercase, it says nothing about SetList.json being lowercase. (The example is lowercase, but if there are going to be inconsistencies that people won't expect, the documentation should state as much explicitly.)

**Comment by ZeldaZach** [comment]
It aligns to the lower-case change we made for Keywords, the `code` and `mtgo` fields within a Set.

Seems like `printings` is capitalized, so I could look to change that

**Comment by scarletcs** [comment]
APIs vary on whether or not they capitalise or lowercase set codes, meaning most peoples' workflows will need conversion at some point, it'd just be a matter of whether the conversion is to uppercase or lowercase and where it happens and to what data set.

I think the best thing for MTGJSON to do here would be to pick a philosophy as to how it wants to present set codes and stick with that to make comparisons within its own data set consistent.  Lowercasing or uppercasing would both work.

**Comment by ZeldaZach** [comment]
Based on the fact that we've been going on a lower-case binge recently, I am more inclined to update printings to be lowercase. Will re-open with new name.
