### ISSUE TITLE
2 of the meld pairs have incorrect side and name order

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#187]
Hanweir Battlements and Gisela, the Broken Blade should be `side: "a"` and have index 0 in the `names` array, but they are instead `side: "b"` and index 2. (Hanweir Garrison and Bruna, the Fading Light are of course also affected in the inverse manner.)

The Graf Rats meld pair is correct.

**Comment by ZeldaZach** [comment]
So I'm looking at it again, but we don't state anything about the ordering, just that one part will be 1st, the other part will be 3rd, and the melded combination will be 2nd. I'm not sure if this is worth fixing. 

Looking for other opinions

**Comment by KingSupernova31** [comment]
The documentation says "Meld cards are listed in the order of CardA, Meld, CardB."

Hanweir Battlements and Gisela, the Broken Blade are card A, yet they're in the place of card B.

**Comment by ZeldaZach** [comment]
So I've thought about this further, and I have come to the conclusion that this will be a no fix.

My reasoning: If you take a look at the numbering, in the three meld pairs, they are inconsistent with how they choose to define what card number to give the meld pair (Bruna/Hanweird depend on the top half, Chittering on the bottom). As such, this makes it quite hard to dictate the ordering back to the user.

Our documentation states that you will find **[Meld Piece, Melded Object, Meld Piece]**. While this may not be clear in the current version of the document, we will make it clear in the next revision. I feel it is appropriate here to leave this to the end user to decipher as meld is inherently weird and we're already providing a _lot_ of help with the information provided.

I'm sorry if this isn't the outcome you're looking for, but if someone ever were to come up with an interesting solution that could account for Wizards' awkward printing style with numbering, this can possibly be revisited in the future.
