### ISSUE TITLE
Language map is incomplete

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson#19]
https://github.com/mtgjson/mtgjson-python/blob/master/mtgjson4/mtg_global.py#L759-L769

"Korean" and "Chinese Simplified" is missing, see http://gatherer.wizards.com/Pages/Card/Languages.aspx?multiverseid=442889

**Comment by ZeldaZach** [comment]
If you'd like to open a PR to fix that quickly, please feel free to
