### ISSUE TITLE
Eldritch Moon is now on Gatherer

### ISSUE THREAD

**Issue by dgant** [mtgjson/mtgjson#191]
Sooner than usual!

http://gatherer.wizards.com/Pages/Search/Default.aspx?set=[%22Eldritch%20Moon%22]

**Comment by lsmoura** [comment]
OMG! Look at the "Brisela trio" card numbers:
15a, 15b and 28a... There is no "28b", but there is a "28a". OMG...

**Comment by Garbee** [comment]
@tooomm You don't need to comment at all to subscribe to an issue. Just click "Subscribe" on the right sidebar of an issue under the "Notifications" header. That way you aren't causing more email and notifications to go around then necessary.

**Comment by florentdouine** [comment]
I'm looking for a simple solution too @lsmoura 
Maybe we can handle this case manually by duplicating Brisela's card for both 15b and 28b ?

**Comment by Garbee** [comment]
There are also [other problems](https://twitter.com/JonGarbee/status/753194694226706432) with the numbering format with this crap. I think it best to wait a bit and see if they update things before having numbers change under us.

**Comment by Garbee** [comment]
@lsmoura The "28b" is less of an issue in this  case, as it is a half of "15b". The bigger issue is the one I linked to on twitter which is where the *face* card is "204b" or whatever while the "a" part is the flip side half of the linked card.

We can actually handle the linking right by just using the data provided. The issue more-over is, why do *face* cards have "a" identifiers. I think this is either a mistake *or* they built their system to only handle a true double-split and never something as complex as this. Therefore, they are hacking the data around their engines limitation which is awful (over just fixing the engine.)

**Comment by dgant** [comment]
For my purposes, it doesn't matter what the printing numbers are, and barely matters if they change later.  I recognize that there may be very good reasons why other consumers may depend on stable/logical card numbering. But I'd endorse a rapid release, even if it comes with a footnote of "this is subject to change"

Players look at sites like MagicCards.info, see a 2-3 week delay in adding the latest set, and conclude that the site is dead. The next few weeks will be a peak in interest in Eldritch Moon, and a delay in getting card data online will be perceived as outdatedness, untrustworthiness, or even site death. That's unreasonable, yes, but that's how many players think. I find more value in imperfect information now than perfect information later.

**Comment by Garbee** [comment]
Your needs may differ from others, and yes some people rely on stable numbering since the numbers *shouldn't change*. We should make sure they are accurate before pushing.

You can very easily put a notice up that you need to wait on pulling in the data since there seems to be a discrepancy with the data.

Also, the mtjson ID itself is created using a *hash that includes the number* so if that is to change, so is the ID internally which means sites using that to sync updated data are going to get messed up.

Overall, the reasons for waiting for confirmation from Wizards that this is in fact correct way outweigh the need to "rush out" simply for the people that don't care about the number being correct superficially.

**Comment by dgant** [comment]
An MTGJson release that's subject to amendments, and marked as such, provides zero value for you, but 99+% value for others.

Moreover, we have no reason to believe Wizards is going to change these numbers. The numbers are printed on the physical cards. Those will not change. The letters could, in theory, change, but nobody is disputing the letters. Should MTGJson be frozen until we get written confirmation from someone at Wizards? They don't give two hoots about us.

**Comment by Garbee** [comment]
>The numbers are printed on the physical cards.

`a` and `b` denotations are **not** printed on the cards physically. Which is where the problem arises since it only exists in Gatherer (where we pull data from.) The "card number" in the JSON (which is hashed into the ID) will contain the letters as a part of the identifier.

**Comment by dgant** [comment]
> The letters could, in theory, change, but nobody is disputing the letters.

**Comment by Garbee** [comment]
Also, people do have *automated* systems running against this. They may never know of a possible issue until it is too late.

**Comment by Garbee** [comment]
The system can't exactly handle that efficiently. If you'd like to contribute to a more optimized system that can efficiently handle multiple release points then new issues to facilitate that are welcome.

IMO, if you are at the point _currently_ where you need the data "ASAP NO EXCUSES" then write your own parser for gatherer and do it by directly scraping the site. An API (especially with the ability to only facilitate one channel) should err on the stability side and take its time when something bonkers like this appears. Quite a bit of CPU time gets crunched when punching out a new release with the current setup, that shouldn't be taken lightly.

**Comment by tooomm** [comment]
Written from @Garbee:
>@tooomm You don't need to comment at all to subscribe to an issue. Just click "Subscribe" on the right sidebar of an issue under the "Notifications" header. That way you aren't causing more email and notifications to go around then necessary.

That is either not true, not working for me... or I simply don't understand it!

It looks like this for every single issue, even if I'm visiting it for the first time and never had participated to it or got mentioned there before:
![sub](https://cloud.githubusercontent.com/assets/9874850/16816250/6e90e26e-493d-11e6-94ab-e841fad125dd.png)
And of course I don't receive notifications for each and every issue. :)

**Comment by Garbee** [comment]
@tooomm Then [get in touch](https://github.com/contact) with Github if it isn't working for you. But that [is what that button](https://help.github.com/articles/subscribing-to-conversations/) should trigger.

**Comment by galaxyoyo** [comment]
There are only three meld pairs. Isn't it possible to make an exception, to add (temporary or not) the three pairs manually? I think that's the best solution you can do shortly ... But I know it can be better ...

**Comment by Garbee** [comment]
How would we add them manually if we don't know if the existing data is accurate or not? We could add them how they *logically* should be, but Wizards can still decide that their way is right and never update. We'd then be out-of-sync with the "official" Gatherer data.

**Comment by lsmoura** [comment]
For those who need the info already: 9d1882b9023240b6374714f3169ff3a6cfb28b82

Please read the commit information before using.
