### ISSUE TITLE
Case inconsistency between AllSets.json key and "code" field

### ISSUE THREAD

**Issue by magreenblatt** [mtgjson/mtgjson#193]
The key in the AllSets.json file is upper-case (e.g. "XLN") while the "code" field in the set data is lower-case (e.g. "xln"). Other usages of the code value (like the "printings" field) are upper-case, and in V3 the "code" field was also upper-case. It would be nice if the case could be consistent in all usages.

**Comment by ZeldaZach** [comment]
So we (just) recently changed printings to be lowercase, but I did plan on keeping the keys as upper. I agree consistency is important, so maybe converting everything to uppercase is the right move?

**Comment by magreenblatt** [comment]
All in uppercase sounds good to me :)
