### ISSUE TITLE
Resplitting into stripped and full outputs

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson#197]
With MTGJSONv3, we had "FILE" and "FILE-x" to indicate the two file options. A stripped version, and an extra/bloated one. With my initial release of MTGJSONv4, I went away from this model, opting to give one file with all of the information.

With recent advancements in the software, I am reconsidering splitting the model again.  There are a few fields that can (probably) be safely moved to a separate file that a user can get if they truly need the data, and give all of our other users a break on data downloads.

__

My first thought is to move **foreignData** and the **content from #168** into this bloated version of the file. My reasoning: Most people aren't going to use foreign data. For those who choose to use it, most will work with only a single non-English language. As such, we'd be providing a lot of bulk waste to these users.

I really like the idea of XMage's splitting, albeit with some tuning. This is information _most_ users won't want, but I could see it being helpful somewhere in the pipeline.

In addition to these two thoughts, I am willing to consider moving any and all fields that seem bulky that an end user would _probably_ not directly want if they're looking for a good sum of the data. At the moment, these are the only two fields I would consider moving, but I'd like outside opinions before I go forward with any such "fork" of the files. 

Please feel free to voice your opinion on what we should consider for splitting into two versions of files, and what should field(s) should not be incorporated into the "stripped" version.

**Comment by JayDi85** [comment]
It's can be [GraphQL](https://www.graphql.org/) or API interface to fetch data. With GraphQL developers can selects and query only needed data.

**Comment by ZeldaZach** [comment]
I don't think GraphQL is what I'm looking for in this situation, but it's a thought for the future!

The overall impact and responses I have gotten indicate splitting would be useful. I only plan on moving really heavy hitters to the secondary files (which will have the new file name). I'll see what I come up with and have a PR up soon

**Comment by magreenblatt** [comment]
The stripped version of AllSets.json could also remove the "printings" field, since that value can already be determined from the JSON data if desired.

**Comment by ZeldaZach** [comment]
I could see that as an option too

**Comment by MidnightLightning** [comment]
For the projects that I use MTGJSON data for, I typically end up making a pre-run step where I download the main `AllCards.json` file, loop through it, and prune out the data I know that project won't need, and save it as a separate JSON file that the application uses for all further processing. I think if the main MTGJSON builds created different heavy/medium/light outputs, it might help bootstrap some projects, but odds are you'd never get a perfect blend that would suit everyone.

A GraphQL server is great for handling different sorts of requests from different clients in a centralized manner, but I don't think that's the intent of this project (someone could create a GraphQL front-end for the master `AllCards.json` file, though!). What might be useful for users who don't have the means to create a pre-parsing script is to create a sort of "build server" where users could tick off the properties they want, click "Export", and end up with a tailored JSON file with just the properties they needed? Other projects I've seen that do similar things would be the [Painterly Minecraft texture pack](http://painterlypack.net/customizer.php) and the jQuery Mobile [Download Builder](http://jquerymobile.com/download-builder/).

**Comment by ZeldaZach** [comment]
@MidnightLightning While i do like what the minecraft/jquery programs are doing, I'm not sure if that's the goal of my project in its current state. First, AllCards is poorly documented and I hope to improve upon that file soon. Second, my first thought is to have the "SET.json" files be complete and the compiled outputs will have a small/large version.

I believe @silasary will take a crack at it, and if it goes well I will extend upon it to better serve the users.

**Comment by ZeldaZach** [comment]
I’m gonna back away from this for the time being. We decided to not support the Xmage blob, so this isn’t fully needed now. 

Can come back to it in the future if it becomes an issue.

**Comment by MickHardins** [comment]
I'm fine with the idea of splitting. In the future i would also consider to provide full database splitter per language. For the latter, i'm not sure if it's possible, since i don't know whats the current support to foreign languages
