### ISSUE TITLE
W16 cards not legal in Standard

### ISSUE THREAD

**Issue by bradleyjx** [mtgjson/mtgjson#199]
Guessing the initial update to Gatherer did not have these listed as legal in Standard, but current cards from this set are listed as such.

**Comment by yeurch** [comment]
Yeah, +1 for this.
All the W16 cards should be standard legal, but in `W16.json`, only around half a dozen show as standard, presumably because of the other printings.

**Comment by gwax** [comment]
This appears to have been fixed in a previous rebuild.
