### ISSUE TITLE
Cards missing from Starter 2000 (S00)

### ISSUE THREAD

**Issue by magreenblatt** [mtgjson/mtgjson#200]
#### Description of Bug:
The following cards are missing from the Starter 2000 set data:

['Armored Pegasus', 'Bog Imp', 'Coercion', 'Counterspell', 'Disenchant', 'Drudge Skeletons', 'Flame Spirit', 'Flight', 'Giant Growth', 'Goblin Hero', u"Hero's Resolve", 'Inspiration', 'Llanowar Elves', 'Merfolk of the Pearl Trident', 'Obsianus Golem', 'Orcish Oriflamme', 'Prodigal Sorcerer', 'Python', 'Rod of Ruin', 'Samite Healer', 'Scathe Zombies', 'Shock', 'Soul Net', 'Stone Rain', 'Terror', 'Venerable Monk', 'Wind Drake']

**Comment by ZeldaZach** [comment]
Took a look and this is correct on Gatherer, but incorrect on Scryfall. I can only assume Sf saw different set symbols (The cards you listed have Classic 6th Edition symbol, whereas the other cards don't have a set symbol) and split them up accordingly?

cc: @csuhta

**Comment by csuhta** [comment]
The Starter 2000 box included both 6ED cards and special Starter 2000 cards. Gatherer incorrectly has duplicates of the 6ED cards filed in Starter 2000. 

(This isn’t a case where the cards include the 6ED symbol but are visually different, they’re exactly the same cards. Explorers of Ixalan is another example product like this.)

**Comment by ZeldaZach** [comment]
Appreciate the insight. As such, this is closed as a nofix.

If you come across any other inconsistencies, @magreenblatt , please do feel free to create new tickets :)

**Comment by magreenblatt** [comment]
Thanks for the explanation. Makes sense!
