### ISSUE TITLE
Oracle update

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgjson#201]
There was a very recent Oracle update than changed the wording on many cards. Notable ones are listed in the article, but there is now new templating for creating tokens (using the “create” word).

http://magic.wizards.com/en/articles/archive/feature/eldritch-moon-update-bulletin-oracle-text-2016-07-28

**Comment by ZeldaZach** [comment]
Is this live as of *now* or when the next set comes out?

**Comment by tooomm** [comment]
The first example is on gatherer:
http://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&text=+[%22cast%20spells%20as%20though%20they%20had%20flash%22]

While the create token example is still the same:
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=207883
and there are no changes with the advertised `create token` wording as of now:
http://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&text=+[%22create%20a%20token%22%]

**Comment by gwax** [comment]
This has been fixed by previously committed PRs.
