### ISSUE TITLE
Incorrect key in AllSets.json for PRNA (Ravnica Allegiance Promos)

### ISSUE THREAD

**Issue by magreenblatt** [mtgjson/mtgjson#203]
#### Description of Bug:
The "code" value for "Ravnica Allegiance Promos" is "prna" but the JSON key in AllSets.json is "PRN" (missing the 'A'). The JSON keys for other promo sets seem to be correct ('P' + set code).

**Comment by ZeldaZach** [comment]
RNA/PRNA was accidentally included into the 4.2 build. The set is not complete nor is it ready. This bug shouldn't be a problem in future builds, but I'm going to leave it open to re-confirm later.

**Comment by ZeldaZach** [comment]
Seem to be valid on my local build temporarily. Will re-eval soon. Thanks for all the reports!

**Comment by lfgcampos** [comment]
@ZeldaZach not sure if I should open a ticket for it but... when are you planning to include RNA?
The json doesn't look complete as you stated before: https://mtgjson.com/json/RNA.json

Another question: should we open requests to include new editions? Or do you have a time schedule for it (ex: 1 week prior to the release, etc)?

**Comment by CantyCanadian** [comment]
The spoiler season is done and I seem to have access to a lot of cards from RNA in the JSON. However, as the original issue stated, PRNA is still labeled as PRN, causing some issues when trying to fetch images online. Any news on if that'll be fixed?

**Comment by ZeldaZach** [comment]
Still busted in 4.2.1? Oof I’ll check again :/
