### ISSUE TITLE
Flavor Text is missing New Line characters

### ISSUE THREAD

**Issue by esb** [mtgjson/mtgjson#205]
#### Description of Bug:
The Flavor text is being scraped without keeping the new-line characters. The data is formatted in Gatherer in multiple divs for each line in exactly the same way as the card text box, but a new line is not being added for each div in the same was that it is done for card text.

**Comment by ZeldaZach** [comment]
Can you give a few examples of cards that are "broken" in this situation? So I can better investigate

**Comment by esb** [comment]
From Dragon's Maze, Rakdos Cluestone

"flavorText": "\"Burn. Bleed. Enjoy.\" ÔÇöCluestone inscription",

The entry for this card in Gatherer is formatted with 2 divs which is formatted in 2 lines.

div class="flavortextbox">"Burn. Bleed. Enjoy."</div
div class="flavortextbox">—Cluestone inscription</div

The flavor text in the json file is missing a "\n" between the two lines.

**Comment by ZeldaZach** [comment]
Hmm, our primary data source for flavortext (Scryfall) doesn't seem to have the linebreaks and such within their API nor their website...

A bit curious myself why this is. cc: @csuhta

**Comment by csuhta** [comment]
Scryfall has sourced flavor texts from a lot of places, and while we try to have the correct flavor text, and whitespace it correctly on newer cards, the whitespace in flavor text is not guaranteed to be perfect. Maintaining it at this level of nuance is currently not a good use of our time.

**Comment by ZeldaZach** [comment]
Provided flavor text is accurately spaced on _funny_ cards, as that might matter, I could agree that it's not fully necessary.

@esb If you'd like to submit flavor text corrections, I'm sure SF would appreciate it and I can get it implemented.
