### ISSUE TITLE
Conspiracy and Cogwork cards missing Watermark information

### ISSUE THREAD

**Issue by CrypticRat** [mtgjson/mtgjson#206]
With Conspiracy 2 coming up, I'm looking for a way to filter out the metadraft cards that appeared either on cards with the type Conspiracy or on artifact creatures like Cogwork Librarian. These cards do clearly have a watermark though if the information is being grabbed from Gatherer, Gatherer doesn't list a watermark field for these cards as it does for others.

For reference:
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=97087
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=382216
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=382233

**Comment by CrypticRat** [comment]
The new Conspiracy set is on Gatherer and it's still missing this watermark information for the relevant cards in both sets. :/

If/when this gets around to including Take the Crown, can the watermark information be added manually? It would be extremely helpful for identifying which cards have metadraft abilities or are conspiracies with a simple check.

**Comment by lsmoura** [comment]
Hey!
Next month I'll get around and implement the watermark field. I'll leave this open until then.

**Comment by fenhl** [comment]
The watermark needs to be added to all cards with the card type conspiracy — that's easy — but also to draft-matters cards. I believe a [regex search for `\b[Dd]raft(ed)?\b`](https://mtg.wtf/card?q=o%3A%2F%5Cb%5BDd%5Draft%28ed%29%3F%5Cb%2F) should correctly identify these cards, though I haven't checked for false negatives.

**Comment by ZeldaZach** [comment]
Fixed in V4
