### ISSUE TITLE
Missing Watermarks

### ISSUE THREAD

**Issue by esb** [mtgjson/mtgjson#206]
#### Description of Bug:
Stinkweed Imp (Multiverse ID 370450) from Modern Masters is missing the Golgari watermark.

**Comment by ZeldaZach** [comment]
Good catch! Upstream issue. https://scryfall.com/card/mma/98/stinkweed-imp

cc: @csuhta

**Comment by ZeldaZach** [comment]
More missing:

Greater Mossdog
Life from the Loam
Moldervine Cloak
Electrolyze
Trygon Predator

**Comment by csuhta** [comment]
All fixed upstream
