### ISSUE TITLE
Wrong Rarity for Starter 1999 Goblin Hero

### ISSUE THREAD

**Issue by esb** [mtgjson/mtgjson#207]
#### Description of Bug:

Goblin Hero from Starter 1999 (Multiverse ID 21066) was misprinted with a gold symbol even though it is a Common card. The rarity is incorrectly set to Rare in the JSON file.

https://magic.wizards.com/en/articles/archive/goblin-misprints-2002-10-10

**Comment by ZeldaZach** [comment]
Heh, nice find. Seems to be an upstream thing.

cc: @csuhta

**Comment by csuhta** [comment]
Fixed
