### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by bottleofwater** [mtgjson/mtgjson#207]
The SSL certificate seems to have expired. It still works most of the time (due to cache, I assume), but for example the following like triggers a Cloudflare error instead of a regular 404:

https://mtgjson.com/json/somerandomurl

HTTP access works fine in the meantime.

**Comment by Garbee** [comment]
> Issued On	Monday, June 27, 2016 at 8:00:00 PM
> Expires On	Sunday, January 1, 2017 at 6:59:59 PM

These are the current SSL certificate dates that I am seeing.

Can you please check the SSL certificate itself and provide:

* Issuer
* Issued on date
* Expiry date

**Comment by bottleofwater** [comment]
Hm, it seems to work fine now. Strange. I'm closing this issue, and I'll let you know if I get this error again. Thanks.
