### ISSUE TITLE
Firestorm (Weatherlight) missing punctuation in flavor

### ISSUE THREAD

**Issue by esb** [mtgjson/mtgjson#209]
#### Description of Bug:

Firestorm in Weathlight is missing a ! in the flavor text.

"Glok loved storms " should be "Glok loved storms!"

**Comment by esb** [comment]
Also in Weatherlight, more missing ! marks.

Fervor should have flavor text of

“If your blood doesn’t run hot, I will make it run in the sands!”

**Comment by esb** [comment]
Boiling Blood - "Your father has no horns!\nYour mother wears a bell\nYou drink the milk of goats!"
Vodalian Illusionist - "Torahn gore these shifty fishtails!"
Phantom Wings - "But you said 'when goats fly!'"
Inner Sanctum - "Either way, do not ignore me!"
Benalish Missionary - "I say let him find out for himself—right now!"

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
All fixed upstream

**Comment by ZeldaZach** [comment]
Thanks for all of the reports, @esb Keep up the great work :)
