### ISSUE TITLE
Inconsistent set names

### ISSUE THREAD

**Issue by friscoMad** [mtgjson/mtgjson#209]
I have found some inconsistent set names:
- FTV: Anihilition: Has (2014) after the name
- Commander 2013 is named as "Commander 2013 Edition" while all other Commanders are "Commander 201X"
- Magic 2013 and 2014 are listed as "Magic 201X Core Set" while the rest are just Magic 201X

**Comment by dgant** [comment]
They are, sadly, consistent with Gatherer:

![image](https://cloud.githubusercontent.com/assets/116363/17952214/519ee628-6a36-11e6-9673-4dca166b1013.png)

**Comment by frisco82** [comment]
That was fast! 
In fact I expected that was the cause but maybe it could be provided a new attribute with a more standarized name in those cases.

**Comment by ZeldaZach** [comment]
Addressed via SF data
