### ISSUE TITLE
Wrong Multiverse ID for Nissa, Sage Animist (Origins)

### ISSUE THREAD

**Issue by esb** [mtgjson/mtgjson#210]
#### Description of Bug:

Nissa, Sage Animist from Origins has a Multiverse ID of 398439. It should be 398432.

The ID given actually is for Bellows Lizard.

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
This isn't an upstream issue: https://api.scryfall.com/cards/multiverse/398432?pretty=true

**Comment by ZeldaZach** [comment]
Hmm, weird. I'll look into this on my end further. Thanks!

**Comment by ZeldaZach** [comment]
This was fixed upstream at some point. My local rebuild is correct. Will be live in 4.2.1. Thanks for the ticket!
