### ISSUE TITLE
Glissa, the Traitor in From the Vault: Lore is missing Watermark

### ISSUE THREAD

**Issue by esb** [mtgjson/mtgjson#211]
#### Description of Bug:

Glissa, the Traitor (V16) does not have a watermark field.

It should be 'phyrexian'

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
Fixed upstream

**Comment by ZeldaZach** [comment]
Appreciate the quick fix!
