### ISSUE TITLE
Incorrect Duel Decks set codes

### ISSUE THREAD

**Issue by magreenblatt** [mtgjson/mtgjson#213]
#### Description of Bug:
Comparing Duel Decks set codes between MTGJSON versions 4 and 3:

```
                                               V4    V3
Duel Decks: Elves vs. Goblins                  DD1   EVG
Duel Decks: Jace vs. Chandra                   DD2   DD2
Duel Decks: Divine vs. Demonic                 DDC   DDC
Duel Decks: Garruk vs. Liliana                 DDD   DDD

Duel Decks Anthology: Elves vs. Goblins        EVG   DD3_EVG
Duel Decks Anthology: Jace vs. Chandra         JVC   DD3_JVC
Duel Decks Anthology: Divine vs. Demonic       DVD   DD3_DVD
Duel Decks Anthology: Garruk vs. Liliana       GVL   DD3_GVL
```
I believe the V3 set codes are correct and the V4 set codes are incorrect as follows:

- "Duel Decks: Elves vs. Goblins" should be EVG: https://magic.wizards.com/en/content/duel-decks-elves-vs-goblins:

- "Duel Decks Duel Decks Anthology" is a reprint of previous Duel Decks and should be DD3: https://magic.wizards.com/en/content/duel-decks-duel-decks-anthology. The individual decks are usually referred to as DD3_EVG, DD3_JVC, DD3_DVD and DD3_GVL.

**Comment by ZeldaZach** [comment]
I know that scryfall decided to go away from the gatherer set codes for some sets as they were not helpful. However, maybe they have more information on what happened with the Duel Decks on their end?

cc: @csuhta

**Comment by csuhta** [comment]
`DD3_EVG` and friends are codes that appear only on Gatherer, and it seems to be a hackaround to deal with the fact that WotC re-used `EVG` for two sets.

- Duel Decks: Elves vs. Goblins 's official set code is `EVG`, but it was not printed on the cards (Gatherer is not incorrect here). https://magic.wizards.com/en/content/duel-decks-elves-vs-goblins
- Duel Decks: Jace vs. Chandra's official set code is `DD2`, but it was not printed on the cards (Gatherer is correct here). https://magic.wizards.com/en/content/duel-decks-jace-vs-chandra
- All of the cards from Duel Decks Anthology had `EVG`, `JVC`, `DVD`, `GVL` printed on the cards, but the whole collection was assigned the product code `DD3`, even though the deck pairs are individually numbered and considered distinct sets (maybe, sort of?)

The whole situation is bad. Scryfall is unwilling to use the underscore hack for EVG and unwilling to use duplicate set codes, so we decided to assign Duel Decks: Elves vs. Goblins the code `DD1` and Duel Decks Anthology: Elves vs. Goblins the code `EVG` to match what is printed on the cards and match up to how people tend to sell the cards.

**Comment by ZeldaZach** [comment]
Appreciate the insight, Corey! Given this information, I will ponder on a fix, with a no fix being a valid solution, for the next few days.

**Comment by magreenblatt** [comment]
Corey, thanks for the explanation. Personally, I think it’s better to stick with the Gatherer codes because that’s what other (non-Scryfall-based) MTG data sources are currently using. Inventing new/different codes just makes it harder to map data across sources.

**Comment by ZeldaZach** [comment]
Since one of the goals of v4 is to maintain compatibility with the most popular sources (i.e.Scryfall) as it's simplistic. At the same time, I am more than willing to add a sub-code for the "old" set codes if you would find that helpful. (`v3Code`)

v3 to v4 is an incompatible change, and this just happens to be one of the "broken" components. Let me know what you think of my idea
