### ISSUE TITLE
Cards missing from RQS (Rivals Quick Start Set)

### ISSUE THREAD

**Issue by magreenblatt** [mtgjson/mtgjson#214]
#### Description of Bug:
According to the decklists [1] this set should contain "Scathe Zombies" and "Reverse Damage", but those cards are missing from the MTGJSON data.

[1] https://mtg.gamepedia.com/Rivals_Quick_Start_Set

**Comment by magreenblatt** [comment]
According to [1] all of the cards in RQS are actually standard 4th edition cards. Consequently all RQS card records should probably be removed. See related discussion in issue #215.

**Comment by taw** [comment]
They're not totally same due to different copyright year on copyright line.

**Comment by ZeldaZach** [comment]
I'd like to discuss this, along with #215 via Discord with you, @magreenblatt . Invite's found on the website homepage. Feel free to reach out next week anytime!

**Comment by magreenblatt** [comment]
Zack, what time (and timezone) would be best for you, for Discord discussions?

**Comment by magreenblatt** [comment]
Returning to the previous topic (adding the missing cards). It makes sense to keep the RQS records when they're actually different printings.

**Comment by ZeldaZach** [comment]
@magreenblatt Discord invite: https://discordapp.com/invite/74GUQDE

I'm around most days at various hours, just have to ping me.

---

I feel this ticket is a duplicate of #215 so I'm going to leave discussions of this there.

**Comment by ZeldaZach** [comment]
Fixed in 4.2.1
