### ISSUE TITLE
Differentiate between new and previous printings in sets

### ISSUE THREAD

**Issue by magreenblatt** [mtgjson/mtgjson#215]
In issue #214 I reported some cards missing from RQS (Rivals Quick Start Set). According to [1] all of the cards in RQS are actually standard 4th edition cards. There are other sets, like S00 (Starter 2000), that contain both new (S00) printings and cards from previous (6ED) printings. However, only the S00 printings are currently listed for that set (see issue #200).

I think set data should include all cards that were included in that set (both new and previous printings), and provide a way to identify the cards from previous printings. This could be done by adding a new "fromPrinting" value to the card records that come from a previous printing. Some examples of what this would look like:

- All RQS cards would have an additional "fromPrinting": "4ED" value.
- The missing S00 cards from issue #200 would be added with an additional "fromPrinting": "6ED" value.
- RIX, which includes lands from XLN, would have card records added for those lands with an additional "fromPrinting": "XLN" value.

After making this change the existing "printings" field will need to be reconsidered. Perhaps the "printings" field should only list sets that had new printings of the card. We can add a new "allSets" field that lists all sets that contained the card (both new and existing printings). Or, we could remove "printings" completely from AllSets.json since the value can already be determined from the JSON data if desired.

[1] https://mtg.gamepedia.com/Rivals_Quick_Start_Set

**Comment by magreenblatt** [comment]
Incorrect existing card printing records (like with the current RQS set) may need to be fixed upstream.

The missing cards for mixed-printing sets like S00 can often be determined by comparing to the deck lists at https://github.com/taw/magic-preconstructed-decks, and then choosing the closest existing printing (for example, 6ED is the closest printing that predates S00 for the missing cards). This will also rediscover sets like RQS that are 100% existing printings.

I'm not sure how best to identify lands that were included from previous printings.

**Comment by magreenblatt** [comment]
Comparing the V4.2 data to the deck lists linked above, the sets with missing card records (e.g. likely mixed printings) appear to be [E01, E02, GK1, GNT, S00, W16, W17].

**Comment by magreenblatt** [comment]
An alternate approach to adding card records and the "fromPrinting" value in AllSets.json would be to delete the incorrect card records (e.g. all cards from RQS) and instead rely on the resolution of issue #64 to build mixed printing deck lists. In this case AllSets.json would contain set records but no card records for sets that are 100% existing printings.

**Comment by magreenblatt** [comment]
Challenger Decks [1] are another example where we should have a set record (with code Q01) but no card records (because cards come from the Kaladesh block and Amonkhet block).

[1] https://mtg.gamepedia.com/Challenger_Decks

**Comment by ZeldaZach** [comment]
This is an interesting idea, and I do like it in some regards. Will think about it over the next week or so and see what prototypes I can come up with

**Comment by ZeldaZach** [comment]
So I'm going to leave this open to user interpretation. If someone would like to come along and look into something like this, I wouldn't object :)

**Comment by ZeldaZach** [comment]
Closing in favor of #64
