### ISSUE TITLE
colorIdentity missing

### ISSUE THREAD

**Issue by dgant** [mtgjson/mtgjson#216]
Hello,

There are about 68 cards missing the colorIdentity property on at least one of their printings. Examples:
- Mikaeus, the Lunarch (Innistrad)
- Supreme Verdict (RTR)
- Dryad Militant (RTR)

A mostly-comprehensive list of cards affected by this: http://combodeck.net/Query/card_!colorless?p=[~@VO@CLegal_in_these_Commander_colors@Lc~]

Note that some cards, like Balance, are missing colorIdentity for one of their printings but not all of them.

**Comment by gwax** [comment]
As far as I can tell this has been fixed. Please reopen with additional details if I am incorrect.
