### ISSUE TITLE
Kaladesh and its Inventions have been added to Gatherer.

### ISSUE THREAD

**Issue by AgentConundrum** [mtgjson/mtgjson#219]
Gatherer has been updated with the [Kaladesh](http://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&set=["Kaladesh"]) and [Kaladesh Inventions](http://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&set=+["Kaladesh%20Inventions"]) sets.

(Not sure this post is necessary, but I've seen others link these in the past, so apologies in advance if this is unwanted.)

**Comment by gwax** [comment]
This has been resolved by previously committed PRs.
