### ISSUE TITLE
MultiverseId is missing for RNA/PRW2/PRNA

### ISSUE THREAD

**Issue by lfgcampos** [mtgjson/mtgjson#220]
#### Description of Bug:
`multiverseId` is missing for the new set (RNA, PRW2 and PRNA).
https://mtgjson.com/json/RNA.json
https://mtgjson.com/json/PRW2.json
https://mtgjson.com/json/PRNA.json

**Comment by ZeldaZach** [comment]
Since these sets aren't on Gatherer (yet), there is no such MID. This isn't really a "bug" per say, but when they go on gatherer I will look into a provisional update (4.2.1_1) ?

**Comment by lfgcampos** [comment]
But the set is there: http://gatherer.wizards.com/Pages/Search/Default.aspx?set=[%22Ravnica+Allegiance%22]

**Comment by lebenski** [comment]
Also need this for Cube Tutor please!

**Comment by ZeldaZach** [comment]
RNA went live on gatherer 6 hours after my comment. A rebuild is in progress and will be up today. Thanks for your patience!

**Comment by lebenski** [comment]
Thanks for all your great work!

**Comment by ZeldaZach** [comment]
New files are up, enjoy!

**Comment by lfgcampos** [comment]
@ZeldaZach thank you very much!
`foreignData` will be added later as well?

**Comment by ZeldaZach** [comment]
Expect foreignData in the next release. It takes time to propagate that to our upstream sources.

**Comment by lebenski** [comment]
Hey @ZeldaZach.  Please tell me if i'm being blind or looking in the wrong place but I still don't see the multiverseId in here:

https://mtgjson.com/json/RNA.json

**Comment by lfgcampos** [comment]
@lebenski isn't it a cache issue?
I can see the `multiverseId` here without problems.

And I could download all the images yesterday from gatherer using the `multiverseId`.

**Comment by lebenski** [comment]
Yes it is!  Thanks
