### ISSUE TITLE
switching to capitalized set codes has changed the uuid for all cards

### ISSUE THREAD

**Issue by kellenwhitaker** [mtgjson/mtgjson#221]
#### Description of Bug:
The latest release capitalizes the set code. Since the uuid hash is dependent on the set code, it appears that this has changed all uuid's, breaking compatibility with previous releases.

**Comment by ZeldaZach** [comment]
Hmm, that's a problem. We have two options: Call the "new" UUIDs the standard, or say 4.2.1 has broken UUID's and 4.2.2 will have "fixed" ones.

Since I won't be lower-casing set codes anymore, anywhere, I'm tempted to call this the new standard. What do you think?

**Comment by kellenwhitaker** [comment]
My main concern is that the uuid standard has already changed once. Something like this should stay consistent, I believe, since it's an obvious target for a key in a database. The main issue that recently cropped up during development of my application is when a set needs to be updated, not when it's first populated. So having an evolving uuid standard can definitely present some downstream issues.

Either solution would be easy to implement. Just .lower() the set code before hashing, or just use the new standard.

**Comment by ZeldaZach** [comment]
Based on that, expect this to be the new "standard" going forward. I'll make more notes on fields i'll have to address based on what the UUIDv5 is made of. Appreciate the ticket, and thanks for caring!

**Comment by kellenwhitaker** [comment]
No problem. Will make changes to my application in order to adapt.
