### ISSUE TITLE
Create token oracle changes

### ISSUE THREAD

**Issue by ShawnieBoy** [mtgjson/mtgjson#222]
Sorry to jump in so early, but it looks as though the oracle changes for token generation haven't been caught.

**Comment by tritoch** [comment]
And what would gatherer be without a few errors.  These two cards appear to have been missed (a split and a kami flip):

http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=369041&part=Alive
http://gatherer.wizards.com/Pages/Card/Details.aspx?printed=true&multiverseid=78975

**Comment by gwax** [comment]
This appears to have been fixed in a previous build.
