### ISSUE TITLE
Question on UUID and setcode uppercase

### ISSUE THREAD

**Issue by NikolayXHD** [mtgjson/mtgjson#223]
Since 4.2.1 is released with set codes converted to uppercase, and set code is used to calculate `uuid` 4.2.1 uuids are supposed to be incompatible with previous release (again)

Is it correct or am I missing something?

**Comment by ZeldaZach** [comment]
Re: #221 
You are correct, UUID's unfortunately did change with this release. At this point, I do plan on keeping them consistent as the other fields shouldn't change.

Sorry about that!

**Comment by NikolayXHD** [comment]
Maybe it's worth mentioning in release notes to help other developers be prepared.

**Comment by ZeldaZach** [comment]
Agreed, I'll make that change now. Appreciate the input!!
