### ISSUE TITLE
Gatherer has botched the Æ migration

### ISSUE THREAD

**Issue by csuhta** [mtgjson/mtgjson#224]
Wizards has stopped using the Æ symbol in card names in favor of "Ae", with errata.

http://markrosewater.tumblr.com/post/144471532728/this-is-a-bit-weird-but-i-notice-its-the-aether
http://markrosewater.tumblr.com/post/145462266763/if-youre-not-using-the-ae-ligature-on-cards

Gatherer has messed this up, however, and now has TWO names for some cards if you are not careful when importing: http://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=420593

**Comment by lsmoura** [comment]
Fixed on 6fda83da974eb698dd29b8062f2eea51564509c2
