### ISSUE TITLE
Wrong multiverseId for Gearhulks in MPS

### ISSUE THREAD

**Issue by Palladinium** [mtgjson/mtgjson#225]
The five Gearhulks in Kaladesh Inventions have the multiverseId of the corresponding card from Kaladesh.

The following multiverseIds should change:

Name | Current Id | Correct Id | Number
--------|------|------|------
Combustible Gearhulk | 417685 | 420591 | 4
Verdurous Gearhulk | 417745 | 420592 | 5
Torrential Gearhulk | 417640 | 420589 | 2
Noxious Gearhulk | 417669 | 420590 | 3
Cataclysmic Gearhulk | 417582 | 420588 | 1

**Comment by florentdouine** [comment]
In consequence, the number is wrong too : torrential gearhulk is 67 !

**Comment by lsmoura** [comment]
Multiverse, Number, Artist and Rarity were all wrong. Gatherer's listing on MPS cards display links to KLD Gearhulks. All fixed now.

**Comment by florentdouine** [comment]
great job @lsmoura ! As Always :)
