### ISSUE TITLE
Basic land rarity assigned to "common"

### ISSUE THREAD

**Issue by mildmongrel** [mtgjson/mtgjson#225]
#### MTGJSON Version: 4.X.X
 4.2.1 (also seen in 4.2)

#### Description of Bug:
The rarity for basic lands in MTGJSON 4, at least spot-checking for recent sets like DOM, GRN, RNA is "common".  According to the docs I'd expect "basic".  FWIW, MTGJSON 3 used "Basic Land".  For my use case, using a specific rarity makes it more straightforward to construct booster packs.

**Comment by ZeldaZach** [comment]
The issue is I don't have a good source to determine when a land is a "common" vs a "basic". I'd have to hard code that in, which I could, but it seems weird. The symbol indicates it's a common

**Comment by mildmongrel** [comment]
Makes sense and I can work around it, thanks for taking a look.  If you don't think this will change, you can enhance the documentation for card rarity to remove 'basic'.
