### ISSUE TITLE
TCGPlayer property queries fail for certain cards

### ISSUE THREAD

**Issue by kellenwhitaker** [mtgjson/mtgjson#229]
#### Description of Bug:
TCGPlayer property queries fail for for basic lands, GRN/RNA Guildgates, split cards, and cards having diacritical marks in their names. This means Product Ids are not found for these cards.

Sorry, jumped the gun on the PR. I meant to raise the issue first.

**Comment by ZeldaZach** [comment]
Fixed in c7f8987ca479425631537fec93a4e7b302da9c80
