### ISSUE TITLE
Inconsistent data between printings

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#229]
I've noticed it on Winter Orb, which has completely wrong Oracle text on half the versions, but it affects a bunch of other cards in `AllSets-x.json` too.

Fortunately for others it's mostly Æ, missing rulings, wrong reminder text etc., but Winter Orb is horribly wrong. It would still be a good idea to have some validation step that non-printing-specific fields are consistent between printings.

Below is full list of inconsistent cards:

Key rulings of card Fog is inconsistent between versions
- [{"date"=>"2009-10-01", "text"=>"Fog has no effect on damage that’s already been dealt."}] - be un ced cedi rv 4e mr 5e 6e bd 7e m10 arc m11 me4 m12 m13 m14
- nil - ema

Key text of card Force of Nature is inconsistent between versions
- "Trample (This creature can deal excess combat damage to defending player or planeswalker while attacking.)\nAt the beginning of your upkeep, Force of Nature deals 8 damage to you unless you pay {G}{G}{G}{G}." - be un ced cedi rv 4e 5e bd 9e me4
- "Trample (If this creature would assign enough damage to its blockers to destroy them, you may have it assign the rest of its damage to defending player or planeswalker.)\nAt the beginning of your upkeep, Force of Nature deals 8 damage to you unless you pay {G}{G}{G}{G}." - rep

Key text of card Winter Orb is inconsistent between versions
- "Players can't untap more than one land during their untap steps." - be un rv 4e 5e med
- "As long as Winter Orb is untapped, players can't untap more than one land during their untap steps." - ced cedi ema

Key rulings of card Karmic Guide is inconsistent between versions
- [{"date"=>"2008-04-01", "text"=>"A “creature card” is any card with the type Creature, even if it has other types such as Artifact, Enchantment, or Land. Older cards of type Summon are also Creature cards."}] - ul c13 vma
- nil - ema

Key text of card Pariah is inconsistent between versions
- "Enchant creature (Target a creature as you cast this. This card enters the battlefield attached to that creature.)\nAll damage that would be dealt to you is dealt to enchanted creature instead." - 7e 10e
- "Enchant creature\nAll damage that would be dealt to you is dealt to enchanted creature instead." - cn2

Key text of card Fiery Temper is inconsistent between versions
- "Fiery Temper deals 3 damage to target creature or player.\nMadness {R} (If you discard this card, you may cast it for its madness cost instead of putting it into your graveyard.)" - grc
- "Fiery Temper deals 3 damage to target creature or player.\nMadness {R} (If you discard this card, discard it into exile. When you do, cast it for its madness cost or put it into your graveyard.)" - tsts soi

Key text of card Molimo, Maro-Sorcerer is inconsistent between versions
- "Trample (This creature can deal excess combat damage to defending player or planeswalker while attacking.)\nMolimo, Maro-Sorcerer's power and toughness are each equal to the number of lands you control." - 10e arc
- "Trample (If this creature would assign enough damage to its blockers to destroy them, you may have it assign the rest of its damage to defending player or planeswalker.)\nMolimo, Maro-Sorcerer's power and toughness are each equal to the number of lands you control." - dpa

Key rulings of card Ghitu Encampment is inconsistent between versions
- [{"date"=>"2008-08-01", "text"=>"A noncreature permanent that turns into a creature can attack, and its {T} abilities can be activated, only if its controller has continuously controlled that permanent since the beginning of his or her most recent turn. It doesn't matter how long the permanent has been a creature."}, {"date"=>"2009-10-01", "text"=>"Activating the ability that turns it into a creature while it's already a creature will override any effects that set its power and/or toughness to a specific number. However, any effect that raises or lowers power and/or toughness (such as the effect created by Giant Growth, Glorious Anthem, or a +1/+1 counter) will continue to apply."}] - 10e ddn
- [{"date"=>"2008-08-01", "text"=>"A noncreature permanent that turns into a creature can attack, and its {T} abilities can be activated, only if its controller has continuously controlled that permanent since the beginning of his or her most recent turn. It doesn’t matter how long the permanent has been a creature."}, {"date"=>"2009-10-01", "text"=>"Activating the ability that turns it into a creature while it’s already a creature will override any effects that set its power and/or toughness to a specific number. However, any effect that raises or lowers power and/or toughness (such as the effect created by Giant Growth, Glorious Anthem, or a +1/+1 counter) will continue to apply."}] - pd2

Key rulings of card Rise from the Grave is inconsistent between versions
- [{"date"=>"2009-10-01", "text"=>"Rise from the Grave doesn’t overwrite any previous colors or types. Rather, it adds another color and another subtype."}, {"date"=>"2009-10-01", "text"=>"If the targeted creature is normally colorless, it will simply become black. It won’t be both black and colorless."}, {"date"=>"2009-10-01", "text"=>"A later effect that changes the affected creature’s colors will overwrite that part of Rise from the Grave effect; the creature will be just the new color. The same is true about an effect that changes the affected creature’s types or subtypes."}, {"date"=>"2009-10-01", "text"=>"A “creature card” is any card with the type creature, even if it has other types such as artifact, enchantment, or land. Older cards of type summon are also creature cards."}] - m10 gvl m11 cmd m13 ddagvl c15
- [{"date"=>"2009-10-01", "text"=>"Rise from the Grave doesn’t overwrite any previous colors or types. Rather, it adds another color and another subtype."}, {"date"=>"2009-10-01", "text"=>"If the targeted creature is normally colorless, it will simply become black. It won’t be both black and colorless."}, {"date"=>"2009-10-01", "text"=>"A later effect that changes the affected creature’s colors will overwrite that part of Rise from the Grave effect; the creature will be just the new color. The same is true about an effect that changes the affected creature’s types or subtypes."}, {"date"=>"2009-10-01", "text"=>"A “creature card” is any card with the type creature, even if it has other types such as artifact, enchantment, or land. Older cards of type summon are also creature cards."}, {"date"=>"2016-07-13", "text"=>"If the targeted creature card is normally colorless, it will simply become black. It won’t be both black and colorless."}] - emn

Key text of card Taurean Mauler is inconsistent between versions
- "Changeling (This card is every creature type at all times.)\nWhenever an opponent casts a spell, you may put a +1/+1 counter on Taurean Mauler." - pch
- "Changeling (This card is every creature type.)\nWhenever an opponent casts a spell, you may put a +1/+1 counter on Taurean Mauler." - arc c15

Key text of card Duskdale Wurm is inconsistent between versions
- "Trample (If this creature would assign enough damage to its blockers to destroy them, you may have it assign the rest of its damage to defending player or planeswalker.)" - dpa
- "Trample (This creature can deal excess combat damage to defending player or planeswalker while attacking.)" - m11 m13

Key text of card Chameleon Colossus is inconsistent between versions
- "Changeling (This card is every creature type.)\nProtection from black\n{2}{G}{G}: Chameleon Colossus gets +X/+X until end of turn, where X is its power." - arc c15
- "Changeling (This card is every creature type at all times.)\nProtection from black\n{2}{G}{G}: Chameleon Colossus gets +X/+X until end of turn, where X is its power." - v13

Key text of card Khalni Garden is inconsistent between versions
- "Khalni Garden enters the battlefield tapped.\nWhen Khalni Garden enters the battlefield, put a 0/1 green Plant creature token onto the battlefield.\n{T}: Add {G} to your mana pool." - arc pc2 c13
- "Khalni Garden enters the battlefield tapped.\nWhen Khalni Garden enters the battlefield, create a 0/1 green Plant creature token.\n{T}: Add {G} to your mana pool." - ddr

Key text of card Æther Vial is inconsistent between versions
- "At the beginning of your upkeep, you may put a charge counter on Æther Vial.\n{T}: You may put a creature card with converted mana cost equal to the number of charge counters on Æther Vial from your hand onto the battlefield." - fvr mma
- "At the beginning of your upkeep, you may put a charge counter on Aether Vial.\n{T}: You may put a creature card with converted mana cost equal to the number of charge counters on Aether Vial from your hand onto the battlefield." - mps

Key rulings of card Sword of Feast and Famine is inconsistent between versions
- [{"date"=>"2011-06-01", "text"=>"You'll untap all lands you control even if the player doesn't discard a card."}] - mbs md1
- [{"date"=>"2011-06-01", "text"=>"You’ll untap all lands you control even if the player doesn’t discard a card."}] - mps

Key rulings of card War Priest of Thune is inconsistent between versions
- [{"date"=>"2010-08-15", "text"=>"Unlike Manic Vandal’s ability, War Priest of Thune’s ability is not mandatory. If you’re the only player who controls an enchantment, you must target one of them, but you don’t have to destroy it."}] - m13
- nil - ema

Key text of card Prey Upon is inconsistent between versions
- "Target creature you control fights target creature you don't control. (Each deals damage equal to its power to the other.)" - m13 ddl cn2
- "Target creature you control fights target creature you don't control." - emn

Key text of card Walker of the Grove is inconsistent between versions
- "When Walker of the Grove leaves the battlefield, put a 4/4 green Elemental creature token onto the battlefield.\nEvoke {4}{G} (You may cast this spell for its evoke cost. If you do, it's sacrificed when it enters the battlefield.)" - mma c13
- "When Walker of the Grove leaves the battlefield, create a 4/4 green Elemental creature token.\nEvoke {4}{G} (You may cast this spell for its evoke cost. If you do, it's sacrificed when it enters the battlefield.)" - ddr

Key rulings of card Crater Hellion is inconsistent between versions
- [{"date"=>"2004-10-04", "text"=>"The ability does 4 damage to every creature on the battlefield other than Crater Hellion."}] - ddl c13 vma
- nil - ema

Key text of card Jetting Glasskite is inconsistent between versions
- "Flying\nWhenever Jetting Glasskite becomes the target of a spell or ability for the first time in a turn, counter that spell or ability." - cns
- "Flying\nWhenever Jetting Glasskite becomes the target of a spell or ability for the first time each turn, counter that spell or ability." - ema

Key rulings of card Shoreline Ranger is inconsistent between versions
- [{"date"=>"2009-02-01", "text"=>"Unlike the normal cycling ability, Islandcycling doesn't allow you to draw a card. Instead, it lets you search your library for an Island card. After you find an Island card in your library, you reveal it, put it into your hand, then shuffle your library."}, {"date"=>"2009-02-01", "text"=>"Islandcycling is a form of cycling. Any ability that triggers on a card being cycled also triggers on Islandcycling this card. Any ability that stops a cycling ability from being activated also stops Islandcycling from being activated."}, {"date"=>"2009-02-01", "text"=>"Islandcycling is an activated ability. Effects that interact with activated abilities (such as Stifle or Rings of Brighthearth) will interact with Islandcycling. Effects that interact with spells (such as Remove Soul or Faerie Tauntings) will not."}, {"date"=>"2009-02-01", "text"=>"You can choose to find any card with the Island land type, including nonbasic lands. You can also choose not to find a card, even if there is an Island card in your library."}] - cns
- nil - ema

Key rulings of card Unhallowed Pact is inconsistent between versions
- [{"date"=>"2012-05-01", "text"=>"The card will return to the battlefield under your control only if it's still in the graveyard when Unhallowed Pact's ability resolves. If it's not (perhaps because an ability like undying has already returned it to the battlefield), nothing happens."}, {"date"=>"2012-05-01", "text"=>"If Unhallowed Pact is enchanting a token creature, that creature can't return to the battlefield."}] - cns
- [{"date"=>"2012-05-01", "text"=>"The card will return to the battlefield under your control only if it’s still in the graveyard when Unhallowed Pact’s ability resolves. If it’s not (perhaps because an ability like undying has already returned it to the battlefield), nothing happens."}, {"date"=>"2012-05-01", "text"=>"If Unhallowed Pact is enchanting a token creature, that creature can’t return to the battlefield."}] - ddr

Key rulings of card Hunt the Weak is inconsistent between versions
- [{"date"=>"2014-07-18", "text"=>"If either target is an illegal target when Hunt the Weak tries to resolve, neither creature will deal or be dealt damage."}, {"date"=>"2014-07-18", "text"=>"If the creature you control is an illegal target when Hunt the Weak tries to resolve, you won’t put a +1/+1 counter on it. If that creature is a legal target but the creature you don’t control isn’t, you’ll still put the counter on the creature you control."}, {"date"=>"2014-11-24", "text"=>"You can’t cast Hunt the Weak unless you choose both a creature you control and a creature you don’t control as targets."}, {"date"=>"2014-11-24", "text"=>"If either target is an illegal target as Hunt the Weak tries to resolve, neither creature will deal or be dealt damage."}, {"date"=>"2014-11-24", "text"=>"If the creature you control is an illegal target as Hunt the Weak tries to resolve, you won’t put a +1/+1 counter on it. If that creature is a legal target but the creature you don’t control isn’t, you’ll still put the counter on the creature you control."}] - m15 frf
- [{"date"=>"2014-11-24", "text"=>"You can’t cast Hunt the Weak unless you choose both a creature you control and a creature you don’t control as targets."}, {"date"=>"2014-11-24", "text"=>"If either target is an illegal target as Hunt the Weak tries to resolve, neither creature will deal or be dealt damage."}, {"date"=>"2014-11-24", "text"=>"If the creature you control is an illegal target as Hunt the Weak tries to resolve, you won’t put a +1/+1 counter on it. If that creature is a legal target but the creature you don’t control isn’t, you’ll still put the counter on the creature you control."}] - kld

Key text of card Priest of the Blood Rite is inconsistent between versions
- "When Priest of the Blood Rite enters the battlefield, put a 5/5 black Demon creature token with flying onto the battlefield.\nAt the beginning of your upkeep, you lose 2 life." - ori
- "When Priest of the Blood Rite enters the battlefield, create a 5/5 black Demon creature token with flying.\nAt the beginning of your upkeep, you lose 2 life." - ddr

Key text of card Affa Guard Hound is inconsistent between versions
- "Flash\nWhen Affa Guard Hound enters the battlefield, target creature gets +0/+3 until end of turn." - ddp
- "Flash (You may cast this spell any time you could cast an instant.)\nWhen Affa Guard Hound enters the battlefield, target creature gets +0/+3 until end of turn." - cn2

Key rulings of card Monk Idealist is inconsistent between versions
- [{"date"=>"2004-10-04", "text"=>"You can cast this if there are no enchantments in your graveyard. The enters the battlefield ability just doesn’t do anything."}] - c15
- nil - ema

**Comment by dgant** [comment]
Just ran into confusion due to Winter Orb's text being out of date.

**Comment by ZeldaZach** [comment]
Addressed in V4 with consistent data from SF
