### ISSUE TITLE
Unstable missing tokens 

### ISSUE THREAD

**Issue by excention** [mtgjson/mtgjson#230]
#### Description of Bug:
Unstable Tokens are missing. You will notice that there are gaps in the token numbers. Token #1,3,6,8,9,11,13,14,17,18. Not sure if the issue goes beyond this set.

**Comment by ZeldaZach** [comment]
Addressed in a prior push to master. There are now 30 entries into the tokens list for UST (20 fronts, 10 backs). Just wait for 4.2.2 or build yourself if you need the tokens asap :)

I've attached my build of UST for you to use
[UST.json.txt](https://github.com/mtgjson/mtgjson/files/2792717/UST.json.txt)
