### ISSUE TITLE
Prerelease Foil Promos?

### ISSUE THREAD

**Issue by kforte318** [mtgjson/mtgjson#230]
I noticed that the prerelease foil promos (the ones with the gold date on them) haven't been added for the recent sets. Will they be added in the future? Is there a reason they aren't part of the document? It appears as though prerelease cards from other sets are present so I was confused.

**Comment by silasary** [comment]
Older sets had a fixed pre-release promo.
Newer sets are just a randomly assigned rare or mythic from the set.

**Comment by ZeldaZach** [comment]
SF has pre-release promo sets for newer sets... I think that's good enough imo (V4)
