### ISSUE TITLE
Variation of Piety (Arabian Nights) with mid=977 missing

### ISSUE THREAD

**Issue by magreenblatt** [mtgjson/mtgjson#231]
#### Description of Bug:
Gatherer lists 2 versions of Piety [1] with multiverse IDs 977 and 978. The 977 variation is missing from AllSets.json in version 4.2.1. Both variations exist in version 4.2 and earlier.

[1] http://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=978

**Comment by ZeldaZach** [comment]
So several cards from Arabian Nights have two printings: A light version, and a dark version. They're honestly the same card, and seem interchangeable in the packs so I'm not sure if we want to support them...

**Comment by ZeldaZach** [comment]
https://api.scryfall.com/cards/search?q=is%3Avariation contains the 41 cards with a variation. We can consider what to do from here

**Comment by magreenblatt** [comment]
Thanks for the list. My primary concern with skipping these records is that they have unique multiverse IDs. Other sources that refer to cards by multiverse ID may fail to match if these records are excluded.

If you don't like the idea of variations having distinct card records perhaps we could add an attribute (like "multiverseIdVariations") that lists the alternate multiverse ID value(s) on the single existing card record?

**Comment by ZeldaZach** [comment]
That could be an idea. Would accept a PR for that. Feel free to discuss on Discord

**Comment by excention** [comment]
Variations of the cards are important from a collection standpoint. Even though the light and dark versions are just the circle number it's not much different from alt artwork like in fallen empires and such in my opinion.

**Comment by ZeldaZach** [comment]
Fair enough, so we'll have to look at how to address this correctly. I don't want multiple copies within the initial set honestly, as for example: 5 copies of tamiyo's journal makes no real sense.

**Comment by magreenblatt** [comment]
Thanks for the fix :)
