### ISSUE TITLE
Colors Field Missing from Colorless Cards in AllCards

### ISSUE THREAD

**Issue by Donglecow** [mtgjson/mtgjson#231]
Colorless cards such as artifacts and lands don't have the colors field in the AllCards.json file.

This can be programatically worked around but it may be worth adding this field in to say "colors":["colorless"].

**Comment by tritoch** [comment]
https://github.com/mtgjson/mtgjson/blob/master/web/documentation.pug#L96

**Comment by csuhta** [comment]
["colorless" is not a color](http://magiccards.info/rule/105-colors.html#rule-105-4). If this field were present, it would be an empty array. But the policy tritoch linked states that the whole key will be missing instead.

**Comment by Donglecow** [comment]
Thanks for the responses, and for the documentation link (which I admit I should've read, sorry), however I still think that it would be better for consistency to have the field, even if it was empty for the sake of consistency. Programatically, I could have done a check for "colors":[], for example, rather than having to catch an exception.

Nevertheless, if this was intended and not a mistake then that doesn't really matter!

Thanks for the replies again.

**Comment by fenhl** [comment]
This seems like a non-issue, given the documentation @tritoch quoted.
