### ISSUE TITLE
Splitted cards have wrong cmc

### ISSUE THREAD

**Issue by carlol** [mtgjson/mtgjson#232]
#### Description of Bug:

Hi,
thank you for your hard work.

I found this error looking at Fire//Ice spell (see below for the json objects).

{
                "layout": "split",
                "name": "Ice",
                "names": [
                    "Fire",
                    "Ice"
                ],
                "manaCost": "{1}{U}",
                "convertedManaCost": 4,
                "colors": [
                    "U"
                ],
                "type": "Instant",
                "supertypes": [],
                "subtypes": [],
                "types": [
                    "Instant"
                ],
                "rarity": "common",
                "text": "Tap target permanent.\nDraw a card.",
                "artist": "Dan Scott",
                "number": "225",
                "multiverseId": 456821,
                "borderColor": "black",
                "hand": 0,
                "life": 0,
                "legalities": {
                    "1v1": "Legal",
                    "commander": "Legal",
                    "duel": "Legal",
                    "legacy": "Legal",
                    "pauper": "Legal",
                    "vintage": "Legal"
                },
                "rulings": [
                    {
                        "date": "2018-12-07",
                        "text": "You divide the damage as you cast Fire, not as it resolves. Each target must be assigned at least 1 damage. In other words, as you cast Fire, you choose whether to have it deal 2 damage to a single target, or deal 1 damage to each of two targets."
                    },
                    {
                        "date": "2018-12-07",
                        "text": "If Fire targets two creatures and one becomes an illegal target, the remaining target is dealt 1 damage, not 2."
                    },
                    {
                        "date": "2018-12-07",
                        "text": "If the target permanent becomes an illegal target for Ice, the spell doesn’t resolve. You don’t draw a card."
                    }
                ],
                "foreignData": [
                    {
                        "language": "Japanese",
                        "name": "Ice"
                    }
                ]
            },
            {
                "layout": "split",
                "name": "Fire",
                "names": [
                    "Fire",
                    "Ice"
                ],
                "manaCost": "{1}{R}",
                "convertedManaCost": 4,
                "colors": [
                    "R"
                ],
                "type": "Instant",
                "supertypes": [],
                "subtypes": [],
                "types": [
                    "Instant"
                ],
                "rarity": "common",
                "text": "Fire deals 2 damage divided as you choose among one or two targets.",
                "artist": "Dan Scott",
                "number": "225",
                "multiverseId": 456821,
                "borderColor": "black",
                "hand": 0,
                "life": 0,
                "legalities": {
                    "1v1": "Legal",
                    "commander": "Legal",
                    "duel": "Legal",
                    "legacy": "Legal",
                    "pauper": "Legal",
                    "vintage": "Legal"
                },
                "rulings": [
                    {
                        "date": "2018-12-07",
                        "text": "You divide the damage as you cast Fire, not as it resolves. Each target must be assigned at least 1 damage. In other words, as you cast Fire, you choose whether to have it deal 2 damage to a single target, or deal 1 damage to each of two targets."
                    },
                    {
                        "date": "2018-12-07",
                        "text": "If Fire targets two creatures and one becomes an illegal target, the remaining target is dealt 1 damage, not 2."
                    },
                    {
                        "date": "2018-12-07",
                        "text": "If the target permanent becomes an illegal target for Ice, the spell doesn’t resolve. You don’t draw a card."
                    }
                ],
                "foreignData": [
                    {
                        "language": "Japanese",
                        "name": "Fire"
                    }
                ]
            }

Best regards,

CL

**Comment by silasary** [comment]
This is correct.  The CMC of Fire // Ice is 4. 

(This is a change from the pre-2017 [Amonkhet] rules, where each side had its own CMC)

**Comment by ZeldaZach** [comment]
Hey @carlol the CMC are correct on these cards. There _should_ be a field called `faceConvertedManaCost` that identifies the cost on the face of the card.

<img width="366" alt="screenshot 2019-01-24 11 46 04" src="https://user-images.githubusercontent.com/7460172/51693831-ab0ca480-1fcd-11e9-997c-323dbf73e58c.png">

Hope this helps!!
