### ISSUE TITLE
Add caching of network data (Gatherer, Wizards)

### ISSUE THREAD

**Issue by magreenblatt** [mtgjson/mtgjson#236]
Running an MTGJSON build currently takes a long time (2.5 hours). A lot of that time is spent downloading network resources that could be cached. We should do that (and have a command-line flag for clearing the cache when desired).

**Comment by ZeldaZach** [comment]
My concern is there are sometimes updates to resources that are not known (like SF updates a card's oracle text to be correct) There are also volatile fields on SF so a hash check of the file wouldn't work necessarily. Have to be creative.

Gatherer resources can and should be cached, as those should never change (I use them only for printed text/type, so once is good)

**Comment by magreenblatt** [comment]
I was thinking mostly about caching the scraped websites, but even caching Scryfall data for 24 hours as recommended in [1] could be an improvement from a developer standpoint.

[1] https://scryfall.com/docs/api

**Comment by ZeldaZach** [comment]
Considering I (usually) only build once every few weeks, it might not be necessary. But sure, helps with local testing :)

**Comment by kellenwhitaker** [comment]
I would think caching the Gatherer resources would cut down on compile times (and testing times) substantially. Was going to suggest adding more concurrency, but since the Gatherer stuff is static, I don't think there's a need. Fetching the Gatherer pages takes forever.

**Comment by ZeldaZach** [comment]
You make a good point @kellenwhitaker as we only need to update our gatherer sources once every few weeks, so we can cache them for longer

**Comment by ZeldaZach** [comment]
Any further thoughts on this @magreenblatt

**Comment by ZeldaZach** [comment]
bump @magreenblatt

**Comment by magreenblatt** [comment]
Sorry, I won’t have time to work on this soon. Feel free to reassign or close.

**Comment by MickHardins** [comment]
If this is not urgent, i can take a look at it.

**Comment by ZeldaZach** [comment]
Not urgent, but something that would be nice to have. It has no impact on data, just time.

**Comment by MickHardins** [comment]
PR #282 should have this feature implemented :)
