### ISSUE TITLE
Card: Easy access to latest printing

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgjson#237]
Use case: filter out duplicates by showing latest printing

Currently, when looking for a card or group of cards, all of the printings are returned in alphabetical order. This leads to need to call on sets to parse each set to get the release date and reduce to the most current.

Possible approaches:

1. Data point in the card itself for latest printing that could return an array of the set code and set name respectively.

2. Printings array is return in release order, ascending or descending, so long as it's documented for future users.

**Comment by ZeldaZach** [comment]
Outside of the scope of MTGJSON, but I'm sure MTG.IO will look into this :)
