### ISSUE TITLE
Wrong date

### ISSUE THREAD

**Issue by TriangularCube** [mtgjson/mtgjson#239]
#### Description of Bug:
In version.json for 4.2.1, date is set to 2018. Pretty sure this is an oversight as it appears correctly at the top of the website.

**Comment by ZeldaZach** [comment]
I'm mid-building 4.2.2 and it has the wrong date. I'll `sed` it before uploading. Thanks for the report!!

**Comment by ZeldaZach** [comment]
Fixed 4.2.2 :)
