### ISSUE TITLE
Include future sets in data

### ISSUE THREAD

**Issue by silasary** [mtgjson/mtgjson#239]
It would be useful to include the basic info about upcoming sets  (Name, Code, Release Date, Type, and Block)

Since the introduction of Announcement days, this information is known well in advance, and it would be useful to have that included in AllSets.json

**Comment by dgant** [comment]
WhatsInStandard has an API that might help! https://github.com/glacials/whatsinstandard

**Comment by dgant** [comment]
This would be a nice feature to have, though. I manually update ComboDeck with upcoming set information as it is.

**Comment by Psithief** [comment]
Haha, yes. Imagine having code that knows when to start looking for set updates.

**Comment by ZeldaZach** [comment]
Not sure what to do this with for now... Feel free to re-create in V4 if needed :)
