### ISSUE TITLE
AllCards 'Un' set field

### ISSUE THREAD

**Issue by dev-id** [mtgjson/mtgjson#241]
AllCards should carry a field designating a card as being a card from an 'Un' set, that is, Unhinged or Unglued.  Currently there is no such designation, so if you want to exclude these cards, you need to run through AllSets.

**Comment by silasary** [comment]
There should be a Border: Silver property?

**Comment by tritoch** [comment]
I think we should avoid using `border` because it already is a field in AllSets.json and some cards do not have a static border type (both white and black border printings)

**Comment by tritoch** [comment]
`un` is also incorrect, that would exclude things from `pHHO` like `Fruitcake Elemental` `pCEL` like `Proposal` 

https://scryfall.com/search?q=%28%2B%2Be%3Apcel+OR+%2B%2Be%3Ahho%29

**Comment by fenhl** [comment]
mtg.wtf has an `is:funny` filter which does exactly this. For example, [here are `is:funny` cards except those from UGL/UNH](https://mtg.wtf/card?q=is%3Afunny+-e%3AUGL+-e%3AUNH). The search engine [derives this filter](https://github.com/taw/magic-search-engine/blob/master/indexer/lib/indexer.rb#L148-L153) from the set code. We could do the same to add a `"funny": true` field to the card.

**Comment by ZeldaZach** [comment]
Can you propose a better name then "funny"?

**Comment by fenhl** [comment]
`"un"` or `"uncard"` perhaps?

**Comment by silasary** [comment]
See above [comment](https://github.com/mtgjson/mtgjson/issues/241#issuecomment-276110616) on why `un` isn't great for this.

**Comment by KingSupernova31** [comment]
No longer needed in v4 if I'm not mistaken.

**Comment by ZeldaZach** [comment]
We went with the border option from what i recall
