### ISSUE TITLE
Foreign names generation does not check card 'number' and duplicates entries

### ISSUE THREAD

**Issue by Psykopear** [mtgjson/mtgjson#241]
Hi, first of all thank for your work with this project. 
While porting an application to version 4, I noticed a possible bug in the generation of `foreignData`.

#### Description of Bug:
In sets where there are cards with different `number`, for example `Plains` cards in `C18` set, the `foreignData` field of each card contains all the `foreignData` of cards with the same `multiverseId` and different `number`.

So for example, generating the `C18` set, if you see the card with data
```json
            "multiverseId": 451248,
            "name": "Plains",
            "number": "293",
```

you can see its `foreignData` field contains multiple entries for each language, for example `Italian`:

```json
                {
                    "language": "Italian",
                    "multiverseId": 452242,
                    "name": "Pianura",
                    "type": "Terra Base — Pianura"
                },
                [...]
                {
                    "language": "Italian",
                    "multiverseId": 452241,
                    "name": "Pianura",
                    "type": "Terra Base — Pianura"
                },
                [...]
                {
                    "language": "Italian",
                    "multiverseId": 452240,
                    "name": "Pianura",
                    "type": "Terra Base — Pianura"
                },
```

This can be fixed by passing `card['number']` to `parse_foreign` function inside `provider/scryfall.py`. 
With this information, the check in line 212 could go from:
```python
if set_name != foreign_card["set"] or foreign_card["lang"] == "en":
    continue
```
to
```python
if (set_name != foreign_card["set"]
    or card['number'] != foreign_card['collector_number']
    or foreign_card["lang"] == "en"):
    continue
```

If you confirm that this is a bug, I can open a PR with the fix.

edit: I just noticed there were some new commits today, but apparently the problem is still present

**Comment by ZeldaZach** [comment]
Hey @Psykopear thanks for bringing this issue to my attention! If you'd like to open a PR here, I'd be glad to review and possibly merge it in :)

**Comment by Psykopear** [comment]
PR opened
