### ISSUE TITLE
upgrade guide for v3 to v4?

### ISSUE THREAD

**Issue by jordanbrauer** [mtgjson/mtgjson#242]
Hi there, 

First of all, thanks a tonne in advance for this library! 

I am using it (v3 specifically) to make an app & had to do a lot of manual data normalization to data in the JSON files in the import mechanism I have made. It seems that v4 has updated fields from v3, and am unable to find an upgrade guide in your docs. Does this exist, or is it something that needs to added? 

Thanks again!

---

P.S. is there an archive of latest v3 JSON files anywhere?

**Comment by ZeldaZach** [comment]
Hey @jordanbrauer and welcome to MTGJSONv4! The "upgrade guide" is based on our changelog, which you can view at https://mtgjson.com/changelog. If you scroll to the bottom, you can follow all changes we've made over time. Hopefully this gives you enough to make the changes necessary for your project!

If you find any changes not well documented, please do let us know so we can correct them for others!

Finally, if you'd like your project listed on our about us page https://mtgjson.com/about we'd love to have you :)

**Comment by jordanbrauer** [comment]
Ah, okay! I figured that the changelog would be the next best spot to check, but wanted to be sure first. At a quick glance, it _should_ be enough information combined with my test errors, to make the changes. If not, I will for sure let you know!

I may just keep all the card data I have as is, and attempt to support both v3 & v4 as import sources. Hopefully this won't be too hard with the changelog 🙂!

> if you'd like your project listed on our about us page

That would be awesome! I will for sure reach out when I have an MVP/beta available (or maybe at least a beta-signup with an "about" section on the tool, closer to that time).

**Comment by ZeldaZach** [comment]
Can't wait to see what you're working on :)
