### ISSUE TITLE
Legalities Missing from CN2 Cards

### ISSUE THREAD

**Issue by minouris** [mtgjson/mtgjson#242]
The legalities are missing from card data for CN2. Cards in this set should be legal for Vintage, Legacy and
Commander, unless otherwise indicated.

![cn2_legality_json](https://cloud.githubusercontent.com/assets/16748789/19421633/31e2649e-9462-11e6-84f0-33c7e00bf4d5.png)
![cns_legality_gatherer](https://cloud.githubusercontent.com/assets/16748789/19421632/31dfc6d0-9462-11e6-9ff4-4f0cca4ee122.png)

**Comment by gwax** [comment]
This has been fixed by previously committed PRs.
