### ISSUE TITLE
foreignData multiverseId for double sided card backs wrong

### ISSUE THREAD

**Issue by robertjanetzko** [mtgjson/mtgjson#243]
#### Description of Bug:
front and back sides of double sided cards have the same multiverseId for all foreignDatas
(it seems scryfall does not provide this data as it lists only one multiverseId on foreign printings for double sided cards)

Gatherer shows both images with different multiverse ids (410951, 410952)
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=410951
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=410952

Front:
```javascript
                "foreignData": [
                    {
                        "language": "German",
                        "multiverseId": 410951,
                        "name": "Anwerber der Dämmerwache",
                        "text": "{2}{G}: Schaue dir die obersten drei Karten deiner Bibliothek an. Du kannst davon eine Kreaturenkarte offen vorzeigen und sie auf deine Hand nehmen. Lege den Rest in beliebiger Reihenfolge unter deine Bibliothek.\nZu Beginn jedes Versorgungssegments und falls im letzten Zug keine Zaubersprüche gewirkt wurden, transformiere den Anwerber der Dämmerwache.",
                        "type": "Kreatur — Mensch, Krieger, Werwolf"
                    },
                    {
                        "language": "Spanish",
                        "multiverseId": 413261,
                        "name": "Reclutador de Vigilaponiente",
                        "text": "{2}{G}:Mira las primeras tres cartas de tu biblioteca. Puedes mostrar una carta de criatura que se encuentre entre ellas y ponerla en tu mano. Pon el resto en el fondo de tu biblioteca en cualquier orden.\nAl comienzo de cada mantenimiento, si no se lanzaron hechizos en el último turno, transforma al Reclutador de Vigilaponiente.",
                        "type": "Criatura — Guerrero licántropo humano"
                    },
```
Back:
```javascript
                "foreignData": [
                    {
                        "language": "German",
                        "multiverseId": 410951,
                        "name": "Heuler der Krallenhorde",
                        "text": "Kreaturenzauber, die du wirkst, kosten beim Wirken {1} weniger.\nZu Beginn jedes Versorgungssegments und falls ein Spieler im letzten Zug zwei oder mehr Zaubersprüche gewirkt hat, transformiere den Heuler der Krallenhorde.",
                        "type": "Kreatur — Werwolf"
                    },
                    {
                        "language": "Spanish",
                        "multiverseId": 413261,
                        "name": "Aullador de Krallenhorde",
                        "text": "Te cuesta {1} menos lanzar los hechizos de criatura.\nAl comienzo de cada mantenimiento, si un jugador lanzó dos o más hechizos en el último turno, transforma al Aullador de Krallenhorde.",
                        "type": "Criatura — Licántropo"
                    },
```

**Comment by ZeldaZach** [comment]
~~Uploading 4.2.2 shortly. Lmk if it's still an issue for you!~~

**Comment by ZeldaZach** [comment]
I've let SF know, and will update this when I hear back.

**Comment by ZeldaZach** [comment]
Update: SF doesn't have the full data available as they have to manually confirm it as correct. Not sure of a good fix. Willing to accept a file that has the mappings if you'd like to make it :)

**Comment by robertjanetzko** [comment]
mtgjson3 had this data, so it should be available somewhere.
what kind of mapping would you need? multiverseId to multiverseIdBack?

**Comment by ZeldaZach** [comment]
You can just give it as simply `Card Name | Front ID | Back ID` in a list or something if that's convenient for you. Unfortunately I have no backups of MTGJSONv3 data, so if you have some feel free to share it on.

The mapping you make doesn't have to be JSON or anything, simple CSV or smth would work too. Lmk if you have Qs

**Comment by robertjanetzko** [comment]
ok, I think I can write a script that will check all languages of all b sides on gatherer for the back side id

**Comment by ZeldaZach** [comment]
Appreciated! Thanks for supporting my project :)

**Comment by robertjanetzko** [comment]
here is a map for all foreign flip, transform and meld cards: https://gist.github.com/robertjanetzko/ab3a746e697da06070426197b94350c9

and here is some code to create it: https://gist.github.com/robertjanetzko/0020b377a8cb0d36ec43c08dbf719244

**Comment by ZeldaZach** [comment]
I'm reviewing your outputs but they don't seem to be too helpful in its current state.

Can you have it output (in non-json format) `Card Name, CardMID, Foreign Lang, ForeignMID\n`? that would be super helpful! :)

**Comment by robertjanetzko** [comment]
i thought you could just replace the multiverse ids of the b-sides with the ones from the map

but I can also export them as csv tomorrow

**Comment by robertjanetzko** [comment]
CSV: https://gist.github.com/robertjanetzko/85800a676a2c598599a1aa2b11007ef2
and code to create it: https://gist.github.com/robertjanetzko/276180ff2d2362c9021c5518b45ff8e6

**Comment by ZeldaZach** [comment]
Submitted and approved upstream. Thanks for the help. Will be fixed in the next release :)

@robertjanetzko If you'd like to join us on Discord, please feel free! It's how we stay in contact around these parts. Link's on the website.
