### ISSUE TITLE
403 Error when Accessing from Java Application

### ISSUE THREAD

**Issue by aroelke** [mtgjson/mtgjson#244]
I'm trying to write a Java application that makes use of MTGJSON, but when my application attempts to connect to mtgjson.com in order to get any information (even version number), I get a 403 error.  Is this intentional?

**Comment by justin-gerhardt** [comment]
mtjson.com is not the right domain, you've made a typo. The domain is mtgjson.com

**Comment by skwerlman** [comment]
mtjson.com doesn't throw a 403 tho, so i think its only a typo in the report

**Comment by tritoch** [comment]
Your INVENTORY_SOURCE http://mtgjson.com/json/ returns 403.

Your INVENTORY_FILE must not be getting passed to your url grabber

**Comment by aroelke** [comment]
Sorry about the typo; I fixed it.

Also, it seems to have magically fixed itself somehow.  My INVENTORY_SOURCE gets concatenated with other values to get the version information and download the file, but without changing anything its works now.
