### ISSUE TITLE
Outdated Vintage Banned/Restricted List

### ISSUE THREAD

**Issue by Fizztastic** [mtgjson/mtgjson#246]
http://magic.wizards.com/en/game-info/gameplay/formats/vintage
Cards to be added to the banned list:
- Adriana's Valor 
- Assemble the Rank and Vile 
- Echoing Boon 
- Emissary's Ploy 
- Hired Heist 
- Hold the Perimeter 
- Hymn of the Wilds 
- Incendiary Dissent 
- Natural Unity 
- Sovereign's Realm 
- Summoner's Bond 
- Weight Advantage 

Cards to be added to the restricted list:
- Chalice of the Void
- Dig Through Time
- Lodestone Golem
- Treasure Cruise

Cards to be removed from the restricted list:
- Gifts Ungiven
- Thirst for Knowledge

**Comment by gwax** [comment]
This has been fixed by previously committed PRs.
