### ISSUE TITLE
Unstable Double sided Tokens Missing Numbers, and layout/side details

### ISSUE THREAD

**Issue by excention** [mtgjson/mtgjson#247]
#### Description of Bug:
The unstable tokens are missing card numbers, and layout/side details to denote that they are a single card with an alternate art on the back. Assume that the layout is supposed to be "double_faced_token"

**Comment by ZeldaZach** [comment]
I've been having a lot of issues dealing with Unstable tokens. Will re-review at some point in the future when I find time. If you'd like to contribute a fix for them, always accepting! :)

**Comment by excention** [comment]
Do you have some idea where the offending code is in the code base? I can take a look no guarantees

**Comment by ZeldaZach** [comment]
https://github.com/mtgjson/mtgjson/blob/master/mtgjson4/compile_mtg.py#L383 would be a good starting point

**Comment by excention** [comment]
https://github.com/excention/mtgjson/tree/Ticket247
