### ISSUE TITLE
Add Array of Printed Languages to Set Object

### ISSUE THREAD

**Issue by nhrsn** [mtgjson/mtgjson#249]
A set defines the languages that all its cards are printed in (apart from a few corner cases). If each set object displays a list of its printed languages it would be easier to loop over sets and determine how many cards in all languages exist.

**Comment by ZeldaZach** [comment]
After our discussions, I've come to realize this is probably _not_ the best way to handle such a feature. The inconsistencies of printings in foreign languages makes it tough, especially when we get to cards that have printings in only a specific language.

I'm leaving it up to the reader as an exercise to determine what languages to prune for in each set. Thanks for the ticket, and I hope you have more ideas in the future :)
