### ISSUE TITLE
Phoenix Heart

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#250]
If http://mtgsalvation.gamepedia.com/Proposal and http://mtgsalvation.gamepedia.com/Splendid_Genesis are treated as cards, then http://mtgsalvation.gamepedia.com/Phoenix_Heart should probably be as well.

**Comment by gwax** [comment]
Phoenix Heart does not show up in magiccards.info, which is where the rest of this set is pulled from. Until there is an upstream to draw upon, mtgjson cannot provide the card.

**Comment by taw** [comment]
@gwax MCI is barely maintained, so it needs to be fixed here if anywhere.

**Comment by gwax** [comment]
mtgjson scrapes, normalizes and aggregates data from elsewhere

whether it is MCI or somewhere else, there needs to be somewhere that the data is scraped from.

**Comment by silasary** [comment]
Scryfall has this data, under [pcel](https://scryfall.com/sets/pcel).  Seems like a point if favor for #412

**Comment by ZeldaZach** [comment]
I'd like support for this added, if it has to be done by a C.js edit, then so be it.

**Comment by silasary** [comment]
I could send a PR that defines Phoenix Heart and potentially [Gleemox](https://scryfall.com/card/pgmx/1) in C.js, if you think that's ideal.  (Although I'm not a fan of defining entire cards with corrections)

**Comment by gwax** [comment]
@silasary I don't think it's ideal but I think it's the most practical solution for right now.

**Comment by gwax** [comment]
Phoenix Heart would want to be added to the pCEL config json: https://github.com/mtgjson/mtgjson/blob/master/shared/set_configs/promo/pCEL.json

And Gleemax would want to be in UNH config json: https://github.com/mtgjson/mtgjson/blob/master/shared/set_configs/un/UNH.json

**Comment by silasary** [comment]
Gleemox, not gleemax.  (Entirely different card).  

And it would probably want to go somewhere with other Magic Online Promo cards (If we had them).

**Comment by fenhl** [comment]
@gwax: Gleemox is a MTGO-only promo un-card, not to be confused with [Gleemax](https://mtg.wtf/card/uh/121) from _Unhinged_ (which is [on Gatherer](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=73947) and thus in MTG JSON already).

**Comment by ZeldaZach** [comment]
I know we have mtgo-only sets in JSON... did we miss that promotional set somehow?

**Comment by gwax** [comment]
TIL.

Then, I'd be inclined to say that Gleemox should probably get its own set config in the the `un` folder.

**Comment by gwax** [comment]
Or, maybe `pMGTO` for online-only promos

**Comment by KingSupernova31** [comment]
Fixed in v4.
