### ISSUE TITLE
SOI missing magicCardsInfoCode

### ISSUE THREAD

**Issue by aeosynth** [mtgjson/mtgjson#252]
Shadows over Innistrad (SOI) is missing its magicCardsInfoCode: `soi`

edit: it's missing all the `mciNumber`s as well

**Comment by Garbee** [comment]
If the set code is the same for MCI then I don't think we set it at all. It should only be set if it is different then the primary set code.

**Comment by aeosynth** [comment]
these are the only sets which do not have a `magicCardsInfoCode`:

```
RQS Rivals Quick Start Set
VAN Vanguard
DDQ Duel Decks: Blessed vs. Cursed
W16 Welcome Deck 2016
SOI Shadows over Innistrad
EMA Eternal Masters
EMN Eldritch Moon
V16 From the Vault: Lore
CN2 Conspiracy: Take the Crown
DDR Duel Decks: Nissa vs. Ob Nixilis
KLD Kaladesh
MPS Kaladesh Inventions
C16 Commander 2016
```

13/200 sets
