### ISSUE TITLE
Cockatrice/Oracle

### ISSUE THREAD

**Issue by MECHHavik** [mtgjson/mtgjson#254]
#### Description of Bug:
When using the Oracle program for Cockatrice the attached error message comes up. Not sure if it's something wrong with your coding or the Cockatrice/Oracle program.
![error 2-18-19](https://user-images.githubusercontent.com/47767892/52989976-ea16f580-33d3-11e9-8508-01c21aaac4f4.jpg)

**Comment by skwerlman** [comment]
What version of cockatrice are you using?

**Comment by ZeldaZach** [comment]
This is a Cockatrice issue, not a MTGJSON issue. Please file the issue there, and ensure you are on 2.6.2 or newer.
