### ISSUE TITLE
some cards have {0} mana cost

### ISSUE THREAD

**Issue by aeosynth** [mtgjson/mtgjson#254]
this might not be a bug, but some cards (eg black lotus) have `{0}` as their mana cost, whereas most cards with 0 cmc do not have the mana cost field.

**Comment by dgant** [comment]
{0} should be correct. That is in fact the mana cost.

In Magic the distinction between a mana cost of "{0}" and "no mana cost" is significant: Black Lotus costs {0}, which means you can cast it for that cost (free), while Ancestral Vision has no mana cost, meaning you can not cast it for its mana cost. You can only cast Ancestral Vision if you're allowed to do so without paying its mana cost (ie. Suspend or something like Cascade).

Do you have an example of a card with an inappropriate mana cost?
