### ISSUE TITLE
Remove mhash dependency

### ISSUE THREAD

**Issue by lsmoura** [mtgjson/mtgjson#255]

**Comment by ekendra-nz** [comment]
> mhash@2.1.6 install  /mtgjson/node_modules/mhash
> node-gyp rebuild

make: Entering directory `/mtgjson/node_modules/mhash/build'
  ACTION binding_gyp_libmhash_target_test .
make[1]: Entering directory `/mtgjson/node_modules/mhash/deps/mhash'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory `/mtgjson/node_modules/mhash/deps/mhash'
  TOUCH Release/obj.target/libmhash.stamp
  CXX(target) Release/obj.target/mhash/mhash.o
make: g++: Command not found
make: *** [Release/obj.target/mhash/mhash.o] Error 127
make: Leaving directory `/mtgjson/node_modules/mhash/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-042stab123.3
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mtgjson/node_modules/mhash
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mhash@2.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mhash@2.1.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-30T04_30_37_166Z-debug.log

**Comment by ZeldaZach** [comment]
Removed in V4
