### ISSUE TITLE
Bloodbraid elf missing foreign data [pt-br]

### ISSUE THREAD

**Issue by kiagam** [mtgjson/mtgjson#256]
Hi guys, just noticed that bloodbraid elf is missing foreign data for portuguese - brasil

https://scryfall.com/card/arb/50/pt/elfo-tran%C3%A7as-de-sangue

That is the one that caught my eye, not sure if there are other entries missing. If you ever need translation for pt-br, feel free to message me.

thanks

**Comment by ZeldaZach** [comment]
Nice catch. I'll get this fixed up in the 4.3.0 release coming really soon :)

**Comment by ZeldaZach** [comment]
Should be fixed now!
