### ISSUE TITLE
mkm_name and mkm_id missing

### ISSUE THREAD

**Issue by MickHardins** [mtgjson/mtgjson#258]
Hi! In v3 Sets had some fields that are now missing like mkm_name and mkm_id. Any plans to re-insert this info? 😄

**Comment by ZeldaZach** [comment]
Hi @MickHardins! We decided to end support of MKM name/id with MTGJSONv4 since they weren't too useful to most of our users and can be determined manually by a user on the MKM website.

We also want to be careful with how many external dependencies we add, as the more external sources we support, the more work we'll need to do to keep it valid and accurate in case of changes upstream.

I'll keep this open for discussion for a few days to allow others to leave their opinions and we can determine where to go from there :)

**Comment by MickHardins** [comment]
Thanks for the super-fast response! Personally I think mkm is way more useful than TCG for EU players, but i also understand that for non-EU players it's the opposite. 

Keeping the dependencies low it's good, but IMHO adding the most used store in EU could provide some utility for developers.

Anyway, if i'm the only one to use those fields, then it's probably not worth it readding it, and i'll do some scraping! :)

**Comment by ZeldaZach** [comment]
Starting to look into this a bit more, but a roadblock I'm hitting is I don't have a conversion from MTGJSON -> MKM.

I have the MKM lineup of (Set Name, Set ID) but they don't have, for example, official MTG codes, so I can't validate which sets they go to automatically... gonna have to investigate further

**Comment by MickHardins** [comment]
I could have a mapping from mtgjson code to mkm code up to dominaria. I'll try to check in the next days, although it will probably take more time, since i'm very busy lately. :(

**Comment by ZeldaZach** [comment]
Not a problem, it can make it into a provisional release :) Here's my current mapping, but I need it translated to gatherer/scryfall set codes:

Here's a gist of all the sets they have available: https://gist.github.com/ZeldaZach/be62b82f22508564f332f7f51c502b68
Key = Set Name, value = Set ID. I need to get a Set Name <-> Set Code translation to implement this.

**Comment by ZeldaZach** [comment]
bump @MickHardins

**Comment by MickHardins** [comment]
Hi Zach, sorry for the late reply.
This is what i have:
https://gist.github.com/MickHardins/9423cfc5a88ceed8c28fff93c5da394f

It's a CSV with ";" as a delimiter (because of commas in some set names). It contains Set Name, MKM Name (-1 if not available), MKM ID (0 if unavailable), and Set Code (Mtgjson)

let me know if it's helpful :)

**Comment by cusco** [comment]
Hello,

apologies for opening this again, perhaps a new issue should be created or a different form of contact be made? If so please let me know.

I was having the same issue.. 

Looking at SetList I iterate through each record to find the 'mcmId' or 'mcmIdExtras' and right now I have 355 sets from cardmarket that I could not relate to the information provided by mtgjson, and 281 that were indeed related.

Then I used the before mentioned gist to relate missing ones, but still only an additional 19 were related...

in my case, I'm trying to get additional info: code, release_date, type, is foil only - but I can see how it should be useful for anyone else working with cardmarket data to be able to relate any available info.


I don't have access to cardmarket API, however a piece of information that was available only [behind the API ](https://api.cardmarket.com/ws/documentation/API_2.0:PriceGuide)is now [offered publicly](https://www.cardmarket.com/en/Magic/Data/Download).  This is [relatively recent](https://news.cardmarket.com/en/Magic/were-making-the-price-guide-and-product-catalogue-available-for-download) and it is possible to see an increase interest for cardmarket id.


**This being said, is this something that I should keep my eye on and mtgjson will improve? or should I try to look elsewhere?**
