### ISSUE TITLE
Rakdos the Defiler in RNA Guild Kit is missing Artist

### ISSUE THREAD

**Issue by marshl** [mtgjson/mtgjson#259]
#### Description of Bug:Rakdos the Defiler in RNA Guild Kit is missing Artist
Rakdos the Defiler in RNA Guild Kit (GK2) does not have an artist,.
The artist should be "Zoltan Boros & Gabor Szikszai". (http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=460617)

No other cards in the set are missing an artist.

**Comment by ZeldaZach** [comment]
Thanks for pointing this out! I'll get it fixed up in the next release :)

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
Fixed upstream
