### ISSUE TITLE
Readdress how failed downloads work

### ISSUE THREAD

**Issue by theelk801** [mtgjson/mtgjson#26]
Here's the log: https://gist.github.com/theelk801/c62033260ddb5ef1cfb6e94d3b63d8ae

**Comment by fenhl** [comment]
I'm not seeing any exception in the main task, just lots of unretrieved ones in other tasks. We should make sure these are propagated to the main task.

**Comment by ZeldaZach** [comment]
I see a lot of `concurrent.futures._base.TimeoutError` errors. The timeouts were something we tried to address with the re-download but that seems to be failing. 

Ticket update: Readdress how failed downloads work

**Comment by ZeldaZach** [comment]
Code location: [MTG_HTTP.PY](https://github.com/mtgjson/mtgjson-python/blob/master/mtgjson4/mtg_http.py#L21)

**Comment by theelk801** [comment]
This is one of the reasons to just use the Scryfall API, you know exactly where you stand with regards to things timing out since you're not scraping.

**Comment by ZeldaZach** [comment]
I'll need to consult with them, but scraping exclusively from scryfall seems like a bad thing for both parties.

1) We essentially become "scryfall.json.zip" which is not what I want to be. 
2) Their API is a paid service, so providing a full download of their work seems like we're hurting their business model
3) Sometimes they may have mistakes that we can correct before them.

**Comment by theelk801** [comment]
That's understandable. I didn't realize they had a paid version of their API though.

**Comment by ZeldaZach** [comment]
I don't believe this ticket is relevant anymore. We use a different method to download now, as well as a completely different structure.
