### ISSUE TITLE
Hyphen/Minus inconsistencies for planeswalkers

### ISSUE THREAD

**Issue by marshl** [mtgjson/mtgjson#260]
#### The use of hyphen or minus sign for planeswalker loyalty costs is inconsistent
While most planeswalkers (137) use the minus sign (−) for the text minus loyalty abilities, a handful of them use hyphens (-) instead. Those planeswalkers are:
"Garruk the Slayer"
"Urza, Academy Headmaster"
"Will Kenrith"
"Rowan Kenrith"
"Ral, Izzet Viceroy"
"Vraska, Golgari Queen"

This only seems to affect the  "text" field, the "originalText" field uses minus signs. This is also a really minor issue; you don't really need to fix it, I just thought you should know. Thanks :)

**Comment by ZeldaZach** [comment]
You're fully correct on this one! I'll forward it upstream :)

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by ZeldaZach** [comment]
Addressed upstream
