### ISSUE TITLE
ITP has duplicate numbers for unrelated cards

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#262]
#### Description of Bug:

Most number duplicates are just multipart cards with missing a/b (or a/b/c/d/e for unsets), so I can fill that in.

This one is just data bug.

https://mtgjson.com/json/ITP.json

* `"53" - "Plains", "Forest"`
* `"54" - "Plains", "Island"`
* `"55" - "Plains", "Mountain"`
* `"56" - "Plains", "Island"`
* `"57" - "Island", "Swamp"`

Whichever numbers mtgjson ends up choosing, they should very definitely be unique within same set.

**Comment by taw** [comment]
Actually now that I double checked this file, there's weird stuff like `"frameVersion": "2015",` for some of them. (it came out in 1996)

**Comment by ZeldaZach** [comment]
Upstream issue.

cc: @csuhta

**Comment by csuhta** [comment]
Fixed upstream (also we added localizations for the other collector numbers too)
