### ISSUE TITLE
A25 / CNS / CN2 Watermarks

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#263]
#### Description of Bug:

This is somewhat between bug and enhancement request.

* https://mtgjson.com/json/A25.json
* https://mtgjson.com/json/CNS.json
* https://mtgjson.com/json/CN2.json

A25 cards have `"watermark": "set"`. Even Gatherer lists their actual watermarks.

I guess something like `"set (CNS)"` would make the most sense, because some sets have stupid names like "Magic: The Gathering—Conspiracy" which don't necessarily match normalized names mtgjson uses otherwise.

In related issue,  CNS / CN2 use `"watermark": "conspiracy"`. As it conflicts with A25 use of "conspiracy" watermark, I'd recommend changing it to `"watermark": "draft"`.

Related links:

* http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=442194
* http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=416758

**Comment by ZeldaZach** [comment]
I like the idea of changing the watermarks to being `set (CODE)` where appropriate.

I don't think I'll change the CNS/CN2, as there won't be a conflict with the naming scheme.
