### ISSUE TITLE
BFZ basics with rarity common

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#265]
#### Description of Bug:

https://mtgjson.com/json/BFZ.json

BFZ had fun basics as they were in two versions, full art (for boosters and fat packs) and traditional (for intro packs). Anyway, they should all have rarity `"basic"`, not `"common"`.

Related links:

* http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401887
* http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401889

**Comment by ZeldaZach** [comment]
We discontinued the "basic" type as only basic lands had it. Can easily determine on own now.

Should we look at re-adding it? Would be a simple fix (if basic land -> set type). Want more opinions.

**Comment by taw** [comment]
Why? It's official rarity, it gets own print sheets, and it only _mostly_ maps to basic type.

There are exceptions both ways:

* [some basic lands have nonbasic rarity printed on them](http://mtg.wtf/card/pjgp/90/Island)
* [ME4 had basic sheet with these](http://mtg.wtf/card?q=-t%3Abasic+r%3Abasic+%2B%2B)

**Comment by ZeldaZach** [comment]
If you can provide me the full list of lands that fit the basic role, and common role, I can look into integrations

**Comment by JayDi85** [comment]
@taw gatherer "rarity" is booster slot type, not real card rarity (info from scryfall admins -- that's why they have diffs).

**Comment by taw** [comment]
What do you mean by "real card rarity"?

**Comment by JayDi85** [comment]
Rules rarity -- see 206.2

> 206.2. The color of the expansion symbol indicates the rarity of the card within its set. A red-orange symbol indicates the card is mythic rare. A gold symbol indicates the card is rare. A silver symbol indicates the card is uncommon. A black or white symbol indicates the card is common or is a basic land. A purple symbol signifies a special rarity; to date, only the Time Spiral®“timeshifted”cards, which were rarer than that set’s rare cards, have had purple expansion symbols. (Prior to the Exodus™set, all expansion symbols were black, regardless of rarity. Also, prior to the Sixth Editioncore set, with the exception of the Simplified Chinese Fifth Editioncore set, Magiccore sets didn’t have expansion symbols at all.)

**Comment by JayDi85** [comment]
@taw look at that comment from scryfall:
https://github.com/scryfall/gatherer-bugs/issues/34#issuecomment-425260926

> The Uzra lands are not basic lands, but this isn't what "Basic Land" rarity on Gatherer means here. It is WotC's notation for appearing in the basic land slot of a booster. It usually makes the card even more "common" than common cards.
> 
> Newer cards with this rarity have "L" printed on the bottom of the card with a black set symbol next to the type line. Scryfall files those cards under commons since most people don't make this really specific distinction.

**Comment by taw** [comment]
> If you can provide me the full list of lands that fit the basic role, and common role, I can look into integrations

So here's how I see it:

* rarity only _approximately_ maps to things like expansion symbol, print sheets, or card frequency
* basic land is official rarity, WotC refers to it as a separate rarity on 100% consistent basis, and never once referred to basics as commons, I'm completely baffled by scryfall thinking here. ( [Random example](https://magic.wizards.com/en/articles/archive/news/changes-2008-06-02) )
* there are boosters, precons, and promos, and no notion of "rarity" will neatly work for all
* unless you think Gatherer has data bugs (and that wouldn't be the first), we should generally trust what Gatherer says is card's official rarity

For boosters:

* basics land type and basic rarity mostly map
* one exception where non-basic officially has basic rarity is ME4 Urza lands
* the other exception is [ARN Mountain at C1 rarity](http://mtg.wtf/card?q=e%3Aarn+t%3Abasic), which in terms of frequency is basically a rare 🤷‍♂️ , I don't have a super strong opinion on what to do with it, it was literally a mistake by WotC
* there's been some cases where land sheet was used for something else than basics, like guildgates, or [UST Steamflogger Boss](http://mtg.wtf/card/ust/93/Steamflogger-Boss) - they're generally not seen as being of basic rarity

For precons:

* precon "rarity" is completely made up anyway, so we should just follow basic type = basic rarity
* I don't think there are any controversial cases

For promos:

* a lot of basic lands will have non-basic symbol [like this](http://mtg.wtf/card/pjgp/93/Forest) or [this](http://mtg.wtf/card/parl/71/Forest)
* others will have basic symbol [like this](http://mtg.wtf/card/parl/27/Forest)
* [or no symbol](http://mtg.wtf/card/palp/12/Island)
* [or whatever that is](http://mtg.wtf/card/parl/39/Island)
* I'd just give all promos of any kind single `special` rarity
* Gatherer doesn't generally have promos, so it won't give us any help

For related information:

* if anyone feels like having separate `expansion symbol color` field, nothing wrong with that, but that is not same as rarity. It would be very easy to get it algorithmically (except for some promos). It would differ from rarity mostly for old sets, which didn't have colored expansion symbols.
* if anyone feels like having separate `print sheet rarity` field, [I actually have this data for most sets](http://mtg.wtf/sealed), and I even display it for a few notable ones with 2 print sheets ([see this for example](http://mtg.wtf/card?q=e%3Aarn+view%3Afull) ). It's a lot of messy reverse engineering, and probably not 100% accurate (like we don't really know what's 101th half-frequency common etc.).

**Comment by ZeldaZach** [comment]
This seems like a lot of work for little reward, so I'll leave this open for a bit if anyone wants to give it a shot, but it's a no-fix on my end.
