### ISSUE TITLE
'little girl' has no color

### ISSUE THREAD

**Issue by aeosynth** [mtgjson/mtgjson#266]
the UNH card 'little girl' has no colors or color identity; it should be ['white'], ['w']

http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74257

**Comment by lsmoura** [comment]
Yeah... my color detector parser does not understand `{hw}`! I'll fix this manually.

**Comment by KingSupernova31** [comment]
This is still an issue in the most recent build.

**Comment by skwerlman** [comment]
it looks like this change got lost on a rebuild
