### ISSUE TITLE
ARN many to one multiverseid mapping needed

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#266]
#### Description of Bug:

For some background - https://magic.wizards.com/en/articles/archive/versus-b-2002-08-08

v3 was matching gatherer and had 92 cards. v4 has this more limited idea and 78.

It's probably fine either way, but then mtgjson should include `otherMultiverseIds` field or something.

This many-to-one multiverseid mapping applies to S00 in a different way.

**Comment by ZeldaZach** [comment]
Dupe #231
