### ISSUE TITLE
RNA Guildgates missing tcgplayer fields

### ISSUE THREAD

**Issue by Grantward68** [mtgjson/mtgjson#268]
#### Description of Bug:
All the RNA set tcgplayerProductId & tcgplayerPurchaseURL fields seem to be missing for all 10 Guildgate cards:  243-244, 249-250, 252-253, & 255-258.

**Comment by ZeldaZach** [comment]
Fixed upstream, will push a release at some point soon. Thanks for the report!!
[RNA.json.txt](https://github.com/mtgjson/mtgjson/files/2975956/RNA.json.txt)
