### ISSUE TITLE
Adding Concurrency

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson#27]
By adding concurrency (`multiprocessing`) to the build sequence, we can increase the speed of the builds. The goal is <2 hours for an all build.

My initial thought is to make each set run on a thread in a pool, but suggestions are greatly appreciated!

**Comment by fenhl** [comment]
We should not be using threads since we're already using asyncio and threads don't really do anything in Python. Multiprocessing is the way to go.

**Comment by ZeldaZach** [comment]
I'm not a Python expert, but isn't the multiprocessing package just `ThreadPool()` ?

**Comment by fenhl** [comment]
Multiprocessing uses processes, not threads. Hence the name.

**Comment by ZeldaZach** [comment]
Weird how they use the word thread then... but anyway, yeah processes would be useful
