### ISSUE TITLE
HTR17 set is missing two cards

### ISSUE THREAD

**Issue by ctrlaltca** [mtgjson/mtgjson#270]
#### Description of Bug:
It looks like the HTR17 set is missing two cards out of three.
Original ticket: https://github.com/Cockatrice/Cockatrice/issues/3643
Scryfall set: https://scryfall.com/sets/htr17
Mtgjson set: https://mtgjson.com/json/HTR17.json

**Comment by ZeldaZach** [comment]
Was added after build. Will be added in 4.3.2 when that’s ready in a week or two.
