### ISSUE TITLE
Wrong french name "unforge"

### ISSUE THREAD

**Issue by dauclem** [mtgjson/mtgjson#271]
"Unforge" french translation should be "Refusion" : http://lotusnoir.info/magic/cartes/?c=refusion&ed=&ref=

**Comment by Nightfirecat** [comment]
Doesn't look like it...

* http://magiccards.info/ds/fr/71.html
* http://gatherer.wizards.com/Pages/Card/Languages.aspx?multiverseid=51616

**Comment by Nightfirecat** [comment]
Hm... That said, there's this: http://www.ebay.com/itm/CARTAPAPA-MTG-Refusion-Unforge-4-SOMBRACIER-/330795641399?hash=item4d04f4ea37:m:m832C4uy3RClGOakVYrnPuw

**Comment by Nightfirecat** [comment]
I guess this must have been a printing error? The rules text says this: (emphasis mine)

> Détruisez l'équipement ciblé. Si cet équipement était attaché à une créature, ***la Refonte*** inflige 2 blessures à cette créature.

**Comment by dauclem** [comment]
"Refonte" is used for "Reshape" too : http://gatherer.wizards.com/Pages/Card/Languages.aspx?multiverseid=76081
I thought it could not be used twice. I close this issue.

Thank you for your quick reply.

**Comment by Nightfirecat** [comment]
Huh, that's rather bizarre. 🤔
