### ISSUE TITLE
Duplicate uuid in UST set

### ISSUE THREAD

**Issue by schnolis** [mtgjson/mtgjson#272]
#### Description of Bug:
Both cards with the name Clue have the same uuid in the UST set
        {
            "artist": "John Avon",
            "colorIdentity": [],
            "colors": [],
            "layout": "double_faced_token",
            "name": "Clue",
            "number": "18",
            "reverseRelated": [],
            "scryfallId": "9b111525-0600-4bae-94a3-df8f9472388f",
            "scryfallOracleId": "422255ab-969d-485f-8c8b-cb7efe33c9fe",
            "side": "b",
            "type": "Token",
            "uuid": "aeda024e-7324-51a4-8dc3-bc857a4cb720"
        },
        {
            "artist": "John Avon",
            "colorIdentity": [],
            "colors": [],
            "layout": "double_faced_token",
            "name": "Clue",
            "number": "18",
            "reverseRelated": [],
            "scryfallId": "9b111525-0600-4bae-94a3-df8f9472388f",
            "scryfallOracleId": "422255ab-969d-485f-8c8b-cb7efe33c9fe",
            "side": "a",
            "text": "{2}, Sacrifice this artifact: Draw a card.",
            "type": "Token Artifact — Clue",
            "uuid": "aeda024e-7324-51a4-8dc3-bc857a4cb720"
        },

**Comment by ZeldaZach** [comment]
So the cards are really weird because they're the same card in essence, one side just has the picture larger... 

I'll think about what to do here next week.
