### ISSUE TITLE
PDOM - Dominaria Promos are missing tcgplayerProductId

### ISSUE THREAD

**Issue by jmcsmith** [mtgjson/mtgjson#273]
Looks like the PDOM cards are missing the tcgplayerProductId in the set file. 
I specifically checked Llanowar Elves but also searched for the field anywhere in the file and it was not there.

**Comment by ZeldaZach** [comment]
https://shop.tcgplayer.com/magic/open-house-promos/llanowar-elves
https://shop.tcgplayer.com/magic/prerelease-cards/jayas-immolating-inferno
https://shop.tcgplayer.com/magic/prerelease-cards/forebears-blade

Looks like they have their own methods of marking cards... will have to play around with this to get promos added correctly

**Comment by ZeldaZach** [comment]
Just re-built locally and they all appear to be there. Will close now. If still an issue at the next release, please do drop a line!

[PDOM.json.txt](https://github.com/mtgjson/mtgjson/files/2975915/PDOM.json.txt)
