### ISSUE TITLE
newSetFiles and updateSetFiles fields missing in changelog.json

### ISSUE THREAD

**Issue by jceddy** [mtgjson/mtgjson#275]
For both the 3.7.1 and 3.8 updates the newSetFiles and updateSetFiles fields are missing.

My importer uses these to determine which set files to grab/import...was this a deliberate change, or an oversight?

**Comment by lsmoura** [comment]
This was deliberate for now, as I'm unable to update mtgjson properly until late march. Sorry about this. If you are willing to update `changelog.json` with the proper values, and make a push request, I'll happily commit it and redeploy.

Once I'm done with my current work commitments, I'll get back to normal.

I'm going to leave this open until this is fixed.

**Comment by jceddy** [comment]
would it work to have a new version (3.8.1?) that just updates/adds the sets affected by 3.7.1 and 3.8? or would it be better to add the missing fields to those releases?

**Comment by lsmoura** [comment]
In this case, just add the fields to the existing releases... Don't create a new release, since no cards/sets have changed.

**Comment by lsmoura** [comment]
Published!
