### ISSUE TITLE
Genesis Hydra Promo

### ISSUE THREAD

**Issue by dkniffin** [mtgjson/mtgjson#282]
I recently received this card in a deck:

<img src="https://cloud.githubusercontent.com/assets/1680080/22333878/384e1042-e3a6-11e6-84fd-1203ba17d28d.png" width="300px"/>

I don't see this printing of it in the data. Not sure if this data set usually includes promos or not.

**Comment by lsmoura** [comment]
Same thing of #281 -- Here's the MCI link: http://magiccards.info/mbp/en/142.html

**Comment by dkniffin** [comment]
@lsmoura Thanks! I'm consuming this data via the MTG Unnofficial android app, so there's a few steps between this dataset and the app. I think these cards are getting lost somewhere. I'll track that down and report it there.

**Comment by lsmoura** [comment]
What app? Does it uses mtgjson data?

**Comment by dkniffin** [comment]
This is the app: https://play.google.com/store/apps/details?id=io.carlol.mtgu.mobile&hl=en I thought it was using this data, but now that I'm searching in the app, I can't seem to find a reference to this dataset.
