### ISSUE TITLE
Color Identity missing for some cards

### ISSUE THREAD

**Issue by MitjaHenner** [mtgjson/mtgjson#284]
Some cards that have a color don't have a color identity, for example:
Jaya, Dromoka, Kiyomaro, Korlash, Glissa, Atarka, Daghatar, Kolaghan, Ojutai, Shu Yun, Silumgar, Tasigur, Yasova

**Comment by gwax** [comment]
This appears to be fixed as of now. If not, could you please reference the specific set files that are broken.
