### ISSUE TITLE
Add PucaTrade ID number

### ISSUE THREAD

**Issue by MidnightLightning** [mtgjson/mtgjson#287]
For importing/reporting on cards within the the [PucaTrade](https://pucatrade.com) website, they don't use the multiverse ID, nor the number within an expansion set. Instead they have their own "PucaID" number, which is part of the URL for individual cards on their site, and part of their sample import spreadsheet.

Compounding the problem for figuring out which card is which, for cards with multiple art, they modify the name of the card to either have a description of the card (["Island (Spire)"](https://pucatrade.com/cards/show/30983)), the card number in the set (["Plains (230)"](https://pucatrade.com/cards/show/20761)), or something arbitrary (["Feast of the Unicorn [Version 2]"](https://pucatrade.com/cards/show/29878)).

If mtgjson could include the PucaID alongside the other identifiers already in this data set, it would greatly help in matching up cards from other systems to Puca.

- [puca-import-example-paper-have.csv.txt](https://github.com/mtgjson/mtgjson/files/745424/puca-import-example-paper-have.csv.txt)

**Comment by MidnightLightning** [comment]
Note, PucaTrade's [website terms](https://pucatrade.com/terms) do note:

> GENERAL RULES. You agree not to engage in any of the following prohibited activities: (i) copying, distributing, or disclosing any part of the Service in any medium, including without limitation by any automated or non-automated “scraping”

So, mtgjson could not just spider/scrape all the public card information pages from PucaTrade, though it may be worth reaching out to the PucaTrade admins to see if a specific collaboration like this could be agreed upon, to benefit both sites.

**Comment by Garbee** [comment]
I don't see the value in adding in Pucatrade IDs. The vast majority of the datasets users won't touch it. It then paves the way for adding the IDs of any given site into the mix which then aren't useful to the vast majority of users.

**Comment by MidnightLightning** [comment]
I agree that bloating the dataset unnecessarily should be avoided, but looking at the mtgjson data repository as a core linking source, I see it as beneficial to link together as many sources as possible in a curated list. I don't use the mtgjson data blob as-is for my application use, since I don't need a lot of that information. I pre-process it into a slimmed down JSON data file that actually gets bundled with my application. I presume others do that as well?

Is there some threshold of MTG site popularity or mtgjson-user popularity that merits including them? MagicCards.info's number for each card is in the set, in addition to the official Wizards Multiverse ID. Why is MagicCards.info included if other popular MTG sites are to be excluded?

**Comment by Garbee** [comment]
Some information is retrieved/compared with magiccards.info. We have never gathered any data from other sources beyond MCI and Gatherer.

**Comment by digitalDojoNZ** [comment]
This type of optional functionality could be developed in a separate repo as non-core modular add-ons for those that need them.

**Comment by fenhl** [comment]
The magiccards.info interface as I understand it is mostly a legacy feature that exists because magiccards.info was once a near-perfect data source.

Perhaps a repository for manually maintained data such as this or the data discussed in #341 could be created under the mtgjson organization, and maintained by any volunteers. If there is interest in such a project, it should be brought to @ZeldaZach's attention, perhaps on [gitter](https://gitter.im/mtgjson/mtgjson).
