### ISSUE TITLE
'layout' field inconsistent on a few CHK cards

### ISSUE THREAD

**Issue by roesel** [mtgjson/mtgjson#288]
Hello, 

in the set CHK, there are flip-cards, with a playable direction (layout should equal `normal`) and the post-flip direction (layout should equal `flip`). 

A good example is Student of Elements/Tobita, Master of Winds ([gatherer](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=78691)), where Student of Elements has layout set to `normal` and Tabita to `flip`. 

However, in the following cases:

- [Bushi Tenderfoot/Kenzo the Hardhearted](http://gatherer.wizards.com/Pages/Card/Details.aspx?printed=true&multiverseid=78600)
- [Initiate of Blood/Goka the Unjust](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=78688)
- [Jushi Apprentice/Tomoya the Revealer](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=78686)   
- [Akki Lavarunner/Tok-Tok, Volcano Born](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=78694)
- [Kitsune Mystic/Autumn-Tail, Kitsune Sage](http://gatherer.wizards.com/Pages/Card/Details.aspx?printed=false&multiverseid=78695)
- [Budoka Gardener/Dokai, Weaver of Life](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=78687)

this is not so. I think in most (if not all) of these cases, the original "playable" card isn't listed at all and only its `flip` version is available. 

Thanks!

Edit: Just noticed that this was supposedly fixed on the 23rd of January and I am not working with mtgjson directly, but with [magicthegathering.io](https://magicthegathering.io) which might have an outdated DB from before the fix. If this is the case, feel free to close this issue.

**Comment by gwax** [comment]
This has been resolved as of a previous build.
