### ISSUE TITLE
Card text should use {CHAOS} for the chaos symbol not CHAOS

### ISSUE THREAD

**Issue by pbbadenhorst** [mtgjson/mtgjson#289]
There are planechase cards referencing a roll of chaos. Some are using CHAOS and others are using {CHAOS}.

I believe all the instances should be {CHAOS}.

From comprehensive rules:

107.12. The chaos symbol is {CHAOS}. It appears on one face of the planar die used in the Planechase casual variant, as well as in abilities that refer to the results of rolling the planar die. See rule 901, “Planechase.”

**Comment by Nightfirecat** [comment]
What cards do you see that display `{CHAOS}`? As far as I can tell, instances of "chaos" get converted to `{C}`: https://github.com/mtgjson/mtgjson/blob/e3176f80f0ff81219e2004d17be7459bbc3b75b0/build/rip.js#L1525

I agree that they should read `{CHAOS}`.

**Comment by pbbadenhorst** [comment]
[chaos.txt](https://github.com/mtgjson/mtgjson/files/751858/chaos.txt)

File attached, name, set, text

**Comment by pbbadenhorst** [comment]
As far as I know {C} is the symbol for colorless mana.

107.4c The colorless mana symbol {C} is used to represent one colorless mana, and also to represent a cost that can be paid only with one colorless mana.

**Comment by silasary** [comment]
Prior to the release of OGW, {C} represented the Chaos symbol. 
When they introduced the colourless symbol, they changed chaos to {CHAOS}, and used {C} for colourless instead.

Any references to {C} are old/obsolete, and should be replaced.
