### ISSUE TITLE
Missing Legalities field from AER cards in 3.8.1

### ISSUE THREAD

**Issue by mdurao** [mtgjson/mtgjson#290]
The title says it all, example card: Walking Ballista.
The file was downloaded from the website, not created locally by me.

Thank you.

**Comment by mdurao** [comment]
- Is it possible to update the public files on website?
- How can I generate locally a AllCards-x.json grabbing the "legalities" from Wizards?

Thanks

**Comment by Garbee** [comment]
The readme explains how to use the code to do local builds and get legalities.

**Comment by mdurao** [comment]
I know I can use the `npm build/buildSet.js` but it only generates the `AER.json`.
Is there any script or shortcut to rebuild the `AllSets-x.json`?
Am I missing something?

TIA, @Garbee

**Comment by Garbee** [comment]
Oh, didn't realize that command doesn't build the AllSets bit too. I think AllSets-X is built manually from the looks of it. By compiling the full set json's and merging them together.

**Comment by lsmoura** [comment]
`node web` builds everything into the `public` folder

**Comment by mdurao** [comment]
I'll give it a try, thanks!
Shouldn't the public website be updated too?

**Comment by lsmoura** [comment]
I'm fixing it. Should be updated by tomorrow as I have other fixes to publish. This issue will only be closed when things are merged into master (and consequently published).

**Comment by mdurao** [comment]
`node web` worked like a charm!

Obrigado!
