### ISSUE TITLE
Fate Reforged release date is off by a day

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#291]
#### MTGJSON Version: 4.3.2

https://mtgjson.com/json/FRF.json
https://mtgjson.com/json/CP2.json

#### Description of Bug:

Nothing I can find implies they were released one day apart. It should be 2015-01-23 for both.

Other clash packs (CP1 for M15; CP3 for ORI) seem to be fine.

Related sources:

* https://mtg.gamepedia.com/Fate_Reforged
* https://magic.wizards.com/en/game-info/products/card-set-archive/fate-reforged

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
CP2 release date has been fixed upstream
