### ISSUE TITLE
Pain \\ Suffering split card sides have same multiverseid in AllSets.json

### ISSUE THREAD

**Issue by ivodopyanov** [mtgjson/mtgjson#293]
#### Description of Bug:

There are two json card records for Invasion set:
First one with name="Suffering", multiverseid=20578, manacost="{3}{R}", side="b"
Second one with name="Pain", multiverseid=20578, manacost="{B}", side="a"

Everything correct except multiverseid. Pain's should be 20577

**Comment by ZeldaZach** [comment]
I've reported this upstream, but is this a problem for all split cards or just this one unique pair? Gatherer does report the same content no matter which MID you use, so it shouldn't be that big of a deal.

**Comment by ZeldaZach** [comment]
This is an upstream issue. If you'd like to report any and all combinations that would be cool. I'll be closing this as it's not a MTGJSON fix directly, but any changes upstream will get incorporated in our releases :)

Thanks for your report and helping to make MTGJSON the best!
