### ISSUE TITLE
legalities incorrect

### ISSUE THREAD

**Issue by dafreaki** [mtgjson/mtgjson#294]
AllCards-x.json 3.8.1 

Shock is Standard Legal  

"Shock":{"layout":"normal","name":"Shock","manaCost":"{R}","cmc":1,"colors":["Red"],"type":"Instant","types":["Instant"],"text":"Shock deals 2 damage to target creature or player.","imageName":"shock","printings":["STH","6ED","pFNM","S00","BTD","7ED","ONS","8ED","9ED","10E","DPA","M12","M14","DDN","AER"],"legalities":[{"format":"Commander","legality":"Legal"},{"format":"Legacy","legality":"Legal"},{"format":"Modern","legality":"Legal"},{"format":"Onslaught Block","legality":"Legal"},{"format":"Tempest Block","legality":"Legal"},{"format":"Vintage","legality":"Legal"}],"colorIdentity":["R"]}

I will add more when i come find them

**Comment by mdurao** [comment]
Hi @dafreaki,

I believe this is already referenced in general by bug #290.
Should be fixed soon.

Cheers.

**Comment by lsmoura** [comment]
Fixed on #290. Will deploy live soon.
