### ISSUE TITLE
Flip/transform card faceConvertedManaCost is zero but it shouldn't be

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#294]
#### Description of Bug:

IIRC `faceConvertedManaCost` was supposed to show split/aftermath cards cmc, since after rules change they have different value on stack and different value elsewhere (or when fused on stack).

Somehow flipped version of flip cards got 0 `faceConvertedManaCost` and I can't see any reason why it should be so. They never have 0 cmc in any zone.

> 709.1c

> A flip card's color and mana cost don't change if the permanent is flipped. Also, any changes to it by external effects will still apply.

Here's all flip cards (set code, name, face cmc, cmc, mana cost). It affects all of them as far as I can tell.

* `["BOK", "Azamuki, Treachery Incarnate", 0, 3.0, nil]`
* `["BOK", "Budoka Pupil", 3.0, 3.0, "{1}{G}{G}"]`
* `["BOK", "Callow Jushi", 3.0, 3.0, "{1}{U}{U}"]`
* `["BOK", "Cunning Bandit", 3.0, 3.0, "{1}{R}{R}"]`
* `["BOK", "Faithful Squire", 3.0, 3.0, "{1}{W}{W}"]`
* `["BOK", "Hired Muscle", 3.0, 3.0, "{1}{B}{B}"]`
* `["BOK", "Ichiga, Who Topples Oaks", 0, 3.0, nil]`
* `["BOK", "Jaraku the Interloper", 0, 3.0, nil]`
* `["BOK", "Kaiso, Memory of Loyalty", 0, 3.0, nil]`
* `["BOK", "Scarmaker", 0, 3.0, nil]`
* `["C18", "Budoka Gardener", 2.0, 2.0, "{1}{G}"]`
* `["C18", "Dokai, Weaver of Life", 0, 2.0, nil]`
* `["CHK", "Akki Lavarunner", 4.0, 4.0, "{3}{R}"]`
* `["CHK", "Autumn-Tail, Kitsune Sage", 0, 4.0, nil]`
* `["CHK", "Budoka Gardener", 2.0, 2.0, "{1}{G}"]`
* `["CHK", "Bushi Tenderfoot", 1, 1.0, "{W}"]`
* `["CHK", "Dokai, Weaver of Life", 0, 2.0, nil]`
* `["CHK", "Goka the Unjust", 0, 4.0, nil]`
* `["CHK", "Initiate of Blood", 4.0, 4.0, "{3}{R}"]`
* `["CHK", "Jushi Apprentice", 2.0, 2.0, "{1}{U}"]`
* `["CHK", "Kenzo the Hardhearted", 0, 1.0, nil]`
* `["CHK", "Kitsune Mystic", 4.0, 4.0, "{3}{W}"]`
* `["CHK", "Nezumi Graverobber", 2.0, 2.0, "{1}{B}"]`
* `["CHK", "Nezumi Shortfang", 2.0, 2.0, "{1}{B}"]`
* `["CHK", "Nighteyes the Desecrator", 0, 2.0, nil]`
* `["CHK", "Orochi Eggwatcher", 3.0, 3.0, "{2}{G}"]`
* `["CHK", "Shidako, Broodmistress", 0, 3.0, nil]`
* `["CHK", "Stabwhisker the Odious", 0, 2.0, nil]`
* `["CHK", "Student of Elements", 2.0, 2.0, "{1}{U}"]`
* `["CHK", "Tobita, Master of Winds", 0, 2.0, nil]`
* `["CHK", "Tok-Tok, Volcano Born", 0, 4.0, nil]`
* `["CHK", "Tomoya the Revealer", 0, 2.0, nil]`
* `["CM2", "Nezumi Graverobber", 2.0, 2.0, "{1}{B}"]`
* `["CM2", "Nighteyes the Desecrator", 0, 2.0, nil]`
* `["CMD", "Nezumi Graverobber", 2.0, 2.0, "{1}{B}"]`
* `["CMD", "Nighteyes the Desecrator", 0, 2.0, nil]`
* `["PHUK", "Nezumi Graverobber", 2.0, 2.0, "{1}{B}"]`
* `["PHUK", "Nezumi Graverobber", 2.0, 2.0, "{1}{B}"]`
* `["PHUK", "Nighteyes the Desecrator", 0, 2.0, nil]`
* `["PHUK", "Nighteyes the Desecrator", 0, 2.0, nil]`
* `["PREL", "Budoka Pupil", 3.0, 3.0, "{1}{G}{G}"]`
* `["PREL", "Ichiga, Who Topples Oaks", 0, 3.0, nil]`
* `["PRM", "Budoka Pupil", 3.0, 3.0, "{1}{G}{G}"]`
* `["PRM", "Ichiga, Who Topples Oaks", 0, 3.0, nil]`
* `["PSAL", "Autumn-Tail, Kitsune Sage", 0, 4.0, nil]`
* `["PSAL", "Kitsune Mystic", 4.0, 4.0, "{3}{W}"]`
* `["PSAL", "Nezumi Graverobber", 2.0, 2.0, "{1}{B}"]`
* `["PSAL", "Nezumi Graverobber", 2.0, 2.0, "{1}{B}"]`
* `["PSAL", "Nighteyes the Desecrator", 0, 2.0, nil]`
* `["PSAL", "Nighteyes the Desecrator", 0, 2.0, nil]`
* `["SOK", "Erayo, Soratami Ascendant", 2.0, 2.0, "{1}{U}"]`
* `["SOK", "Erayo's Essence", 0, 2.0, nil]`
* `["SOK", "Homura, Human Ascendant", 6.0, 6.0, "{4}{R}{R}"]`
* `["SOK", "Homura's Essence", 0, 6.0, nil]`
* `["SOK", "Kuon, Ogre Ascendant", 3, 3.0, "{B}{B}{B}"]`
* `["SOK", "Kuon's Essence", 0, 3.0, nil]`
* `["SOK", "Rune-Tail, Kitsune Ascendant", 3.0, 3.0, "{2}{W}"]`
* `["SOK", "Rune-Tail's Essence", 0, 3.0, nil]`
* `["SOK", "Sasaya, Orochi Ascendant", 3.0, 3.0, "{1}{G}{G}"]`
* `["SOK", "Sasaya's Essence", 0, 3.0, nil]`
* `["TD0", "Nezumi Graverobber", 2.0, 2.0, "{1}{B}"]`
* `["TD0", "Nighteyes the Desecrator", 0, 2.0, nil]`
* `["UNH", "Curse of the Fire Penguin Creature", 0, 6.0, nil]`
* `["UNH", "Curse of the Fire Penguin", 6.0, 6.0, "{4}{R}{R}"]`

**Comment by taw** [comment]
Now that I keep checking, it looks like it also affects all cards with `layout` `transform`. They have 0 cmc when they copy something, but not otherwise.

Somehow `layout` `meld` cards avoided this issue.

Basically, `faceConvertedManaCost` should only be defined for split / aftermath cards.

(unless I missed some multipart layout)

**Comment by taw** [comment]
... and those flip cards should also have `manaCost` matching their other side as per rule 709.1c.

**Comment by ZeldaZach** [comment]
Looking at it, I see no issues with leaving the fCMC value as 0 for those parts. The information is (technically) correct, as that face does not have a mana cost value. The manaCost fields should be matching on the front/back, so if that's not the case please do open a separate issue.

Any other opinions on this?

**Comment by taw** [comment]
For my local workaround, I can choose cmc/fcmc based on layout, but it's quite awkward to fill in `manaCost` for flip cards to one that agrees with the rules, as that means I need to chase the other side.

It's just trying to treat split cards, flip cards, and transform cards same way, but they have different rules, and (I'd guess) different user expectations.
