### ISSUE TITLE
Renaissance

### ISSUE THREAD

**Issue by fenhl** [mtgjson/mtgjson#295]
The reprint sets [*Renaissance*](http://mtgsalvation.gamepedia.com/Renaissance) and its Italian version *Rinascimento* seem to be missing.

**Comment by tooomm** [comment]
I think this is covered with #579 now, too.

**Comment by ancestral** [comment]
This may help as far as Renaissance goes:
https://www.wizards.com/magic/expert/Chronicles/Chronicles.asp
http://www.wizards.com/magic/generic/cardlists/Ren_Italian.html
http://www.wizards.com/magic/generic/cardlists/Ren_Fr_Ger.html

**Comment by ZeldaZach** [comment]
Added in V4
