### ISSUE TITLE
CMA releaseDate is wrong

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#295]
#### Description of Bug:

It's listed as `"releaseDate": "2017-06-06"`

It seems should be 2017-06-09

* https://magic.wizards.com/en/products/commander-anthology
* https://mtg.gamepedia.com/Commander_Anthology

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
Fixed upstream
