### ISSUE TITLE
In DDR "Ob Nixilis Reignited Emblem" is a card

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#296]
#### MTGJSON Version: 4.3.2

https://mtgjson.com/json/DDR.json

#### Description of Bug:

This is in `cards`, should be in `tokens`:
```
            "name": "Ob Nixilis Reignited Emblem",
            "number": "76",
```

The same emblem in BFZ is correctly in `tokens`.

**Comment by ZeldaZach** [comment]
Thanks for catching this, simple fix. Will push shortly.
