### ISSUE TITLE
APC Portuguese Life / Death is wrong

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#297]
#### MTGJSON Version: 4.3.2

https://mtgjson.com/json/APC.json

#### Description of Bug:

I don't systematically check these, I just have some regexps to clean up split card foreign names as they had issues on gatherer, and I noticed that it's flipped backwards to what it should be (and from what v3 had).

```
            "name": "Life",
            "foreignData": [
                {
                    "language": "Spanish",
                    "name": "Vida"
                },
                {
                    "language": "Portuguese (Brazil)",
                    "name": "Morte"
                }
            ],
```

```
            "name": "Death",
            "foreignData": [
                {
                    "language": "Spanish",
                    "name": "Muerte"
                },
                {
                    "language": "Portuguese (Brazil)",
                    "name": "Vida"
                }
            ],
```

It's actually a more systematic problem, as [Apocalypse was apparently printed in a lot of languages](https://magic.wizards.com/en/game-info/products/card-set-archive/apocalypse), but Gatherer and Scryfall just list small random subset. I can't even find any scans of that online.

And I doubt it's just this one card in one set.

Probably a fairly low priority thing overall, depending on scope of this.

**Comment by ZeldaZach** [comment]
This seems like an upstream issue as all translations come from SF. cc: @csuhta

**Comment by taw** [comment]
Assault // Battery is reversed in multiple translations. I'm sure there's more, since I keep running into them without even trying.

**Comment by csuhta** [comment]
Fixed all APC Portuguese split cards upstream
