### ISSUE TITLE
Aftermath cards should have layout aftermath not layout split

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#301]
#### Description of Bug:
It worked this way in v3. They don't look the same, and they don't work the same according to rules.

This information can be reverse engineered, but it needs layout, card's rules text, and then finding the other side and and checking that side's rules text, so it's quite awkward.

**Comment by ZeldaZach** [comment]
Gonna need more opinions to make a change to how I'm handling it right now.

However, as I've said in the past, V4 != V3 and we made changes we thought would improve the data set.

**Comment by silasary** [comment]
As I have previously mentioned, this change would be very useful for image
processing

>
