### ISSUE TITLE
S99 release date seems wrong

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#302]
#### MTGJSON Version: 4.3.2

https://mtgjson.com/json/S99.json

#### Description of Bug:

`"releaseDate": "1999-07-01"`

[Wiki](https://mtg.gamepedia.com/Starter_1999) and v3 have it as `1999-07-12`.

[Wizards' page](http://www.wizards.com/magic/starter/starter/welcomeold2.asp) doesn't seem to list any date.

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
I'm hesitant to change this since we have no authoritative source. Someone may need to ask WotC on Twitter or something

**Comment by taw** [comment]
I tried to do a quick sanity check based on days of the week, but while now it's always Friday, it wasn't like that back then:

* lea - 1993-08-05 - Thu
* leb - 1993-10-04 - Mon
* 2ed - 1993-12-01 - Wed
* ced - 1993-12-10 - Fri
* cei - 1993-12-10 - Fri
* arn - 1993-12-17 - Fri
* pdrc - 1994-01-01 - Sat
* atq - 1994-03-04 - Fri
* 3ed - 1994-04-01 - Fri
* leg - 1994-06-01 - Wed
* drk - 1994-08-08 - Mon
* fem - 1994-11-01 - Tue
* plgm - 1995-01-01 - Sun
* pmei - 1995-01-01 - Sun
* 4ed - 1995-04-01 - Sat
* ice - 1995-06-01 - Thu
* chr - 1995-07-01 - Sat
* hml - 1995-10-01 - Sun
* all - 1996-06-10 - Mon
* rqs - 1996-06-10 - Mon
* parl - 1996-08-02 - Fri
* pcel - 1996-08-14 - Wed
* mir - 1996-10-08 - Tue
* mgb - 1996-11-01 - Fri
* itp - 1996-12-31 - Tue
* vis - 1997-02-03 - Mon
* 5ed - 1997-03-24 - Mon
* por - 1997-05-01 - Thu
* van - 1997-05-01 - Thu
* ppod - 1997-05-01 - Thu
* wth - 1997-06-09 - Mon
* ppre - 1997-10-04 - Sat
* tmp - 1997-10-14 - Tue
* sth - 1998-03-02 - Mon
* pjgp - 1998-06-01 - Mon
* exo - 1998-06-15 - Mon
* p02 - 1998-06-24 - Wed
* ugl - 1998-08-11 - Tue
* palp - 1998-09-01 - Tue
* usg - 1998-10-12 - Mon
* ath - 1998-11-01 - Sun
* ulg - 1999-02-15 - Mon
* 6ed - 1999-04-21 - Wed
* ptk - 1999-05-01 - Sat
* uds - 1999-06-07 - Mon
* s99 - 1999-07-12 - Mon
* pgru - 1999-07-12 - Mon
* pwor - 1999-08-04 - Wed
* pwos - 1999-09-04 - Sat
* mmq - 1999-10-04 - Mon
* brb - 1999-11-12 - Fri
* psus - 1999-12-01 - Wed
* pfnm - 2000-02-01 - Tue
* pelp - 2000-02-05 - Sat
* nem - 2000-02-14 - Mon
* s00 - 2000-04-24 - Mon
* pcy - 2000-06-05 - Mon
* btd - 2000-10-01 - Sun
* inv - 2000-10-02 - Mon
* pls - 2001-02-05 - Mon
* 7ed - 2001-04-11 - Wed
* pmpr - 2001-05-01 - Tue
* apc - 2001-06-04 - Mon
* ody - 2001-10-01 - Mon
* dkm - 2001-12-01 - Sat
* tor - 2002-02-04 - Mon
* jud - 2002-05-27 - Mon
* ons - 2002-10-07 - Mon
* lgn - 2003-02-03 - Mon
* scg - 2003-05-26 - Mon
* prel - 2003-07-26 - Sat
* 8ed - 2003-07-28 - Mon
* mrd - 2003-10-02 - Thu
* dst - 2004-02-06 - Fri
* 5dn - 2004-06-04 - Fri
* chk - 2004-10-01 - Fri
* unh - 2004-11-20 - Sat
* bok - 2005-02-04 - Fri
* sok - 2005-06-03 - Fri
* 9ed - 2005-07-29 - Fri
* rav - 2005-10-07 - Fri
* p2hg - 2005-12-09 - Fri
* pgtw - 2006-01-01 - Sun
* gpt - 2006-02-03 - Fri
* pcmp - 2006-03-18 - Sat
* dis - 2006-05-05 - Fri
* csp - 2006-07-21 - Fri
* cst - 2006-07-21 - Fri
* tsb - 2006-10-06 - Fri
* tsp - 2006-10-06 - Fri
* hho - 2006-12-31 - Sun
* plc - 2007-02-02 - Fri
* ppro - 2007-02-09 - Fri
* pgpx - 2007-02-24 - Sat
* fut - 2007-05-04 - Fri
* 10e - 2007-07-13 - Fri
* pmgd - 2007-07-14 - Sat
* psum - 2007-07-21 - Sat
* me1 - 2007-09-10 - Mon
* lrw - 2007-10-12 - Fri
* evg - 2007-11-16 - Fri
* mor - 2008-02-01 - Fri
* plpa - 2008-02-01 - Fri
* p15a - 2008-04-01 - Tue
* shm - 2008-05-02 - Fri
* eve - 2008-07-25 - Fri
* drb - 2008-08-29 - Fri
* me2 - 2008-09-22 - Mon
* pwpn - 2008-10-01 - Wed
* ala - 2008-10-03 - Fri
* dd2 - 2008-11-07 - Fri
* con - 2009-02-06 - Fri
* ddc - 2009-04-10 - Fri
* arb - 2009-04-30 - Thu
* m10 - 2009-07-17 - Fri
* v09 - 2009-08-28 - Fri
* hop - 2009-09-04 - Fri
* me3 - 2009-09-07 - Mon
* zen - 2009-10-02 - Fri
* ddd - 2009-10-30 - Fri
* h09 - 2009-11-20 - Fri
* wwk - 2010-02-05 - Fri
* dde - 2010-03-19 - Fri
* roe - 2010-04-23 - Fri
* dpa - 2010-06-04 - Fri
* arc - 2010-06-18 - Fri
* m11 - 2010-07-16 - Fri
* v10 - 2010-08-27 - Fri
* ddf - 2010-09-03 - Fri
* som - 2010-10-01 - Fri
* pd2 - 2010-11-19 - Fri
* me4 - 2011-01-10 - Mon
* mbs - 2011-02-04 - Fri
* ddg - 2011-04-01 - Fri
* nph - 2011-05-13 - Fri
* cmd - 2011-06-17 - Fri
* m12 - 2011-07-15 - Fri
* v11 - 2011-08-26 - Fri
* ddh - 2011-09-02 - Fri
* isd - 2011-09-30 - Fri
* pd3 - 2011-11-18 - Fri
* dka - 2012-02-03 - Fri
* ddi - 2012-03-30 - Fri
* avr - 2012-05-04 - Fri
* pc2 - 2012-06-01 - Fri
* m13 - 2012-07-13 - Fri
* v12 - 2012-08-31 - Fri
* ddj - 2012-09-07 - Fri
* rtr - 2012-10-05 - Fri
* cm1 - 2012-11-02 - Fri
* gtc - 2013-02-01 - Fri
* ddk - 2013-03-15 - Fri
* pwcq - 2013-04-06 - Sat
* dgm - 2013-05-03 - Fri
* mma - 2013-06-07 - Fri
* m14 - 2013-07-19 - Fri
* v13 - 2013-08-23 - Fri
* ddl - 2013-09-06 - Fri
* ths - 2013-09-27 - Fri
* c13 - 2013-11-01 - Fri
* bng - 2014-02-07 - Fri
* ddm - 2014-03-14 - Fri
* jou - 2014-05-02 - Fri
* md1 - 2014-05-30 - Fri
* cns - 2014-06-06 - Fri
* vma - 2014-06-16 - Mon
* cp1 - 2014-07-18 - Fri
* m15 - 2014-07-18 - Fri
* v14 - 2014-08-22 - Fri
* ddn - 2014-09-05 - Fri
* ktk - 2014-09-26 - Fri
* c14 - 2014-11-07 - Fri
* dd3_dvd - 2014-12-05 - Fri
* dd3_evg - 2014-12-05 - Fri
* dd3_gvl - 2014-12-05 - Fri
* dd3_jvc - 2014-12-05 - Fri
* ugin - 2015-01-17 - Sat
* frf - 2015-01-23 - Fri
* cp2 - 2015-01-24 - Sat
* ddo - 2015-02-27 - Fri
* dtk - 2015-03-27 - Fri
* tpr - 2015-05-06 - Wed
* mm2 - 2015-05-22 - Fri
* cp3 - 2015-07-17 - Fri
* ori - 2015-07-17 - Fri
* v15 - 2015-08-21 - Fri
* ddp - 2015-08-28 - Fri
* bfz - 2015-10-02 - Fri
* exp - 2015-10-02 - Fri
* c15 - 2015-11-13 - Fri
* ogw - 2016-01-22 - Fri
* ddq - 2016-02-26 - Fri
* soi - 2016-04-08 - Fri
* w16 - 2016-04-08 - Fri
* ema - 2016-06-10 - Fri
* emn - 2016-07-22 - Fri
* v16 - 2016-08-19 - Fri
* cn2 - 2016-08-26 - Fri
* ddr - 2016-09-02 - Fri
* kld - 2016-09-30 - Fri
* mps - 2016-09-30 - Fri
* c16 - 2016-11-11 - Fri
* pca - 2016-11-25 - Fri
* aer - 2017-01-20 - Fri
* mm3 - 2017-03-17 - Fri
* dds - 2017-03-31 - Fri
* w17 - 2017-04-15 - Sat
* akh - 2017-04-28 - Fri
* mp2 - 2017-04-28 - Fri
* cma - 2017-06-09 - Fri
* e01 - 2017-06-16 - Fri
* hou - 2017-07-14 - Fri
* c17 - 2017-08-25 - Fri
* xln - 2017-09-29 - Fri
* ddt - 2017-11-10 - Fri
* ima - 2017-11-17 - Fri
* e02 - 2017-11-24 - Fri
* v17 - 2017-11-24 - Fri
* ust - 2017-12-08 - Fri
* rix - 2018-01-19 - Fri
* a25 - 2018-03-16 - Fri
* ddu - 2018-04-06 - Fri
* dom - 2018-04-27 - Fri
* bbd - 2018-06-08 - Fri
* cm2 - 2018-06-08 - Fri
* ss1 - 2018-06-15 - Fri
* gs1 - 2018-06-22 - Fri
* m19 - 2018-07-13 - Fri
* c18 - 2018-08-10 - Fri
* grn - 2018-10-05 - Fri
* med - 2018-10-05 - Fri
* gk1 - 2018-11-02 - Fri
* gnt - 2018-11-16 - Fri
* puma - 2018-12-07 - Fri
* uma - 2018-12-07 - Fri
* rna - 2019-01-25 - Fri

Probably need to ask them, if they even know. There weren't any prereleases, and this set wasn't originally legal in any format.

**Comment by ZeldaZach** [comment]
Closing as I'm not planning on fixing via my side
