### ISSUE TITLE
Artists for some DFCs listed twice as "X & X"

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#303]
#### MTGJSON Version: 4.3.2

https://mtgjson.com/json/RIX.json

#### Description of Bug:

There are entries like (each of those 4 twice):

```
      "artist": "Svetlin Velinov & Svetlin Velinov",
      "artist": "Titus Lunter & Titus Lunter",
      "artist": "Victor Adame Minguez & Victor Adame Minguez",
      "artist": "Bastien L. Deharme & Bastien L. Deharme",
```

It doesn't seem to affect any other sets. All other "X & Y" are actually two different names.

**Comment by ZeldaZach** [comment]
Looks like an oversight on my part. I"ll see about fixing this later.
