### ISSUE TITLE
Multiple cards with same multiverseid.

### ISSUE THREAD

**Issue by AdamLeBlanc** [mtgjson/mtgjson#303]
Hi,

There are two printings of "Nalathni Dragon" listed with the same multiverseid, which can cause problems for some applications. Not sure if this is by design of a bug.

**Comment by gwax** [comment]
Are both "Nalathni Dragon" cards showing up in the same set or are they from different sets but showing the same multiverseid. Either way, this is likely a bug.

However, there are legitimate cases where two "cards" may have the same multiverseid: split, flip, transform, and aftermath cards all list separate "card" entities for each half but share a single multiverseid.

**Comment by ZeldaZach** [comment]
This should be addressed in v4
