### ISSUE TITLE
"AEther" cards missing mciNumber

### ISSUE THREAD

**Issue by zombor** [mtgjson/mtgjson#304]
Looks like a bunch (maybe all?) of cards that have "Aether" in their name are missing `mciNumber` fields. Especially troublesome for older cards that also don't have `number`.

**Comment by zombor** [comment]
Also, these are missing the `mciNumber`:

 - Every card in mirage
 - Most (all?) alternate art cards (urza's lands, fallen empires, etc)
 - Cards that have multiple versions (planeshift with alternate arts)

**Comment by gwax** [comment]
The urza lands (or anything with alternate art in a single set) are a different problem. I will open a separate issue for that matter.
