### ISSUE TITLE
boosterV3 field wrong for 4 sets

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#304]
#### MTGJSON Version: 4.3.2

https://mtgjson.com/json/NEM.json
https://mtgjson.com/json/ME1.json
https://mtgjson.com/json/MED.json
https://mtgjson.com/json/TSB.json

#### Description of Bug:

NEM and ME1 should have booster field, they were regular booster sets.

MED and TSB shouldn't have boosters. TSB is included as one card in sheets of another set, and MED sort of too, except in only weird special edition's special boosters. Masterpiece sets don't have booster field in mtgjson otherwise.

I suspect MED ended up with ME1's boosters during v3 migration due to set code switch. TSB fake boosters was a v3 bug. No idea how NEM issue happened.

Links:

* https://mtg.gamepedia.com/Nemesis
* https://mtg.gamepedia.com/Masters_Edition
* https://mtg.gamepedia.com/Guilds_of_Ravnica/Mythic_Edition
* https://mtg.gamepedia.com/Time_Spiral#Timeshifted

**Comment by ZeldaZach** [comment]
I'll get this fixed up later
