### ISSUE TITLE
Modern Horizons cards are missing "future" legality

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#307]
The current spoilers from Modern Horizons are missing the "future" legality that cards from the WAR spoiler have.

**Comment by ZeldaZach** [comment]
From what I understand, "future" means it will be legal in the _next_ standard, after rotation. MH will skip standard, so it won't get this tag. Correct me if I'm wrong please.

cc: @csuhta

**Comment by KingSupernova31** [comment]
The documentation is completely wrong about "future". It claims that it's a properly value, whereas the files have it as a key. This was already discussed months ago, but apparently was never fixed.
