### ISSUE TITLE
Don't cache failed downloads

### ISSUE THREAD

**Issue by fenhl** [mtgjson/mtgjson#313]
I'm trying to rebuild all sets right now (see my [rebuild](https://github.com/fenhl/mtgjson/tree/rebuild) branch) but it's basically impossible since the cache system seems to save failed downloads. I suspect that not doing this would make the process much easier, but I don't know how to do this.

**Comment by gwax** [comment]
Apparently, in WotC's infinite genius, when Gatherer has a Server Error, it returns an error page with a 200 status code.

**Comment by gwax** [comment]
It's ok, they're nice enough to put "Server Error" in the page title, so I can work around it.
