### ISSUE TITLE
Goblin Test Pilot and Monkeys

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgjson#314]
Goblin Test Pilot is now a Pilot in addition to its other types.

Tree Monkey, Zodiac Monkey and Ravenous Baboons are Monkeys, no longer Apes.

(Monkey Cage is correct, though; it makes Monkeys now.)

**Comment by ancestral** [comment]
Please see the Kaladesh Update Bulletin from September 30, 2016: http://magic.wizards.com/en/articles/archive/feature/kaladesh-update-bulletin-2016-09-30

**Comment by fenhl** [comment]
All of these are correct on Gatherer and should be automatically fixed by the [full rebuild](https://github.com/fenhl/mtgjson/tree/rebuild). As such, this issue is blocked by #313.

**Comment by gwax** [comment]
This has been resolved.
