### ISSUE TITLE
MPS Set Code & Card Number Conflict

### ISSUE THREAD

**Issue by tritoch** [mtgjson/mtgjson#315]
The new Amonkhet Masterpieces have the set code MPS, which is the same as the Kaladesh Masterpieces.  Both sets start card numbers at 001.  So we now have a duplicate MPS\001

Propose we recode the new MPS set as MP2.

Other options: Add a 'relatedBlock' key to all cards in MPS sets, or change the card number to reflect the set it's contained in.

**Comment by Garbee** [comment]
IMO we shouldn't go cluttering the code space like this. If they're doing this now, then foreseeably they are going to continue just using "MPS" in the future. Which means we'd end up with MP2/MP3/MP4/etc. until they stop. Which could collide in the future with anything WoTC decides to do that then hits the same naming convention. We'd be better off doing a combined code like, `MPS-AER` to signify the Masterpieces from Aether Revolt. Rinse and repeat for future sets. That way all the MPS sets are distinct but still spaced out.

**Comment by fenhl** [comment]
Since we use set codes like `DD3_EVG` for *Duel Decks Anthology*, we should use `MPS_AKH` here.

**Comment by thg2k** [comment]
The first time that masterpiece series appeared, though not named as such, was with BFZ and they were named "Zendikar Expeditions", with code EXP, but it could also be retrofitted as MPS_BFZ. On the card the printed code was "EXP" anyway so MPS_BFZ could only be an alias.

For Kaladesh Inventions the code used on the Gatherer is MPS_KLD, while for Amonkhet Invocations the code on the Gatherer is MPS_AKH, which makes both of them pretty much official.

**Comment by Garbee** [comment]
Zendikar Expeditions are just that, Expeditions. The "Masterpieces" are officially a continuation of the Expeditions experiment but with a wider focus on what they can be. They should not ever be referenced as 'Masterpeices' in any way unless Wizards oracle's them into that. While they do reference when announcing Masterpieces "like Zendikar Expeditions" it's just that, "like". They are not a part of the same family inherently as a data structure.

**Comment by gwax** [comment]
As far as I can tell, these are currently managed as MPS_AKH.

I do not think this is an issue anymore

Please reopen with additional details if I am incorrect.
