### ISSUE TITLE
Set legality incorrect

### ISSUE THREAD

**Issue by zhelu** [mtgjson/mtgjson#316]
Commander 2016 is legal in legacy, vintage, and commander.
Example: Atraxa

AER cards should be standard legal.
Example: Heart of Kiran

**Comment by zhelu** [comment]
This is an issue in at least version 3.8.2.

**Comment by mdurao** [comment]
New expansion should also be Standard!

**Comment by bakert** [comment]
Still seeing these commander cards showing as not legal in Legacy:

Armory Automaton
Boompile
Charging Cinderhorn
Curse of Vengeance
Entrapment Maneuver
Evolutionary Escalation
Frenzied Fugue
Goblin Spymaster
Grave Upheaval
Migratory Route
Parting Thoughts
Primeval Protector
Runehorn Hellkite
Treacherous Terrain

**Comment by bakert** [comment]
The Commander 2016 cards are fixed for sure. Not sure about the rest. Please ignore previous comment – I had not updated our prod systems to 3.10.0

**Comment by ZeldaZach** [comment]
If you find incorrect set legalities, please open another ticket defining what the issues are and we'll gladly fix them :)
