### ISSUE TITLE
New Card Layout - Aftermath

### ISSUE THREAD

**Issue by tritoch** [mtgjson/mtgjson#317]
The new set Amonkhet has a card type similar to `split` but the 'Left' half of the card is rotated so it's now more 'Top'.  The mechanic is called `Aftermath`

http://i.imgur.com/GwMtUmE.png

**Comment by KingSupernova31** [comment]
Why is there a new layout for the split cards from Amonkhet? They work the exact same way as other split cards, they just look slightly different. It would make more sense if they still used the normal "split" layout.

**Comment by dgant** [comment]
Here's one example: For ComboDeck I automatically rotate and crop card art from scans based on the MTGJson layout. Flip, split, and aftermath cards all require distinct cropping math.
