### ISSUE TITLE
Missing cards from Happy Holidays

### ISSUE THREAD

**Issue by vanyamil** [mtgjson/mtgjson#318]
Goblin Sleigh Ride and Thopter Pie Network (Happy Holidays promo cards for 2015 and 2016) are missing in the database.

**Comment by Garbee** [comment]
These aren't even playable nor generally available. Why should they be included in the DB?

**Comment by dgant** [comment]
Because anyone who builds on top MTGJSON and wants to include these cards will have to re-implement them on their own. Anecdotally, ComboDeck users search for holiday/fun cards fairly often.

You can buy Thopter Pie Network for $23 on TCGPlayer.

**Comment by vanyamil** [comment]
For example, I'm running stats on the Magic Bracket using this DB and I
just can't do anything about those two cards because both Cards-x and
Sets-x stop at 2014 for pHHO.

Ivan

**Comment by fenhl** [comment]
Goblin Sleigh Ride has been added now. Thopter Pie Network is still missing.

**Comment by ZeldaZach** [comment]
Added in V4 (HHO)
