### ISSUE TITLE
Should multipart cards have multiple Gatherer multiverseids?

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#318]
#### Description of Bug:

This seems to apply to all multipart cards. So for example: 

* https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=20579
* https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=20580

Presumably the first ID is meant to be for first part of the card, and the second ID for the second part of the card. Gatherer displays same stuff regardless of which ID you use for the query.

Is it worth trying to figure out which one was meant for what? Or include both somehow?

Gatherer at some point changed their mind and new split cards have only one ID:

* https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430845
* https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=457368

It's not a huge deal for me, `multiverseid` just changed for same card while I was updating deck database, and I noticed this.

**Comment by ZeldaZach** [comment]
There's no guarantee in ordering of multiverseIDs for the sides (at least, I haven't coded one in). I'm not sure if this is something that needs to be looked into, but if you have suggestions I'm open to them

**Comment by taw** [comment]
From examples I've seen they were always consecutive numbers, so presumably left side would have earlier id than right part by one.

Maybe just pick whichever one as canonical in some consistent way so it stays the same between mtgjson updates (either first or last), and then stuff the other as `other_multiverseid`, in case there's some use for cross-referencing?

[The obvious problem card](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74358) seems to have only one not five.

**Comment by ZeldaZach** [comment]
I've found counter examples in the past that do not have consecutive numbers. As such, I can't safely add it without introducing issues... not sure if it's worth it honestly as the system returns the same, and people really _shouldn't_ be using gatherer for development purposes 🤷‍♂️

**Comment by taw** [comment]
4.4.0 now flipped one card from `"multiverseid": 20582` to `"multiverseid": 20581` (both are two sides of same card).
It would be nice if they at least got stable at some point.

**Comment by ZeldaZach** [comment]
That's a flip upstream then, as my methods aren't race-time bound. I'm inclined to no-fix this for the time being, but I'll bring it up with upstream to see if they have any interest.
