### ISSUE TITLE
Some promo cards missing artists

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#319]
~[I'll just link here as that's mtgjson data](http://mtg.wtf/artist/_).~

Links in comment below.

**Comment by taw** [comment]
Well, mtg.wtf fixed it locally, so the link no longer works. The cards and their corrected artists are in Media Inserts set:

* [Alhammarret, High Arbiter](http://mtg.wtf/card?q=e%3Ambp+Alhammarret,+High+Arbiter) - Richard Wright
* [Dwynen, Gilt-Leaf Daen](http://mtg.wtf/card?q=e%3Ambp+Dwynen,+Gilt-Leaf+Daen)- Steven Belledin
* [Hixus, Prison Warden](http://mtg.wtf/card?q=e%3Ambp+Hixus,+Prison+Warden) - Magali Villenueve
* [Kothophed, Soul Hoarder](http://mtg.wtf/card?q=e%3Ambp+Kothophed,+Soul+Hoarder) - Tianhua X
* [Pia and Kiran Nalaar](http://mtg.wtf/card?q=e%3Ambp+Pia+and+Kiran+Nalaar) - Tyler Jacobson

**Comment by ZeldaZach** [comment]
Addressed in V4
