### ISSUE TITLE
Stop using base set size file

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson#319]
Can easily infer newer sets

**Comment by ZeldaZach** [comment]
https://scryfall.com/search?q=set%3AWAR+is%3Abooster

**Comment by ZeldaZach** [comment]
https://scryfall.com/search?q=set%3AWAR+is%3Abooster+unique%3Aprints gets the correct value

`set: ${SETCODE} is:booster unique:prints` Easily callable via the api `https://api.scryfall.com/cards/search?order=set&q=set:WAR%20is:booster%20unique:prints`

**Comment by ZeldaZach** [comment]
Fixed in e02a763241b472a56c9c19560f18e44387494e53

**Comment by silasary** [comment]
Hate to do this to you, but that number isn't always right.
See CN2 with foil Kaya, and War of the Spark with 36 extra Japanese walkers

>

**Comment by ZeldaZach** [comment]
I ran a regression test against scryfall's count and manually put corrections in for the ones they don't agree with me on. See https://github.com/mtgjson/mtgjson/blob/master/mtgjson4/resources/base_set_sizes.json. Thanks for the concern, tho. Appreciate the oversight :)
