### ISSUE TITLE
Planeswalker Loyalty Integer, needs String

### ISSUE THREAD

**Issue by dev-id** [mtgjson/mtgjson#320]
Currently planeswalker loyalty is an integer, needs to be changed to string to store `X` for the new planeswalker: http://mythicspoiler.com/akh/cards/nissastewardofelements.jpg

**Comment by tritoch** [comment]
AKH.json: `"loyalty":null,"name":"Nissa, Steward of Elements"`

**Comment by ancestral** [comment]
Nissa should have a loyalty of `X`.

**Comment by skwerlman** [comment]
@ancestral maybe don't @-mention random people?

**Comment by Garbee** [comment]
@ancestral On top of not mentioning people when not needed, there also is no need to comment with information already contained within the issue/PR. It just creates noise for people watching the tracker.

Thank you.

**Comment by fenhl** [comment]
I think that for backwards compatibility, we should keep loyalty as an integer field if possible, and only use a string for X.

**Comment by ZeldaZach** [comment]
@fenhl I feel that would just be messy as it would look like a hack. In V4 I'm changing it to String for sure, but i'm not sure what we should do for now...

**Comment by fenhl** [comment]
Why would it look like a hack? JSON supporting multiple field types is a feature, not a bug.

**Comment by ZeldaZach** [comment]
If that's a thing, then I'm fine with just throwing the X as a string and keeping the field as an integer

**Comment by Garbee** [comment]
Think of how we tell this to people though in the docs, "It is an integer, except for some case it is a string". So to store this locally, we'd need to use a text-based field anyways. It seems pointless to have a value as one type except in niche cases for a given property.

Just because JSON has a feature doesn't mean it is beneficial to be used in such a way. For complete clarity to anyone using the API, keeping it as a string all the time when pulled is useful. Then, if you in your application want to handle multiple types, go ahead and do it.

**Comment by fenhl** [comment]
The example value of `4` in the docs makes this not an option without breaking compatibility.

**Comment by Garbee** [comment]
> without breaking compatibility

It was entirely compatible until Wizards decided to change what was allowed for the field. In most sane systems you can convert from `"4"` to `4` as an int losslessly and without a fuss. This is making what is provided *less* strict, which is actually more compatible not less.

**Comment by ZeldaZach** [comment]
@Garbee I do agree that it's an easy conversion, just we need to figure out the best way of doing this

**Comment by Garbee** [comment]
The best way to handle it is to just make them all strings for loyalty. That way we can handle whatever Wizards does in the future. It won't break any applications with a strict -> loose change like this unless they are very poorly developed in the first place. In which case, learning experience for those developers.

Now, developers may be casting them to int for storage. In which case "X" will become 0 in most sane systems. So that's a minor bug but it would still match what we currently provide that they'd need to change anyways. So if they haven't updated yet to work around this, they'd get a nice notice error that the conversion happened and they need to update their stuff to handle it from the language.

Also it's a good warning to any future fields, just use strings. Wizards will find a way to twist everything to fuck up any level of structured data. It's their specialty. They hate developers.

**Comment by ZeldaZach** [comment]
I can agree that a conversion int&rarr;string is best. We should include a note in the changelog to identify this change, but otherwise I'm fine moving forward with it

**Comment by fenhl** [comment]
I strongly disagree with just making everything strings. The tools JSON provides to structure data are in most cases easier to use than string parsing. Even statically/strongly typed languages have ways to deal with this.

**Comment by Garbee** [comment]
Consistency should win here. Having this field be either one of two types is inconsistent with how we handle everything else. Collector numbers are strings. Why? Cards can have A/B spllits. Power/Toughness, are strings. Why? `1+*`, `*`, etc. So why for this one case should we now decide that one field can be one of two given types? It's inconsistent, plain and simple. So either we go dual-types everywhere, or we keep consistency and make loyalty a string.

**Comment by ancestral** [comment]
I also agree number -> string is the way to go for loyalty. It’s just like card numbers; they aren’t always integers any more.

**Comment by taw** [comment]
Using `"X"` for Nissa is a much better temporary solution than having `null`, even if all others are numbers.

Long term it's same story as P/T - vast majority of cards will have integer there, but no all.

**Comment by gwax** [comment]
Pretty sure this has to be changed to string.

It may, unfortunately, break some things downstream but WotC is, effectively, forcing our hand.

**Comment by silasary** [comment]
Note that (At least for .NET based languages), putting a null could be as equally breaking as a string. (Integers are not a nullable type)

**Comment by Garbee** [comment]
@silasary This is why everything would need to be converted to string at once. Not a split where they a int's where possible and string otherwise. For 3.x, it would mean initial breakage for consumers. But, that's a necessity to get the data correct and in an usable format.

**Comment by fenhl** [comment]
It is absolutely not a necessity, given JSON's aforementioned capability of supporting multiple types. For example, a quick search gives [this answer for .NET](https://stackoverflow.com/a/17923802).

**Comment by Garbee** [comment]
And that's only assuming people already have such a system in place. If people are stuck switching code anyways, should it be a one-time thing to go to string or should they handle dual-types now and then later move to strings for 4.x alone?

I'm just considering how much time needs to be wasted in this. It should be as little as possible. One type is the way to go.

**Comment by fenhl** [comment]
That's a good point, actually: we will need a major version bump for this either way.

**Comment by Garbee** [comment]
Is there a documented system for the versioning? I don't think we need to include type changes alone with needing a major. This is an API built to work against a dataset that can change underneath at any moment. That needs to be understood and conveyed to developers. Be prepared to types to change occasionally, with good warnings in the release notes when it happens.

**Comment by fenhl** [comment]
I'm assuming [semantic versioning](http://semver.org/) with [the documentation](https://mtgjson.com/documentation.html) as the API. If this is not the case, it should be mentioned explicitly on the website.

**Comment by Garbee** [comment]
The versioning system isn't documented. So we need to make a versioning system. No one should ever assume SemVer. That is a very stringent thing to work against and even people who do claim to support it falter. As it is, currently no guarantees on the API consistency are made so it's open to change at any point as-needed. Quite possibly exactly why one hasn't been done yet is cases just like this.

**Comment by gwax** [comment]
I don't like breaking changes without a major bump. I say we milestone this for 4.0 and see if there are some other schema changes we'd like to lump in.

**Comment by taw** [comment]
@gwax For 4.0 changes, this inconsistency:

      "colorIdentity": ["G"],
      "colors": ["Green"],

should get fixed. I'd say `"G"` everywhere is more natural.

**Comment by fenhl** [comment]
@taw: Already reported. mtgjson/mtgjson4#56

**Comment by ZeldaZach** [comment]
Addressed
