### ISSUE TITLE
Missing set DDS (Duel Decks: Mind vs Might)

### ISSUE THREAD

**Issue by eddie-g** [mtgjson/mtgjson#321]
Please add when possible, thanks.

**Comment by tooomm** [comment]
While it is added now, it has the wrong date (year)! Should be **2017**-03-31
<br>

>Keep an eye out for Duel Decks: Mind vs. Might to hit the shelves at your local game store on March 31!

http://magic.wizards.com/en/articles/archive/feature/duel-decks-mind-vs-might-2017-03-20
