### ISSUE TITLE
AKH  Amonketh set available on gatherer

### ISSUE THREAD

**Issue by nicho92** [mtgjson/mtgjson#322]
http://gatherer.wizards.com/Pages/Search/Default.aspx?set=[%22Amonkhet%22]

Thanks !

**Comment by ancestral** [comment]
I would love to have this card data!

**Comment by marinatedpork** [comment]
Me too! Is there anything I can do to help get a PR going to add the JSON?

**Comment by lsmoura** [comment]
They are on the website already... I'll publish an update next week.

**Comment by ancestral** [comment]
Which web site are you taking about?

**Comment by lsmoura** [comment]
mtgjson.com?

**Comment by lsmoura** [comment]
if you need the repository for something, please checkout the branch `sergio/AKH`. it has the json files there as well.
