### ISSUE TITLE
Only update Setlist.json set meta data date field if data other than prices change.

### ISSUE THREAD

**Issue by jmcsmith** [mtgjson/mtgjson#322]
With the addition of prices, and potentially automatic weekly builds (to update prices), only update the meta data date field if data other than prices has changed.
With that said maybe add an additional field in meta data that tracks when the last time the prices were updated.

This will allow people to either update when prices change or only when card data changes if they are not including prices or using their own sources.

**Comment by ZeldaZach** [comment]
can easily add `priceDate` that will update weekly, and `date` will only update if a diff of OLD and NEW show more than just price changes... will be tricky to add in, as I'll need older builds to confirm, but I can think about it
