### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by jenjia** [mtgjson/mtgjson#323]
I am trying to build DDS (Duel Decks: Mind vs. Might):
_node build/buildSet.js DDS_

But I keep getting this error:

_Error ripping: DDS (Duel Decks: Mind vs. Might)
Error: ENOENT: no such file or directory, open '/Users/username/Documents/folder/mtgjson/json/AKH.json'
    at Error (native)_

And when I try to build AKH, I get that I don't have the folder DDS.json, I am in a loop of same error.

Any advice? thx

**Comment by gwax** [comment]
This is resolved as of `master` (and a couple releases back too). The issue is that there was no definition for AKH at the time of this Issue but the set could be found in gatherer.
