### ISSUE TITLE
add spoiler flag

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson#325]
>**Could you set a field on MTGJson to indicate if a SET is still in "Spoiler" time or full?** We could filter on it then and not show it on the list
>
>Source: https://github.com/dr4fters/dr4ft/issues/432#issuecomment-485267172

Also needs documentation then once added.

**Comment by ZeldaZach** [comment]
Will consider after 4.4.0 release

**Comment by ZeldaZach** [comment]
Thought about it some more: In my opinion there is no real need for such a thing. The following query can detect if a set is fully released or not:

`if releaseDate > NOW then spoiler is true`

I'd recommend dr4ft to modify their code to accommodate for this
