### ISSUE TITLE
Sideboard is a copy of mainboard

### ISSUE THREAD

**Issue by DJCatBlitz** [mtgjson/mtgjson#326]
MTGJSON Version: 4.2.3

Description of Bug:
I checked most of the decks in AllDeckFiles.zip. In all cases the sideboard is a copy of the mainboard

**Comment by ZeldaZach** [comment]
Sounds like an upstream thing. cc: @taw

**Comment by taw** [comment]
Yeah, the script exporting to https://github.com/taw/magic-preconstructed-decks-data had exactly this bug. Script fixed and new data uploaded now.
