### ISSUE TITLE
AKH Planeswalker Decks exclusive cards & Standard legalities

### ISSUE THREAD

**Issue by bradleyjx** [mtgjson/mtgjson#333]
The eight AKH cards found solely in Planeswalker decks are not listed as being legal in Standard.

Liliana, Death Wielder
Liliana's Influence
Desiccated Naga
Tattered Mummy

Gideon, Martial Paragon
Gideon's Resolve
Companion of the Trials
Graceful Cat

There may also be an unexposed issue revolving around #331 as well - the ten taplands are were printed in OGW/SOI, which means that they're implicitly legal due to that. When those sets rotate in October, are these cards explicitly-legal due to their inclusion in AKH, or will they fall off?

**Comment by Garbee** [comment]
@bradleyjx They are printed in AKH in the DeckBuilder Toolkits. Therefore they are legal until AKH rotates out. Just like any other AKH card (unless banned/restricted beforehand.)

Those ones that aren't listed as legal are possibly issues on Gatherer's side of things at the time the data was scraped. That can be cleaned up when the next scrape happens.

**Comment by fenhl** [comment]
This appears to be fixed now.
