### ISSUE TITLE
Aid the Fallen is missing a blank after 'Choose one or both'

### ISSUE THREAD

**Issue by DJCatBlitz** [mtgjson/mtgjson#334]
#### Description of Bug:
Aid the Fallen is missing a blank after 'Choose one or both'.
All other cards with this template have this blank

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
This is fixed upstream

**Comment by DJCatBlitz** [comment]
Umezawa's Charm and Twisted Reflection have the same problem
