### ISSUE TITLE
Various cards including Quirion Ranger do not have colorIdentity information

### ISSUE THREAD

**Issue by bakert** [mtgjson/mtgjson#334]
Specifically:

1996 World Champion (WUBRG)
Camouflage (G)
False Orders (R)
Fraternal Exaltation (U)
Nalathni Dragon (R)
Natural Selection (G)
Proposal (W)
Quirion Ranger (G)
Raging River (R)
Sewers of Estark (B)
Shichifukujin Dragon (R)
Splendid Genesis (G)
Windseeker Centaur (R)

**Comment by gwax** [comment]
As far as I can tell, these cards have color identities now.

This must have been fixed at some point in the past.

Please reopen with additional details if I am in error.
