### ISSUE TITLE
War of the Spark Mythic Edition cards lack multiverseids

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#335]
#### Description of Bug:

* https://mtgjson.com/json/MED.json
* https://gatherer.wizards.com/Pages/Search/Default.aspx?set=[%22War+of+the+Spark+Mythic+Edition%22]

Also Gatherer has it as 3 separate sets, and mtgjson as 1, but that's a judgement call.

Printed card metadata says something like `MED WS2/008` etc. - same code suggesting one set, but `/008` and being relates completely independently suggesting it's separate sets. If they keep doing this, will it be a ten year set (like MCI and v3 used to do with promos?).

Regardless of 1 vs 3, it should get multiverseids, so I can fetch correct pics etc..

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
Multiverse IDs added upstream
