### ISSUE TITLE
"Placed" syntax deprecated

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgjson#335]
`placed` is no longer used for describing the act of adding counters to objects. It is only `put`. (Gatherer confirms the change; Hardened Scales is an excellent example.)

The following cards use `placed` incorrectly (should be `put`):

Corpsejack Menace
Fathom Mage
Hardened Scales
Flourishing Defenses
Tatterkite
Melira's Keepers
Melira, Sylvok Outcast
Primal Vigor
Bloodcrazed Hoplite
Enduring Scalelord

**Comment by silasary** [comment]
Duplicate of #327, which was fixed as part of #328.
