### ISSUE TITLE
missing space on hp - thank you section

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson#338]
No space between name and text

```
Robert Schultsfor creating and mantaining this project from 2013 to 2015. Thank you for all your work and dedication!
```

**Comment by gwax** [comment]
Looking at the site source, I see: `<li><strong>Robert Schults</strong> for creating and mantaining`...

There is, clearly, a space, so I'm going to presume this was fixed at some point in the past.

**Comment by ZeldaZach** [comment]
I fixed this a few days ago when I added the logo to the site.
