### ISSUE TITLE
Warnings while building deck data

### ISSUE THREAD

**Issue by skoogiz** [mtgjson/mtgjson#338]
#### MTGJSON Version: 4.X.X
4.4.0

#### Description of Bug:
While buildeing the decks I get blocks of warnings like this. 
```
[INFO] 2019-04-30 00:04:41,484: Finished deck Replicator
[WARNING] 2019-04-30 00:04:41,489: No match for {'name': 'Mountain', 'set_code': 's00', 'number': '30', 'foil': False, 'count': 2, 'multiverseid': 25480}
[WARNING] 2019-04-30 00:04:41,489: No match for {'name': 'Forest', 'set_code': 's00', 'number': '13', 'foil': False, 'count': 2, 'multiverseid': 25482}
[WARNING] 2019-04-30 00:04:41,489: No match for {'name': 'Swamp', 'set_code': 's00', 'number': '49', 'foil': False, 'count': 2, 'multiverseid': 25478}
[WARNING] 2019-04-30 00:04:41,490: No match for {'name': 'Giant Growth', 'set_code': 's00', 'number': '15', 'foil': False, 'count': 1, 'multiverseid': 25502}
[WARNING] 2019-04-30 00:04:41,490: No match for {'name': 'Orcish Oriflamme', 'set_code': 's00', 'number': '34', 'foil': False, 'count': 1, 'multiverseid': 25540}
[WARNING] 2019-04-30 00:04:41,490: No match for {'name': 'Rod of Ruin', 'set_code': 's00', 'number': '40', 'foil': False, 'count': 1, 'multiverseid': 25529}
[WARNING] 2019-04-30 00:04:41,491: No match for {'name': 'Soul Net', 'set_code': 's00', 'number': '46', 'foil': False, 'count': 1, 'multiverseid': 25543}
[WARNING] 2019-04-30 00:04:41,492: No match for {'name': 'Terror', 'set_code': 's00', 'number': '51', 'foil': False, 'count': 1, 'multiverseid': 25504}
[INFO] 2019-04-30 00:04:41,498: Finished deck Player A's advanced pack
```
What do they mean? Are the mentioned cards not added to the deck or are there some data missing for the cards?

If the affected deck gets incomplete maybe some more info should be added to the warning. 

Either way I think the affected deck should be mentioned in the warning.

**Comment by ZeldaZach** [comment]
This is a leftover from when I was compiling and testing the decks. I do need to fix that up at some point. Thanks for pointing out

**Comment by ZeldaZach** [comment]
Tag @taw To help fix up this: https://paste.ee/p/EJe1j (also pm'd on twitter)

**Comment by taw** [comment]
There's two issues - oversized cards and S00.
I plan to make oversized cards match v4.
S00 is, eh, not fun.

**Comment by ZeldaZach** [comment]
Just ping back whenever you're up-to-date and I'll re-work on a fix

**Comment by taw** [comment]
Oversized cards now match v4.
I think S00 is the only difference affecting precons.

**Comment by ZeldaZach** [comment]
Re-build attached, still quite a few errors @taw :

[mtgjson_2019-06-12_14.07.39.log](https://github.com/mtgjson/mtgjson/files/3282637/mtgjson_2019-06-12_14.07.39.log)

**Comment by taw** [comment]
Hmm, I thought everything except S00 was fixed already. I'll fix them for reals on next update I guess.

**Comment by taw** [comment]
I refreshed the data. I think that should solve all warnings other than S00.

**Comment by ZeldaZach** [comment]
Will re-check after Sunday's rebuild

**Comment by taw** [comment]
@ZeldaZach Is it all gone except S00?

**Comment by ZeldaZach** [comment]
Yep, look into that when you can? Closing as this isn't an issue on my side now.
