### ISSUE TITLE
Omit tcgplayerProductId from AllCards

### ISSUE THREAD

**Issue by brokentone** [mtgjson/mtgjson#339]
#### Description of Bug:
First off, thanks for the work compiling this data! While I was analyzing some cards I found that the AllCards dataset has `tcgplayerProductId` in each entry -- which isn't actually useful on the card level, only on the card + set intersection.

I noticed the following:
> Some data properties will be omitted if they have differing examples from set to set.

And I would think this property likely ought to be omitted as well.

**Comment by ZeldaZach** [comment]
MTGJSON 4.4.0 has this field omitted in AllCards. Please try updating your downloads :)
