### ISSUE TITLE
suggestion for gatherer up/down check badge in readme

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson#339]
Stumbled upon this possibility...
Do we want this online indicator (or similar) in the readme to automatically indicate if gatherer is down (and back up again) so we can get updates faster and smoother:
[![Gatherer Website](https://img.shields.io/website-up-down-green-red/http/gatherer.wizards.com.svg?label=Gatherer%20Website)](http://gatherer.wizards.com/)

It can also be customized, for example the label can easily be changed.
Found it on: www.shields.io

**Comment by Garbee** [comment]
I'm not sure what the badge would really offer. MTGJson is only updated manually when gatherer is in fact up. It really has no bearing at all on the day-to-day activity of the repository.

**Comment by tooomm** [comment]
The idea was once you see it being "down", and later back "up" again while browsing the repo or working on stuff/issues... you know that you should do some updates.
No idea if there is some other easy way to track for gatherer changes.
Maybe a reliable newsfeed from wizard?

Just an idea though. :)
