### ISSUE TITLE
Consistent File Access (using pathlib.Path instead of os.path)

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson#34]
We use both `os` and `pathlib` libraries for reading/writing files. I'd like to fix up the code to use either or. We can have a discussion on which is better here, but it seems a bit weird having two libs in that do the same thing

**Comment by fenhl** [comment]
`pathlib` is much nicer to use imo.

**Comment by ZeldaZach** [comment]
Any backing to your opinion, @fenhl ? Just looking for a justifiable claim to go one way or the other

**Comment by fenhl** [comment]
For example, this line: https://github.com/mtgjson/mtgjson-python/blob/8666ea0e10c152e97936c2440857512604e10f79/mtgjson4/mtg_http.py#L135

could be rewritten as:

```python
if (mtgjson4.mtg_storage.CACHE_DIR / 'set_mids' / f'{set_name}.txt').exists():
```

**Comment by fenhl** [comment]
Basically, `os.path` handles strings, while `pathlib.Path` objects have all the required operations as actual methods on them. Since we're on 3.6+, it is also possible to use a `pathlib.Path` instead of a `str` anywhere a path is required.

**Comment by ZeldaZach** [comment]
Sounds like a solid argument to me.

Ticket update: Move away from `os.path` -> `pathlib.Path`
