### ISSUE TITLE
Mark cards which cannot appear in boosters

### ISSUE THREAD

**Issue by asilano** [mtgjson/mtgjson#340]
I use MTGJson as a source for programatically producing booster contents; but cards which cannot appear in boosters (such as the Planeswalker deck exclusives) are not marked in any way.

I would like cards which cannot appear in boosters to carry some indication of the fact, so that I can generate a plausible booster.

An alternative fix would be to give the official set size in the set data, since the "extra" cards have collector IDs higher than the set size (for instance, Gideon, Martial Paragon is card 270 of 269).

**Comment by fenhl** [comment]
This could be consolidated with the `sheetRarity` field proposed in #364.
