### ISSUE TITLE
cards in set "CNS" have no foreignData

### ISSUE THREAD

**Issue by mike1ong** [mtgjson/mtgjson#340]
#### Description of Bug:
cards in set "CNS" have no foreignData
check [Apex Hawks](https://gatherer.wizards.com/Pages/Card/Languages.aspx?multiverseid=382424)

**Comment by ZeldaZach** [comment]
Upstream as Scryfall doesn't have the JP data
cc: @csuhta

**Comment by csuhta** [comment]
Added upstream

**Comment by ZeldaZach** [comment]
Will be added in tomorrow’s rebuild to JSON
