### ISSUE TITLE
MTG rules parser went on a journey to lands unknown and brought something back.

### ISSUE THREAD

**Issue by peterix** [mtgjson/mtgjson#341]
#### Description of Bug:
There is some extra text that doesn't belong in https://mtgjson.com/json/CardTypes.json, possibly others.

See:
![image](https://user-images.githubusercontent.com/203326/57200696-21d31980-6f8f-11e9-8469-24ccd98fd4de.png)

**Comment by ZeldaZach** [comment]
I blame Wizards. The parser is very hacky so I'm not too surprised it broke. Will look into a fix later.

**Comment by ZeldaZach** [comment]
Fixed in a694a9bb7b5ad30f2370357556acad7ca34bbb86
