### ISSUE TITLE
Add prerelease dates and development codenames to set data

### ISSUE THREAD

**Issue by Tedderouni** [mtgjson/mtgjson#341]
Please add the dates of the prerelease tournament and the development codenames for sets that have them.  If needed, this data is listed on https://en.wikipedia.org/wiki/List_of_Magic:_The_Gathering_sets

**Comment by Garbee** [comment]
What usefulness does this information provide to applications taking advantage of the API? I don't think the API needs to have all the random miscellaneous information available crammed within it.

**Comment by Tedderouni** [comment]
This API is intended as a source of information, is it not?  This is additional information about the sets.  It's up to the consumers of the API to decide what's useful and choose which bits of information they use or don't use.

**Comment by Garbee** [comment]
Everything has a cost to compile and maintain. Use-cases drive the investment of time into maintaining things. If there is no compelling use-case, things shouldn't be included. Simply because someone may possibly find them beneficial one day maybe doesn't mean the information needs to be in an API.

If there isn't a decent enough use-case then the data doesn't need to be included.

**Comment by tritoch** [comment]
MTGJSON is a project to scrape and parse the Gatherer database. It is intended to be hands off. The only manual data is a bit of set headers. This is outside the scope of the project. You can extend the project in any way you please under the Creative Commons license.

**Comment by Garbee** [comment]
Maintaining the extra data here wouldn't be too bad in the end. But the cost of investing the time to add the data (and keep it up-to-date in the future) still needs justification beyond simply wishing its existence.

**Comment by fenhl** [comment]
I feel like a compelling case against this has been made, so I'm closing this until a better case is made in favor of this feature.
