### ISSUE TITLE
Add BlockList.json or add "block" field to SetList.json

### ISSUE THREAD

**Issue by owo** [mtgjson/mtgjson#342]
While each set object in **AllSets.json** has a block field, this field isn't present in **SetList.json**.
Having this field is very useful for organizing sets by block and allows developers to not to have to hardcode that information.

Alternatively, a new file called **BlockList.json** could organize sets by blocks in the following format:

```
[
    {
        "name": "block name",
        "sets": [
            {
                "name": "Set Name",
                "code": "SET",
                "releaseDate": "2017-05-13"
            },
           ...
        ]
    },
    ...
]
```

In addition to having **BlockList.json**, having **StandardBlockList.json**, which contains only the sets in standard, could also prove useful to some apps, like those geared towards writing deck lists.

**Comment by Garbee** [comment]
The fewer files added the better. I think adding block to the existing set list should be doable.
