### ISSUE TITLE
Slightly wrong ability text for Tibalt, Rakish Instigator

### ISSUE THREAD

**Issue by DJCatBlitz** [mtgjson/mtgjson#343]
#### Description of Bug:
Tibalt, Rakish Instigator has "Whenever" instead of "When" in its text

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
This seems like it’s already fixed (?)

**Comment by ZeldaZach** [comment]
I think I got caught in a MTGJSON cache by accident. You're correct.
