### ISSUE TITLE
releaseDate is specified per set even for sets which did not release at once like FNM promos

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#344]
#### Description of Bug:

https://mtgjson.com/json/F16.json
https://mtgjson.com/json/F17.json
etc.

It's going to be a bit tedious to track them all, but Wizards has announcement articles for all FNM promos.

Tagging them all as January 1st makes some cards appear before their first printing.

Technically they release first Friday of each month.

**Comment by ZeldaZach** [comment]
Since we do per-set releases and not per-card releases now, I'm inclined to close this as a no-fix as it doesn't really benefit anyone as far as I can see. If you see otherwise, please do let me know how we could possibly improve on this.

**Comment by taw** [comment]
Per-set release dates really don't work for a lot of promo "sets" which are just collections of cards released at various times.

It's a bit less of a problem, as most of them got split into annual subsets, but it still loses data compared with v3.

**Comment by ZeldaZach** [comment]
I know it's a loss, but it's a trivial one to me. If I get a compelling case from someone who's actively looking for such data and they have a quality source that makes parsing such data easy, I will gladly reconsider.

**Comment by taw** [comment]
I use those exact dates for two features:

* which cards in a set are reprints
* which cards were legal in various formats at various times

I don't know of any machine readable sources. Release months or sets for [FNM cards are listed on this wiki](https://mtg.gamepedia.com/FNM_card).

**Comment by taw** [comment]
PPRO is even more annoying, as cards in it were printed anywhere from 2007 to 2018.
