### ISSUE TITLE
Split cards do not have correct number

### ISSUE THREAD

**Issue by vrspectre** [mtgjson/mtgjson#345]
#### Description of Bug:
Split cards should have different numbers. They used to, but as of this release that seems to have been removed. 

example: The two instances of 430842 should have 153a and 153b as their "number". 
https://mtgjson.com/json/HOU.json

**Comment by juggler885** [comment]
I think the side field in the card has this information (at least it contains a and b for instance 430842)

Edit: Also this data seems to come from scryfall, and they don't do this with the collector number either

**Comment by vrspectre** [comment]
I hadn't noticed there was a side field. Thanks for pointing that out. I must have missed when it got added. I'll update my code to reference it instead.
