### ISSUE TITLE
include additional general information in file

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson#347]
It would be nice to have e.g. a `date of creation` and `version number` information in the json files.
For automated update checking reasons or just knowing which version of the file you are actually using, or if there are new versions/updates available! Same for troubleshooting and easy identification of outdated versions for example...

Would allow for easy and quick checks against http://mtgjson.com/json/version.json or http://mtgjson.com/json/changelog.json for example.

Right now the first level starts with real data already, so this structural change would be better something for [mtgjson v4](https://github.com/mtgjson/mtgjson4)?

**Comment by fenhl** [comment]
Closing as duplicate of mtgjson/mtgjson4#53.
