### ISSUE TITLE
"Global Series Jiang Yanggu & Mu Yanling" cards does not contain duelDeck

### ISSUE THREAD

**Issue by naknut** [mtgjson/mtgjson#347]
#### Description of Bug:
Global Series Jiang Yanggu & Mu Yanling is listed as a duel deck on the MTGJSON website but none of the cards contain the `duelDeck` property that should exist on duel deck cards.

**Comment by ZeldaZach** [comment]
Didn't meet the normal duelDeck requirements. Added.
