### ISSUE TITLE
Add Welcome Deck 2017 (W17/M17)

### ISSUE THREAD

**Issue by lanodan** [mtgjson/mtgjson#349]
Welcome Deck 2017 (W17/M17) is currently missing, please add it.
Listed here: http://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&set=[%22Welcome%20Deck%202017%22]

**Comment by gwax** [comment]
This is fixed in `master` but has not yet been released.

**Comment by gwax** [comment]
This has been released.
