### ISSUE TITLE
Set Config Standardization

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson#35]
The formatting of the set_configs isn't consistent, and I'd like to change that. We should specify what field(s) are required/optional in a schema/documentation.

My initial thought is
- set name
- set code
- release date
- border
- type
- booster pack contents (TODO: Needs to be reworked)
- languages available in 
- scryfall key (if necessary)

but I'm open to suggestions

I know @ancestral started on this a while ago, but I never heard back

**Comment by tooomm** [comment]
For later, maybe we can have travis check that all fields we want/need are provided for new entries.

Like with the changelog check introduced in https://github.com/mtgjson/mtgjson/pull/381 or the json check+lint from https://github.com/mtgjson/mtgjson/pull/431.

**Comment by ZeldaZach** [comment]
Moved away from this, using SF's version instead.

Missing booster fields, but we'll consider alternatives in the future.
