### ISSUE TITLE
Cards with no mana cost are missing a CMC

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#350]
Cards without a "mana cost" field are also missing the "cmc" field. (Cards with a mana cost of 0 have their CMC included correctly.)

**Comment by patrickbard** [comment]
I think that's the correct behavior since they actually have no mana cost.

It's something you should expect in your code, looking for undefined for example.

**Comment by silasary** [comment]
**202.3a**
> The converted mana cost of an object with no mana cost is 0, unless that object is the back face of a double-faced permanent or is a melded permanent.

**Comment by Garbee** [comment]
[Lands](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=426955) have no CMC on Gatherer. [Cards with a casting cost](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=429875) do. This is where the discrepancy is coming in.

I don't think this is a big enough thing that needs to be handled in the current system. We can fix the consistency problem in a future major revision of the data store. For now, it is simple programming logic to check for this and handle it in any language.

**Comment by patrickbard** [comment]
@silasary I know that. But that is a rule to be assumed after this one:

**202.1b**

> Some objects **have no mana cost**. This normally includes all land cards, any other cards that have no mana symbols where their mana cost would appear, tokens (unless the effect that creates them specifies otherwise), and nontraditional Magic cards. Having no mana cost represents an unpayable cost (see rule 117.6). Note that lands are played without paying any costs (see rule 305, “Lands”). 


What I meant is that the card itself _do have no mana cost_, and we deal with that as being 0 by the rule you've mentioned.

While this could be a consistency problem for some, the opposite may too as I'm not so sure if it's correct treating that as a real property of the card.

Imagine, if all cards without a mana cost would be set to 0 someone may have a hard time separating cards with actual zero mana cost (printed on it) and assumed 0 mana cost (e.g. Lands). While both sides have small annoyances, I can see one being easily treated in code, and the other generalizing things that would be more difficult to deal with later on.

**Comment by csuhta** [comment]
JSON has a tool to represent no mana cost vs. a mana cost of `{0}` though: `null`.

Use the string `"{0}"` for a cost of 0 mana, and `null` for no cost.

You can communicate all situations that way:

- Land, Evermind, etc: `mana_cost`:`null`, `cmc`:`0`
- Cancel: `mana_cost`:`"{1}{U}{U}"`, `cmc`: `3`
- Pact of Negation: `mana_cost`:`"{0}"`, `cmc`:`0`

**Comment by patrickbard** [comment]
With both values as you described, I think it would be the best option for compatibility and consistency for everybody.

**Comment by Garbee** [comment]
If a mana cost doesn't exist, why create the property just to set it to `null`?

**Comment by KingSupernova31** [comment]
You guys are confusing mana cost with converted mana cost. They are entirely separate concepts. A card can have a mana cost of 0 (like Ornithopter), or a mana cost of null (like Ancestral Vision). Both of those have an identical converted mana cost of 0.
