### ISSUE TITLE
Apostrophes in Rulings are not normalised.

### ISSUE THREAD

**Issue by Psithief** [mtgjson/mtgjson#351]
Introduced in a7c605cf4a3540aba45040b174d84fd0809be1f0 (#328), rulings now use left single quotes for apostrophes instead of the normalised `'`.

**Comment by fenhl** [comment]
Apparently this was manually fixed in #270 without an accompanying change in the build system.

**Comment by gwax** [comment]
This will be fixed by #368 followed by a rerun of all builds.
