### ISSUE TITLE
Data changes without version number changes!

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#351]
#### Description of Bug:

The "4.4.0" is very different now from what it used to be, and it's not just price data.
Also the new version is bugged. But it's really hard to track this as version stays the same while data changes.

There are `text` changes, `foreignData` changes. Please bump version number if you change content.

**Comment by taw** [comment]
There are even new cards added (in `PWAR`) without version bump.

**Comment by ZeldaZach** [comment]
I'm still working on how should we properly manage spoiler season, price/bug fix updates, etc. Right now, unless I made significant code changes, I'm fine bumping the date and leaving the number, but I'll think about it more and come up with a better solution

**Comment by ZeldaZach** [comment]
My newest idea is to bump versions using pre-release notation
`4.4.1-alpha` -> `4.4.1-alpha.2` -> ... until `4.4.1` is fully released

**Comment by taw** [comment]
Any version number system works, as long as they're tagged somehow.
