### ISSUE TITLE
UTF8 BOM is some foreign names

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#352]
#### Description of Bug:

This is a bug in "new 4.4.0", it wasn't a bug in "old 4.4.0" as far as I can tell. (https://github.com/mtgjson/mtgjson/issues/351)

In 4BB, 4ED, 5ED, 6ED, 7ED, 8ED, APC, CHR, EXO, INV, JUD, LGN, MIR, MMQ, NEM, ODY, ONS, P02, PCY, PLS, POR, SCG, STH, TMP, TOR, UDS, ULG, USG, VIS, WTH there's UTF8 BOM included in some foreign names.

For example in `4BB`, just before 純白の秘薬. I've only seen it for Japanese names, but I haven't checked everything.

**Comment by ZeldaZach** [comment]
Not to sure what the issue is... can you explain in further detail please?

**Comment by taw** [comment]
There's an extra invisible character ([UTF8 BOM](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8)) in a lot of places in JSON files.

You generally won't see it in browser preview, but if you parse that json with any programming language there will be extra character there.

**Comment by ZeldaZach** [comment]
Can you check if this comes from upstream or if I introduce it?

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by ZeldaZach** [comment]
Handled; the cards updated were
https://api.scryfall.com/cards/d47ef7e7-d034-43aa-b0ad-9967e43c76a8
https://api.scryfall.com/cards/de94b4d5-be8a-431a-bfb4-7e0f7cd021eb
https://api.scryfall.com/cards/f7e209fd-526c-4a0e-b90b-f8712d040b36
https://api.scryfall.com/cards/ffa5e788-9489-451d-9239-c0d34d06837f
https://api.scryfall.com/cards/09d69b12-79af-47e7-98bf-297a8dd7d4a4
https://api.scryfall.com/cards/0a975be3-b172-4f20-818b-130f1e5d53ef
https://api.scryfall.com/cards/1281d4d2-b61d-4bf1-aeb4-0ecb923abf67
https://api.scryfall.com/cards/176615b8-4f59-46d0-aad1-dbcc997842f6
https://api.scryfall.com/cards/2e9ca162-8c74-4ca7-8fab-70bb0b1fa90f
https://api.scryfall.com/cards/34cdee53-76b8-4f30-8e93-e48b1ac23068
https://api.scryfall.com/cards/3d216ee8-d727-4aaf-95b7-dacb1afb6e51
https://api.scryfall.com/cards/4376e342-17fe-458c-a043-bfcbe5f9a39d
https://api.scryfall.com/cards/4d8b617c-13ea-4e42-8be1-c868808abe74
https://api.scryfall.com/cards/56bbe83e-31de-403c-90ed-778125f11429
https://api.scryfall.com/cards/5fce989b-f7ad-40cf-a5fc-5d05c2064ee9
https://api.scryfall.com/cards/74269777-feba-4590-a01e-739fe1426e09
https://api.scryfall.com/cards/7bcf6702-5255-4df6-85f1-ebf7247da433
https://api.scryfall.com/cards/82eff756-e0b7-4d86-a156-f57be50e2a17
https://api.scryfall.com/cards/99a1a7ef-ecf5-4d42-90d9-c5578a4809f1
https://api.scryfall.com/cards/9fc9936c-748e-4797-95ca-cafff8debddd
https://api.scryfall.com/cards/a02fe247-a516-4a7c-8218-862cf51fa092
https://api.scryfall.com/cards/a243dc3e-eb2b-42a7-8112-cd9c98e990ac
https://api.scryfall.com/cards/ad30c831-6f01-473d-8e84-82c182864cc1
https://api.scryfall.com/cards/b2423120-a587-4898-b01c-1f184e050990
https://api.scryfall.com/cards/b550f2eb-4e45-410d-88cb-8cee9acaacb4
https://api.scryfall.com/cards/bbad9b62-6af8-45c6-b552-df0291f86ff0
https://api.scryfall.com/cards/bea08dc2-24f2-4245-b6a0-2677fb7b45f4
https://api.scryfall.com/cards/cbac2b2c-2f27-480d-aa33-190691173430
https://api.scryfall.com/cards/cf76ebb6-b568-4553-8777-7e3a35201c9c
https://api.scryfall.com/cards/d35dfb2c-a334-4cc9-b544-5858231f588a
