### ISSUE TITLE
Missing rarity on AllCards.json

### ISSUE THREAD

**Issue by patrickbard** [mtgjson/mtgjson#352]
I've noticed that `AllCards.json` and `AllCards-x.json` are lacking the rarity information, example:

```
"Ancestral Recall": {
    "layout": "normal",
    "name": "Ancestral Recall",
    "manaCost": "{U}",
    "cmc": 1,
    "colors": [
      "Blue"
    ],
    "type": "Instant",
    "types": [
      "Instant"
    ],
    "text": "Target player draws three cards.",
    "imageName": "ancestral recall",
    "colorIdentity": [
      "U"
    ]
  },
```

**Comment by mtgdrafts** [comment]
I think that's intentional, since a card could be printed at different rarities. You can get the rarity of a specific printing of a card from AllSets.

**Comment by patrickbard** [comment]
I see. But I think it could still be there as well, perhaps embedded with the printing.

Here a suggestion:

```
 "Aether Vial": {
    "layout": "normal",
    "name": "Aether Vial",
    "manaCost": "{1}",
    "cmc": 1,
    "type": "Artifact",
    ...
    "printings": [
        {
            set: "DST",
            rarity: "Uncommon"
        },
        {
            set: "V10",
            rarity: "Mythic Rare"
        },
        {
            set: "MMA",
            rarity: "Rare"
        },
        {
            set: "MPS",
            rarity: "Special"
        }
    ],
    ...
  },
```

I think that's useful for someone who wants to loop at all cards without worrying about sets.

But I can agree that now it looks more like an enhancement than an issue.

**Comment by Garbee** [comment]
I don't think this is needed. If you want the rarity of the cards, get it from the sets data. `AllCards` is explicitly all the normalized information available and rarity can't be normalized.

**Comment by jmazouri** [comment]
I think it would be useful to have a field containing the "current" rarity of a card - such as when searching for Pauper cards, where a card's last printed rarity is considered.

**Comment by Garbee** [comment]
"current" is variable. As the rarity level entirely depends upon the card's perceived play value within the set of printing.

Simple though, if you need rarity, use `AllSets` and get the data from that. `AllCards` is all the normalized card data available.

**Comment by tritoch** [comment]
> Here a suggestion:
    "printings": [
        {
            set: "DST",
            rarity: "Uncommon"
        },

Where do you draw the line with this? Cards have plenty of printing specific data beyond rarity, that's why AllSets exists. Artist, Card Number, Flavor Text, Printed Text, etc...

**Comment by Garbee** [comment]
@tritoch It will go as far as necessary to have all possible information included in every single file. Because at some point, "it's just one more thing" all the way until everything includes everything.

**Comment by fenhl** [comment]
Formats like Pauper actually use the most common (not most recent) rarity of a given card. However, this may not be the expected result for other use cases (you might expect to see the most recent rarity instead), so anything that requires something like this should compute it from the set-specific info in `AllSets.json`.
