### ISSUE TITLE
PWAR Mobilized District has no artist

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#353]
#### MTGJSON Version: 4.4.0

This affects "new 4.4.0" but not "old 4.4.0".

https://mtgjson.com/json/PWAR.json

#### Description of Bug:

`PWAR` Mobilized District has no `artist` field. All other cards in all other sets seem to be fine.

It's probably worth adding an automated check for this.

**Comment by ZeldaZach** [comment]
Appears to be upstream issue.

cc: @csuhta

**Comment by csuhta** [comment]
Fixed upstream
