### ISSUE TITLE
Missing mciNumber in cards with multiple variations

### ISSUE THREAD

**Issue by hisie** [mtgjson/mtgjson#353]
I have checked that in, at least, one collection (Limited Edition Alpha) the basic lands has no mciNumber. Are there some reason for that? If is really a bug, to make a pull request is it simply necessary modify the file json/LEA.json? if not, How can i help to make it appear?

Thank you very much

**Comment by gwax** [comment]
Currently, mtjson's backend doesn't know how to handle magiccards.info when there are multiple variations of a card in a set.

This would need to be fixed in: [rip.js](https://github.com/mtgjson/mtgjson/blob/master/build/rip.js#L852)

**Comment by ZeldaZach** [comment]
Removed in V4, as MCI is gone
