### ISSUE TITLE
Junk Rules Text in keywords.json

### ISSUE THREAD

**Issue by SternerStock** [mtgjson/mtgjson#354]
#### Description of Bug:
Keywords.json breaks down on line 41, after "undergrowth" in "AbilityWords".
Maybe an oxford comma was added or removed in the rules text that is being parsed? Line 41 begins with "and will of the council.", and it's just snippets of rules text down from there.
See https://mtgjson.net/json/Keywords.json

**Comment by ZeldaZach** [comment]
Handled. Also dupe #341
