### ISSUE TITLE
Warning: Gatherer has deleted all supertypes

### ISSUE THREAD

**Issue by csuhta** [mtgjson/mtgjson#355]
All of the basic lands have been damaged and don't include "Basic" in their type line anymore.

- http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430642
- http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=407693
- http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=121233

Legendary creatures aren't legendary:

- http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=423754

World enchantments aren't World:

- http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3326

I reported this issue to WOTC customer service, but this is so bad multiple people might want to open tickets.

**Comment by Garbee** [comment]
Looks to be fixed to me.

**Comment by csuhta** [comment]
Yes, it looks like they had emergency downtime and fixed it. All clear!
