### ISSUE TITLE
PRNA set is under PRN in AllSets.json

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#355]
#### MTGJSON Version: 4.4.0

https://mtgjson.com/json/AllSets.json

#### Description of Bug:

Set with code `PRNA` is under json key `PRN`. This confuses some tooling, as everything else has matching code and sent code.

All other set codes match.

**Comment by ZeldaZach** [comment]
Stupid bug I introduced. Simple fix. WIll push in a sec.

**Comment by ZeldaZach** [comment]
31521b2f6f2d6093a2482ba6f6b7ceb9d6525f66
