### ISSUE TITLE
Planar card subtypes are incorrectly split into multiple subtypes

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#356]
#### Description of Bug:

> 309.3.

> Plane subtypes are listed after a long dash, and may be multiple words: “Plane — Serra’s Realm.” All words after the dash are, collectively, a single subtype. Planar subtypes are called planar types. A plane can have only one subtype. See rule 205.3n for the complete list of planar types.

For example here https://mtgjson.com/json/OPCA.json

It's listed as:

```
    "subtypes": [
                "New",
                "Phyrexia"
     ],`
```

It should be:

```
    "subtypes": [
                "New Phyrexia"
     ],`
```

And so on. It seems to affect all planar cards with multiword subtypes.

**Comment by ZeldaZach** [comment]
That's my fault for splitting on spaces :D Will need a new method

**Comment by taw** [comment]
Just split everything on spaces except when it's Plane, then don't split on anything.

I don't think there are any exceptions to this rule.
