### ISSUE TITLE
Some cards are missing frameEffect

### ISSUE THREAD

**Issue by naknut** [mtgjson/mtgjson#358]
#### Description of Bug:
Some cards seem to be missing the frameEffect field when it should be set. For example "Niv-Mizzet Reborn" in "War of the Spark". He has a legendary frame but the frameEffect is omitted.

**Comment by ZeldaZach** [comment]
Seems to be an upstream issue. cc: @csuhta 

Niv doesn't have `frame_effect`: https://api.scryfall.com/cards/56a2609d-b535-400b-81d9-72989a33c70f?format=json&pretty=true

But Gwafa does: https://api.scryfall.com/cards/da097d1a-6e51-41d7-8dfe-f26acfb0038f?format=json&pretty=true

**Comment by ZeldaZach** [comment]
Seems to be fixed
