### ISSUE TITLE
Proposal: storing booster generation instructions on the set info

### ISSUE THREAD

**Issue by thinkingofmaud** [mtgjson/mtgjson#359]
In mtgjson, most sets have the boosterV3 property, which is an array of rarities.
Let's see, for example: Shards of Alara

```
"boosterV3": [
  [
    "rare",
    "mythic rare"
  ],
  "uncommon",
  "uncommon",
  "uncommon",
  "common",
  "common",
  "common",
  "common",
  "common",
  "common",
  "common",
  "common",
  "common",
  "common",
  "land",
  "marketing"
]
```

This does not reflect at all how boosters should be generated. I think better format for that.
I looked around, for example, mtggen uses this format to generate packs: https://github.com/copperdogma/mtgen/blob/master/mtgen/wwwroot/ala/packs.json. That may be too unterse, but is readable.

They way I see it, it would be better to create a gen property in set, and that should hold the values needed to create a booster. That is a proposal on how to do it.

```
"booster" : [
  1,
  [
    1,
    "mythic rare",
    7,
    "rare"
  ],
  3,
  "uncommon",
  9,
  "common",
  1,
  [
    1,
    "foil",
    5,
    "common"
  ],
  "land",
  1,
  "marketing"  
]
```

and, also, the foil distribution, since this is a post Time Spiral set:

```
"foilDistribution" : {
  "land": 8,
  "common": 88,
  "uncommon": 24,
  "rare": 7,
  "mythic rare": 1
}
```

And maybe even some additional description, pointing to the source of the info.

"description" : "That's the set that debuted the mythic rare rarity https://magic.wizards.com/en/articles/archive/making-magic/year-living-changerously-2008-06-02"

This gen property could be further extended to collect info about Tournament Packs, wal-mart boosters, and so on.
Also, some cards "rarity" value does not reflect at all how they collate into the pack.
Island is a "common", on that set, that value does not reflect on how it is collated on a booster pack.
So, Island, in that set, should have a "genRarity" : "land" property. That property should be optional, used only for cards that have a genRarity different from the displayed rarity. 
The land genRarity alone should help in issues like Modern Horizons having a snow land for each pack, or Guilds of Ravnica having a guildgate on each pack.

I know that it is a ton of work, but, that's not an edge case, or a special rule. That's the way usual boosters work since Alara.

Afterwards, it can be used to tackle the madness that is the Alliances rarity system https://mtg.gamepedia.com/Talk:Alliances
It would also help with cards that have special rarities, like masterpieces, zendikar expeditions, power 9 in vintage masters, timeshifted cards, and so on.

---

Related:

* https://github.com/mtgjson/mtgjson/issues/225
* https://github.com/mtgjson/mtgjson/issues/265#issuecomment-471282586
* https://github.com/mtgjson/mtgjson/issues/35#issuecomment-423776108

**Comment by ZeldaZach** [comment]
I purposely marked the field as "boosterV3" because I knew we would come up with a better solution for V4, just we didn't have an idea established before launching.

I would gladly look into something like your proposal, with some changes.

```json
{
  "booster": [
    [{
      "type": "rare",
      "odds": 0.875
    }, {
      "type": "mythic",
      "odds": 0.125
    }],
    {
      "type": "uncommon",
      "total": 3
    },
    {
      "type": "common",
      "total": 9
    },
    [{
      "type": "common",
      "odds": 0.833
    }, {
      "type": "foil",
      "odds": 0.166,
      "distribution": {
        "common": 0.50,
        "uncommon": 0.33,
        "rare": 0.146,
        "mythic": 0.021
      }
    }]
  ]
}
```

Explained:
`type`: What are the restrictions on the card? (Can say "legendary creature", "planeswalker", etc...)
`odds`: (Optional) What are the odds of opening the card? Useful for sub-sets which _must_ equal to 0.999 or 1.0 for the sum of all odds. Excluded means odds = 100%. 
`total`: (Optional) How many repeating entries of this object are there? Excluded = 1
`distribution`: (Optional) Map of `type`s to determine type of card to use

tagging @taw as he might have an interest in suggesting ideas

**Comment by thinkingofmaud** [comment]
>  type: What are the restrictions on the card? (Can say "legendary creature", "planeswalker", etc...)

Scryfall already has a syntax for that, so we can have "r:common t:land" for the guildgates or "t:basic" for the snow land.

That syntax may also be used for the "one planeswalker per pack" of War of The Spark and the "one legendary creature per pack" of Dominaria.
I think the foil cards dont count for that rule, but I could not find any source on that.

This does not solve the Alliances shenanigans though... i see no other solution than to list the genRarity of each card.

**Comment by ZeldaZach** [comment]
🤷‍♂ It's hard to set the standard. If you have other ideas do feel free to post!

**Comment by taw** [comment]
You wish it was that simple.

Some relevant code behind [Sealed simulator](http://mtg.wtf/sealed): [1](https://github.com/taw/magic-search-engine/blob/master/search-engine/lib/card_sheet_factory.rb) [2](https://github.com/taw/magic-search-engine/blob/master/search-engine/lib/pack_factory.rb).

So what I'm basically doing for very simple "normal" set:

* preparing print sheets, each by a query (one of the reasons why I needed `basic` rarity) - for very simple sets there are 5 sheets: basic, common, uncommon, rare/mythic, foil
* sheets consist of either card printings (at equal ratios), or of subsheets (at specified ratios), but this is just to make code simpler. In theory we could just give every card on a sheet specific chance.
* for example rare/mythic sheet has two subsheets at a mixing ratio (rare subsheet; mythic subsheet). foil sheet has a lot of subsheet
* having a few versions of a booster made out of these sheets - for very simple set it's 0.75 (1R, 3U, 10C, 1B) and 0.25 (1R, 3U, 9C, 1F, 1B).
* code also makes sure there are no duplicates, has very simple commons color balancing logic etc. - but this isn't really necessary for mtgjson

Unfortunately it turns out a lot of sets are not that simple. And we're guessing a lot of those ratios.

If you want something machine readable, and cover most boosters, minimum solution would be something like:

```
  sheets: {
     common: [
        {numbers: ["1","2","3","4","5",..], weight: 1.0, foil: false}
      ] ,
      uncommon: [...],
      basic: [...],
      foil: [
        {numbers: ["1","2","3","4","5",..], weight: 12.0, foil: true},
        {numbers: ["100","101","102",...], weight: 2.0, foil: false},
        {numbers: ["150","151","152",...], weight: 1.0, foil: false}
        ...
      ],
      rare_mythic: [
        {numbers: ["100","101","102",...], weight: 2.0, foil: false},
        {numbers: ["150","151","152",...], weight: 1.0, foil: false}
      ]
  },
  booster: {
    {cards: {rare_mythic: 1, uncommon: 3, common: 10, basic: 1}, weight: 3.0},
    {cards: {rare_mythic: 1, uncommon: 3, common: 9, foil: 1, basic: 1 }, weight: 1.0},
  }
```

Also numbers would sometimes need to be like `123a/123b` (multipart cards, I'm assuming here that numbers are totally unique, which is true once I'm done with the index, but not true in raw mtgjson data) or `mps:6` (for cards from different sets).

Then it would cover non-booster cards (buy a boy, planeswalker deck promos), old sets with known ratios not corresponding to any "rarity", and a lot of other issues, but sometimes there would be a lot of sheets and booster versions.

This won't deal with partner cards very cleanly, but I think everything else kinda fits. Maybe some extra flags for sheets (`balanceColors: true` for commons, `partner` for BBD) would cover those extra cases. Color balancing didn't even work same for all sets, but that might be going too far.

I though about moving that stuff from code to some pre-generated json for performance reasons, but it's not high on my priority list.

**Comment by taw** [comment]
> so we can have "r:common t:land" for the guildgates or "t:basic" for the snow land.

I literally use MCI style queries for mtg.wtf's Sealed simulator, but that's really not the right approach for mtgjson, unless it starts bundling a search engine with itself. I mean, mtg.wtf's is open source, but it's not something that would be terribly convenient to use for most software.

The only sensible solution is to somehow list which card goes onto which sheet, at which rate, either inside `card` or in some separate `sheets`.

This has nice advantage of being able to [deal with stuff like this](https://github.com/taw/magic-search-engine/blob/master/data/print_sheets/Alliances_checklist.txt), masterpieces, excluded non-booster cards, and so on.

**Comment by thinkingofmaud** [comment]
> This won't deal with partner cards very cleanly, but I think everything else kinda fits. Maybe some extra flags for sheets (balanceColors: true for commons, partner for BBD) would cover those extra cases. Color balancing didn't even work same for all sets, but that might be going too far.

Partner is https://magic.wizards.com/en/articles/archive/news/find-your-partner-battlebond-2018-05-18, right?

Zach had a post about color balance - https://github.com/dr4fters/dr4ft/issues/454#issue-438130114

**Comment by taw** [comment]
> Partner is https://magic.wizards.com/en/articles/archive/news/find-your-partner-battlebond-2018-05-18, right?

[You can see this issue](https://github.com/taw/magic-search-engine/issues/106).

Battlebond collation [explained here](https://twitter.com/GavinVerhey/status/999437362357649408).

It would either need special BBD-specific logic (what I do), or one 2-card print sheet per pair, then one 2-card print sheet for foil version of that pair, followed by obscene number of booster types.

> Zach had a post about color balance - dr4fters/dr4ft#454 (comment)

It doesn't _really_ work. If you try that without weight corrections, you'll have massively skewed card frequencies by color. Same problem if you generate pack at random then reject invalid ones.

Also some sets color balance by printed color, some by color identity, in either case it's just approximation of secret collation process. (that's not something I currently handle, as 90% of sets don't have this problem)

For simple case math for weight correction isn't too bad ([code](https://github.com/taw/magic-search-engine/blob/master/search-engine/lib/color_balanced_card_sheet.rb)), to hit every criterion on the list, it would basically require running a constraint solver to get correct weights.

Anyway, those rules aren't really exact. The booster packing process tries to mostly hit them, but they can be occasionally violated. They're not hard rules like "3 uncommons per pack".

**Comment by thinkingofmaud** [comment]
The gen property may also be used to store sheet, subsheet, and collation data, as well as the sources from where it was researched, when applicable.
Is there a set where we have perfect collation and sheet data?
It also seems that even on modern sets, some cards are "shortprinted" on the sheets, so, yeah, weight correction needs to be considered even on a pure statistical model, ignoring sheet collation.

@taw, while i was getting into this booster back rabbit hole, i tested your app. It generates basic lands fo 4th edition booster packs, while mtgen does not...
Dr4ft also has the same issue.

You are probably way more knowleged about this than i ever will be. Can I check if my research on the issue of the basic land slot on boosters is right?

* From alpha to unlimited, core sets had basic lands printed on the common, uncommon, and rare sheets.
* In revised, basic lands were printed on the common and the uncommon sheet.
* Until shards of alara, expert sets had no basic land cards.
** Exception - snow basics.
* With revised, wizards improved the collation and printed basic lands on a separate sheet, removing them from boosters at first, intending to put basic lands only on the other products.
* From revised to planeshift, both core and expert packs had no "vanilla" basic lands in.
** Exception: unglued had basic lands. Were they on a dedicated slot?
* After 7th edition, core sets had basic lands, in a dedicated slot. Expert sets continue to have no basic lands.
** In time spiral, there's a slot, that is occupied by a timeshifted card. I'd guess the collation process should be identical to the basic land slot from 7th edition.
* After shards of alara, wizards starts using the basic land slot on almost all boosters, but, sometimes, that land slot is occupied by something else.

**Comment by taw** [comment]
[Outstanding issues are documented in this ticket](https://github.com/taw/magic-search-engine/issues/106).

Situation of pre-Alara basic lands is of the things that needs double checking.

**Comment by taw** [comment]
So I took a quick stab at exporting. Here's one for RNA. This format is not quite what I had it mind (it shouldn't repeat identical sheets, it should flatten away subsheets, have sheet names not just `sheet-1` etc.). It's also verbose as hell. Well, it's a starting point for export script.

[rna.txt](https://github.com/mtgjson/mtgjson/files/3259980/rna.txt)

**Comment by taw** [comment]
As for 4th Edition, with says:

> Fourth Edition was the first set to have its basic lands printed on a separate print sheet. This freed up room on the other card sheets to include more spells. The boosters didn't contain basic lands anymore.

I'll probably need to go through all the pre-Alara sets again, and double check that basic lands are ok for each one.

**Comment by thinkingofmaud** [comment]
> RNA

Nice. Well, it's something.

There are pictures of the visions sheets in https://mtg.gamepedia.com/Print_sheet#cite_note-How-7

Still, it's not clear how the commons subsheet on the rare sheet are distributed on packs. It's one of the common slots, as in 10 commons, 3 uncommons, 1 common from the rare sheet, 1 rare?

**Comment by taw** [comment]
> Still, it's not clear how the commons subsheet on the rare sheet are distributed on packs. It's one of the common slots, as in 10 commons, 3 uncommons, 1 common from the rare sheet, 1 rare?

Which sets are you talking about?

**Comment by thinkingofmaud** [comment]
Visions, where the rare sheet has 50 commons (upper half subsheet) and 50 rares (bottom half subsheet) printed on it.

https://mtg.gamepedia.com/File:Uncut-VIS-R.jpg

Sorry for not being clear.

**Comment by taw** [comment]
> Visions, where the rare sheet has 50 commons (upper half subsheet) and 50 rares (bottom half subsheet) printed on it.

Did they just physically cut it into halves before the rest of the process? If so, then it's basically two sheets with extra steps.

Anyway, here's updated rna.txt export. Now with identical sheets merged, and with more concise format of card information. It's actually borderline readable now.

[rna.txt](https://github.com/mtgjson/mtgjson/files/3263971/rna.txt)

Next steps is flattening subsheets for export, and exporting sheet names so it's like `rna-commons` not like `sheet-1` (they have them at some point, but that doesn't get through exporter). We should probably just ignore existence of BBD for MVP, everything else will probably have usable exporter in a few more iterations.

**Comment by jhallbachner** [comment]
I think for general use you can build a heuristic-based approach that's a lot simpler. The thing that matters most that isn't cleanly covered by full random selection is color balance; every set basically has different "buckets" of cards (colors, color pairs, artifacts, lands) that should be distributed somewhat evenly.

If we assume that we have a value for "printed rarity" (i.e. the sheet(s) a card's on and at what frequency), you can generate a pretty solid pack for everything pre-modern with the exact same heuristic.

- fill the rare slot, if present, with a card from the rare sheet
- fill any special sheet slot (like timeshifted cards) just like is done with the rare sheet
- fill the uncommon slots successively, always disallowing a card from the same "bucket" as the previous card filled
- fill a set of six commons, disallowing cards to be in the same bucket as either of the preceding 2 cards
- if slots are left, fill another set of up to five commons, starting with a bucket not present in the first six if any
- fill up one land slot

so for a normal old the config might be like (extreme pseudocode here): 

```
{
  buckets: [W U B R G A L],
  slots: [
    'rare',
    'uncommon',
    'uncommon',
    ...
    'common',
    'common',
    'land'
  ]
}
```

For sets prior to Time Spiral you can do foils by defining a global foil chance for every set and making one card foil at random in a pack that rolls a foil.

For sets after Time Spiral you just assume a slot for foils in 1 out of every _n_ packs and put a random foil (proportionate to rarity) in there.

Some special exceptions:
- Mirrodin block has a lot of artifacts so you'll get some weird results if you try to treat them all as a bucket. you probably want to be able to split any given bucket further, e.g. `buckets: [W U B R G A A A L]` to have artifacts split into three buckets.
- Time Spiral, Innistrad, etc. have a special slot that needs to get filled.
- DOM and WAR have a special slot whose contents tells you which slot to have them replace.
- Planar Chaos basically just has special sheets for "common timeshifted" and "uncommon/rare timeshifted"
- Battlebond is its own weirdo situation that's probably hard to fully taxonomize.

**Comment by thinkingofmaud** [comment]
Time spiral is easy, the special slot uses the same logic as basic lands in most sets.

I think your heuristic is spot on, for the commons. You still need to even the buckets with the actual slots, or you will get probabilities that are off.

Example: Time Spiral
* Pack Contents: 9 Commons, 1 Common or Foil, 3 Uncommons, 1 Rare, 1 Timeshifted.
* All cards with the same rarity appear at the same ratio.
* Basic Lands do not appear in a pack.
* 23 commons of each color. 6 colorless commons. With that ratio, you can't guarantee a colorless common for each pack, so they don't get an dedicated bucket.
* * So, we have [W U B R G A A A A A]
* * Colorless cards should be overrepresented in the A bucket, to compensate for them not appearing in the colored bucket.
* * * Alternatively, they should have their dedicated C bucket, but that bucket will have the odds for a colorless unfoil common actually appearing in that pack. If the odds are not met, its treated as the A bucket.

Since that statistical model does not guarantee the elimination of duplicates this needs to be checked later.

Foils after time spiral is also easy. After the common pack is generated, if the odds for the foil are met, just remove the last common, replace it with a foil.

Uncommon sheet is a diferent beast. I think rejecting uncommon triplets that have the same color is the best choice, for now.

There's also the issue of multicolor blocks, where we have multicolored cards at common.
I think multicolored cards should be left in the general bucket, for that set, or having their own dedicated.

**Comment by ancestral** [comment]
Here’s my take:

I don’t like guessing.

MTGJSON is a resource with factual information.

If you want to build a booster generator, don’t put it in this project.

If the data can’t be sourced reliably, then it shouldn’t be captured.

**Comment by taw** [comment]
> I don’t like guessing.
> 
> MTGJSON is a resource with factual information.
> 
> If you want to build a booster generator, don’t put it in this project.
> 
> If the data can’t be sourced reliably, then it shouldn’t be captured.

Other than foils, which are known to be approximate, and some sets with weird rules (like DOM, BBD, WAR), contents of boosters are known quite well.

**Comment by taw** [comment]
So I got the export to state I'm reasonably happy with.

All sets:
[export_sealed.txt](https://github.com/mtgjson/mtgjson/files/3290444/export_sealed.txt)

Just RNA:
[rna.txt](https://github.com/mtgjson/mtgjson/files/3290446/rna.txt)

Notes:

* the only place where I threw out data was which BBD card partners with which other card, everything else is flattened but as complete as I have it
* overall quality of this data is decent, but there are many known issues (and probably some unknown ones)
* I tried to use compact format, it's 800kB compact / 1.4MB pretty-printed. I could use different format just as easily if that's more convenient to whoever's going to inject it.
* cards are identified like `rna:69` or `rna:69:foil`, multipart cards are identified by first part like `rna:221a`, it should be clear enough.
* I think `PLS`, `BFZ`, `OGW`, `UGL`, `UNH`, `UST` might have some numbering mismatches with most recent mtgjson. Everything else I think should just match exactly.
* sheets have globally unique names like `rna_uncommon`, some names are weird like `rna_rna_common`, that's basically when it uses special query for them. Names come from internal code, so aren't nicest, but should be clear enough.
* even base query is more than name implies, `rna_uncommon` sheet is like `++ e:rna r:uncommon is:booster is:nonfoil`
* all ratios are expressed by weight only (so if there are two options with weight 3 and 1, it means 3/4 and 1/4 respectively)
* especially foils have obscenely high weights, but that's probably correct

If this feels useful, message me and I can setup some git repo for automatically exporting this json, just like I did with precons.

**Comment by ancestral** [comment]
> Other than foils, which are known to be approximate, and some sets with weird rules (like DOM, BBD, WAR), contents of boosters are known quite well.

* The commons are actually split onto two sheets where there are actually a handful of cards that printed more frequently. Which ones? We have no idea.
* Wizards has certain rules about color variance in a pack, and rumor has it number of creatures and non-creature spells.
* Your “weird sets” example is starting to become the norm. Wizards can now set rules on how boosters are made, like a Planeswalker in every pack. (It’s unknown enough that MaRo has guessed himself how it works.)
* Sets like Fallen Empires, Homelands, Alliances and Chronicles, these sets have multiple cards in a rarity on a sheet, and often have card variants that further complicate things.

If you want to make a booster generator with intricate rules, go do that in a different project. MTGJSON is a resource that is delivering factual information, not guesses. **We don’t have enough information on the booster generation process to ensure accuracy**, and the reality is some older sets probably can never be re-created correctly **because the order on the sheets is unknown**.

**Comment by taw** [comment]
> Sets like Fallen Empires, Homelands, Alliances and Chronicles, these sets have multiple cards in a rarity on a sheet, and often have card variants that further complicate things.

Those sets are actually 100% known, Wizards back then provided official information about that, [you can check them out](https://github.com/taw/magic-search-engine/tree/master/data/print_sheets).

> The commons are actually split onto two sheets where there are actually a handful of cards that printed more frequently. Which ones? We have no idea.

> Wizards has certain rules about color variance in a pack, and rumor has it number of creatures and non-creature spells.

So what actually happens is that collation is done by hand. It includes color, estimated power level etc.

For a few sets we have full print sheets, but mostly we don't. It's just a limitation of what we have, we don't make up fake data here.

> The commons are actually split onto two sheets where there are actually a handful of cards that printed more frequently. Which ones? We have no idea.

[There's crazy amount of information here](http://www.lethe.xyz/mtg/collation/), if anyone really cared.

> Your “weird sets” example is starting to become the norm. Wizards can now set rules on how boosters are made, like a Planeswalker in every pack. (It’s unknown enough that MaRo has guessed himself how it works.)

It's still just a few sets, and it's not clear if it's really going to become common. It's not even that we can't figure it out, just that those special sets aren't a priority.

[And we can always ask for this information](https://twitter.com/GavinVerhey/status/999437362357649408).

> MTGJSON is a resource that is delivering factual information, not guesses. 

We do a lot of guessing already. Like what's with our `rarity` field really? Or `releaseDate`? Or format legality (Chinese standard where). It's all a spectrum.

**Comment by ancestral** [comment]
> > Sets like Fallen Empires, Homelands, Alliances and Chronicles, these sets have multiple cards in a rarity on a sheet, and often have card variants that further complicate things.
> 
> Those sets are actually 100% known, Wizards back then provided official information about that, [you can check them out](https://github.com/taw/magic-search-engine/tree/master/data/print_sheets).

It’s not always just that simple. For example, with Fallen Empires, it is not unheard of to get two versions of the same card, with alternate art.

> > The commons are actually split onto two sheets where there are actually a handful of cards that printed more frequently. Which ones? We have no idea.
> 
> > Wizards has certain rules about color variance in a pack, and rumor has it number of creatures and non-creature spells.
> 
> So what actually happens is that collation is done by hand. It includes color, estimated power level etc.
> 
> For a few sets we have full print sheets, but mostly we don't. It's just a limitation of what we have, we don't make up fake data here.

No, but if we don’t have the formula, then we’re guessing what the formula is.

> > MTGJSON is a resource that is delivering factual information, not guesses.
> 
> We do a lot of guessing already. Like what's with our `rarity` field really? Or `releaseDate`? Or format legality (Chinese standard where). It's all a spectrum.

We are taking what Scryfall has sourced, and what Wizards provides on Gatherer, and their official information. Release date and legality data is coming from those sources, but at this point it’s been established with those are trusted sources.

That being said, you’re talking about creating formulas for generating boosters. This is straying considerably away from what MTGJSON’s goals are. However, this would be something that would be amazing to add into [dr4ft](https://github.com/dr4fters/dr4ft).

@ZeldaZach What do you want to do here? I don’t disagree there may be a better way to format the set info, but things like how boosters are generated and foil ratios are total guesses without substantial data from trusted sources. I want MTGJSON to continue to be a dependable resource with accurate information.

**Comment by ZeldaZach** [comment]
I'm very hesitant to add such large chunks of data at this time. I am not saying no, but I just don't find this to be the correct path. Ancestral is correct that this would make a great addition to the dr4ft project in generations. I have no problems re-working what we currently have, but I don't think this is the right path. For something this large, I'd like a few more people to weigh in before anything is set in stone.

**Comment by thinkingofmaud** [comment]
> If you want to make a booster generator with intricate rules, go do that in a different project. MTGJSON is a resource that is delivering factual information, not guesses. **We don’t have enough information on the booster generation process to ensure accuracy**, and the reality is some older sets 
probably can never be re-created correctly **because the order on the sheets is unknown**.

Very true. For alpha, even the distribution of basic lands is unknown!

**Comment by ancestral** [comment]
Yeah, it sucked for those people who bought packs and could get a basic land as their rare, as the basic lands were on the same sheet as the rares.

**Comment by thinkingofmaud** [comment]
```
basic =
  rarity: 'basic'
  lambda: (card) -> 'Basic' in card.supertypes
  scryfall: 't:Basic'
  description: 'A land with the supertype "basic", usually Forest, Swamp, Plains, Mountain, or Island'

timeSpiralFoil =
  odds: 1/6 # odds of appearing in each pack
  rarity: 'foil'
  replaces: 'common'
  description: 'https://magic.wizards.com/en/articles/archive/making-magic/purple-reign-2006-09-25-0'
  # since the distribution is ommited, it follows the same distribution as an usual pack

alara =
  specialRarities: {basic} # rarities that arent the usual curm
  slots:
    rare_mythic: 1
    uncommon: 3
    common: 10
    basic: 1
  extras: [timeSpiralFoil] # cards that arent guaranteed, but have a chance of appearing
  length: 15 # how many playable cards each pack should have
  description: 'https://magic.wizards.com/en/articles/archive/news/changes-2008-06-02'
```

or, in json 

```
{
	"specialRarities": {
		"basic": {
			"rarity": "basic",
			"scryfall": "t:Basic",
			"description": "A land with the supertype \"basic\", usually Forest, Swamp, Plains, Mountain, or Island"
		}
	},
	"slots": {
		"rare_mythic": 1,
		"uncommon": 3,
		"common": 10,
		"basic": 1
	},
	"extras": [{
		"odds": 0.16666666666666666,
		"rarity": "foil",
		"replaces": "common",
		"description": "https://magic.wizards.com/en/articles/archive/making-magic/purple-reign-2006-09-25-0"
	}],
	"length": 15,
	"description": "https://magic.wizards.com/en/articles/archive/news/changes-2008-06-02"
}
```

**Comment by ZeldaZach** [comment]
Interesting approach. You're missing token/ad cards and other misc stuff that might appear in a pack, but overall I kind of like it. Where would the description come from if they're not all the same?

**Comment by thinkingofmaud** [comment]
I'm using description to point to an article or some other source of that info. That may not be necessary for mtgjson.

The packs are not all the same. For example, Core 20 is core 19 has a new, higher foil ratio. Core 19 is Alara but there is a special land slot. Modern Masters is Alara but instead of a land slot you have a foil slot. 

Alpha has basic lands in all of the sheets, Islands on the rare sheet.

Mtgjson already has tokens. It also stores ads, and stuff like that?

**Comment by ZeldaZach** [comment]
Can you show me a few more examples? `ORI UST LEA ZEN EMN UNG XLN C18 WAR` is my standard "quick" testing procedure for seeing if I broke anything

**Comment by thinkingofmaud** [comment]
UST has the contraptions. Are they all of the same rarity?
LEA has the lands on all slots. I think the easiest way to do it is using the extras to replace cards for lands.
EMN has a slot with a special distribution, the double card.
UNG has one land per pack? Then i can use the same model as Sevent /Eigth Edition (memory fails me right now).
XLN and ZEN have a masterpiece extra. Same approach could be used for VMA and TSP. Related: https://github.com/mtgjson/mtgjson/issues/378
C18 is what?

WAR is though because of the one planeswalker per pack rule. It neees a special distribution table on the slots. Also DOM. https://github.com/mtgjson/mtgjson/issues/359#issuecomment-498501300
BBD is the thoughest nut to crack. Maybe the distribution table approach would suffice.

**Comment by thinkingofmaud** [comment]
On Throne of Eldraine - https://mtg.gamepedia.com/Throne_of_Eldraine

> "The Draft Booster has the possibility of containing borderless planeswalkers or special new showcase cards. The Showcase frame is a catch-all term to cover a variety of different treatments that embody the spirit of the relevant set.[16] The art and frame will play into the set's theme (in this case it frames the card boxes with green vines). Each set will have its own unique showcase cards. Which cards get the treatment (and usually, it will just be cards from that set), and at what rarity, will vary from set to set. Showcase cards replace cards of the same rarity as the non showcase card in packs. The showcase cards don’t require a mechanic with a new frame. That just happens to be the case for Throne of Eldraine.[19] The Showcase cards replace cards of the same rarity as the non showcase card in packs. There are no non-foil common showcase cards in booster packs. Those appear only in the Collector Booster. Every rare or mythic rare from the set that doesn't already have a variant frame (meaning that it doesn't exist as a borderless planeswalker card or showcase card) will be available as extended-art cards. The extended-art cards are all rares and mythic rares and are only found in the Collector Booster."

New rarity for collectors, in an alternate pack, that works like a urza foil. New bike shed for every set.

**Comment by ZeldaZach** [comment]
I saw that and was thinking "ughhhhh." Not sure how we should handle it, but this is going to force our hand for a V4. I'm still leaning towards using an enum-type class and not defining odds initially, but leave room for them to come in the future. This field should be easy enough for people and machines to understand. Will brainstorm soon.

**Comment by taw** [comment]
Just saying, the machine-readable system I have can handle that just fine.

Simpler systems just can't deal with the kind of complexity WotC is going to throw at us.

**Comment by ancestral** [comment]
Given the complexities we’ve witnessed with Collector’s Edition packs, Promo Packs, and now how [Theme Boosters will feature unique rares in THB](https://magic.wizards.com/en/articles/archive/card-preview/theros-beyond-death-theme-boosters-2019-12-17) not found in booster box packs, I feel like this booster generation is something that either should be dropped as a feature, or pushed to version 5 or later.

**Comment by ZeldaZach** [comment]
I somewhat agree, @ancestral . I'm gonna need a new format for boosters, and nothing we have currently will support what I"d like. I plan on supporting, in V3 format, only draft boosters. Will be working on V5 and ideas for that soon.

**Comment by HerveH44** [comment]
@taw Hi, I am currently trying to refactor dr4ft backend. I think I could use your booster generation file. I'd like to know if you can get it available through APIs. Also I don't know if you want to change some things, but I'd love to have the weight of the cards as a key in the sheet (so it would be easier to calculate the odds). For example instead of 

`      "mh1_basic": {
        "cards": {
          "mh1:250": 1,
          "mh1:251": 1,
          "mh1:252": 1,
          "mh1:253": 1,
          "mh1:254": 1
        }
      },`

I think it would be better:
`      "mh1_basic": {
        "cards": {
          1: ["mh1:250", ""mh1:251", "mh1:252", "mh1:253","mh1:254"]
        }
      },`

Also if there's still some room for change, instead of the query, (set+number etc) would it be possible to just get the uuid of mtgjson ?

Also, how do you handle balance_colors?

**Comment by taw** [comment]
@HerveH44 

I can setup something similar to https://github.com/taw/magic-preconstructed-decks-data for API.  I could do some trivial structure changes, but it's easy to do it at consumer level as well. I forgot mtgjson added uuids, I could make a json with those too.

[All the code is here](https://github.com/taw/magic-search-engine/tree/master/search-engine/lib).

[In particular color balancing code is here](https://github.com/taw/magic-search-engine/blob/master/search-engine/lib/color_balanced_card_sheet.rb). This needs to be done by code as naive way (rerolling commons if there's a duplicate) introduces big bias.

Color balancing is generally by color identity (some early multicolor sets were balanced by color not identity).

Most of the interesting code is between [this](https://github.com/taw/magic-search-engine/blob/master/search-engine/lib/pack_factory.rb) and [this](https://github.com/taw/magic-search-engine/blob/master/search-engine/lib/card_sheet_factory.rb) file.

If you're interested in using this data, let's get in contact.

**Comment by HerveH44** [comment]
@taw I wrote to your mail address Tomasz.Wegrzanowski@gmail.com. Is it correct? I don't know how to reach you privately otherwise :( !

I did a first implementation very basic and it seems to work.

**Comment by taw** [comment]
I setup JSON data export to: https://github.com/taw/magic-sealed-data in two formats (compact one, and one with uuids for easier interoperability). Hopefully this will be useful to someone.

**Comment by ZeldaZach** [comment]
I'm honestly happy with the work @taw did at https://raw.githubusercontent.com/taw/magic-sealed-data/master/sealed_basic_data.json and I'm going to consider importing it as a separate file within MTGJSON (AllBoosterPackLayouts (?))

**Comment by ancestral** [comment]
Technically, the weighting of commons on the commons sheet isn’t weight of 1. The commons are actually printed across multiple sheets of 121 cards, so a handful of commons are technically more common than others. I think it ends up being two sheets, meaning there are 40 commons in a large set that appear slightly more often than others. Wizards will supposedly select a handful to occupy those commons they want slightly more often in draft and let them occupy those slots.

I am struggling to find a source to prove this, but I do remember Mark Rosewater mentioning this on the Wizards site, his Tumblr, or his Drive to Work podcast.

**Comment by taw** [comment]
@ancestral [Here's one source](http://www.lethe.xyz/mtg/collation/101-commons.html)

Anyway, the real collation process is really complicated. I think what I have is the best machine readable information, but it could be improved. If we know which common is half-rarity, we could simulate this.

Some of the time it's a decent guess - like M10 has just one colorless common Terramorphic Expanse so I'd bet a beer that's one - but I don't think there's any official source of that.

(also right now my color balancing algorithm doesn't work for sheets with different rarities, but I could figure out some way to fix that)

**Comment by ZeldaZach** [comment]
Took just under a year, but we got this done! ✋
