### ISSUE TITLE
PWAR missing TCGPlayerID

### ISSUE THREAD

**Issue by jmcsmith** [mtgjson/mtgjson#361]
PWAR is missing TCGPlayerID for all cards except Deliver Unto Evil.

**Comment by ZeldaZach** [comment]
Upstream; cc: @csuhta

**Comment by jmcsmith** [comment]
appears to be corrected with the latest build except for the Japanese plainswalkers.

**Comment by ZeldaZach** [comment]
🤷‍♂ Not much I can do then, this is a TCGPlayer issue
