### ISSUE TITLE
Missing punctuation in flavor text some cards

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgjson#361]
I have discovered some flavor text is missing punctuation. For example, Battle Mastery should have several exclamation marks. In M15, they are there, but they are missing in LRW (Lorwyn).

In LRW:

`"flavor": "\"Boom Boom Boots the size of oxcarts, then an axe like a falling sun. Elves scattered. Trees scattered. Even the hills ran for the hills\"\n—Clachan Tales",`

In M15:

`"flavor": "\"Boom! Boom! Boots the size of oxcarts, then an axe like a falling sun. Elves scattered. Trees scattered. Even the hills ran for the hills!\"\n—Clachan Tales",`

**Comment by fenhl** [comment]
This is an upstream issue: http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=145973

Only way to fix it is by overriding the relevant flavor texts in `shared/C.js`. Sounds like a lot of work to me but if anyone wants to do it, pull requests are always welcome.

**Comment by bakert** [comment]
These overrides would now live in the respective set_configs rather than in C.js which has been trimmed down.

**Comment by ZeldaZach** [comment]
Addressed in V4
