### ISSUE TITLE
Missing Multiverse ID values for Modern Horizons (MH1)

### ISSUE THREAD

**Issue by RDWonline** [mtgjson/mtgjson#362]
I downloaded the latest version of MTGJSON AllSets.json (4.4.1) and inserted the contents to my local MySQL databases.  After running it twice I confirmed that the multiverseID value does not exist for any of the MH1 cards.

**Comment by hankinsoft** [comment]
Signature Spellbook: Gideon is also missing MultiverseIds.

**Comment by ZeldaZach** [comment]
Upstream: cc @csuhta

**Comment by csuhta** [comment]
MH1 has been updated on Scryfall
SS2 is not on Gatherer yet
