### ISSUE TITLE
HHO uses unnecessary (b) for second printing

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#363]
#### MTGJSON Version: 4.4.0

https://mtgjson.com/json/HHO.json

#### Description of Bug:

"Gifts Given (b)"  / "Gifts Given" 
"Stocking Tiger (b)" / "Stocking Tiger"

They differ by just presence or absence of "Happy Holidays YYYY" in corner of the art, so they should just have same name as their base card.

It's not like Very Cryptic Commands, which have completely different card text.

**Comment by ZeldaZach** [comment]
It's considered a "variation", so it should be marked in the variation field, not card name. Will look into this.
