### ISSUE TITLE
Several set name translations are inaccurate

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson#364]
#### Description of Bug:
- Betrayers of Kamigawa has wrong french translation:
`"French": "神河謀叛",` in `translations`<br>
Same problem for "Champions of Kamigawa", and maybe others?

- Japanese translations are often framed in `『』` signs, see https://github.com/mtgjson/mtgjson-website/issues/187#issuecomment-499261172.

- Some sets contain an empty translations array: `"translations": {}`,
I assume that's the case when there are no official translations or the set got only printed in english.
However, other sets have the same string copied over to all languages. That should be one way or the other.

- `Commander 2017 EDITION` has "Edition" written in capslock, others sets have a similar issue

**Comment by ZeldaZach** [comment]
My translations come directly from `https://magic.wizards.com/en/products/card-set-archive` by changing "en" to the appropriate language. As such, I'm hesitant to change it unless we can get a full list of all mandatory changes. I'd rather keep this system automated if possible.

**Comment by ZeldaZach** [comment]
I think this function disagrees with my prior comment: https://github.com/mtgjson/mtgjson/blob/master/mtgjson4/provider/wizards.py#L386 As such, if someone provides me a list of corrections I'm more than willing to import and apply them.

**Comment by lionelh** [comment]
Hello,
Here is a list of all the incorrect French translations i have found :
Fourth edition is still in English (the right French value is "Quatrième édition")
Ice age is still in English (the right French value is "Ère glaciaire")
Homelands is still in English (the right French value is "Terres natales")
Fifth edition is still in Enfliqh (the right French value is "Cinquième édition")
Weatherlight is still in English (this right French value is "Aquilon")
Tempest is still in English (the right French value is "Tempête")
Stronghold is still in English (the right French value is "Forteresse")
Exodus is still in English (the right French value is "Exode")
Urza's saga is still in English (the right French value is "L'épopée d'Urza")
Urza's legacy is still in English (the right French value is "L'héritage d'Urza")
Classic Sixth Edition is still in English (the right French value is "Sixième édition")
Urza's destiny is still in English (the right French value is "La destinée d'Urza")
Mercadian Masques is still in English (the right French value is "Masques de Mercadia")
Prophecy is still in English (the right French value is "Prophétie")
Seventh Edition is still in English (the right French value si "Septième édition")
Champions of Kamigawa is in Japanese (the right French value is "Guerriers de Kamigawa")
Betrayers of Kamigawais in Japanese (the right French value is "Traîtres de Kamigawa")
Saviors of Kamigawa is in Japanes (the right French value is "Libérateurs de Kamigawa")
Rivals of Ixalan the translation is right but in uppercase as this is the only one in uppercase, could you fix also this ?

I hope those information could help you to have a better set of informations

**Comment by lionelh** [comment]
Here is the list in CSV format (first column is the set's code and second column is the French translation).
The list only contains the sets wich need translation fix.

[french-translation-fix.txt](https://github.com/mtgjson/mtgjson/files/3643326/french-translation-fix.txt)

**Comment by lionelh** [comment]
Hello @ZeldaZach 
Here is a CSV file with an upated list of fixed french trnaslation. I also put some comment because for some expansion there are french translation but that expansion was never print in french.

[french-translation-fix.txt](https://github.com/mtgjson/mtgjson/files/4557648/french-translation-fix.txt)

**Comment by ZeldaZach** [comment]
Thanks for that @lionelh I've applied it as a fix to mtgjsonv5 (still in development)

**Comment by ZeldaZach** [comment]
As translation fixes come in, I'll add them to the override. But this should be on a ticket-by-ticket bases, not in a block ticket like this.
