### ISSUE TITLE
Deck Naming

### ISSUE THREAD

**Issue by Buried-In-Code** [mtgjson/mtgjson#365]
#### Description of Bug:
There are 3 decks called "Jace", 1 for JVC, 1 for DDM and 1 for DD2.
Due to the way it is setup they all try to use the link: https://mtgjson.com/json/decks/Jace.json which resolves to the JVC deck making it not possible to get the decks for DDM and DD2

**Comment by Buried-In-Code** [comment]
Looking at other decks this also applies to "Liliana"
M19, GVL, DDD resolves to M19
https://mtgjson.com/json/decks/Liliana.json

**Comment by ZeldaZach** [comment]
cc: @taw

**Comment by taw** [comment]
Well, that's what Wizards does a lot so 🤷‍♂ . They won't have unique names.
They also reprint the same deck a lot, so it will definitely have same name.
(also funny story, Planechase Anthology reprinted decks, but they have different decklists as plane cards are not really included in reprinted decks, but in a separate all-planes deck, just in case you thought it's not complicated enough)

I use urls like http://mtg.wtf/deck/m19/liliana
That's totally unique

**Comment by Buried-In-Code** [comment]
It's not so much about the unique names, i'm just seeing if something can be added to make them unique as you have done for your urls

**Comment by ZeldaZach** [comment]
My compromise is to rename them `name_setcode.json` if you think that would be helpful

**Comment by Buried-In-Code** [comment]
Yes that would definitely be helpful, thanks
