### ISSUE TITLE
Wrong data for Liliana Death Wielder Planeswalker Deck

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgjson#368]
#### MTGJSON Version: 4.4.1
MTGJSON Version: 4.4.1
#### Description of Bug:
Wrong data in this JSON file.

The JSON file says there are two of every card, but that’s not the case in real life. There are:

    1 Liliana, Death Wielder
    1 Channeler Initiate
    1 Oracle's Vault
    2 Liliana's Influence
    1 Festering Mummy
    2 Dune Beetle
    4 Tattered Mummy
    2 Baleful Ammit
    3 Desiccated Naga
    2 Gravedigger
    1 Crocodile of the Crossing
    2 Giant Spider
    2 Decimator Beetle
    4 Foul Orchard
    1 Grasping Dune
    4 Swamp (261)
    4 Swamp (262)
    3 Swamp (263)
    3 Forest (267)
    3 Forest (268)
    3 Forest (269)
    2 Trial of Ambition
    1 Edifice of Authority
    1 Luxa River Shrine
    2 Cartouche of Ambition
    2 Splendid Agony
    2 Cartouche of Strength
    1 Gift of Paradise

Note: The lands are not full art lands.

**Comment by ancestral** [comment]
![IMG_0959](https://user-images.githubusercontent.com/735024/59400993-d87ca380-8d5e-11e9-8e48-c895d90a3a0a.jpeg)

**Comment by ZeldaZach** [comment]
Upstream issue

cc: @taw

**Comment by taw** [comment]
> The JSON file says there are two of every card, but that’s not the case in real life.

Where do you see "two of every card"?

https://mtgjson.com/json/decks/LilianaDeathWielder_AKH.json shows correct card numbers.

Full art basics are a mistake, I'll add some logic to it to figure out correct basics.

**Comment by ancestral** [comment]
In the JSON file, there are two Liliana, Death Wielder, aren’t there?

**Comment by taw** [comment]
Oh right, it seems so. I thought you meant `count`s are all `2`. All decks seem to have their contents duplicated :-/

**Comment by ancestral** [comment]
I believe other decks also have duplicated contents too.
