### ISSUE TITLE
HOU — Hour of Devastation

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgjson#370]
HOU is now on Gatherer.

HOU pre-release is in a week.

**Comment by gwax** [comment]
This is committed to master but hasn't been released yet.

**Comment by ancestral** [comment]
Cool, I figured as much, but thought it wouldn’t hurt to track this.

Thanks!

**Comment by membran** [comment]
If I may ask here, I only recently began following and using this project here, what's the usual release cycle / refresh of the downloadable files on mtgjson.com? I took a look at the changelog on the website but couldn't spot a pattern in it at first glance. 

So I guess what I'm asking is, is there any ETA on the next release?

**Comment by fenhl** [comment]
We try to release a new version as soon after Gatherer updates as possible. Unfortunately, @lsmoura (the only person who has access to the website and can cut releases) has not been responding to messages lately. This is the main reason that releases have been late. @ZeldaZach is considering setting up a copy of the website at a different location to facilitate timely releases for HOU and in the future.

**Comment by taw** [comment]
Can I generate `AllSets-x.json` locally somehow?

I tried following instructions locally, but everything just crashes.

**Comment by gwax** [comment]
@taw unfortunately, a bunch of stuff appears to be broken right now. I'm working through fixing a bunch of things but I haven't fixed everything and it takes some time for things to go from me fixing it to getting through a PR.

**Comment by fenhl** [comment]
We will be setting up the new website on Monday if we don't hear from @lsmoura during the weekend.

**Comment by broady** [comment]
Looks like it's up there now?

**Comment by taw** [comment]
HOU Masterpieces are missing from the new release.

(also a lot of old stuff seems broken)

**Comment by fenhl** [comment]
Masterpieces have been added. For other bugs, please refer to other relevant issues (or open one if it's not reported).
