### ISSUE TITLE
DPA foiling is wrong

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#370]
#### MTGJSON Version: 4.4.1

https://mtgjson.com/json/DPA.json

#### Description of Bug:

It's marked as all nonfoil, but 5 of those cards are actually foils:

* Ascendant Evincar
* Immaculate Magistrate
* Kamahl, Pit Fighter
* Mahamoti Djinn
* Verdant Force

Reference: https://mtg.gamepedia.com/Duels_of_the_Planeswalkers_(decks)

**Comment by ZeldaZach** [comment]
Upstream issue, thanks for the find

cc: @csuhta

**Comment by csuhta** [comment]
Fixed on Scryfall
