### ISSUE TITLE
DDR foiling is missing

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#371]
#### MTGJSON Version: 4.4.1

https://mtgjson.com/json/DDR.json

#### Description of Bug:

In Duel Decks: Nissa vs. Ob Nixilis deck, all cards are marked as non-foil, but these are actually in foil version:

* Nissa, Voice of Zendikar
* Ob Nixilis Reignited 

As can be easily verified by star in their footer, or [any box opening video](https://www.youtube.com/watch?v=l7GD7ocRBCQ).

**Comment by ZeldaZach** [comment]
Upstream issue
cc: @csuhta

**Comment by csuhta** [comment]
Fixed on Scryfall
