### ISSUE TITLE
Italic format correct?

### ISSUE THREAD

**Issue by DJCatBlitz** [mtgjson/mtgjson#372]
#### Description of Bug:
I'm not sure if this is working as intended, but it is the first time, that my parser found &lt;i&gt (italic format) in ability texts for english texts. (for cards: Arcum's Astrolabe and Icehide Golem)
Is this intended?

**Comment by ZeldaZach** [comment]
Upstream issue. Nice catch :)

cc: @csuhta

**Comment by csuhta** [comment]
Fixed on Scryfall
