### ISSUE TITLE
MIR:87† marked as having foil

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#374]
#### MTGJSON Version: 4.4.1

https://mtgjson.com/json/MIR.json

#### Description of Bug:

So there's this card in MIR, which seems to be a Spanish alt art, and mtgjson thinks it has both foil and nonfoil versions. 

While I'm no expert on rare foreign printings, this seems pretty unlikely as [first foils were only released two years after Mirage](https://mtg.gamepedia.com/Foil_card). And also looked nothing like this card: https://scryfall.com/card/mir/87%E2%80%A0/es/reality-ripple
More like this card: https://scryfall.com/card/ppre/4/lightning-dragon

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
This card is already marked as nonfoil only on Scryfall. Maybe stale data?

**Comment by ZeldaZach** [comment]
Could be. I'll be building Sunday so no worries.
