### ISSUE TITLE
M19 Pendulum of Patterns marked as having foil

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#375]
#### MTGJSON Version: 4.4.1

https://mtgjson.com/json/M19.json

#### Description of Bug:

This baffled me, as it's a common from Tezzeret planeswalker deck. Deck opening videos reveal 4 nonfoils in Tezzeret planeswalker deck, I can't find any information about it, and nobody actually sells it (a few sites list it with "none in stock" for foil version, they probably just list every card).

I'm like 99% sure this is a bug.

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
Fixed on Scryfall
