### ISSUE TITLE
Split card data seems to be off, data references only one side of card

### ISSUE THREAD

**Issue by petejohnson84** [mtgjson/mtgjson#375]
I have been syncing data from mtgjson to a database somewhat frequently and noticed something interesting when some new split card data made it's way into my database. For example, when searching through the json data manually (https://mtgjson.com/json/AllSetsArray.json) for string "orderchaos" I get six matches which seems correct (Commander 2016, Apocalypse, Planechase, two matches for each set because each side order and chaos). But in the data, each object seems to reference the order side, none of the data represents the chaos side. In my older data, there appears to be data for chaos side, but I'm not seeing it in the latest data. I am seeing this for many split cards.

**Comment by fenhl** [comment]
Aftermath cards appear to be unaffected.

**Comment by bakert** [comment]
This is breaking a lot of our stuff for the Penny Dreadful format (our main website, and if we reboot our bot that will go down too) at a crucial time (rotation). It would be really awesome to know if this is being actively worked on or not. If not I will dig in and try and fix it and send a pull request. But if experts on the codebase are already doing it I won't as I'll surely be slower/worse :)

**Comment by fenhl** [comment]
As pointed out in #359, this may have been introduced in #328 (not confirmed), which would mean that the split cards were never coded correctly.

**Comment by fenhl** [comment]
A bisect confirms that #328 introduced this, which probably means that someone who knows how the Gatherer interface works should take a look at this. @ZeldaZach? @gwax?

**Comment by gwax** [comment]
I'll take a look.

**Comment by gwax** [comment]
Seems like the gatherer api changed. I think that I have a fix but I need to check it doesn't break anything else and then do a rebuild.
