### ISSUE TITLE
VMA really has one extra rarity

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#378]
#### MTGJSON Version: 4.4.1

https://mtgjson.com/json/VMA.json

#### Description of Bug:

So mtgjson v4 decided to get rid of `special` and `basic` rarities. 

This is mostly fine, but VMA really has one extra rarity beyond mythic, and it's currently not indicated in any way.

`boosterV3` field sort of suggests this.

Some references:

* https://mtg.gamepedia.com/Vintage_Masters
* https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=382841 (VMA special)
* https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=382914 (VMA mythic)

This can be solved in many ways, but those 9 cards should be marked somehow. Some obvious options include:

* bring `special` rarity back for this
* move the power 9 to another set (`VMA9` or something)
* throw an extra flag in for this

**Comment by ZeldaZach** [comment]
I'm still uncertain what to do with this right now, but you are correct they should have some distinction...

**Comment by taw** [comment]
I think the best match to how other sets do it (with masterpiece sets like `MPS` `EXP` etc.) is to move them to separate set. `VMA9` would be an obvious code for that.

Extra rarity or flag would increase complexity everywhere else.

**Comment by ancestral** [comment]
What is Scryfall doing here? They’re using Mythic Rare for the 382841 and 382914.

**Comment by ZeldaZach** [comment]
I'm most inclined to go with a new rarity of some kind ("Ultra Mythic Rare") or something. I don't like the idea of a new set or a new flag (that would only be active for a few cards)

**Comment by ZeldaZach** [comment]
I've decided to stick with upstream's inclination for rarity, as our new booster field (1519fe5489b9fb2894f2d75a72003a8faee134ec) better handles this. If someone wants to make a booster, we have enough details for them to do so.
