### ISSUE TITLE
BFZ/OGW non-full-art basics shouldn't have foils

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#379]
#### MTGJSON Version: 4.4.1

https://mtgjson.com/json/BFZ.json
https://mtgjson.com/json/OGW.json

#### Description of Bug:

Those two sets have two versions of each basic. The full-art ones are in boosters, and have foils and nonfoils.

The non-full-art are in intro packs only, and as far as I can tell, don't have foil versions.

References:

* https://mtg.gamepedia.com/Battle_for_Zendikar
* https://mtg.gamepedia.com/Oath_of_the_Gatewatch
* nonfoils for sale - http://www.starcitygames.com/catalog/category/5308?&color=L
* foils for sale - http://www.starcitygames.com/catalog/category/5309?&color=L

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
Fixed on Scryfall
