### ISSUE TITLE
5ED had no foils

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#380]
#### MTGJSON Version: 4.4.1

https://mtgjson.com/json/5ED.json

#### Description of Bug:
5 variant cards in 5ED are marked as `"hasFoil": true`. 

Foils didn't exist back then. [The first core set that had foils was 7ED](https://mtg.gamepedia.com/Seventh_Edition).

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
Fixed on Scryfall
