### ISSUE TITLE
WC02 World Championships Ad is listed as card, should be token

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#381]
#### MTGJSON Version: 4.4.1

https://mtgjson.com/json/WC02.json

#### Description of Bug:

`2002 World Championships Ad` is in wrong place. It should be in tokens, is in cards.

**Comment by ZeldaZach** [comment]
🤷‍♂ It's not a card nor a token. I'd lean towards tokens for sure. Will see what upstream thinks, then make my move

**Comment by taw** [comment]
There's a bunch of other things with `"type": "Card"` even in the same set, all in tokens, so this one should definitely go where they go.

Other WC* sets do the same, putting various `"type": "Card"` stuff in tokes. This one just disagrees with all other such cases.

**Comment by silasary** [comment]
Fixed upstream
