### ISSUE TITLE
Missing watermarks on basic lands

### ISSUE THREAD

**Issue by fenhl** [mtgjson/mtgjson#382]
#### Description of Bug:

MTG JSON 3 had the mana symbols in the `"watermark"` field on basic lands where appropriate (e.g. in *Portal* but not in *Alpha*). These seem to be missing in v4 in all or almost all sets.

**Comment by ZeldaZach** [comment]
Feature not brought over from V3. Do you have any reasons why this should be?

**Comment by fenhl** [comment]
The information is simply missing. The cards have watermarks but MTG JSON does not list them.

**Comment by ZeldaZach** [comment]
https://markrosewater.tumblr.com/post/167578433383/for-druid-of-the-scared-beaker-do-the-mana#notes

I'm gonna call this a no fix based on upstream and maro responses. Sorry mate <3
