### ISSUE TITLE
Decks don't show lands

### ISSUE THREAD

**Issue by Buried-In-Code** [mtgjson/mtgjson#383]
#### Description of Bug:
When you pull a deck, example 'Goblins_DDT' it clumps all the lands into 1 giving the impression there are 20 of the same Mountain land cards rather than split across the 4 possible Mountain land cards.
As far as I can tell this is happening with all the decks.

**Comment by taw** [comment]
Hi @Macro303 

I maintain the decks data in mtgjson.

So the way it works is:

* there's collection of decklists like https://github.com/taw/magic-preconstructed-decks/blob/master/data/cmd/c18/Subjective%20Reality.txt with links to original source (some annotations like which card is a foil, error corrections etc. are just in the repo)
* there's a multistage indexer which uses some logic to translate those decklists into what mtgjson needs
* which is then pushed to this intermediate repo - https://github.com/taw/magic-preconstructed-decks-data
* mtgjson software then rearranges this data into most convenient form and publishes it

The indexer can automatically figure out which set each card is from. Precon cards are from given precon only, standard-legal decks use cards from all standard sets, and it's aware of all exceptions like clash packs, welcome decks, MTGO decks etc.

As far as I know this is all accurate. Maybe if the same card was reprinted in multiple standard legal sets, and then in a standard deck, but not coming from latest set, then it would be wrong. I'm not sure if they ever did that, and even if they did it would most likely be a basic.

What indexer can't figure out automatically is which specific printing in a set it is. Indexer is aware of some rules like with full art cards, but if original sources just say that deck has 20 Mountains, and that set contains 4 possible Mountains, it has no way to decide which combination of Mountains to use. And every single source is like that.

The software is totally ready for manual fixes, which we use for just DKM and foils ([example](https://github.com/taw/magic-preconstructed-decks/blob/master/data/theme-62/dkm/Finkel.txt)).

In principle if anyone's really determined to watch box opening videos on youtube and write down which basics in which numbers there are, we could add that, but I'm not volunteering for that role. (and most videos quickly skip over basics anyway to frustrate such efforts even more)

By the way, at least we have correct set, decklist visualizers on most websites will just use most recent printing, but [data in mtgjson](http://mtg.wtf/deck). Compare:
* [mtgjson data](http://mtg.wtf/deck/nph/feast-of-flesh)
* [basically anything else](https://magic.wizards.com/en/articles/archive/new-phyrexia-intro-packs-2011-05-12#deck3)


I hope that helps.

**Comment by ZeldaZach** [comment]
I'm leaning towards agreeing with Taw here. Not sure if we can do much more without a solid background knowledge bank. If what we provide isn't satisfactory to your needs, please do reach out and I'll see if we can come up with an alternative together :)

**Comment by Buried-In-Code** [comment]
Thanks @taw for the info. That's fine, if there's no source to pull it from then sticking with what you have is good enough
Yea I don't think anyone would want to watch that many videos that closely. 😆
