### ISSUE TITLE
Links under "Additional JSON Files" section on mtgjson.com result in nginx 404

### ISSUE THREAD

**Issue by petejohnson84** [mtgjson/mtgjson#387]
I recently noticed that links under "Additional JSON Files" section on this page http://mtgjson.com/documentation.html result in nginx 404. For example, http://mtgjson.com/json/SetList.json. I believe this was working a day or two ago.

**Comment by ZeldaZach** [comment]
Can you try again? The SetList.json file is working for me correctly right now

**Comment by petejohnson84** [comment]
Yes working now, it was strange because all other links on the site seemed to work fine except those 5 under "Additional JSON Files"

**Comment by ZeldaZach** [comment]
Sounds good, lmk if anything comes up again!
