### ISSUE TITLE
What's up with PZ1 and PZ2 ?

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#389]
#### MTGJSON Version: 4.4.1

https://mtgjson.com/json/PZ1.json
https://mtgjson.com/json/PZ2.json

#### Description of Bug:

PZ2 claims to refer to https://mtg.gamepedia.com/You_Make_the_Cube
Or maybe it's meant to be https://mtg.gamepedia.com/Treasure_Chests

Cube list is presumably https://magic.wizards.com/en/MTGO/articles/archive/magic-online/you-make-cube-voting-2016-10-17 (under "SIMONOT TIMOTHÉE'S TWISTED COLOR PIE").

But size is different (282 vs 540), content is completely different, and from two years after release date, numbers are all over the place.

Did something get really messed up on the way?

PZ1 (Legendary Cube) is only off by one card by size, and it could plausibly be original Legendary Cube.

Anyway, I'm not sure we should even have those sets, at least not with much better quality sources, and much more clarity on what those extra sets are supposed to be.

MTGO had a lot of cubes over the years, and they also changed what was in cube under same name many times. Like [is this PZ1 v2](https://magic.wizards.com/en/articles/archive/magic-digital/legendary-cube-returns-2016-03-23) ? Treasure chest contents also changed on the way.

**Comment by silasary** [comment]
These sets refer to the prize packs associated with the cubes, and are the only method in which cards from recent precons/supplemental sets are made available online

**Comment by ZeldaZach** [comment]
Closing as a no-fix since SF updated the names and the set codes don't really mean what they originally did back then.
