### ISSUE TITLE
Add a foil information per card

### ISSUE THREAD

**Issue by Sembiance** [mtgjson/mtgjson#39]
There should be foil information on a per card level. Early sets had no foils, later sets had foils, some sets like Planeshift had just a few cards that could be foil and some sets are foil only.

Right now there is no way to identify using solely the MTGJSON data which sets/cards are available in foil format so this information would be useful.

**Comment by Sembiance** [comment]
Lots of ways this could be done. A 'foilable'/'foilOnly' boolean at set and card level. Or perhaps an array at set level like this:
{..., "code": "LEA", ..., "possibleCardStock": ["nonfoil"], ...}
{..., "code": "MMQ", ..., "possibleCardStock": ["nonfoil", "foil"], ...}
{..., "code": "V14", ..., "possibleCardStock": ["foil"], ...}
Then if specific cards were an exception (like PLS foils) then I could have a card level field as well.

- All sets pre-Urza's Legacy are non foil. (except that Urza's Saga, the set before Legacy, which actually had the first foil in the pre-release promo Lightning Dragon).
- Sets after Legacy are generally "foilable", except that there are a lot of instances of sets that are not, like Coldsnap theme decks.
- Foil only is cards like Lightning Dragon, From the Vault, etc.  The problem with having the foil status be per set is that some sets have cards that are foil only and non foil, such as Media Inserts and all of the Duel Decks, which will typically have a single foil only card and no other foils.

Lastly, it may be tricky/work intensive to come up with and maintain some of this info for promo sets/cards.

**Comment by Sembiance** [comment]
Unhinged had 'alternate art' cards that don't exist on gatherer. The only difference with these cards are they are foil and have some secret words/symbols in the foiling. They will also need to be considered when adding this per card foil information.

**Comment by Sembiance** [comment]
Additionally, according to http://www.magiclibrarities.net/172-rarities-deckmasters-box-set-cards-english-cards-index.html the DKM set had both foil and non-foil versions of Icy Manipulator and Incinerate. The foil versions had black borders. The Lhurgoyf and Necropotence cards were also available as foils in this set but ONLY as foils and were not available in non-foil in this set, they also had black borders. I should probably add foil:true to these two cards, and then add a new entry for the Icy Manipulator and Incinerate which correctly mark foil : true and also border : black

**Comment by fenhl** [comment]
I am working on this now. I have decided to go with a `"foil"` field on sets and cards with similar semantics to the `"border"` field (sets always have it, cards may override), with the following possible values:

* `"some"`: Cards exist both in foil and regular versions. The norm for current sets.
* `"all"`: All cards are foil, e.g. From the Vaults. In Duel Decks, this would be set for the foil card in each deck.
* `"none"`: No cards are foil. The norm for old sets, and supplemental product like Commander or Duel Decks.
* `"alt"`: Cards exist both in foil and regular versions, but the foils have additional differences and are thus listed as their own card, e.g. _Unhinged_, Icy Manipulator (DKM), Incinerate (DKM), or [Kaya, Ghost Assassin](https://mtg.wtf/card/cn2/75) (CN2).

**Comment by PeerRich** [comment]
do you need assistance? I'd love to use this feature :)

**Comment by fenhl** [comment]
I haven't had much time to work on MTG JSON lately. [This](https://github.com/fenhl/mtgjson/commit/849c87f82eadfc7d6de292d58b8876d51d94d803) is all I have done so far, and it needs to be rebased onto the refactored C.js. If you would like to help, pull requests on [my `foil` branch](https://github.com/fenhl/mtgjson/tree/foil) would be appreciated.

**Comment by fenhl** [comment]
Rebased onto current master.

**Comment by ZeldaZach** [comment]
@fenhl Any news on something like this?

**Comment by fenhl** [comment]
I don't really have the time to work on this right now. Will have to migrate this to v4 once it's ready.

**Comment by ZeldaZach** [comment]
Sounds good

**Comment by ZeldaZach** [comment]
Added in V4 :)
