### ISSUE TITLE
10E originalText

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#392]
#### MTGJSON Version: 4.4.1

https://mtgjson.com/json/10E.json

#### Description of Bug:

This is a bit nitpicky bug, but 10E has regular (with reminder text) and foil (without reminder text) versions.

Those foils lack any `originalText`. It could be generated with a regexp from base card `originalText` (just remove everything in parentheses).

(I don't use `originalText` myself, and I always pre-strip reminder text anwyay, except for uncards, but it's in mtgjson data, so presumably someone uses it)

**Comment by ZeldaZach** [comment]
originalText comes from gatherer, which doesn't discern cards at this level. I could agree with you here, though. I'll add something in. Are there any other sets that have this rule?

**Comment by taw** [comment]
As far as I know it was a 10E only gimmick.

[Also foil versions without reminder text sometimes had extra flavor text instead](https://mtg.gamepedia.com/Tenth_Edition/Changes#Added_flavor_text), but mtgjson seems to handle this just fine already.
