### ISSUE TITLE
Can we get some flag for partially spoiled sets in progress?

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#393]
#### MTGJSON Version: 4.4.1

https://mtgjson.com/json/M20.json etc.

#### Description of Bug:

There are probably some hacks to detect this already, as it misses a lot of data, but could we just get some flag like `isIncompleteSpoiler`?

**Comment by ZeldaZach** [comment]
My initial thought is they can read the releaseDate and understand the set's not released. Do you really think something like this would be needed? (If so, this is how I would do it anyway...)

**Comment by taw** [comment]
Well, sets tend to get fully spoiled awhile before getting released, and checking `releaseDate` against current date isn't really reliable, as you'd also need to know which exact date mtgjson got its data at.

A flag would be simplest solution.

**Comment by ZeldaZach** [comment]
Fair enough, I can add an internal flag for `if (build.date() < releaseDate) { add flag }`
