### ISSUE TITLE
MagicCards.info comparison fails on Æ cards.

### ISSUE THREAD

**Issue by gwax** [mtgjson/mtgjson#395]
Sentences in card titles that start with Æ were replaced with Ae by WotC but MagicCards.info hasn't caught up. Then we get a bunch of does not match errors.

**Comment by ZeldaZach** [comment]
Can we catch them in a regex/replace?

**Comment by bakert** [comment]
Duplicate of, or related to, #304

**Comment by ZeldaZach** [comment]
Dupe #304
