### ISSUE TITLE
Some flags for isPaper isMTGO isArena

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#396]
So mtgjson still has v3 style `isDigital`, but it only covers 2 out of 7 possible combinations.

It would be nice to tag per-set if card exists as paper / MTGO / Arena card.

**Comment by ZeldaZach** [comment]
Hmm... do you have a source to mark this as appropriate?

**Comment by ZeldaZach** [comment]
Hmm... do you have a source to mark this as appropriate?

Upstream only has "digital" so I have no real way of discerning it... tag @csuhta

**Comment by csuhta** [comment]
`digital` on Scryfall means that the specific print is only on digital games, never paper. We also provide the `games` array on each card object to show which systems you can obtain the card in. Perhaps use that instead of `digital`?

**Comment by ZeldaZach** [comment]
Learn something new everyday. Thanks, Corey!
