### ISSUE TITLE
Loyalty costs are formatted wrong

### ISSUE THREAD

**Issue by fenhl** [mtgjson/mtgjson#397]
The loyalty costs in planeswalker abilities are not formatted like in the plain-text version of the Comprehensive rules, which is surprising since all other symbols do conform to the syntax (except for level symbols, whose special formatting I think is justified, given their complex layout).

What we have:

```
+2: Scry 2.
```

How it should look:

```
[+2]: Scry 2.
```

Changing this to use the official syntax would make finding them (and thus e.g. rendering them as graphical symbols) easier for clients.

**Comment by ZeldaZach** [comment]
I can agree with this change

**Comment by fenhl** [comment]
This seems to be complicated by Gatherer itself using the nonstandard syntax.

**Comment by ZeldaZach** [comment]
Addressed https://github.com/mtgjson/mtgjson-python/commit/85b599bb20182c7f09d90eca978eabf7f60b1d15
