### ISSUE TITLE
Treat planeswalker loyalty cost as symbol

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#400]
So mana costs are marked like `{2}{W}`, but planeswalker loyalty abilities are just `+2` or `0`.

What I do with some simple regexps is converting:
```
+1: Create two 3/1 red Elemental creature tokens with haste. Exile them at the beginning of the next end step.
0: Discard all the cards in your hand, then draw that many cards plus one.
–X: Chandra, Flamecaller deals X damage to each creature.
```

to:

```
[+1]: Create two 3/1 red Elemental creature tokens with haste. Exile them at the beginning of the next end step.
[0]: Discard all the cards in your hand, then draw that many cards plus one.
[–X]: Chandra, Flamecaller deals X damage to each creature.
```

[Which then can be displayed with proper styling](http://mtg.wtf/card/ogw/104/Chandra-Flamecaller).

Maybe this feature could be upstreamed. Almost all other special symbols in text box (like mana, energy) get tagged, why not this one?

The only other symbol I can think of not being tagged yet is [level symbol like](http://mtg.wtf/card?q=hexdrinker):

```
Level up {1}
LEVEL 3-7
4/4
Protection from instants
LEVEL 8+
6/6
Protection from everything
```

But that's way less relevant than planeswalkers.

**Comment by ZeldaZach** [comment]
Interesting approach. @csuhta What do you think?

**Comment by taw** [comment]
Oh and I'm using different brackets as `[0]` loyalty ability and `{0}` mana cost would conflict otherwise.

**Comment by omfgitsmark** [comment]
I kinda love this idea. While looking at the plain text of a Dovin PW the other day I was thinking about how cluttered it looked and it not being very readable. 

Along with the "Level Up" cards I'd like to add Saga enchantments to the list as well, though they are still not as relevant as PWs either.

**Comment by lfgcampos** [comment]
Sounds like a good idea!!
Displaying them properly would be a very nice addition to most of the projects that use mtgjson.
