### ISSUE TITLE
All 3 pieces to meld cards have 'layout: normal' & Missing/Incorrect Fields

### ISSUE THREAD

**Issue by bakert** [mtgjson/mtgjson#400]
They have "normal" for layout instead. And "names" is just the front side and the melded card, not the other card needed to form the meld as it was in previous versions.

Probably this had the same problem as the split cards but didn't get cleaned up at the same time?

**Comment by fenhl** [comment]
The following fields are incorrect or missing:

* `"cmc"`
* `"colorIdentity"`
* `"layout"`
* `"names"`

**Comment by ZeldaZach** [comment]
cc : @gwax
