### ISSUE TITLE
isMisprint

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#401]
mtgjson v4 has a bunch of variant cards that are basically misprints like MIR 87†, 4ED 243† etc.

I'm not totally sure if they should really be included, but they should probably be marked with `isMisprint` or something.

For extra complication ARN has accidental printing variants, but they're officially acknowledged, so not sure if they should count as misprints or not.

**Comment by ZeldaZach** [comment]
We only include 'misprints' that were widespread. Simple misprints that occur normally as one or two offs are not included. I'm not opposed to a flag to denote them, but I'm not sure if this is the right move.

Looking for more insight by the community.

**Comment by ZeldaZach** [comment]
See `isAlternative`
