### ISSUE TITLE
UNH foil cards have no reason to be marked (b)

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#404]
#### MTGJSON Version: 4.4.2

https://mtgjson.com/json/UNH.json

#### Description of Bug:

So UST needs this silly `(b)` `(c)` etc. convention, as those cards have different text for same title, but UNH doesn't need the `(b)`. They're just usual foils with slightly fancier foiling process (like card-specific watermark and such).

**Comment by ZeldaZach** [comment]
Would you be happier seeing them as a "variation" then? (Similar to what we did with HHO)

**Comment by taw** [comment]
UNH should probably do just follow 10E and other such sets with fancy foils.
I think HHO does the same as 10E right?

**Comment by ZeldaZach** [comment]
Yep, can do.
