### ISSUE TITLE
The foreign names of 'Unesh, Criosphinx Sovereign' are all in English

### ISSUE THREAD

**Issue by zjuguxi** [mtgjson/mtgjson#405]
Unesh, Criosphinx Sovereign
From HOU, number 52

**Comment by zjuguxi** [comment]
Chinese Simplified Unesh, Criosphinx Sovereign
Chinese Traditional Unesh, Criosphinx Sovereign
French Unesh, Criosphinx Sovereign
German Unesh, Criosphinx Sovereign
Italian Unesh, Criosphinx Sovereign
Japanese Unesh, Criosphinx Sovereign
Korean Unesh, Criosphinx Sovereign
Portuguese (Brazil) Unesh, Criosphinx Sovereign
Russian Unesh, Criosphinx Sovereign
Spanish Unesh, Criosphinx Sovereign

**Comment by PAK90** [comment]
That would be because [the official page has all those names in English too](http://gatherer.wizards.com/Pages/Card/Languages.aspx?multiverseid=430741). Until WotC fixes the Gatherer data, mtgjson can't do anything about it.

**Comment by fenhl** [comment]
Alternatively, if anyone happens to know all the translated names, we could fix it.

**Comment by Vuelos** [comment]
Now it's fixed on [the official page.](http://gatherer.wizards.com/Pages/Card/Languages.aspx?multiverseid=430741)

**Comment by fenhl** [comment]
This appears to be fixed now.
