### ISSUE TITLE
Some  split cards have no mciNumber

### ISSUE THREAD

**Issue by gwax** [mtgjson/mtgjson#409]
For example: C16 - Order and Chaos are missing mciNumber values because magiccards.info lists Order twice [1](http://magiccards.info/c16/en/240a.html) [2](http://magiccards.info/c16/en/240b.html) without listing Chaos.

**Comment by ZeldaZach** [comment]
Seems like something we should report back to them.

**Comment by ZeldaZach** [comment]
MCI discontinued
