### ISSUE TITLE
Missing ForeignData fields

### ISSUE THREAD

**Issue by Fryyyyy** [mtgjson/mtgjson#41]
Some cards (mostly, from what I can tell, the back faces of transform cards) have missing or malformed ForeignData blocks.

Cards that I believe have problems:

`set(['Sage of Ancient Lore', 'Two-Headed Dragon', 'Conduit of Storms', 'Elvish Champion', 'Lambholt Pacifist', 'Heir of Falkenrath', 'Metzali, Tower of Triumph', 'Reckless Waif', 'Ghastly Haunting', 'Nicol Bolas, the Arisen', 'Chandra, Roaring Flame', 'Werewolf of Ancient Hunger', 'Extricator of Flesh', 'Town Gossipmonger', 'Daybreak Ranger', 'Liliana, Heretical Healer', 'Wayward Disciple', 'Ulvenwald Abomination', "Ludevic's Test Subject", 'Arlinn Kord', 'Persistent Nightmare', 'Lambholt Elder', 'Neck Breaker', 'Pious Evangel', 'Grizzled Angler', 'Oran-Rief, the Vastwood', 'Goblin Chieftain', 'Geier Reach Bandit', 'Nissa, Sage Animist', "Azor's Gateway", 'Primal Wellspring', 'Sakura-Tribe Elder', 'Kruin Outlaw', 'Smoldering Werewolf', 'Thraben Sentry', 'Nezumi Graverobber', 'Bane of Hanweir', 'Winged Temple of Orazca', 'Ulvenwald Captive', 'Grizzled Outcasts', 'Westvale Cult Leader', 'Delver of Secrets', 'Kuldotha Phoenix', 'Branded Howler', 'Itlimoc, Cradle of the Sun', "Chandra's Outrage", "Tovolar's Magehunter", 'Cunning Sparkmage', 'Garruk, the Veil-Cursed', 'Search for Azcanta', 'Slith Firewalker', 'Cryptolith Fragment', 'Hanweir Watchkeep', 'Stalking Vampire', 'Solitary Hunter', 'Docent of Perfection', 'Chandra, Fire of Kaladesh', 'Chalice of Life', 'Voracious Reader', "Conqueror's Foothold", 'Westvale Abbey', 'Duskwatch Recruiter', 'Lambholt Butcher', 'Treasure Cove', 'Heir to the Night', 'Ulvenwald Mystics', 'Flameheart Werewolf', 'Merciless Predator', 'Ravager of the Fells', 'Daring Sleuth', "Hadana's Climb", 'Garruk Relentless', 'Ulvenwald Primordials', 'Insectile Aberration', 'Avacynian Missionaries', 'Azcanta, the Sunken Ruin', 'Dowsing Dagger', 'Elusive Tormentor', "Conqueror's Galleon", 'Tomb of the Dusk Rose', 'Convicted Killer', 'Dronepack Kindred', 'Kindly Stranger', "Legion's Landing", 'Ruthless Cullblade', 'Awoken Horror', 'Nighteyes the Desecrator', "Jace, Vryn's Prodigy", 'Erupting Dreadwolf', 'Vault of Catlacan', 'Glorious Anthem', 'Infectious Curse', 'Silverpelt Werewolf', 'Fibrous Entangler', 'Ulrich of the Krallenhorde', 'Gatstaf Howler', 'Ravenous Demon', 'Ancient of the Equinox', 'Thing in the Ice', 'Lord of Lineage', 'Nightfall Predator', 'Incited Rabble', "Chandra's Spitfire", 'Jace, Telepath Unbound', 'Civilized Scholar', 'It That Rides as One', 'Hinterland Hermit', 'Lost Vale', 'Shivan Dragon', 'Mayor of Avabruck', 'Lone Rider', 'Loam Lion', 'Stonewing Antagonizer', 'Gatstaf Arsonists', 'Kessig Forgemaster', 'Final Iteration', 'Huntmaster of the Fells', 'Bearer of Overwhelming Truths', 'Gideon, Battle-Forged', 'Scorned Villager', 'Treasure Map', 'Instigator Gang', 'Growing Rites of Itlimoc', 'Gatstaf Ravagers', 'Pestilence Demon', 'Thaumatic Compass', 'Homicidal Brute', 'Neglected Heirloom', 'Shrill Howler', 'Aurora of Emrakul', "Ludevic's Abomination", 'Path of Mettle', 'Tangleclaw Werewolf', 'Moonscarred Werewolf', 'Serra Angel', u'Supply // Demand', 'Sanctum of the Sun', 'Thraben Gargoyle', 'Whirling Dervish', 'Loyal Cathar', 'Darksteel Juggernaut', 'Ulrich, Uncontested Alpha', 'Howlpack Alpha', 'Arlinn, Embraced by the Moon', 'Archdemon of Greed', 'Krallenhorde Wantons', 'Harvest Hand', 'Vildin-Pack Outcast', 'Grisly Anglerfish', 'Mad Auntie', 'Soul Seizer', 'Lone Wolf of the Natterknolls', 'Vildin-Pack Alpha', 'Howling Chorus', 'Phantasmal Dragon', 'Bloodline Keeper', 'Village Ironsmith', 'Unimpeded Trespasser', 'Sinuous Predator', 'Rampaging Werewolf', 'Profane Procession', 'Startled Awake', 'Storm the Vault', 'Thraben Militia', 'Autumnal Gloom', 'Giant Growth', 'Screeching Bat', 'Cloistered Youth', 'Nissa, Vastwood Seer', 'Adanto, the First Fort', 'Hermit of the Natterknolls', 'Temple of Aclazotz', 'Lunarch Inquisitors', 'Uninvited Geist', 'Royal Assassin', 'Hinterland Scourge', 'Sandbar Crocodile', 'One of the Pack', 'Soltari Priest', 'Werewolf Ransacker', 'Tormented Pariah', 'Skin Invasion', 'Skin Shedder', 'Liliana, Defiant Necromancer', 'Timber Shredder', 'Gatstaf Shepherd', 'Afflicted Deserter', 'Accursed Witch', 'Volcanic Hammer', 'Kessig Prowler', 'Withengar Unbound', 'Curious Homunculus', 'Shard Phoenix', 'Hanweir Militia Captain', 'Krallenhorde Killer', 'Gold-Forge Garrison', "Arguel's Blood Fast", 'Archangel Avacyn', 'Ormendahl, Profane Prince', 'Terror of Kruin Pass', 'Ashmouth Blade', 'Perfected Form', "Markov's Servant", 'Chalice of Death', 'Elesh Norn, Grand Cenobite', 'Krallenhorde Howler', 'Autumn-Tail, Kitsune Sage', 'Aberrant Researcher', 'Mondronen Shaman', 'Unhallowed Cathar', 'Ironfang', 'Atzal, Cave of Eternity', 'Village Messenger', 'Golden Guardian', 'Conduit of Emrakul', 'Wolfbitten Captive', 'Extricator of Sin', 'Spitfire Bastion', 'Chosen of Markov', 'Insidious Mist', 'Nicol Bolas, the Ravager', 'Moonrise Intruder', 'Kitsune Mystic', 'Primal Amulet', 'Spires of Orazca', 'Unholy Fiend', 'Stream of Life', 'Shrieking Drake', "Vance's Blasting Cannons", 'Journey to Eternity', 'Breakneck Rider', 'Scrounged Scythe', 'Avacyn, the Purifier', 'Zhalfirin Knight', 'Kytheon, Hero of Akros', 'Elbrus, the Binding Blade', 'Abolisher of Bloodlines', 'Voldaren Pariah', 'Hinterland Logger', 'Demon-Possessed Witch', 'Wildblood Pack', 'Howlpack of Estwald', 'Villagers of Estwald'])`

**Comment by ZeldaZach** [comment]
Fixed in 32607df23f9cc622677588bb7d64399006e561d0
