### ISSUE TITLE
Missing alternative versions of Tamiyo's Journal

### ISSUE THREAD

**Issue by gwax** [mtgjson/mtgjson#410]
SOI - Tamiyo's Journal has 5 different versions, mtgjson only has one of them: http://magiccards.info/soi/en/265a.html

**Comment by gwax** [comment]
This also breaks mciNumber generation for Tamiyo's Journal

**Comment by ZeldaZach** [comment]
Seems really ridiculous they'd have 6 different versions, changing only the entry # in the _flavor text_... I think we should still support it, but it really is a nuisance.

**Comment by fenhl** [comment]
It was a gimmick central to the theme of SOI, the mystery leading to Emrakul.

**Comment by ZeldaZach** [comment]
I decided on a no-fix for v4. It's just too bizarre to come up with a proper workaround for simply flavor text.
