### ISSUE TITLE
Error in 'duelDeck' docs

### ISSUE THREAD

**Issue by omfgitsmark** [mtgjson/mtgjson#416]
The docs state for the 'duelDeck' field the value can be 'a' or 'b', but some tokens have the value 'c'.

![Capture](https://user-images.githubusercontent.com/35660089/61758962-cac23100-ad94-11e9-9b9f-e75180b31374.PNG)

**Comment by ZeldaZach** [comment]
Should not have C,D,... Will either need to revoke after signing, or simply figure out how to better sign
