### ISSUE TITLE
Betrayers of Kamigawa has duplicate cards

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#418]
Cards 31b and 69b are included twice.

**Comment by ZeldaZach** [comment]
The reason they are included twice is because the "top" flip and "bottom" flip are two "separate" cards. If you take a look, they have the rules text of the face of the card they are representing. I find their double inclusion to be correct, but if you'd like to discuss it further we can.

**Comment by taw** [comment]
31a and 69a are also included. So it's 3 sides for 2-sided card.

**Comment by taw** [comment]
I'll just close it as apparently it was reported before https://github.com/mtgjson/mtgjson/issues/388
