### ISSUE TITLE
Adding Mtg top 8 pro decklists

### ISSUE THREAD

**Issue by jcorum11** [mtgjson/mtgjson#419]
I am an avid player and I have used MTG JSON for a few data science projects related to MTG. What would be most useful to me is to have a convenient way to compare how often a card is used by pros compared to other cards. Unfortunately the resource that I use (mtgtop8.com and others) don't have a convenient statistic on this, though mtg top 8 does have all decklists that has been on their sight since early 2000s. I feel this would be an incredible resource to any player who wants to play magic on a competitive level.

**Comment by ZeldaZach** [comment]
Hey JCorum! Having deck stats would be an interesting thing. I don't know if having decklists of non-constructed products is a good use of MTGJSON upstream, but having some usage stats could be helpful. I'll see what I can come up with on this idea.

If anyone wants to chime in, please feel free to!

**Comment by ZeldaZach** [comment]
I reached out to MTGDecks for more information

**Comment by ZeldaZach** [comment]
No response unfortunately. Will have to close as a no-fix until we can get more information.
