### ISSUE TITLE
Meld cards numbers problems

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#420]
There are two affected cards.

First one seems to be clear mtgjson specific problem:

* on gatherer [Chittering Host is listed as 96b](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=414392), it was also previously so in mtgjson
* mtgjson previously had it as 96b, now it has it as 91b
* printed is 96, so it should be 96b as backside of that

The other one is big Gatherer mess:

* if you go [here](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=414429), 
Hanweir, the Writhing Township is listed as 130b; while Hanweir Garrison is listed as 130a - this is good
* if you go [here](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=414511), Hanweir, the Writhing Township is listed as 130a (same card, different number!); Hanweir Battlements is listed as nonsensical 204b (probably due to bug in its melded side) - this is nonsense, and they should be 103b and 204a respectively

It seems mtgjson picked up this problem, and changed [Hanweir Battlements](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=414511) number from 204a to 204b in recent update. Since Gatherer for this card is inconsistent and obviously bugged I'd recommend reverting it to previous numbers.

These 2 of 9 seem to be the only ones affected. It's so much mess someone should double check what I'm saying here.

**Comment by sboosali** [comment]
any update?

**Comment by KingSupernova31** [comment]
I think this is fixed in v4, can you confirm?

**Comment by ZeldaZach** [comment]
This should be good now
