### ISSUE TITLE
Hymn to Tourach should be Banned in Pauper

### ISSUE THREAD

**Issue by nhrsn** [mtgjson/mtgjson#420]
#### MTGJSON Version: 4.4.1

Can't see a fix in the changelog notes for 4.4.2

#### Description of Bug:

Hymn to Tourach has no key for `pauper` in it's legalities data. The key should exist and the value should be "Banned"

**Comment by ZeldaZach** [comment]
Legality changes aren't usually documented. I just checked the latest rebuild (that went live a few hours ago) and Hymn is correctly banned in Pauper.

**Comment by nhrsn** [comment]
Thanks, sorry should've checked the latest

**Comment by ZeldaZach** [comment]
Heh no worries. Thanks for the report as sometimes things slip through! If you find any other issues, do let me know :)
