### ISSUE TITLE
Rarities in Rivals Quick Start Set and Introductory Two-Player Set

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#422]
There are two 4e precon deck set releases:

* [rqs](http://mtg.wtf/card?q=e%3Arqs) - [wiki](http://mtg.gamepedia.com/Rivals_Quick_Start_Set)
* [itp](http://mtg.wtf/card?q=e%3Aitp) - [wiki](http://mtg.gamepedia.com/Introductory_Two-Player_Set)

Since they're old cards they have no printed rarities, but by convention all such other precons should have same rarities as sets they're for.

Gatherer doesn't even have them, as it presumably treats them as 4e cards. ([example](http://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=201118)) (visually they differ only in copyright year)

mtgjson lists all their rarities as "Special". magiccards.info lists ITP as "Special" and doesn't seem to have RQS.

It would probably be better to just make them match 4e's rarity. mtg.wtf's indexer already does that.

**Comment by KingSupernova31** [comment]
I think this is fixed in v4, can someone confirm?

**Comment by ZeldaZach** [comment]
Looks to be correct
