### ISSUE TITLE
pPRE list front sides of Origins planeswalkers, not their back sides

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#423]
Affected are all five:

* Chandra, Fire of Kaladesh
* Jace, Vryn's Prodigy
* Kytheon, Hero of Akros
* Liliana, Heretical Healer
* Nissa, Vastwood Seer

[Example pic of promo version](http://i.tcgplayer.com/100595_200w.jpg)

This is MCI problem, as it has fronts without backs for them. [Example](http://magiccards.info/ptc/en/201.html)

As far as I can tell they only differ from Origins version in having date stamp (on just one or both sides???), so it shouldn't be hard to fill the missing sides.

**Comment by bernstein82** [comment]
yep, AFAIK the only difference ist the front side having a date stamp

**Comment by ZeldaZach** [comment]
Should be fixed in V4
