### ISSUE TITLE
Missing prices

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgjson#423]
#### Description of Bug:
Prices data missing from most cards from C19. I understand the set been released yet, but sites are using prices for C19 as the cheapest price, meaning in some cases it’s nearly a dollar or more less. Given you are supporting the spoiled set, people will want to order the new cards, and it looks like MTGStocks and others have the data for them.

**Comment by ZeldaZach** [comment]
Upstream issue with MTGStocks. I have reported it to them and will rebuild when they're updated.

In the future, we'll be using a variety of sources.

**Comment by ancestral** [comment]
Hey, I totally get you’re figuring this out. Again, no worries, but maybe the ticket should still be open, unless it’s good now?
