### ISSUE TITLE
Offer "min" version

### ISSUE THREAD

**Issue by omfgitsmark** [mtgjson/mtgjson#425]
By removing formatting (tabs, line breaks, etc.) it is possible to get the size of each json file down to almost 1/4 of it's normal size. 

![image](https://user-images.githubusercontent.com/35660089/63173154-3bafde00-c00d-11e9-9392-d26c24619e9e.png)

For anyone (including myself) who doesn't need it to be pretty or human-readable, a .min version would be great. A smaller file would be easier to work with, and you know I love saving storage and bandwidth.

Compact sans-formatting versions should be offered on the downloads page.

**Comment by ZeldaZach** [comment]
Yeah. This will be the default. See 590ed20a34228c387a880e5c3288ccd55b1a20ac
