### ISSUE TITLE
Card page

### ISSUE THREAD

**Issue by APrettyCoolProgram** [mtgjson/mtgjson#427]
#### MTGJSON Version: 4.X.X
4.5.0-rebuild.1
#### Description of Bug:
The card page (https://mtgjson.com/structures/card/) is missing "tcgplayerPurchaseUrl".

**Comment by ZeldaZach** [comment]
Thanks for the reminder ticket. `tcgplayerPurchaseUrl` was deprecated in 4.4.0 and slated for removal in 4.5.0. It will be gone in the rebuild posted on Sunday.
