### ISSUE TITLE
Crawling Gamepedia is a serious risk

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgjson#428]
#### Description of Bug:
MTGJSON crawls https://mtg.gamepedia.com/Modern for a list of sets that are legal.

This is insecure. Anyone can edit that page and insert or delete a set before a rebuild occurs. Or less maliciously, the page could easily get designed, reformatted, or redirected without notice.

We need a safer method. Either a trusted site like Scryfall, or another that has an API or a Read-Only page, or maybe MTGJSON should just build in the logic itself.

Solving this may also help #47 . (Vintage, Legacy, Brawl, Commander and others could have their own files.)

**Comment by ZeldaZach** [comment]
It's a low level of risk imo, but I'm fine looking for alternatives. If you have any to suggest, please feel free to. I _could_ also host my own list, which might be a good idea, but I'd like to see my options first.

**Comment by ancestral** [comment]
Doesn’t the card data already come with legalities included?
