### ISSUE TITLE
M20 foiling errors for some precon cards

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#429]
#### Description of Bug:

* `CardPrinting(Ironclad Krovod, m20) should be nonfoil`
* `CardPrinting(Vivien, Nature's Avenger, m20) should be foilonly`

These are cards from [this](https://mtg.gamepedia.com/Core_Set_2020/Planeswalker_decks) and [this](https://mtg.gamepedia.com/Core_Set_2020/Welcome_decks) decks.

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
Fixed on Scryfall
