### ISSUE TITLE
Rulings are sometimes in wrong order

### ISSUE THREAD

**Issue by fenhl** [mtgjson/mtgjson#43]
Scryfall's ordering of rulings is incorrect and makes little sense. For example, Humility should have a ruling from 2006-02-01, one from 2007-02-01, and then two from 2009-10-01. Scryfall's has the date sorting reversed but seemingly keeps rulings from the same date in the correct order.

**Comment by ZeldaZach** [comment]
Fixed in 32607df23f9cc622677588bb7d64399006e561d0
