### ISSUE TITLE
Split Schemes to another set

### ISSUE THREAD

**Issue by gwax** [mtgjson/mtgjson#430]
In archenemy sets, we currently conflate cards and schemes

Schemes should be split out to a separate "set" in much the same way that Timespiral splits Timeshifted cards to another set or masterpieces are split to another set.

Relates to #49 and #429

**Comment by fenhl** [comment]
I disagree. They are part of the same physical product, and have the same set code and set symbol. The different form factor is not a valid reason to split them, in the same way that we don't have separate sets for the oversized commanders from the precons.

**Comment by gwax** [comment]
They have a different numbering scheme. Keeping them in the same set means there are multiple cards with the number "1".

I think the oversized commanders should be separate.

Combining them downstream is a LOT easier than splitting them apart downstream.

**Comment by ZeldaZach** [comment]
Going on the basis of how we've done this before (With timespiral stuff) I think it would be a fine split and agree with @gwax in this situation.

**Comment by fenhl** [comment]
How do we handle pFNM, which also reuses the card numbers 1–12 each year?

**Comment by gwax** [comment]
That's a very good question @fenhl 

Can you help me understand why, for your use case, it is important to keep the schemes in the same "set" as the other, non-scheme, cards?

**Comment by fenhl** [comment]
One of my use-cases is [mtg.wtf](https://github.com/taw/magic-search-engine). I don't want to have to memorize a made-up set code if at all avoidable.

As far as I can tell, everything points toward the current situation being correct. pFNM and Tamiyo's Journal (#410) are precedent for multiple cards with the same collector number in the same set.

**Comment by gwax** [comment]
@fenhl has brought me around
