### ISSUE TITLE
Support for Arena specific properties of cards: collectability and craftability

### ISSUE THREAD

**Issue by Nicate** [mtgjson/mtgjson#432]
Is it an idea to support some of these aspects of Arena (only) cards?

- Collectability status: Some cards (and tokens) in the New Player Experience are part of the ANA set, but cannot be collected inside the game. This also means you cannot import deck lists that contain these cards. Something to help filter out these cards could be useful for that.
- Craftability status: One of the New Player Experience cards (Serra Angel) cannot be crafted, but can be imported (and possibly somehow collected). There may be more, I don't know.
- Card style availability: Arena now has card styles, of which some are obtainable and some are not. How the card style is obtained can also differ per card. I'm including this for completeness sake but this is obviously a much less interesting thing, as there are hundreds of them and there's no source as far as I know that lists which ones are obtainable and how, and which are not (other than clicking all of them in Arena). Also, this list constantly changes as Wizards does promotions.

Here is a list of the uncollectable cards from ANA:

- Altar's Reap
- Ambition's Cost
- Blinding Radiance
- Chaos Maw
- Cruel Cut
- Divination
- Doublecast
- Goblin Bruiser
- Goblin Gang Leader
- Goblin Grenade
- Knight's Pledge
- Loxodon Line Breaker
- Miasmic Mummy
- Nimble Pilferer
- Ogre Painbringer
- Overflowing Insight
- Renegade Demon
- Rise from the Grave
- Rumbling Baloth
- Seismic Rupture
- Shorecomber Crab
- Soulhunter Rakshasa
- Take Vengeance
- Titanic Pelagosaur
- Volcanic Dragon
- Waterknot

Here is a list of the tokens related to the uncollectable cards from ANA:

- Goblin

For completeness sake, here is a list of the cards from ANA that _are_ collectable:

- Sanctuary Cat
- Tactical Advantage
- Shrine Keeper
- Angelic Reward
- Confront the Assault
- Serra Angel*
- Spiritual Guardian
- Inspiring Commander
- River's Favor
- Zephyr Gull
- Raging Goblin
- Feral Roar
- Treetop Warden

And a list of all the tokens from ANA related to the collectable cards:

- Spirit

**Comment by ZeldaZach** [comment]
This is an interesting concept. I don't know enough about how Arena works with getting specific cards, but it's not out of the question. Will research more later.

If any others have opinions on this, feel free to drop a line

**Comment by ZeldaZach** [comment]
I'm curious what @csuhta has to say about such an idea

**Comment by ZeldaZach** [comment]
After speaking with upstream, I've decided to close as a no-fix. The reasoning is upstream will be removing non-craftable cards in the near future (that are fake cards that have no purpose outside of the tutorial) as they can't be used anywhere. By default then, all arena cards are craftable.

**Comment by Nicate** [comment]
That sounds like a good idea, then you can't create decklists from MTGJSON that cannot be imported.

Do note that there are many uncraftable cards in Arena, for example all the special lands that were either rewards or purchasable. But I'm guessing that's not what you meant.
