### ISSUE TITLE
Foreigndata have wrong prefix

### ISSUE THREAD

**Issue by mike1ong** [mtgjson/mtgjson#433]
#### Description of Bug:
It should be an upstream issue, two cards have this problem
Scryfall ID: 
ebff1b5d-b948-48fa-9fa7-690b13ab5d71
ea65e470-4892-4b2b-b187-2296c7a8d46a

These foreign names has a wrong "XX" prefix:

language|multiverseId|name
---|---|---
Chinese Simplified|131122|XX骁勇
French|131243|XXLa Valeur
German|131364|XXDie Tapferkeit
Italian|131485|XXIl Valore
Portuguese (Brazil)|131727|XXValor
Spanish|131969|XXValor
Chinese Simplified|131024|XX兽群的呼唤
French|131145|XXAppel du troupeau
German|131266|XXRuf der Herde
Italian|131387|XXRichiamo del Branco
Portuguese (Brazil)|131629|XXChamado do Rebanho
Spanish|131871|XXLlamado de la manada

**Comment by ZeldaZach** [comment]
Ref: https://github.com/scryfall/gatherer-bugs/issues/24
