### ISSUE TITLE
Keywords.json data is break

### ISSUE THREAD

**Issue by nicho92** [mtgjson/mtgjson#434]
#### MTGJSON Version: 4.5.0
data in https://mtgjson.com//json/Keywords.json are broken after "undergrowth" keyword

#### Description of Bug:
![image](https://user-images.githubusercontent.com/11507615/64076650-bd6b6100-ccc7-11e9-917f-8860c3cc78dc.png)

**Comment by ZeldaZach** [comment]
It’s a game of cat and mouse with Wizards haha. All fixed. Will he in today’s rebuild.
