### ISSUE TITLE
"Sultai Ascendacy"

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#437]
The newly introduced CP2 set contains "Sultai Ascendacy", which should be "Sultai Ascenda**n**cy"

**Comment by bakert** [comment]
CP2 is the Fate Reforged clash pack.

MCI has the same error on its Clash Pack page – https://magiccards.info/clash/en/9.html – which is probably the origin of our issue.

Gatherer seemingly does not care to know about clash packs – http://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=386674

I see this entry in pPRE set config:

    {"match": {"name": "Sultai Ascendacy"}, "replace": {"name": "Sultai Ascendancy", "imageName": "sultai ascendancy"}},

I assume a similar entry in CP1_CP2_CP3.json in the CP2 set config would fix this.

**Comment by taw** [comment]
That error was introduced when `clash` set got split into `CP1`/`CP2`/`CP3`, so presumably this fix simply needs to get reapplied.

**Comment by bakert** [comment]
I tried fixing this today but encountered #574.

**Comment by bakert** [comment]
I'm going to try and fix this again but I note that mci's  Sultai Ascendacy page now redirects to Scryfall's Sultai Ascendancy page. I'm therefore not sure what the canonical source for the clash pack info now is. Someone holler if I'm wasting my time trying to fix this against master before I waste my time fixing this against master pls :D

**Comment by taw** [comment]
The concept of "canonical" pages is somewhat questionable.

The way mtg.wtf models it, is that cards have card level info and printing level info. Card level info is shared between all printings (name, typeline, p/t, oracle text etc.), printing level info is not.

The thing is - card level info is always on Gatherer, so you never need other canonical source, and printing level info never changes, so you don't need canonical source.

**Comment by bakert** [comment]
Sounds reasonable. Is it worth fixing this in v3 or v4 going to happen soon?

**Comment by taw** [comment]
They're not really doing anything to v3 other than adding new sets, and even that usually takes some poking.

**Comment by ZeldaZach** [comment]
I'm on a small break from v4 development, but I hope to get it back and ready for beta testing in the next few weeks. Sorry for the delays on my end

**Comment by ZeldaZach** [comment]
Fixed in V4
