### ISSUE TITLE
Repeated hash

### ISSUE THREAD

**Issue by jenjia** [mtgjson/mtgjson#438]
Downloaded AllSets-x.json at 11/8/2017

"id": "34bbf9e14b771f9eb4c4c2970ed54b8ff836118a",
"name": "Scarmaker",
"code": "BOK"

and

"id": "2ba1628b4169e33a4a6773124bec72fadfb6c983",
"name": "Jaraku the Interloper",
"code": "BOK"

**Comment by skwerlman** [comment]
maybe i'm misunderstanding, but those hashes are _very_ different from each ither

**Comment by ZeldaZach** [comment]
I... don't see the issue. @jenjia What's wrong with the hashes?

**Comment by jenjia** [comment]
Both "Scarmaker" and "Jaraku the Interloper" are repeated in the file. They appear 2x times each. So their hash is repeated 2x times in the file.

**Comment by fenhl** [comment]
Closing as duplicate of #388.
