### ISSUE TITLE
missing Foreign Black Bordered (FBB) 

### ISSUE THREAD

**Issue by PeerRich** [mtgjson/mtgjson#439]
On MagicCardMarket and other (mostly) European shops you can buy Foreign Black Bordered (FBB) cards, especially duals are very attractive, due to the black border. I haven't found this set in mtgjson. Adding this would be great!

Here is the full set: https://www.magiccardmarket.eu/Products/Singles/Foreign+Black+Bordered

Here is a set description:
https://www.magiccardmarket.eu/Help/Core_Sets#Foreign_black_bordered_Core_Sets_.28Revised_and_4th_Edition.29

**Comment by ZeldaZach** [comment]
Addressed in V4.1
