### ISSUE TITLE
Legality changes due to bans or set rotations

### ISSUE THREAD

**Issue by Morioki** [mtgjson/mtgjson#44]
When sets rotate out of a format or when ban's come through, there does not appear to be a way to pull the new legalities for the cards without building an entirely new file for that set. 

Would there be a way to create a file of just card legalities or legality changes?

**Comment by ZeldaZach** [comment]
We've been considering creating set-files such as `Standard.json`, `Modern.json`, etc which would follow the formatting of AllSets and AllCards, with the restriction of only cards/sets in those formats.

Would something like that satisfy what you're looking for?

**Comment by Morioki** [comment]
For my use case, I do not think that set files would necessarily satisfy it. I'll give a bit of info on how I came to this request.

In my system, I have imported all the cards into my database in a table with a key to a legalities table that contains a card identifier and then a row for each legality and value pair. Now when sets rotate out of formats or cards get banned, the current option is to rebuild the set that had a card that changed and run an update to insert the differences. 

I thought that a file that contained cards and just their legalities might make the import process either lighter, through a smaller overall file or less database taxing by not having to run an update for each field. 

How the process works now is viable, I just thought I would pose a potential additional feature.

**Comment by ZeldaZach** [comment]
It's something that seems a bit tricky on our end to get right, and it might not be worth the time right now. If you'd like to look into a contribution, I would highly consider it, but I'd rather focus in on some of the bugs we're still having before we release. Hope you understand!
