### ISSUE TITLE
Throne Adventure cards have incorrect Scryfall id

### ISSUE THREAD

**Issue by jmcsmith** [mtgjson/mtgjson#442]
Throne Adventure cards have incorrect Scryfall id.

See Bring to Life:
MTGJson
"scryfallId": "32158458-42eb-41bc-a15a-11af28463eb0"

Scryfall
"id": "a8924faa-d5f5-4119-9fa1-be0789a5655d"

The "Big" part of the physical card works (Animating Faerie)

**Comment by ZeldaZach** [comment]
Just re-tested. I had to make one slight modification, but the SF Id seems to be correct now. Feel free to re-test with the rebuild today!
