### ISSUE TITLE
webpage: no favicon

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson#443]
There is no favicon on the mtgjson webpage. Should be the same as gitter logo maybe.

**Comment by fenhl** [comment]
I created that logo and can upload it in any size required.

**Comment by tooomm** [comment]
How does that logo look with 16x16 and 32x32 pixel?

**Comment by fenhl** [comment]
![mtgjson-logo-16x16](https://user-images.githubusercontent.com/641386/29395159-84d785ea-82fe-11e7-90ac-4def9b0da6cd.png)
![mtgjson-logo-32x32](https://user-images.githubusercontent.com/641386/29395161-87ffc214-82fe-11e7-8053-068850ec9107.png)

**Comment by fenhl** [comment]
An alternative logo that has been proposed previously:
![logo2-16](https://user-images.githubusercontent.com/641386/29395261-20f442ba-82ff-11e7-87e2-cdbaeea9dacd.png)
![logo2-32](https://user-images.githubusercontent.com/641386/29395262-211974f4-82ff-11e7-983e-a2d6f8031245.png)

**Comment by ZeldaZach** [comment]
I can deal with this, but we need to come to an agreement on what our logo should be... What are our proposals?

**Comment by fenhl** [comment]
The first one is a card back in curly braces, same as our github organization logo, and the second one is the color pie in curly braces, similar to the logo on the website but with different colors and a different font. Both use colors from Solarized, as that was the color scheme used on the website at the time. I can look into remaking the color pie one with a white background and the colors used on the website, though they seem a bit too light in my opinion.

**Comment by tooomm** [comment]
We should use the same type of logo/branding everywhere!

Did the color scheme change on the website?

Jep, the color wheel in small looks worse than just the card back in my opinion.

If we want to combine ideas, we could have the small, more simple square logo just with the card back - for favicon, gitter, github org etc.
And in big for the webpage: the colors in braces, but put them also on the same card backs maybe? 
Same font + color scheme for both of them for sure.

**Comment by fenhl** [comment]
The color scheme did change. I agree that the card back looks better than the colors. However, I don't think using the card back for the logo on the website would work given the dimensions. Maybe it's okay to have two different logos because of this.

Another option would be to change the logo on the website to have the card back in curly braces on the left, and then “MTG JSON” on the right, perhaps with a line break.

**Comment by tooomm** [comment]
If you're speaking about one single card as background it could be
```
[logo] [name]
```
instead
```
[name]
[logo]
```
Yes, that could work, and it would be the very same logo. The color wheel could then still be added to the big card, if it looks good.

But I meant 5 cards next to each other, just like the color dots right now. Basically the same as it is right now on the webpage, but combined with cards under each color dot. Maybe it looks stupid though, no idea.


<br>

>The color scheme did change.

I was confused since it's still references on the bottom of the page. But yeah, it's written `used` there.
Do we want to remove that?

**Comment by ZeldaZach** [comment]
New site in the works, we'll figure out what we want to do on the appropriate repo (https://github.com/mtgjson/mtgjson4-website)
