### ISSUE TITLE
Allsets misses card types for modern horizons art cards

### ISSUE THREAD

**Issue by ebbit1q** [mtgjson/mtgjson#444]
Noted in cockatrice here: https://github.com/Cockatrice/Cockatrice/issues/3815
Around 54 cards are missing card types.

**Comment by ebbit1q** [comment]
so apparently in the output for AMH1 every even card will have the types `["Card"]` and the uneven ones will be empty.

**Comment by ebbit1q** [comment]
So confusion stemmed from that these are in fact the art cards and not the set itself. Anyhow the typeline still seems weird to me but it isn't a problem.

**Comment by ebbit1q** [comment]
Special corner case time! The way it deals with these being two faced cards doesn't correctly register because both sides have the same name. ( Introduced here: https://github.com/mtgjson/mtgjson/pull/111 )

**Comment by ZeldaZach** [comment]
Will fiddle around with this tonight... I had issues building them last night and put some hacks in. Will prob revert those out and come up with a better solution.

**Comment by ebbit1q** [comment]
Maybe come up with a way to differentiate double face cards that doesn't look baseline illegal?

**Comment by ZeldaZach** [comment]
I'm gonna shove them into the tokens array, for one. That's my biggest issue. I somewhat rushed to get it building last night. My mistake

**Comment by ZeldaZach** [comment]
Fixed in 52421726f1aefd4a02b286744609aaf68f5a102a, rebuilding and will re-deploy
