### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by TheYsconator** [mtgjson/mtgjson#445]
#### Description of Bug:
When running ```pipenv run python3 -m mtgjson4 -acz``` on a fresh install (after having installed the requirements), I get the following error: https://puu.sh/EigcN/5df6b55b21.png

Is there a way to circumvent this?

**Comment by TheYsconator** [comment]
Disabling the cache appears to work (I guess because then there is no database that can be locked), but I was wondering if there is something I have to do additionally to get caching to work.

**Comment by ZeldaZach** [comment]
I have never experienced such an issue with the cache system, so it's a bit hard for me to diagnose. Looking online, it might be a thread issue. https://codeday.me/es/qa/20190419/523050.html is the best thing I've seen related to this issue, but I'll continue to dig.

**Comment by ZeldaZach** [comment]
@TheYsconator I did some googling and this appears to be a local issue not relating to MTGJSON. Guides online say you may have had the cache DB open accidentally, in the wrong format (did you manually create?) , or didn't have permissions to write to the location (most probable). Feel free to report back :)

**Comment by TheYsconator** [comment]
Hmm I didn't create the cache manually, nor were there (as far as I know) any other applications running that would've touches that database. I was using pipenv instead of pip and virtualenv though, so I can try again tomorrow with pip and virtualenv.

As for the possibility of insufficient permissions; I wouldn't know why my general user level permissions wouldn't be enough, and I guess that it wouldn't be that since it does download and cache some entries before giving the error.

Are you using an API key/ account for scryfall when retrieving from there?
