### ISSUE TITLE
UNH 106★ `frameVersion`

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#447]
#### Description of Bug:

So I decided to actually use mtgjson `frameVersion` instead of guessing based on `releaseDate` like back in v3. Of course I ran into issues right away ;-)

https://mtgjson.com/json/UNH.json

UNH 106 is correctly marked as having old `frameVersion` (`"1997"`), but its promo version 106★ is not, and has incorrect `"2003"`.

They should both be `"1997"`.

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
Fixed on Scryfall
