### ISSUE TITLE
webpage: update utf8 text hint

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson#448]
![untitled](https://user-images.githubusercontent.com/9874850/29576197-45cce742-8767-11e7-999d-a6bb22b1e7a7.png)

Just remove the second part completely?
With the recent change to `AE` we don't use that character any longer.
Are there other special characters which needs a mention instead?

**Comment by fenhl** [comment]
Yes, there are still plenty of non-ASCII characters, such as em dashes (—) in most `"type"` fields, and card names like [El-Hajjâj](https://mtg.wtf/card/4e/18/El-Hajjaj).

**Comment by tooomm** [comment]
Used your examples in the PR. The dash is copied and just looks like a normal one on mistake I guess.
