### ISSUE TITLE
ELD buy a box promo Kenrith, the Returned King 303 has foil and nonfoil versions?

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#449]
#### MTGJSON Version: 4.X.X

https://mtgjson.com/json/ELD.json

#### Description of Bug:

It's tagged as such, but all BoB promos were foil-only (except MH1), so that looks like a mistake.

(unless it's some shenanigans related to all those weird booster types etc., but I don't think so)

**Comment by ZeldaZach** [comment]
The $450 product had a non foil version
