### ISSUE TITLE
Inconsistent ImageName

### ISSUE THREAD

**Issue by jenjia** [mtgjson/mtgjson#450]
For cards that have more then one card in the front:
**Example 1:**
Wear // Tear
```
"imageName": "weartear",
      "layout": "split",
      "name": "Wear",
      "names": [
        "Wear",
        "Tear"
      ],
```
**Example 2:**
Claim // Fame
```
"imageName": "claim",
      "layout": "aftermath",
      "name": "Claim",
      "names": [
        "Claim",
        "Fame"
      ],
```

"Claim" & "Fame" should have imageName created as was "Wear" & "Tear"

**Comment by silasary** [comment]
The imagename field is obsolete, and refers to the name that would have been used for it on mtgimage.

As long as the name is unique, the actual formatting is irrelevant, as there is no formalized schema for it.

**Comment by ZeldaZach** [comment]
Building on what silasary said, the imageName field is officially deprecated and will be removed in the 4.0 release.

**Comment by jenjia** [comment]
Ok, Sorry for the mess, is just that I still use it as my own imageNames.
(I know is better to use id's for speed, etc. But for debugging I still prefer to use imageNames)

**Comment by ZeldaZach** [comment]
Haha, no worries! If you have any questions on how to transition over to a different key, feel free to chat with us on gitter :)

**Comment by lincolnthree** [comment]
Out of curiosity. If imageName goes away, what should we use to distinguish between multiple instance of fuse//split cards? (E.g. Which json entry is the front, which json entry is the back, or which is the first, which is the second in the card's actual name?)

**Comment by fenhl** [comment]
The `"name"` and `"names"` fields cover this. `"name"` is just the name of the half you're looking at, and `"names"` contains the names of both halves in the correct order.

**Comment by lincolnthree** [comment]
Okay, then I think I'm a bit confused about the data.

Let's take Bruna, The Fading Light as an example. There are three entries for this card. I'll just copy the relevant parts. In this example, we have two copies of 'Bruna, the Fading Light' with 'normal' layout, and one with 'meld'. I guess maybe I'm not understanding what's going on here, but it seems like we have duplicate entries, and for some reason they have different image names and unique IDs. What's the story here? Right now I filter these out by removing normal layout cards that have the same name with different image ID and multiple names to get a single representation of this card.

How is this data intended to be used to represent the two (three) cards that end up being Bruna/Gizela/Brizela/etc. And why is there only one entry for "Gizela, the Broken Blade" whereas there are three for this one?

```
{
    "id" : "408e43c56377f68af1d2f1a71733626f9c629ae8",
    "imageName" : "bruna, the fading light1",
    "layout" : "normal",
    "multiverseid" : 414304,
    "name" : "Bruna, the Fading Light",
    "names" : [ 
        "Bruna, the Fading Light", 
        "Brisela, Voice of Nightmares"
    ],
    "number" : "15a",
}

```

```
{
    "id" : "5dcb66f2dc71d5250dd6f35aa27cd0838c37078b",
    "imageName" : "bruna, the fading light2",
    "layout" : "normal",
    "multiverseid" : 414304,
    "name" : "Bruna, the Fading Light",
    "names" : [ 
        "Bruna, the Fading Light", 
        "Brisela, Voice of Nightmares"
    ],
    "number" : "15a",
}
```


```
{
    "id" : "e5f4b38f63e321d151ede8c0cd90b62db2f69978",
    "imageName" : "bruna, the fading light",
    "layout" : "meld",
    "multiverseid" : 414304,
    "name" : "Bruna, the Fading Light",
    "names" : [ 
        "Gisela, the Broken Blade", 
        "Bruna, the Fading Light", 
        "Brisela, Voice of Nightmares"
    ],
    "number" : "15a",
}
```

Thanks for your time. I'm trying to slowly dip my feet into this project and hopefully help out but I'm having a bit of learning curve issues I think :)

**Comment by fenhl** [comment]
This sounds like a bug with meld cards, and should be reported as a separate issue.

**Comment by lincolnthree** [comment]
Gotcha. Will open one. Thanks.

**Comment by lincolnthree** [comment]
https://github.com/mtgjson/mtgjson/issues/451
