### ISSUE TITLE
Meld cards seem to be oddly represented in JSON

### ISSUE THREAD

**Issue by lincolnthree** [mtgjson/mtgjson#451]
Okay, then I think I'm a bit confused about something. This may or may not be a bug.

Let's take Bruna, The Fading Light as an example. There are three entries for this card. I'll just copy the relevant parts. In this example, we have two copies of 'Bruna, the Fading Light' with 'normal' layout, and one with 'meld'. I guess maybe I'm not understanding what's going on here, but it seems like we have duplicate entries, and for some reason they have different image names and unique IDs. What's the story here? Right now I filter these out by removing normal layout cards that have the same name with different image ID and multiple names to get a single representation of this card.

How is this data intended to be used to represent the two (three) cards that end up being Bruna/Gizela/Brizela/etc. And why is there only one entry for "Gizela, the Broken Blade" whereas there are three for this one?

```
{
    "id" : "408e43c56377f68af1d2f1a71733626f9c629ae8",
    "imageName" : "bruna, the fading light1",
    "layout" : "normal",
    "multiverseid" : 414304,
    "name" : "Bruna, the Fading Light",
    "names" : [ 
        "Bruna, the Fading Light", 
        "Brisela, Voice of Nightmares"
    ],
    "number" : "15a",
}

{
    "id" : "5dcb66f2dc71d5250dd6f35aa27cd0838c37078b",
    "imageName" : "bruna, the fading light2",
    "layout" : "normal",
    "multiverseid" : 414304,
    "name" : "Bruna, the Fading Light",
    "names" : [ 
        "Bruna, the Fading Light", 
        "Brisela, Voice of Nightmares"
    ],
    "number" : "15a",
}
{
    "id" : "e5f4b38f63e321d151ede8c0cd90b62db2f69978",
    "imageName" : "bruna, the fading light",
    "layout" : "meld",
    "multiverseid" : 414304,
    "name" : "Bruna, the Fading Light",
    "names" : [ 
        "Gisela, the Broken Blade", 
        "Bruna, the Fading Light", 
        "Brisela, Voice of Nightmares"
    ],
    "number" : "15a",
}
```

Thanks for your time. I'm trying to slowly dip my feet into this project and hopefully help out but I'm having a bit of learning curve issues I think :)

**Comment by fenhl** [comment]
There should only be one entry for Bruna (as well as one for Gisela and one for Brisela). It should have the `"meld"` layout.

**Comment by ZeldaZach** [comment]
Agreed. the 2 "normal" versions should be removed.
