### ISSUE TITLE
Change `leadershipSkills` to something else

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgjson#453]
Currently, one of the structures MTGJSON uses is one that details the different commander-like formats the card is legal to be your commander with, called `leadershipSkills`.

It’s not very obvious what `leadershipSkills` means. The first thing that came to my mind is tracking for some kind of card attribute. Maybe a new name is advisable… maybe `commander`?

But does this need to be its own structure? Is there a reason not to have a `isCommander` list/set of values in `card` with the formats it can be a commander in?

**Comment by ZeldaZach** [comment]
Changing struct names isn't something we can do easily, as we'd have to deprecate, publish both old and new, then remove old over a period of time. The docs should be clear enough to indicate what this field does, and I'm relatively happy with it as-is.
