### ISSUE TITLE
Coldsnap Theme Decks incorrectly all listed as "special" rarity

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#454]
So [this set](http://mtg.wtf/set/cstd). (set `CST` / mci `cstd`)

[They definitely have official common/uncommon/rare rarities](http://magic.wizards.com/en/articles/archive/coldsnap-theme-decks-2008-08-18) - which you can also see on the cards.

But mtgjson lists them all as "Special" rarity. MCI has same error.

Gatherer doesn't list CST cards as separate set. [For example here](http://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=184554) vs [here](http://mtg.wtf/card/cstd/8/Kjeldoran-Home-Guard).

"CST" set in mtgjson seems to be just those CST cards which don't also occur in Coldsnap - which is sort of unusual way - most precon sets have all their cards included. But let's ignore this issue, and fix rarities first.

**Comment by taw** [comment]
Correct mapping is:

      "Arcum's Weathervane" => "uncommon",
      "Ashen Ghoul" => "uncommon",
      "Aurochs" => "common",
      "Balduvian Dead" => "uncommon",
      "Barbed Sextant" => "common",
      "Binding Grasp" => "uncommon",
      "Bounty of the Hunt" => "uncommon",
      "Brainstorm" => "common",
      "Browse" => "uncommon",
      "Casting of Bones" => "common",
      "Dark Banishing" => "common",
      "Dark Ritual" => "common",
      "Deadly Insect" => "common",
      "Death Spark" => "uncommon",
      "Disenchant" => "common",
      "Drift of the Dead" => "uncommon",
      "Essence Flare" => "common",
      "Forest" => "basic",
      "Gangrenous Zombies" => "common",
      "Giant Trap Door Spider" => "uncommon",
      "Gorilla Shaman" => "common",
      "Iceberg" => "uncommon",
      "Incinerate" => "common",
      "Insidious Bookworms" => "common",
      "Island" => "basic",
      "Kjeldoran Dead" => "common",
      "Kjeldoran Elite Guard" => "uncommon",
      "Kjeldoran Home Guard" => "uncommon",
      "Kjeldoran Pride" => "common",
      "Lat-Nam's Legacy" => "common",
      "Legions of Lim-Dûl" => "common",
      "Mistfolk" => "common",
      "Mountain" => "basic",
      "Orcish Healer" => "uncommon",
      "Orcish Lumberjack" => "common",
      "Phantasmal Fiend" => "common",
      "Plains" => "basic",
      "Portent" => "common",
      "Reinforcements" => "common",
      "Scars of the Veteran" => "uncommon",
      "Skull Catapult" => "uncommon",
      "Snow Devil" => "common",
      "Soul Burn" => "common",
      "Storm Elemental" => "uncommon",
      "Swamp" => "basic",
      "Swords to Plowshares" => "uncommon",
      "Tinder Wall" => "common",
      "Viscerid Drone" => "uncommon",
      "Whalebone Glider" => "uncommon",
      "Wings of Aesthir" => "uncommon",
      "Woolly Mammoths" => "common",
      "Zuran Spellcaster" => "common",

**Comment by KingSupernova31** [comment]
I believe this is fixed in v4, can someone confirm?

**Comment by ZeldaZach** [comment]
Yep
