### ISSUE TITLE
Foreign sets keep the English name

### ISSUE THREAD

**Issue by aimadtakhtoukh** [mtgjson/mtgjson#455]
Hello,

I'm trying to make a multi-language Magic search engine, so I cloned the Github repository to use the json folder and get all the data. But foreign sets show the English name, and I can only get the localized names from the English cards file.

Example from Fifth Dawn's Abuna Chant, in French and English : 

In French : 
`    {
      "artist": "John Matson",
      "cmc": 4,
      "colors": [
        "White"
      ],
      "id": "073f52f1850f56c9fc18ee6060dfdb1650423221",
      "layout": "normal",
      "manaCost": "{3}{W}",
      "multiverseid": 80712,
      "name": "Abuna's Chant",
      "number": "1",
      "originalText": "Choisissez l'un — Vous gagnez 5 points de vie ; ou prévenez, ce tour-ci, les prochaines 5 blessures sur une créature ciblée.\nUnion {2}  (Choisissez les deux si vous payez le coût d'union.)",
      "originalType": "Éphémère",
      "rarity": "Common",
      "text": "Choose one —\n• You gain 5 life.\n• Prevent the next 5 damage that would be dealt to target creature this turn.\nEntwine {2} (Choose both if you pay the entwine cost.)",
      "type": "Instant",
      "types": [
        "Instant"
      ]
    }`

In English : 
`"id": "10338c40475fd8af59d53b9538d2e23ccc98f902",
      "imageName": "abuna's chant",
      "layout": "normal",
      "legalities": [
        {
          "format": "Commander",
          "legality": "Legal"
        },
        {
          "format": "Legacy",
          "legality": "Legal"
        },
        {
          "format": "Mirrodin Block",
          "legality": "Legal"
        },
        {
          "format": "Modern",
          "legality": "Legal"
        },
        {
          "format": "Vintage",
          "legality": "Legal"
        }
      ],
      "manaCost": "{3}{W}",
      "mciNumber": "1",
      "multiverseid": 50164,
      "name": "Abuna's Chant",
      "number": "1",
      "originalText": "Choose one You gain 5 life; or prevent the next 5 damage that would be dealt to target creature this turn.\nEntwine {2} (Choose both if you pay the entwine cost.)",
      "originalType": "Instant",
      "printings": [
        "5DN"
      ],
      "rarity": "Common",
      "text": "Choose one —\n• You gain 5 life.\n• Prevent the next 5 damage that would be dealt to target creature this turn.\nEntwine {2} (Choose both if you pay the entwine cost.)",
      "type": "Instant",
      "types": [
        "Instant"
      ]
    }`

Is there any way to match the language's name to its card?

Thank you!

**Comment by ZeldaZach** [comment]
Should be working right in V4 now
