### ISSUE TITLE
World Championship cards missing "isPaper" and "isMtgo" flags

### ISSUE THREAD

**Issue by MidnightLightning** [mtgjson/mtgjson#455]
#### MTGJSON Version: 4.5.1-rebuild.2
AllSets.json

#### Description of Bug:
Cards in the "World Championship" sets (e.g. WC99, WC00, WC01, etc.) do have `hasFoil`, `hasNonFoil`, `isReprint`, and `isStarter` flags, but do not have the `isPaper` and `isMtgo` flags that cards in other sets have.

This is an issue for scripts that parse through the entire set looking for "all cards that have a paper version" or "all cards that have an online version", since it may then incorrectly filter those gold-bordered cards out.

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
I think this may be a misinterpretation of Scryfall data. We set `paper`, `mtgo`, and `arena` in the `games` array field for our card objects. Those indicate what play formats a card is available for. The World Champ decks are not legal/available on MTGO and they aren't legal for paper play, so they don't have those markers.

If you're looking for Scryfall field to indicate "this object made of cardboard" that would be `"digital": false`

**Comment by MidnightLightning** [comment]
"Aren't legal for paper play"? The Championship decks are legal for Vintage, Legacy and Commander use, according to Scryfall data under the `legalities` property (e.g. https://api.scryfall.com/cards/0bf2ee15-fdcb-40b0-9688-6eae31e59549?format=json&pretty=true).

Silver-bordered cards, like the _Unstable_ set, have all the `legalities` set to `not_legal`, but does have `games: paper` set, and MTGJSON is setting `isPaper` to `true` for them.

So, does this mean that MTGJSON should modify how they're parsing Scryfall data to look to the `games` property instead of the `legalities` section when determining what the `isPaper` and `isMtgo` flags should be set to?

**Comment by ZeldaZach** [comment]
The paper/mtgo/arena flags on JSON are supposed to mean the card was printed there. If I am confused on this, I can revise documentation

**Comment by ZeldaZach** [comment]
Note for me (or whoever fixes this): `isPaper` should be set to true if we see `digital == false` or it's a golden border. `https://scryfall.com/search?page=7&q=include%3Aextras+-game%3Apaper+not%3Adigital` gives a list of cards affected. I'd probably just look for gold border as our field is _slightly_ different than what SF proposes. This is indeed a bug on our side.
