### ISSUE TITLE
Can someone commit the foreign language version of recent sets?

### ISSUE THREAD

**Issue by aimadtakhtoukh** [mtgjson/mtgjson#456]
Hello,

I'm trying to make a multi-language Magic search engine. But the most recent sets (Amonkhet, Hour of Destructions, Commander 2017) only have English versions. Can someone upload the foreign versions?

Thank you!

**Comment by makhotkin** [comment]
I believe this issue has to be closed, because the currently avaliable jsons for sets with extras for AKH, HOU and C17 do contain foreign languages

**Comment by aimadtakhtoukh** [comment]
They contain foreign names. To explain the problem further : 
- Each set produced has every card in english, with every foreign names only.
- Older sets also have their texts and flavor texts in a foreign language. As an example, Legions has an english file with foreign names in LEG.json, and the french text in LEG.fr.json. (Doesn't make for easy parsing, but at least it works)
(example : https://github.com/mtgjson/mtgjson/blob/master/json/LGN.fr.json )
- The most recent sets have foreign names, but no foreign texts (there is no HOU.fr.json, as an example).

So I don't believe this issue is closed yet.

**Comment by tooomm** [comment]
Duplicate https://github.com/mtgjson/mtgjson/issues/404

**Comment by fenhl** [comment]
Closed #404 in favor of this.

**Comment by Aveheuzed** [comment]
I'm also interested into this feature : foreign rule and flavor text, even more interested if it comes down through the API of https://magicthegathering.io/ !
Keeping an eye open, waiting for this feature to come down !

**Comment by ZeldaZach** [comment]
Addressed in V4 :)
