### ISSUE TITLE
ELD only Standard legal

### ISSUE THREAD

**Issue by carlol** [mtgjson/mtgjson#457]
#### Description of Bug:
Hi,
Thank you for your work, I noticed that ELD cards are only Standard legal and I have to force other legality manually.

Best regards,

CL

**Comment by ZeldaZach** [comment]
Just checked and it appears cards are correct for standard-ness from today's hot-fix rebuild. Let me know if this isn't the case, and with examples. Thanks for using MTGJSON! :)
