### ISSUE TITLE
Throne of Eldraine Promos (PELD) is gone

### ISSUE THREAD

**Issue by lfgcampos** [mtgjson/mtgjson#458]
Since last rebuild Build: (`v4.5.1-rebuild.2`), `Throne of Eldraine Promos (PELD)` is not available anymore: https://www.mtgjson.com/json/PELD.json

**Comment by ZeldaZach** [comment]
Just went through the latest rebuild logs. It seems the set was empty at the time it was attempting to build. Hit a race time with Scryfall updating that set. It should be back online with tomorrow's full rebuild. Sorry for the delays!

**Comment by lfgcampos** [comment]
Just my opinion about closing the issues, you should/could create a label for it when you are going to fix (but this is not fixed yet) or mark it to be fixed in release x.y.z making it clear to everyone.
