### ISSUE TITLE
Both halves of flip cards have mana costs

### ISSUE THREAD

**Issue by fenhl** [mtgjson/mtgjson#459]
For example, [Dokai, Weaver of Life](https://mtg.wtf/card/chk/202b) is listed with a mana cost of {1}{G}, but should not have a mana cost at all.

**Comment by ZeldaZach** [comment]
I believe this is correct behavior as https://mtg.gamepedia.com/Flip_card says they retain mana cost and such when flipped.

**Comment by fenhl** [comment]
I guess that makes sense. I was expecting them to work like double-faced cards.
