### ISSUE TITLE
Reimplement Booster Field

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson#46]
The Booster field from V3 contained how cards could be obtained via packs. We removed it in V4, temporarily, to reevaluate our options and figure out the best way to implement.

This will be our discussion board on this topic. 

Cite: https://github.com/mtgjson/mtgjson/issues/521

**Comment by tooomm** [comment]
Maybe this should stay open?

From the PR:
>For now, this is just the reimplementation of the v3 field, as it seems to be a deal breaker for many. I want to come up with our own solution for a better booster field, but we'd have to sit on it for a bit to come up with a strong solution. What do you think of the field rename for legacy purposes?

**Comment by ZeldaZach** [comment]
Nah, it’s an internal thing for now. I’ll reopen with solutions in the future
