### ISSUE TITLE
Move tokens to a new 'tokens' array

### ISSUE THREAD

**Issue by Sembiance** [mtgjson/mtgjson#46]
As per Rule 108.2 tokens are not considered cards. Thus I should move them out of the 'cards' array and add a new 'tokens' array along side it. The easiest way to do this would probably be AFTER all processing on the set and cards is done, simply move any card where layout==="token" out of the cards array and into the new tokens array.

**Comment by KingSupernova31** [comment]
This needs to happen. Random tokens in the card file are screwing up my programs. Additionally, they're missing fields that they should have, such as "types".

**Comment by fenhl** [comment]
I think removing the few tokens that are in the dataset would make sense for now. Then in v4, we can properly implement a complete token list (#47).

**Comment by ZeldaZach** [comment]
Addressed
