### ISSUE TITLE
ForeignNames still missing?

### ISSUE THREAD

**Issue by Fryyyyy** [mtgjson/mtgjson#460]
#### MTGJSON Version: 4.X.X 
Downloaded on 2019-10-13

#### Description of Bug:

 "Armed": {"colorIdentity": ["G", "R"], "colors": ["R"], "convertedManaCost": 6.0, "edhrecRank": 19155, "faceConvertedManaCost": 2.0, "foreignData": [], 

But Gatherer has a number of foreign names for Armed (// Dangerous):

Translated Card Name | Language | Translated Language
-- | -- | --
武裝 // 危險 | Chinese Traditional | 繁體中文
Bewaffnet // Gefährlich | German | Deutsch
Armé // Dangereux | French | Français
Armato // Pericoloso | Italian | Italiano
武装 // 物騒 | Japanese | 日本語
무쌍 // 난무 | Korean | 한국어
Armado // Perigoso | Portuguese (Brazil) | Português
Вооружен // Опасен | Russian | русский язык
武装 // 危险 | Chinese Simplified | 简体中文
Armado // Peligroso | Spanish | Español

**Comment by ZeldaZach** [comment]
Ran Dragon's Maze through an analyzer to see how many printings across all languages a card sees on Scryfall.
```
1	Alive 
1	Armed 
1	Away 
1	Beck 
1	Blood 
1	Call 
1	Catch 
1	Dangerous 
1	Dirty 
1	Down 
1	Far 
1	Flesh 
1	Give 
1	Loss 
1	Profit 
1	Protect 
1	Ready 
1	Release 
1	Serve 
1	Take 
1	Tear 
1	Toil 
1	Trouble 
1	Wear 
1	Well 
1	Willing 
11	Aetherling 
11	Armored Wolf-Rider 
11	Awe for the Guilds 
11	Azorius Cluestone 
11	Bane Alley Blackguard 
11	Battering Krasis 
11	Beetleform Mage 
11	Blaze Commando 
11	Blood Scrivener 
11	Boros Battleshaper 
11	Boros Mastiff 
11	Council of the Absolute 
11	Crypt Incursion 
11	Debt to the Deathless 
11	Dimir Cluestone 
11	Dragonshift 
11	Exava, Rakdos Blood Witch 
11	Fatal Fumes 
11	Fluxcharger 
11	Gleam of Battle 
11	Goblin Test Pilot 
11	Golgari Cluestone 
11	Gruul Cluestone 
11	Haazda Snare Squad 
11	Haunter of Nightveil 
11	Hidden Strings 
11	Hired Torturer 
11	Izzet Cluestone 
11	Korozda Gorgon 
11	Krasis Incubation 
11	Legion's Initiative 
11	Lyev Decree 
11	Maw of the Obzedat 
11	Maze Abomination 
11	Maze Behemoth 
11	Maze Glider 
11	Maze Rusher 
11	Maze Sentinel 
11	Mending Touch 
11	Mindstatic 
11	Morgue Burst 
11	Murmuring Phantasm 
11	Mutant's Prey 
11	Obzedat's Aid 
11	Opal Lake Gatekeepers 
11	Phytoburst 
11	Possibility Storm 
11	Punish the Enemy 
11	Rakdos Cluestone 
11	Reap Intellect 
11	Renegade Krasis 
11	Renounce the Guilds 
11	Restore the Peace 
11	Riot Control 
11	Riot Piker 
11	Rot Farm Skeleton 
11	Runner's Bane 
11	Saruli Gatekeepers 
11	Scab-Clan Giant 
11	Scion of Vitu-Ghazi 
11	Selesnya Cluestone 
11	Showstopper 
11	Simic Cluestone 
11	Sinister Possession 
11	Sire of Insanity 
11	Skylasher 
11	Smelt-Ward Gatekeepers 
11	Species Gorger 
11	Steeple Roc 
11	Sunspire Gatekeepers 
11	Tajic, Blade of the Legion 
11	Thrashing Mossdog 
11	Trait Doctoring 
11	Ubul Sar Gatekeepers 
11	Uncovered Clues 
11	Varolz, the Scar-Striped 
11	Viashino Firstblade 
11	Weapon Surge 
11	Woodlot Crawler 
11	Zhur-Taa Ancient 
13	Blast of Genius 
13	Maze's End 
13	Nivix Cyclops 
13	Plasm Capture 
13	Trostani's Summoner 
14	Ascended Lawmage 
14	Bronzebeak Moa 
14	Deputy of Acquittals 
14	Jelenn Sphinx 
14	Kraul Warrior 
14	Notion Thief 
14	Pilfered Plans 
14	Pyrewild Shaman 
14	Rakdos Drake 
14	Rubblebelt Maaka 
14	Spike Jester 
14	Voice of Resurgence 
14	Wake the Reflections 
15	Warleader's Helix 
17	Carnage Gladiator 
17	Deadbridge Chant 
17	Drown in Filth 
17	Gruul War Chant 
17	Lavinia of the Tenth 
17	Master of Cruelties 
17	Mirko Vosk, Mind Drinker 
17	Warped Physique 
18	Orzhov Cluestone 
18	Teysa, Envoy of Ghosts 
18	Tithe Drinker 
19	Boros Cluestone 
19	Emmara Tandris 
19	Ral Zarek 
19	Render Silent 
20	Advent of the Wurm 
20	Bred for the Hunt 
20	Feral Animist 
20	Melek, Izzet Paragon 
20	Ruric Thar, the Unbowed 
20	Savageborn Hydra 
21	Blood Baron of Vizkopa 
22	Clear a Path 
22	Sin Collector 
24	Pontiff of Blight 
24	Unflinching Courage 
25	Gaze of Granite 
25	Progenitor Mimic 
26	Vorel of the Hull Clade 
27	Zhur-Taa Druid 
3	Breaking 
3	Entering 
40	Dimir Guildgate 
41	Selesnya Guildgate 
51	Golgari Guildgate 
53	Gruul Guildgate 
55	Izzet Guildgate 
58	Boros Guildgate 
61	Azorius Guildgate 
67	Putrefy 
68	Rakdos Guildgate 
7	Burn 
7	Turn 
79	Simic Guildgate 
84	Orzhov Guildgate 
87	Wind Drake 
```

Appears that split cards only ever have received English translations on Scryfall, for the most part. This is a deficit in upstream data source.

Maybe it's an oversight on their part or still on the backlog. If it's a critical issue here, I can look into alternatives.

cc: @csuhta

**Comment by csuhta** [comment]
We haven't been able to pull localized data for split cards in DGM because many of the pages on Gatherer are corrupt or incorrect. We've reported it to WotC but they haven't published a fix.

For example: 
https://gatherer.wizards.com/Pages/Card/Details.aspx?printed=true&multiverseid=370080

- Same mana cost on both sides (we can recover from this issue)
- Name doubled-up on both sides (we can recover from this issue)
- No text on second side (We can't sync this page accurately, have to stop here, there is no text anywhere we can copy in)

If you have this localized data transcribed somewhere else, we'd be happy to import it.

**Comment by Fryyyyy** [comment]
Can't you still continue - not have the text but at least still get the name ?

**Comment by ZeldaZach** [comment]
After speaking with upstream, I unfortunately have to no-fix this unless someone were to manually transcribe the contents (which is time consuming and not too practical). Hopefully Gatherer gets an update in the future, or another source of this data comes about.

Sorry mate :(
