### ISSUE TITLE
Add isPaper/Mtgo/Arena to "AllCards"

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#461]
The isOnlineOnly attribute only applies to individual printings of a card, which makes sense. However there are some cards like Shorecomber Crab that do not exist in paper in any printing. There should be a better way to determine this than going to allSets.json and checking if any printing of that card is not online only. I see two good options, which are not mutually exclusive:

Add an attribute in allCards.json to indicate where the card in general (regardless of printings) is available. Could be an object with values "paper", "MTGO", and "arena" each of which is true or false.

Add an attribute in allSets.json to indicate where that set was released. Same structure as above.

**Comment by ZeldaZach** [comment]
I could see expanding `isPaper, isMtgo, and isArena` to AllCards as a collective OR for the printings.

I really want to move away from AllCards right now. It seems almost all of the questions we get asked about that file are solved with AllSets... Issue for another ticket, but AllCards will be renamed soon.

**Comment by ZeldaZach** [comment]
After discussing it further with the team, this kind of operation breaks the "atomic" nature of AtomicCards (formerly AllCards). As such, I can't seem to justify adding such a feature at this time. We highly discourage the use of the AtomicCards file for anything other than seeing if a card exists, and always push for AllPrintings to be the go-to file.
