### ISSUE TITLE
Missing promos

### ISSUE THREAD

**Issue by fenhl** [mtgjson/mtgjson#461]
I've noticed that the pFNM printing of [Sylvan Scrying](https://mtg.wtf/card/bfz/192) is missing. We should also check for other missing promos.

**Comment by fenhl** [comment]
[Source for the promo](https://magic.wizards.com/en/articles/archive/feature/april-through-june-fnm-promo-update-2016-03-31)

**Comment by fenhl** [comment]
Additional missing promos I've found:

* [Capture of Jingzhou; Doran, the Siege Tower; Gaddock Teeg; Prismatic Geoscope (Judge Gift Program)](https://twitter.com/MagicJudges/status/912315795920834560)
* [Moat (Magic Online Holiday Cube)](https://magic.wizards.com/en/articles/archive/arcana/wallpaper-day-moat-2012-12-20)
* [Mutavault (Grand Prix); Noble Hierarch (Pro Tour)](https://magic.wizards.com/en/articles/archive/organized-play/grand-prix-updates-2018-promos-schedules-and-day-two-cut-2017-10-26)

**Comment by ZeldaZach** [comment]
Addressed in V4
