### ISSUE TITLE
Ixalan on Gatherer

### ISSUE THREAD

**Issue by ShawnieBoy** [mtgjson/mtgjson#463]
Ixalan is on Gatherer, however just found a discrepancy between the dinosaur subtype update. Ripscale Predator was listed on the [site](https://magic.wizards.com/en/articles/archive/card-preview/royal-recipe-dinosaur-tribal-2017-09-06) as becoming a dinosaur, although this is not on gatherer. Which is correct?

**Comment by fenhl** [comment]
We should assume that Gatherer is correct unless Wizards indicate otherwise. Given that Eli Shiffrin has [commented](https://www.reddit.com/r/magicTCG/comments/7150ny/ixalan_is_up_in_gatherer/dn8hkho/?context=3) on a Reddit thread pointing this out, they're probably aware of the discrepancy.

**Comment by DanielHeath** [comment]
Thanks for running this! 

Anything I can do to help out? Want me to build the new set JSON or anything?

**Comment by fenhl** [comment]
That would be great, I don't think anyone is doing that yet.

**Comment by tooomm** [comment]
@ShawnieBoy are you sure Ripscale Predator is even part of this set?

It's also not listed in the wizards gallary from last week:
https://magic.wizards.com/en/articles/archive/card-image-gallery/ixalan
Or at Scryfall: https://scryfall.com/search?q=%2B%2Be%3Axln+predator&order=set

I guess your article has false information.

**Comment by silasary** [comment]
It's not in the set.  The article lists all previous cards which will be given errata to become Dinosaurs, as of the Ixalan Rules Update.

It may be that that errata will be published in a week, when the Rules Update goes live.
