### ISSUE TITLE
frameEffect missing from AllSets

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#463]
#### Description of Bug:

It's per-printing not per-card so understandably got removed from AllCards, but it seems it accidentally got removed from AllSets too.

It should definitely be there.

**Comment by fenhl** [comment]
Probably a result of <https://scryfall.com/blog/new-preview-field-and-frame-effect-deprecation-notice-213>.

**Comment by ZeldaZach** [comment]
Yeah I'll have a fix for this up with a new release (because I have to end support for frameffect at the same time)
