### ISSUE TITLE
pPRE / ptc is very dubious

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#467]
In the olden days there were very few promos per prerelease.

Nowadays nearly every rare/mythic can get stamped version. For a while MCI and mtgjson added new cards, but at some point they just gave up.

[Here's one possible data source](http://sales.starcitygames.com/category.php?cat=5333&start=0).

From what I've seen scryfall redid it manually. mtg.wtf is following mtgjson for now.

**Comment by ZeldaZach** [comment]
Addressed in SF, which means V4 supports it
