### ISSUE TITLE
AllCards/AllSets for more formats

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson#47]
Continuation of https://github.com/mtgjson/mtgjson/issues/178

Currently, we will build all sets in existence into these two files. Should we look into a limiting factor, or have different downloads? Technically, they're all real magic cards, so I'd like to keep them bundled. They have an annotation that they're not legal (silver boarder) and most people can infer that information.

Discussions welcome!

**Comment by KingSupernova31** [comment]
Doesn't the "legalities" field accomplish this? Un-cards, Proposal, etc have no legalities at all, whereas things like Chaos Orb and Shahrazad do. (They're just banned.)

**Comment by ZeldaZach** [comment]
I believe you are correct, @KingSupernova31 . People can read up on the legalities field to determine card types.

I do plan on making Standard.json, Modern.json, etc in the future. But that's a diff ticket.

**Comment by ancestral** [comment]
I would love to have download links for the following:

* Standard
* Modern
* Legacy
* Vintage
* Commander
* No-Un Cards

(Sorry if this belongs in a different ticket…)

**Comment by ancestral** [comment]
Non-playable tournament cards like 1996 World Champion, Planechase Schemes and Vanguard cards exist in the No-Un Cards. Either this is a mistake, or we need a “tournament-compatible” download.

**Comment by ZeldaZach** [comment]
Those should be pulled out from the NoUn file. A sweep for "Not Legal" in Vintage should help clear that up

**Comment by ancestral** [comment]
Well, I want a file that has every tournament compatible card. In other words, banned cards that *could* be unbanned.

**Comment by ancestral** [comment]
I guess the question is, what’s the difference between no-Un and Vintage? Ante cards?

**Comment by ZeldaZach** [comment]
Those are banned. Not legal is different

**Comment by ancestral** [comment]
Revisiting this. @staghouse supported me in the idea of having format-specific downloads beyond just Standard, Modern and Vintage, which is really what this ticket was about in the first place.

The suggestion is one for each of the formats Scryfall supports (Legacy, Brawl, Commander, Pauper, Penny Dreadful and Duel Commander). If you want to stick with Wizards-recognized formats only of those, all those minus Duel Commander and Penny Dreadful.

**Comment by ZeldaZach** [comment]
What I'm looking for now is essentially an expansion of what we offer

We have `Vintage.json`, `Standard.json`, etc. These files are all a subset of `AllSets`. I'm looking for `VintageCards.json`, `StandardCards.json`, etc which will be a subset of `AllCards`.

**Comment by henry739** [comment]
Actively working on this; please could I be assigned?

**Comment by ZeldaZach** [comment]
(Can only assign to those on staff/collab, but consider the issue yours!)
