### ISSUE TITLE
More Prices Support (file formats)

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson#473]
Providers have asked for SQL/SQLite/CSV formats of the daily price data. Seems reasonable.

**Comment by ZeldaZach** [comment]
cc: @omfgitsmark

**Comment by omfgitsmark** [comment]
Do they want a seperate SQLite database of just prices or should we just rebuild the AllPrintings.sqlite file in a price build?

**Comment by ZeldaZach** [comment]
Probably the latter. Since we have prices included in the SQL already

**Comment by omfgitsmark** [comment]
Alright, I updated the build script to rebuild mtgsqlive during a price build. I will use tonight's price build to test and make sure it works correctly before closing this.

**Comment by omfgitsmark** [comment]
Working beautifully. All sql and csv files are now generated during a price build and uploaded daily.
