### ISSUE TITLE
Related Tokens issue

### ISSUE THREAD

**Issue by JineteDV** [mtgjson/mtgjson#475]
Selecting all tokens option for cards like Dowsing Dagger, Huntmaster of the Fells, and treasure map doesn’t also make a token of the backside and attach the card to the token. Selecting all tokens for Arlinn Kord or Gideon, Ally of Zendikar doesn’t even make their emblems.
Doubling clicking on treasure map puts it in the land row instead of the noncreature and nonland row.

**Comment by ZeldaZach** [comment]
This sounds like an issue for the http://github.com/cockatrice/magic-token repo
