### ISSUE TITLE
SetList.json does not include Salvat 2005 nor Salvat 2011 expansions.

### ISSUE THREAD

**Issue by MarkMYoung** [mtgjson/mtgjson#478]
Salvat 2005 cards are white bordered and feature a flying Pegasus as expansion symbol and printed in Spanish, French, and Italian.
https://mtg.gamepedia.com/Salvat_2005

Salvat 2011 cards are black bordered and feature only the head and wing of the Pegasus as expansion symbol and printed only in Spanish.
https://mtg.gamepedia.com/Salvat_2011

https://mtg.gamepedia.com/Magic_Encyclopedia_(Salvat)

I have over 20 cards from these expansions.  I'm loooking for someone to start recognizing these expansions so I can inventory and collect more of them.

**Comment by ZeldaZach** [comment]
Addressed in v4.1
