### ISSUE TITLE
Include number of cards in set

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson#48]
What kind of information do we want? Do we want how many cards are in the "base" set? The "total" set (w/ welcome decks n such)? I'd like a discussion for this before we look into impl.

Cite: https://github.com/mtgjson/mtgjson/issues/551

**Comment by tooomm** [comment]
I think going with wizards here and putting number of cards in "base" set (259)...

https://magic.wizards.com/en/products/coming-soon
![grn](https://user-images.githubusercontent.com/9874850/46593024-4e41b880-cac8-11e8-9096-2a7ceb96326d.png)

...instead the "total" set (273)...

https://scryfall.com/sets/grn?order=set&as=grid

...makes most sense if we are to include only one value.

That's also the base value printed on every card (x/259): https://scryfall.com/card/grn/272/vraskas-stoneglare

MTGJSON could give a hint that the set contains more cards than the core cards like "259+".

<br>

But doing so is not giving all information. Sure, one could read the base set value of 259 and then count all cards in the set to get the other value etc.
Actually that is another argument pro base set number over total cards.

Is having two fields (set_size and set_size_total) or a field with combined values a good option?
(base set/total set --> 259/273)
