### ISSUE TITLE
Missing split card Start//Finish

### ISSUE THREAD

**Issue by DJCatBlitz** [mtgjson/mtgjson#480]
#### Description of Bug:
The Start part of split card Start//Finish is missing
It seems it was overwritten by the test card Start//Fire

**Comment by DJCatBlitz** [comment]
Now Bind and Liberate also also gone (for the same reason as above I think)

**Comment by ZeldaZach** [comment]
Will investigate soon. Thanks for the report.

**Comment by DJCatBlitz** [comment]
Just a proposal:
Could you hard code at least for the three double defined cards something to skip the mystery booster cards, so the "real" cards show up again?
I assume the correct fix is cmplicated, because card name can't be used as a key?

**Comment by kodawah** [comment]
@DJCatBlitz one idea could to have separate fields, as exposed here https://github.com/mtgjson/mtgjson/issues/532: ideally Name could be the card as printed (with // and whatnot), and VariantName could be the single side of the card

**Comment by ZeldaZach** [comment]
This is addressed in v5, will not be addressed in v4
