### ISSUE TITLE
Iconic Masters

### ISSUE THREAD

**Issue by fenhl** [mtgjson/mtgjson#481]
IMA is now on Gatherer. Someone who has working rebuilds should run one.

**Comment by bakert** [comment]
I'm working through this at the moment but it's my first time and it's fairly slow going. I'm nearly there though (I think). Pull request later on today I hope.

**Comment by bakert** [comment]
Also Duel Decks: Merfolk vs. Goblins.

**Comment by bakert** [comment]
#486 is the PR but it definitely has issues.
