### ISSUE TITLE
mtgJSON mtgArenaId discrepancies

### ISSUE THREAD

**Issue by peardox** [mtgjson/mtgjson#481]
I've found some small issues using ELD.json 

You quote all the cards with mtgArenaId where applicable

I noticed one discrepancy between mtgJSON + Arena logs (Lonesome Unicorn) - where do the codes come from?

The different code numbers were worked out from a screen grab of a booster opening vs the JSON in the log vs ELD.json

Also Arena have Wildcards - there's an uncommon below (code = 8), it'd be cool to have those, I guess they're Arena only tokens?

Here's a translation of the log snippet below. The 'translation' is in the same order as the JSON extracted from Arena logs

I suspect there will be other discrepancies - found this one by chance

(C) Gingerbread Cabin
(C) Fling
(C) Sporecap Spider
(C) ??? 70168 ??? Lonesome Unicorn - mtgJSON = "mtgArenaId": 70473,
(C) Redcap Raiders
(U) Keeper of Fables
(R) Wishclaw Talisman
(U) Uncommon Wildcard

And the raw log

{
  "cardsOpened": [
    {
      "grpId": 70392,
      "goldAwarded": 0,
      "gemsAwarded": 0,
      "set": ""
    },
    {
      "grpId": 70273,
      "goldAwarded": 0,
      "gemsAwarded": 0,
      "set": ""
    },
    {
      "grpId": 70323,
      "goldAwarded": 0,
      "gemsAwarded": 0,
      "set": ""
    },
    {
      "grpId": 70168,
      "goldAwarded": 0,
      "gemsAwarded": 0,
      "set": ""
    },
    {
      "grpId": 70283,
      "goldAwarded": 0,
      "gemsAwarded": 0,
      "set": ""
    },
    {
      "grpId": 70310,
      "goldAwarded": 0,
      "gemsAwarded": 0,
      "set": ""
    },
    {
      "grpId": 70257,
      "goldAwarded": 0,
      "gemsAwarded": 0,
      "set": ""
    },
    {
      "grpId": 8,
      "goldAwarded": 0,
      "gemsAwarded": 0,
      "set": ""
    }
  ],
  "totalVaultProgress": 5.0,
  "wildCardTrackMoves": 1,
  "wildCardTrackPosition": 21,
  "wildCardTrackCommons": 0,
  "wildCardTrackUnCommons": 0,
  "wildCardTrackRares": 0,
  "wildCardTrackMythics": 0
}

**Comment by ZeldaZach** [comment]
I don't see any issues with arenaIDs currently, but if you have a specific list do let me know. 

I also don't support wildcards right now as they don't really serve a purpose for data collections as they have no attributes or anything.
