### ISSUE TITLE
Tokens with multiple UUIDs

### ISSUE THREAD

**Issue by omfgitsmark** [mtgjson/mtgjson#482]
It's been reported that there are duplicate tokens appearing. They have the same scryfallId but different mtgjson UUIDs.

Example given:
"Brainiac" token from UST
3edb5529-0895-5bd1-9852-365d42474f39
d2690c9c-fb4d-5235-91a9-125755c09929

**Comment by ZeldaZach** [comment]
Looks to be an upstream issue that was fixed.
