### ISSUE TITLE
Inconsistencies surrounding types, subtypes and super types in CardTypes.json

### ISSUE THREAD

**Issue by Frankacy** [mtgjson/mtgjson#485]
#### Description of Bug:

I've noticed that `CardTypes.json` does not, in fact, contain all card types. 

It seems to be missing types and subtypes from Unglued/Unhinged (such as Clamfolk, Cyborg, Donkey, etc), promotional cards (such as Autobot, Legend), and other special releases (like the Hero super type).

I was wondering if this is by design, and if so, are there any plans to supply a complete list of types?

**Comment by ZeldaZach** [comment]
Wizards doesn't include these types in their comprehensive rules, so I don't have a source for this information. [I sent a tweet](https://twitter.com/Zoozach/status/1200570020977360897) so we can wait and see what happens for now.

**Comment by ZeldaZach** [comment]
Sooo upstream has no desires to track such a thing. I'm gonna have to figure out a method. For the time being, it's black/white border only unfortunately.

**Comment by Frankacy** [comment]
First of all, thanks for looking into this 🙇🏻‍♂️

I wasn't aware these types were coming from the comp rules. From that perspective, the current behaviour makes sense. If the intention is only to have tournament-legal card types, that's totally fine. Though it might be a good idea to mention it in the documentation :)
