### ISSUE TITLE
@sembiance/xbase has removed the logging commands used in base

### ISSUE THREAD

**Issue by bakert** [mtgjson/mtgjson#485]
base.info, base.debug, etc.

A new `npm install` now leaves you with a broken setup. You have to manually add the logging stuff back in.

**Comment by bakert** [comment]
I guess we can change package-lock.json to have the appropriate pointer to a github hash and never update it and keep using an old version. If we end up keeping package-lock.json under source control. See #486

**Comment by gwax** [comment]
Cleaner solution is probably to replace the sembiance/base logger with [winston](https://www.npmjs.com/package/winston).

**Comment by gwax** [comment]
I'm working on this and a few other related issues; I'll probably get something in soon (next day or so).

**Comment by ZeldaZach** [comment]
@gwax Thanks for your help on this issue

**Comment by gwax** [comment]
Almost have the PR ready; it turned out to be a lot hairier than I thought.
