### ISSUE TITLE
Proposal: link split cards by their UUIDs

### ISSUE THREAD

**Issue by emaiax** [mtgjson/mtgjson#486]
About split cards, as the doc says `Basically each ‘sub-card’ has its own record`, this means they should be the "same card" (as in having the same multiverse_id) but also has it's own record? My question is regarding specifically about having a way to identify a counter part of a split record.

For example, looking for `Wax/Wane`, i can see we have 6 records, 3 split cards from `Archenemy, Invasion, World Championship Decks 2002` sets. The last one doesn't have a MID as expected, but looking for the previous 4 cards, i've found this 3 distinct MIDs `[220502, 220502, 20582, 20581]`

I know this came straight from Gatherer, as the image shows, and to be honest i haven't found any difference between them, even those from `Invasion`, and yet they have different MIDs.

![image](https://user-images.githubusercontent.com/1289661/69770931-a83c8c00-1169-11ea-84db-5b41bb775d27.png)

I think we should have a better and more consistent way to find a counter part of a split card, double faced, dual and etc. As they are the only one to have `names`, they also could have `linked_id` to be clear we're linking both "cards".

**Comment by ZeldaZach** [comment]
We currently have a `variations` field which links a card to other records by a list of MTGJSON UUIDs. I feel like we can steal from that field and make `namesIds` which would link to all of the appropriate MTGJSON UUIDs. Seems like a solid suggestion.

**Comment by ZeldaZach** [comment]
Also, _don't_ use multiverseIDs for anything useful. They're inconsistent and not found in every record.
