### ISSUE TITLE
Wrong Price Version for Online Cards

### ISSUE THREAD

**Issue by eddie-g** [mtgjson/mtgjson#489]
There is a bug in pricing with all the Promo WAR walkers, and perhaps others too.

For example: 

Teferi, Time Raveler
for UUID(cd15b31d-1c66-5421-a9cb-cecb83f08f53) this is the WAR edition 221 
last updated date is : 2019-10-08 with price 45.99

However it seems that 

Teferi, Time Raveler
for UUID(7d8e9b39-11b3-5e45-a246-93b962f404b3) this is WAR edition 221★
has last updated date of : 2019-12-06 with price 51.8 which is close to the current reflected price for the non promo version.

![image](https://user-images.githubusercontent.com/8391906/70368827-6ac8b480-1875-11ea-999a-a3741f9e3970.png)

Likely there is a mixup somewhere with the promo/non promo versions.

**Comment by ZeldaZach** [comment]
This should be addressed in v5 now :)
