### ISSUE TITLE
Some card are missing Foreign Data

### ISSUE THREAD

**Issue by jazcarate** [mtgjson/mtgjson#490]
#### Description of Bug:
In `AllCards.json` file, there are cards with empty `foreignData` key, when ther should have.

At first glance, I though that cards that had multiple printings, and the original printing had no foreign data, were not calculating the foreign data from subsequent printings.
i.e:
*Arc Lightning* has an empty array as `foreignData`.
Original printing of Arc Lighthing, in [Gatherer](https://gatherer.wizards.com/Pages/Card/Languages.aspx?multiverseid=5733), has no languages.
The Khans of Tarkir printing, in [Gatherer](https://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=386478) does have languages.

I would expect that *Arc Lightning* to have the foreign data of the latter set.

Yet, I've found that *Righteousness* (first printed in alpha, with no languages. Last printed in Throne of Eldraine with languages), does have the correct `foreignData`.

Even more weird, *Gruesome Slaughter*'s [gatherer page](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401905) has languages, and there is only one printing; yet `AllCards.json` has an empty `foreignData`.

Am I mistaken in thinking that the source of truth is Gatherer? Because it might happen that if you go by the first "prints" result on `scryfall`, there three examples work out.

- *Arc Lightning*'s [Scryfall](https://scryfall.com/card/prm/55791/arc-lightning) first printing is a English only promo (no `foreignData`).
- *Righteousness*'s [Scryfall](https://scryfall.com/card/eld/27/righteousness) first printing is Throne of Eldraine, with all the languages (and has correct `foreignData`).
- *Gruesome Slaughter* [Scrydall](https://scryfall.com/card/bfz/9/gruesome-slaughter)'s first printing is an English only promo (no `foreignData`)

**Comment by ZeldaZach** [comment]
Gatherer is too fractured to accurately pull primary data from it. As such, we default to SF currently, using gatherer as a backup for several fields.

For foreign printings, if any exist, it should take place in AllCards. This is something I will look into soon.

**Comment by ZeldaZach** [comment]
Addressed in v5, will not be backporting to v4.
