### ISSUE TITLE
Price Support from new sources

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson#492]
From my CommandFestDC Trip, it seems people want access to the following: 
- CardKingdom Pricing
- StarCityGames Pricing
- Amazon Pricing

Will be investigating soon.

**Comment by kodawah** [comment]
MagicCardMarket?

**Comment by ZeldaZach** [comment]
Support for MKM is complete in v5. Not backporting. Ticket staying open.

**Comment by ZeldaZach** [comment]
Support for CardKingdom is complete in v5 31c318717ebbf4a89a664f4949a3f4193bae19cd. Not backporting. Will be closing the ticket and calling other providers advancements of the future
