### ISSUE TITLE
Judge Gift Program JSON expansion outdated

### ISSUE THREAD

**Issue by brunoliveiralcantara** [mtgjson/mtgjson#497]
I needed cards like Imperial Seal that are not in the JSON of this expansion pJGP (Judge Gift Program).

Would you like someone to update it?

Thank you.

**Comment by brunoliveiralcantara** [comment]
?

**Comment by ZeldaZach** [comment]
Is there a place to find the full list of cards? Scryfall, magiccardsinfo, etc?

**Comment by brunoliveiralcantara** [comment]
Yes Zach I know this, but I would like to know if there will be update in the JSON of this edition to contain the missing letters. Only that.

hug

**Comment by ZeldaZach** [comment]
For us to add it to the JSON we usually need a source that contains it. Most of what we do isn't hand written (minus corrections). Do you know of any place we can find a list with all information so we can possibly scrape it?

**Comment by brunoliveiralcantara** [comment]
I understand, I only know 1 site in Brazil that contains this information: http://ligamagic.com.br/?view=cards/search&card=ed%3djr

I hope you have helped in some way and thank you very much for your feedback Zach.

**Comment by ZeldaZach** [comment]
Added in V4 via SF :)
