### ISSUE TITLE
Homura's Essence has no text key-value

### ISSUE THREAD

**Issue by bakert** [mtgjson/mtgjson#498]
Because it is missing from the Gatherer page: http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=84716

**Comment by bakert** [comment]
We should patch until it is fixed. Do we also have a way of notifying WotC?

**Comment by fenhl** [comment]
Unfortunately no. You could try contacting customer support, of course, but they have been notoriously unresponsive regarding anything website-related in my experience. Patching it and moving on is probably the best approach.

**Comment by bakert** [comment]
I have started to try and fix this. If I pull/merge latest master and without making any changes run `node build/buildSet.js SOK` (multiple times) these things happen:

(1) I lose the translations for Chinese Simplified, French, German, Italian, Japanese, Brazilian Portuguese and Spanish for Rune-Tail's Essence, Erayo's Essence and Sasaya's Essence. And what is more the English replacing them is Rune-Tail, Kitsune Ascendant, Erayo, Soratami Ascendant and Sasaya, Orochi Ascendant not the flip side name.

(2) The text of each of these three Essence cards plus Kuon's Essence becomes the text of the original side not the flip side. The types become the original side not the Legendary Enchantment side. Kuon, Ogre Ascendant (the B one) and Homura (the one I'm trying to fix) don't get changed at all.

These are problems with Gatherer that are either new or at least that we aren't working around in current master:

http://gatherer.wizards.com/Pages/Card/Languages.aspx?multiverseid=87595 (translation fail)

The "printed" version is wrong in Gatherer: http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=87595.

We should probably patch all of this, too, or at least not overwrite good translations and rules text with bad.

**Comment by bakert** [comment]
It's not actually this simple. Current master has the translation of the flip side for BOTH sides currently. So we're replacing a bad translation with English. I guess that's actually an improvement?

**Comment by bakert** [comment]
#503 deals with all of this madness in the most sensible way I could find.
