### ISSUE TITLE
License of mtgjson.com datasets 

### ISSUE THREAD

**Issue by marnovo** [mtgjson/mtgjson#499]
What is the license for the datasets currently available at https://mtgjson.com/?

**Comment by lincolnthree** [comment]
https://creativecommons.org/choose/zero/

**Comment by lincolnthree** [comment]
https://github.com/mtgjson/mtgjson/blob/master/LICENSE

**Comment by marnovo** [comment]
Thank you, I was wondering if the LICENSE listed only applied to the code from this repository or also to the datasets.

**Comment by ZeldaZach** [comment]
This applies to the data generated as well
