### ISSUE TITLE
POR Armored Pegasus only has one version in MTGjson

### ISSUE THREAD

**Issue by FirefoxMetzger** [mtgjson/mtgjson#500]
The card Armored Pegasus from POR only has a single entry in AllSets-x.json .

However, there are two versions of that card. magiccards.info tracks them as POR (Portal Demogame) and PO (Portal), but PO is not a valid set code. (See images attached)

Is this a missing card in mtgjson and if so, how to best add it? Or am I blind and the two sets are tracked separately?

[armored pegasus2](https://user-images.githubusercontent.com/4402489/32978030-da41ca2a-cc39-11e7-9ba1-7dcbcf871bc7.jpg)
[armored pegasus1](https://user-images.githubusercontent.com/4402489/32978031-da5f1b66-cc39-11e7-81cc-255f0ecfb6a5.jpg)

**Comment by KingSupernova31** [comment]
Is this fixed in v4?

**Comment by ZeldaZach** [comment]
Looks to be!
