### ISSUE TITLE
Chosen of Markov card on Gatherer returns HTTP 500, crashing generation

### ISSUE THREAD

**Issue by SilverNexus** [mtgjson/mtgjson#501]
The Card "Chosen of Markov" (multiverse id 243229) does not work right on Gatherer. Attempting to access it (from any source, it seems) causes Gatherer to return an HTTP 500 error.
This causes a failure when attempting to encode DKA or allsets from this particular card without a functional cached copy of the set.
Since this is really an upstream issue, any fix would be a workaround. I also don't know where to go to tell the Gatherer site maintainers at Wizards, but I feel they should know of the issue as well.
The only thought I had to prevent failure was to give up on Gatherer for that card after a certain number of retries and then try to get most of the information from somewhere else, say magiccards.info.

**Comment by ZeldaZach** [comment]
Should be fixed with 3.13.1
