### ISSUE TITLE
Some transform cards (especially promotional) has same scryfall_id of both side.

### ISSUE THREAD

**Issue by giniman** [mtgjson/mtgjson#501]
For example, Search for Azcanta // Azcanta, the Sunken Ruin has same scryfall_ids if it is promo

PXLN-74s, PXTC-74 are problem.

Need to check other transform cards.

Thanks.

**Comment by ZeldaZach** [comment]
I'm looking at the outputs, but the appear to be as expected. Unlike Scryfall, who aims to provide whole card objects that include all sides, MTGJSON provides card segments. Transform cards will have the same Scryfall ID as Scryfall sees both sides as one entity. You can link two halves together via "names" or "otherFaceIds"
