### ISSUE TITLE
Meld cards have incorrect Penny Dreadful legality

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#502]
Affected set: https://mtgjson.com/json/EMN.json
Version: 4.6.1+20191222

`Chittering Host` and `Hanweir, the Writhing Township` are not marked as legal in Penny Dreadful, even though both cards on the other side of their meld are.

(`Brisela, Voice of Nightmares` correctly isn't, as `Gisela, the Broken Blade` is not Penny-legal, even though its other part is)

**Comment by ZeldaZach** [comment]
This appears to be an upstream issue. cc: @csuhta

**Comment by csuhta** [comment]
Fixed upstream!
