### ISSUE TITLE
Structures.json

### ISSUE THREAD

**Issue by omfgitsmark** [mtgjson/mtgjson#504]
A file containing the structures in JSON format should be offered, possibly automatically generated.

Currently, in order to change/add/remove a property there are at least 3 things that need to be updated (repo, docs, mtgsqlive), possibly more. If everything references back to a single file, simply changing that file will update everything necessary. It could also be very useful for end users and their projects, and might even be helpful to newcomers.

Even if we don't generate it automatically, just manually maintaining one is still a huge benefit.

My idea for the structure structure:
~~https://gist.github.com/omfgitsmark/8582b05b356abedb4dd1595e40c5ec1a~~
https://gist.github.com/omfgitsmark/11a024d297dcb7dbf2af7831d19f7f61

It could probably be improved, so let me know if you think of anything.

**Comment by sboosali** [comment]
https://gist.github.com/omfgitsmark/8582b05b356abedb4dd1595e40c5ec1a is dead link (or has a typo?)

**Comment by omfgitsmark** [comment]
Yeah, I think I deleted that gist because it was just an example. It's a little outdated now, but I did end up reposting a full Structures.json here: https://gist.github.com/omfgitsmark/11a024d297dcb7dbf2af7831d19f7f61

I'm not sure this idea will ever come to fruition though.

**Comment by ZeldaZach** [comment]
This is a real pain point for me as there's no way I could easily handle this internally unless I started slopping config files together and such... Not sure what our best approach is here.

**Comment by ZeldaZach** [comment]
I've decided to abandon this ticket. We split the repos for a reason when v4 came about, and I'm happy with the results.
