### ISSUE TITLE
Ixalan Flip cards Set Listing returns HTTP 500

### ISSUE THREAD

**Issue by SilverNexus** [mtgjson/mtgjson#505]
Another upstream issue. Fantastic.
It looks like the Sets & Legality page for all Ixalan flip cards return an HTTP 500 error.
At least Legion's Landing, Dowsing Dagger, Search for Azcanta, Growing Rites of Itilmoc, and Primal Amulet all crash on the Sets & Legality page with an HTTP 500. I hadn't tested the others, but I assume they do the same.
Given #501 and #504, I'd imagine something for DFCs in the Gatherer backend is partially broken.

**Comment by ZeldaZach** [comment]
Should be fixed with 3.13.1
