### ISSUE TITLE
Death Baron from PM19 has both foil and non foil versions

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#505]
#### Description of Bug:
Death Baron from PM19 (97d106d2-5270-5a8d-afc0-6e2fcd175edf) has `hasNonFoil` incorrectly set to `false`

The card has both a foil and non foil version, see https://shop.tcgplayer.com/magic/promo-pack-core-set-2020/death-baron?xid=i98c34f92f9b344e3823222d7e10eb24a

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
Fixed upstream
