### ISSUE TITLE
Add isPlanewalkerStamped field to promo pack cards

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#508]
#### Description of Bug:
I propose we should add this field to each card having the silver planeswalker logo, usually coming from the "promo pack" boosters. This is similar to what is is done for prerelease and a few release cards with `isDateStamped`

When using mtgjson with a limited amount of information, currently it is extremely hard to pinpoint exactly to which which version the promo pack points to

**Comment by ZeldaZach** [comment]
Good idea, will see about implementation soon.

**Comment by ZeldaZach** [comment]
Added to v5, not backporting to v4
