### ISSUE TITLE
Running MTGJSONv4 on Windows

### ISSUE THREAD

**Issue by RDWonline** [mtgjson/mtgjson#51]
Using Python 3.7, I did the following:

1. Extracted the contents of mtgjson-master.zip to directory "C:\Users\a046369\Desktop\mtgjson4-master\"
2. Executed "pip3 install -r requirements.txt".  Several messages about files being downloaded and installed
3. From the directory "C:\Users\a046369\Desktop\mtgjson4-master\" I typed:
"C:\Users\a046369\AppData\Local\Programs\Python\Python37-32\python.exe" -m mtgjson
4. I got the error in the attachment

I didn't see a python3.exe file as the original documentation stated.

![pyerror](https://user-images.githubusercontent.com/32939229/46564219-01958c00-c8d4-11e8-84ed-9ddb61c2fc32.gif)

**Comment by ZeldaZach** [comment]
Python3 -m mtgjson4

**Comment by RDWonline** [comment]
I tried that first.  This is the message I got.  Where is that executable?  pythonw -m mtgjson4 didn't work either.

![pyerror2](https://user-images.githubusercontent.com/32939229/46564636-7ec20080-c8d6-11e8-8816-b27bd870ccf2.gif)

**Comment by ZeldaZach** [comment]
You need the path for python3... check out google on how to exec a python script

**Comment by PAK90** [comment]
I found the fix for this: remove `:` from the logfile name generation. Windows doesn't like colons in filenames, apparently.
