### ISSUE TITLE
Unstable variants

### ISSUE THREAD

**Issue by fenhl** [mtgjson/mtgjson#510]
Some of the cards in *Unstable* come in different variants. These variants always have the same name, but include different art (by the same artist or by different artists), rules text, flavor text, watermarks, and/or P/T.

[This Reddit thread](https://www.reddit.com/r/magicTCG/comments/7ho89l/ust_unstable_alternate_artcards_megathread/) includes known cards and variations, but is probably still incomplete.

The question is, how do we want to handle these variants in MTG JSON? Gatherer seems to be limited to a single variant per card name.

**Comment by ZeldaZach** [comment]
TCGPlayer and MTGJSON are working together to solve this issue. I'm in talks with them and will post an update once we have come to an agreement

**Comment by tooomm** [comment]
Official wizards article: https://magic.wizards.com/en/articles/archive/news/unstable-variants-2017-12-06

**Comment by ZeldaZach** [comment]
Yep, we saw the article earlier today and we're working on a fix

**Comment by fenhl** [comment]
Okay so the Killbots even have different names.

**Comment by thg2k** [comment]
Hello everyone, i'm on board with this issue.

I propose to differentiate between cards that only differ by flavor text and artwork (case 1), with those that also change game-wise (card text, P/T etc) (case 2).

Can we go for SAME NAME but DIFFERENT serial number for those in case 1 and DIFFERENT NAME for those in case 2? Examples below (serial / card name):

3a "Amateur Auteur"
3b "Amateur Auteur"
3c "Amateur Auteur"
3d "Amateur Auteur"

3a "Everythingamajig (a)"
3b "Everythingamajig (b)"
3c "Everythingamajig (c)"
3d "Everythingamajig (d)"
3e "Everythingamajig (e)"
3f "Everythingamajig (f)"

**Comment by MarkMYoung** [comment]
Changing the "serial number" will not work.  That letter is used for "card parts" (e.g., split, flip, and transform cards).  It should be handled the same way as FNM Promos or Ugin's Fate cards (which both contain an alternate Dragonlord's Servant) by using a different (possibly pre-existing) expansion.

There were also alternate art foils for Unglued and Unhinged.  For Unglued, TCGplayer and iMtG call them Arena Promos.  For Unhinged, iMtG calls them Unhinged Alternate Foils and TCGplayer leaves them in Unhinged but throws " (FOIL)" on the end of the card name (very bad idea).

**Comment by silasary** [comment]
Worth noting that Kaya, Ghost Assassin (CN2) has an alternate printing, and which is included in the mtgjson set file.

**Comment by CharlesStover** [comment]
Gatherer has been updated with these variants. Each has a unique multiverseid.

**Comment by jceddy** [comment]
I noticed that variants for the following are now in MTGJSON:

Everythingamajig
Garbage Elemental
Ineffable Blessing
Knight of the Kitchen Sink
Sly Spy
Very Cryptic Command
XXX Killbot

But not for the non-functional variants like Novellamental, Target Minotaur, Amateur Auteur and Very Slow Zombie.

**Comment by ZeldaZach** [comment]
Addressed in V4
