### ISSUE TITLE
a handful of cards have the "promo" star (*) prefixed rather than suffixed to the collector number

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#510]
#### Description of Bug:
I noticed a few cards, like Day of Judgement or Gravecrawler from the promos sets, have this oddly formatted number (`*64`) with the star  prefixed rather than suffixed.

For the sake of uniformity, since all recent promos have either a * or a unicode star suffixed, would it be possible to change those number to follow the new format? It would immensely simplify parsing the code.

**Comment by ZeldaZach** [comment]
If you take a look at the card, the number is _actually_ written as is. Unfortunately I am inclined to stick with how it was printed and close as a no-fix. This does bring up a good point on better documentation on my part!

![image](https://user-images.githubusercontent.com/7460172/72314448-08758780-365d-11ea-976a-a6908193afdf.png)

![image](https://user-images.githubusercontent.com/7460172/72314462-11665900-365d-11ea-9062-5daf5bb4a9b9.png)

**Comment by kodawah** [comment]
fair enough, i honestly didn't notice and i agree it's better to keep them as written on the card, thank you

**Comment by kodawah** [comment]
hmm browsing around, there are come cards that are printed as *<num> but they are numbered as <num><star>

example https://scryfall.com/card/proe/4%E2%98%85/emrakul-the-aeons-torn

should those be changed instead?

**Comment by silasary** [comment]
Please report those using the "Report Card Issue" button on the appropriate
Scryfall card pages
