### ISSUE TITLE
a couple of WCD inconsistencies/fixes

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#512]
#### Description of Bug:
Hi, i found a couple of inconsistencies for WCD cards, there still might be more, I'll report here if I find any.

* The following cards should be suffixed with `sb` to indicate they come from the sideboard (and have the sideboard badge)
Envelop - dh39
Shatter - gb219
Relic Barrier - gn147
Misdirection - ab87
Torture - ll59b
Autumn Willow - et83b

* The  *mountain*s in PTC have an incorrect number:
https://scryfall.com/card/4ed/373/mountain
https://scryfall.com/card/ptc/et373/mountain
(same for 374 and 375) should have matching art, but they don't

* All the cards from PTC signed by Shawn Hammer Regnier have an inconsistent number prefix, they are tagged as `srXX` while they should contain the initial of each name (`shrXX`) like the other cards from people with multiple names (like `tvdlXX`)

**Comment by kodawah** [comment]
Misdirection - `ab87sb` would conflict with Wash Out from the same same, so one of the two needs to be changed (Misdirection -> ab87asb?)

**Comment by ZeldaZach** [comment]
Looks like an upstream issue. cc: @csuhta

**Comment by kodawah** [comment]
I reported these with the "report card problem" in scryfall

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
These have all been fixed on Scryfall

**Comment by kodawah** [comment]
thanks @csuhta!
