### ISSUE TITLE
AllPrices paper/paperFoil outdated

### ISSUE THREAD

**Issue by DominikMendel** [mtgjson/mtgjson#513]
### Steps to reproduce
Downloaded AllPrice from 1/11/2020
### What is expected?
paper/paperFoil have prices past 2019-12-05.
### What is actually happening?
There is no updated information for paper/paperFoil after 2019-12-05.
### Other relevant information
There is updated information for mtgo and mtgoFoil though.

**Comment by ZeldaZach** [comment]
Fix incoming
