### ISSUE TITLE
Legendary Cube (PZ1), Treasure Chests (PZ2), and V17. Missing

### ISSUE THREAD

**Issue by MuSanKitty** [mtgjson/mtgjson#514]
FTV: Transform and Explorers of Ixalan released on 11/24 but were skipped in the recent updates..

**Comment by MuSanKitty** [comment]
Either are available as individual sets yet???

**Comment by fenhl** [comment]
V17 is still missing though.

**Comment by tooomm** [comment]
@MuSanKitty you find `E02`here... https://mtgjson.com/json/E02.json

Other is missing as single set and in the big json I guess, yes.

**Comment by MuSanKitty** [comment]
I appreciate it.. Thank you! It isn't actually showing on the webpage so I wasn't sure!

**Comment by tooomm** [comment]
It is showing on the webpage ;)
![untitled](https://user-images.githubusercontent.com/9874850/33670994-b606a466-daa6-11e7-855f-e70ec21ce1e8.png)

But I also always experience refreshing problems with the webpage.
To display the newest version on the main page correctly, you always have to refresh the page for example...
Might be cloudflare caching?

**Comment by ZeldaZach** [comment]
Y'all need to tell me all the sets that aren't up so I can do it all at once 😛

**Comment by fenhl** [comment]
The only three sets newer than *Vintage Masters* that are missing from MTG JSON are *Legendary Cube* (PZ1), *Treasure Chests* (PZ2), and V17.

**Comment by MuSanKitty** [comment]
Might have been a cache problem.  I didn't try again this afternoon, but everyday this week I had gone to look for it and it wasn't there. *shrugs* I got it now so we are good... I do appreciate everyones help.. I'll keep an eye out for the rest :)

**Comment by silasary** [comment]
PZ2 is an ongoing set (similar to PRM), in that new cards are added to it every few months.

Also, neither of them is on Gatherer.

**Comment by ZeldaZach** [comment]
Should be fixed with 3.13.1
