### ISSUE TITLE
Theros - Beyond Death release

### ISSUE THREAD

**Issue by DanielHeath** [mtgjson/mtgjson#515]
The new set is live on gatherer, but not on mtg-json (according to the version file). 

I haven't tried to run the v4 scripts yet, but I could give it a shot if nobody else expects they'll get to it this week.

**Comment by ZeldaZach** [comment]
I didn't bump the version number, but MTGJSON has had Theros for over a week now. I'll publish an official version tomorrow with changelog. 

Thanks for your concern, I do appreciate it!!
