### ISSUE TITLE
New layout for augment cards?

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#515]
The augment cards from Unstable have a different visual layout on the card. Should they receive their own layout in the card file?

**Comment by ZeldaZach** [comment]
That's a good point. We're still not fully set with Unstable yet, but I'll be sure to consider this

**Comment by KingSupernova31** [comment]
I think they should. They're more visually distinct than leveler cards, and those have their own layout.

**Comment by ZeldaZach** [comment]
Addressed in V4
