### ISSUE TITLE
Getting all sets doesn't works on website

### ISSUE THREAD

**Issue by Siemienik** [mtgjson/mtgjson#517]
Hi guys! It's my first issue written here, so I want to thank you very much for an amazing job :)  
#### MTGJSON Version: 4.X.X
I don't know the present version, if I could ask you, please edit this line and add the correct info

#### Description of Bug:
On the mtgjson website, the page which lists all available sets doesn't work:

![image](https://user-images.githubusercontent.com/2893099/72896197-7259f500-3d1f-11ea-9ad8-61ab2d8241ef.png)
https://mtgjson.com/downloads/all-sets/

I will be grateful a lot to resolve this bug,

KIND REGARDS!

**Comment by ZeldaZach** [comment]
Hey @Siemienik I just took a look and it appears you are on an outdated cache. I have triggered the site to dump the entire cache, but if you hard refresh (CTRL+F5 or Shift+Command+R) the page should work for you. Let me know if this is not the case!!
