### ISSUE TITLE
Two typos in ability text

### ISSUE THREAD

**Issue by DJCatBlitz** [mtgjson/mtgjson#518]
#### Description of Bug:
Nexus Wardens: "under you control" -> "under your control"
Skophos Maze-Warden: "until the end of turn" -> "until end of turn"

And as a reminder: Bind//Liberate and Start//Finish are still missing :(
Currently I have to patch the json file for those cards hard coded after each update
I hope this can be fixed somehow

**Comment by skwerlman** [comment]
both of these typos exist in scryfall as well

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by silasary** [comment]
These are fixed
