### ISSUE TITLE
Gatherer has updated Oracle text for Unglued and Unhinned

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgjson#518]
Gatherer has updated Oracle text for Unglued and Unhinned

**Comment by ancestral** [comment]
Unhinged, obviously

**Comment by fenhl** [comment]
There was no announcement as far as I'm aware. Almost every uncard was changed.

**Comment by tooomm** [comment]
Found this tweets by wotc employees:
- https://twitter.com/EliShffrn/status/943227067180527616
- https://mobile.twitter.com/TabakRules/status/943220715276210176

**Comment by ZeldaZach** [comment]
I'll be rebuilding when RIX is on Gatherer. This will be fixed then.

**Comment by ZeldaZach** [comment]
Should be fixed with 3.13.1
