### ISSUE TITLE
Flavor text quote errors

### ISSUE THREAD

**Issue by CajunAvenger** [mtgjson/mtgjson#519]
Many of the older cards with quotes are not linebreaking their attribution, while newer ones are. While working on a fix for this, I also found a number of cards (mostly FNM promos) were missing quotation marks in their flavor texts that were printed on the card.

For the attributions I used the regex `/([^\n])( |["\/] ?)— ?([A-Z"])/`, replacing `capture[0]` with `capture[1] + capture[2] + "\n—" + capture[3]`. The space in capture[2] is now unnecessary and can be removed. This hits 7363 cards, as far as I can tell it only misses the two printings of Sir Shandlar of Eberyn due to the lowercase (note adding /i to get that adds false positives).

As mentioned this ended up digging up about 50 cards with quotation mark issues, which are listed here: https://pastebin.com/vSvtK01g

**Comment by ZeldaZach** [comment]
Looks like an upstream issue. Thanks for taking the time to compile this list!!

cc: @csuhta

**Comment by csuhta** [comment]
Thanks for the 50-card list, we spot checked and confirmed it seems accurate (that we have quote issues to fix there).

For the other flavor text line-break fixes, we are not willing to blindly run a regex of this nature against all of our flavor texts. Would it be possible for you to create a CSV or other list of `scryfallId` fields to target for fixes here?

**Comment by ZeldaZach** [comment]
Primary issue is solved, secondary can be taken upstream
