### ISSUE TITLE
Add MTGO only sets

### ISSUE THREAD

**Issue by Sembiance** [mtgjson/mtgjson#52]
There are several missing MTGO only sets that could be added:
- PRM set. (promo cards)
- Mirrodin Pure vs. New Phyrexia

Theme Decks:
- Boltslinger
- Exiler
- Deathdancer Xira
- Enchantress Rubinia

More sets?

I have an e-mail from someone that lists out a lot of the PRM cards, but I would need to find a more automated way of updating this list, probably looking into the MTGO game files directly to see if I can parse this info out or not.

**Comment by ZeldaZach** [comment]
Addressed in v4 :)
