### ISSUE TITLE
Steamflogger Boss rarity should be Rare instead of steamflogger boss

### ISSUE THREAD

**Issue by CharlesStover** [mtgjson/mtgjson#520]
Current rarity is "steamflogger boss," however according to Gatherer and print, it should just be Rare.

**Comment by ZeldaZach** [comment]
So i'll be closing this as a no fix because if we write it as a rare, some programs may consider it to be any rare in the system. I'd rather them mark it as steamflogger and then determine what they want to do next.

If you disagree, please feel free to give me more info on why it should be rare
