### ISSUE TITLE
Add isOnlineOnly to setlist file

### ISSUE THREAD

**Issue by cheyner** [mtgjson/mtgjson#520]
I routinely will pull in the setlist to make sure i'm up-to-date, but I'd like to excldue online sets.  It'd be super handy to have isOnlineOnly in the setlist file so I can check for it.

**Comment by ZeldaZach** [comment]
Small change, very reasonable. I'll get this added.

**Comment by silasary** [comment]
Can we also get a isPaperOnly while you're in there?

**Comment by ZeldaZach** [comment]
I don't see why not, sure!
