### ISSUE TITLE
Normalise set booster contents

### ISSUE THREAD

**Issue by mirror35** [mtgjson/mtgjson#521]
Set booster contents is not normalised. Booster rarity values do not match card rarities.

Suggest the following format:

booster:[
{type:"rarity", value:"Rare"},
{type:"name", value:"Steamflogger Boss"},
[
...options
]
]

I don't mind implementing this if it's something people want / there are no objections.

**Comment by fenhl** [comment]
See also previous discussion starting at https://github.com/mtgjson/mtgjson/issues/364#issuecomment-314023611.

**Comment by mirror35** [comment]
Thanks - I've knocked together a utility which normalises the data into the format given. The format is extensible so could cope with sheet rarity if this data is available in future.

From what I can see, booster information is hardcoded in the ./shared/set_configs/ directory - but I'm still learning the source layout so I'd appreciate confirmation that this is the case.

Also - is this information used in the code anywhere? Or is it just pulled into the final files when they're created?

Few examples:

TSP:

    "booster": [
        {
            "type": "rarity",
            "name": "Rare"
        },
        {
            "type": "rarity",
            "name": "Uncommon"
        },
        {
            "type": "rarity",
            "name": "Uncommon"
        },
        {
            "type": "rarity",
            "name": "Uncommon"
        },

...

        {
            "type": "rarity",
            "name": "Common"
        },
        {
            "type": "rarity",
            "name": "Special",
            "set": "TSB"
        }
    ]


UST:

....
        {
            "type": "rarity",
            "name": "Common"
        },
        [
            {
                "type": "rarity",
                "name": "Basic Land"
            },
            {
                "type": "name",
                "name": "Steamflogger Boss"
            }
        ],
        {
            "type": "rarity",
            "name": "Token"
        }

**Comment by aritsune** [comment]
is this still planned? it would be incredibly useful for what I'm working on

**Comment by fenhl** [comment]
It doesn't seem to be a priority for any of the core maintainers, but a pull request would be appreciated.

**Comment by ZeldaZach** [comment]
At this time, V4 has removed the "booster" field. It will return in the future when we can figure out how to normalize it. This ticket can be found at https://github.com/mtgjson/mtgjson4/issues/46
