### ISSUE TITLE
Secret Lair (SLD) cards missing multiverseId

### ISSUE THREAD

**Issue by magreenblatt** [mtgjson/mtgjson#522]
#### Description of Bug:
Secret Lair Drop cards exist in Gatherer: https://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&set=[%22Secret%20Lair%20Drop%22]

However, no multiverseId values are included for these cards in AllPrintings.json at the current version.

**Comment by ZeldaZach** [comment]
Yep you're right! cc: @csuhta

**Comment by csuhta** [comment]
Added (for the ones that exist on Gatherer so far)
