### ISSUE TITLE
Various Missing Cards

### ISSUE THREAD

**Issue by cheyner** [mtgjson/mtgjson#523]
#### Description of Bug:
I've been manually going through our card data, and have noticed some missing items.  Here's the run down:

"In Oketra's Name" is missing from Mystery Booster (MB1)

There are several promo versions that are missing.  In this case, the prerelease promo (XXXs) is present but the promo pack version (XXXp) is not.  I've listed the cards as best I could below (I realize the set code would probably be prefixed by "P" in mtgjson, and have looked in those files).
AER-031P	Disallow
AER-109P	Heroic Intervention
AKH-005P	Aven Mindcensor
AKH-065P	Pull from Tomorrow
DTK-120P	Sidisi, Undead Vizier
GRN-008P	Dawn of Hope
GRN-010P	Divine Visitation
GRN-030P	Venerated Loxodon
GRN-044P	Mission Briefing
GRN-075P	Mausoleum Secrets
GRN-084P	Ritual of Soot
GRN-109P	Legion Warboss
GRN-141P	Pelt Collector
GRN-165P	Deafening Clarion
GRN-204P	Tajic, Legion's Edge
GRN-212P	Unmoored Ego
GRN-213P	Vraska, Golgari Queen
HOU-165P	Mirage Mirror
KLD-096P	Noxious Gearhulk
KLD-112P	Combustible Gearhulk
KTK-034P	Clever Impersonator
M15-100P	In Garruk's Wake
M15-231P	Soul of New Phyrexia
OGW-147P	Zendikar Resurgent
ORI-240P	Sword of the Animist
RNA-042P	Mass Manipulation
RNA-122P	Biogenic Ooze
RNA-130P	Guardian Project
SOI-016P	Eerie Interlude
SOI-242P	Anguished Unmaking
WAR-001P	Karn, the Great Creator
WAR-062P	Narset's Reversal
WAR-079P	Bolas's Citadel
WAR-097P	Liliana, Dreadhorde General
WAR-197P	Feather, the Redeemed
WAR-244P	Blast Zone
WAR-270P	Tamiyo, Collector of Tales

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
I spot-checked this, and this report seems to be a bit outdated or working from incorrect data.

- In Oketra's Name is not in MB1, that was a mistake that WotC corrected after publishing their full card list. A lot of other sites (including Scryfall) originally generated an image for that card and then removed it later. https://magic.wizards.com/en/articles/archive/news/mystery-booster-revealed-2019-11-11
- WAR#270 is Jace, Arcane Strategist, not Tamiyo, Collector of Tales
- PHOU#165p is here https://scryfall.com/card/phou/165p/mirage-mirror
- and so on

**Comment by ZeldaZach** [comment]
Thanks for that. The version number posted made me question it a bit, but I couldn't find any answers.

**Comment by cheyner** [comment]
Ok.  That 165p version of Mirage Mirror, is not in the PHOU file that I downloaded on 1/30.  And so on.  

I can see that the current PHOU.json file does have the card as expected.  So not sure what changed in the meantime.

**Comment by cheyner** [comment]
Here is one that is still missing from the MTGJSON file:
https://www.cardmarket.com/en/Magic/Products/Singles/Theros-Beyond-Death-Promos/Legion-Warboss

https://scryfall.com/search?as=grid&order=released&q=%21%22Legion+Warboss%22&unique=prints
