### ISSUE TITLE
Path to Exile (MagicFest 2020) hasNonfoil incorrectly set to false

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#524]
#### Description of Bug:
https://scryfall.com/card/pf20/1/path-to-exile

There are two versions of this card, one is foil and one is non foil.

**Comment by kodawah** [comment]
actually there are a couple of promo pack cards with incorrect `hasNonFoil` too

* a27c50c88ae8 Steel Leaf Champion
* 8e22c3379ed4 Athreos, Shroud-Veiled

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
I fixed Path to Exile and Athreos, Shroud-Veiled upstream. I don't know which version of Steel Leaf Champion is being referred to here, could you link to a Scryfall permapage?

**Comment by kodawah** [comment]
thanks @csuhta, i can't find it any more in the most recent dump either, maybe it got fixed already

while on the subject, would it be possible to add the promo pack version for https://scryfall.com/card/grn/109/legion-warboss please?

**Comment by csuhta** [comment]
Added https://scryfall.com/card/pgrn/109p/legion-warboss

**Comment by kodawah** [comment]
thank you all, I'll go ahead and close this for now :-)
