### ISSUE TITLE
More range groups for Set information

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#525]
The Set information contains the overall set size (TotalSetSize) and number of actual cards (BaseSetSize) and it's great for spotting promo cards sneaking in the main expansion

However with the recent addition of extended art, showcase and super foils, there is no information where each of these duplicated card set starts or ends, making it very hard to identifying cards and introducing a lot of aliasing

Would it be pessible to add `ranges` to the set information so that when parsing cards it is possible to pin point exactly where these fall?

Example
```json
"TotalSetSize" : 397,
"BaseSetSize" : 269,
"Categories" : [
{
    "Type" : "borderless planeswalkers",
    "StartNumber" : 270,
    "Size" : 3
},
{
    "Type" : "showcase",
    "StartNumber" : 273,
    "Size" : 30
},
...
]
```

**Comment by ZeldaZach** [comment]
I've decided against this feature, simply because there's no easy way to do this, and to do it manually is a real PITA. Wizards is very inconsistent with these type of things, so having inconsistent data and orderings is not something I feel comfortable doing.

Would consider reviewing a PR, but it's going to be closed for the time being.

**Comment by kodawah** [comment]
@ZeldaZach isn't there some way that we could pull this information from scryfall? Somewhat mimicking the separations they have in sets https://scryfall.com/sets/thb ( In Boosters • 254 cards ,  Extended Art Cards • 55 cards , Promos • 6 cards )

Without a precise information like that right now it's not possible to programmatically determine if a card is a Bundle promo, and it would vastly simplify detecting the other card styles

**Comment by silasary** [comment]
Scryfall doesn't provide that data through its API right now

**Comment by kodawah** [comment]
@silasary are you saying that it's a limitation upstream would need to address?

**Comment by lyngbach** [comment]
I would just like to add in here that the original suggestion does not always fit in the scenario (like it was pointed out with WotC inconsistently handling this).

I am referring to the Arabian Nights set where `baseSetSize` is 78 and `totalSetSize` is 92 with the variants being the darker symbol cards that is mixed in all over in the set list.

**Comment by kodawah** [comment]
@lyngbach i don't think using ARN is a fair comparison, this would be strictly for the "promo-non-promo" cards that are mixed in the "non-promo" set in Scryfall (with incremental collector numbers) such as from ELD onwars. Nobody is suggesting to do that for cards that feature alternative cards which reuse the same collector number

**Comment by lyngbach** [comment]
I am all in for that. I too need a way to determine the difference in a programmable way, just wanted to point out that some sets have a different `baseSetSize` compared to the `totalSetSize` that are not the newer extended art/variants.

I guess for now we have to make our own logic for each set.
