### ISSUE TITLE
AllSets.json doesn't have the number field for Fifth Edition cards

### ISSUE THREAD

**Issue by bolsheviktory** [mtgjson/mtgjson#525]
As stated, the 5th edition cards don't have the number fields for the cards.
Can these please be added?

**Comment by Psithief** [comment]
Since the source of mtgjson is gatherer.wizards.com, and Gatherer doesn't list the numbers, that information can't be added.

**Comment by bolsheviktory** [comment]
Ok, thanks!
Is there a list of sets which don't have printing numbers for reference?
Scryfall needs them to retrieve card images.

**Comment by SadisticMystic** [comment]
Exodus was the first set that included collector numbers at the bottom of the card.

**Comment by JayDi85** [comment]
@bolsheviktory scryfall have api to get json data for cards -- it's have card number too. And images. You can search card by name or load all cards for set.

**Comment by bolsheviktory** [comment]
Yep, thanks! I'll look into using that or using magiccards.info since that data seems to always be available

**Comment by bolsheviktory** [comment]
I looked through the files, magiccards.info is being scraped for it's data.
Can I request for the scryfall api be called to compile the MTGJSON data so all sets have the proper print numbers?

**Comment by silasary** [comment]
Scryfall's numbers, just like MCI's, are made up and completely arbitrary. Compare [427](https://scryfall.com/card/5ed/427) on scryfall and [447](https://magiccards.info/5e/en/447.html) on MCI.

Neither of them is any less right than the other, and unless WotC makes an updated statement, they officially *do not have collector's numbers*.

Note that when looking into this, I checked the Magic Online versions of these cards, whose Collectors Numbers are marked as `N/A/449`.

There is an open issue to add a 'scryfallNumber` field over in  #412, which will have parity with the preexisting `mciNumber` field.  
But neither of those numbers will ever be added as an official number without a statement from WotC (at which point, the number would come from Gatherer like normal)

**Comment by bolsheviktory** [comment]
Ok, thanks for responding and for the explanation
