### ISSUE TITLE
Wrong name in some Spanish cards

### ISSUE THREAD

**Issue by alfchaval** [mtgjson/mtgjson#527]
I have found in AllPrintings that there are 238 cards that have more than a name in their Spanish version, some of them are translation errors that were printed, but there are others that do not match the printed text.
Unfortunately finding images of old Spanish cards can be difficult, but here is the list of errors I could check.

(Set) English card name | wrong Spanish cardname -> correct Spanish cardname

//Some cards have a character in upper or lower case incorrectly
(JOU) Underworld Coinsmith | Forjamonedas del inframundo -> Forjamonedas del Inframundo
(PS11) Kalonian Behemoth | Behemot Kaloniano -> Behemot kaloniano
(PS11) Sphinx of Jwar Isle | Esfinge de la isla jwar -> Esfinge de la isla Jwar
(PS11) Suntail Hawk | Halcón Colasol -> Halcón colasol

//This one needs an extra character
(C18) Etherium Sculptor | Escultor de eterium -> Escultora de eterium

//Most Invasion and Apocalypse split cards have swapped names
(APC) Fire | Hielo -> Fuego
(APC) Ice | Fuego -> Hielo
(APC) Illusion | Realidad -> Ilusión
(APC) Reality | Ilusión -> Realidad
(APC) Order | Caos -> Orden
(APC) Chaos | Orden -> Caos
(INV) Assault | Violencia -> Asalto
(INV) Battery | Asalto -> Violencia
(INV) Pain | Sufrimiento -> Dolor
(INV) Suffering -> Dolor -> Sufrimiento
(INV) Spite | Malicia -> Despecho
(INV) Malice | Despecho -> Malicia
(INV) Stand | Cumplir -> Enfrentar
(INV) Deliver | Enfrentar -> Cumplir
(INV) Wax | Menguar -> Crecer
(INV) Wane | Crecer -> Menguar

//Some sets have splitcards with untranslated names
(C19) Dusk | Dusk -> Ocaso
(C19) Dawn | Dawn -> Alba
(C19) Refuse | Refuse -> Negarse
(C19) Cooperate | Cooperate -> Cooperar
(C19) Farm | Farm -> Labrar
(C19) Market | Market -> Vender
(CMD) Fire | Fire -> Fuego
(CMD) Ice | Ice -> Hielo
(DDH) Spite | Spite -> Despecho
(DDH) Malice | Malice -> Malicia
(DIS) Supply | Supply -> Oferta
(DIS) Demand | Demand -> Demanda
(PSAL) Supply | Oferta/Demanda -> Oferta
(PSAL) Demand | Demand -> Demanda

**Comment by omfgitsmark** [comment]
I show all the capitalization and spelling correct for the translated names you listed, so I'm wondering where you are seeing that?

The split card names are swapped for those listed cards. I'm looking into how those are getting swapped only for those cards.

The untranslated names are that way on both Gatherer and Scryfall in the text, even though the card images do show the correct translations you provided. We should preferably report it to them and hope they fix it, but if anything we can try to apply a custom fix.

I'll update when I get more information.

EDIT: Oh and the untranslated names are for all languages of those cards, not just spanish

**Comment by omfgitsmark** [comment]
It appears the swapped split card names are also from scryfall.

cc: @csuhta

**Comment by omfgitsmark** [comment]
I was wrong, you are correct about some mispellings/capitilization errors but you have some wrong sets. I'll list them below:

`Etherium Sculptor` is actually missing a letter in PS11 but is correct in C18.

**Comment by ZeldaZach** [comment]
This does appear to be an upstream issue. cc @csuhta

**Comment by ZeldaZach** [comment]
Poke @csuhta

**Comment by csuhta** [comment]
Fixed on Scryfall!
