### ISSUE TITLE
-X loyalty abilities misformatted

### ISSUE THREAD

**Issue by CajunAvenger** [mtgjson/mtgjson#529]
Loyalty costs with numbers are enclosed in brackets ([+1], [-1], [0], etc), but -X loyalty costs are just left as -X. Can be seen on the following cards, appears to affect all printings:

Chandra Nalaar
Tezzeret the Seeker
Ashiok, Nightmare Weaver
Ugin, the Spirit Dragon
Liliana, Heretical Healer//Liliana, Defiant Necromancer
Chandra, Flamecaller
Sorin, Grim Nemesis
Huatli, Warrior Poet
Nahiri, Storm of Stone
Sorin, Vengeful Bloodlord
Chandra, Awakened Inferno
Abian, Luvion Usurper

**Comment by ZeldaZach** [comment]
Thanks for the ticket! Silly mistake on my part :)
