### ISSUE TITLE
Add Variations field for Unstable cards, the (a) versions too

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#531]
This is a followup to https://github.com/mtgjson/mtgjson/issues/503 - the fix seems incomplete: all the cards in unstable that have the "a" variant (so name is the main one) do not have any variation array at all, and that makes impossible determine if the cards has any variation at all (at least without looping through the entire db)

Would it be possible to add the variation array to the main rendition too?

Incidentally I'd suggest to strip the custom (b) (c) suffix from the name altogether, as they interfere with ways to remove them, such as for cards like " B.O.B. (Bevy of Beebles) " - the software needs to know when it's ok to stip the parenthesis and when not, whereas if the name was always the canonical one it would be simpler to make assumptions for anything parsing the card name

**Comment by kodawah** [comment]
example: Secret Base

**Comment by ZeldaZach** [comment]
Fixed in v5, not backporting
