### ISSUE TITLE
UGL: Timmy, Power Gamer -- wrong legendary and types

### ISSUE THREAD

**Issue by JayDi85** [mtgjson/mtgjson#531]
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9786

It must have:
 * Supertype: Legendary
 * Subtypes: Human, Gamer

**Comment by ZeldaZach** [comment]
I am running a full rebuild to fix all issues right now.

**Comment by ZeldaZach** [comment]
Should be fixed with 3.13.1
