### ISSUE TITLE
Keep Name as printed on the card, add a separate VariantName field

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#532]
Expanding on my suggestion in https://github.com/mtgjson/mtgjson/issues/531 - having a custom tag in the card.Name can lead to problems and different expectations. In particular when dealing with non-mtgjson sources, one cannot use equality with that field, as the suffix would negate it, and one should derive the custom tag from the number which is not always available (or more simply one cannot know it beforehand). Using a matching function is not the best since it would introduce many false positives in others sets, and Unstable should not be special cased.

With so many variations in circulation however it is also important to have an easy way to understand what card is what. So my proposal would be to keep the `Name` as the original name of the card, verbatim as printed, without any custom suffix, and add another field like `VariantName` containing anything that could be useful to identify the card.

**Comment by ZeldaZach** [comment]
We decided to go with this approach, using
```
name: Fire // Ice
faceName: Fire
```
