### ISSUE TITLE
bind from invasion missing from AllCards because of bind//liberate

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#533]
It looks like Bind from invasion (https://scryfall.com/card/inv/182/bind) is missing from AllCards, while Bind//Liberate (https://scryfall.com/card/cmb1/88/bind-liberate) is present in its place.

This is the opposite behavior of Smelt // Herd // Saw: that card is rightfully is missing because the card Smelt should be more relevant.

Would it be possible to give priority to cards from expansions when composing AllCards?

**Comment by kodawah** [comment]
the same happens for Liberate https://scryfall.com/card/inv/21/liberate

**Comment by DJCatBlitz** [comment]
see also #480

**Comment by omfgitsmark** [comment]
@ZeldaZach 
will be addressed in v5.
AllCards should not use card names as a key or they overwrite eachother, and can cause other serialization issues.

**Comment by kodawah** [comment]
@omfgitsmark well having a way to figure out if a card existed or not with a simple map lookup was a useful feature, how is this going to be solved?

**Comment by ZeldaZach** [comment]
Card names _will_ be the key, but I'll have to get clever with how I'm handling dupe named cards. I'm probably gonna go with the (b), (c) approach.

**Comment by kodawah** [comment]
> Card names will be the key, but I'll have to get clever with how I'm handling dupe named cards. I'm probably gonna go with the (b), (c) approach.

@ZeldaZach unless you're referring to the (to-be-implemented) VariantName, I don't think that is a good solution. The actual card Name *needs* to be the card as printed, or it risks causing even more confusion than now.

Have you considered using an array for multiple printings? If backward compatibility needs to be respected it could be done in a separate file - AllCards.json (as is now, only one printing) and AllCardsMultiple.json (with map[array] style)

**Comment by ZeldaZach** [comment]
I like the idea! V5 will have compatibility changes, and making each card name an array seems like a solid approach. Would handle the un-cards well too!
