### ISSUE TITLE
add Set.IsNonFoilOnly field

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#534]
Would it be possible to add and `isNonFoilOnly` property to the Set object?
It could be useful when parsing cards and make sure that the foil property is correctly not-set.
It would couple a similar role as `isFoilOnly`.
I tried implementing it on my end but there are too many scattered editions to check

**Comment by ZeldaZach** [comment]
Unfortunately I don't have an easy way of doing this. Might be a good suggestion for upstream.

cc: @csuhta

**Comment by csuhta** [comment]
We just added this upstream, as `nonfoil_only`!

(Also we now fully-automate both fields so they should always match data)

https://scryfall.com/docs/api/sets

**Comment by kodawah** [comment]
this is sweet, thanks @csuhta !
