### ISSUE TITLE
UGL: Paper Tiger, Rock Lobster, Scissors Lizard - wrong types

### ISSUE THREAD

**Issue by JayDi85** [mtgjson/mtgjson#535]
[Paper Tiger](https://scryfall.com/card/ugl/78) must be **Cat**
[Rock Lobster](https://scryfall.com/card/ugl/79) must be **Lobster**
[Scissors Lizard](https://scryfall.com/card/ugl/80) must be **Lizard**

**Comment by ZeldaZach** [comment]
Dupe #531
