### ISSUE TITLE
Flip/transform legends with incorrect leadershipSkills

### ISSUE THREAD

**Issue by vhaso** [mtgjson/mtgjson#536]
#### Description of Bug:

The AllCards.json has a field leadershipSkills which indicates wether a card can be your Brawl, EDH or Oathbreaker commander. A number of legendary creatures that are flipped/transformed sides of artifacts, lands and (non-)legendary creatures have a label leadershipSkills['commander'] that is true. Under common rules for Commander these creatures are not legal commanders.

The following legendary creatures are mislabeled:

Autumn-Tail, Kitsune Sage
Avacyn, the Purifier
Azamuki, Treachery Incarnate
Brisela, Voice of Nightmares
Dokai, Weaver of Life
Goka the Unjust
Hanweir, the Writhing Township
Ichiga, Who Topples Oaks
Jaraku the Interloper
Kaiso, Memory of Loyalty
Kenzo the Hardhearted
Nighteyes the Desecrator
Ormendahl, Profane Prince
Scarmaker
Shidako, Broodmistress
Stabwhisker the Odious
Tobita, Master of Winds
Tok-Tok, Volcano Born
Tomoya the Revealer
Ulrich, Uncontested Alpha
Withengar Unbound

What follows is a Python script that compares the cards Scryfall API lists as legal commanders with the cards labeled as commanders in AllCards.json (as of writing it prints the list shown above):
```python
import json
import requests

# Load commanders from scryfall api, this list excludes banned commanders and
# the not:funny filter excludes silver-bordered commanders
url = 'https://api.scryfall.com/cards/search?q=is:commander+not:funny'
response_sf = requests.get(url)
page_sf = json.loads(response_sf.content)
cmds_sf = [cmd['name'].split(' // ')[0] for cmd in page_sf['data']]

while page_sf['has_more']:
    url = page_sf['next_page']
    response_sf = requests.get(url)
    page_sf = json.loads(response_sf.content)
    for cmd in page_sf['data']:
        cmds_sf.append(cmd['name'].split(' // ')[0])

# Load AllCards.json
with open('AllCards.json', 'r', encoding='utf8') as f_json:
    cards_json = json.load(f_json) #keys are cardnames

# look for cards with 'commander': True in leadershipSkills and
# 'commander': 'Legal' in legalities 
cmds_json=[]
for cardname in cards_json:
    info = cards_json[cardname]
    is_commander = 'leadershipSkills' in info and\
        info['leadershipSkills']['commander']
    is_legal = 'commander' in info['legalities'] and\
        info['legalities']['commander'] == 'Legal'
    if is_commander and is_legal:
        cmds_json.append(cardname)

# Compare both lists
cmds_wrong = [cmd for cmd in cmds_json if cmd not in cmds_sf]
for cmd in cmds_wrong:
    print(cmd)
```

**Comment by ZeldaZach** [comment]
Thanks for catching this! Working on a fix for v5 :)

**Comment by ZeldaZach** [comment]
Fixed in v5 (to be published soon).
