### ISSUE TITLE
Set: "block" and "onlineOnly" gone?

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson#54]
Looking at https://mtgjson.com/v4/docs.html I can't find them anymore, also no mention in https://mtgjson.com/v4/changelog.html.

**Comment by ZeldaZach** [comment]
Both block and onlineOnly are still valid fields... Looks like we missed them in documentation. Re-issue at the website github

**Comment by tooomm** [comment]
I didn't compare all documentation, these came up to me because I looked for them in particular. (they would be helpful properties to filter/search the set page for example)

Somebody else should double check the documentation as well. It is very important to have all information listed there.
