### ISSUE TITLE
planeshift cards with foil-only counterparts also have normal foils

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#540]
the three planeshift special cards
* "Skyship Weatherlight" ("1ccd68e3-9293-5c59-ac45-28a8b330da16")
* "Ertai, the Corrupted" ("fddac3e2-62f2-5cba-9efa-72f996b4fd10")
* "Tahngarth, Talruum Hero" ("8fc138f9-046e-53b8-bbc3-70c899e09d86")
that *do not* have the special tag (start) to their number have `hasFoil` incorrectly set to false.

The normal variant of these card have a foil printing: see for example https://shop.tcgplayer.com/magic/planeshift/tahngarth-talruum-hero?id=7893l

**Comment by kodawah** [comment]
(maybe upstream issue, cc: @csuhta)

**Comment by kodawah** [comment]
i noticed the same is true for Tenth Edition foil-only booster cards too, but I'm not too sure.
I believe 10th edition have nonfoil, foil and superfoil, but the links in scryfall point to the same page 

https://scryfall.com/card/10e/244%E2%98%85/uncontrollable-anger and https://scryfall.com/card/10e/244/uncontrollable-anger both point to https://shop.tcgplayer.com/magic/10th-edition/uncontrollable-anger?id=15377&partner=Scryfall

**Comment by csuhta** [comment]
We've correct the Planeshift foils on Scryfall. 

For 10th edition, I do not believe there are regular foils. All foils have the alternate reminder text and typography, according to this article https://magic.wizards.com/en/articles/archive/premium-foils-tenth-edition-2007-07-12

**Comment by kodawah** [comment]
Thanks! I didn't know about 10E, and was surprised that they got the (*) specifier.
