### ISSUE TITLE
buildSet fails on pages where Gatherer has server errors past 11 pages

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgjson#541]
buildSet fails for basic land cards that would spill over to more than 11 pages.

Here’s an example:
http://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=8329

If you try to go to page 12, or the last page (like clicking on `>>`), this is the link:
http://gatherer.wizards.com/Pages/Card/Printings.aspx?page=12&multiverseid=8329

Which gets redirected to a general server error page:
http://gatherer.wizards.com/Pages/Error.aspx?aspxerrorpath=/Pages/Card/Printings.aspx

As a workaround, making a change in `rix.js`, inserting a simple statement after line 724 to cap numPages to 11 does the trick (however, I’m sure there may be a more elegant solution):
`            if (numPages > 11) numPages = 11;`

**Comment by ZeldaZach** [comment]
I'm using this fix right now to get a full-rebuild up.

**Comment by ancestral** [comment]
Looks like Wizards fixed this bug on their end. Yay!

**Comment by fenhl** [comment]
Good to hear. If anyone else is still seeing this bug, just drop a comment and we'll reopen.
