### ISSUE TITLE
DOM frameEffect mostly disappeared

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#541]
#### MTGJSON Version: 4.X.X

https://mtgjson.com/json/DOM.json

#### Description of Bug:

In latest update, only 10 cards have frameEffect legendary. There should be 59 of them.
It was correct previous week.

**Comment by ZeldaZach** [comment]
I just rebuilt it using v4 and v5, without seeing this strange bug. Gonna close for now, but if you see it again in next week's build on Monday night let us know
