### ISSUE TITLE
whirling dervish tcgplayerProductId error

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#542]
hi,
i believe whirling dervish (d546d705-189d-5662-98e0-9baaa9aab670) has a wrong `tcgplayerProductId`: currently 38229 points to the Junior Euro Series, while the `number` (2U07) makes the card belong to the Junior APAC Series (which is missing from TCG entirely)

**Comment by kodawah** [comment]
the euro version of the card (a8aec7b9-179e-5db6-a5da-9bf04bb9610a) correctly points to the correct tcg edition fwiw

**Comment by ZeldaZach** [comment]
Nice spotting! Appears to be upstream

cc: @csuhta

**Comment by csuhta** [comment]
Hey there, could you please provide Scryfall IDs and what their product ID should be? I'm not sure which versions you are talking about (we don't have a card with UUID d546d705-189d-5662-98e0-9baaa9aab670)

**Comment by ZeldaZach** [comment]
Referring to https://api.scryfall.com/cards/cd0aef6e-39ba-4231-9d53-2619930f52b4?format=json&pretty=true and https://api.scryfall.com/cards/3a24a043-b8e4-42de-bfa4-e7e8bb9c473a?format=json&pretty=true

@csuhta

**Comment by kodawah** [comment]
please note that this seems recurring with the Junior APAC series, Sakura-Tribe Elder (https://scryfall.com/card/pjas/1U06/sakura-tribe-elder) is affected as well and soltari priest too.
Since the edition is not on TCG it should be possible to just exclude the cards from this set to be extra ssafe https://scryfall.com/sets/pjas

**Comment by csuhta** [comment]
I'm having trouble reconciling this because TCGplayer has the cards in two sets, while we have 4 Junior sets, and also their images are very low-resolution so I cannot check collector numbers.

If you're sure what needs to be changed, could you please provide a list or CSV for me with the corrections? Ideally mapping the Scryfall ID → TCGplayer ID (or empty if it needs to be unset)

**Comment by ZeldaZach** [comment]
If you'd like this addressed further @kodabb please contact Scryfall directly.

**Comment by kodawah** [comment]
i've completed my research, i'll forward it to scryfall and leave a copy here for posterity 

Sakura-Tribe Elder
 - PJAS: unset tcgproductid
 - PJJT: unset tcgproductid
 - PJSE: no change
 - PSUS: unset tcgproductid

Serra Avatar
 - PSUS: no change

Shard Phoenix
 - PJAS: unset tcgproductid
 - PJJT: unset tcgproductid
 - PJSE: no change
 - PSUS: unset tcgproductid

Lord of Atlantis
 - PSUS: no change

Volcanic Hammer
 - PJJT: unset tcgproductid
 - PSUS: no change

Thran Quarry
 - PSUS: no change

Elvish Lyrist
 - PSUS: no change

Two-Headed Dragon
 - PJJT: unset tcgproductid
 - PSUS: no change

City of Brass
 - PSUS: no change

Glorious Anthem
 - PJAS: no change
 - PJJT: no change
 - PJSE: no change
 - PSUS: no change

Elvish Champion
 - PJAS: replace to 192935
 - PJJT: unset tcgproductid
 - PJSE: no change
 - PSUS: replace to 192936

Slith Firewalker
 - PJAS: replace to 214586
 - PJSE: replace to 38224
 - PSUS: no change

Soltari Priest
 - PJAS: no change
 - PJJT: replace to 214574
 - PJSE: no change
 - PSUS: no change

Royal Assassin
 - PJJT: unset tcgproductid
 - PJSE: no change
 - PSUS: unset tcgproductid

Mad Auntie
 - PJJT: no change
 - PSUS: no change

Crusade
 - PSUS: no change

Whirling Dervish
 - PJAS: unset tcgproductid
 - PJJT: no change
 - PJSE: no change
 - PSUS: unset tcgproductid

Wild Growth
 - PJJT: no change
 - PSUS: no change

**Comment by csuhta** [comment]
Updated on Scryfall
