### ISSUE TITLE
Who // What // When // Where // Why

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgjson#543]
It appears Wizards changed the name on the card in Gatherer.

So the set_configs file needs to get updated. Change all instances of `Who/What/When/Where/Why` to `Who // What // When // Where // Why`.

**Comment by tooomm** [comment]
Correct, it got changed: http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74358

**Comment by ZeldaZach** [comment]
Handled correctly in v4
