### ISSUE TITLE
C20 release date

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#544]
https://www.mtgjson.com/json/C20.json

It is incorrectly listed as  "releaseDate": "2020-04-24".

[That was the original release date, but it changed to  "releaseDate": "2020-04-17".](https://mtg.gamepedia.com/Commander_2020)

**Comment by ZeldaZach** [comment]
Upstream issue

cc: @csuhta

**Comment by csuhta** [comment]
Changed on Scryfall (also IKO too)
