### ISSUE TITLE
Version??  Version 3.13.1 has no version info either in version.json nor version-full.json

### ISSUE THREAD

**Issue by gopat** [mtgjson/mtgjson#545]
Description
=======
Version 3.13.1 (currently published version) has no version info either in `version.json` nor `version-full.json`, `version.json` just contains `undefined` wich is invalid as a JSON value (and unsurprisingly chokes several parsers).

Steps to reproduce
======
Using `wget` (in a posix-like enviroment), and as of now (2018-01-22T14:30:00Z):
```
wget -O - -q 'http://mtgjson.com/json.version.json' ; echo;
wget -O - -q 'http://mtgjson.com/json.version-full.json' ; echo;
```
...results in:
```
undefined
{}
```
But should return:
```
"3.13.1"
{
  "version":"3.13.1"
}
```

**Comment by gopat** [comment]
Some screenshots:

![version json_1](https://user-images.githubusercontent.com/10393246/35226978-1a71fd0a-ff8d-11e7-94f8-6028d7b093cf.png)

![version json_2](https://user-images.githubusercontent.com/10393246/35226990-22cc3a06-ff8d-11e7-9801-f1a3acf31e0b.png)

![version json_3](https://user-images.githubusercontent.com/10393246/35226999-255fa19a-ff8d-11e7-9097-3efdcefcd431.png)

Firefox Developer Edition 59.0b2 on Windows 10
As the shots include UI in Spanish, and for those who don't speak Cervantes' tongue:
 - `Datos sin procesar`: `Raw data`
 - `Cabeceras`: `Headers`
 - `Guardar`: `Save`
 - `Copiar`: `Copy`
 - `Cabeceras de la respuesta`: `Response Headers`
 - `Cabeceras de la petición`: `Request Headers`

**Comment by ZeldaZach** [comment]
Fixed. Misspelt "version" in the changelog

**Comment by gopat** [comment]
@ZeldaZach Thank you!
