### ISSUE TITLE
C20 foils

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#545]
https://www.mtgjson.com/json/C20.json

There are 210 cards with `"hasFoil": true`. That's mostly wrong.

Actually there are only 4 foil cards per deck, so 20 total. Feel free to double check, but the correct list seems to be only these cards (commander, alt commander, and 2 partners for each deck) :

* Akim, the Soaring Wind
* Brallin, Skyshark Rider
* Cazur, Ruthless Stalker
* Gavi, Nest Warden
* Haldan, Avid Arcanist
* Jirina Kudro
* Kalamax, the Stormsire
* Kathril, Aspect Warper
* Kelsien, the Plague
* Nikara, Lair Scavenger
* Otrimi, the Ever-Playful
* Pako, Arcane Retriever
* Shabraz, the Skyshark
* Silvar, Devourer of the Free
* Tayam, Luminous Enigma
* Trynn, Champion of Freedom
* Ukkima, Stalking Shadow
* Xyris, the Writhing Storm
* Yannik, Scavenging Sentinel
* Zaxara, the Exemplary

**Comment by ZeldaZach** [comment]
Took a look, and this appears to be an upstream issue

cc: @csuhta

**Comment by csuhta** [comment]
Fixed on Scryfall
