### ISSUE TITLE
IKO release missed

### ISSUE THREAD

**Issue by carlol** [mtgjson/mtgjson#546]
#### MTGJSON Version: 4.X.X

Hi, probably I'm missing something but I don't know where to find the latest release (IKO). I see in the GitHub repo home the 3.6.3 badge but I don't find it.

Could you help me?

Best regards

**Comment by staghouse** [comment]
You can find it near the top of the sets downloads list here:

https://mtgjson.com/downloads/all-sets/

Directly from the individual set source here:

https://www.mtgjson.com/json/IKO.json

Or you can find it with all the other printings in AllPrintings which you can find here:

https://mtgjson.com/downloads/all-files/
