### ISSUE TITLE
Artifact in CardTypes missing "Gold" subtype

### ISSUE THREAD

**Issue by jroed** [mtgjson/mtgjson#547]
#### MTGJSON Version: 4.6.3+20200422

CardTypes.json

#### Description of Bug:

Artifact in CardTypes.json is missing `Gold` subtype.

**Comment by ZeldaZach** [comment]
Seems to be missing upstream in the artifact catalog

cc: @csuhta

**Comment by csuhta** [comment]
Fixed on Scryfall
