### ISSUE TITLE
Rename/Alter "AttributeValues"

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgjson#548]
#### MTGJSON Version: 5.0.0

**Rename:** The new AttributeValues file should be named back to its original "KeyValues" name as it is more precise.

**Alter:** The following data points need to be adjusted:

card =>
- remove types
- remove subtypes
- remove supertypes
- remove foreignData

set =>
- remove code
- add type

add foreignData (top level) =>
- add language

**Comment by ZeldaZach** [comment]
Addressed
