### ISSUE TITLE
Various pricing data issues

### ISSUE THREAD

**Issue by zovt** [mtgjson/mtgjson#549]
#### Description of Bug:
Some pricing data appears to be missing for a bunch of cards in a variety of ways. For example, Abomination (16376f75-9dcb-583b-9094-161ead43dd82) and Zuran Orb (224263a4-f3a6-5587-b39f-834735133ffa) are completely missing any historical data, and Abduction (595a775a-7bef-5ffb-a4f8-bb35257b1e9d) and Absolute Law (9bffc560-c719-5c23-841f-b6b5e30c2fa6) are missing data since February. 

They seem to be older cards for the most part, but Scryfall does have pricing data for them and I'm fairly sure they grab data from TCGPlayer as well.

Let me know if you need any more information.

**Comment by zovt** [comment]
`Thalia, Guardian of Thraben` (c5b37a65-d68d-5ff8-9d25-c9e500ee7ea3) seems to be completely missing data as well as an example of a newer card missing data

**Comment by ZeldaZach** [comment]
Hey @zovt Thanks for the report! Having oversight on my work is always appreciated.

I went through each and every card you reported on this ticket. From my investigation, it appears that TCGPlayer no longer has any copies of these specific printings available, which leads them not to report back data. As such, the system is working as expected.

If you come across listings for these cards, do let me know!!
