### ISSUE TITLE
[Enhancement] Last modified on sets

### ISSUE THREAD

**Issue by oniice** [mtgjson/mtgjson#549]
Could we get a last modified on set data, to signify there has been a change?
Would be very useful for stuff that is consuming the data and updates/fixes are done to the JSON.

**Comment by oniice** [comment]
Just found https://mtgjson.com/json/changelog.json 
Has useful meta data for seeing files changes, still would be nice for the timestamp on each set data file

**Comment by tooomm** [comment]
At best, such information would be automatically included into the single files on every update. The changelog is edited manually and often the "changed files" info is left out or incomplete...

**Comment by ZeldaZach** [comment]
Sorry about the issues with the changelog.. .It's hard with full rebuilds. I recommend you read the `git pull` logs when you re-up and can determine from that
