### ISSUE TITLE
Create version.json for MTGJSONv4

### ISSUE THREAD

**Issue by RDWonline** [mtgjson/mtgjson#55]
Please create and maintain a version.json file for MTGJSONv4.  It will allow for applications to programmatically determine the version on the server.  Thanks in advance.

**Comment by ZeldaZach** [comment]
I’m thinking about it, but our files now have a `meta` tag that includes version and date. Is that not good enough?

**Comment by RDWonline** [comment]
I think it would be a lot more efficient for the version number to be in a separate 100 byte file rather than having to pull down the JSON file, loading it all into memory and THEN doing the comparison.  By then, I may have needlessly consumed ~190MB of bandwidth for nothing.

**Comment by jmcsmith** [comment]
I agree this file would be helpful as it would allow checking for updates without checking every set file. changelog.json is also helpful if the update, new and removed set lists are kept uniform and machine readable.

**Comment by ZeldaZach** [comment]
Hmm, so how about a single file, that includes current version, affected sets, and release date?

**Comment by RDWonline** [comment]
If your object will allow me to check the version number of a specific file, then yes, this could work.

**Comment by ZeldaZach** [comment]
Sorry for not checking up with you guys, but I made a format that will be added in 4.0.1 (tonight-ish)
```json
{
	"4.0.0": {
		"date": "2018-10-13",
		"filesModified": ["a", "b", "c"]
	}
}
```

New versions will be added to the top of the dictionary.

**Comment by ZeldaZach** [comment]
Added in 4.0.1
Will have a push to code later, but i did it manually for right now as we were making some changes

**Comment by tooomm** [comment]
Hmm, this sounds like a blend between a very tiny file which only contains the version of the most current download/output, and a history of changed files (not really a changelog either)

Wouldn't it be better to have
- `currentVersion` for e.g. simple update checks and to determine further actions
- `updatedFiles` or `changedFiles`...
- and a proper `changelog`

all in separate json files to serve different needs?

I can see the last two beeing combined, or currentVersion holding the other information as well, but only the most recent and not all history etc.pp.
That would depend on what is most needed and useful, and should be discussed.

**Comment by ZeldaZach** [comment]
I don't plan on making a formal JSON changelog as it's not really helpful. The changelog on the website is probably good enough.

Version will still be a relatively small file, compared to everything else. Maybe i can make a current or smth that only has the first entry from version.json not sure

**Comment by jceddy** [comment]
I used the old changelog.json pretty heavily...sad to see it gone.
