### ISSUE TITLE
Document program parameters as in the README

### ISSUE THREAD

**Issue by allentiak** [mtgjson/mtgjson#551]
#### MTGJSON Version: 4.X.X

master (ef7b551)

#### Description of Bug:

The repo README explains how to use the program. But the program itself does not show that info in any visible way...

- Once installed, if I invoke the program without parameters, it gives no useful info: the user has to infer what each parameter does...

```
% python3 -m mtgjson4   
usage: __main__.py [-h] [-a] [-c] [-x] [-z] [-s [SET [SET ...]]] [--skip-keys]
                   [--skip-sets [SET [SET ...]]] [--skip-cache] [-p]
                   [--pricing]

```

- Once installed, inferring `-h` as the "help" option, I if I invoke the program with it, it gives not much useful info, only the one pertaining itself: the user has to infer what each other parameter does...

```
% python3 -m mtgjson4 -h
usage: __main__.py [-h] [-a] [-c] [-x] [-z] [-s [SET [SET ...]]] [--skip-keys]
                   [--skip-sets [SET [SET ...]]] [--skip-cache] [-p]
                   [--pricing]

optional arguments:
  -h, --help            show this help message and exit
  -a
  -c
  -x
  -z
  -s [SET [SET ...]]
  --skip-keys
  --skip-sets [SET [SET ...]]
  --skip-cache
  -p, --pretty-output
  --pricing
```

**Comment by ZeldaZach** [comment]
Ya know, I thought I did this at some point in history, but it appears I forgot. Addressed :)

**Comment by allentiak** [comment]
Thanks, @ZeldaZach!
