### ISSUE TITLE
sprite dragon (369) is missing frameeffects = inverted

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#552]
This card ("d1a83411-2f0d-5e07-8af6-ae8a34c7c0a1") seems to have a missing frameEffect property

**Comment by ZeldaZach** [comment]
Good catch! Links back to SF UUID 7172db88-2208-47c4-8226-bc094fd04a9b

cc: @csuhta

**Comment by csuhta** [comment]
Fixed on Scryfall
