### ISSUE TITLE
Wrong mkm_name for Rivals of Ixalan

### ISSUE THREAD

**Issue by paithan** [mtgjson/mtgjson#554]
I noticed that the mkm_name field for Rivals of Ixalan has changed to "Ixalan".  (It used to be "Rivals of Ixalan".)  I don't think the change is intended.

**Comment by tooomm** [comment]
Looking at the [blame](https://github.com/mtgjson/mtgjson/blame/master/json/RIX.json) it got introduced in a huge rebuild (https://github.com/mtgjson/mtgjson/pull/542)
