### ISSUE TITLE
Arenaid is missing - ArendId : 69450

### ISSUE THREAD

**Issue by giniman** [mtgjson/mtgjson#557]
#### MTGJSON Version: 4.X.X
I am coding some decklist maker for Arena but this Id code is missing.

**Comment by ZeldaZach** [comment]
I'm gonna need more information on where this is missing from. What card in what set should it go to?

**Comment by giniman** [comment]
I'll collect more data from MTGA using some self-made tools and report to you. Thanks.

**Comment by ZeldaZach** [comment]
This ID seems to be defined now. Upstream had some issues.
