### ISSUE TITLE
Fallen Empires (FEM) has incorrect "booster" value

### ISSUE THREAD

**Issue by magreenblatt** [mtgjson/mtgjson#558]
At v3.14 Fallen Empires has the following "booster" value:

```
  "booster": [
    "uncommon", 
    "uncommon", 
    "common", 
    "common", 
    "common", 
    "common", 
    "common", 
    "common"
  ], 
```

However, this set contains "Rare" cards. I have no evidence but perhaps it should be something closer to Homelands (HML):

```
  "booster": [
    [
      "rare", 
      "uncommon"
    ], 
    [
      "rare", 
      "uncommon"
    ], 
    "common", 
    "common", 
    "common", 
    "common", 
    "common", 
    "common"
  ], 
```
It would also be interesting if anyone has information on odds for "rare" vs "uncommon" in these sets.

**Comment by magreenblatt** [comment]
Also a problem with The Dark (DRK), Antiquities (ATQ) and Arabian Nights (ARN)

**Comment by ZeldaZach** [comment]
If you'd like to submit a PR I'd appreciate it! :)
