### ISSUE TITLE
'is' and 'has' property names

### ISSUE THREAD

**Issue by jroed** [mtgjson/mtgjson#558]
There are several properties that have an 'is' or 'has' prefix. For example `hasFoil` is true or false if the card can be found in foil or not.

It seems that these properties prefixes are not coherently used in some cases. Therefore I would like to propose the following definitions:
1. A property has an 'is' prefix if the property is associated with **THIS variant** of the card.
2. A property has a 'has' prefix if the property is associated with **ALL variants** of the card (such that the property is true if there is at least one variant with this property among all variants of the card).

Example: If a card is oversized the property `isOversized` is `true` but this doesn't make a claim about other variants of the card. Whereas if a card has a variant in foil the property `hasFoil` is `true` which is a claim about all variants of the card (including the card itself).

If we want to adhere to the above mentioned definitions some property prefixes would need to be adapted.
- `isAlternative` renamed to `hasAlternative` (Does this card have an alternative variant to its printed counterpart?)
- `isArena` renamed to `hasArena` (Does this card have a variant in Magic: The Gathering Arena?)
- `isMtgo` renamed to `hasMtgo` (Does this card have a variant in Magic: The Gathering Online?)
- `isPaper` renamed to `hasPaper` (Does this card have a variant in print?)
- `isReprint` renamed to `hasReprint` (Does this card have a variant that is a reprint?)

**Comment by ZeldaZach** [comment]
I'm very confused with the request, as the examples you posted are exactly the opposite of what I'd expect.

As one example, isAlternative defines _this_ printing of the card is an alternative. Adding misc keys, like hasAlternative to other printings of the card feel wasteful imo.

I spoke with the full dev team and we all agree it's a bit of an overkill, however we'll do a better job on our documentation to indicate to look for certain components.

If you'd like to discuss this idea further, hit us up on Discord sometime https://mtgjson.com/discord 

In any case, thanks for trying to help improve MTGJSON! I hope to see more tickets in the future
