### ISSUE TITLE
Time Spiral "Timeshifted" (TSB) contains a "booster" but all cards are "Special"

### ISSUE THREAD

**Issue by magreenblatt** [mtgjson/mtgjson#559]
At v3.14 the Time Spiral (TSB) set contains a "booster" value with various rarities but all cards are listed as "rarity": "Special".

```
  "booster": [
    "rare", 
    "uncommon", 
    "uncommon", 
    "uncommon", 
    "common", 
    "common", 
    "common", 
    "common", 
    "common", 
    "common", 
    "common", 
    "common", 
    "common", 
    "common", 
    "timeshifted purple"
  ], 
```
According to https://mtg.gamepedia.com/Timeshifted the TSB cards would appear in the "timeshifted purple" slot of the Time Spiral (TSP) booster pack. TSB and TSP both contain the same "booster" value. Perhaps TSB should be treated more like a "Masterpiece Series" set and the "booster" record should be removed (leaving it in TSP only).

**Comment by ZeldaZach** [comment]
Not a relevant issue at this time, until we can figure out the booster. This has been inc'd on the booster discussion
