### ISSUE TITLE
Missing mcmID's for Mystery Booster and Tempest

### ISSUE THREAD

**Issue by splatterb0y** [mtgjson/mtgjson#559]
#### Description of Bug:
Sets "Mystery Booster" (MB1) and "Tempest" (TMP) are both missing mcmId's and purchaseUrls for CardMarket. Is there some way to fix this?

**Comment by ZeldaZach** [comment]
Heh, I found some issues within the building scripts. Thanks for reporting! I'll have it fixed on v5, with a possible backport to v4.
