### ISSUE TITLE
Include TCGPlayer API ProductID in card info

### ISSUE THREAD

**Issue by jmcsmith** [mtgjson/mtgjson#56]
Integrate the TCGPlayer API to have TCGProductID as a field on each card.
Category ID is always 1 for Magic
Each MTG set would have a group in category 1. For example Battlebond is group 2245
Each card then has a productid. For example Spire Garden is id 166659
Card data also contains an image link [(https://6d4be195623157e28848-7697ece4918e0a73861de0eb37d08968.ssl.cf1.rackcdn.com/166659_200w.jpg](https://6d4be195623157e28848-7697ece4918e0a73861de0eb37d08968.ssl.cf1.rackcdn.com/166659_200w.jpg)
Inclusion of this data would allow developers using MTGJson to get TCG prices and link more easily.

**Comment by ZeldaZach** [comment]
I recently got a TCGPlayer API key for the project, so I'll consider looking into this in the future :)
