### ISSUE TITLE
Keywords.json is Broken:  Returns Rules Text Instead of Keyword Abilities

### ISSUE THREAD

**Issue by johnathanbostrom** [mtgjson/mtgjson#561]
#### MTGJSON Version: 4.X.X
4.6.3+20200505
#### Description of Bug:
https://www.mtgjson.com/files/Keywords.json  
It looks like whatever scraper/parser you are using to automatically get the text for keyword abilities is broken.  Instead of a list of keywords, keywordAbilities contains rules text starting from 702.2a and ending with 702.139f.  KeywordActions has a similar problem.

**Comment by ZeldaZach** [comment]
I've uploaded a new Keywords.json, but for the compressed versions just wait until Monday's rebuild :) 

Thanks for the ticket, much appreciated!!
