### ISSUE TITLE
Unsanctioned lands have the same tcgplayerid per land type

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#563]
Both https://scryfall.com/card/und/95/forest and https://scryfall.com/card/und/96/forest point to the same product page https://shop.tcgplayer.com/magic/unsanctioned/forest?id=208389&partner=Scryfall. The same is true for all the basic lands.

The tcgplayer id should be

Forest
        208379, (full)
        208389

Island
        208383, (full)
        208453

Mountain
        208382, (full)
        208391

Swamp
        208384, (full)
        208454

Plains
        208386, (full)
        208392

**Comment by ZeldaZach** [comment]
Interesting catch. Looks to be a slight oversight.

cc: @csuhta

**Comment by csuhta** [comment]
Fixed on Scryfall
