### ISSUE TITLE
missing double-sided tokens

### ISSUE THREAD

**Issue by GaryTheHutt** [mtgjson/mtgjson#564]
There was a mixture of normal and double-sided tokens in Modern Horizons booster packs. The more common non-foil tokens are all double sided (76 combinations) and the normal layouts are all foil (except there are no single sided foil emblems). The double sided versions missing from the data are:

Shapeshifter / Angel
Shapeshifter / Bear
Shapeshifter / Elephant
Shapeshifter / Rhino
Shapeshifter / Squirrel
Shapeshifter / Construct
Shapeshifter / Golem
Shapeshifter / Wrenn and Six Emblem
Angel / Bird
Angel / Soldier
Angel / Illusion
Angel / Zombie
Angel / Elemental mtgjson/mtgjson-website#8
Angel / Goblin
Bird / Elemental mtgjson/mtgjson-website#9
Bird / Bear
Bird / Elephant
Bird / Spider
Bird / Squirrel
Bird / Construct
Bird / Myr
Bird / Serra the Benevolent Emblem
Soldier / Marit Lage
Soldier / Elemental mtgjson/mtgjson-website#9
Soldier / Elephant
Soldier / Rhino
Soldier / Spider
Soldier / Squirrel
Soldier / Construct
Soldier / Golem
Soldier / Myr
Soldier / Serra the Benevolent Emblem
Soldier / Wrenn and Six Emblem
Illusion / Marit Lage
Illusion / Elemental mtgjson/mtgjson-website#9
Illusion / Elephant
Illusion / Rhino
Illusion / Spider
Illusion / Squirrel
Illusion / Construct
Illusion / Golem
Illusion / Myr
Illusion / Serra the Benevolent Emblem
Illusion / Wrenn and Six Emblem
Marit Lage / Elemental mtgjson/mtgjson-website#8
Marit Lage / Goblin
Marit Lage / Spirit
Zombie / Bear
Zombie / Elephant
Zombie Rhino
Zombie / Spider
Zombie / Squirrel
Zombie / Construct
Zombie / Serra the Benevolent Emblem
Zombie / Wrenn and Six Emblem
Elemental mtgjson/mtgjson-website#8 / Bear
Elemental mtgjson/mtgjson-website#8 / Elephant
Elemental mtgjson/mtgjson-website#8 / Rhino
Elemental mtgjson/mtgjson-website#8 / Spider
Elemental mtgjson/mtgjson-website#8 / Squirrel
Elemental mtgjson/mtgjson-website#8 / Construct
Elemental mtgjson/mtgjson-website#8 / Golem
Elemental mtgjson/mtgjson-website#8 / Myr
Goblin / Bear
Goblin / Elephant
Goblin / Rhino
Goblin / Spider
Goblin / Squirrel
Goblin / Construct
Goblin / Golem
Goblin / Myr
Goblin / Serra the Benevolent Emblem
Goblin / Wrenn and Six Emblem
Elephant / Spirit
Rhino / Spirit
Spirit / Myr

**Comment by GaryTheHutt** [comment]
Throne of Eldraine draft packs include normal layout non-foil tokens, but collector packs included double-sided foil tokens. The latter are all missing from the data. 56 combinations:

Goat / Food #15
Goat / Food #16
Goat / Food #17
Goat / Food #18
Human / Food #15
Human / Food #16
Human / Food #17
Human / Food #18
Knight / Food #15
Knight / Food #16
Knight / Food #17
Knight / Food #18
Mouse / Food #15
Mouse / Food #16
Mouse / Food #17
Mouse / Food #18
Faerie / Food #15
Faerie / Food #16
Faerie / Food #17
Faerie / Food #18
Rat / Food #15
Rat / Food #16
Rat / Food #17
Rat / Food #18
Dwarf / Food #15
Dwarf / Food #16
Dwarf / Food #17
Dwarf / Food #18
Bear / Food #15
Bear / Food #16
Bear / Food #17
Bear / Food #18
Boar / Food #15
Boar / Food #16
Boar / Food #17
Boar / Food #18
Giant / Food #15
Giant / Food #16
Giant / Food #17
Giant / Food #18
Human Cleric / Food #15
Human Cleric / Food #16
Human Cleric / Food #17
Human Cleric / Food #18
Human Rogue / Food #15
Human Rogue / Food #16
Human Rogue / Food #17
Human Rogue / Food #18
Human Warrior / Food #15
Human Warrior / Food #16
Human Warrior / Food #17
Human Warrior / Food #18
Wolf / Food #15
Wolf / Food #16
Wolf / Food #17
Wolf / Food #18

**Comment by GaryTheHutt** [comment]
Theros: Beyond Death (THB) draft packs include normal layout non-foil tokens, but collector packs included double-sided foil tokens. The latter are all missing from the data. 24 combinations:

Goat / Human Soldier
Goat / Satyr
Human Soldier / Pegasus
Human Soldier / Kraken
Human Soldier / Reflection
Human Soldier / Tentacle
Human Soldier / Zombie
Human Soldier / Elemental
Human Soldier / Spider
Human Soldier / Wolf
Human Soldier / Nightmare
Human Soldier / Gold
Human Soldier / Wall
Pegasus / Satyr
Kraken / Satyr
Reflection / Satyr
Tentacle / Satyr
Zombie / Satyr
Elemental / Satyr
Satyr / Spider
Satyr / Wolf
Satyr / Nightmare
Satyr / Gold
Satyr / Wall

**Comment by ZeldaZach** [comment]
Dupe #565
