### ISSUE TITLE
token layout errors

### ISSUE THREAD

**Issue by GaryTheHutt** [mtgjson/mtgjson#565]
There are 8 double-sided token combinations in the Ravnica Alliance Guild Kit. They are listed as normal layout in the data:

Bird / Sphinx
Bird / Thopter
Spirit mtgjson/mtgjson-website#1 / Spirit mtgjson/mtgjson-website#10
Bat / Spirit mtgjson/mtgjson-website#10
Cleric / Treasure
Dragon / Goblin

**Comment by GaryTheHutt** [comment]
It seemed more workable to submit each ticket within the context of the set I was seeing the problem since the errors are not consistent across sets. However, if that's your preference I will just add comments regarding each instance I see the same error.

**Comment by GaryTheHutt** [comment]
Same error in C19 set. All tokens are double sided; 21 combinations:

Bird #1 / Sculpture
Bird #2 / Sculpture
Human / Pegasus
Human / Spirit
Human / Drake
Human / Treasure
Angel of Sanctions / Horror
Heart-Piercer Manticore / Dragon
Assassin / Morph
Zombie #10 / Zombie #11
Zombie #10 / Ob Nixilis Reignited Emblem
Beast #13 / Wurm
Beast #14 / Wurm
Centaur / Egg
Egg / Rhino
Egg / Gargoyle
Egg / Eldrazi
Plant / Snake
Plant / Morph
Saproling / Morph
Saproling / Manifest

**Comment by GaryTheHutt** [comment]
Same error in GN2 set. All tokens are double sided; 6 combinations: 

Dragon #1 / Zombie #6 (M20)
Dragon #2 / Dinosaur
Dragon #2 / Zombie #6 (M20)
Soldier (M20) / Zombie #6 (M20)
Dinosaur / Soldier (M20)
Zombie (M20) / Wolf (M20)

**Comment by GaryTheHutt** [comment]
Same error in UND set. All tokens are double sided; 4 combinations:

Beeble / Squirrel
Beelble / Dragon
Goblin / Giant Teddy Bear
Giant Teddy Bear / Acorn Stash

**Comment by ZeldaZach** [comment]
@GaryTheHutt For your info, if you see the same issue across 2 or 3 sets, it's a compilation thing that will (probably) impact every set. Based on the work you've done, I have enough to look into what's happening.

**Comment by GaryTheHutt** [comment]
I looked at that, but it was not across every set where it was applicable. A few sets were configured correctly, but it is *almost* every set where applicable. Sorry for generating so much feedback, but I thought it would make it easier to fix if I gave you the specifics.

**Comment by ZeldaZach** [comment]
After reviewing the situation, I've had to decide not to pursue this feature. The value gained for repeated contents is minimal, and I don't have a strong source to provide this data other than hearsay. I appreciate your help in pointing out deficiencies within the project, but for the time being this will have to go as a no-fix.

If you do require the information to be more precise than I provide (i.e. with this ticket solved), if you'd like to provide a comparable fix with a credible source of data, I would welcome it!
