### ISSUE TITLE
changelog.json has typo in key

### ISSUE THREAD

**Issue by oniice** [mtgjson/mtgjson#565]
3.13.1 has as typo in they key.
Key is verison

Super trivial, but just came across it when consuming the data =)

**Comment by ZeldaZach** [comment]
I’ve been messing that up a lot. I’ll get em fixed soon

**Comment by tooomm** [comment]
fixed in https://github.com/mtgjson/mtgjson/commit/994644982a373365362ffe4aed0b3d0ae3911cef
