### ISSUE TITLE
GNT missing tokens

### ISSUE THREAD

**Issue by GaryTheHutt** [mtgjson/mtgjson#566]
There are 6 distinct double-sided tokens in the Game Night Box which aren't in the data:

Goblin (M19) / Thopter (M19)
Knight (M19) / Goblin (M19)
Knight (M19) / Thopter (M19)
Knight (M19) / Zombie (M19)
Zombie (M19) / Goblin (M19)
Zombie (M19) / Thopter (M19)

**Comment by ZeldaZach** [comment]
Dupe #565
