### ISSUE TITLE
set type

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson#57]
The proper set type for `Battlebonds` is missing. `two-headed_giant`?

Reading the initial issues it should be in the file already (can't check currently):
https://github.com/mtgjson/mtgjson/issues/581 & https://github.com/mtgjson/mtgjson/issues/587
If that's the case as described in the issue:
- set types should be uniform in case and don't use spaces
- why did it change to upper case? is there a pattern in the file when to use lower and when to use upper case?
- documentation needs updates

**Edit: is this implemented as `draft_innovation`?
And everything is lower case again? Documentation and AllSets file should be fine then.**

**Comment by ZeldaZach** [comment]
cc @ancestral

**Comment by ancestral** [comment]
Battlebond type is `draft_innovation`, a classification Wizards uses. (Scryfall also uses this value under their `set_type` property.)

From [Introducing Magic Weekend](https://magic.wizards.com/en/articles/archive/news/introducing-magic-weekend-2018-10-29), published today:
>Think of it like Battlebond or Conspiracy. We call products like these our "Draft innovation" sets—sets that get to break the rules a little, that get permission to do things other sets can't. They happen once a year, and they're different each time.
