### ISSUE TITLE
HOU token layout

### ISSUE THREAD

**Issue by GaryTheHutt** [mtgjson/mtgjson#570]
There are 24 double-sided Hour of Devastation tokens missing from the data:

Adorned Pouncer / Horse
Adorned Pouncer / Warrior mtgjson/mtgjson-website#17 (AKH)
Champion of Wits / Insect
Champion of Wits / Warrior mtgjson/mtgjson-website#17 (AKH)
Dreamstealer / Insect
Dreamstealer / Warrior mtgjson/mtgjson-website#17 (AKH)
Earthshaker Khenra / Cat (AKH)
Earthshaker Khenra / Zombie (AKH)
Proven Combatant / Cat (AKH)
Proven Combatant / Zombie (AKH)
Resilient Khenra / Cat (AKH)
Resilient Khenra / Zombie (AKH)
Sinuous Striker / Cat (AKH)
Sinuous Striker / Zombie (AKH)
Steadfast Sentinel / Cat (AKH)
Steadfast Sentinel / Zombie (AKH)
Sunscourge Champion / Cat (AKH)
Sunscourge Champion / Zombie (AKH)
Horse / Warrior mtgjson/mtgjson-website#17 (AKH)
Horse / Zombie (AKH)
Snake / Warrior mtgjson/mtgjson-website#17 (AKH)
Snake / Zombie (AKH)
Insect / Warrior mtgjson/mtgjson-website#17 (AKH)
Insect / Zombie (AKH)

**Comment by ZeldaZach** [comment]
Dupe #565
