### ISSUE TITLE
Errata for thousands of cards

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgjson#570]
With Dominaria now on Gatherer, thousands of cards have received errata. A rebuild should be needed.

`his or her` → `their`
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=438643

**Comment by ZeldaZach** [comment]
Ugh... I'll start my machine on this soon

**Comment by tooomm** [comment]
There is more than `their`:
https://magic.wizards.com/en/articles/archive/news/dominaria-oracle-changes-2018-04-13

**Comment by ancestral** [comment]
Yep. Lotsa stuff changed!

No one added DDU, sadly, so those are up now. Bu tI just realized we need challenger decks too…
