### ISSUE TITLE
AKH token layout

### ISSUE THREAD

**Issue by GaryTheHutt** [mtgjson/mtgjson#572]
There were 18 double-sided tokens included in the Amonkhet Bundle missing from the data. The 23 single-sided tokens included in booster packs is accurate. The double sided tokens are:

Angel of Sanctions / Drake
Anointer Priest / Drake
Aven Initiate / Snake
Aven Wind Guide / Hippo
Glyph Keeper / Warrior
Heart-Piercer Manticore / Warrior
Honored Hydra / Warrior
Labyrinth Guardian / Warrior
Labyrinth Guardian / Insect
Oketra's Attendant / Beast
Sacred Cat / Insect
Tah-Crop Skirmisher / Cat
Temmet, Vizier of Naktamun / Zombie
Trueheart Duelist / Zombie
Trueheart Duelist / Snake
Unwavering Initiate / Wurm
Vizier of Many Faces / Zombie
Zombie / Gideon of the Trials Emblem

**Comment by ZeldaZach** [comment]
Dupe #565
