### ISSUE TITLE
PCA token layout

### ISSUE THREAD

**Issue by GaryTheHutt** [mtgjson/mtgjson#573]
All Planechase Anthology tokens are double-sided. Listed as normal in data. 14 combinations are:

Eldrazi / Eldrazi Spawn mtgjson/mtgjson-website#2
Eldrazi / Eldrazi Spawn mtgjson/mtgjson-website#3
Eldrazi / Eldrazi Spawn mtgjson/mtgjson-website#4
Angel / Saproling
Goat / Insect
Germ / Goblin
Spider / Saproling
Zombie / Hellion
Dragon / Saproling
Goblin / Boar
Goblin / Saproling
Beast / Saproling
Ooze mtgjson/mtgjson-website#16 / Ooze mtgjson/mtgjson-website#17
Ooze mtgjson/mtgjson-website#16 / Plant

**Comment by ZeldaZach** [comment]
Dupe #565
