### ISSUE TITLE
C16 layout

### ISSUE THREAD

**Issue by GaryTheHutt** [mtgjson/mtgjson#574]
Same layout issue with Commander 2016 tokens. All tokens are double-sided, but listed as normal in data. The 18 combinations are:
Spirit mtgjson/mtgjson-website#1 / Spirit mtgjson/mtgjson-website#6
Bird mtgjson/mtgjson-website#2 / Spirit mtgjson/mtgjson-website#6
Bird mtgjson/mtgjson-website#2 / Saproling mtgjson/mtgjson-website#16
Bird mtgjson/mtgjson-website#2 / Myr
Elemental / Soldier
Goat / Thopter
Soldier / Squid
Spirit mtgjson/mtgjson-website#6 / Germ
Spirit mtgjson/mtgjson-website#6 / Saproling mtgjson/mtgjson-website#16
Bird mtgjson/mtgjson-website#7 / Ogre
Thopter / Germ
Thopter / Horror
Thopter / Daretti, Scrap Savant Emblem
Zombie / Goblin
Zombie / Elf Warrior
Zombie / Worm
Ogre / Beast
Saproling mtgjson/mtgjson-website#16 / Saproling mtgjson/mtgjson-website#17

**Comment by ZeldaZach** [comment]
Dupe #565
