### ISSUE TITLE
How do we accomodate incorrect magiccards.info scans for two flip cards?

### ISSUE THREAD

**Issue by bakert** [mtgjson/mtgjson#575]
There are two supplemental set scans that we point at from magiccards.info that are the wrong way up.

http://magiccards.info/scans/en/cmd/92b.jpg shows Nezumi Graverobber on the top part.
http://magiccards.info/scans/en/rep/3b.jpgs shows Budoka Gardener on the top part.

I emailed Hannes about this ages ago but I guess it's not going to be fixed upstream. Is there anything mtgjson should do?

I know we patch Gatherer issues all the time but images is different in that I'm not sure what we should point at instead. Feel free to close wontfix if that's the policy on this kind of thing.

**Comment by ZeldaZach** [comment]
Moot issue w/ MCI closed
