### ISSUE TITLE
Commander 2015 token layout

### ISSUE THREAD

**Issue by GaryTheHutt** [mtgjson/mtgjson#575]
The double-sided experience counter token is missing from your collection. https://shop.tcgplayer.com/magic/commander-2015/experience-double-sided-token?partner=mtgtcg

Other tokens in the set are double-sided, but marked as normal in your layout field. The 26 token versions are:

Experience / Experience
Shapeshifter / Shapeshifter
Shapeshifter / Elemental Shaman
Angel / Knight mtgjson/mtgjson-website#5
Angel / Spirit mtgjson/mtgjson-website#22
Cat / Zombie
Cat / Spirit mtgjson/mtgjson-website#23
Knight mtgjson/mtgjson-website#4/ Elemental Shaman
Knight mtgjson/mtgjson-website#5/ Spirit
Knight mtgjson/mtgjson-website#5/ Gold
Drake / Elemental
Germ / Zombie
Germ / Frog Lizard
Zombie / Elephant
Zombie / Wolf
Zombie / Spirit mtgjson/mtgjson-website#22
Dragon / Dragon
Dragon / Spider
Lightning Rager / Lightning Rager
Bear / Spider
Beast / Snake mtgjson/mtgjson-website#17
Elephant / Saproling
Saproling / Snake mtgjson/mtgjson-website#17
Saproling / Spider
Saproling / Snake mtgjson/mtgjson-website#21
Spider / Wolf

**Comment by ZeldaZach** [comment]
Dupe #565
