### ISSUE TITLE
token faces

### ISSUE THREAD

**Issue by GaryTheHutt** [mtgjson/mtgjson#577]
MD1 tokens are listed as 'normal' layout, but should be double-sided.

There are 3 combos:
Soldier / Spirit
Soldier/ Elspeth, Knight-Errant Emblem
Spirit / Myr

**Comment by GaryTheHutt** [comment]
Not sure what you mean by the website showing data. I downloaded the AllPrintings.json file and expanded all the data into spreadsheets. In most of the places the Layout field in the Token object should be 'double-sided' it is set to 'normal' and there is no side-b relationship set, so it looks like all the tokens for those sets are single sided. But it is inconsistent. For a few sets, it is correctly set to double-sided with side-b relationships (although I fundamentally disagree with your decision in many cases as to which side should be side-a).

**Comment by ZeldaZach** [comment]
Dupe #565
