### ISSUE TITLE
All `subtype: Saga` cards should have `layout: saga`

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#577]
It's pretty clearly a new layout.

**Comment by KingSupernova31** [comment]
Agreed. Most of the other layouts relate to the rules of the card, having some functional difference from normal cards.  However the "aftermath" layout is simply a visual difference from other split cards, so for consistancy, "saga" should be its own layout as well.

**Comment by silasary** [comment]
For those of us who use the layout field to apply image masks, this would be very useful.

**Comment by ZeldaZach** [comment]
Should be fixed in V4
