### ISSUE TITLE
Bant on the march deck file redirect to 404

### ISSUE THREAD

**Issue by krijoh92** [mtgjson/mtgjson#578]
#### Description of Bug:

Requesting https://www.mtgjson.com/json/decks/BantOnTheMarch_CON.json deck file gets redirected to  https://www.mtgjson.com/json/decks/BantOnTheMarch_CON_.json

**Comment by ZeldaZach** [comment]
Thanks for catching this. Fixed :)

**Comment by krijoh92** [comment]
Hmm, this bug has reappeared @ZeldaZach :/

This time on version 5.0.0+20200720

**Comment by ZeldaZach** [comment]
I changed from Apache to nginx. Might’ve missed this fix. Will address soon.

**Comment by ZeldaZach** [comment]
Fixed again. Sorry for the occurrence! Shouldn't happen again
