### ISSUE TITLE
Add Challenge decks

### ISSUE THREAD

**Issue by Sembiance** [mtgjson/mtgjson#58]
It has been requested that I add 'challenge deck' cards.

Currently these include:
- Face the Hydra
- Battle the Horde
- Defeat a God

See this link for more info: http://mtgsalvation.gamepedia.com/Challenge_deck

**Comment by Sembiance** [comment]
These do not appear to be on magiccards.info so I'll need to find another source of information as to what cards are in each deck and for future decks.

**Comment by ZeldaZach** [comment]
A fellow over at Cockatrice make an XML of all of the card data with picture links. You're free to use it.

https://github.com/Cockatrice/Magic-Token/blob/master/challenge_tokens.xml

**Comment by ZeldaZach** [comment]
Addressed in V4
