### ISSUE TITLE
Godzilla, Doom Inevitable is missing hasNonFoil=true

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#580]
https://shop.tcgplayer.com/magic/ikoria-lair-of-behemoths/godzilla-doom-inevitable-yidaro-wandering-monster?xid=piaf73c996-0159-421e-9f96-19a763653c6a

**Comment by ZeldaZach** [comment]
Nice catch

cc: @csuhta

**Comment by csuhta** [comment]
Fixed!
