### ISSUE TITLE
temple of abandon 347★ has wrong tcgplayer id

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#581]
it is pointing to https://shop.tcgplayer.com/magic/theros-beyond-death/temple-of-abandon?id=206632 while it should point to https://shop.tcgplayer.com/magic/theros-beyond-death/temple-of-abandon-extended-art?id=206641

**Comment by ZeldaZach** [comment]
Looks to be an upstream issue
cc: @csuhta

**Comment by csuhta** [comment]
Fixed on Scryfall
