### ISSUE TITLE
disallowed "type" for Explorers of Ixalan (e02)

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson#582]
http://mtgjson.com/json/E02.json
has `type: "board game deck"`
which is not allowed according to: http://mtgjson.com/documentation.html#sets

**Comment by silasary** [comment]
Among the existing types, I'd categorize it as "box"

>
That said, if wizards continues to release "Packaged Experiences" in the
E0X range, this may need it's own thing

**Comment by ZeldaZach** [comment]
V4 will have new documentation, and I'm allowing this type for the time being
