### ISSUE TITLE
There are no Time Spiral Timeshifted boosters

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#584]
See: https://mtgjson.com/json/TSB.json

One of the cards from Time Spiral Timeshifted is in Time Spiral boosters on special sheet, but there shouldn't be any boosters for Time Spiral Timeshifted set.

Same as masterpiece (like [EXP](https://mtgjson.com/json/EXP.json) etc.) sets don't get "booster" field for set which might include them.

**Comment by ZeldaZach** [comment]
At this time, V4 has removed the "booster" field until we can come up with a better solution. This will be addressed in the future, but such a ticket isn't necessary.

Thanks for bringing this to my attention!
