### ISSUE TITLE
every godzilla cards have the wrong tcgproductid

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#584]
The current tcgproductid for the IKO godizlla cards are pointing to the normal version

The correct list seems to be this

Godzilla Name - Normal Name | TCG Product Id
-- | --
Ghidorah, King of the Cosmos - Illuna, Apex of Wishes | 212004
Biollante, Plant Beast Form - Nethroi, Apex of Death | 212076
Mothra, Supersonic Queen - Luminous Broodmoth | 212007
Bio-Quartz Spacegodzilla - Brokkos, Apex of Forever | 212040
Rodan, Titan of Winged Fury - Vadrok, Apex of Thunder | 212014
King Caesar, Awoken Titan - Snapdax, Apex of the Hunt | 212027
Godzilla, Primeval Champion - Titanoth Rex | 212031
Godzilla, Doom Inevitable - Yidaro, Wandering Monster | 212061
Destoroyah, Perfect Lifeform - Everquill Phoenix | 212060
Gigan, Cyberclaw Terror - Gyruda, Doom of Depths | 212253
Spacegodzilla, Death Corona - Void Beckoner | 212022
Anguirus, Armored Killer - Gemrazer | 212073
King Caesar, Ancient Guardian - Huntmaster Liger | 212085
Dorat, the Perfect Pet - Sprite Dragon | 212043
Babygodzilla, Ruin Reborn - Pollywog Symbiote | 212029
Mothra's Giant Cocoon - Mysterious Egg (JP Alternate Art) | 212065
Battra, Terror of the City - Dirge Bat (JP Alternate Art) | 212069
Mechagodzilla - Crystalline Giant (JP Alternate Art) | 212070
Godzilla, King of the Monsters - Zilortha, Strength Incarnate | 212041

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
Fixed on Scryfall
