### ISSUE TITLE
Lightning Bolt's oracle text is wrong

### ISSUE THREAD

**Issue by JineteDV** [mtgjson/mtgjson#585]
Updated my xml before checking this again, it persists.

Is: Lightning Bolt deals 3 damage to target creature or player.
Should be: Lightning Bolt deals 3 damage to any target.

**Comment by fenhl** [comment]
More specifically, the text is *correct* for the following printings:

* LEA
* LEB
* 2ED
* 3ED
* 4ED
* BTD
* MED
* M10
* M11
* PD2
* MM2
* E01
* A25

but *outdated* for the following printings:

* CEI
* CED
* pJGP
* ATH
* pMPR

**Comment by ZeldaZach** [comment]
Those bottom sets are all MCI aren’t they? Being discontinued with v4

**Comment by ZeldaZach** [comment]
Looked into it; The outdated ones are not real magic sets, and they're MCI. No-fix as addressed in v4

**Comment by fenhl** [comment]
How are these “not real magic sets”?
