### ISSUE TITLE
Classic VI edition wrong number

### ISSUE THREAD

**Issue by nicho92** [mtgjson/mtgjson#585]
#### MTGJSON Version: 4.6.3+20200601
Gatherer give wrong collector number

#### Description of Bug:
![image](https://user-images.githubusercontent.com/11507615/83558237-01b7b600-a513-11ea-9c69-10819b8e54db.png)

**Comment by ZeldaZach** [comment]
Hmm, seems to be a more widespread issue in 6th Edition. Will talk with upstream and figure out what's up.

**Comment by ZeldaZach** [comment]
Fixed upstream, will be addressed on Monday here!
