### ISSUE TITLE
.json.zip links 404

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#59]
On https://mtgjson.com/v4/ :

* https://mtgjson.com/v4/json/AllSets.json.zip
* https://mtgjson.com/v4/json/AllCards.json.zip

**Comment by ZeldaZach** [comment]
So the issue we have at hand is incorrect file names across our website

Future Spec: File names SHALL follow the format
```
SET_CODE.json
SET_CODE.json.gz
SET_CODE.json.zip
```
Where SET_CODE is defined as any file name. Will be fixed soon.
