### ISSUE TITLE
C20 cards all marked as having nonfoil version

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#590]
https://www.mtgjson.com/json/C20.json

As far as I known, 20 cards with foils only exist in foil versions.

**Comment by ZeldaZach** [comment]
If you know which cards, might be helpful. However, this tags back to upstream.

cc: @csuhta

**Comment by taw** [comment]
All cards C20.json marks as hasFoil+hasNotFoil are actually foil only (commander, alt commander, and alt partner commanders for each deck), not foil+nonfoil.

For precon sets, generally card is either foil, or nonfoil, not really both (there was like one exception to this rule ever).

**Comment by ZeldaZach** [comment]
According to upstream, the collector packs are the reason non-foils can exist. As such, this appears to be working as expected.

**Comment by taw** [comment]
Oh wow, I missed that.
