### ISSUE TITLE
C20 release date is wrong

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#591]
https://www.mtgjson.com/json/C20.json

It incorrectly has `"releaseDate": "2020-04-24"`. That was the original planned release, [but it got moved to 2020-04-17](https://mtg.gamepedia.com/Commander_2020).

**Comment by ZeldaZach** [comment]
Seems to be indicated upstream. I'm not sure of the model they follow (scheduled date or actual date)

cc: @csuhta
