### ISSUE TITLE
Lurrus missing MTGO Price

### ISSUE THREAD

**Issue by oelarnes** [mtgjson/mtgjson#592]
#### Description of Bug:
Seems to be the only card in IKO missing an mtgo price. I strongly suspect it's due to the fact that mtgo exports the name as "Lurrus of the Dream Den" rather than "Lurrus of the Dream-Den"

**Comment by ZeldaZach** [comment]
Appears one of our upstream providers is having an ID collision. Will address it with them directly.

**Comment by ZeldaZach** [comment]
This was fixed upstream, should have been populating for a bit.
