### ISSUE TITLE
WAR Planeswalkers mismatched prices

### ISSUE THREAD

**Issue by oelarnes** [mtgjson/mtgjson#593]
#### Description of Bug:
The WAR file has records for the Japanese alt-art planeswalkers with collector numbers like "number": "1★" (at least, this is how scryfall represents things). The mtgo prices for the usual version of the card is being attached to these records.

**Comment by ZeldaZach** [comment]
Hey @oelarnes can you go into a bit more detail on the issue. Are the digital prices wrong? paper? Is there a flip between the printings? Can you show examples so I can dig deeper into this

**Comment by oelarnes** [comment]
There are two entries for Teferi, Time Raveler. One has a normal collector number, an mtgoId, and no mtgo price. I copied these values from the json object currently linked on the main site:

"mtgoId": 72048...  "name": "Teferi, Time Raveler", "number": "221" ... "prices": {"mtgo": {}, "mtgoFoil": {}, ...

The other has a starred collector number, no mtgoId, and an mtgo price

"name": "Teferi, Time Raveler", "number": "221★", "prices": {"mtgo": {"2020-06-23": 27.49}

I believe the mtgo price on the second record corresponds to the mtgoId on the first record.

**Comment by ZeldaZach** [comment]
I just went through v4's AllPrices and it appears to be correct on that part. The internal "prices" field shouldn't be used any longer and the AllPrices.json file should be the source of price data instead.
