### ISSUE TITLE
Battlebond not listed as a set in AllCards-x.json for many BBD reprints

### ISSUE THREAD

**Issue by paithan** [mtgjson/mtgjson#594]
The first card I noticed was Feral Hydra

**Comment by paithan** [comment]
Also Wandering Wolf

**Comment by paithan** [comment]
Also: Swords to Plowshares and Rhox Brute,

**Comment by jmcsmith** [comment]
I see all these in the json.

**Comment by fenhl** [comment]
I can confirm that these are in the JSON. Closing as cannot reproduce, will reopen if you can clarify.

**Comment by paithan** [comment]
Sorry, I should have been more specific: when I look at AllCards-x.json, it is missing the Battlebond printing for each of these cards.

I found more: Yotian Soldier, Night Market Guard, Fertile Ground, Elvish Visionary, Giant Growth, Earth Elemental, Blaze, Lightning Talons, Pathmaker Initiate, Shock, Fill with Fright, Painful Lesson, Phantom Warrior, Call to Heel, Opportunity, Negate, and Pacifism.

**Comment by paithan** [comment]
Angelic Chorus is also one of these.

**Comment by paithan** [comment]
I found another card: Hunted Wumpus

**Comment by paithan** [comment]
The presumably related issue #602 has been mostly fixed.  That seems to have fixed this too, as all the above cards are now listed.  Thank you!
