### ISSUE TITLE
(v5) EnumValues.json is not capturing individual deck "type"

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgjson#594]
In https://mtgjson.com/api/v5/EnumValues.json, the property of `data.deck.type` is an empty array. It seems these are no longer being capture as enum values and thus not in the generated json.

**Comment by ZeldaZach** [comment]
Hmm... the uploaded version is empty, but my local version has the value. Will postpone this until I do another full build and see what's up.

**Comment by ZeldaZach** [comment]
Yeah on the rebuild they're in... not sure why that bugged out before.
