### ISSUE TITLE
Once More With Feeling is "restricted"

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#595]
For some reason the Unglued card Once More With Feeling has legality "Restricted" in Un-Sets rather than "Legal".

**Comment by ZeldaZach** [comment]
Possible it actually is restricted...?

**Comment by fenhl** [comment]
Yup, it says so right on the card.

**Comment by KingSupernova31** [comment]
Oh, I see. I don't think it should be entered that way on MTGjson though. It's not actually restricted according to the Banned and Restricted list that WOTC publishes.

**Comment by ZeldaZach** [comment]
After thinking about this for a bit, I'm leaving it as is. The card states its own abilities and it's an un-set.
