### ISSUE TITLE
Some split cards have the wrong half's original text

### ISSUE THREAD

**Issue by Tedderouni** [mtgjson/mtgjson#597]
On some split cards, the originalText field for the second half of the card has the original text for the first half.  Examples I've found include: Assault/Battery, Stand/Deliver, and Pain/Suffering from Invasion; Order/Chaos from Apocalypse; and Rough/Tumble from Commander 2013.  Not sure if there are others.

**Comment by ZeldaZach** [comment]
If this is still an issue on V4, feel free to open a ticket or comment on a relevant one
