### ISSUE TITLE
Missing IKO cards?

### ISSUE THREAD

**Issue by lconnellan** [mtgjson/mtgjson#598]
#### Description of Bug: 

Recently tried updating the database on cockatrice from https://www.mtgjson.com/files/AllPrintings.json.xz but there appears to be some missing cards from Ikoria e.g. The Ozolith, and some other cards with placeholder names. Not sure if this is a cockatrice problem or a MTGJSON problem but I thought I should raise it anyway.

Interestingly the cards seem to be there in the CSV version?

**Comment by ZeldaZach** [comment]
We had a system failure last night. A new build went live a moment ago with all of Ikoria!

**Comment by lconnellan** [comment]
Ok thanks!
