### ISSUE TITLE
Incorrect original types and original text on some split cards (upstream)

### ISSUE THREAD

**Issue by Tedderouni** [mtgjson/mtgjson#598]
I've found a few split cards where the original types and original text are incorrect.  The ones listed here are incorrect on Gatherer too.  Not sure if there are any other examples of this.

- Ice from Fire/Ice in Commander
- Ice from Fire/Ice in Duel Decks: Izzet vs. Golgari
- Death from Life/Death in Duel Decks: Izzet vs. Golgari

**Comment by ZeldaZach** [comment]
Should be working on V4, but might not. If so, open a ticket there or append to one that's there already :)
