### ISSUE TITLE
Add frame field

### ISSUE THREAD

**Issue by Sembiance** [mtgjson/mtgjson#60]
Add a 'frame' field for sets (and also to cards in promo sets) that denote what style of 'frame' the set/card has (original, eigth edition, magic 2015, timeshifted, etc).

Make sure this doesn't conflict/overlap with 'layout'. So potentially come up with a different name than 'frame'

**Comment by Kerrick** [comment]
I think frame is a fine name, it seems plenty different from layout.

Also, 👍!

**Comment by ZeldaZach** [comment]
Addressed in V4 :)
