### ISSUE TITLE
Creature types are not updated with M19 update

### ISSUE THREAD

**Issue by theelk801** [mtgjson/mtgjson#600]
There are some creature type erratas that haven't been updated with M19 like Dragon Egg now being an Egg and Electryte now being a Trilobyte.

**Comment by ZeldaZach** [comment]
Full rebuild will be required; Will look into doing it around September

**Comment by fenhl** [comment]
There are also Oracle text changes, e.g. on Phantasmal Image, which are still missing.

**Comment by ancestral** [comment]
We need to do a rebuild sooner than September, with reprint bugs and with Commander out in August.

**Comment by KingSupernova31** [comment]
It looks like none of the oracle updates from M19 have been incorporated. The full list of affected cards can be found here:

https://magic.wizards.com/en/articles/archive/news/core-set-2019-oracle-changes-2018-07-06

Hopefully this can be fixed sooner than September, it's a pretty serious issue for any application that needs accurate text.

**Comment by fenhl** [comment]
Any updates on this? A “full rebuild” was released on August 10, but it didn't fix this issue.

**Comment by ZeldaZach** [comment]
Hmm... If the full rebuild didn't catch it, maybe there's a SET_CORRECTIONS overriding the rebuild

**Comment by fenhl** [comment]
Apologies, it seems the issue was a rogue cache on my end.
