### ISSUE TITLE
Certain double-sided tokens where both sides have the same name have the same UUID for each side

### ISSUE THREAD

**Issue by aaronbamberger** [mtgjson/mtgjson#600]
#### Description of Bug:
I'm actually not 100% sure this is a bug, it's possible this is intentional behavior, but it was surprising to me, so I wanted to open an issue to check.  My assumption was that card UUIDs uniquely indicated a card face, since that seems to be true for most of the double-sided cards that I checked.  However, certain double-sided tokens that seem to differ only in image share the same UUID for each side.  These tokens only seem to exist in a few sets, specifically

* Eldritch Moon Promos
* Global Series Jiang Yanggu & Mu Yanling
* Unstable
* Modern Horizons Art Series

(although that last one isn't really a set, so I could understand some weirdness there).

An example token is the Zombie token from Eldritch Moon Promos, where both sides have the UUID `01a073de-9b36-56e4-8a44-3f757de2cfbd`

I believe I have an exhaustive list of all of the tokens that have this issue that I can post if needed, but I didn't want to open an issue with a big list if this ends up being expected behavior.  If this is not intentional, let me know and I can put up the whole list of affected tokens.

Thanks so much for this project, it's really neat!

**Comment by ZeldaZach** [comment]
Every card in the program should have a unique UUID (hence the U in UUID). This is most certainly a bug that I will be looking into.

**Comment by aaronbamberger** [comment]
That's what I figured, just wanted to double check.  The full list of tokens that I noticed with this behavior are:

* Modern Horizons Art Series (AMH1)
  * Endling
  * Morophon, the Boundless
  * Sisay, Weatherlight Captain
  * Waterlogged Grove
  * Sword of Sinew and Steel
  * Prismatic Vista
  * Silent Clearing
  * Wall of One Thousand Cuts
  * Face of Divinity
  * Smoke Shroud
  * First Sliver's Chosen
  * Arcum's Astrolabe
  * Ingenious Infiltrator
  * Sword of Truth and Justice
  * Mox Tantalite
  * Lancer Sliver
  * Goblin Matron
  * Rebuild
  * Serra the Benevolent
  * Scour All Possibilities
  * Watcher for Tomorrow
  * Soulherder
  * Wrenn and Six
  * Zhalfirin Decoy
  * Plague Engineer
  * Warteye Witch
  * Winds of Abandon
  * Force of Despair
  * Echo of Eons
  * Ayula, Queen Among Bears
* Eldritch Moon Promos (PEMN)
  * Zombie
* Global Series Jiang Yanggu & Mu Yanling (GS1)
  * Mowu
* Unstable (UST)
  * Angel
  * Saproling
  * Vampire
  * Zombie

**Comment by ZeldaZach** [comment]
So this breaks down to me forgetting to say "tokens please use the token UUID generation op"... oops.
