### ISSUE TITLE
Cards with multiple faces (e.g. transform layout) missing Scryfall Illustration ID

### ISSUE THREAD

**Issue by cheyner** [mtgjson/mtgjson#601]
#### Description of Bug:
"transform" layout cards in MTGJSON data are lacking ScryfallIllustrationId

In the Scryfall API, for cards w/transform layout, Scryfall Illustration ID is nested in the card_faces object.

**Comment by ZeldaZach** [comment]
Good catch. It seems to be an issue on v5 & v4. Will address and backport.
