### ISSUE TITLE
Reprints in M19 are not listed

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#602]
Cards in M19 that are reprints from an earlier set are not properly listed as being in M19. For example, Dragon Egg's printings are listed as just M14, EMA, and IMA. Cards that are exclusive to M19 do not have this issue.

**Comment by paithan** [comment]
This does not apply to all reprints.  E.g. Knightly Valor still has M19 listed as a printing in AllCards-x.json.

**Comment by paithan** [comment]
This is similar to issue #594.  

M19 problem cards I've noticed: Meandering River, Stone Quarry, Timber Gorge, Woodland Stream, Diregraf Ghoul, Switcheroo, Bone to Ash, Dragon Egg (as KingSupernova31 mentioned), Recollect, Gift of Paradise, Enigma Drake, Rogue's Gloves, Gargoyle Sentinel, Inspired Charge, Oreskos Swiftclaw, Totally Lost, Anticipate, Ghostform, Tolarian Scholar, Snapping Drake, Cancel, Disperse, Doomed Traveler, Child of Night, Mind Rot, Duress, Walking Corpse, Macabre Waltz, Smelt, Sure Strike, Trumpet Blast, Act of Treason, Shock, Electrify, Lava Axe, Tormenting Voice, Fire Elemental, Daggerback Basilisk, Centaur Courser, Oakenform, Naturalize, Highland Game, Wall of Vines, Giant Spider, Plummet, Druid of the Cowl, Titanic Growth, Field Creeper, Manalith

**Comment by KingSupernova31** [comment]
Rupture Spire too.

**Comment by paithan** [comment]
It seems like reprints that have been printed a lot (e.g. Lava Axe) are always missing, while others sometimes have the new set included.

**Comment by ancestral** [comment]
At least one reprint isn’t showing in Battlebond: Greater Good.

**Comment by ancestral** [comment]
We need someone to attempt a rebuild as something did not work right last time.

**Comment by ZeldaZach** [comment]
I’ll get to it this week

**Comment by paithan** [comment]
The problem has been fixed for all cards listed above except for Act of Treason.  Excellent!

**Comment by ZeldaZach** [comment]
Fixed in V4

**Comment by paithan** [comment]
Act of Treason is still missing here.

**Comment by KingSupernova31** [comment]
@paithan Is this an issue in v4? I don't believe v3 is still being supported.

**Comment by paithan** [comment]
I don't know about the version numbers.  When I download the new json files and use them, M19 isn't listed as a printing of Act of Treason.

**Comment by KingSupernova31** [comment]
If you're having an issue with v4, you should open a ticket there. Any problems with v3 are most likely never going to be fixed.
