### ISSUE TITLE
Price Issues in v4

### ISSUE THREAD

**Issue by cmdr0** [mtgjson/mtgjson#602]
#### Description of Bug:

AllPrices.json appears to be missing price data/historic prices for a large number of cards (12,583)
Complete list of discovered IDs at https://pastebin.com/23wqTAas
List does include some JMP/M21, which at this point is not expected to have price data, but was not filtered out of my query

First fifty from that list presented here:

**Name [Set]:** Scroll Rack [wc98]
**UUID:** "000031ff-f095-52c5-98a1-35bdb5e18a5b"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Swamp [wc01]
**UUID:** "0001fc69-3a61-51e3-aa17-19abb29803f2"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Zombie Master [fbb]
**UUID:** "000473fc-c380-58ef-a52e-c745b880b0c2"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Boiling Blood [wth]
**UUID:** "000cdbc5-3c5b-5bb6-b7db-49bf40a5d14f"
**Price Data:**
```
{ "prices": { "mtgo": { "2020-06-23": 0.04 }, "mtgoFoil": { "2020-06-23": 0.02 }, "paper": { "2020-06-21": 0.22 }, "paperFoil": {} } }
```

**Name [Set]:** Swamp [prm]
**UUID:** "000e47b7-d761-5b00-b32f-bb17b60b19be"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Tainted Isle [tor]
**UUID:** "00141b3e-ccfd-5a78-a2d7-8156ca88ca96"
**Price Data:**
```
{ "prices": { "mtgo": { "2020-06-23": 0.19 }, "mtgoFoil": { "2020-06-23": 0.52 }, "paper": { "2020-06-21": 2.95 }, "paperFoil": { "2020-06-21": 13.92 } } }
```

**Name [Set]:** Fire // Ice [wc01]
**UUID:** "00154bfc-bc93-55c4-a2cb-0c33a2f68d65"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Mishra's Factory [4bb]
**UUID:** "00177f04-58c8-5a7c-8f83-6175b6482f40"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Forest [wc02]
**UUID:** "0018480d-8174-5976-90b0-9323cf297b2d"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Tawnos, Urza's Apprentice [pz2]
**UUID:** "001fdbb1-bb67-5c9f-89d4-e5394a44a415"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Plow Under [wc04]
**UUID:** "0023f81f-e305-565b-b775-25fc2cea6954"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Bull Elephant [mgb]
**UUID:** "0024c9c6-623b-5d28-8198-76cce6eaa1c1"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Gideon Jura [prm]
**UUID:** "002ad4bf-8219-590c-b271-9272f3f9ebe8"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Lu Bu, Master-at-Arms [prm]
**UUID:** "002ce20a-a78f-5add-9d5f-96a99cc67323"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Ancient Stirrings [prm]
**UUID:** "002ff8e2-fbf4-500f-822a-326613b2859a"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Rhox [psal]
**UUID:** "00359c5d-c907-56ca-b831-0b239eab1d48"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Nimbus Wings [zen]
**UUID:** "00388d67-7d0e-5ae6-8c39-49cfd15deacf"
**Price Data:**
```
{ "prices": { "mtgo": { "2020-06-23": 0.04 }, "mtgoFoil": { "2020-06-23": 0.01 }, "paper": { "2020-06-21": 0.12 }, "paperFoil": { "2020-06-21": 0.2 } } }
```

**Name [Set]:** Sandbar Merfolk [usg]
**UUID:** "003b8845-21f5-5758-a2b1-ad3e18a50fef"
**Price Data:**
```
{ "prices": { "mtgo": { "2020-06-23": 0.04 }, "mtgoFoil": { "2020-06-23": 0.02 }, "paper": { "2020-06-21": 0.14 }, "paperFoil": {} } }
```

**Name [Set]:** Hero of Goma Fada [prm]
**UUID:** "003f7d58-d112-50ff-a8c2-58dd7c19a54a"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Reverse Damage [itp]
**UUID:** "00428bd3-0fa1-5e09-b7de-2804b8a0175c"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Tibalt, Rakish Instigator [prm]
**UUID:** "0042f7c3-9630-5ba9-9669-0d339bdc07f9"
**Price Data:**
```
{ "prices": {} }
```

**Name [Set]:** Evacuation [ps11]
**UUID:** "004d40c5-e506-54af-91cd-71621c4dcd9d"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Untamed Wilds [itp]
**UUID:** "004fcfe5-fc9c-550e-81b5-025e8e9d68b4"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Revel in Riches [xln]
**UUID:** "0052a6c6-4279-5c04-8d20-9c9893d2aa26"
**Price Data:**
```
{ "prices": { "mtgo": { "2020-06-23": 0.02 }, "mtgoFoil": { "2020-06-23": 0.59 }, "paper": { "2020-06-21": 3.18 }, "paperFoil": { "2020-06-21": 7.46 } } }
```

**Name [Set]:** Assault // Battery [tsb]
**UUID:** "00574b2a-ccb0-5ceb-ae66-673d973c1360"
**Price Data:**
```
{ "prices": { "mtgo": { "2020-06-23": 0.02 }, "mtgoFoil": { "2020-06-23": 0.3 }, "paper": { "2020-06-21": 0.16 }, "paperFoil": { "2020-06-21": 0.33 } } }
```

**Name [Set]:** Dire Fleet Captain [xln]
**UUID:** "005a975d-6519-5feb-817a-9b606684a171"
**Price Data:**
```
{ "prices": { "mtgo": { "2020-06-23": 0.03 }, "mtgoFoil": { "2020-06-23": 0.02 }, "paper": { "2020-06-21": 0.14 }, "paperFoil": { "2020-06-21": 0.35 } } }
```

**Name [Set]:** Island [psal]
**UUID:** "006085a6-f164-5e4b-807a-6a8e916e1564"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Omnath, Locus of Mana [wwk]
**UUID:** "0068aba4-76d5-5c13-b250-1fdd031df180"
**Price Data:**
```
{ "prices": { "mtgo": { "2020-06-23": 0.78 }, "mtgoFoil": { "2020-06-23": 2.19 }, "paper": { "2020-06-21": 21.72 }, "paperFoil": { "2020-06-21": 36.21 } } }
```

**Name [Set]:** Rakdos Firewheeler [prm]
**UUID:** "0073334d-ca4e-5232-956e-faf391f43e43"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Mishra, Artificer Prodigy [tsp]
**UUID:** "00766259-ad0c-56e7-99fd-974075a3d26d"
**Price Data:**
```
{ "prices": { "mtgo": { "2020-06-23": 0.02 }, "mtgoFoil": { "2020-06-23": 0.03 }, "paper": { "2020-06-21": 0.8 }, "paperFoil": { "2020-06-21": 13.44 } } }
```

**Name [Set]:** Grim Tutor [m21]
**UUID:** "008d4f50-38c2-5b57-9e8f-9d85692167e9"
**Price Data:**
```
{ "prices": {} }
```

**Name [Set]:** Flying Men [tsb]
**UUID:** "00918060-9e23-507a-9f24-a055d0eb64ce"
**Price Data:**
```
{ "prices": { "mtgo": { "2020-06-23": 0.02 }, "mtgoFoil": { "2020-06-23": 0.03 }, "paper": { "2020-06-21": 1.79 }, "paperFoil": { "2020-06-21": 3.82 } } }
```

**Name [Set]:** Vraska's Contempt [xln]
**UUID:** "009a7f95-4de3-5466-a608-8195abd5c503"
**Price Data:**
```
{ "prices": { "mtgo": { "2020-06-23": 0.02 }, "mtgoFoil": { "2020-06-23": 0.7 }, "paper": { "2020-06-21": 1.63 }, "paperFoil": { "2020-06-21": 2.92 } } }
```

**Name [Set]:** Whelming Wave [jmp]
**UUID:** "009dcf1b-097f-5bd8-94b7-d4280b8d8127"
**Price Data:**
```
{ "prices": {} }
```

**Name [Set]:** Spawning Pool [wc99]
**UUID:** "00a4b301-7d93-54b4-b9e7-94127faa4737"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": { "2020-06-21": null }, "paperFoil": {} } }
```

**Name [Set]:** Sylvan Library [prm]
**UUID:** "00abc47e-421b-5cb9-bdcd-3c4b64e05e11"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Horizon Seed [psal]
**UUID:** "00adb245-cae8-52e7-9704-05b9690583e2"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Master of Etherium [ps11]
**UUID:** "00afe8bd-8548-521f-9113-8c11b976a8c5"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Tamiyo, Collector of Tales [pwar]
**UUID:** "00b46211-0230-527b-b155-96123d5088fe"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Steal Artifact [4bb]
**UUID:** "00bad095-b804-50b5-afce-89f7c831568e"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Necratog [wth]
**UUID:** "00cc297f-f86f-5a62-a701-0177e39eae09"
**Price Data:**
```
{ "prices": { "mtgo": { "2020-06-23": 0.04 }, "mtgoFoil": { "2020-06-23": 0.03 }, "paper": { "2020-06-21": 0.18 }, "paperFoil": {} } }
```

**Name [Set]:** Cursed Scroll [wc99]
**UUID:** "00d6e8fa-7e64-5aa6-b9fd-bf93b55aac3a"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Vines of Vastwood [zen]
**UUID:** "00dae5b5-316d-56e0-9acc-0827f37db1d4"
**Price Data:**
```
{ "prices": { "mtgo": { "2020-06-23": 0.04 }, "mtgoFoil": { "2020-06-23": 0.05 }, "paper": { "2020-06-21": 0.81 }, "paperFoil": { "2020-06-21": 5.93 } } }
```

**Name [Set]:** Call of the Wild [wth]
**UUID:** "00de3931-a548-5705-8f95-54e45364245a"
**Price Data:**
```
{ "prices": { "mtgo": { "2020-06-23": 0.1 }, "mtgoFoil": { "2020-06-23": 0.33 }, "paper": { "2020-06-21": 0.38 }, "paperFoil": {} } }
```

**Name [Set]:** War Mammoth [itp]
**UUID:** "00df2d4f-3d69-546f-9563-da130c861f2b"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Dawnfeather Eagle [aer]
**UUID:** "00e5461a-b77d-5590-8674-98e78f411105"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Name [Set]:** Goblin Grenadiers [wth]
**UUID:** "00ea9aaa-778c-5010-954a-c3a9b2f44765"
**Price Data:**
```
{ "prices": { "mtgo": { "2020-06-23": 0.04 }, "mtgoFoil": { "2020-06-23": 0.06 }, "paper": { "2020-06-21": 0.34 }, "paperFoil": {} } }
```

**Name [Set]:** Dauntless Onslaught [ths]
**UUID:** "00ecdefd-0445-576e-a9a5-f5b21aa177e9"
**Price Data:**
```
{ "prices": { "mtgo": { "2020-06-23": 0.03 }, "mtgoFoil": { "2020-06-23": 0.02 }, "paper": { "2020-06-21": 0.06 }, "paperFoil": { "2020-06-21": 0.22 } } }
```

**Name [Set]:** Uro, Titan of Nature's Wrath [pthb]
**UUID:** "00f5b56c-d9f2-5f0b-a286-c872de999c54"
**Price Data:**
```
{ "prices": {} }
```

**Name [Set]:** Pain Kami [psal]
**UUID:** "00f789fc-c808-5051-acf7-c70989b4b2a5"
**Price Data:**
```
{ "prices": { "mtgo": {}, "mtgoFoil": {}, "paper": {}, "paperFoil": {} } }
```

**Comment by ZeldaZach** [comment]
As I'm looking through these, I'm noticing a pattern. There are a lot of cards that aren't sold/ID'd by upstream systems (such as Gold Border cards) and the other cards I see here (Like Boiling Blood) has the correct amount of data in AllPrices v4 and v5. I'm not really sure where to go with this at the moment until we can clarify further which cards _should_ have better pricing data and what's wrong with them.

**Comment by ZeldaZach** [comment]
If you have more info in the future, please feel free to reopen :)
