### ISSUE TITLE
Set titles for website and github

### ISSUE THREAD

**Issue by Cortes2141** [mtgjson/mtgjson#603]
I know this is totally small potatoes, but would it be possible to get the set titles on http://mtgjson.com/sets.html. So rather than it just saying 'UST 2017-12-08'  it could say 'UST - Unstable 2017-12-08' or some variant. Additionally, on GitHub, the descriptions column just says something like 'Language Files 1'. Could we update it to say the set and the language? ie '10th Edition - Chinese'...  Again, I know its probably not that important, but it would cut down on my having to go Google search the code for a particular set i need the JSON file for, then doing a CTRL-F on the page :)

**Comment by hoganlong** [comment]
The set title not showing seems to be a bug -- the code clearly is attempting to render `set.name` in an h2 tag.  That value is empty on the webpage.

I'm not sure what you mean by the descriptions column.  Which page?

**Comment by Cortes2141** [comment]
Hey, sorry it has taken me so long to get back. I forgot about this issue and have been working on other things! Here is a screen shot showing the "descriptions" for each JSON file... It would be great if it said "10th Edition French" instead of just language file...
![mtg sets](https://user-images.githubusercontent.com/39924413/45272158-2e8b8600-b471-11e8-86e4-f1f8abf049f8.jpg)

**Comment by tooomm** [comment]
The right part `Language Files 1`, `partial rebuild`, Introduce editorconfig (#371)` etc. are names of the latest commit changing these files, and no editable descriptions...
So this can not be changed.

**Comment by ZeldaZach** [comment]
Addressed in our rebuild of the website
