### ISSUE TITLE
Include spoilers

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#606]
#239 suggests that the details of new sets are included before the full card list is released. I suggest taking that a bit further and including newly spoiled cards as they come out. This would be extremely helpful for websites that want to have an up-to-date database of cards, as they wouldn't have to be missing information for the several weeks between the first spoilers and the full set dump.

Clearly this would require a bit of work to maintain as all the info would have to be entered manually, but it shouldn't be that bad. Websites like Mythic Spoiler will collect all the spoilers known on any given date and transcribe their text, which should make it pretty easy to pull from them.

**Comment by ZeldaZach** [comment]
Addressed in V4. Glad to get this working :)
