### ISSUE TITLE
C18 is missing from AllCards, AllSets-x, and AllSets

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgjson#608]
Cards (or at least new cards) from C18 are missing from three of four compiled JSON files.

If you do a search for `Yuriko` (one of the new commanders from the set) you should see it at least once, but it’s only in one of the four files. The same goes for other new Commander 2018 cards.

**Comment by ZeldaZach** [comment]
I'm honestly not sure why this is going haywire like this...

**Comment by ZeldaZach** [comment]
It's possible the files didn't get cached yet as cloudflare is being annoying

**Comment by tooomm** [comment]
How are the allsets, allcards files created btw?
As we don't keep them in the repo and don't update them as we do with the others.

Maybe we should start doing so if that solves the issues with big delays?

**Comment by fenhl** [comment]
Hmm. In version 4 we won't have build artifacts in the repo at all. Since that's not an option for v3 though, I think it would make sense to be consistent and have all of the build artifacts in the repo.

**Comment by KingSupernova31** [comment]
This is fixed now, right?

**Comment by ZeldaZach** [comment]
Should be
