### ISSUE TITLE
Rarity field missing from AllCards

### ISSUE THREAD

**Issue by Carkoth** [mtgjson/mtgjson#609]
Have the rarities been moved to somewhere else?

**Comment by ZeldaZach** [comment]
I don't believe AllCards gets rarity b/c cards can have at different rarities over time.

**Comment by Carkoth** [comment]
Yes, that could be a possibility, but in the example card section of the website
![capture](https://user-images.githubusercontent.com/32584280/44248416-3ff9af00-a19f-11e8-82e1-144b6e7e6435.PNG) There is a rarity, although there is not in the actual files.

**Comment by ZeldaZach** [comment]
That's a card example from SET.json, not AllCards

**Comment by Carkoth** [comment]
Oh, sorry

**Comment by Carkoth** [comment]
So, the array of rarities in AllSets coresponds with each card

**Comment by ZeldaZach** [comment]
In V4 this has changed, I believe rarity is in each card in AllSets. Feel free to check that out
