### ISSUE TITLE
Space at start of type field for a lot of cards

### ISSUE THREAD

**Issue by JoshuaLamusga** [mtgjson/mtgjson#611]
There is a space as the first character for the type field for Zombie Giant such that it reads:
"type": " Creature — Zombie Giant", for AllCards.json.

This is not local to the 'Zombie Giant' token. A lot of tokens have this issue. Easy enough to fix with search and replace.

**Comment by JoshuaLamusga** [comment]
This is not local to the 'Zombie Giant' token. A lot of tokens have this issue. Easy enough to fix with search and replace on `"type": " ` to `"type": "`

**Comment by ZeldaZach** [comment]
Addressed in V4
