### ISSUE TITLE
layout and names incorrect for Zndrsplt, Eye of Wisdom and Okaun, Eye of Chaos

### ISSUE THREAD

**Issue by bakert** [mtgjson/mtgjson#613]
Both have layout=flip incorrectly (probably because the rules text contains "flip a coin").

The order of names is wrong in that it is not consistent across both entries. For Zndrsplt's entry Okaun is listed first. And *vice versa*.

**Comment by fenhl** [comment]
Duplicate of #588 (layout) and #586 (names).

**Comment by bakert** [comment]
Oops, thanks.
