### ISSUE TITLE
Arena promos (pARL) release dates are wrong

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#614]
Definitely affects basics. [There were many releases over time](https://mtg.gamepedia.com/Arena_League_promos), but `pARL.json` lists them all as 1996-08-02, which was presumably when first one was released.

Or we could just do what scryfall does and have separate Arena sets per year. ([example](https://scryfall.com/sets/pal02))

Probably issue for mtgjson4.

**Comment by ZeldaZach** [comment]
Addressed in v4
