### ISSUE TITLE
Add "Augment" from Unstable to card keywords

### ISSUE THREAD

**Issue by mrphlip** [mtgjson/mtgjson#615]
I'm finding the `keywords` field on cards quite useful, but I'd find it helpful if the Augment keyword from Unstable could be added to the list.

The code I'm writing has special handling for host/augment cards, and currently the only way I can recognise a card with Augment is to search in the rules text and see if the ability is in there...

**Comment by ZeldaZach** [comment]
Added. Will be in tomorrow's full rebuild.
