### ISSUE TITLE
Inconsistent use of setcode "ALL"

### ISSUE THREAD

**Issue by 4zor4hai** [mtgjson/mtgjson#617]
Hi,

I want to thank you for the work you put in here. I use your .jsons to populate my database.
I'm now working on code that will parse the change log and identify the setcodes that have been updated. On the latest version (3.19.1) the full rebuild is completed, and the setcode is set to "ALL".
This of course would also imply the set "Alliances".

I just wan't to know if you will be consistent with the other code "ALL_OF_THEM" as seen used before, in the future?

Thanks again.

BRGDS
Espen A.

**Comment by ZeldaZach** [comment]
Hmm, that's weird.

I recommend you look into migration into our V4 of the client. We have new structures and better data reliance. Unfortunately there will be no more bug fixes to V3 as we're about to release V4. V3 will be depreciated at release, removed by end of year.

**Comment by ZeldaZach** [comment]
Hi @4zor4hai I looked further into this, and you are correct we updated our changelog incorrectly. In the future, it will list all sets (on v4). Thanks for using our software :)
