### ISSUE TITLE
Rin and Seri, Inseparable not present in AllPrintings file

### ISSUE THREAD

**Issue by carlol** [mtgjson/mtgjson#618]
#### Description of Bug:
Hi,

the card "Rin and Seri, Inseparable" doesn't seam to be present in the exported file AllPrintings, on the other hand I could find it in the M21 file in AllSets section.

It is a known issue?

Best Regards,

CL

**Comment by ZeldaZach** [comment]
Hey @carlol I just took at a look at AllPrintings for both v4 and v5, and I was able to find Rin and Seri in both AllPrintings files. Are you sure you digested the file correctly?
<img width="466" alt="Screenshot 2020-07-09 13 24 15" src="https://user-images.githubusercontent.com/7460172/87070926-80290700-c1e7-11ea-98c2-959f9ae9c442.png">

**Comment by ZeldaZach** [comment]
If you continue to have this issue, please let me know!
