### ISSUE TITLE
Same card, different mana cost

### ISSUE THREAD

**Issue by waho0ka** [mtgjson/mtgjson#618]
Hi,

There are six cards that have two different mana costs depending on what set you look at.  For example, Doran, the Siege Tower has the mana cost {B}{G}**{W}** in the Champs and States (pCMP) set but has the mana cost **{W}**{B}{G} in both From the Vault: Legends (V11) and Lorwyn (LRW).  All three printings actually display the mana cost as the former with {B} first, though Gatherer lists the mana cost field as the latter with {W} first.

This is a minor issue, but causes issues for me when flattening out the JSON into a list of unique cards.

The other cards affected:
Fungal Shambler:  {4}{G}{U}{B} vs {4}{B}{G}{U}
Karador, Ghost Chieftain:  {5}{B}{G}{W} vs {5}{W}{B}{G}
Oros, the Avenger:  {3}{W}{B}{R} vs {3}{R}{W}{B}
Riku of Two Reflections:  {2}{U}{R}{G} vs {2}{G}{U}{R}

Thanks,
Wahooka

**Comment by fenhl** [comment]
These cards have received errata so that the order or colors matches the one used for new cards starting with KTK. Some promo sets have not been updated properly since they're not on Gatherer.

**Comment by ZeldaZach** [comment]
This is fixed in V4.
