### ISSUE TITLE
Add types to EnumValues

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgjson#619]
I would like to move Card Types in the documentation to a strict data model. In order to do this I will need Enums for subtypes and supertypes like so:

`EnumValues.data.types.subTypes` `EnumValues.data.types.superTypes`

**Comment by ZeldaZach** [comment]
Not sure I understand what you're looking for here.

**Comment by staghouse** [comment]
I would like Enum values for subTypes and SuperTypes to be filled in to the EnumValues files in the structure above

**Comment by ZeldaZach** [comment]
Does `card.subtypes` and `card.supertypes` not do it for you?

**Comment by staghouse** [comment]
You bring up a good inspiration that we can probably add a new frontmatter variable to target repeatitive enums. Let me try that first.
