### ISSUE TITLE
AllPrices.json missing Online prices for [Meld,Flip,Transform] cards and possibly more.

### ISSUE THREAD

**Issue by eddie-g** [mtgjson/mtgjson#620]
AllPrices.json is missing data entirely for any Meld,flip or transform cards.

uuid: 3042d741-2594-57e5-a2b8-31a290600128
name : Homura, Human Ascendant // Homura's Essence
cardhoarder: https://www.cardhoarder.com/cards/22138/sok-homura-human-ascendant
**No price data**

uuid:5bb79a0f-ad7d-5383-8c9d-04bc757bcb4f
name: Gisela, the Broken Blade // Brisela, Voice of Nightmares
cardhoarder: https://www.cardhoarder.com/cards/66429/v17-gisela-the-broken-blade
**No Price Data**

uuid: 8c23c710-3169-5569-b5b4-08eebdab978a
name: Thing in the Ice // Awoken Horror
cardhoarder: https://www.cardhoarder.com/cards/59868/soi-thing-in-the-ice
**No Price Data**

There are hundreds of missing cards.

**Comment by ZeldaZach** [comment]
Can you please indicate if this is a v4, v5, or both issue?

**Comment by eddie-g** [comment]
> Can you please indicate if this is a v4, v5, or both issue?

This is with v5.
https://mtgjson.com/api/v5/AllPrices.json

**Comment by ZeldaZach** [comment]
A fix is building now and will deploy in the morning. b49b4c30eca88fa99b1bc9c2bd980ce5dd5bfaed

**Comment by eddie-g** [comment]
Issue still persists: Note

7a1aab33-99c6-5756-8f30-832f2e11bc67
Dark Depths / CSP
https://www.cardhoarder.com/cards/24583/csp-dark-depths
**No Online Price Data**

![image](https://user-images.githubusercontent.com/8391906/87237660-b10f6480-c3be-11ea-86ea-8fbd9a80565d.png)

**Comment by ZeldaZach** [comment]
I looked into it further and realized our upstream provider was missing MTGJSON ids for around 3000 cards. I've sent them an aggregated list with the correct IDs to associate, and am waiting for their adoption.

**Comment by ZeldaZach** [comment]
I put a temporary block of code in MTGJSON5 to account for these missing IDs for the time being. Waiting for upstream adoption still.

**Comment by ZeldaZach** [comment]
This has been addressed in full, and should be up now!
