### ISSUE TITLE
Cards missing from pHHO and ARC

### ISSUE THREAD

**Issue by Cerxi** [mtgjson/mtgjson#620]
It appears that pHHO and ARC are missing some cards!

pHHO is missing \#12 Naughty // Nice, \#16 Thopter Pie Network, and \#17 Some Disassembly Required

ARC (or perhaps a theoretical pARC?) is missing \#54 Plots that Span Centuries, \#55 Perhaps You've Met My Cohort, \#56 Your Inescapable Doom, \#57 Drench the Soil in their Blood, and \#58 Imprison this Insolent Wretch

There's also the HTR set, which appears to simply not exist at all

**Comment by tooomm** [comment]
Did these cards miss all the time? Or did it occur recently?

**Comment by ZeldaZach** [comment]
No fix in v3. Fixed in v4.
