### ISSUE TITLE
Overgrown Tomb and Temple Garden missing cipt

### ISSUE THREAD

**Issue by JineteDV** [mtgjson/mtgjson#624]
Ran oracle again to get a new xml today. Overgrown Tomb and Temple Garden are missing the <cipt>1</cipt> line in the xml file.

**Comment by ZeldaZach** [comment]
Did they have this in the past? I don't remember if shocks had this quality

**Comment by fenhl** [comment]
This sounds like a Cockatrice issue rather than an MTG JSON issue?

**Comment by JineteDV** [comment]
@ZeldaZach they did, all the other shocklands still cipt.

**Comment by ZeldaZach** [comment]
My initial review shows this is a Cockatrice issue. Please re-file there.
