### ISSUE TITLE
Zndrsplt & Okaun layout set to "flip"

### ISSUE THREAD

**Issue by BryGuy501** [mtgjson/mtgjson#625]
Zndrsplt, Eye of Wisdom and Okaun, Eye of Chaos from Battlebond are categorized a "flip" layout cards, but I believe they should be "normal". "Flip" is used for Kamigawa's flip mechanic cards like Jushi Apprentice, and the other "Partner" cards from Battlebond etc. are listed as "normal" layout.

**Comment by ZeldaZach** [comment]
Fixed in v4. No plans for fixes in v3 at this time
