### ISSUE TITLE
Bad character in the french translation of set with code RIX (aka Rivals of Ixalan)

### ISSUE THREAD

**Issue by lionelh** [mtgjson/mtgjson#626]
The french translation for 'Rivals of Ixalan' (SetCode = RIX) ends with '}' character which i think is an error.

**Comment by omfgitsmark** [comment]
https://github.com/mtgjson/mtgjson/blob/master/mtgjson5/resources/translation_overrides.json#L57

**Comment by lionelh** [comment]
The bad value is present in sqlite and JSON files so i believe that the mentioned file (translation_overrides.json) should be fixed.

**Comment by ZeldaZach** [comment]
This was fixed in #637
