### ISSUE TITLE
WCxx Signature

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#628]
World Championship Decks decks all have signature of the player who made them.

It would be nice to have this in data. It could arguably just go into `watermark` field.

Card number already includes player's initials, so it's very easy to do this.

**Comment by ZeldaZach** [comment]
I like the idea, will see what I come up with. Low priority right now, but it shouldn't take too long to brainstorm.

**Comment by kodawah** [comment]
I spoke with upstream, which is not too keen to reuse `watermark` for something that is not really a watermark (understandably)

They mentioned they might add a new category in the future when more deck sources are added, and this would be a good fit for it, so it's something on the radar now 👍

**Comment by staghouse** [comment]
Some ideas

`"isAutographed" -> Bool`
`"isSigned" -> Bool`
`"flourishes": [
  "autographed": Bool,
  ...
]`

**Comment by taw** [comment]
Other than signatures, are there any other card features not in mtgjson?
