### ISSUE TITLE
WCxx card numbers

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#629]
mtgjson WCxx sets use naming scheme of (player initials)(number)(`sb` if sideboard).

However, there are a few cases where this isn't followed.

This is not actually SB card:
* WC98 Cali Nightmare: ["Karplusan Forest bs356sb"]

These are actually SB cards:
* WC04 Blue-White Anti-Affinity Control: ["Pacifism gn33"]
* WC04 Green-White Astral Slide: ["Rude Awakening jn92", "Scrabbling Claws jn237"]

(sideboard cards have SB sticker on bottom right, so they're very easily verifiable, [mtg wiki for source](https://mtg.gamepedia.com/World_Championship_Decks))

As far as I can tell, these are the only cases.

**Comment by kodawah** [comment]
thanks, reported upstream, will update soon

**Comment by kodawah** [comment]
fixed upstream, the updated numbers should be present in the next build

ticket may be closed
