### ISSUE TITLE
erebus and other layout!=normal cards do not have the correct v4uuid in the db

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#630]
#### Version(s) affected
- [ ] MTGJSON 4
- [x] MTGJSON 5

#### Description of Bug
i might be doing something wrong, but `Elbrus, the Binding Blade` has `bcc0bed1-cce7-5a8b-86b5-5a9b9568fbcd`on the db file, and `718043c6-ccf8-549c-b3d8-822e531874c8` on the json file (this latter one is correct)

I noticed for a few other cards as well, but i lost the list, i'll submit it if you need it

**Comment by ZeldaZach** [comment]
The SQL is generated _from_ the JSON, so I'm not sure why they would be different. @omfgitsmark can you look into this please?

**Comment by ZeldaZach** [comment]
Just checked the v4 JSON. This looks correct to me. 
<img width="622" alt="Screen Shot 2020-07-25 at 5 49 39 PM" src="https://user-images.githubusercontent.com/7460172/88466922-4c183c00-ce9f-11ea-8f13-8a840a4fc383.png">

v5 JSON
<img width="690" alt="Screen Shot 2020-07-25 at 5 50 39 PM" src="https://user-images.githubusercontent.com/7460172/88466928-5f2b0c00-ce9f-11ea-9d49-b817bbe34241.png">

Can I get more info?

**Comment by ZeldaZach** [comment]
If you still have an issue, please let me know
