### ISSUE TITLE
"aftermath" card layout type is gone, now "split" type

### ISSUE THREAD

**Issue by wellawel** [mtgjson/mtgjson#630]
Cards such as Appeal//Authority are now (4.0.2) marked as layout "split", while in 3.x their layout was "aftermath". 

I guess this is a bug as the layouts are clearly different, compared to a card like Alive//Well

**Comment by fenhl** [comment]
I don't think this is a bug. Planeswalkers also have a layout that is clearly different from regular cards, but they're not marked specially. You can determine whether a split card has aftermath by parsing the text.

**Comment by wellawel** [comment]
Well then this is a regression. Split cards are displayed 90 degrees
rotated, aftermath cards you can read one half without rotation, the other
with rotation.  So the aftermath type is useful for displaying, and it was
available in 3.x before

**Comment by fenhl** [comment]
This is version 4. It's a breaking change.

**Comment by ZeldaZach** [comment]
Version 4 had a breaking change for this. This (the v3) repo is also not accepting new tickets, so closing

**Comment by wellawel** [comment]
Ah, didn't realize v4 is in a different repo, my bad! Thx
