### ISSUE TITLE
Atomic Cards missing uuid field

### ISSUE THREAD

**Issue by krijoh92** [mtgjson/mtgjson#631]
#### Version(s) affected
- [ ] MTGJSON 4
- [x] MTGJSON 5

#### Version(s) tested against
MTGJSON: 5.0.0+20200720

#### Description of Bug
Each card in AtomicCards.json is missing `uuid` field

**Comment by ZeldaZach** [comment]
Atomic Cards don’t get UUIDs as we don’t have a generation scheme for partial objects. One could say a UUID might be helpful, but it would have to come from an alternative scheme. 

I’m open to suggestions on how we can better serve our data, but UUIDs as we build them currently aren’t compatible with AtomicCards

**Comment by krijoh92** [comment]
Hmm, I admit I have no insight into how you build any of the data at the moment, so I don't have the ability to give any suggestions.

But if the absence of UUIDs for AtomicCards is a conscious decision I should probably create a PR for the documentation repo removing UUID from AtomicCards as a start, and later add it back if we can figure a way to give them UUIDs ? 

I'll see if I can make sense of how you're building the data and maybe I'll be able to figure out some solution :)

**Comment by ZeldaZach** [comment]
Yeah, AtomicCards shouldn't have a UUID in the docs. cc @staghouse  to address that, if necessary.

This ticket will be closed as the issue at hand is moot. You're more than welcomed to open a new ticket/pull request for additional discussions if you're interested, or to reopen this one if it's warranted.
