### ISSUE TITLE
Double faced tokens with same side value for both sides

### ISSUE THREAD

**Issue by krijoh92** [mtgjson/mtgjson#632]
#### Version(s) affected
- [ ] MTGJSON 4
- [x] MTGJSON 5

#### Version(s) tested against
MTGJSON 5.0.0+20200720

#### Description of Bug
I've found that tokens in Unstable (UST) have the same value for both sides (both are "a"), thus making them get the same uuid value.

**Comment by ZeldaZach** [comment]
Terribly sorry you ran across this issue! Will try to have this addressed before Monday's full rebuild :)
