### ISSUE TITLE
provide frequent xdelta patches to main downloadable files

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#634]
In addition to building the releases every week, it would be nice if we could have daily xdelta patches of the main text files (.json and .sql). In this way we could just download the main file and keep it updated!

I know not many details change every day, but especially during spoiler seasons, where the single set.json is provided, we could maybe expand support for users of the main file too

https://en.wikipedia.org/wiki/Xdelta

**Comment by ZeldaZach** [comment]
I _really_ like this idea, and it's somewhat feasible. I'm gonna loop in @omfgitsmark as this feels like a cool thing to try introducing to the build sequence.

Our first approach to this would be for only AllPrintings. This would give us a good focus on if this is feasible and how much effort it would take on our part. This would take place whenever a non-price build happens. When the build finishes, run a diff on backup/AllPrintings.json (which is saved on the  box) and new/AllPrintings.json. We would provide this as a patch on the website, with its own SHA256. If that test seems feasible, we can move towards creating an xdelta of backup/AllPrintings.sql and new/AllPrintings.sql.

For normal operations, I expect this to run weekly (as we build weekly right now), and we can run it against spoilers when those happen too.

**Comment by kodawah** [comment]
> For normal operations, I expect this to run weekly (as we build weekly right now), and we can run it against spoilers when those happen too.

In spoiler seasons you could also generate a new allprintings.json by loading the old one, reload and apply the new set.json and dump to file. Then run xdelta and provide the daily change from whichever reference

**Comment by jmcsmith** [comment]
I love the idea of being able to load my app one time and then keep it up to date with deltas. I don't use AllPrintings.json at this time for the initial load but for deltas that may be enough.
Please let me know if help is needed with testing consumption of the deltas.

edit: I think that deltas on the weekly runs and spoiler runs would be plenty.

**Comment by ZeldaZach** [comment]
It's been a number of years now, and I'm not sure if this is the right direction. Things are built more frequently nowadays (daily!), and there hasn't been much discussion here since. Moving to close for the time being.
