### ISSUE TITLE
Individual decks should not have releaseDate: null

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgjson#635]
We know this is how the app has worked for a while, however, can we not get every release date of every deck?

**Comment by ZeldaZach** [comment]
You didn't specify if this is a v4 and/or v5 issue. Please let me know when you do. Will look into it soon.

**Comment by staghouse** [comment]
V4 and v5

**Comment by ZeldaZach** [comment]
Tagging @taw  for more details

**Comment by taw** [comment]
Oops, I thought they'd be automatically flagged on my side.

That's the issue with newly added WCxx decks.

**Comment by taw** [comment]
It should be fixed now on my end.

**Comment by ZeldaZach** [comment]
Thanks for the prompt fix. Will be built on Monday.
