### ISSUE TITLE
Add List of Preconstructed Decks

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#64]
From https://en.wikipedia.org/wiki/List_of_Magic:_The_Gathering_theme_decks

https://github.com/mtgjson/mtgjson/issues/612

**Comment by fenhl** [comment]
We should probably be using [taw/magic-preconstructed-decks](https://github.com/taw/magic-preconstructed-decks), since it's more complete than the Wikipedia list.

**Comment by ZeldaZach** [comment]
SF plans on looking into this, so I'll mark it as upstream for now. Still can possibly go on my own to do this at some point

**Comment by ZeldaZach** [comment]
Started looking into this. Taw let me know that he plans on updating the service in January to better accommodate us, so I'll be holding off until then.

**Comment by magreenblatt** [comment]
Just to check, this will also include the quantity of each card in the deck list (keeping in mind that some decks also have alternate art cards)?

**Comment by magreenblatt** [comment]
Another complexity is constructed products that combine cards from multiple sets. For example, Starter 2000 box (which includes both 6ED and Starter 2000 cards) and Explorers of Ixalan (which includes both Ixalan and Explorers of Ixalan cards).
