### ISSUE TITLE
Remove dependency on MTGJSON UUID in Cardhoarder price file

### ISSUE THREAD

**Issue by cheyner** [mtgjson/mtgjson#640]
As discussed, we feel it best for mtgjson to no longer depend on the presence of its UUID in the Cardhoarder price file.  Instead, we'd ask that you find a way to map the MTGO ID on your end.  We'll continue to provide the mtgjson UUID in our file for the next 60 days to accommodate this transition.

**Comment by ZeldaZach** [comment]
This has been successfully addressed in v4 and v5
