### ISSUE TITLE
Potential Addition of TCGPlayer Buylist Data

### ISSUE THREAD

**Issue by tpblaster** [mtgjson/mtgjson#642]
Currently, only TCGPlayer retail data is pulled for the pricing file. Right now the TCGPlayer retail prices are found using group ids. Using the same data and the endpoint List Product Buylist Prices by Group buylist data could be grabbed. For cards with both foil and nonfoil the skus need to be parsed in order to get complete data. Each sku id refers to a specific version of a card like a near mint foil scalding tarn from modern masters 2017.

**Comment by ZeldaZach** [comment]
I like the idea of having buylist prices for TCGPlayer within the project! Our [Prices Object](https://github.com/mtgjson/mtgjson/blob/master/mtgjson5/classes/mtgjson_prices.py) already has the ability to store buylist and retaillist pricing.

If we're going to do this, I'd recommend only storing the NM pricing for buylist, as almost every other price is derived from it with a gradient chart.

**Comment by tpblaster** [comment]
Unfortunately, TCGPlayer buylist is one of the few buylists that doesn't use a gradient chart to derive lower condition prices. On the other hand, I do agree that only storing the near mint data makes sense

**Comment by ZeldaZach** [comment]
Fixed by #646 :D
