### ISSUE TITLE
Bad JSON format / AllPrices on some prices

### ISSUE THREAD

**Issue by JeromedC34** [mtgjson/mtgjson#649]
#### Version(s) affected
- [ ] MTGJSON 4
- [X ] MTGJSON 5

#### Version(s) tested against
MTGJSON 5.0.0+20200811

#### Description of Bug
In the AllPrices.json file, some prices are in double quotes.
For example in "data"/"395a846d-cafd-52e5-9f1e-53d1f12e5650"/"paper"/"cardkingdom"/"buylist"/"foil"/"2020-06-15" the price is "0.05" instead of 0.05, the other prices for other dates are OK.

**Comment by ZeldaZach** [comment]
I traced this back to an upstream error 3 months ago that wasn't caught until today. I have rectified the fix on my private prices repo, and will have them rebuilt for today. Thanks for letting me know of this!!
