### ISSUE TITLE
scryfallOracleId not in v5 AtomicCards

### ISSUE THREAD

**Issue by DanielMaly** [mtgjson/mtgjson#651]
We have been relying on the ouput of AllCards in v4 to get data about individual card faces, which we would then join with Scryfall data because it's more suitable for our purposes for information about individual printings.

Since v5, `scryfallOracleId` is gone from AtomicCards, making the entire data source useless. Is there any way to return `scryfallOracleId` to AtomicCards?

**Comment by ZeldaZach** [comment]
Hey @DanielMaly sorry you aren't satisfied with my data set as-is. I've pushed a change to include the scryfallOracleId entity (within identifiers) for the 5.0.1 release. 

If you're interested, I'd love to know your use case so I can help better adapt and enrich our data. You shouldn't have to go to multiple data providers for information. If there's something missing, I'd love to try and solve it.
