### ISSUE TITLE
Certain Sets missing from v4

### ISSUE THREAD

**Issue by florenceboettger** [mtgjson/mtgjson#654]
#### Version(s) affected
- [x] MTGJSON 4
- [ ] MTGJSON 5

#### Description of Bug

Certain sets, such as Theros Beyond Death, Scars of Mirrodin or Ixalan are missing from v4. Those sets, as well as all their individual cards, are missing from https://mtgjson.com/api/v4/AllPrintings.json.xz, whereas https://mtgjson.com/api/v5/AllPrintings.json.xz contains those sets. Similarily, the individual jsons for those sets are absent. For instance, https://mtgjson.com/api/v5/THB.json.xz gives the correct json, but https://mtgjson.com/api/v4/THB.json.xz is missing. Notably, this does not affect all sets, as https://mtgjson.com/api/v4/PTHB.json.xz works.

**Comment by ZeldaZach** [comment]
I had to do a hotfix on v4 last night. Rebuilding it in its entirety. Will close when reup'd

**Comment by ZeldaZach** [comment]
In the meantime, I rolled back v4's release from yesterday.
