### ISSUE TITLE
SetList.json 404

### ISSUE THREAD

**Issue by AxeBane** [mtgjson/mtgjson#657]
#### Version(s) affected
- [X] MTGJSON 5

#### Version(s) tested against
MTGJSON 5.0.0

#### Description of Bug
GET requests to https://mtgjson.com/api/v5/SetList.json reach a 404 page as of today's date.
Similar results have been found with directly accessing through the front-end web page.
This may not be limited to just SetList.json.

**Comment by ZeldaZach** [comment]
Looks to be my last build was killed by the OS. I reverted and this is handled. Will address the issue on my end today.
