### ISSUE TITLE
Salvat/Hachette are not recognized as expansions

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#66]
The various Salvat/Hachette expansions are not in the card file.

https://github.com/mtgjson/mtgjson/issues/478

**Comment by ZeldaZach** [comment]
Upstream issue, but I'm working with SF to get 2011 in place. We should have 2005 already in.

**Comment by ZeldaZach** [comment]
Should be good to go in 4.0.3 (next build)
