### ISSUE TITLE
Missing non-english card reprints from Portal set

### ISSUE THREAD

**Issue by JayDi85** [mtgjson/mtgjson#660]
#### Version(s) affected
- [ ] MTGJSON 4
- [x] MTGJSON 5

#### Version(s) tested against

Current website

#### Description of Bug
[Assassin's Blade from Portal](https://scryfall.com/search?q=Assassin%27s+Blade+set%3Apor&unique=cards&as=grid&order=name) on scryfall have 2 print versions (numbers 80 and 80a):
![shot_200821_203131](https://user-images.githubusercontent.com/8344157/90913456-57527f00-e3ed-11ea-8a1e-f6d270f1bd01.png)

BUT mtgjson contains only 1 print in [json set](https://mtgjson.com/api/v5/POR.json) and it ignore china only reprint. Another example [War of the Spark with japan only images](https://scryfall.com/search?order=set&q=set%3Awar+is%3Ajpwalker&unique=prints) contains all non-english reprints correctly in mtgjson.

**Comment by ZeldaZach** [comment]
Thanks for pointing this out. I need to figure out how to better integrate foreign-only printed cards... hmm

**Comment by JayDi85** [comment]
Example from scryfall api (request image without specific language param): if you try to get card without English version then it will return first available card.

So mtgjson can use same logic: sort available cards by language and put the first one to the list.

**Comment by ZeldaZach** [comment]
This has been addressed and all variants are now in the main file.
