### ISSUE TITLE
Meld cards gets composite name with meld's part but they must not

### ISSUE THREAD

**Issue by JayDi85** [mtgjson/mtgjson#661]
#### Version(s) affected
- [ ] MTGJSON 4
- [x] MTGJSON 5

#### Version(s) tested against

Current website

#### Description of Bug
* [Bruna, the Fading Light](https://scryfall.com/card/emn/15a/bruna-the-fading-light) from scryfall have simple name ([json](https://api.scryfall.com/cards/27907985-b5f6-4098-ab43-15a0c2bf94d5?format=json&pretty=true)): `Bruna, the Fading Light`

![shot_200822_182428](https://user-images.githubusercontent.com/8344157/90958325-ca6afc80-e4a4-11ea-8e40-5003865942ef.png)
* Same card from mtgjson have composite name in mtgjson: `Bruna, the Fading Light // Brisela, Voice of Nightmares` ([json](https://mtgjson.com/api/v5/EMN.json))

![shot_200822_182710](https://user-images.githubusercontent.com/8344157/90958377-22096800-e4a5-11ea-838a-6b41fc09ad1d.png)

I think it's incorrect logic for cards with `layout = meld`. So I recommends to use scryfall logic -- all meld cards uses simple name.

**Comment by ZeldaZach** [comment]
This was a design decision for MTGJSON5. We've heard arguments from both sides, and I worked with several folks to try and come up with the best approach. More info is on https://github.com/mtgjson/mtgjson/issues/616#issuecomment-655646281.

**Comment by JayDi85** [comment]
Correct link about names: https://github.com/mtgjson/mtgjson/issues/616#issuecomment-655648085
