### ISSUE TITLE
void beckoner "misprint" wrong tcgplayerid

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#663]
977d943c-8388-512b-9712-29fa7824713d (aka Void Beckoner, 373A) has the same tcgplayerid of 075b1f28-306b-5d5c-878b-599a2d037380 (aka Void Beckoner, 104) 

it seems that this bug is not present upstream

**Comment by ZeldaZach** [comment]
Can you check if this is still a problem?

**Comment by kodawah** [comment]
seems fine now 👍
