### ISSUE TITLE
Chinese 5ED, 6ED, and Portal cards marked as having foils

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#664]
Newly added Chinese special versions `/NUMs/` cards in:

* https://mtgjson.com/api/v5/POR.json
* https://mtgjson.com/api/v5/5ED.json
* https://mtgjson.com/api/v5/6ED.json

5ED, 6ED, and Portal predate foils.

(might be worth checking if any other sets are affected)

**Comment by ZeldaZach** [comment]
I'm looking at the [Magic Library](http://www.magiclibrarities.net/332-rarities-simplified-chinese-alternate-art-cards-simplified-chinese-cards-index.html), but it doesn't mention anything about these cards being in foil. Maybe you can lend a hand @csuhta ?

**Comment by csuhta** [comment]
Corrected on Scryfall!
