### ISSUE TITLE
A lot of links on https://mtgjson.com/downloads/all-decks/ don't work

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#665]
Seems like it affects ones with special characters like "Above the Clouds (1)" goes to https://mtgjson.com/api/v5/decks/AboveTheClouds1_JMP.json, which 404s.

**Comment by ZeldaZach** [comment]
Well that's a problem. Thanks for pointing it out. I'm gonna see what I can do.

**Comment by ZeldaZach** [comment]
I can't seem to reproduce this. Looking at the latest release, I see that URL working as expected. Can you confirm and close?

**Comment by taw** [comment]
Yeah, looks like it's working now.
