### ISSUE TITLE
Precon data schema updated

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#666]
Data files got updated https://github.com/taw/magic-preconstructed-decks-data

Old schema - `decks.json`

New schema - `decks_v2.json`

Changes:

* `commander` is now separate from `sideboard` (applies to `decks_v2.json` only).
* every card has `mtgjson_uuid` so complex matching system should not be necessary (applied to both) - this is backwards compatible, as you can ignore this and match the old way, but it will simplify your life to just use it. Every card should have it.

Please switch to new schema on next mtgjson version update.

**Comment by ZeldaZach** [comment]
I'll get to this when I can, will be before our next release
