### ISSUE TITLE
compile a new file for tcg skus

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#668]
So i was thinking of a way to integrate @tpblaster's changes from https://github.com/mtgjson/mtgjson/pull/644

If we want to avoid including vendor-specific information in the main files, maybe we could shove vendor specific data in a separate file. I'd design AllTCGSkus.json like AllIdentifiers, so a map of uuids pointing to the map of sku and product id

The only question is if we need to something similar for mkm too

**Comment by ZeldaZach** [comment]
Love the idea, and we have a PR up. I need to scope through it a bit more, but we'll have this done soon.

**Comment by ZeldaZach** [comment]
Fixed by #670. Thanks @tpblaster

**Comment by kodawah** [comment]
s/#644/#670/
