### ISSUE TITLE
open spoiler season endpoint

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#669]
it would be nice to have an endpoint to notify that magic is in spoiler season, and thus we should update mtgjson daily instead of weekly. Not sure if it's better a simple true/false function or if there could be more data attached to it (set code, planned releas date etc)

alternatively with so many products coming out we could use a similar endpoint to know if we're /not/ in spoiler season :joy:

**Comment by ZeldaZach** [comment]
I think this might be out of scope for the project. People can easily poll our SetList.json and see if isPartialPreview is found and that should most likely indicate if we're in preview season.

**Comment by kodawah** [comment]
well as of right now, we can just download allprintings every day. The goal of this feature request would be to avoid making pointless downloads, not causing an additional one :-)

maybe it's something that can be ignored once addressed with xdelta support

**Comment by staghouse** [comment]
Wouldn't using the sha256 files circumvent this or am I missing something?

**Comment by ZeldaZach** [comment]
We've (for the most part) migrated to daily builds. So this is a bit moot.
