### ISSUE TITLE
Archenemy Promotional Schemes Missing

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#67]
Promotional Archenemy Schemes are missing:

Perhaps you have met my Cohort
Plot that spans Centuries
Your inescapable Doom
Imprision this Insolent Witch
Drench the Soil in their Blood

https://github.com/mtgjson/mtgjson/issues/476

**Comment by ZeldaZach** [comment]
I don't know if we have archenemy in the current release. Can you check and confirm this is still an issue?

**Comment by KingSupernova31** [comment]
You're right, vanguards, planes, schemes, etc are all not included in v4, so this is moot until they're added.
