### ISSUE TITLE
Incorrect Foreign Data for 3ED Goblin King

### ISSUE THREAD

**Issue by tpblaster** [mtgjson/mtgjson#672]
#### Version(s) affected
- [ ] MTGJSON 5

#### Version(s) tested against
- MTGJSON 5.0.1

#### Description of Bug
UUID: e3094187-d666-414b-a1fd-ae0ef55c3fcb refers to 3ED Goblin King. When checking how the data is referred to in Foreign Data, there are 3 entries for that UUID when Revised only has an English version. I think this is a bug that is mapping some FBB foreign data to Revised cards. This may be an upstream issue as Scryfall also has the foreign versions listed on the Revised card page for Goblin King.

**Comment by ZeldaZach** [comment]
I'm looking at all of Revised and they all have 3 entries. Can you confirm Revised was English only, as upstream sources have them in several languages?
