### ISSUE TITLE
simplified chinese old variants have empty ForeignData and no IsAlternative

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#675]
A few cards like Assasin's Blade from Portal or Charcoal DIamond from 7th Edition have different art in Simplified Chinese.

However it's not possible to programmatically tell these apart from their English counterpart: they would need isAlternative set and possibly foreignData too. Unfortunately only checking for foreignData empty leads to false positives, as a lot of cards in the Promos department have this field empty too.

**Comment by ZeldaZach** [comment]
Looking upstream, they seem to indicate the artworks are the same via oracle_id.

Assassin's Blade:
EN: https://api.scryfall.com/cards/b80e8fe0-eccb-4268-a6ce-1365c68e6b13?format=json&pretty=true
CS: https://api.scryfall.com/cards/235f25bf-e079-4957-bbb1-0f90716275ad?format=json&pretty=true

cc: @csuhta 

We might want to add an oracleID field to each foreignData entry point if the art differs from the main version.

**Comment by csuhta** [comment]
We indicate that they have distinct artwork with the `illustration_id` field. If the UUIDs there match, the cards have the same art.

**Comment by ZeldaZach** [comment]
Ahh, my bad. Sorry for the rogue ping. Will think about fixes on my end.

**Comment by kodawah** [comment]
upstream has added the `schinesealtart` promo type, so we can close this bug
