### ISSUE TITLE
2xm boosterfun cards are tagged as isAlternative

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#676]
related to #652

it looks like all the box topper cards got tagged as isalternative but they shouldn't get that flag as they already have properties that tell them apart from normal variants

**Comment by ZeldaZach** [comment]
Not sure if there's an easy enough way to distinguish them. They're technically alternatives, right?

**Comment by kodawah** [comment]
no, they are promos/variants, but not alternatives

you could maybe prune them out if they have a particular promotype set

**Comment by ZeldaZach** [comment]
After reviewing the case, I believe this is correct as-is. Alternatives gets tagged to all cards nowadays that aren't in the "base set" which is defined (for newer sets) by the card being <= the baseSetSize.

If this is incorrect assumption, maybe there are other issues of a similar vein we need to tackle.

**Comment by kodawah** [comment]
> Alternatives gets tagged to all cards nowadays that aren't in the "base set" which is defined (for newer sets) by the card being <= the baseSetSize.

I think you mean `>=`, right?

> If this is incorrect assumption, maybe there are other issues of a similar vein we need to tackle.

I believe that is incorrect, all the "booster fun" cards from newer sets are /not/ tagged isAlternative and that is correct. Case in point `The Great Henge` 361, or if you need a borderless version (like the 2xm box toppers) see `Alrund's Epiphany` 295: neither of these are tagged as isAlternative afaik, and that is correct.

2xm is the only set where this does not happen so I think it's a bug.
