### ISSUE TITLE
isStarter and isAlternative confusion

### ISSUE THREAD

**Issue by ebbit1q** [mtgjson/mtgjson#679]
The latest reprint for Lotus Cobra has a "showcase" version with number 307 instead of 193 that is marked as isStarter but not as isAlternative, while the normal frame version has neither of these tags. Could the function of these two tags be clarified?

**Comment by kodawah** [comment]
`isAlternative` is only when there aren't alternative ways of determining card difference (ie kaya from conspiracy) - lotus cobra has `promo_types` and `frame_effects` that you can check to tell them apart

as for `isStarter`... KIWF

**Comment by ebbit1q** [comment]
https://mtgjson.com/data-models/card/#isAlternative states that the card simply has a variation on its original, checking the list of frame effects for ones you consider alternative and which are from an original printing (say devoid cards) does not seem like a good solution. The card does not have promotypes set at all.

**Comment by kodawah** [comment]
yes it's a variation, and documentation should be probably improved. Sorry, I don't understand how devoid is related to this question, can you pleaseelaborate?

For the case at hand it is very possible that the mtgjson version you downloaded didn't have yet all the fields initialized, given it's a recent preview card. Today's mtgjson version has everything you need

```
          "name": "Lotus Cobra",
          "number": "307",
          "frameEffects": [
            "showcase"
          ],
          "promoTypes": [
            "boosterfun"
          ],
```

**Comment by ebbit1q** [comment]
devoid cards also have a frameEffects but are not alternatives

**Comment by kodawah** [comment]
of course, but they also do not have any other printing than the one with the frameeffects, so there is nothing to differentiate from

**Comment by ebbit1q** [comment]
that's the entire point....

**Comment by kodawah** [comment]
I guess we're talking about different things then, let's start over.

`isAlternative` is set when you can't differentiate with the usual ways (promotypes, frameEffects, borderColor etc). For conspiracy and battlebond, this usually corresponds to cards having the same name but different illustrationId. For more recent sets (in particular promotypes==boosterfun) the illustrationId restriction does not apply but the same concept is still valid.

`isStarter` should be dropped entirely

is there anything unclear, besides documentation that needs some updating (cc @omfgitsmark / @staghouse)?

**Comment by ebbit1q** [comment]
Let's show a simple usecase:
We want to have a list of all of the normal printings of a card in a set for every set. Now the simple way would be to have a single attribute saying which card is the normal printing. isAlternative missing would indicate the card being the normal/primary printing.
Instead of this we would have to check every single attribute to see which ones are different between the two and guess which one seems more "normal". This seems rather inconvenient so I propose the function of isAlternative to be the same as the documentation suggests.

**Comment by staghouse** [comment]
Is there any documentation wordage updates I can make in relation to this ticket?

**Comment by ebbit1q** [comment]
no, I believe isAlternative should be changed to function like is described in the documentation instead. cards like lotus cobra that are a second printing with different art should be marked isAlternative instead of needing to compare their frameEffects. currently the workaround is to give precedence to the card with the lower collector number.

**Comment by ZeldaZach** [comment]
Will be deprecating isStarter, as it's just confusing. I will look at adopting Booster instead, as that's more useful anyway.
