### ISSUE TITLE
Add promo rarities

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#68]
Should "promo" be allowed as a possible value for rarity?

https://github.com/mtgjson/mtgjson/issues/462

**Comment by ZeldaZach** [comment]
It would be too much of a hassle imo to do this manually

**Comment by fenhl** [comment]
We should keep this issue open since there might be a way to automate this or someone willing to do the work manually.

**Comment by ZeldaZach** [comment]
I don't expect anyone to step up for such a minuscule thing... If something pops up we can revisit this
