### ISSUE TITLE
Chinese USG cards marked as having foils 

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#680]
https://mtgjson.com/api/v5/USG.json

I missed one in https://github.com/mtgjson/mtgjson/issues/664 - I think it's the last one now.

The thing that confused me is that USG was the first set with foils - but that was only a single card prerelease promo Lighting Dragon. (mtgjson lists it as PPRE/4, not as part of USG set). There were no in-booster foil cards.

Those 6 Chinese alt art cards in USG have no foils, and are wrongly marked as `"hasFoil": true`, hey should be `"hasFoil": false`.

**Comment by ZeldaZach** [comment]
cc @csuhta

**Comment by ZeldaZach** [comment]
This appears fixed
