### ISSUE TITLE
Broken decks (Cavalcade Charge)

### ISSUE THREAD

**Issue by JayDi85** [mtgjson/mtgjson#682]
#### Version(s) affected
- MTGJSON 5

#### Version(s) tested against

Current website

#### Description of Bug
Some decks can be broken (e.g. contains wrong cards amount or duplicated data). 

As example: Cavalcade Charge ([mtgjson](https://mtgjson.com/api/v5/decks/CavalcadeCharge_THB.json), [other](https://www.mtggoldfish.com/deck/2772612#online)) -- it contains duplicated records of `Bonecrusher Giant // Stomp` (each record with 4 cards). Maybe it's a broken deck import or broken original deck source. 

I don't check another decks but it can contains same problems. Possible solution: add additional check with cards count in main deck (e.g. it must be 40, 60, 100 cards size).

**Comment by ZeldaZach** [comment]
Looking further into this, it appears "correct" as-is, even if it's not the intended result. If you take a look at the data block, there are 4 copies of "Bonecrusher Giant" and 4 copies of "Stomp", as the faceNames are different. This does feel unintuitive, so maybe we can set the count to 0 for the back sides of split-like cards? Or maybe you have a proposed solution on how we can better provide this data indicating we have flip cards

**Comment by JayDi85** [comment]
Each deck's record must be one card with amount. Same as one line from standard text deck. With face cards only. So your deck file must have same structure as text deck but with full cards info.

**Comment by JayDi85** [comment]
If you want to add full faces info to json then look at scryfall data format. It contains additional faces or parts list with full info. One json object equal one printed card.

**Comment by ZeldaZach** [comment]
I believe this was fixed by #708
