### ISSUE TITLE
add .originalReleaseDate to CardObject

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#683]
Sometimes cards are added at a different point in time than the set.ReleaseDate, however this information is lost in the pulling data from upstream. It's important to keep this information if we want to sort cards and sets by release date

**Comment by ZeldaZach** [comment]
Can you provide a few examples so I can test against this?

**Comment by kodawah** [comment]
PWOR is the simplest set to test, since you'll notice the date on crucible but not on horde, then any other Promos sets is game
