### ISSUE TITLE
foreign data for cards missing in AtomicCards.json

### ISSUE THREAD

**Issue by joriki** [mtgjson/mtgjson#684]
The foreign data for German (and other languages) is missing in AtomicCards.json for the following cards:

Ezuri's Archers: Ezuris Bogenschützen
Copperhorn Scout: Kupferhornspäher
Kiln Fiend:  Meiler-Unhold
Act of Heroism: Heldentat
Grotesque Mutation: Groteske Mutation
Tumble Magnet: Magnet des Taumelns

These cards have two different Scryfall pages; one includes only the English, Japanese and Simplified Chinese versions, whereas the other also includes versions in other languages (including German), for instance:

https://scryfall.com/card/ima/137/kiln-fiend
https://scryfall.com/card/roe/153/kiln-fiend

AtomicCards.json only reflects the data on the first of these pages.

**Comment by ZeldaZach** [comment]
AtomicCards needs better handling of foreign data, and not selecting on a primary basis. This is indeed a bug.
