### ISSUE TITLE
Modal DFC's back cmc is wrong for every card

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#688]
Affects https://mtgjson.com/api/v5/ZNR.json (and future sets to come)

[They changed the rules again](https://magic.wizards.com/en/articles/archive/news/comprehensive-rules-changes-2020-09-22):

> _Some tweaks to these rules that explain how the converted mana cost of a double-faced permanent is calculated. It used to be that a double-faced permanent with its back face up used the mana cost of the front face to determine its converted mana cost. Now that's true of transforming double-faced permanents only. The converted mana cost of a modal double-faced permanent is determined using the mana cost of the face that's up._

So:

* originally each face used own cmc
* then they chaged it so both faces use front's cmc
* now they changed it again, so non-modal DFCs use front face for cmc of both , modal DFCs use own cmc

mtgjson follows old rules, and has wrong entries like:

```
        "convertedManaCost": 7, // should be 0 etc.
        "faceName": "Turntimber, Serpentine Wood",
```

**Comment by KingSupernova31** [comment]
Any update on this? It should be an easy fix, just check the layout and calculate the CMC based on that face's mana cost if it's an MDFC.

Also worth noting that this wasn't actually a rule change, MDFCs are a completely new thing, so it was just a rule addition in order to support them at all.

**Comment by ZeldaZach** [comment]
This was fixed a while ago, guess I missed tagging this ticket.
