### ISSUE TITLE
Runtime Warning from incompatible Gevent version

### ISSUE THREAD

**Issue by 0az** [mtgjson/mtgjson#689]
#### Version(s) affected
- [ ] MTGJSON 4
- [X] MTGJSON 5

#### Version(s) tested against
5.0.1-4-g64e4e0a

#### Description of Bug

mtgjson5 exits with SIGSEV when started with Python 3.8.
```
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
```

```dockerfile
FROM python:3.8.5-buster

WORKDIR /app

ADD \
	requirements.txt \
	/app/
RUN pip install -r requirements.txt

ADD \
	MANIFEST.in \
	README.md \
	setup.py \
	/app/
ADD \
	mtgjson5/ \
	/app/mtgjson5
RUN pip install -e .

ENTRYPOINT ["python", "-m", "mtgjson5"]
```

**Comment by 0az** [comment]
See: https://github.com/python-greenlet/greenlet/issues/178

Fixing this also means dropping support for 3.6.

**Comment by jamadden** [comment]
Why would this mean dropping support for Python 3.6? gevent 20.9 supports the same versions of Python as gevent 20.6.x did, and the same goes for greenlet 0.4.17 and 0.4.16.

**Comment by ZeldaZach** [comment]
My goal is to support py 3.6 still, which is why I'm not overly happy with the fix. Will do some testing on the latest version in a few days to see what happens on 3.6

**Comment by ZeldaZach** [comment]
Should be addressed now
