### ISSUE TITLE
Add FBB and FWB

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#69]
Add Foreign Black Bordered and Foreign White Bordered sets.

https://github.com/mtgjson/mtgjson/issues/439

**Comment by ZeldaZach** [comment]
Not sure what this really means...

**Comment by KingSupernova31** [comment]
Each printing of Revised and 4th Edition in a foreign language was technically a different set. Same for Italian Legends. I think it's fine to treat them as the same set, but the foreign text at least needs to be added. (For example, Legends cards don't have their Italian translation in the foreignText field.)

**Comment by lfgcampos** [comment]
This is indeed important since the price difference from 4th FWB and FBB is huge and make sense to have it as 2 different sets IMO.

**Comment by ZeldaZach** [comment]
Update: SF just released FBB at https://scryfall.com/sets/fbb?order=set

Waiting on FWB to close ticket, but I will build FBB in the next few days or so and get it up (This will include a rebuild of AllCards/AllSets too. Will be an increment in version)

**Comment by ZeldaZach** [comment]
Will be added on 4.0.3 (next build)
