### ISSUE TITLE
Replace the multiverseid items in the 'variations' field with 'id'

### ISSUE THREAD

**Issue by Sembiance** [mtgjson/mtgjson#69]
The 'variations' field currently uses multiverseid's to point to other cards, but this doesn't work for sets that are not on gatherer but still have alternate art cards.

Sets that are currently missing 'variations' but should have some: DKM, DPA, CST, CED, CEI and several of the promo sets.

I should update the field to use the newly introduced 'id' field instead of multiverseid.

**Comment by ZeldaZach** [comment]
We discarded variations in V4. Not sure if that's correct or not, but we did. Can re-open there if it's an issue

**Comment by ZeldaZach** [comment]
Incorrect linking: We discarded the `variations` field, which was set if the card had multiple artworks in a single set. Variations of cards, like from unstable, are all in there

**Comment by tooomm** [comment]
>Incorrect linking

True. My bad! This is indeed confusing.

>We discarded the `variations` field, which was set if the card had multiple artworks in a single set. Variations of cards, like from unstable, are all in there

Well, in unstable, there are cards with multiple artworks as well. ;)
https://scryfall.com/card/ust/98a/target-minotaur
