### ISSUE TITLE
Typos in two cards

### ISSUE THREAD

**Issue by DJCatBlitz** [mtgjson/mtgjson#691]
Text of 

Kabira Outrider:
When Kabria Outrider enters the battlefield, ...
->
When Kabira Outrider enters the battlefield, 

Obuun, Mul Daya Ancestor
Landfall - Whenever land enters the battlefield ...
->
Landfall - Whenever a land enters the battlefield

**Comment by kodawah** [comment]
reported upstream, thanks

**Comment by kodawah** [comment]
this should be fixed in today's release
