### ISSUE TITLE
Add more data from Set to SetList / Include Identifiers

### ISSUE THREAD

**Issue by KMB** [mtgjson/mtgjson#694]
Hello

Two suggestions:

a)
I was surprised by the lack of information (or at least the difference in information) when comparing Set with SetList. I would have expected SetList to be all the data that is in Set minus cards and tokens.

In order to get a list of sets including the translated information I would need to parse the AllPrintings file, which seems over the top.

My suggestion is to add the data that is available in Set to the SetList excluding cards and tokens.

b)
My second suggestion is about the external information within the Set model. Here I propose a model similar to the Identifiers model that Cards uses. It could hold all the external information like mcmId, mcmName, etc. I would also like to see the scryfallUuid for the set there.

Referring to https://github.com/mtgjson/mtgjson/issues/651 I get where you are coming from, but unless Mtgjson starts offering images there will always be an overlap and a need to connect both services. There are other small differences in both data-sets (Scryfall's lack of translated set names for example) as well as the data-quality (e.g: Charix from the Bundle is missing in PZNR here on Mtgjson) so there isn't really a one size fits all solution. That would be great because then I wouldn't have to program two imports, which have to be matched... :-)

Regards
KMB

**Comment by staghouse** [comment]
For context, SetList was originally created as an internal desire to populate documentation pages and download files, which is why it is pretty bare.
