### ISSUE TITLE
ZNC foiling

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#697]
Not totally sure if it's a bug, as there are too many booster types to keep track of.

Anyway, https://mtgjson.com/api/v5/ZNC.json has everything marked as `"hasFoil": true`, implying ZNC cards are available as foil somewhere else in some weird booster type.

https://mtgjson.com/api/v5/C20.json does not.

Did something change between IKO/C20 and ZNR/ZNC, or is this a bug?

**Comment by ZeldaZach** [comment]
Yeah that looks off to me. cc @csuhta
