### ISSUE TITLE
INV Urborg Skeleton foiling

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#698]
https://mtgjson.com/api/v5/INV.json

Chinese alt art Urborg Skeleton (134s) is marked as nonfoil-only.

Invasion had regular foils of all cards in boosters, so I believe this is incorrect, and it should have same foiling (both foil and nonfoil available) as all other cards in the set.

**Comment by ZeldaZach** [comment]
cc: @csuhta

**Comment by csuhta** [comment]
Fixed on Scryfall
