### ISSUE TITLE
Randomly gets stuck

### ISSUE THREAD

**Issue by AridTag** [mtgjson/mtgjson#7]
Known issue where it will just seemingly get stuck processing a set

**Comment by ZeldaZach** [comment]
I assume this is something to do with the synchronization of the project. There's probably a race time condition that causes a deadlock. 

cc: @fenhl

**Comment by silasary** [comment]
I'm assuming this is when running `--all-sets`, and on windows?

It is almost certainly getting stuck specifically on Conflux.

**Comment by ZeldaZach** [comment]
I'm on Mac and I still get stuck so that's not the issue, at least on my end

**Comment by ZeldaZach** [comment]
https://gist.github.com/ZeldaZach/852af2d2f716946304f3f550a72c1c09
