### ISSUE TITLE
Cards with alternate art have duplicate foreignNames entries

### ISSUE THREAD

**Issue by Sembiance** [mtgjson/mtgjson#70]
Cards that have alternate art within the same set (such as basic lands in most sets) have duplicate foreignName entries, one for each alternate art.

Ideally the only foreignName entry should be the one that matches the artwork of that card.

This is trickier said than done as the ordering of the alternate art can vary in different ways and took effort to get correct for the regular 'variations' field. A similar or more amount of effort needs to be done here to ensure the foreignName version is the same artwork as the card entry.

**Comment by Sembiance** [comment]
This was reported in Issue #12 with the following example:
```
      "foreignNames": [
        {
          "language": "Chinese Traditional",
          "name": "平原",
          "multiverseid": "399229"
        },
        {
          "language": "Chinese Traditional",
          "name": "平原",
          "multiverseid": "399088"
        },
        {
          "language": "Chinese Traditional",
          "name": "平原",
          "multiverseid": "399095"
        },
        {
          "language": "Chinese Traditional",
          "name": "平原",
          "multiverseid": "399104"
        },
```

**Comment by ZeldaZach** [comment]
Not an issue in V4 anymore
