### ISSUE TITLE
[Card Object] otherFaceParts, for collecting consistent UUID order for meld cards

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgjson#705]
The problem im facing with meld cards is that as each card changes, there can either be 1 or 2 uuids, which can make logic funky and hard to work with when figuring out what the next card should (image some type of function where you are cycling through the parts.)

Something helpful would be a `otherFaceParts` that is a list of each part of the card, in a logical order, including its own id and would be consistent across all 3 cards. For example:

```
// card 1
{
  ...,
  otherFaceParts: [
    card1UUID,
    card2UUID,
    card3UUID
  ],
  ...
}
// card 2
{
  ...,
  otherFaceParts: [
    card1UUID,
    card2UUID,
    card3UUID
  ],
  ...
}
// card 3 (melded)
{
  ...,
  otherFaceParts: [
    card1UUID,
    card2UUID,
    card3UUID
  ],
  ...
}```

**Comment by Palladinium** [comment]
v4 used to work similarly to what you propose - meld cards had a `names` array that AFAIK was always in the order `[front_1, back, front_2]`, it included the current card, and was identical in all three cards.

As a workaround for v5, I've had luck with this method (pseudocode):

```
function find_cards(ids, side) {
  // This function returns all cards in the same set whose uuid is in ids, and whose side is side
}

// Returns the meld face cards in the order [front_1, front_2, back]
function get_meld_faces(card) {
  if(card['side'] == 'a') {
    back = find_cards(card['otherFaceIds'], 'b')[0]
  } else if(card['side'] == 'b') {
    back = card;
  }

  fronts = find_cards(back['otherFaceIds'], 'a')
  fronts.sort_by('number'); // or 'multiverseId', or any other field that'll stay consistent

  return [fronts[0], fronts[1], back];
}
```

**Comment by staghouse** [comment]
Thanks, im doing something similar myself as a workaround.

**Comment by ZeldaZach** [comment]
Priority raised by Mythic Patron request
