### ISSUE TITLE
Modern Horizons Art Series cards don't have "side" set properly

### ISSUE THREAD

**Issue by MidnightLightning** [mtgjson/mtgjson#709]
All cards in the "Modern Horizons Art Series" are classified as `tokens` and have `layout` set to `art_series` (which are correct), however, all the tokens in the data file have `side` set to `a`, and none of them have `reverseRelated` values set.

So, as-is, there's no way to differentiate the "front" from the "back" for those tokens in the MTJSON data set: both have the `faceName` of the related MTG card, and both have the `name` set to the `faceName` doubled up with a  ` // ` delimiter.

These should be updated to set the "back" side to have a `side` of `b` (to follow the pattern of "Transform" cards), and the `reverseRelated` values of the individual faces reference each other.

**Comment by Palladinium** [comment]
The same problem occurs with:
- Tokens in the "Zendikar Rising Art Series" (AZNR) set, whose layout is also `art_series`
- Tokens in the "Zendikar Rising Minigames" (MZNR) set, whose layout is `double_faced_token` (which is correct)

### Tested with
v5.0.1
Downloaded from https://www.mtgjson.com/api/v5/AllPrintings.json on Dec 7th, 2020
sha256: 2a64648632f787e5526aef65d1e2902e6fd314c152d29de37515c6221fe32400

**Comment by ZeldaZach** [comment]
Raising to High Priority
