### ISSUE TITLE
Create a JSON schema for the files

### ISSUE THREAD

**Issue by Sembiance** [mtgjson/mtgjson#71]
It would be nice to provide a JSON schema (http://json-schema.org/) for the MTGJSON files. This will add another layer of testing before publishing and also would ease importing the data into databases.

**Comment by FrancescoRizzi** [comment]
+1

**Comment by CaptainMan** [comment]
@lsmoura Is this currently being worked on? If not I could take a crack.

**Comment by lsmoura** [comment]
Not right now. I'm working on some other things, then OGW release, then tokens. If you want to try something out, I'd appreciate it!

**Comment by CaptainMan** [comment]
I've never made a json schema, but it looks similar enough to xsd which I have some experience with.

I was thinking 5 schemas, 1 for each file (last I checked there were 4) and 1 for common definitions.

**Comment by jonahgeorge** [comment]
Regarding a standardized schema, I'd like to voice an opinion about the `booster` field for sets. 

Currently this is an array of elements of either type `String` or `Array(String)`. This makes marshaling into a typed language more difficult than it needs to be- evident in the `Rarity` functions in the [Go Client](https://github.com/lsmoura/mtgjson/blob/a497b067d10473b20533796d899c70845a54a99f/sample/go/mtgjson.go#L12-L53). If a schema is to be defined, could this field be only of type `Array(String)` and represent the `1 rare or mythic rare` cards with a pipe? Example below.

Before:
```json
"ZEN": {
    "name": "Zendikar",
    "code": "ZEN",
    "magicCardsInfoCode": "zen",
    "releaseDate": "2009-10-02",
    "border": "black",
    "type": "expansion",
    "block": "Zendikar",
    "booster": [
      [
        "rare",
        "mythic rare"
      ],
      "uncommon",
      "uncommon",
      "uncommon",
      "common",
      "common",
      "common",
      "common",
      "common",
      "common",
      "common",
      "common",
      "common",
      "common",
      "land",
      "marketing"
    ]
}
```
After:
```json
"ZEN": {
    "name": "Zendikar",
    "code": "ZEN",
    "magicCardsInfoCode": "zen",
    "releaseDate": "2009-10-02",
    "border": "black",
    "type": "expansion",
    "block": "Zendikar",
    "booster": [
      "rare|mythic rare",
      "uncommon",
      "uncommon",
      "uncommon",
      "common",
      "common",
      "common",
      "common",
      "common",
      "common",
      "common",
      "common",
      "common",
      "common",
      "land",
      "marketing"
    ]
}
```
