### ISSUE TITLE
Some cards with multiple versions aren't included.

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#71]
Some cards with multiple versions aren't included, such as the Tamiyo's Journals with different flavor text.

https://github.com/mtgjson/mtgjson/issues/410

**Comment by ZeldaZach** [comment]
So there's really no good solution to this. The _only_ impacted card is Tamiyo's journal, and the difference is only flavortext. Imo, I don't recommend a fix as it wouldn't make sense to anybody...

**Comment by KingSupernova31** [comment]
Other cards with different versions are supported though, such as the different guildgates from Guilds of Ravnica and the Unstable variants.

**Comment by ZeldaZach** [comment]
So Tamiyo's Journal is the _only_ card that has this issue... I don't think it's worth the issue ticket tbh

~~_EDIT_ Maybe some cards from the recent un-set have this issue too?~~

**Comment by tooomm** [comment]
Do we keep a list of known issues then somewhere?
