### ISSUE TITLE
Missing CORS header in /api/v5/CON.json.sha256 and /api/v5/CON.json response

### ISSUE THREAD

**Issue by PierreJeanjacquot** [mtgjson/mtgjson#711]
#### Version(s) affected
- [ ] MTGJSON 4
- [X] MTGJSON 5

#### Version(s) tested against
MTGJSON 5.0.1+20201102

#### Description of Bug
When hitting https://mtgjson.com/api/v5/CON.json.sha256 and https://mtgjson.com/api/v5/CON.json the HttpResponse doesn't contain header `Access-Control-Allow-Origin: *`
This prevents fetch request to complete and to perform the redirection to the permanently moved resource new location.

#### To reproduce:
Open the browser's console and execute the following script:
```js
(async () => {
  try {
    const resonse = await fetch("https://mtgjson.com/api/v5/CON.json")
    console.log("OK got response:", resonse.status)
  } catch (e) {
    console.log("Error:", e)
  }
})()
```

**Comment by ZeldaZach** [comment]
Thanks for the alert. I've fixed this up! Had a bad Nginx rewrite rule :)
