### ISSUE TITLE
CMR - wrong cost order in Amareth, the Lustrous

### ISSUE THREAD

**Issue by JayDi85** [mtgjson/mtgjson#712]
#### Version(s) affected
- [x] MTGJSON 5

#### Version(s) tested against
current website

#### Description of Bug
[Amareth, the Lustrous](https://scryfall.com/card/cmr/266/amareth-the-lustrous) from CMR:
* must have cost: `{3}{G}{W}{U}`
* [mtgjson](https://mtgjson.com/api/v5/CMR.json) shows wrong cost order: `{3}{G}{U}{W}`

**Comment by ZeldaZach** [comment]
Fixed
