### ISSUE TITLE
CMR release date is wrong

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#715]
https://mtgjson.com/api/v5/CMR.json

I'm not sure where `"releaseDate": "2020-11-11"` is coming from.

Official release date is `2020-11-20`. [wiki](https://mtg.gamepedia.com/Commander_Legends), and [official page](https://magic.wizards.com/en/products/commander-legends) both list `2020-11-20`.

**Comment by staghouse** [comment]
This has been resolved. Current date is now `2020-11-20` according to https://mtgjson.com/api/v5/CMR.json
