### ISSUE TITLE
Multiple MultiverseIDs missing from Secret Lair Drop

### ISSUE THREAD

**Issue by epigamic** [mtgjson/mtgjson#720]
#### Version(s) affected
- [ ] MTGJSON 4
- [X] MTGJSON 5

#### Version(s) tested against
MTGJSON 5.0.0+20201124

#### Description of Bug
A small subset of cards from Secret Lair Drop have MultiverseIDs in mtgjson but many more that are listed in Gatherer are missing them.

Files tested:
https://mtgjson.com/api/v5/SLD.json
https://mtgjson.com/api/v5/AllPrintings.json

Gatherer page with Secret Lair Drop cards:
https://gatherer.wizards.com/Pages/Search/Default.aspx?set=[%22Secret+Lair+Drop%22]

Example of card that is missing a MultiverseID (i.e. is listed on Gatherer, but does not have a MultiverseID in mtgjson):
Acidic Slime
Gatherer: https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=497497
UUID: 4f83eed0-9565-5f56-9354-67f69fc9877d

**Comment by ZeldaZach** [comment]
Hey mate, thanks for the report! Would love to get this fixed, and I think you might be able to help!

Can you provide me a full list of missing MultiverseIds? Maybe formatted as MTGJSON_UUID,MULTIVERSE_ID or SCRYFALL_UUID,MULTIVERSE_ID so I can import the changes?

**Comment by epigamic** [comment]
Happy to help. Here is a list of MTGJSON_UUID,MULTIVERSE_ID for all cards on the referenced Gatherer page, including those which already have a MultiverseID in mtgjson. This includes correct MultiverseIDs for cards with multiple versions (Lightning Bolt, Serum Visions, Thalia, Guardian of Thraben.

4f83eed0-9565-5f56-9354-67f69fc9877d,497497
1571957b-0497-5eb4-98ea-fa1a8773299b,485311
15d2153c-840b-54b3-a740-faa289453e81,497520
4f86556f-d146-5c8f-8101-88d3d155335b,497503
4a445e1e-95fb-52b1-a26d-b64592693a72,497494
b97ec876-4b14-5ee4-bdd6-39a7524509b7,479388
a7d45e03-a1aa-527f-a5ab-5fd806111ef4,485303
b17abbf5-8b0d-5723-9f9e-fb69d518ee12,479505
d946e317-7f8d-5397-9a3a-963101b5c430,485309
1ef8afc8-77f4-58e7-9ba0-d78a7cb73a94,485307
3993a2c3-a626-526b-b2b7-7d58c2651b80,479392
e3b61ca3-b574-5b51-97ad-72dc4a11e67d,485320
e86b79ae-e7b5-5218-9ec4-fc34756ebdf5,479379
3f80c076-6102-5273-9710-b5a83c61dfc7,479512
b91834a6-59ff-5774-bc56-25c3b0e2c050,497519
ffda0b30-2c36-57bc-a0b3-951a9c178e78,497518
08585c69-7aa0-540e-8474-c975207abd3c,485304
bb836c50-5498-5ad4-9563-4717d88ffa8f,497506
f288db5b-f80b-5d7b-bfaa-ed45910e6056,497502
e419bf41-b88c-5dba-9c8a-1d4cb1d073f5,485312
d1907fec-42d8-5100-a4b5-cb6e01d6a0fa,485310
1639b187-476f-5d5a-bf22-7e7d9a324a9d,479501
641dfec5-2976-5e62-9cc0-b4c8bda9f359,479503
13d2f88e-05a1-5f41-9786-89972b4b3505,485321
1625e47e-39eb-50b1-bcf8-1a19cc9b7c2f,497495
7dc1a803-e2b2-55d6-bb1c-3a9f1de6bd71,497493
4cd1bf17-bd7d-58e3-ac4e-f03b8cd06e34,485280
07992efb-4ddd-561a-a30c-1fa8a89e31c6,485308
47d962d2-9b96-57f7-a8db-c6d755cee739,497507
7484825f-cf0f-5721-91af-9f388b812410,479374
03518f51-fcd0-5891-b365-99f74c0672ec,479376
64857a21-7825-57ac-8c15-4c03c8d5b804,479377
cf7e1b75-1301-56ea-9529-a425830f8b25,479378
c54d07d1-0947-5a6b-98a1-a41f1d972c8d,479375
7f5fe3c6-13f3-587d-9366-79a2cfbe9dad,479380
b5fb8ec2-d763-53f2-9f39-8b54120bca1f,479497
938acf65-6f5e-514a-8913-f89d79ab9d15,479365
9a7d9a2b-14d3-5c0f-bb62-a1c28493610f,485323
c5f9b56c-eada-5c69-981b-6d32ac432f18,479499
aa42098a-51ee-5368-96e7-e61f82bce5a7,485277
15fffe16-8007-5eba-ad0d-dccfab8ff28b,479498
1890023b-f3ed-58bf-add9-a95760d1bbaa,479508
dd196bd8-2a99-5335-9935-d0a4976540aa,479502
f2fb2522-184c-5c62-afb3-cd70b1002125,479385
0b01460f-a11a-5403-9c6a-34aad284e22e,479381
26bb9b31-fc82-54b3-b13e-56dd1dba312a,485315
fa340683-e523-511d-8c98-ea498d69da0c,485316
20446d8e-c01e-5d05-93c1-488efb00087c,485317
6787846a-9e3d-52cb-a190-24f29331c62d,485318
cae4d1fa-6b49-5d7e-be34-f09268a0a787,497504
1d38195c-f5f1-560e-9c6a-fe1af7ca661c,497516
88339ccb-b4f2-53df-97a9-0d8b2e8bca9d,479366
897a3d5e-ec9c-52b5-967c-914d90aeb10c,479513
d35c3ec6-7c03-532f-8f0f-676c21a6229d,497508
89445970-2a9b-5156-a92c-9ab4eea26c04,479389
43a82ca6-338d-5ef9-ae82-1ed44ebb6c0a,479507
d599d800-2e6c-5833-a885-71253b320d40,485279
7a317099-ea5e-5392-a595-1aa81334270b,479514
473b3896-44de-5ddf-88fb-afec760c379c,497496
4897eecb-b2e9-5e1b-bc09-73431f81914a,497509
4b519479-1493-5758-9211-df4c7d3940b2,479509
abc61539-34ee-5b31-a88d-c9b8841d776a,479515
6391a5e5-d41b-5a8f-85b2-746d411dac67,497492
8b3eaf0e-8a2a-5e1d-8ae9-0e34b05183aa,479367
276ea161-aa92-55e8-a716-f7299174eb62,479511
8ae84b1a-0e5d-5b96-802a-529f558102d0,479504
c4417193-b9c4-5df7-b3ea-bdd749ff6832,485322
f916309d-fabb-549a-a216-d5b788439fc9,485276
67c99f0e-7735-5b1b-b99d-eef24d845dde,479506
6e94e581-8563-561b-92f8-c68739fbd039,479387
c8dc8db7-6a76-5f7d-b9ec-d95f6246cdb0,479368
8c73c87b-959a-5c6d-8272-5aa87d039439,479382
a4302153-bc7b-5860-972c-20656a7f8708,479386
91addac9-2096-57a4-be4d-52c365c4fa40,497501
e95969b4-1fab-599b-a712-f96a17335ce3,497505
cf265ce3-a76a-562d-a9f0-7720f22b0590,479516
1d697a84-f961-5999-99af-75ba182309ee,497498
9e9ab6d0-fcd8-523c-a8e9-8773b0443dd1,479397
fb3bdc21-d1c3-5fa2-8ea6-3ff48b11a5bc,479398
ef228daa-505c-5fbf-83c4-110eba5b5946,479399
f93fa4d1-068d-5126-bbba-3863884b39c4,479400
c3eb2450-4ad2-51ec-94fe-51d6be98ad17,479383
ba437894-c60c-558a-a8ed-436118d794e4,479373
778193e7-59cb-57d9-8837-9a7543c022b3,479370
3775114c-c464-5a2d-b0c8-454e7f4e2389,479372
a78f0947-fc4e-5831-89af-d7ff3e5a1e3c,479369
c9f3cc8a-52a5-5743-819a-a83a20a20e67,479371
2dfdcffa-746b-5273-8991-017bf506c418,485319
76a81fd3-8410-581b-8c08-b796210d8126,485278
af9a0ba0-d941-56c7-b479-da3c92994cc0,485306
1f8ea226-550c-59df-ac54-ae49b84716dd,497491
4d9c6f9c-67bb-5d10-a39c-b77234623cf4,485313
f5016e90-917e-5a9a-9740-60e4775e811b,497517
7cba949d-88c9-516f-bfc9-b68a6f43004f,479517
696679ff-91c6-53a4-bd90-f51eba23237f,479518
2322a15f-3028-52f2-a962-33d3b7e11284,479519
5af9d664-4932-5e96-8d0a-9863ed9b4d39,479520
6de61478-4cad-5f8b-98f1-9ddd23f5b823,479500
81e80eb8-bbc0-5727-a0b0-d0d4245fb72d,497499
2c334c2c-6664-5bb8-8052-d7e88ed4b835,479384
8a11fe5f-2a95-5ee0-92d4-21be912dcb24,497500
33721f15-5b41-5b3a-b430-89adada99a12,485314
f9e17610-a7f2-5943-bd29-626453de5ae8,485305
184745b0-6ba3-5fc0-9304-8f6acd7c386f,479510
