### ISSUE TITLE
Doubled entry in json array for Soulhunter Rakshasa

### ISSUE THREAD

**Issue by DJCatBlitz** [mtgjson/mtgjson#724]
#### Description of Bug
Soulhunter Rakshasa has a double entry in this version. Only Unstable cards have multiple entries in the json array with same name and layout otherwise. Perhaps this is a bug?

**Comment by ZeldaZach** [comment]
Can you provide some more detail? v4, v5, or both? What file(s) did you see an issue in?

**Comment by DJCatBlitz** [comment]
I'll try ;)
I use AtomicCards.json and when I parsed the json Soulhunter Rakshasa appeared two times. For all cards (except unstable) this means the cards have different layouts, are split cards, meld cards, ...
Only Soulhunter Rakshasa  had this problem with same layout.

**Comment by DJCatBlitz** [comment]
Fixed in 20201214 version!
