### ISSUE TITLE
isPaperOnly missing

### ISSUE THREAD

**Issue by SleazyOtto** [mtgjson/mtgjson#725]
isPaperOnly doesn't exist in V5 SetList.json, only in V4

**Comment by staghouse** [comment]
`isPaperOnly` is an optional field and currently no Sets are only printed in paper. Not sure if thats a bug but you should not expect it to return false

**Comment by SleazyOtto** [comment]
It's not that it returns false, it's simply not there (which fits the "optional" classification).  However, if it's not populated in any instance - not even Alpha? Beta? - why bother with it?
Mostly, I was just surprised when I saw it in the doc, but not in the actual data.  (i.e., no big deal)

**Comment by staghouse** [comment]
Right, optional values that are false don't return at all, so it makes sense if you don't see it - but also, i agree that is strange that it never populates for any set. That's leading me to believe this is a bug.

**Comment by ZeldaZach** [comment]
Just took a look, and this field is 100% falsey in the v4. Since the field is optional, I see no issue with our current impl.
