### ISSUE TITLE
Some Prerelease Promos are missing.

### ISSUE THREAD

**Issue by giniman** [mtgjson/mtgjson#726]
#### Version(s) affected
- [ ] MTGJSON 5

#### Version(s) tested against

MTGJSON 5.0.0, Nov 30th.

#### Description of Bug
Prerelease Promotional cards, Malfegor (pcon-117★), Ajani Vegeant (pala-154★), Obelisk of Alara(pcon-140★) is missiong.
I am not sure the card set and numbering rules changed in prerelease promotional cards...

**Comment by Palladinium** [comment]
I can confirm this, some promo cards appear to be missing when migrating from v4 to v5.

Tested with: https://www.mtgjson.com/api/v5/AllPrintings.json
Downloaded on Dec 3rd, 2020
sha256: `ff593ee0989e96c2623d36de3ed6a4e116c550884053d70970db1eefe2cc6495`

Missing cards:
- PEMN Hanweir Battlements // Hanweir, the Writhing Township
- PEMN Hanweir Garrison // Hanweir, the Writhing Township
- PHEL Angel
- PHEL Demon
- PLPA Figure of Destiny
- PLPA Knight of New Alara
- PLPA Magister of Worth
- PLPA Obelisk of Alara
- PMOR Earwig Squad
- PPRE Ajani Vengeant
- PPRE Door of Destinies
- PPRE Dragon Broodmother
- PPRE Korlash, Heir to Blackblade
- PPRE Malfegor
- PPRE Oros, the Avenger
- PPRE Overbeing of Myth
- PPRE Wren's Run Packmaster
- PREL Hedge Troll
- PREL Shriekmaw
- PREL Storm Entity
- PSHM Demigod of Revenge
- PSHM Vexing Shusher
- PTSP Lotus Bloom
- PTSP Sudden Shock

**Comment by ZeldaZach** [comment]
Rebuilt. This should be solved. Upstream was migrating promos around.
