### ISSUE TITLE
UST Full-art tokens don't have otherFaceIds set

### ISSUE THREAD

**Issue by Palladinium** [mtgjson/mtgjson#727]
#### Version(s) affected
MTGJSON 5

#### Version(s) tested against
v5.0.1
Downloaded from https://www.mtgjson.com/api/v5/AllPrintings.json on Dec 3rd, 2020
sha256: ff593ee0989e96c2623d36de3ed6a4e116c550884053d70970db1eefe2cc6495

#### Description of Bug
Affected cards: All of the two-sided full-art tokens in the Unstable (UST) set.
- Angel
- Beast
- Clue
- Elemental (Red)
- Elemental (White/Green)
- Saproling
- Spirit
- Thopter
- Vampire
- Zombie

Problems:
- Their `layout` is `token`, though maybe it should be `art_series`.
- They don't have an `otherFaceIds` field. It should contain the id of the other face of the card.
- Their `reverseRelated` field is an empty array. It should be filled in to reference the other card, similarly to `transform` cards.

**Comment by ZeldaZach** [comment]
Priority raised by Mythic Patron
