### ISSUE TITLE
Set Translations have been failing for a while

### ISSUE THREAD

**Issue by michelg31** [mtgjson/mtgjson#728]
#### Version(s) affected
- [ ] MTGJSON 4
- [x] MTGJSON 5

#### Version(s) tested against

5.0.1+20201203

#### Description of Bug
In setList.json, DATA information for each set. 
For each DATA entry, you have a field translations.
It is consistant (with somemissing) until AKH but for release after AKH,  it is mostly empty with no entries or with Null values.

I checked in allprintings.zip and you do have the translations, so it is mostly for JSON

example for AKH :
{"baseSetSize": 269, "block": "Amonkhet", "code": "AKH", "isFoilOnly": false, "isOnlineOnly": false, "keyruneCode": "AKH", "mcmId": 1729, "mcmName": "Amonkhet", "mtgoCode": "AKH", "name": "Amonkhet", "releaseDate": "2017-04-28", "tcgplayerGroupId": 1882, "totalSetSize": 287, **"translations": {"Chinese Simplified": "阿芒凯", "Chinese Traditional": "阿芒凱", "French": "Amonkhet", "German": "Amonkhet", "Italian": "Amonkhet", "Japanese": "『アモンケット』", "Korean": "아몬케트", "Portuguese (Brazil)": "Amonkhet", "Russian": "Амонхет", "Spanish": "Amonkhet"},** "type": "expansion"}

example for HOU :
{"baseSetSize": 199, "block": "Amonkhet", "code": "HOU", "isFoilOnly": false, "isOnlineOnly": false, "keyruneCode": "HOU", "mcmId": 1731, "mcmName": "Hour of Devastation", "mtgoCode": "HOU", "name": "Hour of Devastation", "releaseDate": "2017-07-14", "tcgplayerGroupId": 1934, "totalSetSize": 209, **"translations": {},** "type": "expansion"}, 

example for WAR:
{"baseSetSize": 264, "block": "Guilds of Ravnica", "code": "WAR", "isFoilOnly": false, "isOnlineOnly": false, "keyruneCode": "WAR", "mcmId": 2439, "mcmName": "War of the Spark", "mtgoCode": "WAR", "name": "War of the Spark", "releaseDate": "2019-05-03", "tcgplayerGroupId": 2418, "totalSetSize": 311, "translations": **{"Chinese Simplified": null, "Chinese Traditional": null, "French": "La Guerre des Planeswlakers", "German": null, "Italian": null, "Japanese": null, "Korean": null, "Portuguese (Brazil)": null, "Russian": null, "Spanish": null}**, "type": "expansion"}

I made a count of nb translations coming from your files for expansions :
code | nb translations 
ZNR | 0
IKO | 1
THB | 1
ELD | 1
WAR | 4
RNA | 1
GRN | 0
DOM | 1
RIX | 1
XLN | 0
HOU | 0
AKH | 10
AER | 10
KLD | 10
EMN | 10
SOI | 10
OGW | 10
BFZ | 10
DTK | 10
FRF | 10
KTK | 10
JOU | 10
BNG | 10
THS | 10
DGM | 0
GTC | 10
RTR | 10
AVR | 0
DKA | 0
ISD | 0
NPH | 0
MBS | 10
SOM | 0
ROE | 0
WWK | 0
ZEN | 0
ARB | 10
CON | 10
ALA | 10
EVE | 10
SHM | 10
MOR | 9
LRW | 10
FUT | 10
PLC | 10
TSP | 10
TSB | 0
CSP | 10
DIS | 10
GPT | 10
RAV | 10
SOK | 10
BOK | 10
CHK | 10
5DN | 10
DST | 10
MRD | 10
SCG | 3
LGN | 3
ONS | 3
JUD | 10
TOR | 10
ODY | 10
APC | 10
PLS | 0
INV | 0
PCY | 10
NEM | 0
MMQ | 1
UDS | 1
ULG | 1
USG | 1
EXO | 1
STH | 1
TMP | 1
WTH | 1
VIS | 0
MIR | 4
ALL | 0
HML | 1
ICE | 1
FEM | 0
DRK | 0
LEG | 0
ATQ | 0
ARN | 0

Hope it will help you

Regards

**Comment by michelg31** [comment]
I double checked and there is also missing information in allprintings.sqlite

Example for WAR in set_translations

Language  | setCode | traslation
Chinese Simplified | WAR |  _Null_
Chinese Traditional | WAR |  _Null_
French | WAR | La Guerre des Planeswlakers
German | WAR |  _Null_
Italian | WAR |  _Null_
Japanese | WAR |  _Null_
Korean | WAR |  _Null_
Portuguese (Brazil) | WAR |  _Null_
Russian | WAR |  _Null_
Spanish | WAR |  _Null_

**Comment by ZeldaZach** [comment]
Will have to re-audit my set translation code, as Wizards breaks things a lot :)

**Comment by angelcervera** [comment]
Maybe related to this: https://github.com/mtgjson/mtgjson/issues/979
