### ISSUE TITLE
Add 'seeded' booster info

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#73]
At pre-release events, they sometimes have 'seeded' boosters. Potentially add this info: http://mtgsalvation.gamepedia.com/Booster_pack#Seeded_boosters

https://github.com/mtgjson/mtgjson/issues/62

**Comment by ZeldaZach** [comment]
We'd need to get more information first on what the seeded boosters are. Would rather defer to another source for that information, if we can find it.

**Comment by ZeldaZach** [comment]
So i spent quite a bit of time this weekend trying to find somewhere that might possibly have this info. It just doesn't exist. Frankly, this isn't too critical at this time and not worth anymore effort. Sorry :(
