### ISSUE TITLE
Several missing decks from upstream

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson#733]
A kind user provided me with missing decks from the GN2 block @taw can you look at incorporating these, if they aren't available yet?

Glorious Combat (White)

1 Highcliff Felidar  [GN2]
1 Zetalpa, Primal Dawn [GN2]
1 Kytheon's Irregulars [GN2]
1 Loxodon Lifechanter [M20]
1 Sephara, Sky's Blade [M20]
1 Griffin Protector [M20]
2 Inspiring Captain [M20]
2 Squad Captain [M20]
3 Steadfast Sentry [M20]
2 Consul's Lieutenant [GN2]
2 Fiend Binder [GN2]
2 Patron of the Valiant [GN2]
1 Relief Captain [GN2]
1 Steppe Glider [GN2]
2 Topan Freeblade [GN2]
1 Howling Golem [GN2]
1 Take Vengeance [GN2]
2 Inspired Charge [M20]
3 Raise the Alarm [M20]
2 Mighty Leap [GN2]
2 Pacifism [M20]
26 Plains [GN2]

Massive Might (Green)

1 Earthshaker Giant [GN2]
1 Voracious Hydra [M20]
1 Ghalta, Primal Hunger [GN2]
1 Ripjaw Raptor [GN2]
1 Wakeroot Elemental [M20]
2 Ferocious Pup [M20]
2 Howling Giant [M20]
3 Leafkin Druid [M20]
2 Silverback Shaman [M20]
2 Crested Herdcaller [GN2]
2 Grazing Whiptail [GN2]
1 Howling Golem [GN2]
2 Ranging Raptors [GN2]
2 Thundering Spineback [GN2]
2 Overcome [M20]
3 Thunderherd Migration [GN2]
3 Growth Cycle [M20]
1 Plummet [M20]
2 Spidery Grasp [GN2]
26 Forest [GN2]

Draconic Fury (Red)

1 Fiendish Duo [GN2]
1 Drakuseth, Maw of Flames [M20]
1 Akoum Hellkite [GN2]
1 Lathliss, Dragon Queen [GN2]
1 Glint-Horn Buccaneer [M20]
1 Dragon Mage [M20]
2 Goblin Smuggler [M20]
2 Keldon Raider [M20]
4 Pack Mastiff [M20]
2 Ripscale Predator [M20]
2 Dragon Egg [GN2]
2 Kargan Dragonrider [GN2]
2 Sparktongue Dragon [GN2]
2 Voldaren Duelist [GN2]
1 Zealot of the God-Pharaoh [GN2]
1 Howling Golem [GN2]
1 Act of Treason [M20]
1 Tectonic Rift [M20]
1 Destructive Tampering [GN2]
1 Chandra's Outrage [M20]
1 Shock [M20]
1 Brute Strength [GN2]
2 Lightning Strike [GN2]
26 Mountain [GN2]

Endless Hordes (Black)

1 Calculating Lich [GN2]
1 Torgaar, Famine Incarnate [GN2]
1 Dread Presence [M20]
1 Vilis, Broker of Blood [M20]
3 Gorging Vulture [M20]
2 Gravedigger [M20]
2 Sanitarium Skeleton [M20]
4 Undead Servant [M20]
1 Accursed Horde [GN2]
1 Carrion Screecher [GN2]
2 Crow of Dark Tidings [GN2]
1 Gavony Unhallowed [GN2]
2 Lord of the Accursed [GN2]
3 Tattered Mummy [GN2]
1 Howling Golem [GN2]
1 Blood for Bones [M20]
1 Bone Splinters [M20]
1 Rise from the Grave [GN2]
2 Murder [M20]
2 Grasp of Darkness [GN2]
1 Liliana's Mastery [GN2]
26 Swamp [GN2]

Aerial Acrobatics (Blue)

1 Sphinx of Enlightenment [GN2]
1 Brineborn Cutthroat [M20]
1 Agent of Treachery [M20]
1 Dungeon Geists [M20]
2 Air Elemental [M20]
2 Cloudkin Seer [M20]
2 Frost Lynx [M20]
2 Moat Piranhas [M20]
2 Warden of Evos Isle [M20]
2 Aven Wind Mage [GN2]
2 Cryptic Serpent [GN2]
2 Salvager of Secrets [GN2]
1 Howling Golem [GN2]
1 River's Rebuke [GN2]
1 Captivating Gyre [M20]
2 Winged Words [M20]
1 Rise from the Tides [GN2]
1 Engulf the Shore [GN2]
1 Unsummon [M20]
2 Decision Paralysis [GN2]
1 Dramatic Reversal [GN2]
2 Galestrike [GN2]
1 Claustrophobia [GN2]
26 Island [GN2]

**Comment by taw** [comment]
It's all done now.
