### ISSUE TITLE
Missing booster data for Amonkhet Remastered (AKR)

### ISSUE THREAD

**Issue by fverdoja** [mtgjson/mtgjson#738]
#### Version(s) affected
- [ ] MTGJSON 4
- [x] MTGJSON 5

#### Version(s) tested against

MTGJSON 5.0.1+20201221

#### Description of Bug
In `data.AKR` the `booster` attribute is missing.

Since it's an MTGA-only set, Amonkhet Remastered boosters don't have foils nor a basic land slot, so they should pretty simple. Deserts and other non-basic lands appear among the other cards of their rarity (as can be seen in the first two picks of [this BenS video](https://www.youtube.com/watch?v=eQSMRBhu9qA&t=6845s))
```json
{
  "default": {
    "boosters": [
      {
        "weight": 1,
        "contents": {
          "common": 10,
          "uncommon": 3,
          "rareMythic": 1
        }
      }
    ],
    "boostersTotalWeight": 1,
    "sheets": {
      ... // Sheets
    }
  }
}
```

However I am noticing that you chose to have the boosters for KLR (another MTGA-only set) have a basic land and foil slot, which they don't actually have as well. May I ask why did you make this choice?

Regardless of the reason, AKR should probably be consistent with what you chose for KLR, I think.

Thanks for the great work!

**Comment by silasary** [comment]
Upstream issue for https://github.com/taw/magic-sealed-data

**Comment by fverdoja** [comment]
I didn't know you were taking the booster data from there. What do you suggest? Should I post the issue there as well or are the people involved in that project looking here?

**Comment by ZeldaZach** [comment]
I just ping @taw normally. Speaking of that, hey Taw can you look into this? :)

**Comment by taw** [comment]
@ZeldaZach is this true for all Arena draft boosters for Standard as well, not just remastered sets? That they never contain any foils, but otherwise match paper/MTGO boosters?

**Comment by fverdoja** [comment]
Arena packs never contain foils, that's correct. 
iirc, they also don't contain a basic land slot, unless in the set there are non-basic lands in the land slot.

**Comment by taw** [comment]
I'll add Arena boosters for all sets then. They'll be listed as `arena` type not `default`. (and generally 0 foils, 1 rare/mythic, 3 uncommons, 10 color balanced commons, 0 basics)

**Comment by taw** [comment]
Kaladesh Remastered and Amonkhet Remastered now have fixed Arena boosters.

**Comment by taw** [comment]
All sets now have Arena boosters.
[It's live on mtg.wtf](https://mtg.wtf/sealed) and should get included in next weekly update of mtgjson.

As long as the only differences are - no foils and no basic-only slot (but yes to mixed basic/common land slots) - I can add Arena boosters together with regular boosters.

So that's pretty much it for this issue?

**Comment by fverdoja** [comment]
I think this solves it, thanks! If you want to include all sets present in Arena I think you are only missing Dominaria, otherwise this is closed ;)

**Comment by taw** [comment]
I just forgot to enable Dominaria Arena Booster, it's there now.

**Comment by fverdoja** [comment]
Thanks a lot for addressing this then :) I think this does it for this one.
