### ISSUE TITLE
Add additional Duels sets

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#74]
Should add the additional Duels of the Planeswalkers sets (2012/1013/etc) and other 'Duels' digital sets, such as 'Magic Duels: Origins'. Will need to make sure I get the 'booster' property set correctly as it differs significantly from physical MtG.

https://github.com/mtgjson/mtgjson/issues/53

**Comment by ZeldaZach** [comment]
The "booster" field is currently not implemented in V4, and I don't think we'd add it for such sets anyway. My recommendation is to close and wait for the booster impl

**Comment by KingSupernova31** [comment]
Can't the sets be added, just without the "booster" field?

**Comment by ZeldaZach** [comment]
Booster field has been addressed now. Will see if there's a source for this. If not, will bump to 4.2

**Comment by ZeldaZach** [comment]
So this is something I can't find definitive data on, so I'll have to bump it back

**Comment by ZeldaZach** [comment]
Marked as upstream since SF will be looking into this at some point. A bit tough to do on my own.

**Comment by ZeldaZach** [comment]
Still will be an upstream, but a nofix on my part.

**Comment by tooomm** [comment]
Is SF aware of this? @ZeldaZach

**Comment by ZeldaZach** [comment]
Yes, it's on their long todo list from what I can tell
