### ISSUE TITLE
Daily build for spoilers

### ISSUE THREAD

**Issue by jmcsmith** [mtgjson/mtgjson#740]
#### Version(s) affected
- [ ] MTGJSON 4
- [x] MTGJSON 5

#### Description of Bug
Schedule daily builds for spoilers.

**Comment by ZeldaZach** [comment]
I've marked Kaldeheim for spoiler builds starting tomorrow.

**Comment by jmcsmith** [comment]
@ZeldaZach looks like the last build of Kaldheim was 1-9-2021. Are daily builds for spoilers still working?

**Comment by ZeldaZach** [comment]
The builds were getting uploaded but not pushed live. I gotta fix that soon. In any case, deployed
