### ISSUE TITLE
Missing word for Bretagard Stronghold

### ISSUE THREAD

**Issue by DJCatBlitz** [mtgjson/mtgjson#742]
#### Version(s) affected
- [ ] MTGJSON 4
- [x] MTGJSON 5

#### Version(s) tested against
MTGJSON 5.0.1+20210109"

#### Description of Bug
Bretagard Stronghold is missing a "could" in its 3rd ability text

**Comment by ZeldaZach** [comment]
Reported, should be fixed shortly
