### ISSUE TITLE
Typo on Varragoth, Bloodsky Sire  (Is it helpful to report these kind of bugs?)

### ISSUE THREAD

**Issue by DJCatBlitz** [mtgjson/mtgjson#744]
#### Version(s) affected
- [ ] MTGJSON 4
- [x] MTGJSON 5

#### Version(s) tested against
MTGJSON 5.0.0+20210109

#### Description of Bug
search -> searches

**Comment by ZeldaZach** [comment]
Reported and should be fixed shortly. As a general rule of thumb, during spoiler season assume some data might be slightly off. If you see an issue that persists more than 2 or 3 days, then it's worth reporting. A good chunk of these should get caught on the first audit, which happens after we load in the data.
