### ISSUE TITLE
Add 'deck' or 'subset' field

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#75]
This can be used to identify which cards are part of which decks (such as 'elf' deck in the 'elves vs goblins' set). The existing 'source' field is used a bit like this for some promos sets like CPK, but it's not quite the same thing, but it probably would work just fine for this.

https://github.com/mtgjson/mtgjson/issues/51

**Comment by ZeldaZach** [comment]
Source has been removed, but I think this could be an interesting idea. Would need someone to sit down and go through everything though

**Comment by ZeldaZach** [comment]
Note: Most of the Duel Deck sets number the first deck and then the second deck though

ex: in DDU cards number 1-34 are the green deck
