### ISSUE TITLE
Include formatting info for text

### ISSUE THREAD

**Issue by fenhl** [mtgjson/mtgjson#75]
Figuring out which parts of a card's rules text are in italics is currently only possible using a complete list of keyword abilities, since some keyword abilities are printed with a following em dash, like ability words. For example, [Inner Sanctum](http://magiccards.info/query?q=%21Inner+Sanctum) has “cumulative upkeep — Pay 2 life”, but [Plated Geopede](http://magiccards.info/query?q=%21Plated+Geopede) has “_landfall_ — Whenever a land enters the battlefield under your control, Plated Geopede gets +2/+2 until end of turn”.

It would be very helpful to include this formatting info in the rules text field. A syntax that could work well with the current syntax for mana symbols is `{i:Landfall}`. Backwards incompatibility is avoidable by using a separate `formattedText` field until the next major release.

**Comment by mirandir** [comment]
Maybe a more 'standard' syntax (like the tags <i></i>, <b></b>, ...) would be better.

**Comment by fenhl** [comment]
Are you referring to HTML tags? I'm not sure the simple formatting of MTG cards warrants having to use XML within JSON.

**Comment by mirandir** [comment]
Sorry, there were examples in my message, but github doesn't display them.

Yes, I'm referring to HTML/XML tags. MTG cards have simple formatting but (I can be wrong) it seems to me many languages have build-in functions to read those tags. Maybe those tags will make the developers' work easier ?

**Comment by fenhl** [comment]
(Github uses Markdown, so you need to escape &lt; as &amp;lt; in situations where it might be parsed as an XML tag.)

While it is true that XML has widespread support in standard libraries, the language itself is fairly complex and could introduce problems if not encoded/parsed correctly. For example, I don't know if the database uses &quot;straight&quot; ASCII quotes instead of “curly” Unicode quotes, but if it does, all of those would have to be escaped as &amp;quot;.

Anyway, I would be content with any representation of italics as long as the format is unambiguous.

**Comment by lsmoura** [comment]
Even tough the keyword on the card is printed in italics, the Gatherer website (or magiccards.info) does not provide the information about italics on the text card...

For example: http://gatherer.wizards.com/Pages/Card/Details.aspx?printed=false&multiverseid=401804

**Comment by flyingmutant** [comment]
Just to voice an agreement with @fenhl — something simpler than HTML/XML is preferable, if technically possible.

**Comment by taw** [comment]
So mtg.wtf uses piles of regexps to work around mtgjson limitations. (issue above is just most recent one)

Things like - mana costs, loyalty costs, reminder text, ability keywords need proper markup at some point. It would make more sense to regexp that in mtgjson build process instead of at use time.

**Comment by ericcholis** [comment]
Given that the keyword abilities and ability words are standardized, my suggestion is to simply have a lookup to compile a list of applicable keywords/abilities.

So that ultimately, Akoum Firebird might look like:

```
{
	"artist": "Chris Rahn",
	"cmc": 4,
	"colorIdentity": [
		"R"
	],
	"colors": [
		"Red"
	],
	"id": "579f3ed94f19c94dccd16df6b3417a399e6deba8",
	"imageName": "akoum firebird",
	"keywordAbilities": [
		"Flying",
		"Haste"
	],
	"abilityWords: [
		"Landfall",
	],
	"layout": "normal",
	"manaCost": "{2}{R}{R}",
	"mciNumber": "138",
	"multiverseid": 401804,
	"name": "Akoum Firebird",
	"number": "138",
	"power": "3",
	"rarity": "Mythic Rare",
	"subtypes": [
		"Phoenix"
	],
	"text": "Flying, haste\nAkoum Firebird attacks each combat if able.\nLandfall — Whenever a land enters the battlefield under your control, you may pay {4}{R}{R}. If you do, return Akoum Firebird from your graveyard to the battlefield.",
	"toughness": "3",
	"type": "Creature — Phoenix",
	"types": [
		"Creature"
	]
}
```

Alternatively, keywordAbilities and abilityWords could be combined into a single array.
