### ISSUE TITLE
Set MZNR has incorrect layout entries (4 of 5)

### ISSUE THREAD

**Issue by peardox** [mtgjson/mtgjson#752]
Every card in MZNR has a layout marked as 'token' while the proper layout from Scryfall is 'double_faced_token' for four of the five cards.

It's worth noting that WotC one single-sided token mixed in with this token set and rumor has it (not 100% on this) that there will a be similar token set for set boosters for KHM

This also affects a few other cards from some other sets - see https://scryfall.com/search?q=layout%3Adouble_faced_token

For now something like the following should work as a catch-all (hardly bullet-proof)...

if scryfall_object.get("layout") == "double_faced_token":
        mtgjson_card.layout = "double_faced_token"

**Comment by ZeldaZach** [comment]
I'll look into this further in the near future, thanks for bringing it up.
