### ISSUE TITLE
originalReleaseDate should be on atomic cards

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#753]
The originalReleaseDate of a card doesn't change with expansion since it always refers to the first one, so it can be on card (atomic).

**Comment by ZeldaZach** [comment]
This could come about by taking the min value of all release dates in the cycle, taking into account the set release date if a date isn't found... I'll think about it.

Other comments are welcomed!

**Comment by KingSupernova31** [comment]
Oh, does originalReleaseDate of a card in a particular expansion refer to that expansion's release date? I assumed it was referring to the first printing of that card in any expansion. If it's the former, I still support the described field in atomic cards, but think it should be given a different name to avoid confusion.

**Comment by ZeldaZach** [comment]
originalReleaseDate is associated with cards that appear in a set and the card wasn't in the set at launch. FNM Promos are a good example, as they're in one encompassing set, but the cards don't release until the proper week. 

Supporting a release date on a card-by-card basis in AtomicCards could be an interesting change, and i'd be willing to convert this ticket towards that goal.

**Comment by ZeldaZach** [comment]
I've thought more about this, and agree that AtomicCards could use a boost indicating when a card was first printed. However, that is unrelated to the `originalReleaseDate` field of Card (Set), so I will be closing this ticket in favor of #1020
