### ISSUE TITLE
Add isNonEnglishOnly card property

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#759]
I know foreign language support is being reworked, so i wanted to propose adding a flag to better identify which cards do not have an english printing.

This would be helpful to determine when to check the ForeignData array, and would simplify code that need to deduplicate cards by language

**Comment by ZeldaZach** [comment]
I like this idea. I don't have a way to pull in foreign-only cards yet, so it's on the backburner. But i'll keep it in mind!

**Comment by staghouse** [comment]
+1

**Comment by kodawah** [comment]
the default language field is perfect, even better than a boolean
