### ISSUE TITLE
Include additional frame information

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#76]
It would be nice to have information about nonstandard frames including:
various masterpiece frames
Ixalan DFC backside frame
textless promos
full art promos
full art lands
(possibly Nyx, miracle, and other such minor frame features)
the new legendary frame (this can be extrapolated from the current frame field combined with the supertypes.)

https://github.com/mtgjson/mtgjson/issues/454

**Comment by ZeldaZach** [comment]
I don't have enough information right now to make an informed decision. Will defer for help

**Comment by tooomm** [comment]
Linking https://github.com/mtgjson/mtgjson/issues/480 and https://github.com/mtgjson/mtgjson4/issues/77

**Comment by ZeldaZach** [comment]
Labeled as upstream, since they might look into it in the future. Will consider myself at some point

**Comment by ZeldaZach** [comment]
This is now doable using the `frame_effect` feature. Not sure what I want to do with this though. Looking for additional inputs before I go forward with anything
