### ISSUE TITLE
KHM snow duals incorrectly listed as commons

### ISSUE THREAD

**Issue by clsn-eng** [mtgjson/mtgjson#760]
#### Version(s) affected
Whichever version is live on the website.

#### Version(s) tested against
The download from the website

#### Description of Bug
The common snow dual lands are listed as commons.
They should be listed as appearing in the same slot as the basic lands.
eg. M19 is a set which has the same booster structure.

**Comment by ZeldaZach** [comment]
This sounds like a booster issue. cc: @taw

**Comment by taw** [comment]
Like with every set, booster information went through a bunch of iterations, as there's usually something missing from official data.

Latest data should all be correct I think.
