### ISSUE TITLE
`hasAlternativeDeckLimit` not set for Seven Dwarves

### ISSUE THREAD

**Issue by venning** [mtgjson/mtgjson#763]
#### Version(s) affected
- [ ] MTGJSON 4
- [x] MTGJSON 5

#### Version(s) tested against
"MTGJSON 5.1.0+20210207"

#### Description of Bug
The `hasAlternativeDeckLimit` boolean for the card "Seven Dwarves" is not set in Atomic Cards.

Description for this property in the docs: "If the card allows a value other than 4 copies in a deck".

Seven Dwarves allows for up to 7 copies of itself in a deck, so it should likely be set to `true`.

**Comment by ChainsawXIV** [comment]
This should likely also be set for Once More with Feeling which has a special deck limit of one.

**Comment by ZeldaZach** [comment]
Thanks for pointing this out, I'll get around to fixing this soon!
