### ISSUE TITLE
Incorrect multiverseId by side for some MDFCs

### ISSUE THREAD

**Issue by ChainsawXIV** [mtgjson/mtgjson#764]
#### Version(s) affected
- [ ] MTGJSON 4
- [x] MTGJSON 5

#### Version(s) tested against
MTGJSON 5.1.0

#### Description of Bug
In some but not all cases, the multiverseId values for the various faces of modal double faced cards are incorrect. I have not checked all MDFCs, but a quick spot check shows that, for example:

- All Kaldheim god cards have their front and back multiverseIds swapped between sides
- The Zendikar pathway lands have the same id for both sides (some back, others front)

Some other MDFCs have multiverseId's as expected (for example, Kaldheim pathway lands).

Possibly related to #714 depending on the root of that issue.

**Comment by ZeldaZach** [comment]
I put a note upstream with fixes for the gods & pathways pointed out

**Comment by ZeldaZach** [comment]
Fixed this up :)
