### ISSUE TITLE
baseSetSize incorrect since M21 

### ISSUE THREAD

**Issue by peardox** [mtgjson/mtgjson#765]
Looking at recent standard sets...

ELD 269 269
THB 254 254
IKO 274 274
M21 274 277*
ZNR 280 285*
KHM 285 290*

The first number is the base set size as quite by Wikipedia +Fandom, the second number is the one reported by MTGJson. Since M21 the numbers appear to be incorrect (to high - can't quite work out which extra cards are being counted).

**Comment by kodawah** [comment]
im affected by this as well

**Comment by ZeldaZach** [comment]
Will look into this as soon as I can

**Comment by taw** [comment]
I tried using baseSetSize for my sealed data, but then discovered the same 3 issues.

**Comment by peardox** [comment]
Having explored for a few hours it appears that Scryfall _may_ have mis-labelled some M21 + ZNR cards
Using https://magic.wizards.com/en/productdetails as a (badly laid out) reference it appears that ...

M21 #275-277 (alt art Teferi, Master of Time) are not main set cards (it's also got PWDeck cards just to confuse things...)
ZNR #380-384 (standard lands) are not main set cards
KHM, on the other hand, counts correctly if I apply a test for promoTypes = ''
