### ISSUE TITLE
isInBooster option available upstream

### ISSUE THREAD

**Issue by peardox** [mtgjson/mtgjson#767]
Scryfall has a promo_types array that is not fully passed to MTGJson
Scryfall has a booster field that is omitted in MTGJson

Taking https://api.scryfall.com/cards/ce2bc7ad-458d-445e-a0a9-7897b596fdd0?format=json&pretty=true as an example the card's promo_types includes 'planeswalkerdeck' and has a booster entry of false

This information indicates that the sample card is to be found in Planeswalker Decks and not in Boosters

```
# Remove terms that are covered elsewhere
mtgjson_card.promo_types = [
    card_type
    for card_type in mtgjson_card.promo_types
    if card_type not in {"starterdeck", "planeswalkerdeck"}
]

```

It's covered elsewhere (???) but not exposed as far as I can ascertain. There is no way to know if the sample card is available in a booster or not

**Comment by ZeldaZach** [comment]
That booster field looks new, will have to audit the docs. Might use that to fixup/drop that isStarter component.

As for PWD, that's not a "promo" type imo. It's just indicating the card is only in promo decks, a special kind of deck. Will think more of this in the coming weeks.
