### ISSUE TITLE
A problem with no upstream solution (card orientation)

### ISSUE THREAD

**Issue by peardox** [mtgjson/mtgjson#769]
Maybe you've noticed that AZNR has cards in both portrait and landscape orientation? If not, the set has that dubious distinction. Fortunately they _appear_ to be one block or portrait followed by another block or landscape (36 and 45 cards respectfully - note I need to verify this assumption)

The yet-to-hit-scryfall [AKHM](https://magic.wizards.com/en/articles/archive/card-image-gallery/kaldheim-art-cards-2021-02-03) is almost entirely in landscape orientation with four exceptions - cards 53, 58, 63 and 67 are portrait-orientation (this one I am sure of - just put them all in a binder)

This is not the only time WotC have had cards best viewed sideways of course.

My concern here is that the data _should_ be available (even if it's only in my head ATM) as this, of course, affects web page, application and mobile layout

**Comment by staghouse** [comment]
+1 this. Would like a property like `"orientation": "portrait || landscape"`

**Comment by ZeldaZach** [comment]
I like the idea, I'll see what we can come up with in the future!

**Comment by KingSupernova31** [comment]
This should also apply to battles.
