### ISSUE TITLE
Include a field for misc icons

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#77]
Some cards have icons on them that denote something that's usually set-specific.

* Double-faced card front/back icons
* Future sight type icons
* Odyssey block "interacts with the graveyard" icon.

https://github.com/mtgjson/mtgjson/issues/228

**Comment by ZeldaZach** [comment]
Hmm... How does Scryfall address this? Is it in the API in someway? cc @csuhta

**Comment by csuhta** [comment]
Scryfall doesn't currently expose this information. We're considering some kind of "frame effect" field for things like these icons and things like the Nyx-touched and Miracle frames.

**Comment by ZeldaZach** [comment]
I'm gonna leave this open as an upstream issue then. Lets see who gets to it first :)

**Comment by tooomm** [comment]
This is related to https://github.com/mtgjson/mtgjson/issues/480 and https://github.com/mtgjson/mtgjson/issues/228

**Comment by ZeldaZach** [comment]
Doable with the new `frame_effects` Sf added (https://scryfall.com/docs/api/layouts). We need to come up with a way to make this useful linking to #76
