### ISSUE TITLE
Identify Tourney Promos

### ISSUE THREAD

**Issue by Lockheed-Dragon** [mtgjson/mtgjson#770]
Currently all "tourney" promos have the tag promoType == "tourney", this doesn't help identify the type of promo, for example, Mutavault has both a Grand Prix and a Champs promo, both are tagged in an identical fashion. If we are searching without the exact set code, this can cause some confusion.

Can we add identifiers like "tourney,grandprix" or "tourney,champs" similar to the way FNM promos are handled?

Thanks,
Lockheed

**Comment by ZeldaZach** [comment]
Hey Lockheed! Looking further at this, can you not just use the set name to determine the type?

**Comment by Lockheed-Dragon** [comment]
Hey Zach, you'll notice in the initial comment, that we may be searching without the exact set code. 
Though I can examine the set code of each card returned in my search and extrapolate from there, that's adding complexity that doesn't exist for other similar situations as noted above for FNM promos.

Consistency is king! :)

**Comment by ZeldaZach** [comment]
Since this hasn't seen much activity/interest, I'm going to close as a no-fix for the time being.
