### ISSUE TITLE
In AllPrintings.json, set legality depending on the printing

### ISSUE THREAD

**Issue by cognivore** [mtgjson/mtgjson#773]
## Clarification and Motivation

Currently, legality seems to be determined based on the most legal printing of a given card, as seen in this gold-bordered printing of Arcbound Ravager:

![Screenshot of well-structured JSON representing a gold-bordered Arcbound Ravager MTG card that has legality: modern, ...](https://user-images.githubusercontent.com/66186054/111262671-8c8a1d00-861c-11eb-9dbb-faf5a7bdfddd.png)

That makes for additional checks whilst working with AllPrintings.json.

## Acceptance criteria

 - [ ]  `legality` is calculated per-printing, not per-cardname.

**Comment by ZeldaZach** [comment]
Hey @cognivore I just double checked to confirm and legalities are determined on a per-printing basis as-is. Is there something I'm missing here?

**Comment by KingSupernova31** [comment]
Gold-bordered cards aren't legal in Modern.

**Comment by ZeldaZach** [comment]
Will dig further into this soon
