### ISSUE TITLE
Secret Lair Teferi, Hero of Dominaria missing artist attribution in AllPrintings

### ISSUE THREAD

**Issue by camfulton** [mtgjson/mtgjson#774]
#### Version(s) tested against

MTGJSON 5.1.0+20210316

#### Description of Bug
The Secret Lair Drop Teferi, Hero of Dominaria has an empty artist attribution.

The attribution on the card is "KNIIO".

**Comment by ZeldaZach** [comment]
This was fixed up a few weeks ago, thanks for the report!! :)
