### ISSUE TITLE
mcmIds missing for "buy a box"-promos

### ISSUE THREAD

**Issue by splatterb0y** [mtgjson/mtgjson#777]
Version: 5.1.0+20210322

"Athreos, Shroud-Veiled" a Buy a Box-Promo for THB does not have it's mcmId attached.
It should be mcmId 429026. This might be true for other BAB promos too.

**Comment by ZeldaZach** [comment]
Yep this appears to be an issue with mtgjson. will investigate further soon!

**Comment by splatterb0y** [comment]
The 2021 Judge Reward "The Gitrog Monster" - mcmId 557289 has the same issue.

**Comment by ZeldaZach** [comment]
This is a sub-ticket of #781

**Comment by ZeldaZach** [comment]
This has been addressed
