### ISSUE TITLE
Missing Kaldheim Art Series

### ISSUE THREAD

**Issue by lfgcampos** [mtgjson/mtgjson#778]
Kaldheim also has an Art Series.
Other sets have it included but Kaldheim not.

Link for reference: https://mtg.fandom.com/wiki/Kaldheim/Art_Series

**Comment by ZeldaZach** [comment]
Thanks for the report! Seems like these were missed upstream, I've left a note and we'll get to this soon :)

**Comment by lfgcampos** [comment]
Already include, thank you @ZeldaZach!

https://mtgjson.com/api/v5/AKHM.json
