### ISSUE TITLE
Restore foreignNames for the AllCards file

### ISSUE THREAD

**Issue by Sembiance** [mtgjson/mtgjson#78]
The 'foreignNames' field was changed in 3.0.0 to only be present and only include data for that specific set (prior to this it was identical for every card in every set, see Issue #12 )

For the 'AllCards' files however, it probably makes sense to restore the 'foreignNames' field so that it includes all available languages for the card, regardless of set, since the AllCards files don't care about sets. Right now this field is entirely missing

**Comment by bra1n** [comment]
Any news on this? :)

**Comment by phrozen** [comment]
I miss this field the most, I understand that foreignFields include the multiverseID of the card in the foreign language and that AllCards must not care about each set, but it should really have the possible names included. AllCards is said to be "quick and easy way to get basic card data" I really think that the card name is the most basic data one should have, and translations are really important.

**Comment by lsmoura** [comment]
I'll get into it, guys. I still need a couple of weeks tough. I'll need to rewrite the `generate.js` file altogether and this will be implemented in the rewrite.

**Comment by galaxyoyo** [comment]
A couple of weeks ? Will it be possible to put an update of all of the sets before, with all of your modifications ? It'll can help me with my app ...

**Comment by ZeldaZach** [comment]
Addressed in V4 :)
