### ISSUE TITLE
TSR Timeshifted cards are all "false"

### ISSUE THREAD

**Issue by nicho92** [mtgjson/mtgjson#780]
#### Version(s) tested against
MTGJSON 5.1.0+20210326

#### Description of Bug
all timeshifted cards in TimeSpiral Remastered have "isTimeshifted" attribute to false.

**Comment by ZeldaZach** [comment]
Thanks for the report! I've validated this issue and will work on a fix soon :)

**Comment by nicho92** [comment]
In the same Way , MH2 timeshifted cards to

![image](https://user-images.githubusercontent.com/11507615/122635736-e26fd480-d0e5-11eb-829b-ae1212aeb1cb.png)

**Comment by staghouse** [comment]
Should "isTimeshifted" be deprecated in favor of of new `rarity` value of `special`?

**Comment by nicho92** [comment]
For TSR expansion. It's ok, all timeshifted icon's set are purple... but in MH2 set, timeshifted cards have their own rarity (common, uncommon, rare, mythics, ...) . so i think keeping "isTimeshifted" with correct value is better solution.
![image](https://user-images.githubusercontent.com/11507615/133566242-c8c10dd9-1a3b-44e4-82af-0e86e7dfc319.png)

**Comment by kodawah** [comment]
i think the official card name from wotc for mh2 and mh1reprints is "Retro Frame" not "Timeshifted". I think it'd be fine to move the boolean value to the rarity section for TSP and TSR, and just leave the rest as is (being part of two different sets, there is no need to distinguish them with a boolean)
