### ISSUE TITLE
originalReleaseDate missing on Mesmeric Glare promo face

### ISSUE THREAD

**Issue by patrickgaskill** [mtgjson/mtgjson#782]
#### Version(s) tested against

MTGJSON 5.1.0+20210222

#### Description of Bug

The Mesmeric Glare adventure face on the PMEI promo is missing its originalReleaseDate, which exists on its other face Hypnotic Sprite.

Mesmeric Glare mtgjsonv4Id: `8d87b558-d73f-5f11-92ca-0d813c3af60b`

**Comment by ZeldaZach** [comment]
Thanks for the report. I've validated the issue. Will look into a fix soon!
