### ISSUE TITLE
wrong translation for Vesuvan Doppelganger 

### ISSUE THREAD

**Issue by gweniche** [mtgjson/mtgjson#788]
Hi,

they re is a wrong translation for Vesuvan Doppelganger  in french for the set Foreign Black Border and Revised Edition, actually its Mutaforme Vesuvano but for french should be 'DOPPELGANGER VÉSUVÉEN'.

thx

**Comment by ZeldaZach** [comment]
Thanks for the report! I've validated the claim and filed it upstream. Should be fixed soon :)

**Comment by staghouse** [comment]
This looks to be resolved. Can you confirm @gweniche?

**Comment by gweniche** [comment]
> This looks to be resolved. Can you confirm @gweniche?

Perfect, thx a lot.
