### ISSUE TITLE
Add special guest gift cards

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#79]
Add the rest of the special guest gift cards. Robot Chicken is already included, but the others are not.

https://www.magiclibrarities.net/798-rarities-special-guest-gift-cards-english-cards-index.html

**Comment by ZeldaZach** [comment]
I'd call this an upstream issue cc: @csuhta

**Comment by ZeldaZach** [comment]
cc: @jhallbachner

**Comment by ancestral** [comment]
It might be good to determine what is a card. For example, [there was a MTG Japan-only game on the Sega Dreamcast](https://mtg.gamepedia.com/Magic:_The_Gathering_(Dreamcast)) that had some truly unusual effects.

**Comment by ZeldaZach** [comment]
I'd call it a card, since we have 1996 World Championship as an example

**Comment by ZeldaZach** [comment]
This is also a fully upstream thing, as I won't be fixing it locally anytime soon
