### ISSUE TITLE
Wrong translation for CONFRONTEZ LES TÉNÈBRES set

### ISSUE THREAD

**Issue by gweniche** [mtgjson/mtgjson#791]
Hi,

they re is a wrong translation for Eldritch Moon in french for the set, actually its CONFRONTEZ LES TÉNÈBRES but for french should be 'Lune Hermétique'.

thx

**Comment by ZeldaZach** [comment]
Hi @gweniche ! I'm not sure I understand the issue. Should the French translation of Eldrich Moon be "CONFRONTEZ LES TÉNÈBRES" or "Lune Hermétique" ?

**Comment by gweniche** [comment]
It's " La Lune Hermétique ".
