### ISSUE TITLE
Add manaValue field

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#793]
Converted mana cost has been renamed to mana value. All fields referencing it in the JSON should eventually be updated. This is a breaking change, so it would probably be best to add duplicate `manaValue` fields and leave `convertedManaCost` around until the next major update.

**Comment by ZeldaZach** [comment]
Your proposed solution makes sense, but I'm very hesitant of renaming such a "critical" field until we ensure our audience is well informed. Will look at adding manaValue, but CMC will be lingering until v6 most likely.
