### ISSUE TITLE
STX promo cards

### ISSUE THREAD

**Issue by valentinoredo** [mtgjson/mtgjson#797]
Version: MTGJSON v5.1.0+20210503

Hi,
in STX Set json file there are some cards which have the same mcmid. 
For example:
Fracture, number 188, mcmid 558037
Fracture, number 378, mcmid 558037

I'm not expert about MTGJSON files but I think it's an error as they are two distinct cards and on mkm there are two cards, one for main set, one for promo set

**Comment by ZeldaZach** [comment]
This was addressed on May 17th, forgot to close ticket (was handled upstream). Sorry for the delay in response!
