### ISSUE TITLE
mcmid on STA Set

### ISSUE THREAD

**Issue by lafadot** [mtgjson/mtgjson#798]
MTGJSON Ver: v5.1.0+20210503

Hi,
I noticed that for STA Set, only 8 of 126 cards have an mcmId. Is it right ? I guess almost all cards should have an mcmid, isnt it?
I also know that MagicMarket APIs are facing some issues, maybe it's related to the actual API fault?

Thank you

**Comment by Samurus** [comment]
Hi, 
I just found this project but I did some research with scryfall and MCM. Here is some related information which might help:

I figured that scryfall has about 59k "products" while only 45k have a cardmarketId. Multiple Issues come together here:
Problem 1 - unmapped Set codes:  MCMcombines multiple sets to one set. I think around 300 sets are missing or have another code there. 
Problem 2 - different card numbers for cards without number. Scryfall has e.g. 3 different Swamps for old sets and assign card numbers 61,62,63. These combinations have 3 different scryfall-ids. On MCM they have just one productId but 3 different numbers 55,56,57. These kind of Products need manual mappings.

Im pretty sure those problems occur here as well since cardnumbers are not used in the "identifiers data". 
Not sure if anyone has done the full mapping. But sadly this project isnt finished with it yet. Maybe we can contribute in future:) 

update: Following cardmarket-ProductIds have multiple scryfall-mappings (id,count):
	9987,2;16936,3;16938,3;9380,2;5852,2;9639,2;18821,2;18822,2;10052,2;9615,2;9616,2;10177,2;10074,2;10076,2;16935,3;9414,2;18819,2;18085,3;6907,2;18077,3;16934,3;18818,2;10124,2;10022,2;18820,2;18069,3;9402,2;16937,3;18825,2;10057,2;18096,3;10015,2;18061,3;18823,2;9374,2;18824,2;9604,2;9446,2;10043,2;9622,2;10025,2;8138,2;9411,2;

problem 2 example:
https://api.scryfall.com/cards/026cdd68-9a0e-4261-9390-e8abbcd378ba
https://api.scryfall.com/cards/7bfc4649-734d-4140-821c-bfff56c5decf
https://api.scryfall.com/cards/2d534484-6ed0-4b8e-8410-f8861fd8b5a9
they have the card numbers 59,60,61

on mcm they share the code 18096, 18097, 18098 but numbers 53,54,55


related issue: https://github.com/mtgjson/mtgjson/issues/624

**Comment by Samurus** [comment]
List of Scryfall Sets with missing cardmarket product id mappings :

aznr, Zendikar Rising Art Series
wc04, World Championship Decks 2004
oc20, Commander 2020 Oversized
anb, Arena Beginner Set
trna, Ravnica Allegiance Tokens
ddr, Duel Decks: Nissa vs. Ob Nixilis
tmm3, Modern Masters 2017 Tokens
j13, Judge Gift Cards 2013
phel, Open the Helvault
pana, MTG Arena Promos
oc15, Commander 2015 Oversized
wc99, World Championship Decks 1999
htr19, 2019 Heroes of the Realm
tcma, Commander Anthology Tokens
tgk1, GRN Guild Kit Tokens
tmor, Morningtide Tokens
l12, League Tokens 2012
xana, Arena New Player Experience Extras
stx, Strixhaven: School of Mages
f12, Friday Night Magic 2012
kld, Kaladesh
leg, Legends
tcon, Conflux Tokens
tcmr, Commander Legends Tokens
pmps08, Magic Premiere Shop 2008
f17, Friday Night Magic 2017
tavr, Avacyn Restored Tokens
g11, Judge Gift Cards 2011
pd3, Premium Deck Series: Graveborn
tstx, Strixhaven: School of Mages Tokens
prm, Magic Online Promos
aer, Aether Revolt
ddo, Duel Decks: Elspeth vs. Kiora
trtr, Return to Ravnica Tokens
tddi, Duel Decks: Venser vs. Koth Tokens
tddj, Duel Decks: Izzet vs. Golgari Tokens
me2, Masters Edition II
psoi, Shadows over Innistrad Promos
tdtk, Dragons of Tarkir Tokens
leb, Limited Edition Beta
ddn, Duel Decks: Speed vs. Cunning
vma, Vintage Masters
wc98, World Championship Decks 1998
s00, Starter 2000
tuma, Ultimate Masters Tokens
txln, Ixalan Tokens
tust, Unstable Tokens
pkhm, Kaldheim Promos
plist, The List
oc14, Commander 2014 Oversized
tddh, Duel Decks: Ajani vs. Nicol Bolas Tokens
tpr, Tempest Remastered
ha3, Historic Anthology 3
tktk, Khans of Tarkir Tokens
ha5, Historic Anthology 5
pmei, Magazine Inserts
tddm, Duel Decks: Jace vs. Vraska Tokens
togw, Oath of the Gatewatch Tokens
ha1, Historic Anthology 1
tgvl, Duel Decks Anthology: Garruk vs. Liliana Tokens
ody, Odyssey
tc17, Commander 2017 Tokens
tdds, Duel Decks: Mind vs. Might Tokens
akhm, Kaldheim Art Series
tddd, Duel Decks: Garruk vs. Liliana Tokens
tm21, Core Set 2021 Tokens
ddm, Duel Decks: Jace vs. Vraska
tdd2, Duel Decks: Jace vs. Chandra Tokens
ogw, Oath of the Gatewatch
tgrn, Guilds of Ravnica Tokens
4bb, Fourth Edition Foreign Black Border
shm, Shadowmoor
phuk, Hachette UK
pm21, Core Set 2021 Promos
10e, Tenth Edition
tfth, Face the Hydra
tkhm, Kaldheim Tokens
tm12, Magic 2012 Tokens
pcel, Celebration Cards
akr, Amonkhet Remastered
tm19, Core Set 2019 Tokens
oc13, Commander 2013 Oversized
past, Astral Cards
tddk, Duel Decks: Sorin vs. Tibalt Tokens
jvc, Duel Decks Anthology: Jace vs. Chandra
tddl, Duel Decks: Heroes vs. Monsters Tokens
tcn2, Conspiracy: Take the Crown Tokens
tkld, Kaladesh Tokens
tbbd, Battlebond Tokens
hop, Planechase
tmm2, Modern Masters 2015 Tokens
wc02, World Championship Decks 2002
ocm1, Commander's Arsenal Oversized
dvd, Duel Decks Anthology: Divine vs. Demonic
cei, Intl. Collectors’ Edition
ddp, Duel Decks: Zendikar vs. Eldrazi
f18, Friday Night Magic 2018
tisd, Innistrad Tokens
tnph, New Phyrexia Tokens
3ed, Revised Edition
tsr, Time Spiral Remastered
pgpx, Grand Prix Promos
tjou, Journey into Nyx Tokens
ps11, Salvat 2011
tgn2, Game Night 2019 Tokens
pmic, MicroProse Promos
soi, Shadows over Innistrad
t10e, Tenth Edition Tokens
tmh1, Modern Horizons Tokens
emn, Eldritch Moon
ajmp, Jumpstart Arena Exclusives
thp3, Journey into Nyx Hero's Path
cma, Commander Anthology
fmb1, Mystery Booster Retail Edition Foils
tddg, Duel Decks: Knights vs. Dragons Tokens
mb1, Mystery Booster
plny, 2018 Lunar New Year
pr2, Magic Player Rewards 2002
tevg, Duel Decks Anthology: Elves vs. Goblins Tokens
fbb, Foreign Black Border
tima, Iconic Masters Tokens
tjvc, Duel Decks Anthology: Jace vs. Chandra Tokens
znr, Zendikar Rising
8ed, Eighth Edition
taer, Aether Revolt Tokens
teve, Eventide Tokens
tfrf, Fate Reforged Tokens
thb, Theros Beyond Death
me1, Masters Edition
td2, Duel Decks: Mirrodin Pure vs. New Phyrexia
sta, Strixhaven Mystical Archive
tbth, Battle the Horde
oc16, Commander 2016 Oversized
inv, Invasion
tdgm, Dragon's Maze Tokens
tm13, Magic 2013 Tokens
tbfz, Battle for Zendikar Tokens
wc03, World Championship Decks 2003
l13, League Tokens 2013
me4, Masters Edition IV
v10, From the Vault: Relics
tgtc, Gatecrash Tokens
tlrw, Lorwyn Tokens
mgb, Multiverse Gift Box
pres, Resale Promos
ovnt, Vintage Championship
4ed, Fourth Edition
ddl, Duel Decks: Heroes vs. Monsters
avr, Avacyn Restored
tdd1, Duel Decks: Elves vs. Goblins Tokens
khm, Kaldheim
pemn, Eldritch Moon Promos
l16, League Tokens 2016
tpca, Planechase Anthology Tokens
tc16, Commander 2016 Tokens
tc21, Commander 2021 Tokens
c21, Commander 2021
tmed, Mythic Edition Tokens
olgc, Legacy Championship
psdg, Sega Dreamcast Cards
mznr, Zendikar Rising Minigames
psal, Salvat 2005
astx, Strixhaven Art Series
tc19, Commander 2019 Tokens
v17, From the Vault: Transform
trix, Rivals of Ixalan Tokens
pz2, Treasure Chest
pz1, Legendary Cube Prize Pack
tm15, Magic 2015 Tokens
tths, Theros Tokens
t2xm, Double Masters Tokens
tiko, Ikoria: Lair of Behemoths Tokens
wc00, World Championship Decks 2000
tcm2, Commander Anthology Volume II Tokens
iko, Ikoria: Lair of Behemoths
tm10, Magic 2010 Tokens
oc19, Commander 2019 Oversized
klr, Kaladesh Remastered
pbfz, Battle for Zendikar Promos
wc01, World Championship Decks 2001
prix, Rivals of Ixalan Promos
gs1, Global Series Jiang Yanggu & Mu Yanling
ttsr, Time Spiral Remastered Tokens
l17, League Tokens 2017
oc21, Commander 2021 Display Commanders
tthb, Theros Beyond Death Tokens
m21, Core Set 2021
td0, Magic Online Theme Decks
tznr, Zendikar Rising Tokens
j12, Judge Gift Cards 2012
arc, Archenemy
2ed, Unlimited Edition
7ed, Seventh Edition
tm20, Core Set 2020 Tokens
mpr, Magic Player Rewards 2001
mh2, Modern Horizons 2
tala, Shards of Alara Tokens
dpa, Duels of the Planeswalkers
tema, Eternal Masters Tokens
twar, War of the Spark Tokens
por, Portal
ha4, Historic Anthology 4
p04, Magic Player Rewards 2004
pcy, Prophecy
tori, Magic Origins Tokens
ppro, Pro Tour Promos
psus, Junior Super Series
l15, League Tokens 2015
tmbs, Mirrodin Besieged Tokens
tdom, Dominaria Tokens
tddf, Duel Decks: Elspeth vs. Tezzeret Tokens
ocmd, Commander 2011 Oversized
ha2, Historic Anthology 2
j21, Judge Gift Cards 2021
tdka, Dark Ascension Tokens
tsoi, Shadows over Innistrad Tokens
ana, Arena New Player Experience
lea, Limited Edition Alpha
6ed, Classic Sixth Edition
ta25, Masters 25 Tokens
tdag, Defeat a God
tc20, Commander 2020 Tokens
rqs, Rivals Quick Start Set
oc18, Commander 2018 Oversized
ppc1, M15 Prerelease Challenge
fjmp, Jumpstart Front Cards
tund, Unsanctioned Tokens
j16, Judge Gift Cards 2016
tc15, Commander 2015 Tokens
pwp21, Wizards Play Network 2021
sznr, Zendikar Rising Substitute Cards
tzen, Zendikar Tokens
bfz, Battle for Zendikar
tm11, Magic 2011 Tokens
l14, League Tokens 2014
tkhc, Kaldheim Commander Tokens
afr, Adventures in the Forgotten Realms
sld, Secret Lair Drop
cst, Coldsnap Theme Decks
tc18, Commander 2018 Tokens
oc17, Commander 2017 Oversized
jmp, Jumpstart
takh, Amonkhet Tokens
ust, Unstable
pl21, 2021 Lunar New Year
p03, Magic Player Rewards 2003
5ed, Fifth Edition
tmd1, Modern Event Deck 2014 Tokens
ddq, Duel Decks: Blessed vs. Cursed
gvl, Duel Decks Anthology: Garruk vs. Liliana
ced, Collectors’ Edition
tarb, Alara Reborn Tokens
tm14, Magic 2014 Tokens
pred, Redemption Program
slu, Secret Lair: Ultimate Edition
wc97, World Championship Decks 1997
teld, Throne of Eldraine Tokens
tddt, Duel Decks: Merfolk vs. Goblins Tokens
pc2, Planechase 2012
eld, Throne of Eldraine
htr18, 2018 Heroes of the Realm
te01, Archenemy: Nicol Bolas Tokens
pstx, Strixhaven: School of Mages Promos
e02, Explorers of Ixalan
dkm, Deckmasters
unh, Unhinged
tugl, Unglued Tokens
tgk2, RNA Guild Kit Tokens
arn, Arabian Nights
tbng, Born of the Gods Tokens
amh1, Modern Horizons Art Series
tznc, Zendikar Rising Commander Tokens
thou, Hour of Devastation Tokens
tddu, Duel Decks: Elves vs. Inventors Tokens
sum, Summer Magic / Edgar
hho, Happy Holidays
tshm, Shadowmoor Tokens
ren, Renaissance
tdvd, Duel Decks Anthology: Divine vs. Demonic Tokens
usg, Urza's Saga
twwk, Worldwake Tokens
tdde, Duel Decks: Phyrexia vs. the Coalition Tokens
ddf, Duel Decks: Elspeth vs. Tezzeret
me3, Masters Edition III
troe, Rise of the Eldrazi Tokens
tsom, Scars of Mirrodin Tokens
tddc, Duel Decks: Divine vs. Demonic Tokens
tcns, Conspiracy Tokens
tmma, Modern Masters Tokens
ptc, Pro Tour Collector Set
pmoa, Magic Online Avatars
tc14, Commander 2014 Tokens
oana, Arena New Player Experience Cards

**Comment by ZeldaZach** [comment]
Hi @lafadot I just checked and confirmed we now have all the MCM IDs for STA set :)

@Samurus Thanks for taking the time to provide all that information! If I missed any of it on my imports, do let me know in a new ticket. 

This ticket is now resolved :)
