### ISSUE TITLE
future sealed work

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#799]
tracking bug for some sealed work I'd like to see before public release

- [x] if appropriate, add number of boosters in the box
- [x] add a category field - we need to be able to understand whether a product is a booster box/booster pack/deck/special set
- [x] add a decklist reference - for set with defined decklists we need references to the cards contained or links to additional resources
- [ ] add an image link - so that sites can publish the data
- [x] add missing product - currently tcg covers most products, but there are a bunch of missing ones
  - [ ] a bunch of old theme decks (visions, morningtide etc)
  - [ ] various starter decks and intro packs
  - [ ] a lot of sealed boxes, such as mythic edition, theme deck boxes
- [ ] add missing editions - some editions do not map easily to scryfall models, in particular 
  - [ ] https://www.tcgplayer.com/search/all/product?q=Duels%20of%20the%20Planeswalkers 
  - [ ] https://www.tcgplayer.com/search/magic/world-championship-decks?productLineName=magic&setName=world-championship-decks&ProductTypeName=Sealed%20Products&page=1
  - [ ] https://www.tcgplayer.com/search/magic/spellslinger-starter-kit?productLineName=magic&setName=spellslinger-starter-kit
  - [ ] https://www.tcgplayer.com/search/magic/challenger-decks?productLineName=magic&setName=challenger-decks
  - [ ] https://www.tcgplayer.com/search/magic/gift-boxes-and-promos?productLineName=magic&setName=gift-boxes-and-promos
  - [ ] https://shop.tcgplayer.com/magic/mythic-edition-war-of-the-spark/war-of-the-spark-mythic-edition
  - [ ] https://shop.tcgplayer.com/magic/mythic-edition-ravnica-allegiance/ravnica-allegiance-mythic-edition
- [x] fixup a few typos and improve naming consistency
  - [x] "Devestation", "Rambler", "Artufl"
  - [x] a bunch of decks use the color instead of the actual deck name
  - [x] intro pack sets sometimes use "all 5 intro packs" and sometimes use "set of 5"
  - [x] expose `productSize` for `booster` product types too

**Comment by staghouse** [comment]
assuming you're talking about `sealedProduct` - `releaseDate` may return null, is this intentional?

**Comment by kodawah** [comment]
@staghouse yes i'm referring to the new element. I think `releaseDate` is just what tcg reports, we probably should strip empty values though (cc @tpblaster)

**Comment by taw** [comment]
Is this about decklists?

If you have any specific issues related to decklists, report them at https://github.com/taw/magic-preconstructed-decks

There one repo for that data: https://github.com/taw/magic-preconstructed-decks

And repo I used to export processed json: https://github.com/taw/magic-preconstructed-decks-data

**Comment by kodawah** [comment]
> Is this about decklists?

@taw yes, trying to associate sets and decklists together, not sure whether we should duplicate the list of ids or provide an external reference to them

the links looks useful, thanks for sharing them

**Comment by ZeldaZach** [comment]
I haven't thought about this ticket in a while, will push off for now. I know @tpblaster set up the original products setup, will see if they can assist further and/or provide more context

**Comment by taw** [comment]
Well, let me know if you need some assistance from me. My decklists are associated with sets, and generally have names which match product name exactly.

**Comment by kodawah** [comment]
@taw I appreciate the offer, I think the only missing link on the decklist points is understanding which decklist belongs to which product. I was thinking we could associate a list of decklist names under each product entry so that they can be optionally retrieved. But not sure how to do that except manually keep track of things...

example

```json
 "sealedProduct": [
        {
          "identifiers": {
            "tcgplayerProductId": "210821"
          },
          "name": "Commander 2020 Deck Ruthless Regiment",
          "purchaseUrls": {
            "tcgplayer": "https://mtgjson.com/links/0e80e820012f220c"
          },
          "releaseDate": "2020-05-15",
          "decklists": [
              "RuthlessRegiment_C20"
          ],
          "uuid": "3a1bf02e-8e9d-5304-95ac-c37ff4dd39b0"
        },
        {
          "identifiers": {
            "tcgplayerProductId": "210830"
          },
          "name": "Commander 2020 Set of 5",
          "purchaseUrls": {
            "tcgplayer": "https://mtgjson.com/links/ea420d78d780885e"
          },
          "releaseDate": "2020-05-15",
          "decklists": [
              "ArcaneMaelstrom_C20",
              "SymbioticSwarm_C20",
              "TimelessWisdom_C20",
              "EnhancedEvolution_C20",
              "RuthlessRegiment_C20"
          ],
          "uuid": "af2f7b4d-a486-50ad-b27b-2488ab6d63de"
        }
```

So that we can retrieve them by looking up decklist name + "https://mtgjson.com/api/v5/decks/" for example

Alternatively we could use a separate type to keep the name separate and the full url embedded in it. Perhaps listing additional properties like

```json
"decklists": [
    {
        "name": "Arcane Maelstrom",
        "url": "https://mtgjson.com/api/v5/decks/ArcaneMaelstrom_C20.json",
        "deckSize": 100
    }
````

Happy to hear your thoughts on it

**Comment by ZeldaZach** [comment]
@taw Hey mate, been looking into this a bit and had a request.

Currently, each MTG Set we publish has a `sealedProduct` field, of which each product has a UUID associated. For deck-like products (Commander Decks, Starter Decks, etc), is it possible you can update the deck file to include a reference to the entry in MTGJSON? Ex: https://mtgjson.com/api/v5/decks/RuthlessRegiment_C20.json should say `uuid: 3a1bf02e-8e9d-5304-95ac-c37ff4dd39b0` to link back to C20.json's sealedProduct file. 

One approach we could take is to search the XXX.json file based on the file ending of your deck lists, then regex finding the appropriate fuzzy name to match. Let me know if this makes sense / is doable. If not, I can possibly look into handling it on our side.

**Comment by taw** [comment]
I can take a look. No idea how many will actually match.

**Comment by taw** [comment]
@ZeldaZach I created issue for this. https://github.com/taw/magic-search-engine/issues/160

With results of match by name. Let's discuss it there.

**Comment by mallardduck** [comment]
Didn't want to create a new issue for it since it's relevant to this topic. I'm wondering if we could add a count/size field onto the Booster data. This way it's much easier to know how many cards are in each pack type. I can see that for now the booster pack data seems to come from @taw via their repo - so really maybe this would be an addition for me to ask be added there?

**Comment by taw** [comment]
cc: @axxroytovu 

There are occasional boosters that don't have constant number of cards in the data, because some objects that could be in boosters (like tokens, checklists, art cards, marketing cards) are not represented. But it's almost right.

**Comment by mallardduck** [comment]
Yeah that inconsistency is why I was hoping for a new field for count. Even if reality may vary based on non-playable cards, i'm hoping for a simple way to know how many cards a pack claims to contain. (i.e. the value printed on the front of packs)

I know I can probably just pick a pack config to count (and sum) the items within the `*.boosters.content` today to get the number of cards - however hoping to avoid that. Something like adding a `nominal_quantity` onto the `Booster` abstract model. This way each booster type `default`, `set`, etc can present the "normal" card quantity advertised on each pack.

**Comment by axxroytovu** [comment]
Packs have so many variations now that I've mostly been compiling each "pack variation" separately and choosing from that. Is there a particular reason that you need set boosters to tell you exactly 11 instead of "11 or 12" or 11.25?

**Comment by mallardduck** [comment]
Well in general my hope would be that I can fetch the quantity of units (cards, packs, boxes, etc) are in all sealed products. The booster packs were just my primary focus - as "card" is the smallest unit with boosters being the next most common unit of measure.

Knowing how many cards are in a given product can allow you to compute "cost per card" from a booster, or "cost per pack" from a box. Similarly, if you know how many cards are in each pack, and cards per pack - one could even calculate "Cost per Card" for a box of boosters. In this context the resale value of cards doesn't matter - merely the quantities of the measured units.

I suppose if there's not much interest in that within this project I'll just build that into my app code instead. However I thought something like this would have benefits for more people than myself.

**Comment by axxroytovu** [comment]
Yeah so it sounds like you're actually looking for the EV number of cards, right? So a set booster on average has 11.25 cards, so in a box of 30 boosters you'd expect to get 337.5 cards. Is that correct?

**Comment by mallardduck** [comment]
> EV number of cards

I can see how that number would be useful as well - perhaps more useful in some contexts than what I'm asking for. However I'm asking for something much more simple than that, what I want is just the retail card counts.

So for Set Boosters that number is 12; for Draft 15; Collector packs 15; and the new epilogue packs are 5. Similarly, most commander precons claim to include 100 - yet often might include more; again packs were my primary focus for now though. However I will also take in account exceptions to this like MAT (MOM aftermath) collectors only including 6 cards.

Edit: Another way to frame what I'm asking for - currently on the SealedProducts data the only products that have a `productSize` set `booster_boxes`. In general I'm wondering if we could work to populate that value for more product categories and items. If there is too much potential variation for this to be worth it I understand and will just implement within my App.

**Comment by axxroytovu** [comment]
I'm already working on building out the product size map here: https://github.com/mtgjson/mtgjson/pull/1061

Once that gets incorporated, feel free to let me know if there's a way I can improve it for what you're trying to do.

**Comment by kodawah** [comment]
in theory one could derive that information from the Booster data distribution, but adding a `productSize` entry for `booster` does seem nice and easy to have

i'll add it to the tasks above

**Comment by axxroytovu** [comment]
@mallardduck Does the solution here provide what you need? https://github.com/mtgjson/mtgjson/pull/1061#issuecomment-1529935404

@kodabb brought up that overloading `product_size` to mean too many things is not ideal.

**Comment by mallardduck** [comment]
@axxroytovu - yes that solution provided in your comment could work well. As explained I was already under the assumption that `product_size` had a polymorphic meaning and the base unit had to be derived by other fields. So your proposal seems to be much more clear cut.

**Comment by mallardduck** [comment]
Hello! I just came across a new inconsistency with sealed products and wanted to report it here. It's related to the logic I'm working on that involves the product's category and subtype. Specifically, I've noticed some inconsistencies with the commander-related products that don't align with my expectations.

For instance, when it comes to boxes/cases of decks for a set, some of them have the correct category of `case`, but are missing the `subtype`, which, in my opinion, should likely be `commander_deck`. This makes more sense to me because what you're buying is a case or bundle of decks. Similarly, if a product has the commander_deck category, it can imply that it's a single deck.

I do want to highlight a few examples I think are really stellar schemas. These are entries that I think could be the "standard" schema for this use case. Specifically the Brothers' War products:

```
# From SetList.json
  {
    "category": "case",
    "contents": {
      "sealed": [
        {
          "count": 1,
          "name": "The Brothers War Commander Deck Urzas Iron Alliance",
          "set": "brc"
        },
        {
          "count": 1,
          "name": "The Brothers War Commander Deck Mishras Burnished Banner",
          "set": "brc"
        }
      ]
    },
    "identifiers": {
      "cardKingdomId": "267928",
      "tcgplayerProductId": "449724"
    },
    "name": "The Brothers' War Commander Deck Set of 2",
    "purchaseUrls": {
      "cardKingdom": "https://mtgjson.com/links/ad11948cb0cd302a",
      "tcgplayer": "https://mtgjson.com/links/c0314a50e2867431"
    },
    "releaseDate": "2022-11-18",
    "subtype": "",
    "uuid": "10c30ba1-9139-599a-89b4-20e49ae96fc3"
  },
```

I really like having the contents listed - in situations where you are buying a case that's a repeat of the "Set of 2" this can be super helpful. I like that it includes the count of each item in the case - these can be iterated over and summed for a total quantity. Only things I'd like to see different is: the `subtype` set to `commander_deck` or `collector_commander_deck`;  a `uuid` included on items within contents (when possible).

Moreover, I wanted to propose a potential improvement that could benefit not only commander-related things but also have wider applicability. Perhaps transforming subtype into a tag-based system could make it easier to identify the contents of cases. For example, a case of collector boosters could have subtypes like `["booster_box", "collector"]`, and similarly, the example I mentioned above could be `["commander_deck", "collector"]`. Thanks!

**Comment by axxroytovu** [comment]
Good catch. I think they're all supposed to use the tag `deck_box` for "boxes of preconstructed decks" but you're correct that they aren't getting flagged correctly. 

If you want to help add contents, I'm slowly working that data entry [over here](https://github.com/mtgjson/mtg-sealed-content).

Here's my list of to-do improvements that I'm actively trying to work on. If you find anything else let me know and I'll add it to the list.

- [x] Fix product category tagging and move to centralized code location
- [x] Add UUID to product contents
- [x] Filter out non-WOTC products, like [these](https://www.cardkingdom.com/catalog/search?search=header&filter%5Bname%5D=pure+bulk).
- [x] Figure out how to fix/move products between sets, like [this product](https://www.tcgplayer.com/product/449721/magic-dominaria-united-the-brothers-war-jumpstart-booster-box-case?xid=pi1b12b274-a00f-4ec6-a9a8-fbbf5c2a8032&page=1&Language=English).
- [x] Strip `Universes Beyond` per https://github.com/mtgjson/mtgjson/pull/1061#discussion_r1197021479

**Comment by mallardduck** [comment]
> Figure out how to fix/move products between sets, like [this product](https://www.tcgplayer.com/product/449721/magic-dominaria-united-the-brothers-war-jumpstart-booster-box-case?xid=pi1b12b274-a00f-4ec6-a9a8-fbbf5c2a8032&page=1&Language=English).

So for those type of things my personal preference is to fix the source of truth first; and only when unable to do that work around the issue with monkey patching. That in mind I've reported the issue with that product and it has opened a case with TCGplayer support. 🤞 Hopefully they'll help address that issue for us on their side since it seems to just be one seller who accidentally (or maybe intentionally for "keyword stuffing") mislabeled the product.

**Comment by axxroytovu** [comment]
Ok, I've made all of my updates that I wanted on this end. @kodabb what are you still missing? 

> add missing editions - some editions do not map easily to scryfall models, in particular

This is its own issue in https://github.com/mtgjson/mtgjson/issues/1070

> add a decklist reference - for set with defined decklists we need references to the cards contained or links to additional resources
> expose `productSize` for `booster` product types too

Slowly building up this reference link in https://github.com/mtgjson/mtg-sealed-content. Also includes `cardCount` parameter.

> add missing product - currently tcg covers most products, but there are a bunch of missing ones

Pulling cards from CardKingdom fixed a lot of this, otherwise I'm loading in products manually in https://github.com/mtgjson/mtg-sealed-content

> add an image link - so that sites can publish the data

TBD. I don't know where to pull that from if you want to figure out how to do this.

**Comment by kodawah** [comment]
> TBD. I don't know where to pull that from if you want to figure out how to do this.

what i have been doing is `https://product-images.tcgplayer.com/$tcgplayerProductId.jpg`, but i am a bit hesitant to standardize it since it's not officially supported by tcg

> Ok, I've made all of my updates that I wanted on this end. @kodabb what are you still missing?

I think mostly the decklists in the allprintings file, that is being addressed in other tickets. I think once that gets merged we can probably close this bug and reassess what's is missing

**Comment by kodawah** [comment]
i think this ticket can be closed since most points have been implement in mtg-sealed-data
