### ISSUE TITLE
uuid duplicate found (split cards)

### ISSUE THREAD

**Issue by bcattaneo** [mtgjson/mtgjson#80]
E.g.:
* ae155ee2-008f-4dc6-82bf-476be7baa224 (_Archangel Avacyn_ and _Avacyn, the Purifier_)
* 1001e708-e4f9-456a-8b9d-3421a2a3833d (_Avacynian Missionaries_ and _Lunarch Inquisitors_)

**Comment by ZeldaZach** [comment]
Seems to be a lot of issues with split cards... I'm considering re-doing them again to try and solve all of the major issues.

**Comment by bcattaneo** [comment]
Full report: http://cattaneo.uy/private/mtgjsonv4_duplicate_uuid.txt

**Comment by ZeldaZach** [comment]
Fix Proposal: Leave one UUID the same, and for the other one increment the last byte by one to get a new UUID.
```
Archangel Avacyn: ae155ee2-008f-4dc6-82bf-476be7baa224
Avacyn, the Purifier: ae155ee2-008f-4dc6-82bf-476be7baa225
```
