### ISSUE TITLE
CC1 Missing Multiverse IDs

### ISSUE THREAD

**Issue by AEFeinstein** [mtgjson/mtgjson#802]
#### Version(s) tested against
v5.1.0+20210526

#### Description of Bug
Commander Collection: Green does not have multiverse IDs listed, but they do exist on Gatherer:
https://gatherer.wizards.com/Pages/Search/Default.aspx?set=[%22Commander+Collection%3a+Green%22]

It's a small set, so here are the missing multiverse IDs:
```
509339	Bane of Progress
509344	Command Tower
509337	Freyalise, Llanowar's Fury
509338	Omnath, Locus of Mana
509340	Seedborn Muse
509343	Sol Ring
509341	Sylvan Library
509342	Worldly Tutor
```

**Comment by staghouse** [comment]
This looks to be resolved. Can you confirm @AEFeinstein

**Comment by staghouse** [comment]
Confirmed offline that this is resolved.
