### ISSUE TITLE
Duplicate UUID in MH2 JSON version 

### ISSUE THREAD

**Issue by SteveLGK** [mtgjson/mtgjson#803]
#### Version(s) tested against
  "meta": {
    "date": "2021-05-30",
    "version": "5.1.0+20210530"
  },

#### Description of Bug

The following card appears twice. From my comparison (eyes only), there are no differences. Even the UUID is the same.

     {
        "artist": "Steven Belledin",
        "availability": [ "mtgo", "paper" ],
        "borderColor": "black",
        "colorIdentity": [ "R" ],
        "colors": [ "R" ],
        "convertedManaCost": 4.0,
        "edhrecRank": 5978,
        "flavorText": "\"What are the odds, indeed?\"\n—Yursi, to Desera",
        "foreignData": [],
        "frameVersion": "2015",
        "hasFoil": true,
        "hasNonFoil": true,
        "identifiers": {
          "cardKingdomId": "246209",
          "mcmId": "566174",
          "mcmMetaId": "921",
          "mtgjsonV4Id": "646f40c1-d41f-5756-b1c5-30cdbcb5b698",
          "scryfallId": "49a4b0c9-a35b-4b55-ab27-7246bbca0d16",
          "scryfallIllustrationId": "6f5b7422-3f74-46b3-860f-996cf9bb4f3b",
          "scryfallOracleId": "8bd33b5c-0777-41ef-9e17-fb30ce69ec25",
          "tcgplayerProductId": "239665"
        },
        "isReprint": true,
        "layout": "normal",
        "legalities": {
          "commander": "Legal",
          "duel": "Legal",
          "legacy": "Legal",
          "premodern": "Legal",
          "vintage": "Legal"
        },
        "manaCost": "{2}{R}{R}",
        "name": "Chance Encounter",
        "number": "277",
        "printings": [ "MH2", "ODY" ],
        "purchaseUrls": {
          "cardKingdom": "https://mtgjson.com/links/aa5c7636de654522",
          "cardmarket": "https://mtgjson.com/links/a0a112d477fd07a2",
          "tcgplayer": "https://mtgjson.com/links/7da8317de1295ba0"
        },
        "rarity": "rare",
        "rulings": [
          {
            "date": "2009-02-01",
            "text": "You can only win a coin flip if you are the player flipping the coin. Your opponent losing a flip does not count as you winning one. This is a reversal of previous rulings."
          }
        ],
        "setCode": "MH2",
        "subtypes": [],
        "supertypes": [],
        "text": "Whenever you win a coin flip, put a luck counter on Chance Encounter.\nAt the beginning of your upkeep, if Chance Encounter has ten or more luck counters on it, you win the game.",
        "type": "Enchantment",
        "types": [ "Enchantment" ],
        "uuid": "22aed906-f3cc-548b-b24f-c8881d3d41e3",
        "watermark": "set"
      },
      {
        "artist": "Steven Belledin",
        "availability": [ "mtgo", "paper" ],
        "borderColor": "black",
        "colorIdentity": [ "R" ],
        "colors": [ "R" ],
        "convertedManaCost": 4.0,
        "edhrecRank": 5978,
        "flavorText": "\"What are the odds, indeed?\"\n—Yursi, to Desera",
        "foreignData": [],
        "frameVersion": "2015",
        "hasFoil": true,
        "hasNonFoil": true,
        "identifiers": {
          "cardKingdomId": "246209",
          "mcmId": "566174",
          "mcmMetaId": "921",
          "mtgjsonV4Id": "646f40c1-d41f-5756-b1c5-30cdbcb5b698",
          "scryfallId": "49a4b0c9-a35b-4b55-ab27-7246bbca0d16",
          "scryfallIllustrationId": "6f5b7422-3f74-46b3-860f-996cf9bb4f3b",
          "scryfallOracleId": "8bd33b5c-0777-41ef-9e17-fb30ce69ec25",
          "tcgplayerProductId": "239665"
        },
        "isReprint": true,
        "layout": "normal",
        "legalities": {
          "commander": "Legal",
          "duel": "Legal",
          "legacy": "Legal",
          "premodern": "Legal",
          "vintage": "Legal"
        },
        "manaCost": "{2}{R}{R}",
        "name": "Chance Encounter",
        "number": "277",
        "printings": [ "MH2", "ODY" ],
        "purchaseUrls": {
          "cardKingdom": "https://mtgjson.com/links/aa5c7636de654522",
          "cardmarket": "https://mtgjson.com/links/a0a112d477fd07a2",
          "tcgplayer": "https://mtgjson.com/links/7da8317de1295ba0"
        },
        "rarity": "rare",
        "rulings": [
          {
            "date": "2009-02-01",
            "text": "You can only win a coin flip if you are the player flipping the coin. Your opponent losing a flip does not count as you winning one. This is a reversal of previous rulings."
          }
        ],
        "setCode": "MH2",
        "subtypes": [],
        "supertypes": [],
        "text": "Whenever you win a coin flip, put a luck counter on Chance Encounter.\nAt the beginning of your upkeep, if Chance Encounter has ten or more luck counters on it, you win the game.",
        "type": "Enchantment",
        "types": [ "Enchantment" ],
        "uuid": "22aed906-f3cc-548b-b24f-c8881d3d41e3",
        "watermark": "set"
      },

**Comment by staghouse** [comment]
This looks by my eyes to be resolved, can you confirm @SteveLGK

**Comment by SteveLGK** [comment]
Looks good with current version.
