### ISSUE TITLE
Wrong release date for preconstructed decks

### ISSUE THREAD

**Issue by antzidious** [mtgjson/mtgjson#805]
#### Version(s) tested against
v5.1.0+20210601

#### Description of Bug
Preconstructed decks `Awakening Earth` and `Song Dance` from M20 both have a release date of 2021-11-08, which is incorrect. I believe this should be 2019-11-08.

**Comment by ZeldaZach** [comment]
cc @taw

**Comment by taw** [comment]
Fixed

**Comment by staghouse** [comment]
Confirming fixed via documentation

<img width="713" alt="image" src="https://user-images.githubusercontent.com/1939508/128890413-9c51d713-ab08-4bcd-a2fa-dd48980233ea.png">
<img width="725" alt="image" src="https://user-images.githubusercontent.com/1939508/128890486-e9a8c71c-aa89-465d-914a-70e667d047ac.png">
