### ISSUE TITLE
Add AFR to daily spoiler runs

### ISSUE THREAD

**Issue by lfgcampos** [mtgjson/mtgjson#808]
AFR is being spoiled since yesterday (June 24th) and it would be benefical to have it on the daily runs.

**Comment by ZeldaZach** [comment]
These spoilers were successfully added yesterday, but thanks for the re-reminder!

**Comment by lfgcampos** [comment]
Hey @ZeldaZach, sorry to ping you but seems like they are not running daily or I missed something... there were lots of spoilers yesterday but last build it still `20210628`.

**Comment by ZeldaZach** [comment]
Hey @lfgcampos I just took a look at https://mtgjson.com/api/v5/AFR.json and it seems like the file was successfully updated. Let me know if there are other issues.

**Comment by lfgcampos** [comment]
Hey @ZeldaZach, thanks for the heads up!
Now it does but it wasn't at that time :)
