### ISSUE TITLE
incorrect cardKingdomFoilId for Cursed Totem

### ISSUE THREAD

**Issue by joe-nasti** [mtgjson/mtgjson#809]
Tested against AllPrintings.json
{'date': '2021-06-25', 'version': '5.1.0+20210625'}

'uuid' : '2ecba824-4c05-5cdf-8377-e46e4b9d757e'
'name' : 'Cursed Totem'
'cardKingdomId' : '246436'           #  correct mtg/modern-horizons-2/cursed-totem
'cardKingdomFoilId' : '247185'       ​#  incorrect mtg/modern-horizons-2/cursed-totem-foil-etched
'tcgplayerProductId' : '240154'      #  correct https://store.tcgplayer.com/magic/modern-horizons-2/cursed-totem
'mcmId' : '566682'                   #  correct /en/Magic/Products/Singles/Modern-Horizons-2/Cursed-Totem-V1

Everything seems fine, except for 'cardKingdomFoilId' - it should instead point to '246997' / ck url 'mtg/modern-horizons-2/cursed-totem-foil'

Thanks,
Joe

**Comment by kodawah** [comment]
fixed in https://github.com/mtgjson/mtgjson/pull/843
