### ISSUE TITLE
Provide a coarser way to check build version

### ISSUE THREAD

**Issue by AncientSwordRage** [mtgjson/mtgjson#813]
I don't always need to a weekly build from the meta endpoint, especially not the daily spoiler builds.

Can there be a quick way to check the last time the allsets (etc) data was updated, ignoring spoilers?

**Comment by kodawah** [comment]
since we're in perennial spoiler season, the builds have become daily. However it is beneficial to keep older sets up to date as they might contain fixes and adjustments that get reported over time.

**Comment by AncientSwordRage** [comment]
If an old set is updated with fixes/adjustments the version number should change.

What I'm more after is a version number that does get updates weekly if there is no change at all.

**Comment by ZeldaZach** [comment]
It's tricky to handle those kind of changes with versioning, as different components update at different times, so we'd have a really wack system. I feel we can sub-ticket this to the Delta patch ticket #634 where we'll provide a change log between each day/week files, giving the user more visibility on the changes that take place. 

Based on that, I'm inclined to close this ticket in favor of the Delta ticket. If you feel this is the wrong approach, I'd love to continue a discussion on this either on the ticket or on our Discord at https://mtgjson.com/discord :)
