### ISSUE TITLE
OC21 needs some indicator these are not legal Magic cards

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#815]
https://mtgjson.com/api/v5/OC20.json and before had `isOversized: true`

https://mtgjson.com/api/v5/OC21.json doesn't, as they replaced oversized cards by extra-thick non-tournament-legal special foils.

But in mtgjson they look like just regular playable cards. Some new flag is needed to mark them as not tournament legal.

I expect future Commander sets to have the same issue.

**Comment by staghouse** [comment]
My thought is that that property can still be used since the card technically is still oversized, we just need to mark those cards as `isOversized` if they are not already.

Thoughts?

**Comment by ZeldaZach** [comment]
I'll be marking OC21 with isOversized, since that's the intended purpose of the field (to denote a card is not 'legal' in traditional sense).

**Comment by taw** [comment]
Yeah, that works.
