### ISSUE TITLE
Enhance token reverseRelated to be card IDs instead of names.

### ISSUE THREAD

**Issue by jmcsmith** [mtgjson/mtgjson#816]
Currently reverseRelated lists cards that create that token by name. This would be much more helpful programmatically if it was the card UUID.

 `"reverseRelated": [
                    "Scour the Desert",
                    "Soul of Migration"
    ]`
would look like 
`reverseRelated": [
                    "6441701d-0dae-5c5a-9b2d-8f93a951c191",
                    "c0a36974-0541-505c-bcd5-724469f13815"
    ]`

**Comment by ZeldaZach** [comment]
The reason I'm a bit hesitant on this is because UUIDs don't hold in AtomicCards, for example. I wouldn't be able to provide the content there. Then again, I did consider UUIDs in #891 so I'm not sure.

Any other opinions on this topic?

**Comment by ZeldaZach** [comment]
I've decided to go against this suggestion since UUIDs can't be linked back properly in the AtomicCards file, but is still a key component of the card's metadata that needs to be visible
