### ISSUE TITLE
LEA Card "Prodigal Sorcerer" has "flavorName": "Tim"

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#817]
https://mtgjson.com/api/v5/LEA.json

For some weird reason one of the cards has `"flavorName": "Tim"`. This is totally not what `flavorName` is used for (Ikoria style printed-on-the-card second name) and it should be removed.

**Comment by ZeldaZach** [comment]
I need to talk with upstream about this one, that's both funny and a bit weird

**Comment by taw** [comment]
If they want to have some nickNames like Bob or Tim, that's fine, but it should be a separate field.

**Comment by ZeldaZach** [comment]
This has been changed to meet documentation.
