### ISSUE TITLE
Owlbear has keyword of "Keen senses"

### ISSUE THREAD

**Issue by igr-maru** [mtgjson/mtgjson#819]
#### Version(s) tested against

v5.1.0+20210714

#### Description of Bug
Owlbear has keyword of "Keen senses".  Owlbear cards are two, which are boosterfun and normal ones.

**Comment by staghouse** [comment]
This looks to be resolved. Is this still an issue @igr-maru?

**Comment by igr-maru** [comment]
@staghouse 
I've checked this and it was already solved. Thank you.

**Comment by igr-maru** [comment]
So, I'll close this issue.
