### ISSUE TITLE
Older sets had different notions of rarity that don't neatly fit into "common", "uncommon", etc

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#82]
Difficult to summarize, just read the original thread:

https://github.com/mtgjson/mtgjson/issues/364

**Comment by ZeldaZach** [comment]
Useful for when we consider re-impl of the booster field.

**Comment by ZeldaZach** [comment]
It's an interesting idea for sure, but it's hard to impl as we have no definitive sources for such data... Not sure what to do here

**Comment by KingSupernova31** [comment]
Honestly I think it's fine to just go by the rarity that Gatherer displays, even if that doesn't perfectly match how the cards were distributed. I doubt anyone who needs to know the exact collation in old sets would be coming to MTGJSON for that data anyway.

**Comment by ZeldaZach** [comment]
After thinking this through further, there is no reliable way to get the information we need. I don't feel confident changing rarities around like this, so I won't be for the foreseeable future.
