### ISSUE TITLE
JMP MTGO availability issues

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#824]
https://mtgjson.com/api/v5/JMP.json

[This was reported by an user here](https://github.com/taw/magic-search-engine/issues/148), but without much detail.

I can't find exact list, but quick search says some JMP cards were added to MTGO treasure chests when M21 happened.

On mtgjson only 2 JMP cards are marked as available on MTGO.

Perhaps someone more familiar with MTGO can find out correct list.

**Comment by ZeldaZach** [comment]
I looked further into this and it appears the 37 cards from Jumpstart that were brand new are now available on MTGO. I've filed a ticket with upstream.

**Comment by staghouse** [comment]
@taw is this resolved?

**Comment by taw** [comment]
@staghouse  I think so, yeah.
