### ISSUE TITLE
Dungeons are missing from AtomicCards

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#826]
#### Version(s) tested against
5.1.0

#### Description of Bug
AtomicCards has most of AFR, but doesn't contain the three dungeons.

**Comment by kodawah** [comment]
I believe it is because Dungeons are listed as Tokens whereas AtomicCards only covers Card objects.

**Comment by KingSupernova31** [comment]
If that's the case that's incorrect, Dungeons are cards, not tokens.

**Comment by kodawah** [comment]
yes but they appear in the token sheet - they cannot appear in AFR since their collector number would overlap with a existing cards, so they need to go in a separate set (the token one) which is not covered by AtomicCards

**Comment by KingSupernova31** [comment]
What products they're printed in isn't relevant to how they're categorized by WOTC. As far as game mechanics and definitions are concerned, Dungeons are exactly like all other nontraditional cards such as Conspiracies, Planes, Vanguards, etc. and should be treated the same way.

Also note that no tokens are in AtomicCards, despite the fact that many of them have been printed on the same sheets as cards in supplemental products.

**Comment by ZeldaZach** [comment]
I'm in agreement with @KingSupernova31 here. Since AtomicCards supports Conspiracies and Vanguards, I see no reason it shouldn't support Dungeons. This is a valid ticket and i'll see what i can do.
