### ISSUE TITLE
Add support for italicized text

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#828]
There's currently no good way to programmatically separate something like the flavor words on Grim Wanderer from the actual rules text of cards like Aboroth, Abrade, Battershield Warrior, Citadel Siege, etc. (Ability words and reminder text are more easily identifiable because 207.2c contains a list of all ability words and reminder text is always in parentheses.) MTGJSON could start including a list of all flavor words, but that seems like a rather ad hoc solution and might break if WOTC decides to add yet another type of italicized text in the future. A better solution would probably be for each `card` object to have some way to indicate what text is italicized. I see two good possibilities:

* Add a separate `rulesText` field that omits all italicized text.
* Add an `italicizedText` property that contains an array of 2-tuples that indicate the starting and ending indices of any italicized text in the `text` field.

**Comment by ZeldaZach** [comment]
Having a field that omits italics could be interesting, but I'm not sure the value it necessarily provides. I can tell you're trying to target AFR with this ticket, but how would you recommend handling ability words like Chroma?

**Comment by KingSupernova31** [comment]
I'm a little confused by your question, can you elaborate? The value is that programs that care about card functionality will have a way to look at a card's rules text, which as of AFR is very difficult.

**Comment by ZeldaZach** [comment]
I can understand how parsing AFR might be a bit tricky. You can parse on the dash and see if the word(s) before it are found in https://mtgjson.com/api/v5/EnumValues.json's `keywords` section. If it's not there, it can be safely discarded.

Hopefully this workaround is sufficient? I just don't see a huge benefit of offering a separate field in such a way, outside of this niche case offered so far.

**Comment by ZeldaZach** [comment]
I'll be closing this ticket out as we're not sure how much value this provides, as it can be easily done on a downstream's end by just looking for Words with an em-dash at the start of a line, and for most folks this doesn't seem relevant.

**Comment by KingSupernova31** [comment]
Any thoughts on implementing this? It's more relevant than ever now. Any program that wants to display a card's text correctly needs to know what text is in italics, it's not a niche case at all.
