### ISSUE TITLE
Two cards in AFR are missing multiverseId for Japanese ones and jp-name at least. 

### ISSUE THREAD

**Issue by igr-maru** [mtgjson/mtgjson#829]
#### Version(s) tested against
Version(s) tested against
v5.1.0+20210823

#### Description of Bug
The following cards in AFR are missing multiverseId for Japanese ones and jp-name at least.  (I'm not sure other language's)
+2 Mace
Mountain (multiversId is 530170)

**Comment by ZeldaZach** [comment]
I just closed another ticket in regards to `+2 Mace` (#821). There won't be a fix for that one at this time, unfortunately.

I've taken the time to re-audit the Basics and found quite a few missing across multiple languages. I have filed a report upstream and this should hopefully be resolved soon!

**Comment by ZeldaZach** [comment]
This has been addressed!
