### ISSUE TITLE
Include formatting info for text

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#83]
Reminder text is always inclosed in parentheses, so it's easy to locate with a regex. Ability words are more difficult however, so information as to what text in the "text" field is italicized would come in handy.

https://github.com/mtgjson/mtgjson/issues/75

**Comment by KingSupernova31** [comment]
Implementing #84 would solve the issue for locating ability words.

**Comment by ZeldaZach** [comment]
I don't think I want to do this... I don't see a good purpose for it. Would rather look at #84.
