### ISSUE TITLE
"Trelasarra, Moon Dancer"'s name in Japanese is English.

### ISSUE THREAD

**Issue by igr-maru** [mtgjson/mtgjson#830]
#### Version(s) tested against
Version(s) tested against
v5.1.0+20210823

#### Description of Bug
"Trelasarra, Moon Dancer"'s name in Japanese is English. (which has same value in name properties in EN and JP)

**Comment by ZeldaZach** [comment]
Looks to be an upstream issue. I've reported it and it should be resolved soon!

**Comment by ZeldaZach** [comment]
Will have to close this issue, as Gatherer doesn't have the correct information and there's no easy way to gather (ha!) the information from them from just the images.
