### ISSUE TITLE
Move daily builds earlier during the day

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#831]
Right now the build-everything files are live at around 11pm EDT, but this has a couple of drawbacks

 * any change in upstream data won't be reflected until the day after. This of course depends on the time of the change, but on average there is a two day delay from Scryfall updates, and new card additions.
 * 11pm EDT means 5am CET of the day after, basically leaving the European users being able to use the update the day after only
 * being so late in the day, it's impossible to catch any build failure until the day after (as it's happening now) which increase the delays above

I believe we could improve things just by moving the build at 1am EDT, so that all upstream updates would be present and the file would be usable from early EU morning, giving time to run a second build should the automatic one fail.

**Comment by ZeldaZach** [comment]
The current system builds at around 3pm ET, finishing around 7pm ET, and deploying live at 8pm ET. If we move the build times to 1am ET, we're just flip flopping the problem of who has "laggy" data. I could see moving the build earlier, but 1am ET doesn't feel like the right call.

**Comment by lfgcampos** [comment]
Any chance to run it 2 times a day?
I have no idea about costs but asking doesn't hurt =)

**Comment by kodawah** [comment]
@lfgcampos probably twice a day is not really worth it, there are rarely big enough changes to warrant that

I'm not sure I agree on the times @ZeldaZach: the number of changes happening overnight (after 1am ET) are minimal, you'd just let people use data earlier. Maybe a good compromise would be later during the night?

What I think would be ideal is leaving builds as they are and have a way for users to manually trigger build in case of a big change happening, but that brings in other types of problems

**Comment by kodawah** [comment]
the new build times work well 👍
