### ISSUE TITLE
SubType Enchantment/Class is missing 

### ISSUE THREAD

**Issue by ncoxage** [mtgjson/mtgjson#832]
api/v5/CardTypes.json

The subType 'Class' is missing from the Enchantment object

"enchantment": {
            "subTypes": [
                "Aura",
                "Cartouche",
                "Curse",
                "Rune",
                "Saga",
                "Shard",
                "Shrine"
            ]

**Comment by staghouse** [comment]
This seems to be resolved now. Can you confirm @ncoxage?

**Comment by ncoxage** [comment]
yep, "Class" is now present
