### ISSUE TITLE
Grist's leadership skills are wrong

### ISSUE THREAD

**Issue by krijoh92** [mtgjson/mtgjson#834]
#### Version(s) tested against
MTGJSON 5.1.0+20210901

#### Description of Bug
[Grist](https://scryfall.com/card/mh2/202/grist-the-hunger-tide) should be able to be your commander. Based of a [discussion](https://discord.com/channels/224178957103136779/448295284137656342/870047375710900275) in the discord, the "Creature" check fails for Grist

**Comment by ZeldaZach** [comment]
Thanks for pointing this out! I'll have a fix up shortly :)
