### ISSUE TITLE
add an upstream announcement channel in discord

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#835]
It would be nice if we could have an upstream channel in discord for all the upstream notifications, such as from scryfall or taw

for scryfall in particular we would just need to hit "follow" and select the desired channel where to publish the notification

**Comment by taw** [comment]
Do you need any special support from me?

IIRC mtgjson only takes my data through these two repos, so if you want to subscribe to commit messages on both, you'd get pretty much all of it, right?

* https://github.com/taw/magic-sealed-data/commits/master
* https://github.com/taw/magic-preconstructed-decks-data/commits/master

If I plan to do any schema changes, or anything else major, I DMed Zach on twitter, but if you prefer I can msg you on discord. It doesn't happen often.

**Comment by ZeldaZach** [comment]
@taw Our twitter line of contact seems fine for the time being. If anything changes i'll let you know!

**Comment by ZeldaZach** [comment]
Done
