### ISSUE TITLE
Missing translations/foreignData

### ISSUE THREAD

**Issue by ThauEx** [mtgjson/mtgjson#837]
#### Version(s) tested against
v5.1.0+20210906

#### Description of Bug
I noticed that some cards are missing the foreignData, e.g. card id 02a13fa6-ff4e-4794-be31-167af8806771 (swamp)
The foreignData is empty, but when checking scryfall, it has data: https://scryfall.com/card/m21/311/swamp
The german version of this card has the scryfall-id "02a13fa6-ff4e-4794-be31-167af8806771", but this doesn't seem to be inside the dump.
I used this dump: https://mtgjson.com/api/v5/AllPrintings.json

**Comment by ZeldaZach** [comment]
Hey @ThauEx thanks for the ticket! I've looked into how I handle foreign data and it seems I forgot to handle the case where several hundred iterations of a card exist (re: Basic lands). I'll have a fix up shortly :) Thank you!!
