### ISSUE TITLE
Prices last week

### ISSUE THREAD

**Issue by rsamso** [mtgjson/mtgjson#838]
Hello, first at all, i want to congratulate MTGJson for the work are you doing !! is a amazing contribution to MTG community.

I am try to load daily the prices from allprices.json to get the last day price, Is posible to add an new .json file with only the prices of the last week, or last day?

**Comment by ZeldaZach** [comment]
Hey @rsamso thanks for reaching out! I appreciate your kind words :)

There's a working ticket #750 that aims to solve this issue in the near future! If you'd ever like to help out with the project, development wise or financially, feel free to reach out on Discord or on our Website!
