### ISSUE TITLE
Add a list of keyword abilities, keyword actions, and ability words in card info

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#84]
A list of keyword abilities, keyword actions, and ability words that each card has would be helpful.

https://github.com/mtgjson/mtgjson/issues/285

**Comment by ZeldaZach** [comment]
I like this idea a lot, but we'd need to keep a list of _all_ keywords, then a simple regex to see if they're in the text. Not certain about impl but I'd consider help on this

**Comment by lfgcampos** [comment]
You could have a `keywords.json` as well where anyone can contribute when new keywords are added.

**Comment by KingSupernova31** [comment]
It would be easy enough to just pull them from the Comprehensive Rules, they're all listed there.

**Comment by ZeldaZach** [comment]
Good idea, King! 

This seems feasible

**Comment by KingSupernova31** [comment]
So no plans to make card-specific fields, just the game-wide list of all keywords and ability words?

**Comment by ZeldaZach** [comment]
Hmm... I think I misread your ticket then. Thought you wanted the global list. I can work on a new one that's card specific if you open a new ticket

**Comment by KingSupernova31** [comment]
I think either one works. Having only a global list adds an extra step for all the uses that need to know the keywords that are on a specific card, but it's not too hard to match them with a regex.
