### ISSUE TITLE
Check whether `isFoil` for Card (Deck) is still useful

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgjson#842]
With the addition of `finishes`, we should look at `isFoil` and check to see if its still needed or can be replaced with `finishes`

**Comment by ZeldaZach** [comment]
After reviewing the layout, I'm inclined to leave this field as-is. `finishes` gives permutations of how the card can be found, whereas cards in a deck are (usually) definitive in if it's foil or not. Theoretically, we could rename this field to `finish`, as Wizards could theoretically put etched foils in precons.

**Comment by staghouse** [comment]
I agree with you. Closing for now and we can revisit renaming the field later if it seems like a good idea.
