### ISSUE TITLE
STA baseSetSize is incorrectly listed as 0

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#855]
It was previously incorrectly listed as 126. Now it's incorrectly listed as 0.

Cards have it printed as 63, so that's what it should be.

Actually there's been a lot of baseSetSize changes.

* a lot of them look like fixes (MH1, STX, AFC etc.)
* some of them previously worked (UND now incorrectly 100, printed 96 was correct)
* many don't have any base set printed on cards, so I'm not sure what the change means (like ZNC went from 142 to 6; KLR / ALR / various p* sets don't have any as far as I know etc.)

**Comment by ZeldaZach** [comment]
I think I'm just gonna load in an external dependency source, since this is really hard to gauge effectively. I knew a bunch would change, and the ones we tested looked right... @kodabb blahhh

**Comment by kodabb** [comment]
STA cards are numbered up to 126 https://scryfall.com/card/sta/126/ja/putrefy
