### ISSUE TITLE
MultiverseId Missing

### ISSUE THREAD

**Issue by Marcel-Brouette** [mtgjson/mtgjson#857]
On the V5 API, no multiverseid appears on J21 edition (https://mtgjson.com/api/v5/J21.json). For instance the card "Teyo, Aegis Adept" as the multiverseid 534585 => https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=534585.

In fact, there is a good number of online edition which are on the gatherer but no multiverseid are enable on mtgjson. (I don't have an exhaustive listing).

This id is mandatory on my website to check the legality of a card in peasant format.

If you can do something about that, it would be great :) 

Thank you  !

**Comment by ZeldaZach** [comment]
Looks to be an upstream issue, I'll leave a note and see if we can get this fixed up!

**Comment by ZeldaZach** [comment]
I wrote a script to address this and it should be fixed in tomorrow's build!
