### ISSUE TITLE
MH2's Yavimaya Elder Modern Legality Missing

### ISSUE THREAD

**Issue by AEFeinstein** [mtgjson/mtgjson#858]
#### Version(s) tested against

MTGJSON v5.1.0+20211002

#### Description of Bug

In MH2.json, Yavimaya Elder is missing "modern" in it's legalities:

```JSON
"legalities":{
   "commander":"Legal",
   "duel":"Legal",
   "gladiator":"Legal",
   "legacy":"Legal",
   "pauper":"Legal",
   "paupercommander":"Legal",
   "penny":"Legal",
   "premodern":"Legal",
   "vintage":"Legal"
}
```

This made my parser think that MH2 wasn't modern legal (it checks all cards in a set for non-null legalities). If there's a better way to determine if a set is legal in a given format, I'm all ears.

Original report: https://discord.com/channels/224178957103136779/448295284137656342/894975819821232139

**Comment by ZeldaZach** [comment]
This has been addressed

**Comment by AEFeinstein** [comment]
Much appreciated!
