### ISSUE TITLE
B.F.M. right side is missing

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#86]
In allCards.json, the right half is completely missing. In allSets.json, the right half is missing and there are two entries for the left half.

**Comment by ZeldaZach** [comment]
We seem to be having a lot of trouble with split cards... I'm gonna have to sit down and figure it out

**Comment by ZeldaZach** [comment]
So this is correct in both UGL.json and AllSets.json. The cards have two halves. The names are the same, but the flavortext are different.

**Comment by KingSupernova31** [comment]
My error for allSets.json, I was expecting them to have different names. However the issue still exists in allCards.json, there's only one entry.
