### ISSUE TITLE
Split/transform/flip cards missing TCGPlayer paper prices

### ISSUE THREAD

**Issue by Palladinium** [mtgjson/mtgjson#866]
#### Version(s) tested against

AllPrices.json
MTGJSON 5.1.0+20211130

#### Description of Bug

Split, transform and flip cards seem to be missing TCGPlayer prices, and instead of the typical payload they only have `{"currency" => "USD"}` under `json["data"][id]["paper"]["tcgplayer"]`

Examples:
`0ad9df53-068e-5bbd-9a83-d0dc4168ce6e` Fire // Ice (split card)
`7f5f719b-947a-50b0-834b-693f59fc0bea` Alive // Well (split card)
`7472759d-0b05-53ef-8053-951448d5d2c5` Faithful Squire // Kaiso, Memory of Loyalty (flip card)
`925aef52-b1b5-5493-a88a-74f42fbd0ecb` Afflicted Deserter // Werewolf Ransacker (transform card)
`5bd2cbe8-89c4-5742-9abf-23a40cb84d3d` Extricator of Sin // Extricator of Flesh (transform card)

Meld cards seem to be fine, for example:
`5bb79a0f-ad7d-5383-8c9d-04bc757bcb4f` Gisela, the Broken Blade // Brisela, Voice of Nightmares
`6081d8fd-26e1-5e6a-9c98-417d03214856` Bruna, the Fading Light // Brisela, Voice of Nightmares

**Comment by Palladinium** [comment]
This appears to have been mostly fixed as of version 5.1.0+20211129.

Some cards are still affected, see attached file for a full list.
[dfcs_missing_prices.zip](https://github.com/mtgjson/mtgjson/files/7622629/dfcs_missing_prices.zip)

**Comment by Palladinium** [comment]
Here's a list of affected cards: 
[missing_prices.zip](https://github.com/mtgjson/mtgjson/files/7630835/missing_prices.zip)

**Comment by ZeldaZach** [comment]
Hey @Palladinium i'll look into this soon, thanks for the bump :)

Ref: Priority

**Comment by kodawah** [comment]
these cards seem to be missing from the TCGSKU file too, but they do have `tcgplayerProductId` correctly initialized (for both sides too)

I wonder if the tcg provider gets confused by the fact there are two sides but that wouldn't explain how meld cards work. The CK provider loads these entries just fine
