### ISSUE TITLE
Missing Explorers of Ixalan Events, Quests, and Sites

### ISSUE THREAD

**Issue by fenhl** [mtgjson/mtgjson#87]
As @KingSupernova31 pointed out in <https://github.com/mtgjson/mtgjson4/issues/67#issuecomment-430437889>, we are currently missing vanguards, schemes, planes, etc. While not traditional cards, these are *Magic* cards and should be included.

**Comment by ZeldaZach** [comment]
Contemplating how to go about it. Prob just a custom gatherer scrape. Seems feasible for 4.1

**Comment by fenhl** [comment]
I just checked and vanguards, schemes, planes, phenomena, and conspiracies all seem to be on Scryfall. Only *Explorers of Ixalan* events, quests, and sites are missing.

**Comment by ZeldaZach** [comment]
cc: @jhallbachner

**Comment by ZeldaZach** [comment]
Ok, so Events, Quests, and Sites are tiles, not cards. As such, I don't plan on indexing them into MTGJSON at this time.
