### ISSUE TITLE
Innistrad: Double Feature (DBL) is already full spoiled

### ISSUE THREAD

**Issue by lfgcampos** [mtgjson/mtgjson#871]
Innistrad: Double Feature (DBL) is already full spoiled but not availble on mtgjson.

https://mtgjson.com/api/v5/DBL.json
https://scryfall.com/sets/dbl?as=grid&order=set

**Comment by kodawah** [comment]
it is up now

**Comment by ZeldaZach** [comment]
Yep, sorry for not responding to the comments!
