### ISSUE TITLE
Incorrect Card Count (Mind Control) in Illusionary Might Pre-con

### ISSUE THREAD

**Issue by BrucePetrie** [mtgjson/mtgjson#873]
### Steps to reproduce
Download JSON decklist from https://mtgjson.com/api/v5/decks/IllusionaryMight_M12.json

### What is expected?
IllusionaryMight_M12['data']['mainBoard'][12]['count'] = 3

### What is actually happening?
IllusionaryMight_M12['data']['mainBoard'][12]['count'] = 1

### Other relevant information
card [12] is "Mind Control"
https://magic.wizards.com/en/game-info/products/card-set-archive/2012-core-set/event-deck-decklists

**Comment by ZeldaZach** [comment]
cc @taw

**Comment by taw** [comment]
Data in my repo is correct. I think your import script is confused by card appearing in both mainboard and sideboard.

```
➜  magic-preconstructed-decks-data git:(master) jq . <decks_v2.json | jq '.[] | select(.name == "Illusionary Might") | .cards | .[] | select(.name == "Mind Control")'
{
  "name": "Mind Control",
  "set_code": "m12",
  "number": "67",
  "foil": false,
  "count": 3,
  "multiverseid": 238572,
  "mtgjson_uuid": "0a023e18-c3e9-540f-8461-73fd3aef885e"
}
➜  magic-preconstructed-decks-data git:(master) jq . <decks_v2.json | jq '.[] | select(.name == "Illusionary Might") | .sideboard | .[] | select(.name == "Mind Control")'
{
  "name": "Mind Control",
  "set_code": "m12",
  "number": "67",
  "foil": false,
  "count": 1,
  "multiverseid": 238572,
  "mtgjson_uuid": "0a023e18-c3e9-540f-8461-73fd3aef885e"
}
```
