### ISSUE TITLE
Missing CMC value for Zndrsplt, Eye of Wisdom // Zndrsplt, Eye of Wisdom (379) in Secret Lair Drop (SLD)

### ISSUE THREAD

**Issue by GooseDeer** [mtgjson/mtgjson#878]
#### Version(s) tested against
"meta": { "date": "2021-11-30", "version": "5.1.0+20211130" }

#### Description of Bug
The card `Zndrsplt, Eye of Wisdom // Zndrsplt, Eye of Wisdom (379)` for set `Secret Lair Drop (SLD)` has a CMC value of "" rather than 5.0.

Card on Scryfall Api: https://api.scryfall.com/cards/d5dfd236-b1da-4552-b94f-ebf6bb9dafdf

Not sure if this is the only card in the set with this problem. Worth checking the rest of them.

**Comment by GooseDeer** [comment]
itemfive on discord mentioned:

"All cards with layout "reversible_card" have blank manaValues, not just 'Zndrsplt, Eye of Wisdom // Zndrsplt, Eye of Wisdom'. So The Secret Lair Drop cards "Krark's Thumb // Krark's Thumb", "Okaun, Eye of Chaos // Okaun, Eye of Chaos" , "Propaganda // Propaganda" , "Stitch in Time // Stitch in Time" , and "Zndrsplt, Eye of Wisdom // Zndrsplt, Eye of Wisdom" are all messed up."

**Comment by jmcsmith** [comment]
I am seeing this issue also, causes SLD to fail decoding.

**Comment by jmcsmith** [comment]
@ZeldaZach this seems to still be the case for the SLD.json file generated on 12/8/2021
