### ISSUE TITLE
Fixes for issues in older sets

### ISSUE THREAD

**Issue by lsmoura** [mtgjson/mtgjson#88]
A user (that wishes to remain anonymous) of mtgjson has brought to my attention several errors on old sets.

The reference used was mostly the (defunct?) [CrystalKeep](https://web.archive.org/web/20150322083613/http://www.crystalkeep.com/magic/lists/text.php) files. 

The corrections may be found on the [attached diff](https://github.com/lsmoura/mtgjson/files/22397/mtgjson-fixes.diff.txt) that I'm currently analyzing.

I'll create a new branch for this and merge on master when it's all verified.

**Comment by gwax** [comment]
The diff is light on details and doesn't have much in the way of justification.

I'm going to close this for now. If people want this addressed, we can reopen with additional details.
