### ISSUE TITLE
AtomicCard ordering for flip cards is wrong

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson#881]
> Running into a weird bug - using the AtomicCards file, looking at:
> cards['data']['Glasspool Mimic // Glasspool Shore']
> For some reason, Glasspool Shore is the first face. Any idea why that would be? Thanks!

https://twitter.com/CubeApril/status/1467256619553771525

**Comment by april** [comment]
Thanks for looking into this!
