### ISSUE TITLE
Add 'isFunny' to Card Data Model

### ISSUE THREAD

**Issue by AEFeinstein** [mtgjson/mtgjson#888]
Currently a card's funniness can more or less be determined by the [`bordercolor`](https://mtgjson.com/data-models/card-set/#bordercolor) and [`legalities`](https://mtgjson.com/data-models/card-set/#legalities) attributes in the data model. 'Funny' cards have silver borders (except for CMB1 and CMB2) and aren't legal anywhere.

[Unfinity will be adding black bordered funny cards](https://magic.wizards.com/en/articles/archive/making-magic/unfinity-and-beyond-2021-11-29), and the only visual difference will be an acorn stamp.

Scryfall has an [`is:funny`](https://scryfall.com/search?q=is%3Afunny) filter, and adding adding an `isFunny` attribute to the Card Data Model would make filtering out those cards easier than checking border colors and legalities.

**Comment by AEFeinstein** [comment]
Looks like Scryfall's sense of humor is
* Playtest cards
* HasCon
* Happy Holidays
* Heroes of the Realm
* Un- sets

**Comment by ZeldaZach** [comment]
Seems reasonable, will look into this

**Comment by AEFeinstein** [comment]
For completeness, you may also want to look into a `holofoil_stamp` field, with options like oval, [triangle](https://c1.scryfall.com/file/scryfall-cards/large/front/0/a/0a8e78b3-3232-4d48-9d6c-540951a0330e.jpg?1638596643), acorn, and whatever else WotC can dream up. Tracking that manually may be a huge pain though.

**Comment by ZeldaZach** [comment]
Fixed in #889

**Comment by AEFeinstein** [comment]
Holy cannoli that was fast. Guess it's easy when scryfall already collects the data. Thanks!
