### ISSUE TITLE
Add Legalities to Set Data Model

### ISSUE THREAD

**Issue by AEFeinstein** [mtgjson/mtgjson#892]
Currently the [`Legalities`](https://mtgjson.com/data-models/legalities/) data model is only a child of Card (Atomic), Card (Deck), and Card (Set). I would like this data model added as a child of [`Set`](https://mtgjson.com/file-models/set/) as well. This would make tasks like finding a list of [Standard legal](https://magic.wizards.com/en/content/standard-formats-magic-gathering) Sets easy.

**Comment by ZeldaZach** [comment]
Hi there @AEFeinstein Can you go more into detail on why you think something like this is necessary? Not every card in a specific set is legal in all formats (See the new Unfinity, for example). This would make having a blanket Legalities statement on the Set level awkward and misleading.

**Comment by AEFeinstein** [comment]
On a personal level, my current SQLite database setup has a table for Sets, a table for Cards, and a table for banned/restricted information. They all get joined together for queries and it works reasonably well.

Currently I'm inferring a Set's legality by inspecting the cards within it. If all cards have the optional property (legal, banned, or restricted) for a given format, then the Set is considered legal in that format. This approach had been working until the [Arena balanced cards](https://scryfall.com/search?q=name%3A%2F%5EA-.*%2F) came along and were put in their respective paper sets without the optional property for Standard which broke my logic. It would be nice to not have to infer this.

On a less personal level WotC keep lists for [Modern](https://magic.wizards.com/en/game-info/gameplay/formats/modern), [Standard](https://magic.wizards.com/en/content/standard-formats-magic-gathering), and [Pioneer](https://magic.wizards.com/en/game-info/gameplay/formats/pioneer), and I don't think people find those awkward or misleading. It's useful information for a website like https://whatsinstandard.com/

I do agree that Unfinity throws a bit of a wrench in things. In my database, I was planning on marking it as eternal-legal, and adding the 'funny' cards to the banned list.

**Comment by ZeldaZach** [comment]
I have a community feedback PR open #891 if you'd like to leave comments / ideas on it. I've seen a few ideas float around and I"m trying to figure out the best approach.

**Comment by ZeldaZach** [comment]
I've been thinking on this, and with the precedent Wizards set with Unfinity that _some_ cards are legal and some aren't, I unfortunately feel this field wouldn't provide enough value as it would have edge cases / awkward use cases. 

It's possible we could support a Formats.json file that lists all Set Codes and what format(s) they're _generally_ legal in, but again WhatsInStandard.com provides a good chunk of that derivative already.

**Comment by AEFeinstein** [comment]
You're not wrong, especially with unfinity. I wish whatsinstandard.com had an API. I'll survive.

**Comment by ZeldaZach** [comment]
@AEFeinstein Oh, but they do! https://github.com/glacials/whatsinstandard/blob/main/web/api/README.md :)

**Comment by AEFeinstein** [comment]
Well I'll be. That sure isn't listed directly on their website!
