### ISSUE TITLE
`sealedProduct` is missing from sets

### ISSUE THREAD

**Issue by kalinon** [mtgjson/mtgjson#900]
#### Version(s) tested against
MTGJSON 5.1.0+20211219

#### Description of Bug
`sealedProduct` is missing from sets at https://mtgjson.com/api/v5/SetList.json

it is present in the `5.1.0+20211218` backup

**Comment by ZeldaZach** [comment]
TCGPlayer had an outage during my build on the 19th, leading to a lack of IDs and products. This should hopefully be resolved in today's build. Will close once I can confirm it.

**Comment by kalinon** [comment]
ah, makes sense. Glad we know the root cause 👍

**Comment by ZeldaZach** [comment]
Can confirm new build will have it, new build deploys in an hour or so. Thanks for your report!

**Comment by kalinon** [comment]
Confirmed its in `5.2.0+20211220` Thanks!
