### ISSUE TITLE
'Arm for Battle' commander deck misnamed 'Armed for Combat'

### ISSUE THREAD

**Issue by mmurdoch** [mtgjson/mtgjson#903]
#### Version(s) tested against
5.2.0+20220102

#### Description of Bug
The Commander Legends commander deck 'Arm for Battle' is incorrectly named 'Armed for Combat'. Rather than being available at https://mtgjson.com/api/v5/decks/ArmForBattle_CMR.json its URL is: https://mtgjson.com/api/v5/decks/ArmedForCombat_CMR.json

**Comment by ZeldaZach** [comment]
Seems like an upstream issue cc @taw

**Comment by taw** [comment]
Well, that's where I got it from https://mtg.fandom.com/wiki/Commander_Legends/Commander_decks?diff=388726&oldid=388725

Anyway, fixing it now.

**Comment by taw** [comment]
Fixed.
