### ISSUE TITLE
Improve representation of artists

### ISSUE THREAD

**Issue by pbaranay** [mtgjson/mtgjson#905]
Currently, the `Card (Set)` data model represents a card's `artist` as a string. However, this representation is overly simple and has a couple downsides:

1) strings aren't stable identifiers for people, as some artists have changed their names over time (e.g. Jenn Ravenna -> Jenn Ravenna Tran -> Ravenna Tran)
2) "funny" artists from Unsets can't be easily resolved into their real artist; for example, Ron “Don't You Dare Change Me” Spears (Brushstroke Paintermage) is Ron Spears, and Claymore J. Flapdoodle (Elvish Impersonators and others) is actually an alias for Phil Foglio
3) cards illustrated by multiple people can't be easily resolved into their contributing artists (e.g. Zoltan Boros & Gabor Szikszai have illustrated many cards together, but each individual also has their own cards)

It would be great if MTG JSON represented artists unambiguously, probably via a new field. For backwards compatibility, I think the current `artist` field should be left as-is (it also provides a useful function in that it more-or-less replicates the printed artist credit).

As a side note, Scryfall currently defines UUIDs for artists (via the `artist_ids` array returned through various card object APIs); perhaps MTGJSON could reference these same UUIDs?

**Comment by ZeldaZach** [comment]
Artist IDs are an interesting concept, I'll have to check those out. I like keeping `artists` as-is, but having some way of better identifying components.

**Comment by van-riper** [comment]
@pbaranay I'll be willing to do some R&D on an artist data model, what other artist info would you want to be included/considered?

**Comment by pbaranay** [comment]
Thanks @maallaard!

For an actual Artist model, the only information I can think of is the person/entity's _canonical_ name (which could change over time), and a unique identifier. Integrating with the Scryfall artist UUIDs would also be handy. From there, the big value add would be updating the `Card (Set)` model to represent the card's artist(s) via a unique identifier, as well as their name(s).

Beyond that, I have a philosophical question: are you comfortable including any information that isn't found on the "cards" themselves? We have started to see some non-individuals be credited as artists (e.g. MSCHF), so it could be interesting to classify artists as individuals vs. studios vs. collectives vs. whatever. However, that distinction isn't really knowable without outside knowledge, and I don't know if MTG JSON wants to become an authority on that information.

It might be helpful to include a denormalized list of an artist's other names or "aliases" on the model? But as that be computed from looking at other models, I don't think it's that important.

**Comment by ZeldaZach** [comment]
Digging a bit further, we've been retroactively updating artist names as they change to meet with current standards over time. As such, no matter which card you look up that the artist created at any point in time, the name will be the current and correct representation. I'm not sure how much value this field adds, based on that knowledge now.

**Comment by ZeldaZach** [comment]
I changed my mind, I'll put in support for artist Ids :)

**Comment by pbaranay** [comment]
Thanks!
