### ISSUE TITLE
Prices of two sides cards are splittet on both sides

### ISSUE THREAD

**Issue by ThauEx** [mtgjson/mtgjson#906]
Hi,

I noticed that the price for e.g. "Blex, Vexing Pest" is separated on the sides.
Front (5a52cce7-3897-5901-a0ab-d1ed087c41ee):
- cardkingdom

Back (55cd326c-01c3-5523-b2fe-22a614594d5c):
- cardmarket
- tcgplayer

They should be on both sides or only the front one and not separated/splitted on both.

**Comment by ZeldaZach** [comment]
This was fixed up in #926 :)
