### ISSUE TITLE
Duel Commander legality issues for 7 "offensive" cards

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#909]
As per https://www.mtgdc.info/banned-restricted:

"Also, this implies cards marked offensive by Wizards of the Coast. Click here for the list. This list is a work in progress."

It's kinda on them for not listing these cards explicitly on the banlist, but from what I understand, the whole 7 is meant to be banned, and that's not currently matching mtgjson.

**Comment by ZeldaZach** [comment]
Thanks for the report. I've confirmed it's an upstream issue and will work towards addressing it.

**Comment by ZeldaZach** [comment]
Should be fixed today
