### ISSUE TITLE
DFCs in MID and VOW are missing frameEffects

### ISSUE THREAD

**Issue by sunsetsnow** [mtgjson/mtgjson#910]
#### Version(s) tested against

MTGJSON 5.2.0+20220127

#### Description of Bug

None of the DFCs in Innistrad: Midnight Hunt and Innistrad: Crimson Vow and their associated promo sets (PMID, PVOW) have `sunmoondfc` in the frameEffects field, at least in AllPrintings.json (I haven't checked the other files). The frameEffects isn't entirely empty, however, as legendary DFCs in those sets *do* have `legendary` in their frameEffects.

**Comment by ZeldaZach** [comment]
Looks to be missing in upstream. I'll see what I can do about this. Thanks for the report!

**Comment by ZeldaZach** [comment]
Should be fixed with today’s build
