### ISSUE TITLE
tokens in ASTX & AMH2 do not have a side `b` for tokens with `s` in the number.

### ISSUE THREAD

**Issue by GooseDeer** [mtgjson/mtgjson#911]
#### Version(s) tested against
https://mtgjson.com/api/v5/ASTX.json
date: 2022-02-02
version: 5.2.0+20220202

#### Description of Bug
In ASTX & AMH2 each token has two version `1` & `1s` for example. This represents the signed token and non-signed token. 

Tokens that have `s` in the `number` seem to have `null` for the `side` instead of `b`:

![image](https://user-images.githubusercontent.com/26407400/152359931-34f8e329-efc0-49fa-969d-32b4b22c3e34.png)

**Comment by ZeldaZach** [comment]
Confirmed to be an issue. Working on a fix. Thanks for the report!!
