### ISSUE TITLE
Mignight Hunt Commander (likely all commander sets) are reporting `parentCode` as Midnight Hunt

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgjson#912]
#### Version(s) tested against
MTGJSON v5.2.0+20220205

#### Description of Bug

The parent code for `Midnight Hunt Commander` is reporting as `Midnight Hunt`. I believe this is counter to the purpose of sets like this where Commander is its own Set with its own Symbol.

Example of offense:
<img width="384" alt="image" src="https://user-images.githubusercontent.com/1939508/152667061-b203dfa3-fc80-495d-8409-792f2e6cc108.png">

In comparison, Promos report the proper parentCode because they _are_ the cards of the parentCode set code.
<img width="378" alt="image" src="https://user-images.githubusercontent.com/1939508/152667090-3643ec38-ec5f-4be5-8854-b1a7e6940079.png">

**Comment by ZeldaZach** [comment]
Since these commander decks are affiliated with the set in question, I'm okay with this distinction. ParentCode more so indicates what it's related to vs a direct 1:1. If you don't feel this holds, we can discuss it further.
