### ISSUE TITLE
J21 missing a lot of artists

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#913]
The "artist" field is missing in mtgjson for these.

Here's the list of affected J21 cards (multipart cards listed as a/b):

* No artist for Abiding Grace j21 32
* No artist for Abzan Battle Priest j21 33
* No artist for Abzan Falconer j21 34
* No artist for Ainok Bond-Kin j21 36
* No artist for Angelic Purge j21 42
* No artist for Angel of the God-Pharaoh j21 44
* No artist for Anointer of Valor j21 46
* No artist for Arcbound Mouser j21 47
* No artist for Arcbound Prototype j21 48
* No artist for Barbed Spike j21 50
* No artist for Battle Screech j21 53
* No artist for Bonescythe Sliver j21 56
* No artist for Boros Elite j21 57
* No artist for Devouring Light j21 67
* No artist for Disciple of the Sun j21 68
* No artist for Djeru's Renunciation j21 69
* No artist for Doomed Traveler j21 70
* No artist for Enduring Sliver j21 74
* No artist for Esper Sentinel j21 75
* No artist for Fairgrounds Patrol j21 77
* No artist for First Sliver's Chosen j21 81
* No artist for Gilded Light j21 86
* No artist for Glorious Enforcer j21 89
* No artist for Westvale Cult Leader j21 90b
* No artist for Hanweir Militia Captain j21 90a
* No artist for Healer's Flock j21 91
* No artist for Hive Stirrings j21 94
* No artist for Impostor of the Sixth Pride j21 96
* No artist for Irregular Cohort j21 97
* No artist for King of the Pride j21 99
* No artist for Kor Skyfisher j21 100
* No artist for Lancer Sliver j21 102
* No artist for Late to Dinner j21 103
* No artist for Radiant's Judgment j21 114
* No artist for Reprobation j21 116
* No artist for Restoration Angel j21 117
* No artist for Roc Egg j21 120
* No artist for Sandsteppe Outcast j21 121
* No artist for Scour the Desert j21 122
* No artist for Segovian Angel j21 125
* No artist for Selfless Cathar j21 126
* No artist for Sentinel Sliver j21 128
* No artist for Seraph of Dawn j21 129
* No artist for Serra's Emissary j21 131
* No artist for Serra the Benevolent j21 132
* No artist for Shelter j21 133
* No artist for Skyblade's Boon j21 136
* No artist for Soul of Migration j21 138
* No artist for Steelform Sliver j21 144
* No artist for Stirring Address j21 145
* No artist for Sustainer of the Realm j21 146
* No artist for Thraben Standard Bearer j21 150
* No artist for Thraben Watcher j21 151
* No artist for Vesperlark j21 156
* No artist for Wall of One Thousand Cuts j21 157
* No artist for Winged Shepherd j21 158
* No artist for Yoked Plowbeast j21 160
* No artist for Zhalfirin Decoy j21 162
* No artist for Aeromoeba j21 163
* No artist for Archmage's Charm j21 166
* No artist for Bazaar Trademage j21 169
* No artist for Breaching Hippocamp j21 170
* No artist for Burdened Aerialist j21 173
* No artist for Choking Tethers j21 178
* No artist for Coralhelm Guide j21 179
* No artist for Diffusion Sliver j21 181
* No artist for Dismiss j21 182
* No artist for Etherium Spinner j21 184
* No artist for Eyekite j21 188
* No artist for Faerie Seer j21 190
* No artist for Filigree Attendant j21 192
* No artist for Floodhound j21 193
* No artist for Foul Watcher j21 194
* No artist for Ghost-Lit Drifter j21 196
* No artist for Hard Evidence j21 200
* No artist for Junk Winder j21 204
* No artist for Just the Wind j21 205
* No artist for Manic Scribe j21 211
* No artist for Man-o'-War j21 212
* No artist for Master of the Pearl Trident j21 214
* No artist for Mist-Syndicate Naga j21 218
* No artist for Moonblade Shinobi j21 220
* No artist for Mulldrifter j21 221
* No artist for Ninja of the Deep Hours j21 223
* No artist for Ojutai's Summons j21 224
* No artist for Parcel Myr j21 227
* No artist for Phantasmal Form j21 229
* No artist for Phantom Ninja j21 230
* No artist for Pondering Mage j21 231
* No artist for Raving Visionary j21 234
* No artist for Recalibrate j21 235
* No artist for Rise and Shine j21 238
* No artist for Scour All Possibilities j21 242
* No artist for Scour the Laboratory j21 243
* No artist for Scuttletide j21 244
* No artist for Scuttling Sliver j21 245
* No artist for So Shiny j21 252
* No artist for Specimen Collector j21 253
* No artist for Steelfin Whale j21 255
* No artist for Stitchwing Skaab j21 256
* No artist for Svyelun of Sea and Sky j21 259
* No artist for Thought Monitor j21 261
* No artist for Tightening Coils j21 263
* No artist for Windcaller Aven j21 275
* No artist for Wonder j21 279
* No artist for Accursed Horde j21 282
* No artist for Asylum Visitor j21 286
* No artist for Azra Smokeshaper j21 287
* No artist for Bone Shards j21 298
* No artist for Cabal Initiate j21 300
* No artist for Carrier Thrall j21 302
* No artist for Changeling Outcast j21 304
* No artist for Clattering Augur j21 305
* No artist for Cordial Vampire j21 306
* No artist for Dark Salvation j21 308
* No artist for Death Wind j21 314
* No artist for Diregraf Colossus j21 316
* No artist for Discerning Taste j21 317
* No artist for Dregscape Sliver j21 319
* No artist for Echoing Return j21 320
* No artist for Endling j21 322
* No artist for Eyeblight Assassin j21 325
* No artist for Facevaulter j21 326
* No artist for Fleshbag Marauder j21 331
* No artist for Gilt-Blade Prowler j21 332
* No artist for Graveshifter j21 334
* No artist for Haunted Dead j21 336
* No artist for Heir to the Night j21 338b
* No artist for Heir of Falkenrath j21 338a
* No artist for Hell Mongrel j21 339
* No artist for Indulgent Aristocrat j21 340
* No artist for Kitchen Imp j21 342
* No artist for Leeching Sliver j21 344
* No artist for Legion Vanguard j21 345
* No artist for Markov Crusader j21 354
* No artist for Marrow-Gnawer j21 355
* No artist for Mind Rake j21 357
* No artist for Mob j21 359
* No artist for Necrogoyf j21 363
* No artist for Necromancer's Familiar j21 364
* No artist for Nested Shambler j21 365
* No artist for Nether Spirit j21 366
* No artist for Nezumi Cutthroat j21 367
* No artist for Okiba-Gang Shinobi j21 370
* No artist for Putrid Goblin j21 375
* No artist for Ransack the Lab j21 378
* No artist for Ruin Rat j21 381
* No artist for Sinister Starfish j21 383
* No artist for Skullsnatcher j21 384
* No artist for Sling-Gang Lieutenant j21 386
* No artist for Sudden Edict j21 389
* No artist for Throatseeker j21 391
* No artist for Tourach's Canticle j21 393
* No artist for Undead Augur j21 396
* No artist for Venomous Changeling j21 400
* No artist for Vermin Gorger j21 401
* No artist for Warteye Witch j21 404
* No artist for Young Necromancer j21 406
* No artist for Alchemist's Greeting j21 407
* No artist for Arcbound Slasher j21 408
* No artist for Arcbound Tracker j21 409
* No artist for Arcbound Whelp j21 410
* No artist for Battle Squadron j21 413
* No artist for Belligerent Sliver j21 415
* No artist for Bladeback Sliver j21 417
* No artist for Blazing Rootwalla j21 418
* No artist for Blisterstick Shaman j21 419
* No artist for Bloodbraid Marauder j21 420
* No artist for Blur Sliver j21 422
* No artist for Bogardan Dragonheart j21 423
* No artist for Breya's Apprentice j21 424
* No artist for Captain Ripley Vance j21 427
* No artist for Cleaving Sliver j21 430
* No artist for Dragon Mantle j21 437
* No artist for Dragon's Rage Channeler j21 438
* No artist for Faithless Salvaging j21 439
* No artist for Fiery Temper j21 440
* No artist for Fists of Flame j21 443
* No artist for Foundry Street Denizen j21 446
* No artist for Furyblade Vampire j21 448
* No artist for Galvanic Relay j21 450
* No artist for Geomancer's Gambit j21 452
* No artist for Goatnap j21 453
* No artist for Gouged Zealot j21 463
* No artist for Harmonic Prodigy j21 466
* No artist for Hollowhead Sliver j21 469
* No artist for Hordeling Outburst j21 470
* No artist for Igneous Elemental j21 471
* No artist for Incorrigible Youths j21 473
* No artist for Insatiable Gorgers j21 474
* No artist for Insolent Neonate j21 475
* No artist for Krenko's Command j21 480
* No artist for Kuldotha Flamefiend j21 481
* No artist for Lightning Spear j21 484
* No artist for Mad Prophet j21 487
* No artist for Ore-Scale Guardian j21 493
* No artist for Pashalik Mons j21 495
* No artist for Rage Forger j21 496
* No artist for Ravenous Bloodseeker j21 498
* No artist for Reckless Charge j21 500
* No artist for Reckless Racer j21 501
* No artist for Reckless Wurm j21 502
* No artist for Renegade Tactics j21 503
* No artist for Revolutionist j21 504
* No artist for Shiv's Embrace j21 511
* No artist for Skophos Reaver j21 513
* No artist for Slag Strider j21 514
* No artist for Spinehorn Minotaur j21 516
* No artist for Spiteful Sliver j21 517
* No artist for Spreading Insurrection j21 518
* No artist for Strike It Rich j21 521
* No artist for Striking Sliver j21 522
* No artist for Throes of Chaos j21 526
* No artist for Thunderbreak Regent j21 527
* No artist for Unholy Heat j21 529
* No artist for Viashino Lashclaw j21 530
* No artist for Adaptive Snapjaw j21 537
* No artist for Aetherstream Leopard j21 538
* No artist for Aeve, Progenitor Ooze j21 539
* No artist for Awaken the Bear j21 542
* No artist for Ayula, Queen Among Bears j21 543
* No artist for Bannerhide Krushok j21 544
* No artist for Battering Krasis j21 545
* No artist for Bear Cub j21 546
* No artist for Bestial Menace j21 547
* No artist for Chatterfang, Squirrel General j21 552
* No artist for Chatter of the Squirrel j21 553
* No artist for Chitterspitter j21 555
* No artist for Crocanura j21 557
* No artist for Duskshell Crawler j21 561
* No artist for Excavating Anurid j21 568
* No artist for Funnel-Web Recluse j21 573
* No artist for Glimmer Bairn j21 576
* No artist for Grizzly Bears j21 580
* No artist for Harrow j21 583
* No artist for Herd Baloth j21 584
* No artist for Hunting Pack j21 587
* No artist for Incremental Growth j21 588
* No artist for Jewel-Eyed Cobra j21 592
* No artist for Llanowar Tribe j21 598
* No artist for Manaweft Sliver j21 601
* No artist for Mother Bear j21 604
* No artist for Murasa Behemoth j21 606
* No artist for Nantuko Cultivator j21 607
* No artist for Parallel Lives j21 615
* No artist for Predatory Sliver j21 619
* No artist for Prey's Vengeance j21 620
* No artist for Runeclaw Bear j21 624
* No artist for Sanctum Weaver j21 627
* No artist for Savage Swipe j21 630
* No artist for Scale Up j21 631
* No artist for Scurry Oak j21 633
* No artist for Servant of the Scale j21 635
* No artist for Smell Fear j21 638
* No artist for Springbloom Druid j21 642
* No artist for Squirrel Sanctuary j21 645
* No artist for Squirrel Wrangler j21 647
* No artist for Striped Bears j21 648
* No artist for Sylvan Anthem j21 649
* No artist for Tajuru Pathwarden j21 650
* No artist for Tempered Sliver j21 652
* No artist for Timeless Witness j21 654
* No artist for Tireless Provisioner j21 655
* No artist for Trumpeting Herd j21 659
* No artist for Twin-Silk Spider j21 660
* No artist for Ulvenwald Mysteries j21 661
* No artist for Urban Daggertooth j21 662
* No artist for Verdant Command j21 664
* No artist for Webweaver Changeling j21 666
* No artist for Winding Way j21 670
* No artist for Wren's Run Hydra j21 672
* No artist for Arcus Acolyte j21 678
* No artist for Bred for the Hunt j21 681
* No artist for Captured by Lagacs j21 682
* No artist for Chainer, Nightmare Adept j21 683
* No artist for Chrome Courier j21 684
* No artist for Cloudshredder Sliver j21 685
* No artist for Combine Chrysalis j21 686
* No artist for Drey Keeper j21 687
* No artist for Elusive Krasis j21 688
* No artist for Etchings of the Chosen j21 689
* No artist for The First Sliver j21 691
* No artist for Goblin Anarchomancer j21 693
* No artist for Good-Fortune Unicorn j21 694
* No artist for Graceful Restoration j21 695
* No artist for Ingenious Infiltrator j21 697
* No artist for Lavabelly Sliver j21 701
* No artist for Lazotep Chancellor j21 702
* No artist for Lonis, Cryptozoologist j21 703
* No artist for Munitions Expert j21 705
* No artist for Nimbus Swimmer j21 706
* No artist for Priest of Fell Rites j21 707
* No artist for Prophetic Titan j21 708
* No artist for Rakdos Headliner j21 709
* No artist for Reap the Past j21 710
* No artist for Rotwidow Pack j21 712
* No artist for Ruination Rioter j21 713
* No artist for Shambleshark j21 714
* No artist for Soulherder j21 718
* No artist for Sterling Grove j21 720
* No artist for Storm God's Oracle j21 721
* No artist for Sythis, Harvest's Hand j21 722
* No artist for Terminal Agony j21 723
* No artist for Territorial Kavu j21 724
* No artist for Thundering Djinn j21 725
* No artist for Wavesifter j21 726
* No artist for Ravenous Squirrel j21 728
* No artist for Fast j21 730a
* No artist for Furious j21 730b
* No artist for Altar of the Goyf j21 733
* No artist for Amorphous Axe j21 734
* No artist for Batterbone j21 735
* No artist for Birthing Boughs j21 736
* No artist for Bonded Construct j21 738
* No artist for Implement of Combustion j21 744
* No artist for Monoskelion j21 748
* No artist for Myr Enforcer j21 749
* No artist for Myr Scrapling j21 750
* No artist for Nettlecyst j21 752
* No artist for Ornithopter of Paradise j21 753
* No artist for Sanctuary Raptor j21 755
* No artist for Treasure Keeper j21 758
* No artist for Universal Automaton j21 759
* No artist for Zabaz, the Glimmerwasp j21 762
* No artist for Khalni Garden j21 770
* No artist for Sliver Hive j21 776

**Comment by ZeldaZach** [comment]
Seems to be missing in the source, will investigate further

**Comment by ZeldaZach** [comment]
Should be fixed today
