### ISSUE TITLE
French Translation for double cards is missing

### ISSUE THREAD

**Issue by kennydee** [mtgjson/mtgjson#918]
#### Version(s) tested against
MTGJSON 5.2.0+20221002 (All Printings SQL)

#### Description of Bug
Since all double cards, it seems the missing translation is impossible to find in the foreign_data table (by the uuid, or multiverseid).
I even try to look at the french translation directly in the table, and they are not present at all.

Example to reproduce on "Howlpack Piper // Wildsong Howler" from VOW edition  which is "Joueuse de flûte de la hurlemeute // Hurleuse de chant sauvage" in french => "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=542017

Thanks again for this incredible files ;)

**Comment by zqft9001** [comment]
This looks to be an upstream issue, as Scryfall lists Howlpack Piper and other transform cards from VOW as only having English printings:

https://scryfall.com/card/vow/205/howlpack-piper-wildsong-howler

https://scryfall.com/search?q=set%3Avow+is%3Atransform&unique=cards&as=grid&order=name

**Comment by xxdede** [comment]
I confirm and add that there's no translations for all languages.
It seems a problem related to the name (containing the double slash).

I reported the bug on Scryfall website, let's see.

Scryfall reporting unique ID: 0c7f2113-ff12-4582-a0a7-d8fc2fe8e4f5

**Comment by ZeldaZach** [comment]
Unfortunately, Gatherer is _technically_ the final say of translations, and they're mostly broken for split/flip cards. If/when they fix this, it will automatically be imported. Not much we can do on our end :(
