### ISSUE TITLE
Gloomshrieker(NEO-219) has the English contents in Foreign object(in Korean)

### ISSUE THREAD

**Issue by giniman** [mtgjson/mtgjson#919]
#### Version(s) tested against

Gloomshrieker(NEO-219) has the English contents in Foreign object(in Korean)

**Comment by zqft9001** [comment]
This appears to persist into at least 5.2.0+20220516, and to all languages for this card.

Looks to be an upstream issue, but doesn't appear to be affecting all cards from NEO on Scryfall. Reported to Scryfall for this card.

Comparison:

Gloomshrieker
EN:
https://scryfall.com/card/neo/219/gloomshrieker
KO:
https://scryfall.com/card/neo/219/ko/gloomshrieker

Ao, the Dawn Sky (correct for KO and other languages checked)
EN:
https://scryfall.com/card/neo/2/ao-the-dawn-sky
KO:
https://scryfall.com/card/neo/2/ko/%EC%83%88%EB%B2%BD-%ED%95%98%EB%8A%98-%EC%95%84%EC%98%A4

**Comment by zqft9001** [comment]
This is a bigger issue, but it's all specific cards looks like. Still appears to be upstream.

Searching with 

```SELECT cards.name, cards.setCode, cards.text AS "english_text", foreign_data.text AS "foreign_text", foreign_data.`language`, cards.scryfallId FROM cards JOIN foreign_data ON cards.uuid = foreign_data.uuid WHERE cards.text = foreign_data.text AND cards.type NOT LIKE "%Basic Land%" AND cards.text NOT IN ("Vigilance", "Flash", "Menace");```

gives the below results (pulled text fields for brevity):


| name | setCode | language | scryfallId | 
| --- | --- | --- | --- | 
| Catti-brie of Mithral Hall | AFC | German | d3626ede-6c69-4fd5-8de1-cf85f50cd435 | 
| Catti-brie of Mithral Hall | AFC | Spanish | d3626ede-6c69-4fd5-8de1-cf85f50cd435 | 
| Catti-brie of Mithral Hall | AFC | French | d3626ede-6c69-4fd5-8de1-cf85f50cd435 | 
| Catti-brie of Mithral Hall | AFC | Italian | d3626ede-6c69-4fd5-8de1-cf85f50cd435 | 
| Catti-brie of Mithral Hall | AFC | Japanese | d3626ede-6c69-4fd5-8de1-cf85f50cd435 | 
| Catti-brie of Mithral Hall | AFC | Portuguese (Brazil) | d3626ede-6c69-4fd5-8de1-cf85f50cd435 | 
| Catti-brie of Mithral Hall | AFC | Russian | d3626ede-6c69-4fd5-8de1-cf85f50cd435 | 
| Catti-brie of Mithral Hall | AFC | Chinese Simplified | d3626ede-6c69-4fd5-8de1-cf85f50cd435 | 
| Catti-brie of Mithral Hall | AFC | Chinese Traditional | d3626ede-6c69-4fd5-8de1-cf85f50cd435 | 
| Trelasarra, Moon Dancer | AFR | German | f6a4b54c-a8fa-464e-a3dd-f3f3a08606f5 | 
| Trelasarra, Moon Dancer | AFR | Spanish | f6a4b54c-a8fa-464e-a3dd-f3f3a08606f5 | 
| Trelasarra, Moon Dancer | AFR | French | f6a4b54c-a8fa-464e-a3dd-f3f3a08606f5 | 
| Trelasarra, Moon Dancer | AFR | Italian | f6a4b54c-a8fa-464e-a3dd-f3f3a08606f5 | 
| Trelasarra, Moon Dancer | AFR | Japanese | f6a4b54c-a8fa-464e-a3dd-f3f3a08606f5 | 
| Trelasarra, Moon Dancer | AFR | Korean | f6a4b54c-a8fa-464e-a3dd-f3f3a08606f5 | 
| Trelasarra, Moon Dancer | AFR | Portuguese (Brazil) | f6a4b54c-a8fa-464e-a3dd-f3f3a08606f5 | 
| Trelasarra, Moon Dancer | AFR | Russian | f6a4b54c-a8fa-464e-a3dd-f3f3a08606f5 | 
| Trelasarra, Moon Dancer | AFR | Chinese Simplified | f6a4b54c-a8fa-464e-a3dd-f3f3a08606f5 | 
| Trelasarra, Moon Dancer | AFR | Chinese Traditional | f6a4b54c-a8fa-464e-a3dd-f3f3a08606f5 | 
| Aeon Chronicler | C16 | German | 8d108f7a-d255-424d-8936-340150371e81 | 
| Aeon Chronicler | C16 | Spanish | 8d108f7a-d255-424d-8936-340150371e81 | 
| Aeon Chronicler | C16 | French | 8d108f7a-d255-424d-8936-340150371e81 | 
| Aeon Chronicler | C16 | Italian | 8d108f7a-d255-424d-8936-340150371e81 | 
| Aeon Chronicler | C16 | Japanese | 8d108f7a-d255-424d-8936-340150371e81 | 
| Aeon Chronicler | C16 | Portuguese (Brazil) | 8d108f7a-d255-424d-8936-340150371e81 | 
| Aeon Chronicler | C16 | Chinese Simplified | 8d108f7a-d255-424d-8936-340150371e81 | 
| Trial // Error | C16 | German | 383451e1-9b97-4c85-a044-7c68b61c8c65 | 
| Trial // Error | C16 | Spanish | 383451e1-9b97-4c85-a044-7c68b61c8c65 | 
| Trial // Error | C16 | French | 383451e1-9b97-4c85-a044-7c68b61c8c65 | 
| Trial // Error | C16 | Italian | 383451e1-9b97-4c85-a044-7c68b61c8c65 | 
| Trial // Error | C16 | Japanese | 383451e1-9b97-4c85-a044-7c68b61c8c65 | 
| Trial // Error | C16 | Portuguese (Brazil) | 383451e1-9b97-4c85-a044-7c68b61c8c65 | 
| Trial // Error | C16 | Chinese Simplified | 383451e1-9b97-4c85-a044-7c68b61c8c65 | 
| Trial // Error | C16 | German | 383451e1-9b97-4c85-a044-7c68b61c8c65 | 
| Trial // Error | C16 | Spanish | 383451e1-9b97-4c85-a044-7c68b61c8c65 | 
| Trial // Error | C16 | French | 383451e1-9b97-4c85-a044-7c68b61c8c65 | 
| Trial // Error | C16 | Italian | 383451e1-9b97-4c85-a044-7c68b61c8c65 | 
| Trial // Error | C16 | Japanese | 383451e1-9b97-4c85-a044-7c68b61c8c65 | 
| Trial // Error | C16 | Portuguese (Brazil) | 383451e1-9b97-4c85-a044-7c68b61c8c65 | 
| Trial // Error | C16 | Chinese Simplified | 383451e1-9b97-4c85-a044-7c68b61c8c65 | 
| Flood of Recollection | CMR | Chinese Traditional | c14a5b69-ce04-40fc-9933-20b16537de24 | 
| Karfell Kennel-Master | KHM | German | f670c380-6faa-42ec-ab41-6be8137169b2 | 
| Karfell Kennel-Master | KHM | Spanish | f670c380-6faa-42ec-ab41-6be8137169b2 | 
| Karfell Kennel-Master | KHM | French | f670c380-6faa-42ec-ab41-6be8137169b2 | 
| Karfell Kennel-Master | KHM | Italian | f670c380-6faa-42ec-ab41-6be8137169b2 | 
| Karfell Kennel-Master | KHM | Japanese | f670c380-6faa-42ec-ab41-6be8137169b2 | 
| Karfell Kennel-Master | KHM | Korean | f670c380-6faa-42ec-ab41-6be8137169b2 | 
| Karfell Kennel-Master | KHM | Portuguese (Brazil) | f670c380-6faa-42ec-ab41-6be8137169b2 | 
| Karfell Kennel-Master | KHM | Chinese Simplified | f670c380-6faa-42ec-ab41-6be8137169b2 | 
| Karfell Kennel-Master | KHM | Chinese Traditional | f670c380-6faa-42ec-ab41-6be8137169b2 | 
| Deathmark | M12 | Korean | b101ff4a-8617-4c0a-8503-ed8c857ad000 | 
| Gloomshrieker | NEO | German | a2b50751-7f65-4321-86da-eef735bf8b67 | 
| Gloomshrieker | NEO | Spanish | a2b50751-7f65-4321-86da-eef735bf8b67 | 
| Gloomshrieker | NEO | French | a2b50751-7f65-4321-86da-eef735bf8b67 | 
| Gloomshrieker | NEO | Italian | a2b50751-7f65-4321-86da-eef735bf8b67 | 
| Gloomshrieker | NEO | Japanese | a2b50751-7f65-4321-86da-eef735bf8b67 | 
| Gloomshrieker | NEO | Korean | a2b50751-7f65-4321-86da-eef735bf8b67 | 
| Gloomshrieker | NEO | Portuguese (Brazil) | a2b50751-7f65-4321-86da-eef735bf8b67 | 
| Gloomshrieker | NEO | Russian | a2b50751-7f65-4321-86da-eef735bf8b67 | 
| Gloomshrieker | NEO | Chinese Simplified | a2b50751-7f65-4321-86da-eef735bf8b67 | 
| Gloomshrieker | NEO | Chinese Traditional | a2b50751-7f65-4321-86da-eef735bf8b67 | 
| Nylea's Huntmaster | THB | Chinese Simplified | 2a4fe89a-0d2b-493f-883e-a1e0b0918340 |

**Comment by zqft9001** [comment]
---
| name | setCode | URL |
| --- | --- | --- |
| Catti-brie of Mithral Hall | AFC | https://scryfall.com/card/afc/44/de/ | 
| Catti-brie of Mithral Hall | AFC | https://scryfall.com/card/afc/44/es/ | 
| Catti-brie of Mithral Hall | AFC | https://scryfall.com/card/afc/44/fr/ | 
| Catti-brie of Mithral Hall | AFC | https://scryfall.com/card/afc/44/it/ | 
| Catti-brie of Mithral Hall | AFC | https://scryfall.com/card/afc/44/ja/ | 
| Catti-brie of Mithral Hall | AFC | https://scryfall.com/card/afc/44/pt/ | 
| Catti-brie of Mithral Hall | AFC | https://scryfall.com/card/afc/44/ru/ | 
| Catti-brie of Mithral Hall | AFC | https://scryfall.com/card/afc/44/zhs/ | 
| Catti-brie of Mithral Hall | AFC | https://scryfall.com/card/afc/44/zht/ | 
| Trelasarra, Moon Dancer | AFR | https://scryfall.com/card/afr/236/de/ | 
| Trelasarra, Moon Dancer | AFR | https://scryfall.com/card/afr/236/es/ | 
| Trelasarra, Moon Dancer | AFR | https://scryfall.com/card/afr/236/fr/ | 
| Trelasarra, Moon Dancer | AFR | https://scryfall.com/card/afr/236/it/ | 
| Trelasarra, Moon Dancer | AFR | https://scryfall.com/card/afr/236/ja/ | 
| Trelasarra, Moon Dancer | AFR | https://scryfall.com/card/afr/236/ko/ | 
| Trelasarra, Moon Dancer | AFR | https://scryfall.com/card/afr/236/pt/ | 
| Trelasarra, Moon Dancer | AFR | https://scryfall.com/card/afr/236/ru/ | 
| Trelasarra, Moon Dancer | AFR | https://scryfall.com/card/afr/236/zhs/ | 
| Trelasarra, Moon Dancer | AFR | https://scryfall.com/card/afr/236/zht/ | 
| Aeon Chronicler | C16 | https://scryfall.com/card/c16/82/de/ | 
| Aeon Chronicler | C16 | https://scryfall.com/card/c16/82/es/ | 
| Aeon Chronicler | C16 | https://scryfall.com/card/c16/82/fr/ | 
| Aeon Chronicler | C16 | https://scryfall.com/card/c16/82/it/ | 
| Aeon Chronicler | C16 | https://scryfall.com/card/c16/82/ja/ | 
| Aeon Chronicler | C16 | https://scryfall.com/card/c16/82/pt/ | 
| Aeon Chronicler | C16 | https://scryfall.com/card/c16/82/zhs/ | 
| Trial // Error | C16 | https://scryfall.com/card/c16/239/de/ | 
| Trial // Error | C16 | https://scryfall.com/card/c16/239/es/ | 
| Trial // Error | C16 | https://scryfall.com/card/c16/239/fr/ | 
| Trial // Error | C16 | https://scryfall.com/card/c16/239/it/ | 
| Trial // Error | C16 | https://scryfall.com/card/c16/239/ja/ | 
| Trial // Error | C16 | https://scryfall.com/card/c16/239/pt/ | 
| Trial // Error | C16 | https://scryfall.com/card/c16/239/zhs/ | 
| Trial // Error | C16 | https://scryfall.com/card/c16/239/de/ | 
| Trial // Error | C16 | https://scryfall.com/card/c16/239/es/ | 
| Trial // Error | C16 | https://scryfall.com/card/c16/239/fr/ | 
| Trial // Error | C16 | https://scryfall.com/card/c16/239/it/ | 
| Trial // Error | C16 | https://scryfall.com/card/c16/239/ja/ | 
| Trial // Error | C16 | https://scryfall.com/card/c16/239/pt/ | 
| Trial // Error | C16 | https://scryfall.com/card/c16/239/zhs/ | 
| Flood of Recollection | CMR | https://scryfall.com/card/cmr/61/zht/ | 
| Karfell Kennel-Master | KHM | https://scryfall.com/card/khm/101/de/ | 
| Karfell Kennel-Master | KHM | https://scryfall.com/card/khm/101/es/ | 
| Karfell Kennel-Master | KHM | https://scryfall.com/card/khm/101/fr/ | 
| Karfell Kennel-Master | KHM | https://scryfall.com/card/khm/101/it/ | 
| Karfell Kennel-Master | KHM | https://scryfall.com/card/khm/101/ja/ | 
| Karfell Kennel-Master | KHM | https://scryfall.com/card/khm/101/ko/ | 
| Karfell Kennel-Master | KHM | https://scryfall.com/card/khm/101/pt/ | 
| Karfell Kennel-Master | KHM | https://scryfall.com/card/khm/101/zhs/ | 
| Karfell Kennel-Master | KHM | https://scryfall.com/card/khm/101/zht/ | 
| Deathmark | M12 | https://scryfall.com/card/m12/90/ko/ | 
| Gloomshrieker | NEO | https://scryfall.com/card/neo/219/de/ | 
| Gloomshrieker | NEO | https://scryfall.com/card/neo/219/es/ | 
| Gloomshrieker | NEO | https://scryfall.com/card/neo/219/fr/ | 
| Gloomshrieker | NEO | https://scryfall.com/card/neo/219/it/ | 
| Gloomshrieker | NEO | https://scryfall.com/card/neo/219/ja/ | 
| Gloomshrieker | NEO | https://scryfall.com/card/neo/219/ko/ | 
| Gloomshrieker | NEO | https://scryfall.com/card/neo/219/pt/ | 
| Gloomshrieker | NEO | https://scryfall.com/card/neo/219/ru/ | 
| Gloomshrieker | NEO | https://scryfall.com/card/neo/219/zhs/ | 
| Gloomshrieker | NEO | https://scryfall.com/card/neo/219/zht/ | 
| Nylea's Huntmaster | THB | https://scryfall.com/card/thb/187/zhs/ |

**Comment by ZeldaZach** [comment]
Upstream has nulled out these values, since they're incorrect. If they ever get updated, we can restore the true values.
