### ISSUE TITLE
Multiple Sealed Products contains incorrect tcg player ids

### ISSUE THREAD

**Issue by GooseDeer** [mtgjson/mtgjson#920]
#### Version(s) tested against
2022-03-01
5.2.0+20220301

#### Description of Bug
I have gathered a list of mtg sets that contain incorrect sealed projects and therefor incorrect tcgplayer ids.

 
| code   | name                                      | sealed product name                                    | tcgplayer id |
|--------|-------------------------------------------|--------------------------------------------------------|--------------|
| "GN2"  | "Game Night 2019"                         | "Magic Game Night Set"                                 | "175171"     |
| "GNT"  | "Game Night"                              | "Magic Game Night Set"                                 | "175171"     |
| "H1R"  | "Modern Horizons 1 Timeshifts"            | "Modern Horizons Booster Pack"                         | "185892"     |
| "MH1"  | "Modern Horizons"                         | "Modern Horizons Booster Pack"                         | "185892"     |
| "H1R"  | "Modern Horizons 1 Timeshifts"            | "Modern Horizons Booster Box"                          | "185894"     |
| "MH1"  | "Modern Horizons"                         | "Modern Horizons Booster Box"                          | "185894"     |
| "H1R"  | "Modern Horizons 1 Timeshifts"            | "Modern Horizons Booster Box Case"                     | "190885"     |
| "MH1"  | "Modern Horizons"                         | "Modern Horizons Booster Box Case"                     | "190885"     |
| "MH1"  | "Modern Horizons"                         | "Modern Horizons 3 Booster Draft Pack"                 | "192628"     |
| "H1R"  | "Modern Horizons 1 Timeshifts"            | "Modern Horizons 3 Booster Draft Pack"                 | "192628"     |
| "CMB2" | "Mystery Booster Playtest Cards 2021"     | "Mystery Booster Booster Pack Convention Edition"      | "202644"     |
| "CMB1" | "Mystery Booster Playtest Cards 2019"     | "Mystery Booster Booster Pack Convention Edition"      | "202644"     |
| "CMB1" | "Mystery Booster Playtest Cards 2019"     | "Mystery Booster Booster Box Convention Edition"       | "217533"     |
| "CMB2" | "Mystery Booster Playtest Cards 2021"     | "Mystery Booster Booster Box Convention Edition"       | "217533"     |
| "CMB2" | "Mystery Booster Playtest Cards 2021"     | "Mystery Booster Booster Box Convention Edition 2021"  | "246935"     |
| "CMB1" | "Mystery Booster Playtest Cards 2019"     | "Mystery Booster Booster Box Convention Edition 2021"  | "246935"     |
| "CMB2" | "Mystery Booster Playtest Cards 2021"     | "Mystery Booster Booster Pack Convention Edition 2021" | "246936"     |
| "CMB1" | "Mystery Booster Playtest Cards 2019"     | "Mystery Booster Booster Pack Convention Edition 2021" | "246936"     |
| "EVG"  | "Duel Decks Anthology: Elves vs. Goblins" | "Duel Decks Elves vs Goblins Box Set"                  | "32805"      |
| "DD1"  | "Duel Decks: Elves vs. Goblins"           | "Duel Decks Elves vs Goblins Box Set"                  | "32805"      |

Take `Game Night 2019` for example, the sealed product for this set should be `Magic Game Night 2019 Set` with a tcgplayer id of `199357` and `Game Night` the sealed product for this set should be `Magic Game Night Set` with a tcgplayer id of `175171`

**Comment by kodawah** [comment]
i think this got recently fixed by @axxroytovu's code, would you be able to double check?

**Comment by axxroytovu** [comment]
My code didn't change anything coming from TCGplayer. 

Is the bug just a problem with the sealed product names, or a problem with which set code the product is associated with?

**Comment by axxroytovu** [comment]
Should be fixed with https://github.com/mtgjson/mtg-sealed-content/pull/86

Will load into tomorrow's build

**Comment by kodawah** [comment]
@ZeldaZach we can close this one
