### ISSUE TITLE
Keyrune Code for Elves Vs Goblins Duel Deck incorrect. 

### ISSUE THREAD

**Issue by ThePieBandit** [mtgjson/mtgjson#923]
#### Version(s) tested against

MTGJSSON 5.2.0

#### Description of Bug
The keyrune code for Elves Vs Goblins is incorrect. This impacts both the original and Anthologies version. Keyrune uses EVG, the json lists it as DD1 
https://keyrune.andrewgioia.com/icons.html?icon=evg

**Comment by van-riper** [comment]
@ZeldaZach this can be fixed by adding `{"DD1": "EVG"}` to [keyrune_code_overrides.json](https://github.com/mtgjson/mtgjson/blob/master/mtgjson5/resources/keyrune_code_overrides.json) right?

**Comment by ZeldaZach** [comment]
Yep, correct @maallaard!  Got a fix in
