### ISSUE TITLE
Pricing file issues

### ISSUE THREAD

**Issue by SteButler** [mtgjson/mtgjson#925]
The pricing file (as at 19/03/2022, downloaded from the site) doesnt seem to follow the "finishes" column for any given uuid. EG : 

Card uuid "075d381a-35ff-583a-91ad-94570f6b8260" has finishes = "etched"

The JSON has entries for :
    cardmarket->retail->normal
    cardmarket->retail->foil

There is no entry for ->etched for any pricing source.

Can finishes and the pricing file be aligned?

**Comment by van-riper** [comment]
what is the name of this card and from what set?

**Comment by SteButler** [comment]
The Example is Tormod, the Desecrator, CMR 569. But I dont think it's limited to one single card.

**Comment by van-riper** [comment]
it looks like cardmarket is the only vendor that doesn't have an etched option. I would need to know of another card or two with this same exact issue in order to find a pattern and fix it

**Comment by ZeldaZach** [comment]
This appears to be a limitation of CardMarket, as they don't discern etched vs normal foil. Unfortunately there isn't much I can until they work towards their new API that will hopefully support this functionality.
