### ISSUE TITLE
Prossh, Skyraider of Kher has a duplicate name

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#93]
The entry for Prossh, Skyraider of Kher has "names": ["Prossh, Skyraider of Kher", "Prossh, Skyraider of Kher"] for some reason.

**Comment by ZeldaZach** [comment]
This looks like a weird one-off with Scryfall. I checked cards such as Oloro, Avenger of Zendikar, and others from that set but none seem to have this weird qwirk.

cc: @csuhta

**Comment by csuhta** [comment]
This is fixed upstream for Prosh

**Comment by ZeldaZach** [comment]
Will be addressed in the next build
