### ISSUE TITLE
Two cards missing otherFaceIds

### ISSUE THREAD

**Issue by Rodentman87** [mtgjson/mtgjson#933]
#### Version(s) tested against
MTGJSON 5.2.0+20220406

#### Description of Bug
All three paper versions of Alrund, God of the Cosmos (KHM 40, KHM 302, PKHM 40s) and the Secret Lair version of Zndrsplt, Eye of Wisdom are missing otherFaceIds (on both sides of each card)

**Comment by ZeldaZach** [comment]
Thanks for the report! I've confirmed this to be an issue and am working on a fix. Seems to affect cards that were apart of the historic rebalance setup
