### ISSUE TITLE
ANEO tokens have two b sides

### ISSUE THREAD

**Issue by Hamusutaa** [mtgjson/mtgjson#934]
#### Version(s) tested against
5.2.0+20220414

#### Description of Bug
In the Neon Dynasty Art Series (ANEO) tokens, most of the tokens have two "b" sides and no "a" side.  20 of the 81 tokens correctly have an "a" and a "b" side.

**Comment by GooseDeer** [comment]
This seem to be an issue with New Capenna Art Series (ASNC) as well. However in this set all the tokens are marked as side b

**Comment by ZeldaZach** [comment]
Thanks for the ticket. I’ll try to take a look over the weekend

**Comment by ZeldaZach** [comment]
Confirmed upstream is missing an attribute we rely on -- I've let them know and will update here when I have more information.

**Comment by MidnightLightning** [comment]
Adding on that the Midnight Hunt Art Series (AMID) records also have this issue; multiple have only "B" sides. The art card "sides" were recognized as wrong in #709 and supposedly fixed; is that fix now the upstream thing that's not working?
