### ISSUE TITLE
Mtgo tix prices?

### ISSUE THREAD

**Issue by ghost** [mtgjson/mtgjson#935]
I've seen that you get mtgo prices from Cardhoarder in USD. Is there a conversion rate I can get programmatically to convert mtgo prices to TIX?

**Comment by ZeldaZach** [comment]
CardHoarder prices value MTGO Tickets at $1/each from what I understand. @cheyner might be able to provide more insight if my assumption is wrong.

**Comment by ZeldaZach** [comment]
@HarleyQuinn-Z6 You can safely assume that Tix are 1:1 for USD
