### ISSUE TITLE
ADD LOW MID HIGH PRICE in ALLPRICES.JSON

### ISSUE THREAD

**Issue by rjrportillo** [mtgjson/mtgjson#936]
I am currently using the ALLPRICE.JSON file and it is a HUGE help in automating my pricing and inventory processes in my newly opened online singles shop (hopefully, I can afford to open a full pledged LGS soon). However, the market here in our country uses TCG MID prices in pricing singles. Would really appreciate it if this pricing data is added to the ALLPRICE.JSON file. Cheers!

**Comment by ZeldaZach** [comment]
Glad AllPrices provided you some use! Unfortunately I don't plan on extending that file with this kind of data at this time, but maybe in a future iteration of the file, that can be more easily digested, we can consider it
