### ISSUE TITLE
Card entires with the same name are collapsed in allCards.json

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#94]
Some card entries in the individual set files have the exact same key. ("Everythingamajig", "Ineffable Blessing", etc.) When creating allCards.json, all of these entries are improperly collapsed, leading to a single entry that only has the correct text of one of the variants. (Except it will have a "names" field containing an array of its own name several times.)

**Comment by KingSupernova31** [comment]
This is the cause for #86 as well.

**Comment by ZeldaZach** [comment]
So just thinking about this a bit further (no code work done at all)... what's a good solution? If there's a card with multiple rulings texts (i.e. un-cards only) how should we handle it? The cheapest solution we can do is to not include un-cards in these output files, but is that a good idea? I like having _all_ data available.

We'd need to come up with a better method to combine them. Open to ideas.

**Comment by KingSupernova31** [comment]
The way that makes sense to me would be to append " (a)", " (b)", etc to the key in allCards.json. (This matches how most other websites and applications handle them.) The "name" field of the card itself should remain just the actual name of the card, and there could be a "variant" field on the card object that only exists if the card has multiple variants in the same expansion.

This does have a couple potential issues, but I think it covers most use cases and I'm not sure I see a better way.
