### ISSUE TITLE
cardKingdomId identifier seemingly missing

### ISSUE THREAD

**Issue by HighlyTrainedNeuralNetwork** [mtgjson/mtgjson#945]
#### Description of Bug
Looking at the latest available version of AllPrintings and AllIdentifiers at https://mtgjson.com/api/v5/ the cardKingdomId identifer seems to no longer be present. Documentation at https://mtgjson.com/data-models/identifiers/ still suggests that this identifier should be present. To provide a concrete example, the card "Ancestor's Chosen" with scryfallID "7a5cd03c-4227-4551-aa4b-7d119f0468b5" was listed as having the cardKingdomId of "122719" as recently as the 24th of this month.

**Comment by HighlyTrainedNeuralNetwork** [comment]
Issue no longer present after latest update. Unclear why it occurred in this specific case.

**Comment by ZeldaZach** [comment]
@HighlyTrainedNeuralNetwork It's possible a 3rd party provider of ours was down during an update time, causing IDs to go missing. In those cases, simply waiting for a rebuild or pinging me on Discord can usually lead to quick resolutions
