### ISSUE TITLE
Misplaced SKU entries in TCGplayer SKUS

### ISSUE THREAD

**Issue by nhrsn** [mtgjson/mtgjson#947]
#### Version(s) tested against

MTGJSON Version: v5.2.0+20220530
SKUs File: https://mtgjson.com/api/v5/TcgplayerSkus.json.zip

#### Description of Bug

321 entries in the TcgplayerSkus file have SKU data for incorrect TCGplayer product IDs alongside their correct SKU data. The misplaced SKUs seem to be for related printings (i.e alt art, ext art), and exist under their correct UUID.

Examples:

- Infuriate, Strixhaven Mystical Archive (ae5d691c-6ddf-58b0-ada0-4a1c07fd904e)
- Persist, Modern Horizons 2 (6a9e6512-8aa9-5690-90f4-8f92d1d82c49)
- Scion of Halaster, Commander Legends: Battle for Baldur's Gate (8f82d67a-4fba-53e8-94a1-f7bdf350335f)

[Full List (JSON Format)](https://github.com/mtgjson/mtgjson/files/8831379/misplaced.txt)

#### Workaround

If you have matched UUIDs to TCGplayer Product IDs, you can strip these misplaced SKUs from the dataset. In Ruby:

```
if sku_list.map { |sku| sku['productId'] }.uniq.count > 1
    correct_product_id = Card.find_by(uuid: uuid).tcgplayer_product_id
    sku_list = sku_list.select { |sku| sku['productId'] == correct_product_id }
end
```

**Comment by kodawah** [comment]
it could honestly be tcg acting up, do you have the possibility to check the raw tcg api call for those ids?

cc @tpblaster

**Comment by nhrsn** [comment]
I wouldn't be surprised.

[tcg_results.txt](https://github.com/mtgjson/mtgjson/files/10061266/tcg_results.txt)

Not exactly raw, as my API implementation does some additional mappings. Namely, it finds the `set_name` for the `groupId` and indexes `skus` by their ID.

These results look okay to me.

**Comment by tpblaster** [comment]
Are you stilling having issues with this?

**Comment by nhrsn** [comment]
Yes, and there are a few more now. 333 in total.

Here's an updated list (JSON):

[misplaced_skus.txt](https://github.com/mtgjson/mtgjson/files/10451934/misplaced_skus.txt)

**Comment by ZeldaZach** [comment]
Hey @nickhrsn can you possibly explain what the issue is, in a greater detail? Maybe include some concrete examples so I can understand to a greater degree and consider potential changes to the service

**Comment by tpblaster** [comment]
Since we get all this data directly from TCGPlayer, I lean towards it being a catalog issue on their end. You can email the catalog person there and potentially get it fixed on there backend, which will pass through to the file.

**Comment by ZeldaZach** [comment]
That's kind of what I see this as myself @tpblaster -- I'm not sure this is a change our end should support as technically an upstream provider needs to address their own catalog

**Comment by nhrsn** [comment]
Apologies for the delay. I realize this comes down to the treatment of variants (e.g Foil Etched).

Here's a detailed example for Talisman of Creativity from Modern Horizon 1 Timeshifts #34 (01c3caea-becc-5d27-b75a-cd27d901dc4c).

SKUs provided by mtgjson ([mtg_json_skus.json.txt](https://github.com/mtgjson/mtgjson/files/10514006/mtg_json_skus.json.txt))

SKUs from the raw TCGplayer API ([tcg_player_skus.json.txt](https://github.com/mtgjson/mtgjson/files/10514037/tcg_player_skus.json.txt))

- There exist SKUs for TCGplayer product ID `240130` and `240131` in the mtgjson dataset
- The raw TCGplayer API returns only results for `240131`
- It turns out `240130` is the foil etched variant, which would be matched via mtgjson's `tcgplayerEtchedProductId`

I think it's correct to close this issue.
