### ISSUE TITLE
Cards Removed from POR, AER, KLD, etc.

### ISSUE THREAD

**Issue by nhrsn** [mtgjson/mtgjson#948]
#### Version(s) tested against

v5.2.0+20220613

Pulled from AllPrintings.json

#### Description of Bug

Cards Removed:

1. 4ED Ali Baba [Scryfall](https://scryfall.com/card/4ed/175/ali-baba)
2. AER Renegade Map [Scryfall](https://scryfall.com/card/aer/173/renegade-map)
3. AER Reservoir Walker [Scryfall](https://scryfall.com/card/aer/174/reservoir-walker)
4. AER Scrap Trawler [Scryfall](https://scryfall.com/card/aer/175/scrap-trawler)
5. KLD Wild Wanderer [Scryfall](https://scryfall.com/card/kld/173/wild-wanderer)
6. KLD Wildest Dreams [Scryfall](https://scryfall.com/card/kld/174/wildest-dreams)
7. KLD Wily Bandar [Scryfall](https://scryfall.com/card/kld/175/wily-bandar)
8. MID Briarbridge Tracker [Scryfall](https://scryfall.com/card/mid/172/briarbridge-tracker)
9. MIR Flame Elemental [Scryfall](https://scryfall.com/card/mir/175/flame-elemental)
10. ODY Barbarian Lunatic [Scryfall](https://scryfall.com/card/ody/175/barbarian-lunatic)
11. OGW Needle Spires [Scryfall](https://scryfall.com/card/ogw/175/needle-spires)
12. POR Elven Cache (164) [Scryfall](https://scryfall.com/card/por/164/elven-cache)
13. POR Elven Cache (164s) [Scryfall](https://scryfall.com/card/por/164s/zhs/elven-cache)
14. POR Charging Rhino [Scryfall](https://scryfall.com/card/por/161/charging-rhino)
15. POR Deep Wood [Scryfall](https://scryfall.com/card/por/162/deep-wood)

**Comment by ZeldaZach** [comment]
Looks like upstream had some URL inconsistencies, I've raised an alert with them.

**Comment by AEFeinstein** [comment]
Also https://scryfall.com/card/por/163/elite-cat-warrior

**Comment by AEFeinstein** [comment]
🎉
