### ISSUE TITLE
code is missing

### ISSUE THREAD

**Issue by Kasburn666** [mtgjson/mtgjson#95]
Hello,
i don't know where to put this request so i put here :
in the json AllSets.json available here : https://mtgjson.com/v4/json/AllSets.json , the json key "code" is missing for all sets, can you add this key plz ?

**Comment by ZeldaZach** [comment]
Haha whoops. Was my mistake. https://github.com/mtgjson/mtgjson4/blob/master/mtgjson4/__main__.py#L797 Simple one line fix (aka remove the line).

Will have this up by next week (I'm a bit busy this week and can't do a full rebuild)

**Comment by Kasburn666** [comment]
Ok thx do this when you can

**Comment by KingSupernova31** [comment]
"isOnlineOnly" and "meta" are also missing from allSets.json.
