### ISSUE TITLE
Add spellbook information for Arena cards.

### ISSUE THREAD

**Issue by CajunAvenger** [mtgjson/mtgjson#954]
Arena now has 24 cards and growing that use the Spellbook mechanic which allows a card to conjure from a specific list, can that list get added in some form to the jsons?

Unfortunately those aren't currently attached to the card data on Scryfall (I sent a feature request there a few weeks back so maybe eventually), but you can get spellbooks on api calls with `spellbook:"Card Name"` eg https://api.scryfall.com/cards/search?&q=spellbook:%22Big%20Spender%22, and if a card has a spell book if its text contains `"~'s spellbook"` (or `"spellbook" + /draft|conjure/` to skip the card name check).

Simplest implementation of `spellbook: ["array", "of", "card names"]` is fine, a beefier/future-proofed version of like `relatedCards: {spellbook: ["array", "of", "card names"]}` would be neat but not necessary.

**Comment by ZeldaZach** [comment]
I like the idea! Gotta think about how I want to support the data, but it's very reasonable
