### ISSUE TITLE
Etched Foils Missing tcgplayerProductId

### ISSUE THREAD

**Issue by AEFeinstein** [mtgjson/mtgjson#955]
#### Version(s) tested against
[v5.2.0+20220719](https://mtgjson.com/changelog/mtgjson-v5/)

#### Description of Bug

hm, it seems like the etched foil variants in 2X2 don't have `tcgplayerProductId` like the other variants:
```
Cardname                  (NUM): TCGP ID
Emrakul, the Aeons Torn     (1): 276660
Kozilek, Butcher of Truth   (2): 276259
Ulamog, the Infinite Gyre   (3): 276353
Emrakul, the Aeons Torn   (335): 276661
Kozilek, Butcher of Truth (336): 276317
Ulamog, the Infinite Gyre (337): 276355
Emrakul, the Aeons Torn   (413): -1
Kozilek, Butcher of Truth (414): -1
Ulamog, the Infinite Gyre (415): -1
Emrakul, the Aeons Torn   (575): 276801
Kozilek, Butcher of Truth (576): 276444
Ulamog, the Infinite Gyre (577): 276356
```

Maybe it has something to do with TGCP putting "(Foil Etched)" in the product name?
https://www.tcgplayer.com/product/276796/magic-double-masters-2022-emrakul-the-aeons-torn-foil-etched

This also seems to be the case for Commander Legends etched foils. If other sets have foil etched cards, it may apply to them as well.

**Comment by kodawah** [comment]
I'm pretty sure this is by design due to upstream handling of etched cards - if the card is etched-only you need to check for the etched tcgid

If I recall correctly this was the case for CMR cards too

**Comment by AEFeinstein** [comment]
You are correct, and I missed the memo when that separate identifier was added. Fixed my own problem in https://github.com/AEFeinstein/Mtgjson2Familiar/commit/f6659d1e9102e67dae979c208e501cadeb428e84. Thanks!
