### ISSUE TITLE
ZEN non-fullart basics were not available as foils

### ISSUE THREAD

**Issue by taw** [mtgjson/mtgjson#956]
https://mtgjson.com/api/v5/ZEN.json

As far as I understand, the non-fullart basics (230a to 249a) were only available in precons and so only in nonfoil.
Boosters contained fullart basics (230 to 249), foil and nonfoil.

 Mtgjson has all of them listed as available both `"hasFoil": true` and `"hasNonFoil": true`.  Only the fullart version should be  `"hasFoil": true`.

**Comment by zqft9001** [comment]
This appears to be an upstream issue, as Scryfall reports both variants as having foil and standard printings.

https://api.scryfall.com/cards/zen/230

https://api.scryfall.com/cards/zen/230a

**Comment by ZeldaZach** [comment]
All fixed!
