### ISSUE TITLE
"Masters Edition" listed twice against "MED" and "ME1" set codes

### ISSUE THREAD

**Issue by ghost** [mtgjson/mtgjson#96]
The set "Masters Edition" is listed twice in AllSets.json against "MED" and "ME1" set codes. According to Scryfall, "ME1" is the correct code for "Masters Edition" and "MED" should be used for "Mythic Edition". "Mythic Edition" appears to be missing altogether from AllSets.json.

**Comment by ZeldaZach** [comment]
https://api.scryfall.com/sets/ME1 shows Masters Edition
https://api.scryfall.com/sets/MED shows Masters Edition

This appears to be an upstream issue: cc @csuhta

**Comment by csuhta** [comment]
@ZeldaZach This is fixed on Scryfall

**Comment by ZeldaZach** [comment]
Will require a rebuild, which will be done in 4.0.2

**Comment by tooomm** [comment]
The page lists 4.0.2 as up already @ZeldaZach 
Is that not the case yet?

**Comment by ZeldaZach** [comment]
Meant to say 4.0.3 **

**Comment by tooomm** [comment]
Oh sure, kk 😄 

Couldn't verify which one is up due to https://github.com/mtgjson/mtgjson4/issues/95#issuecomment-431285885.
