### ISSUE TITLE
Legalities for CED and ICE sets

### ISSUE THREAD

**Issue by sludin** [mtgjson/mtgjson#963]
#### Version(s) tested against
MTGJSON 5.2.0+20220727

#### Description of Bug
The legalities for ICE and CED cards seem to not be correct.  For example, the ICE Black Lotus ( UUID `27580ad8-a961-5c7e-9832-001faaa3455b` ) has:

```
  legalities: {
    commander: 'Banned',
    duel: 'Banned',
    legacy: 'Banned',
    oldschool: 'Restricted',
    vintage: 'Restricted'
  },
```

What I really want to do is to show printings / prices for tournament legal cards.  For example, a future Vintage player wants to add a Mox Ruby to their deck and searches on my (also future) site and only T-Legal versions pop out.  Filtering by legalities would probably be too complicated for all cases, when at the end if the day I just want to filter out ICE, CED, and a handful of other non tournament legal sets.  It may be simpler for me to just explicitly exclude them versus having some tournament legal flag.

**Comment by sludin** [comment]
This might be a duplicate of #773

**Comment by ZeldaZach** [comment]
Appears to be a dupe as pointed out, will raise priority
