### ISSUE TITLE
Sets released over time have an inconsistent releaseDate field

### ISSUE THREAD

**Issue by KingSupernova31** [mtgjson/mtgjson#97]
Most sets that weren't released all at once, like judge promos or the celebration cards, have a release date of null. However some of them, like the Happy Holidays cards, do have a release date. (The date at which the first card from them was released.) Either way makes sense, but it should be consistent.

Also, the documentation should be updated to explain how the releaseDate of these sets is handled.

**Comment by ZeldaZach** [comment]
These dates are pulled directly from ScryFall. If there are inconsistencies, that's an upstream issue.

cc: @csuhta

**Comment by ZeldaZach** [comment]
SF won't be addressing this as they don't want to release information that is uncertain. Cards from them have a released_at tag for promos to indicate the date. 

Might consider impl that feature in the future, but this ticket is a nofix.

**Comment by KingSupernova31** [comment]
Looks like this has been fixed, all sets have a release date now. Can I rely on that staying the case?

**Comment by ZeldaZach** [comment]
I noticed they decided to publish all dates a few weeks ago. It’s implemented in 4.2, just not the website (yet). Will have website update around New Years
