### ISSUE TITLE
Dungeon tokens are missing attributes required by the AtomicCards data model

### ISSUE THREAD

**Issue by jsimpson523** [mtgjson/mtgjson#975]
#### Version(s) tested against
AtomicCards-5.2.0+20221110
#### Description of Bug
The following tokens...
- Dungeon of the Mad Mage
- Lost Mine of Phandelver
- Tomb of Annihilation
...are missing the following (required) attributes required by AtomicCards...
legalities
purchaseUrls
rulings

**Comment by ZeldaZach** [comment]
You're correct, the structure is technically broken as they're non-optionals. Will put in defaults.
