### ISSUE TITLE
Etched Foil Cards in CMR and CLB are missing TCG Pricing Data

### ISSUE THREAD

**Issue by jonathandmedina** [mtgjson/mtgjson#976]
Hello, 

I've noticed that the TCG pricing data for the etched foils in CMR and CLB is missing. It happened a while back (months ago) but I just got around to checking to make sure it wasn't my code. It looks like in the main Allprices.json file the data is just missing. You can check this card as an example of what I'm talking about: 

Ravos, Soultender - [Etched Foil] Commander Legends (CMR) -  (40946f30-4037-5350-8df6-f349cb7fb12b)

It applies to pretty much all the etched cards though. I've attached a screen shot of the json file and I'll point out in Text what I'm talking about below:

You'll notice that the TCG Player data is empty.

"40946f30-4037-5350-8df6-f349cb7fb12b": {"paper": {"tcgplayer": {"currency": "USD"}, "cardmarket": {"retail": {"normal": {"2022-08-12": 6.0, "2022-08-13": 6.75, "2022-08-14": 6.75, "2022-08-15": 6.75, "2022-08-16": 6.75, "2022-08-17": 6.75, "2022-08-18": 6.75, "2022-08-19": 6.75, "2022 

But cardmarket and other sources have data. The issue may also extend to Double Masters (2x2) Etched foils as well. Maybe TCG changed how they are offering data on Etched Foils? I'm not sure.

I appreciate your help with this. 
-Jonathan

**Comment by ZeldaZach** [comment]
Nice spotting! I have an idea on how to fix this
