### ISSUE TITLE
Split Secret Lair cards into their separate drops

### ISSUE THREAD

**Issue by arjenbrandenburgh** [mtgjson/mtgjson#977]
Currently all Secret Lair cards are together in the [SLD.json](https://mtgjson.com/api/v5/SLD.json) file, which makes sense. It would be great if the cards found in these Secret Lair Drops can have an additional field indicating in which particular drop they appeared.

For example: "Narset, Parter of Veils" with card number 1141 can be found in the "Li’l’ler Walkers" drop.

**Comment by ZeldaZach** [comment]
I like the idea! Will see what I can do on this front
