### ISSUE TITLE
implement related foil field

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtgjson#978]
It would be nice to have a way to map cards that have foil cards listed in separate entries: this is especially useful for 10E and UNH cards that have a single `finish` entry but cards are actually coupled by their collector number.

**proposal**
Introduce two fields that keep track of this mapping in the Card object
- identifiers.FoilOf: uuid
- identifiers.NonfoilOf: uuid

**implementation** *pseudocode*

for set in "Battlebond",	"Conspiracy: Take the Crown", "Fate Reforged", "Onslaught", "Tenth Edition", "Unhinged":
     if card.illustrationid == other_card.illustrationid then
         if card.isFoil()
              card.identifiers.FoilOf = other_card.uuid
         else if card.isNonfoil()
              card.identifiers.NonfoilOf = other_card.uuid

this loop is simple enough that it could be performed for any set, however there might be a few outliers that need manual mapping too

**Comment by ZeldaZach** [comment]
I like the idea! Seems relatively straight forward
